Add a hover state to sidebar panel headers
WordPress/gutenberg pull request #10070
Opened 2018-09-20 13:54 UTC by kjellr

This PR adds a hover state to sidebar panels. When a panel is closed:

- The background changes to a light gray on hover
- The text and icon change from $dark-gray-500 to $dark-gray-900

When a panel is already open, the text and icon color changes, but the background does not. 

This helps subtly differentiate collapsed panels from uncollapsed ones, and provides another visual cue reinforcement that these headers are interactive. 

This _does_ lighten the un-hovered color of these headers to our usual `$dark-gray-500` text color, but I don't think it effects their effectiveness as headers. 

## Screenshots

_Closed, default:_ 
<img width="284" alt="screen shot 2018-09-20 at 9 46 17 am" src="https://user-images.githubusercontent.com/1202812/45822747-2970d700-bcba-11e8-996c-a6f65022d490.png">

_Closed, hovered:_ 
<img width="284" alt="screen shot 2018-09-20 at 9 46 31 am" src="https://user-images.githubusercontent.com/1202812/45822791-3392d580-bcba-11e8-9e8c-b965d826ea43.png">

_Open, default:_
<img width="283" alt="screen shot 2018-09-20 at 9 46 39 am" src="https://user-images.githubusercontent.com/1202812/45822814-3b527a00-bcba-11e8-9d73-6042fc172107.png">

_Open, title is hovered:_
<img width="282" alt="screen shot 2018-09-20 at 9 46 50 am" src="https://user-images.githubusercontent.com/1202812/45822846-51f8d100-bcba-11e8-9128-df566002fb41.png">

## GIF

(The subtle background color isn't quite visible due to the compression 😕)

![sidebar](https://user-images.githubusercontent.com/1202812/45822903-7b196180-bcba-11e8-9687-912055fab180.gif)

This also works nicely alongside #10062:

![sidebar-white](https://user-images.githubusercontent.com/1202812/45822931-88365080-bcba-11e8-823a-6d01a3dc26ca.gif)

2018-09-21 07:31 UTC, jasmussen requested changes
Love it. 

We should make a few changes, then ship this. First off, the Revisions box should have the same hover:

<img width="446" alt="screen shot 2018-09-21 at 09 28 44" src="https://user-images.githubusercontent.com/1204802/45866368-da41a980-bd80-11e8-9ad8-221e61bdd274.png">

Compare:

<img width="409" alt="screen shot 2018-09-21 at 09 28 47" src="https://user-images.githubusercontent.com/1204802/45866375-ddd53080-bd80-11e8-8110-d2ad0ed4ff01.png">

I don't know if we _shouldn't_ change it here, but there's a change incoming in `update/font-picker` (not yet a PR) that changes the text color of the sidebar to be way darker, not just dark gray. This is to be consistent with headings & chevrons inside the block library.

I can be convinced otherwise, but it looks good in that branch.

2018-09-21 13:38 UTC, kjellr commented
> We should make a few changes, then ship this. First off, the Revisions box should have the same hover

✅  b023a78

> I don't know if we shouldn't change it here, but there's a change incoming in update/font-picker (not yet a PR) that changes the text color of the sidebar to be way darker, not just dark gray. This is to be consistent with headings & chevrons inside the block library.

So, interestingly enough... it looks like as of right now, the Document Sidebar panel headers have been `dark-gray-900`, but Block Sidebar panel headers (as well as the revisions header for some reason) are `dark-gray-500`: 

![artboard](https://user-images.githubusercontent.com/1202812/45883805-204a3d80-bd80-11e8-8725-17275875904c.png)

That clearly doesn't make sense. 😄 As you mention, it looks like https://github.com/WordPress/gutenberg/pull/9802 changes the block panel header color to `dark-gray-900` to fix that. 

I tried that in this branch in 13f5657. This technically _works_, but it's a little less ideal because now there's no hover state for expanded items. We could make the text lighter on hover, but that's the opposite of what happens with most of our other hover states. 

In any case, give it a try and let me know what you think. 

(Also — I realized these hover states go beyond the sidebar and effect the block picker, too! 😄 So be sure to take a look there too)

2018-09-24 06:39 UTC, jasmussen commented
I think this is pretty good!

I like the darker panel color. Also the hover seems fine in the library since we use it in a few places:

![screen shot 2018-09-24 at 08 38 28](https://user-images.githubusercontent.com/1204802/45939764-4b799a80-bfd5-11e8-9b89-cd2d4eeb7371.png)

![screen shot 2018-09-24 at 08 38 37](https://user-images.githubusercontent.com/1204802/45939766-4caac780-bfd5-11e8-8470-3960411de84e.png)

I don't think an expanded panel HAS to have that same hover, but it seems like just a matter of CSS specificity to make this work no? What makes this not work do you know?

2018-09-24 12:43 UTC, kjellr commented
> I don't think an expanded panel HAS to have that same hover, but it seems like just a matter of CSS specificity to make this work no? What makes this not work do you know?

Oh right! I tried that initially, but decided that the margins around the title bar in some expanded panels felt too uncomfortable for my taste: 

<img width="297" alt="screen shot 2018-09-24 at 8 38 01 am" src="https://user-images.githubusercontent.com/1202812/45952580-6ea44a00-bfd5-11e8-8b9f-417af7294bf2.png">

<img width="292" alt="screen shot 2018-09-24 at 8 38 14 am" src="https://user-images.githubusercontent.com/1202812/45952586-719f3a80-bfd5-11e8-9431-0c07e2caef50.png">

In those cases, it looks nice and comfortable without the gray background, but when the background is in place, the vertical margin in between the panel background and the panel content feels a little tight. That's why I explored a text-only hover state for expanded panels instead. 

In any case, give this another spin and let me know if you think those margins are uncomfortable or not in practice. I could be convinced otherwise. 🙂

2018-09-25 07:15 UTC, jasmussen approved these changes
Ship it!

2018-09-25 12:52 UTC, merged