Try: Hide gallery crop option from IE.
WordPress/gutenberg pull request #10086
Opened 2018-09-21 09:30 UTC by jasmussen

IE doesn't support object-fit for cropping using CSS.

This PR adds the ability to give a CSS classname to the toggle control, then proceeds to use that CSS class to hide it for all browsers including IE, then unhide it for modern browsers.

I wish it could be the other way around — show it for all browsers, hide it for IE. But alas there doesn't seem to be a solid CSS hack for this.

What do you think?

Screenshots. Chrome:

<img width="975" alt="screen shot 2018-09-21 at 11 26 10" src="https://user-images.githubusercontent.com/1204802/45872971-aae76880-bd91-11e8-9f6d-083aa4766a88.png">

IE:

<img width="1474" alt="screen shot 2018-09-21 at 11 26 31" src="https://user-images.githubusercontent.com/1204802/45872979-af138600-bd91-11e8-8305-4734767a2270.png">

Edge:

<img width="1500" alt="screen shot 2018-09-21 at 11 26 59" src="https://user-images.githubusercontent.com/1204802/45872983-b20e7680-bd91-11e8-9e13-d374bf9df683.png">

2018-09-21 11:32 UTC, cristian-e commented
I think that someone who is using IE and edits a gallery block, might still want to control whether or not the images will be cropped on the front-end. 
Not sure if showing/hiding block options based on the browser is a good idea.

2018-09-21 11:54 UTC, jasmussen commented
This is a solid argument, thank you. We could "dim" the control instead of hiding it altogether?

2018-09-21 12:49 UTC, cristian-e commented
If someone is using IE, toggling this control won't make any changes in the editor, so he might check the gallery on the front-end (again using IE) and see that nothing has changed, so he will think that the control is broken (doesn't do anything).

I think dimming the control will just confuse him. He won't know why that particular toggle control is dimmed.
 
Maybe just inform the user, that he's not seeing any changes in the editor because he's using a browser who doesn't support this feature (in this case object-fit). Just a tought:
![45872971-aae76880-bd91-11e8-9f6d-083aa4766a88](https://user-images.githubusercontent.com/43263346/45881205-2c032780-bdb3-11e8-9fcd-a8a2b0943787.jpg)

Of course this message will not be shown in modern browsers.

2018-09-21 13:29 UTC, aduth commented
>Maybe just inform the user, that he's not seeing any changes in the editor because he's using a browser who doesn't support this feature (in this case object-fit)

On this note, just because the user authoring the content is unable to see the effect, it doesn't seem like we should restrict them from making their content such that visitors to their site could. I can imagine that it might be difficult to explain this in the UI though.

Maybe also worth pointing out to the idea of conditionally hiding options from the editor interface is the potential for confusion if a support guide were to lead them to an option that doesn't appear in their editor.

2018-09-21 15:22 UTC, tofumatt requested changes
I don't think we should be hiding options based on browser support, but the "not supported in older browsers" subtitle idea totally gets the thumbs-up from me.

I think that's the approach we should go with. Maybe "old browsers" could be a link with a support page that outlines features we have that depend on browser tech 🤷‍♂️

2018-09-21 19:33 UTC, jorgefilipecosta commented
As a possible alternative I think we can show a small exclamation point in yellow at the side of crop images option, and when the user passed the mouse over we show a small tip saying the content is not being previewer correctly in the editor because the browser the user is using does not correctly support the needed functionality.

2018-09-25 08:15 UTC, jasmussen commented
Thanks, all, for the feedback. I don't disagree with it, and I'm adding an "in progress" label for now, and I'll revisit as soon as I get bandwidth to try the different approach.

2018-10-23 07:07 UTC, jasmussen commented
I'm going to close this for now. It's still a nice idea, but it would be nice to look at in a more holistic way, and I don't know that I'll get time for this before the big 5.0.

2018-10-23 07:07 UTC, closed without merging