Add an alternative block appender when the container doesn't support the default block
WordPress/gutenberg pull request #10136
Opened 2018-09-24 11:15 UTC by youknowriad

closes #8589

This PR adds a new block appender that trigger only when the parent block doesn't support the default block. (paragraph).

To test it, try registering this block (copy/paste to the console)

```js
wp.blocks.registerBlockType('test/container', {
	title: 'container',
	category: 'common',
	description: 'container',
	icon: 'yes',

	edit() {
		return wp.element.createElement(wp.editor.InnerBlocks, {
			allowedBlocks: ['core/image', 'core/gallery']
		});
	},

	save() {
		return wp.element.createElement(wp.editor.InnerBlocks.Content);
	},
})
```

2018-09-24 11:31 UTC, jasmussen commented
I love it. 

GIF:

![new appender](https://user-images.githubusercontent.com/1204802/45949937-f7cf7700-bffd-11e8-9a8c-ad6fdb72272e.gif)

Can you make it so it has a dashed outline like https://user-images.githubusercontent.com/1204802/44717667-f4f46b80-aabd-11e8-890d-d86f19cf3cea.png? That sort of implies where the boundaries of the inserter block will be.

Also, can you make it so the entire block is clickable? Sort of like how it is in the gallery?

![gallery](https://user-images.githubusercontent.com/1204802/45950001-32d1aa80-bffe-11e8-98cf-1b35defc8ab9.gif)

Nice work! 👍 👍

2018-09-24 12:01 UTC, chrisvanpatten commented
I love this!

I'd also kill for filters…

1. a filter to say "use the alternate block appender all the time" — useful if you're dealing with a post type that is primarily about layout, not textual content (I can think of a few cases where I'd use this)
2. a filter to replace the appender with something custom. You could use it to build some super cool contextual inserter experiences specific to a particular post type.

Overall, awesome and super excited for this.

2018-09-24 15:05 UTC, tofumatt requested changes
I noticed that I can still insert the default block even though it's not listed as an allowed type:

![2018-09-24 15 27 05](https://user-images.githubusercontent.com/90871/45958226-cdd28080-c00e-11e8-929a-9e80c3ea0e1d.gif)

I guess that's true of the existing implementation, right? Do we consider that a bug?

Anyway, code looks mostly good, just some minor tweaks. Tested in IE 11 and seems good there too; I wanted to test there because some flex stuff can be weird there, but it all seemed good.

Might be a good case for an E2E test as this is might not be something routinely tested by us in development.

-----

My only issue is the block appender seems like it should have a larger click target:

![2018-09-24 16 03 50](https://user-images.githubusercontent.com/90871/45960199-94e8da80-c013-11e8-8c84-3547cab588e3.gif)

It seems annoying to have to move my mouse to the centre; that's a tiny click target and we could expand it to the whole area.

2018-09-24 16:33 UTC, youknowriad commented on packages/editor/src/components/block-list-appender/index.js
> +					lastBlockClientId={ last( blockClientIds ) }
FWIW, last also avoids dealing with specific cases (an empty array). I mean `([])[-1]` does return undefined but I don't know if I trust it to not raise errors in all JavaScript contexts

2018-09-25 12:20 UTC, youknowriad commented
@jasmussen I tried tweaking the design as suggested, feel free to polish further.

2018-09-25 13:30 UTC, chrisvanpatten commented
@youknowriad I think a post-type level setting would be a nice alternative over a filter too. The main thing is that the default paragraph appender isn't always the best user interface when dealing with certain types of content, even in cases where the paragraph is an allowed block, and it would help to allow developers to be explicit about that rather than depending on Gutenberg to infer it.

2018-09-26 09:09 UTC, youknowriad commented
> I noticed that I can still insert the default block even though it's not listed as an allowed type:

This is definitely a bug, good catch, I created a specific issue for it https://github.com/WordPress/gutenberg/issues/10186

2018-10-04 12:35 UTC, youknowriad commented on packages/editor/src/components/block-list-appender/index.js
> +					lastBlockClientId={ last( blockClientIds ) }
I'm keeping it as a personal preference for me. But let me know if you feel strongly about it.

2018-10-04 13:48 UTC, jasmussen commented
I pushed a small tweak to the visuals:

![tweaks](https://user-images.githubusercontent.com/1204802/46478283-9d32d980-c7ba-11e8-99b8-d5aaea30c044.gif)

2018-10-04 15:48 UTC, tofumatt approved these changes
Tested locally and the bigger click target is *much* nicer, thanks!

Looks good to me! 👍

2018-10-04 15:48 UTC, tofumatt commented on test/e2e/specs/container-blocks.test.js
> +			element.value = element.value.replace( blockDelimiter, _paragraph + blockDelimiter );
(I know this is unrelated to your patch, but I'ma make the change because it's nicer.)

2018-10-04 16:10 UTC, youknowriad commented
Thanks for the tweaks :)

2018-10-04 16:10 UTC, merged

2018-10-05 13:15 UTC, chrisvanpatten commented
@youknowriad @jasmussen Would it make sense for this new appender design to apply to the Gallery image appender as well? I could see it being nice to have the same design since they are similar UIs, same icons, etc. Happy to open a PR if so :)

2018-10-05 13:30 UTC, jasmussen commented
> @chrisvanpatten Yes, it does. I think the component is different but the design should definitely match. Some explorations are happening here #9682

> @youknowriad Oh cool, I'll let those explorations proceed then! 👍

I actually think those explorations, although on a PR, have somewhat stalled. So Chris if you have an ocean of bandwidth and desire to contribute, I can offer you an emoji medal for it, and I would suggest you work off of the mockups present here: https://github.com/WordPress/gutenberg/pull/9682#issuecomment-425435709

An interim step can be as little as the visual styles, and a bigger step could be adding the additional button. But just to be clear, don't let that pull request block you from making one yourself!

2018-10-24 20:52 UTC, aduth commented on packages/editor/src/components/inserter/index.js
> +			insertionPoint: {
We should almost never want to create a new object to be returned as a value of `mapSelectToProps` return value object.

See: #11028