Set multi select copy content + better selector names
WordPress/gutenberg pull request #1013
Opened 2017-06-03 12:27 UTC by iseulde

This PR enables copying content from a multi selection. To test, select some blocks, and verify that the clipboard data contains the serialised block content.

It also renames some selectors, which hopefully makes things clearer, and fixes a bug in the inserter where a block would be inserted at the wrong position for bottom-to-top selection.

2017-06-03 12:29 UTC, iseulde commented
If anyone finds any better names, feel free to suggest. :)

2017-06-05 17:31 UTC, aduth requested changes
- Do you have plans for a future "paste" handling pull request?
- How can I cut/copy a single block?

2017-06-05 17:31 UTC, aduth commented on editor/modes/visual-editor/block-list.js
> +		document.removeEventListener( 'copy', this.onCut );
Should be `'cut'`, not `'copy'`

2017-06-05 17:32 UTC, aduth commented
Warning on missed selector rename:

```
WARNING in ./editor/inserter/menu.js
387:26-46 "export 'getBlockSelectionEnd' was not found in '../selectors'
```

2017-06-05 18:07 UTC, iseulde commented
@aduth These are specifically for multi-selection. Paste will we quite a bit of work to get right in and outside blocks, but yeah I'll try to address in a separate PR. Regarding copy, would you expect to get the whole block copied when a block is selected and there is a collapsed selection? I don't see what could be wrong with that as nothing would happen by default. :)

2017-06-05 18:11 UTC, jasmussen commented
Cut, copy and paste will be very cool, and the multi select stuff feels born for it.

But it's probably something we should push a bit head of us, especially if it's a lot of work. It's one of those "plus" features that will be really nice to add once everything else is in place and solid.

2017-06-05 18:14 UTC, iseulde commented
Sure. Copy and cut are easy to handle. Note that this PR renames a few things as well. Paste is quite a bit more complicated. :) I don't mind to defer that one.

2017-06-06 19:41 UTC, aduth commented
I'm still a bit unclear on the purpose of these changes then if we're not looking to pursue paste in the near-term. What use case is this satisfying?

2017-06-06 20:26 UTC, iseulde commented
I thought this is something we eventually want. If not, feel free to close the PR.

2017-06-07 07:44 UTC, jasmussen commented
> I'm still a bit unclear on the purpose of these changes then if we're not looking to pursue paste in the near-term. What use case is this satisfying?

To step back a bit, my suggestion to postpone work on _paste_ isn't because I don't like the feature, I think it's potentially cool. But I do get the sense that it's a very difficult undertaking, which if true means we should prioritize it lower than the items in the beta milestone: https://github.com/WordPress/gutenberg/milestone/7

2017-06-08 14:53 UTC, aduth approved these changes
👍

2017-06-10 11:37 UTC, merged