Install `phpcs` using Composer
WordPress/gutenberg pull request #1022
Opened 2017-06-05 15:26 UTC by nylen

From https://github.com/WordPress/gutenberg/pull/986#discussion_r119979875, another way to install `phpcs` and `WordPress-Coding-Standards` is via `composer`.  This PR explores this option.

Still left to do:

- [ ] Get rid of the `phpcs --config-set` call, if possible
- [ ] Simplify the Travis CI configuration accordingly

2017-06-05 21:23 UTC, westonruter approved these changes

2017-06-05 21:41 UTC, westonruter commented
✅

2017-06-06 00:03 UTC, ntwb requested changes
Add one request please :)

2017-06-06 00:03 UTC, ntwb commented on .editorconfig
> +[{package.json,.travis.yml,composer.json}]
How about `[{*.json,.travis.yml}]` so it also covers `.eslintrc.json` and any other `.json` files?

2017-06-06 00:40 UTC, westonruter commented on .editorconfig
> +[{package.json,.travis.yml,composer.json}]
Done. This aligns better with core: https://github.com/WordPress/wordpress-develop/blob/4.7.5/.editorconfig#L16-L18

The `package.json` should be updated to use 2-space indents.

2017-06-06 00:41 UTC, westonruter commented on .editorconfig
> +[{package.json,.travis.yml,composer.json}]
I mean, the `.eslintrc.json`

2017-06-06 00:42 UTC, ntwb approved these changes
✅

2017-06-06 00:49 UTC, ntwb commented on .editorconfig
> +[{package.json,.travis.yml,composer.json}]
Done in #1029

2017-06-06 02:16 UTC, merged

2017-06-06 02:16 UTC, nylen commented
Thanks for the fixes & improvements here!