Fix overscroll issues locking scroll up on long pages.
WordPress/gutenberg pull request #10227
Opened 2018-09-28 08:25 UTC by jasmussen

This, I think, fixes #8603.

I wasn't able to reproduce the exact issue, but I was able to reproduce a different one which I think is the same minus some browser behavior differences.

Essentially, when you don't scroll the `body` but instead scroll an element, once you've scrolled to the end of that element, pause, and then try to scroll further, browsers now try to scroll the _parent_ element, in this case `body`. But because that isn't scrollable, some browsers apply an "overscroll bounce", others just prevent scrolling, even upwards.

Steps to reproduce:

1. Have a page with enough content to create a scrollbar.
2. Scroll to the very end of that content.
3. Hold a brief pause in scrolling.
4. Now in one motion first scroll downwards and then immediately start scrolling upwards.

Observe that you're not scrolling anywhere, or you're invoking overscroll bounces.

Step 4 is crucial — it is BECAUSE we start by scrolling _downwards_ that the browser decides to try and scroll the body element instead of the element we mean to scroll (`.edit-post-layout__content`), and because the body can't be scrolled, this is causing the issue.

This PR fixes that.

This POTENTIALLY also fixes issues reported in https://github.com/WordPress/gutenberg/issues/8383#issuecomment-424998603.

2018-09-29 13:14 UTC, tofumatt commented
To be clear: this bug only exists in Blink/WebKit-based browsers from my testing. This bug doesn't happen at all on Firefox in MacOS because it doesn't rubber-band when scrolling past the end of content.

So to reproduce you at least need Chrome or Safari on MacOS. Maybe it happens elsewhere, but not in my testing.

2018-09-29 13:17 UTC, notnownikki commented
I couldn't reproduce the original issue, so can't comment on this one, sorry

2018-09-29 13:22 UTC, tofumatt requested changes
While this bug happens in both Chrome and Safari, it seems the fix only works in Chrome.

Chrome:
![2018-09-29 14 17 39](https://user-images.githubusercontent.com/90871/46246241-82dfb100-c3f2-11e8-8118-7cb0fc4b15e4.gif)

Safari:
![2018-09-29 14 17 21](https://user-images.githubusercontent.com/90871/46246242-83784780-c3f2-11e8-9a8a-1272489f682e.gif)

So it's better than before, but presumably this bug exists on mobile Safari too and wouldn't be fixed if not fixed on desktop. I'm on a plane right now so can't really test on my actual phone... but I think this needs more work to fix it across browsers.

Looks like [Safari doesn't support this CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-y#Browser_compatibility)... is there something else we can use to get this working on Safari? I guess if not it makes sense to ship this for at least Chrome users.

2018-09-29 13:26 UTC, tofumatt approved these changes
Actually, looks like Safari isn't supporting this anytime soon and it's just hacks to fix it.

Let's get this in to fix Chrome and mobile Firefox. https://caniuse.com/#feat=css-overscroll-behavior says Edge will support it out-of-the-box soon too.

2018-09-30 10:28 UTC, jasmussen commented
Thanks for the sanity check. This is a good start, I agree.

2018-09-30 10:28 UTC, merged