Detect oEmbed responses where the oEmbed provider has gone away
WordPress/gutenberg pull request #10467
Opened 2018-10-10 08:48 UTC by notnownikki

## Description

Some embed providers still listed in core's allowed list are no longer valid. Either the third party's API endpoint has changed, or support has been removed completely.

In these cases, oEmbed returns a different response, and doesn't do the link fallback behaviour. This PR updates for those cases.

Also, it moves the logic of what is a valid preview and what couldn't be embedded out of the edit component.

## How has this been tested?

Try to embed the following URLs where oEmbed has an incorrect API endpoint for the provider:

http://i294.photobucket.com/albums/mm102/magiciansteven/hel512_22.jpg
https://www.reverbnation.com/collection/186-mellow-beats
https://www.amazon.com/Maxboost-Protector-Tempered-Advanced-Accurate/dp/B073DLZWX7

Try to embed this WordPress page that can't be embedded:

https://wordpress.org/gutenberg/handbook/

Try to embed this invalid Twitter URL:

http://twitter.com/ufidosufdisofudisoufio

Embed this valid URL:

https://twitter.com/notnownikki

## Types of changes
Bug Fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

2018-10-10 11:03 UTC, tofumatt requested changes
Seems legit, but the steps to test here read like they'd make an excellent E2E test. Is it possible to add an HTML page that would allow an oEmbed we could use to test (so the tests didn't require an outside connection)? If so that's worth adding (I guess even an HTML copy of a page with valid oEmbed data.)

If this isn't urgent I'd say we should add tests before merging. If it's urgent I'll cave 😉

2018-10-10 11:09 UTC, notnownikki commented
@tofumatt agreed, I'm writing the E2E test now. I'll put this as In Progress and add it to this PR.

2018-10-10 12:28 UTC, notnownikki commented
To test as much as possible, we need to at least make the call to the embed proxy endpoint. I've added an e2e test that intercepts it and returns html that won't cause errors in the console, in the same way we have to for the demo page test.

The new e2e test makes sure that the embed block switches to the correct block based on the URL, aspect ratio class is applied to the embed with a fixed height/width iframe, and that embeds that can't be embedded end up back in the edit state.

2018-10-15 10:58 UTC, notnownikki commented
e2e test is in this PR now

2018-10-15 11:34 UTC, tofumatt approved these changes
It'd be nice to file a follow-up issue that maybe checked for network connectivity in general or something to skip these tests (and alert the user to why) in the future. 😄

Looks good to me though, let's 🚢

2018-10-15 11:34 UTC, tofumatt commented on test/e2e/specs/embedding.test.js
> +	await newPost();
I might move this to `setUp()`, but that's about it.

2018-10-15 12:19 UTC, merged

2019-02-06 18:47 UTC, aduth commented on test/e2e/specs/embedding.test.js
> +/**
The "blocks" folder didn't exist at the time these tests were introduced, but at this point this file would be better placed as `specs/blocks/embed.test.js`.