Columns Block: Make responsive, make editor and theme match
WordPress/gutenberg pull request #10541
Opened 2018-10-12 09:03 UTC by jasmussen

This PR does a number of things.

1. It fixes #7818 by making sure the editor view and theme view are the same, dimension wise. It also adds some margin betweeen columns. 
2. It fixes #6048 by adding basic responsiveness. Essentially mobile has 1 column, beyond mobile has 2, beyond "medium" (782 breakpoint) we show whatever the user has set it to, i.e. 3 or up to 6.
3. It refactors the margins and paddings of the columns block to "level the playing field" between editor and theme, basically making the dimensions the same. This involved making the column (singular) block essentially lose its visual block padding and footprint. 

Editor:

![screenshot 2018-10-12 at 10 52 25](https://user-images.githubusercontent.com/1204802/46859408-f976a880-ce0d-11e8-9994-0f7d01602f9f.png)

Theme:

![screenshot 2018-10-12 at 10 53 16](https://user-images.githubusercontent.com/1204802/46859414-fb406c00-ce0d-11e8-841f-9c586fc14f0d.png)

Dimensions:

![columns](https://user-images.githubusercontent.com/1204802/46859433-05fb0100-ce0e-11e8-801b-0d2e27ebdd11.gif)

Responsive:

![responsive](https://user-images.githubusercontent.com/1204802/46859457-14491d00-ce0e-11e8-9be5-7e202ddf6a88.gif)

There is some overlap with the column blocks due to the fact that this PR makes them more or less lose their footprint, which makes the hover outlines overlap at times. Perhaps the longer term fix here is to make those blocks actual pass-through blocks so they don't have hover outlines, or can be selected. But in the mean time, this PR intends to make the columns block ship-ready for 5.0. 

Please test it thoroughly and decide if you agree!

2018-10-13 04:34 UTC, GlennMartin1 commented
> But in the mean time, this PR intends to make the columns block ship-ready for 5.0.

Perhaps this PR would be the appropriate time/place to remove the Beta designation?

i.e. change **Columns (beta)** to **Columns**.

2018-10-16 12:16 UTC, gziolo commented
This is what I see in this branch:

6 columns:
![screen shot 2018-10-16 at 14 15 33](https://user-images.githubusercontent.com/699132/47015716-fbae6f00-d14d-11e8-9f63-36d5ad4e0ca1.png)

2 empty columns:
![screen shot 2018-10-16 at 14 16 28](https://user-images.githubusercontent.com/699132/47015758-200a4b80-d14e-11e8-9742-60ac0253a6bd.png)

2018-10-16 12:30 UTC, gziolo commented
I will double check later, I just leave my observations since we removed `beta` I'm doing more detailed review :)

2018-10-16 12:45 UTC, gziolo commented
I can confirm that the issues I shared are regressions. This is how they look in `master`:

6 columns:
![screen shot 2018-10-16 at 14 44 58](https://user-images.githubusercontent.com/699132/47017259-14b91f00-d152-11e8-9d91-833869f5ed4d.png)

2 empty columns:
![screen shot 2018-10-16 at 14 43 30](https://user-images.githubusercontent.com/699132/47017271-1a166980-d152-11e8-8846-f55d07a0860b.png)


![screen shot 2018-10-16 at 14 43 30](https://user-images.githubusercontent.com/699132/47017202-f05d4280-d151-11e8-93aa-cb98f4b4b20b.png)

2018-10-16 13:23 UTC, gziolo requested changes
See my previous comments

2018-10-16 13:36 UTC, sarahmonster commented
I'm getting totally lost trying to sift through the columns here and to suss out what CSS is targeting what. I don't think this is a regression—I've gotten painfully lost every time I've tried to test the columns block, but it's making it super difficult for me to provide helpful feedback and/or suggestions here.

I'm seeing a lot of overlapping elements:

<img width="599" alt="screenshot 2018-10-16 13 36 20" src="https://user-images.githubusercontent.com/376315/47017390-08c95f00-d14a-11e8-9c28-daa05dcb10f7.png">
<img width="693" alt="screenshot 2018-10-16 13 36 42" src="https://user-images.githubusercontent.com/376315/47017391-08c95f00-d14a-11e8-8aea-3cba8d21ffca.png">
<img width="576" alt="screenshot 2018-10-16 13 36 54" src="https://user-images.githubusercontent.com/376315/47017392-08c95f00-d14a-11e8-8c08-f84778d2c1c5.png">
<img width="608" alt="screenshot 2018-10-16 13 43 50" src="https://user-images.githubusercontent.com/376315/47017393-0961f580-d14a-11e8-8792-25227ce37fea.png">

I'm not sure if this is intended behaviour, but it's contributing to the overall feeling of lost-ness.

Hiding all the placeholder content (so both "Write your story" and "Add text or type / to add content") would help clean things up a bit, since this seems to pop up all over the place and often in unexpected spots.

I can't select the ellipsis menu for any of the individual columns at the right, or those columns that are below another column block, and I have a lot of difficulty selecting the parent column block:

![2018-10-16 13 50 46](https://user-images.githubusercontent.com/376315/47017640-b3da1880-d14a-11e8-9d09-65b1fd4dfb23.gif)

What's the rationale behind making each individual column selectable, as well as the parent column? Is this an extensability thing, or is it just so you can apply CSS classes to the columns individually? Can we simplify by removing this ability? Would it make sense to include a hairline outline of the columns, so that people could explicitly see the column structure at work and better understand where each column begins and ends?

Using an embed block seems to break the columns out of the editor window:

<img width="888" alt="screenshot 2018-10-16 14 02 47" src="https://user-images.githubusercontent.com/376315/47018329-737b9a00-d14c-11e8-8e0a-68b836c97012.png">

Columns don't span the full width of the screen if the content in them is short—this may also be by design, but I would have expected a full-width sort of deal here:

<img width="690" alt="screenshot 2018-10-16 14 36 19" src="https://user-images.githubusercontent.com/376315/47020244-dec76b00-d150-11e8-90f7-e61f8591c669.png">

I'm not certain how much of this is helpful or specific to this PR at this stage, but I can test a bit more later today to see if I can't suss out some of these issues in more detail. Offhand, I wonder if using grid instead of flexbox might make some of these behaviours a bit more consistent and reliable.

2018-10-16 17:07 UTC, ZebulanStanphill commented
This issue exists on `master`, but it looks like the `min-width` value of some things are causing issues with the column widths. For example, this embed placeholder has a `min-width` that causes its column to become bigger than it should be:

![image](https://user-images.githubusercontent.com/19592990/47033934-a36e7180-d13b-11e8-8c9d-cf2407dee8cb.png)

2018-10-16 17:50 UTC, sarahmonster commented
Yep, that's what happening here. Since it isn't a regression it's probably not strictly important to fix here. I tried fixing it by applying an `overflow: hidden` rule to the container column, but that meant that the toolbar for blocks would then get cut off. Apparently there's a way to [pop things outside an overflow container](https://css-tricks.com/popping-hidden-overflow/), but it relies on relative positioning, which the toolbar doesn't use, and seems like it might be at best a pretty fragile solution.

2018-10-16 17:53 UTC, tofumatt commented
> What's the rationale behind making each individual column selectable, as well as the parent column? Is this an extensibility thing, or is it just so you can apply CSS classes to the columns individually?

As the parent column is also a block, it needs to be selectable for accessibility reasons (keyboard nav) but also so you can select it to change settings.

Some of these seem less regressions since they work on master. There is a *lot* of stuff to test here. 😒

@sarahmonster showed me (in-person) thus far the only fix that consistently works needs to be applied high enough in the DOM that it clips the block toolbar 😢

2018-10-16 17:55 UTC, jasmussen commented
The tricky thing here is that UI freeze is tomorrow. If we can get this in, we can fix bugs later. If we don't get this in, I'm not sure.

The css here is complex, and the block as a whole needs love in phase 2. However for basic things it's hugely valuable.

If we feel this PR improves what's in master and doesn't introduce new issues, I feel it's worth merging as an iterative improvement and then track anything missing.

@mtias any thoughts?

2018-10-16 18:00 UTC, tofumatt commented
I am usually for improvements without regressions. Columns block in general though needs more work I think. I'd rather leave a beta label and :shipit:

2018-10-16 18:45 UTC, ZebulanStanphill commented
The Columns block is, for non-technical-users, almost entirely useless with responsive columns, so I say merge this if there are no regressions but leave the (Beta) label until the block becomes less buggy.

What exactly does "UI freeze" mean?

2018-10-16 21:01 UTC, sarahmonster commented
Responsiveness = totally an improvement. I'm on board with "ship it now, fix it later".

2018-10-17 04:31 UTC, jasmussen commented
This one actually is responsive. But I'm okay with adding back the beta label.

2018-10-17 21:39 UTC, karmatosed commented
I would +1 to adding back in beta or whatever it takes get this in as responsive. It's asked for a lot in feedback and feels like a win.

2018-10-18 11:11 UTC, gziolo commented
Added https://github.com/WordPress/gutenberg/pull/10541/commits/1ca6139b8f9b5685d372f5989e0ade1db397b29c

Before
![screen shot 2018-10-16 at 14 16 28](https://user-images.githubusercontent.com/699132/47015758-200a4b80-d14e-11e8-9742-60ac0253a6bd.png)

After:
![screen shot 2018-10-18 at 13 09 58](https://user-images.githubusercontent.com/699132/47150618-617a3280-d2d7-11e8-8735-77871be48fec.png)

2018-10-18 11:14 UTC, gziolo commented
## Before

Editor:
![screen shot 2018-10-18 at 13 14 28](https://user-images.githubusercontent.com/699132/47150713-c3d33300-d2d7-11e8-8c35-0fb055450739.png)


Frontend:
![screen shot 2018-10-18 at 13 13 33](https://user-images.githubusercontent.com/699132/47150694-aa31eb80-d2d7-11e8-90c3-b997e508cec6.png)

2018-10-18 11:50 UTC, gziolo approved these changes

2018-10-18 11:51 UTC, gziolo commented
I added some tweaks to the PR. There are still some outstanding issues on the mobile view. However they aren't related to the responsive mode at all. See screencast recorded on `master` branch which has the same issue:

![columns](https://user-images.githubusercontent.com/699132/47152393-dd2aae00-d2dc-11e8-8a20-c2364dafb93e.gif)

2018-10-18 12:21 UTC, merged

2018-10-18 12:29 UTC, jasmussen commented
♥️♥️♥️♥️

2018-10-22 17:32 UTC, paaljoachim commented
Looks good! I have a few minor things that I noticed...
Adding a column block the focus goes to paragraph block inside the columns block and not the column block setting.
The user has to nudge the mouse cursor around to find the border of the column block to be able to select the column block setting. Should the column block because it is a container have a thicker border to give a signal of a difference in block? As blocks that have another block inside could have thicker borders. Visually one can see the difference by just looking at the thickness of the border outlines. 

Inserting a block inside the column is not done so on the left side as it the usual approach but on the right side. It would be good to keep it consistent.