Silence PHP errors on REST API responses
WordPress/gutenberg pull request #10606
Opened 2018-10-15 00:46 UTC by earnjam

This is a test of the method discussed on #10476 and https://core.trac.wordpress.org/ticket/44534 to prevent PHP errors and warnings from mangling JSON in REST API responses.

The method here is the earliest we can possibly check for and silence errors. Ideally we would add this header check to core inside of `wp_debug_mode()`. 

We could call `wp_debug_mode()` on `rest_api_init`, but that is further along in the request and there are a bunch of opportunities for plugins/themes to emit errors while loading. 

This method in Gutenberg would essentially leave the window for errors to the loading of mu-plugins, network activated plugins in multisite, and any plugins that come before `Gutenberg` alphabetically. Any errors emitted by later alphabetically ordered plugins loading, hooks/filters and the theme would be silenced.

Fixes #10476 
Related #10492

2018-10-15 07:12 UTC, mtias commented
Could this help with https://github.com/WordPress/gutenberg/issues/8935 or we need to dig deeper there to see if there's anything else amiss?

2018-10-15 11:09 UTC, danielbachhuber approved these changes

2018-10-15 11:10 UTC, danielbachhuber commented
> Could this help with #8935 or we need to dig deeper there to see if there's anything else amiss?

At first glance, #8935 seems to be a server configuration issue specific to uploading media.

2018-10-15 13:54 UTC, danielbachhuber requested changes

2018-10-15 13:54 UTC, danielbachhuber commented on lib/rest-api.php
> +	if ( ! empty( $_SERVER['CONTENT_TYPE'] ) && 'application/json' === $_SERVER['CONTENT_TYPE'] ) {
As it turns out, we may also need to inspect `HTTP_ACCEPT` in addition to `CONTENT_TYPE`: https://core.trac.wordpress.org/ticket/44534#comment:18

2018-10-15 21:46 UTC, danielbachhuber approved these changes

2018-10-15 21:47 UTC, danielbachhuber commented
Thanks @earnjam !

2018-10-15 21:47 UTC, merged

2018-10-18 12:51 UTC, mtias commented
Thanks for the work here!