Add "custom" as selectable option in the font size picker
WordPress/gutenberg pull request #10687
Opened 2018-10-17 13:00 UTC by chrisvanpatten

This PR adds "Custom" as a selectable option in the font size picker and hides the font size text input unless Custom is selected.

The intent here is to disconnect the font size names from pixel values. The pixel values are only used in generating the preview in the Dropdown, and may not map to the actual size applied via CSS, as users may use relative units (em, rem, etc.) in their stylesheet.

When "Custom" is selected the user can enter any numeric value, as before and it will map to an inline `style` attribute.

## Screenshots

![font-sizes](https://user-images.githubusercontent.com/1231306/47087621-79c05380-d1ea-11e8-9e5f-28caa4b59b15.gif)

## Caveats

The only caveat right now is that if you type in a number that corresponds to a pre-defined font size (e.g. `16` or `20`), it reverts to use the corresponding pre-defined font size in the Dropdown. I think this is okay — it's still a better experience than before — but a follow up to this (as part of the API freeze, I think) would be to determine the selected font size via slug matching, not value matching.

Relates to #7761, #9549, #8689, and some others.

2018-10-17 13:02 UTC, chrisvanpatten commented
Design notes: I originally had "Custom" at the top of the dropdown, but moved it to the bottom. Truthfully I'm split on which is better (top or bottom). Luckily it's easy to change if desired :)

2018-10-17 13:18 UTC, chrisvanpatten commented
I think as a path forward for slug matching, the component will need to be updated to expect a slug OR an entire font size object as its `value`, e.g. here:

https://github.com/WordPress/gutenberg/blob/e7d674dc5ee245a41a8c2e9fac88a021dbaded32/packages/block-library/src/paragraph/edit.js#L163

Then we can assume a direct numeric value is a custom value and stop trying to automatically map numbers to the pre-defined sizes.

2018-10-17 13:19 UTC, chrisvanpatten commented
(Also I know the tests need to be updated… working on that next)

2018-10-17 13:34 UTC, chrisvanpatten commented
Removing reviews as I encountered some issues I need to work on…

- [ ] Realised that updating to map via slug is pretty much a pre-requisite for merging this
- [ ] It may be beneficial to provide a default size when "custom" is selected
- [ ] Rather than a dedicated button it might be worth updating the `fontSizes` array to include a "custom" option, store it/handle it the same way as other font sizes, and additionally save a separate `customFontSize`

2018-10-17 14:56 UTC, ZebulanStanphill commented
I like this change! I agree that determining whether or not to use a class vs. inline styles should not depend on the value, but whether you set the font using the preset options or you chose <samp>Custom</samp>.

Considering accessibility, putting <samp>Custom</samp> at the start of the list seems like it would make more sense than down at the bottom?

2018-10-17 17:34 UTC, chrisvanpatten commented
I made some changes so we're now matching font sizes in attributes to the pre-defined font sizes via `slug` instead of `value`.

This fully decouples the custom and pre-defined fonts. The size values provided in the `add_theme_support( 'editor-font-sizes' );` array are now exclusively used for setting the visible size in the dropdown and have no other meaning.

Previously, if you entered a value in the custom size input/range slider that matched one of the pre-defined size values, the Dropdown would update to that option. This was problematic because the CSS for the class may be relative, use different units, etc., leading to a disconnect between the numeric size and the actual output.

This solves a lot of the UX problems but does expose an issue which is that when "resetting" a font size (aka setting font size to "undefined" and removing the CSS class/block attribute setting), we essentially map that to a "normal" slug. This was previously the case but is arguably a bigger issue now. So if you define an editor-font-sizes array without a font size with the "normal" slug, it creates problems.

One basic idea would be to always inject the "Normal" size into the `fontSizes` array, no matter what the user sets inside `editor-font-sizes`.

I'd love technical feedback on that before continuing!

2018-10-17 18:47 UTC, chrisvanpatten commented
_Another refactor in progress to try to make the component a little dumber, and put some of the editor-specific logic into the editor package. Nothing to see here…_

2018-10-17 19:41 UTC, chrisvanpatten commented
I still need to update the failing tests but this is in a better place.

I think the only lingering question is about how to handle the concept of the "default" size.

I've removed specific hard-coded references to the `normal` default into the `editor` package so at least the component itself is isolated from any specific sizes so it's easier to re-use, but we could still look at appending a "Normal" font size if one isn't provided in the editor package when we pull in the font sizes via `wp.data.select`.

2018-10-18 02:01 UTC, chrisvanpatten commented
Finally got the tests to pass! Would love a review on this! ❤️

2018-10-18 17:51 UTC, aduth commented
This seems like something which would need to be included in a UI freeze. Milestoning as such for 4.1.

2018-10-18 17:56 UTC, chrisvanpatten commented
I'm working on a small refactor now with a goal toward simplifying the API, but should be able to wrap it up this afternoon. I'd really love to get this landed pre-merge, if possible!!

2018-10-18 19:06 UTC, chrisvanpatten commented
Okay, I've taken this as far as I can — reviews are now greatly appreciated.

Truthfully I feel the font size components could be simplified further but I'm afraid to rock the boat too much. However I'm more than open to additional ideas there.

2018-10-19 13:11 UTC, chrisvanpatten commented
I've got it back in action! Tests are passing! Review me plz! <3

2018-10-22 19:17 UTC, karmatosed commented
I'd like to step back a little and think about the flow here. Whilst I see a need to guide to a 'custom' font size being possible, I have to say having it appear at the bottom seems a little lost and confusing as an experience. I know it's fixing potentially a bug of not saving sizes when you do edit, but is this the only option? @jasmussen for some insights into this as know likely you have thoughts on inputs like this.

2018-10-22 19:17 UTC, karmatosed requested changes
As commented, we need to think about the position of this and what the experience is like.

2018-10-22 19:43 UTC, chrisvanpatten commented
@karmatosed I should have updated the screenshot as I moved Custom to the top :) 

My main concern is de-emphasising the relationship between pixel values and the font size values. We show pixel sizes in UI no matter what — even if the font size CSS itself uses an `em` or `rem`. This is misleading to users who may expect a certain size to be applied when the theme itself does not actually apply that size.

2018-10-22 20:15 UTC, karmatosed commented
> I should have updated the screenshot as I moved Custom to the top :)

I think at the top this is even more distracting possibly as a UI. It's the word outside of those that to me feels not as fitting. I'd be super interested if others feel the same. Are there any other UIs you can lean into where they have this?

2018-10-22 20:20 UTC, chrisvanpatten commented
Here's an updated screen capture, just for reference:

![font-sizes-2](https://user-images.githubusercontent.com/1231306/47316890-34e75300-d616-11e8-95a7-326f781ca166.gif)

> Are there any other UIs you can show where they have this?

I think the challenge here is that typically you'd have _only_ named font sizes, or _only_ numeric font sizes. We're trying to do _both_ with this UI, which is — as far as I know — new territory.

2018-10-22 20:31 UTC, chrisvanpatten commented
@ZebulanStanphill to the rescue, filling in for my lack of page builder UI knowledge 😂💖

2018-10-23 09:00 UTC, karmatosed commented
Thanks for the example. That sort of confirms to me we have maybe a few issues here:

- Default and custom make sense as binary options, we have multiples.
- Combining both types of UI into one is somewhat confusing.

What other options do we have?

2018-10-23 09:11 UTC, jasmussen commented
Thanks for your ongoing work here. I have to support with @karmatosed, the addition of the "custom" text to the dropdown feels a little bit awkward because it's not sized like the other labels.

I hate to be blunt, so please read the following knowing that I deeply appreciate your work and your desire to fix these issues. I kind of feel like `master` works both better than this branch, and okay on its own:

- When text isn't customized, there's a checkmark next to "Normal"
- When you type in a number, the collapsed dropdown says "Custom". It's not an option in the dropdown, but no items in there have checkmarks either.

I understand that the problem this is trying to solve is the disconnect between the "Custom" label on the button, and the lack of that "custom" in the dropdown itself. But this feels to me like it's comparable to an "unknown state" of a checkbox. For example when you have a treeview with checkboxes, and you have one child checkbox unchecked, another one checked — the parent checkbox then shows sort of a grayed/filled state. In this case, simply making the "Custom" label on the button italic, seems like it could be sufficient to imply that it's a third state.

2018-10-23 09:15 UTC, karmatosed commented
For now, I am going to remove the milestone on this. That's not at all to say something can't be worked on and a milestone added back in. I would encourage you @chrisvanpatten to explore this milestone or not. Working out with space what the problem being solved is will more likely come up with a robust solution. Thanks for all the work done, please don't stop as it's great to explore new possibilities and iterations.

2018-10-23 11:29 UTC, chrisvanpatten commented
Thanks everyone for the feedback. In the interest of time I'm going to close this and hopefully revisit in the next phase.

For my future self, and for future historians, here's a small random brain dump:

+ The current font picker implies a link between a numeric size (rendered in pixels, even though the UI never mentions pixels) that might not exist because the theme could provide different sizing in their classes (either with different units, or with different numeric values entirely)
+ Trying to automatically map numbers to named font sizes is especially problematic in this case because it means that the numbers linked to named font sizes are effectively unavailable for "custom" sizing, even though we can't guarantee that the number you enter is actually going to be the result.
+ Allowing users to provide units in their `editor-font-sizes` is one option but in my opinion isn't viable because it doesn't account for a responsive world where font sizes change and scale based on various conditions.

I definitely appreciate there are challenges here in the UI, and I'm sad this won't make it in because I do feel it's better in separating "custom" and "named" sizes (which, in `master`, interact and connect in weird, unique-to-Gutenberg ways), but addressing this problem has become my personal crusade and I plan to continue exploring in Phase 2 🤺

2018-10-23 11:29 UTC, closed without merging