File Block: Remove the download attribute
WordPress/gutenberg pull request #10693
Opened 2018-10-17 16:27 UTC by Copons

## Description

Remove the `download` attribute from the File block's "Download" button.

The addition of the `download` attribute for `a` tags to the `wp_kses` whitelist has been [recently blocked](https://core.trac.wordpress.org/ticket/44724#comment:11) (cc @pento):

> The `download` attribute doesn't work on cross-origin links (eg, any site that uses a CDN for hosting uploads). I don't know that we necessarily need to account for this, but it is something to consider.
>
> It's also a risk to allow the download filename to be set: for example, an author could upload `my_definitely_not_suspicious_file.txt`, but then set the download attribute to be `CLICK_ME.bat`, which isn't great. If we do allow the `download` attribute, it should only be allowed with no value.

It makes sense to me to just remove the attribute altogether from the File block, and leave to the user the decision of saving the file instead of navigating to it.

## How has this been tested?
Manually on a local environment, checking for regressions.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

2018-10-18 11:47 UTC, talldan commented on packages/block-library/src/file/index.js
> +			selector: '.wp-block-file__link',
I'm not sure about all the selector changes - if, for example, the prefix on the classname ever changed (which I think has been discussed) the block wouldn't continue to work in the same way.

2018-10-18 12:03 UTC, talldan reviewed
Thanks for the PR, @Copons!

I noticed when testing this, the 'button' still says download, which is misleading for the user:
![screen shot 2018-10-18 at 7 57 40 pm](https://user-images.githubusercontent.com/677833/47152875-80e18180-d310-11e8-8a33-359cffd1660c.png)

I think we should consider removing this button entirely or alternatively changing the default text (could be changed to something like 'open').

The other part that's misleading is the toggle option in the sidebar:
![screen shot 2018-10-18 at 7 59 59 pm](https://user-images.githubusercontent.com/677833/47152888-86d76280-d310-11e8-9d7d-066fc4509104.png)

This could be removed or perhaps changed to just 'Show button'.

2018-10-18 17:06 UTC, Copons commented
Thanks for the review @talldan, you made some very interesting points.

> Removing the download attribute makes the button style link somewhat redundant in the File block. It ends up doing the same thing as the other link.

I'd argue that the button would still have a value as a CTA.

Off the top of my head, I can think of a couple of way to keep the button still useful, even without a behaviour of its own:

- When the block is set to show the button, the filename is not a link.
E.g. `filename.txt <a href="filename.txt">Download</a>`

- The button is _part_ of the link, so that when hovered they change style together.
E.g. `<a href="filename.txt">filename.txt <span>Download</span></a>`

---

> changing the default text [...] to something like 'open'

> the toggle option in the sidebar [...] could be [...] changed to just 'Show button'.

Both these points make much sense to me, but of course let's wait for a design look. 🙂

2018-10-20 11:10 UTC, pento commented
We don't need to remove the `download` attribute entirely. If we just restrict it to being set (but not given a value), which removes the security issues.

For sites that use a CDN for hosting uploads, you could use a file passthrough handler to add the `Content-Disposition: attachment` header, forcing the file to be a download. In WordPress Multisite, that already exists in the form of `ms-files.php`. For prehistoric multisites, such as WordPress.com, there's also `wp-content/blogs.php`, which is a file you should definitely look at. ;)

2018-10-20 11:14 UTC, pento requested changes

2018-10-20 11:14 UTC, pento commented on packages/block-library/src/file/index.js
> -						download={ getTextContent( create( { html: fileName } ) ) }
We don't need to remove the `download` attribute, we just need to set it with no value.

2018-10-23 11:59 UTC, Copons commented
Replaced by #10948

2018-10-23 11:59 UTC, closed without merging