Testing: Stub all oEmbed requests as empty string
WordPress/gutenberg pull request #10709
Opened 2018-10-17 23:04 UTC by aduth

This pull request seeks to improve end-to-end tests to stub an empty HTML response for all oEmbeds.

**Testing Instructions:**

Ensure end-to-end tests pass:

```
npm run test-e2e
```

2018-10-17 23:29 UTC, danielbachhuber approved these changes
I've created #10710 as a follow-up task.

2018-10-17 23:36 UTC, notnownikki requested changes
I think the demo test needs to be left as it is. The reason is that we check if the demo content marks the post as dirty, so we need to get back a response from Vimeo, removing the source from the iframe but preserving the dimensions, so that we can check that aspect ratio detection isn't going to make the demo page dirty when it loads. Other tests can stub out the response to an empty string, but the demo page needs to test that we're not going to make everyone's demo post dirty.

2018-10-17 23:38 UTC, danielbachhuber commented
> I think the demo test needs to be left as it is. The reason is that we check if the demo content marks the post as dirty, so we need to get back a response from Vimeo, removing the source from the iframe but preserving the dimensions, so that we can check that aspect ratio detection isn't going to make the demo page dirty when it loads.

@notnownikki How do you suggest we handle the intermittent failure that's failing everyone's builds right now and blocking development?

2018-10-17 23:44 UTC, notnownikki commented
@danielbachhuber could we have the part which stubs out the iframe content respond with a mock if the actual vimeo embed request fails?

2018-10-18 00:01 UTC, notnownikki approved these changes

2018-10-18 00:02 UTC, notnownikki commented
Changing my review on this after discussing at https://wordpress.slack.com/archives/C02QB2JS7/p1539819998000100

I'll fix up the demo test to use a mock if vimeo is down, and the actual response if it isn't, in a future PR.

2018-10-26 14:18 UTC, aduth commented
I don't know that this solution is viable. Closing with #11116 as parent issue for tracking.

2018-10-26 14:18 UTC, closed without merging