Add components readme file
WordPress/gutenberg pull request #10704
Opened 2018-10-17 20:55 UTC by drw158

fixes #10703 

Part of the handbook master thread #10549 

wip

2018-10-17 21:00 UTC, Soean commented on docs/components/README.md
> +This is a library of generic WordPress components to be used for creating common UI elements shared between screens and features of the WordPress dashboard. They are published to vpm via the `@wordpr
`vpm` --> `npm`

2018-10-18 14:19 UTC, drw158 commented
I believe the individual component readmes can stay where they are, and they'll be linked the same way they are now, like https://wordpress.org/gutenberg/handbook/components/autocomplete/

which links to 

https://github.com/WordPress/gutenberg/edit/master/packages/components/src/autocomplete/README.md

I don't have a strong opinion on whether that should change or not though.

2018-10-18 14:37 UTC, mtias commented
> Is the plan that individual readmes from each package will get merged into the docs folder or will we need to write separate documentation for the components?

I want to keep the documentation for each component next to the code. That'll ensure that people consuming the packages can get the relevant readmes and guidelines.

Our /docs can aggregate them if needed.

2018-10-18 14:38 UTC, youknowriad commented
We already aggregate the components with our "docs build tool". I'm thinking we should consolidate the work on this PR with what we already have.

2018-10-18 14:39 UTC, mtias approved these changes
This looks like a great start

2018-10-18 14:41 UTC, mtias commented
> By this I mean. Automatically generate this file.

We might want to categorize and group them manually, though.

2018-10-18 14:42 UTC, youknowriad commented
> We might want to categorize and group them manually, though.

I'm afraid we'll forget to update this list. Can't we add a comment tag or something?

2018-10-18 14:42 UTC, youknowriad commented
That said, I'm fine with manual process first.

2018-10-18 14:45 UTC, mtias commented
> Can't we add a comment tag or something?

Maybe. But I think we should first see what we want as organization (should we have a group for Button that includes IconButton ButtonGroup etc?). Once that is more settled we can look at automating it.

2018-10-18 14:55 UTC, drw158 commented
Good discussion. I wasn't sure what to do with `HigherOrder`. It seems to be a group of components, but it's listed as an individual component. Also, I don't know what it's used for :)

Automated process would be great. I can look into what kind of organization we could have.

2018-10-18 14:57 UTC, drw158 commented
I just double-checked the list and I found a couple that I missed. This is ready for review.

I still haven't updated the manifest file. I think I may need to update that file. I can do that after the PR is merged though.

2018-10-18 20:54 UTC, drw158 commented
Here's my suggestion for categorizing the components:

- **Buttons**
  - Button
  - IconButton
  - ButtonGroup
- **Inputs and Controls**
  - TextControl
  - TextareaControl
  - SelectControl
  - TreeSelect
  - FormToggle
  - ToggleControll
  - RadioControl
  - CheckboxControl
  - RangeControl
  - BaseControl
  - DateTimePicker
  - FormTokenField
- **Menus**
  - MenuGroup
  - Dropdown
  - DropdownMenu
  - MenuItem
  - MenuItemsChoice

All the rest can remain uncategorized. 

Ideally we could have many components on the same page, for example, the menu components. But, I'm not sure how that'd work with the separate readme files.

2018-10-19 16:29 UTC, ajitbohra commented
> Some of these components have not been added to the manifest file — we'll need to add them there after this PR is merged. Or just update the manifest file in this PR?
> 
> [/docs/manifest.json@`master`](https://github.com/WordPress/gutenberg/blob/master/docs/manifest.json)

`manifest.json` is auto generated with `npm run docs:build`

> I still haven't updated the manifest file. I think I may need to update that file. I can do that after the PR is merged though.

You can update the `manifest` in this PR, entry for components parent needs to be added to `root-manifest.js` https://github.com/WordPress/gutenberg/blob/master/docs/root-manifest.json

2018-10-31 19:51 UTC, gziolo commented
The script for generating manifest is here: https://github.com/WordPress/gutenberg/blob/master/docs/tool/index.js - all code is in the same folder. It basically scans various places in the repository and using `glob` discover useful `README` documents to expose in Gutenberg Handbook. They are grouped together using very random rules :)

2018-12-14 09:20 UTC, gziolo commented
@chrisvanpatten - with the recent docs reorganization it seems like out of date. Can you help to either merge it or close?

2018-12-14 09:21 UTC, gziolo requested changes
It is out of date.

2019-01-04 12:13 UTC, gziolo commented
Thanks for your time spent on this PR. I agree that at some point we should add some organization to the components package and add some subfolders. I don't think it's so pressing as of today.

Regarding keeping the list of components it might be hard to maintain manually so I would prefer we spend the time to automate it in a similar fashion we did it for the handbook's manifest.

I'm closing this PR but we can use this work as a template to automatically update `@wordpress/components` README file with the list of components to have it included on this page: https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/.

2019-01-04 12:13 UTC, closed without merging