Add title as an editable attribute on the image block
WordPress/gutenberg pull request #11070
Opened 2018-10-25 15:56 UTC by brentswisher

## Description
Adds a title attribute to the image block, as requestions in #11054, although I think there may be some more discussion needed, I will follow up there. 

## How has this been tested?
Add a new image block to the page either via dropping a file of the media library
Open the settings for that block.
See that there is now a "title" attribute that is defaulted to the current title attribute in the media library
Save and view post, see that the title attribute exists on the image unless it was set to blank.

## Screenshots
![edit_post_ _gutenberg_dev_ _wordpress](https://user-images.githubusercontent.com/6653970/47513220-c7246c80-d84b-11e8-9351-e17cbd770222.png)

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

2019-02-01 10:42 UTC, jasmussen commented
This seems okay to me. We might want to put the Title text below the Image size tools, as those seem more important, but I can understand how there's an argument to keep it close to the Alt text too. This, and the fact that the sidebar is getting crowded, would be the only design considerations we need to think about. Once that's settled, it'd be nice with shorter copy for the help text — how short can we make it?

I would suggest the acessibility feedback is more important. I know that in some cases, the Title attribute can be _detrimental_, but would appreciate thoughts from others.

2019-02-01 10:58 UTC, youknowriad commented
Seeing all the help texts makes me wonder if we shouldn't leverage a ⓘ icon for them. I feel the usability of the UI is starting to suffer from all these texts.

2019-02-01 11:20 UTC, jasmussen commented
> Seeing all the help texts makes me wonder if we shouldn't leverage a ⓘ icon for them. I feel the usability of the UI is starting to suffer from all these texts.

I personally am of the opinion that we should work to retire that icon entirely. I think an in between step is to merge it with the block traversal button so at least those two are one — but the more buttons we can remove from the left hand side of the top toolbar, IMO, the better. 

I feel like the sidebar is the right place for it. You can toggle the sidebar off for a simple basic experience, and anything you put in the sidebar should be stuff that is advanced. The tools we have at our disposal to simplify here is to reduce text as much as is possible, simplify labels as much as possible, only add help text when it's actually necessary, and group items in panels.

2019-02-01 11:53 UTC, youknowriad commented
@jasmussen What I meant is that instead of having help text display under each input, we'd display a  ⓘ icon or similar next to the label.

2019-02-01 11:53 UTC, youknowriad commented
Definitely something out of scope of this PR though.

2019-02-01 11:56 UTC, jasmussen commented
Doh, sorry I thought you meant the Outline button in the top toolbar. 

I don't know that adding an icon with help text would reduce that much more — but I think we can go a long way in simply reducing labels and help texts to as concise text as possible. Of course the meaning has to be conveyed, but nearly always there's a shorter phrasing.

2019-02-04 23:58 UTC, brentswisher commented
Thanks for the feedback @jasmussen and @youknowriad. I'll bring this code up to date so it can be reviewed/merged, in the meantime, any thoughts on the concern I brought up about the default titles in my [comment](https://github.com/WordPress/gutenberg/issues/11054#issuecomment-433110918):

> 2\. Since the default title is set to the file name, I am concerned that adding it here will result in a lot more titles being saved into the page's content with the default (ie: IMG_2323),

Specifically, I'm wondering about images "inheriting" defaulted titles that match their filename.
I know on my sites, that would mean a lot of images get title attributes like "IMG0024.jpg" without me really doing anything.

The only alternative I could think of would be a toggle for if the title should be displayed that is defaulted to off? Then at least the user could see the title they are adding and it's more opt-in than opt-out. The obvious trade-off being adding complexity to an already full UI.

2019-02-05 08:06 UTC, youknowriad commented
@brentswisher I'm having trouble understanding (by reading the code) where this default title is being added. I'm assuming by default it should be undefined.

2019-02-05 14:17 UTC, brentswisher commented
![0hmwpswfej](https://user-images.githubusercontent.com/6653970/52278972-69152400-2926-11e9-968b-7cd4ec844168.gif)

Sorry, should have made that more clear. When an image is uploaded, the media uploader sets the title attribute of that image to be the file name. This is an existing procedure for every image, so when I grab the image attributes in the block, that comes in as the title.

This is the line:
`const imageProps = pick( image, [ 'alt', 'title', 'id', 'link', 'caption' ] );` 

Maybe that's fine and it's obvious enough that is a user wants to change it they will. My worry is that the majority of users might not notice it or understand what is does and we will populate the internet with pointless title attributes. 

I'm open to leaving it as is if others think it's okay, just wanted to at least make sure it was a conscious decision.

2019-02-05 16:10 UTC, youknowriad commented
What if we remove the "title" from this `pick` call? What downsides will we create? Why this "title" property was there for the first time?

2019-02-05 21:01 UTC, brentswisher commented
I was thinking the problem would be that two different attributes for an image both called title seemed confusing. However, in looking at the classic editor it looks like this is exactly what's happening. There is a title for the media item which serves as its name. There is also an "image title attribute" that adds a title to the actual HTML output. I say we follow that example, I'll work on updating.

2019-02-07 02:20 UTC, brentswisher commented
I worked on this some more and not defaulting the title was quite confusing to me. There were two things called title for an image. One which was edited in the media modal and one which was in the block, but were unrelated to each other. I expected them to act the same as the alt attribute when uploading or replacing an image. 

What about a toggle? This way we can keep it with only one title, but make sure it is intended to be displayed? 

Something like this (Copy/design is rough, just a proof of concept)

![hpdnhb00dc](https://user-images.githubusercontent.com/6653970/52386345-bf33b580-2a53-11e9-8e99-31fadcf5c0df.gif)

2019-02-23 16:13 UTC, afercia commented
For the SEO side, please refer to this comment on the issue https://github.com/WordPress/gutenberg/issues/11054#issuecomment-466662836

I think the best option is to keep the **Attachment Title** separated from the **title attribute** as WordPress does in the classic editor experience.

When uploading an image, the filename is used by default for the _Attachment Title_. It's _never_ used for the title attribute. That wouldn't make sense. The Attachment Title is used for the attachment post title, it's searchable, and it's the post title in the attachment page.

The _title attribute_ has a completely different purpose and must be kept separated. It must not be added by default to the image markup. Classic editor doesn't add it. The change in this PR would be a breaking change with serious impact on semantics and accessibility.

In the Classic editor, the _title attribute_ can be added later, in the image details media modal:

<img width="656" alt="screenshot 2019-02-23 at 16 52 34" src="https://user-images.githubusercontent.com/1682452/53288771-f95bc180-378c-11e9-9a64-1d9a9bd7dd70.png">

Right now, this is not possible in Gutenberg because clicking "Edit" for an existing image opens the "Select or Upload Media" modal. Instead, it should open the "Image Details" modal (like in the Classic editor).

2019-04-05 20:09 UTC, mapk commented
@brentswisher where are we right now on this PR? Are you blocked by anything?

2019-04-06 18:40 UTC, brentswisher commented
@mapk not blocked, I've just been taking a bit of a guten-break if you will. I can revisit this week, looks like moving it to the advanced section and calling it "image title attribute" would be best?  That's similar to the classic editor and should minimize accessibility concerns for @afercia?  That would also take care of the earlier issue of whether or not to default it as it will be a different property than the image title in the media library.

2019-04-15 20:55 UTC, designsimply commented
@brentswisher looks like you have a green light in the form of a 👍. Thanks for working on this!

2019-04-15 20:55 UTC, designsimply commented
@brentswisher looks like you have a green light in the form of a 👍. Thanks for working on this!

2019-04-21 00:08 UTC, brentswisher commented
@designsimply Great, I was on vacation all week but have this 98% done locally, just want to do some more testing before pushing it up, should have it ready to look at this upcoming week

2019-06-15 00:18 UTC, mapk commented
I just tested and it's working from a design perspective. 👍 

![imagetitle](https://user-images.githubusercontent.com/617986/59544642-61fbb500-8ec8-11e9-9a03-6e98568bf906.gif)


It would be good to get a code review on this before merging.

2019-07-15 09:33 UTC, tellthemachines requested changes
Thank you for your work on this issue! The code looks good except for a couple of unrelated changes that I have left comments about.

2019-07-16 09:01 UTC, afercia commented
Thanks for working on this! Tested locally and seems to me it works as intended. The only thing I'd suggest to change is the help text for the title attribute input field:

`Provide a clear name for this image.`

Doesn't seem appropriate because the title attribute is not the image name. Quoting from [the HTML 5.2 recommendation](https://www.w3.org/TR/html52/dom.html#the-title-attribute):

> The title attribute represents advisory information for the element, such as would be appropriate for a tooltip. On a link, this could be the title or a description of the target resource; on an image, it could be the image credit or a description of the image ...

Ideally, the short help text should also make clear users shouldn't rely on the title attribute.

2019-07-16 13:00 UTC, brentswisher commented
@tellthemachines thanks for the review, I will check out those extraneous changes and it also looks like it is conflicting with master again. This thing has been rebased a half dozen times so I'm sure that's what caused that. 😄 

@afercia thanks for the review, that text came from @mapk https://github.com/WordPress/gutenberg/pull/11070#issuecomment-460888853 so I will defer to him on that change.

2019-07-17 01:52 UTC, brentswisher commented
@tellthemachines I've brought this up to date with master and rebased my changes over it. I can't see exactly what change you were referring to in the second comment regarding height/width, that should be the same as master currently. 

Worth noting, the diff is somewhat misleading on this PR in that it is showing all of the contents of `<InspectorControls>` as new when really they were just tabbed over and put inside a Fragment, to accommodate adding the `< InspectorAdvancedControls >` which is where the actual code changes are.

2019-07-17 01:53 UTC, brentswisher commented on packages/block-library/src/image/edit.js
> +								onChange={ this.updateImageURL }
Good catch, this was a rebase error at some point, should be fixed now

2019-07-17 01:53 UTC, brentswisher commented on packages/block-library/src/image/edit.js
> +										min={ 1 }
This should be rebased back up to master

2019-07-17 03:51 UTC, tellthemachines approved these changes
Looks good now. Thanks again!

2019-07-29 21:29 UTC, brentswisher commented
@mapk and @afercia - thoughts on the text, this PR has had a long life and I'd love to get it wrapped up. 

I'm of the mind that since it is already under "advanced options" the current text should work, maybe we push it as is and iterate on it later if it becomes an issue?

2019-07-30 17:33 UTC, afercia commented
@brentswisher sure and thanks for persevering! 🙂 I'd just like to see the description text change because it's misleading.

See the work done on the WordPress admin in the past years:
https://core.trac.wordpress.org/query?keywords=~title-attribute

See the big warning on the HTML 5.2 spec:
https://www.w3.org/TR/html52/dom.html#the-title-attribute
> Relying on the title attribute is currently discouraged as many user agents do not expose the attribute in an accessible manner as required by this specification (e.g., requiring a pointing device such as a mouse to cause a tooltip to appear, which excludes keyboard-only users and touch-only users, such as anyone with a modern phone or tablet).

The current text is as follows:

<img width="280" alt="Screenshot 2019-07-30 at 19 25 12" src="https://user-images.githubusercontent.com/1682452/62151352-6b1dd580-b300-11e9-8074-908b830132bc.png">

- it doesn't make clear what it is: it's not a _name_, instead it's an additional description
- it's optional and users shouldn't rely on it for important information
- the text should make clear the title attribute should be used only for non-essential information, as many users won't even see the title attribute
- it doesn't make clear it's actually rendered by browsers as a small "tooltip" on top of the element it's set to

I do realize condensing all this information in a short sentence is not simple but maybe the description could include a link to an extended explanation, as we did for the alt attribute.

2019-08-05 16:41 UTC, brentswisher commented
The problem is I don't see how to get all of that into one sentence. What if we paraphrase the actual spec page:

"The title attribute represents additional information for an image, but is discouraged as the only place that information is available"

If @mapk (or any other designers) had any input that would be great, I'm much better at writing code than copy 😉

2019-08-05 22:56 UTC, mapk commented
How about...

```
Provide an optional, non-essential description for this image.
```

> maybe the description could include a link to an extended explanation, as we did for the alt attribute.

Adding a link in addition is a good idea. @afercia, do you have a link that would be recommended?

2019-08-06 07:05 UTC, afercia commented
@mapk there are a few, good, resources that explain in detail why users shouldn't rely on the title attribute, for example:

https://developer.paciellogroup.com/blog/2010/11/using-the-html-title-attribute/
https://www.24a11y.com/2017/the-trials-and-tribulations-of-the-title-attribute/

They're a bit too technical for the average users though. Maybe the best option is to just link to the HTML 5.2 recommendation, which has a nice, easy to scan, "Warning box":

https://www.w3.org/TR/html52/dom.html#the-title-attribute

2019-09-11 16:03 UTC, brentswisher commented
I've updated the help text to be a link as suggested by @afercia and the text to "Provide an optional description for this image." @mapk "optional, non-essential" seemed a little repetitive without adding any additional information, but if there are strong feelings it should be that I'm not opposed to updating. Love to get this wrapped up and merged if everyone is good with it?

2019-09-11 17:39 UTC, afercia commented
@brentswisher thanks for the ping! Maybe it's a language thing (not an native English speaker here) but as a user, if the whole sentence is linked:

`[link]Provide an optional description for this image.[/link]`

<img width="306" alt="Screenshot 2019-09-11 at 19 27 59" src="https://user-images.githubusercontent.com/1682452/64720428-b401a600-d4ca-11e9-9964-9ddb94375c08.png">

I would expect the link to point to a resource that explains _what an optional description is_. Instead, we'd want the message to inform users they shouldn't rely on the title attribute for important information.

Today, title attributes are only available to a minority of users. I'd tend to think we can contribute to the progress of the Web as a whole if we strive a bit to find some better wording :) 

Also, the part: `description for this image` is not 100% accurate because this is about _the purpose_ of the image, not necessarily the image content (same as for the `alt` attribute).

What about something along the lines of:

`Optional description. [link]Consider to not rely on the title attribute for important information.[/link]`

(I'm trying to avoid `don't` and negative sentences)

/Cc @mapk

2019-09-11 19:34 UTC, brentswisher commented
@afercia Yes, I like it not all being a link better, I reworded the second part a little bit:
<img width="267" alt="Edit_Post_‹_WordPress_Develop_—_WordPress_1" src="https://user-images.githubusercontent.com/6653970/64728693-940dba80-d4a9-11e9-8a84-7b1dffc67593.png">

2019-09-18 16:04 UTC, michelleweber commented
I find it a little odd to only include language about how not to use this field, and no language about what the field actually *is*. Am thinking of something along the lines of:

> Describe the role of this image on the page. (Note: many devices and browsers do not display this text.)

This explains what it is, and by explaining that it's not always used the "don't put key info here" idea is strongly implied.

2019-09-18 17:09 UTC, afercia commented
I'd tend to agree, see my previous comment where I was trying to avoid negative sentences.

2019-09-26 17:14 UTC, brentswisher commented
Happy to update that, would it all be the link text, or just a part of it @michelleweber?

2019-09-27 05:30 UTC, mapk commented
Let's try @michelleweber's idea there. It's worded pretty good!

2019-09-27 09:51 UTC, michelleweber commented
I'd only link the second sentence.

2019-09-27 19:08 UTC, brentswisher commented
Updated to the latest text:
![Edit_Post_‹_WordPress_Develop_—_WordPress](https://user-images.githubusercontent.com/6653970/65795603-a558f700-e138-11e9-884b-fd9ee2b2b0c5.png)

2019-10-01 15:42 UTC, mapk commented
One more suggestion from:

`Note: many devices and browsers do not display this text.`

to:

`Note: this text is not always displayed.`

or simpler:

`Not always displayed.`

I think the link defines the reasons about devices, etc.

2019-10-01 20:39 UTC, michelleweber commented
My two cents -- whenever possible, text should make sense and answer people's questions as much as possible without requiring them to click on a link. In this case, "Not always displayed" doesn't answer questions, it raises them -- why? when? where? -- and that requires clicking. (You could lighten the line visually by only linking "do not display" instead of the whole sentence, tho.)

(I know the longer version doesn't answer every question either, but it does clarify that if its not displayed, it's because of the browser or device and not because your website/something you did.)

2019-10-03 00:13 UTC, mapk commented
> In this case, "Not always displayed" doesn't answer questions, it raises them -- why? when? where? -- and that requires clicking. 

This is fair, but for what it's worth, "_Many devices and browsers do not display this text._" probably raises the same questions too. 

I'm good either way here. I'd love it if there was a way to trim it down, but not opposed to longer text if it helps the user.

2019-10-23 00:42 UTC, brentswisher commented
This has been held up for quite a while with differing opinions on text, but nobody seems strongly opposed to what is there now. Am I reading that correctly? If so feel free to speak up, otherwise, I am going to try to get this moving forward as is.

2019-10-30 13:34 UTC, brentswisher commented
This PR has been going on for a while so a summary may be in order:
- This PR adds a field for "Image Title Attribute" to the Advanced options of the image block.
- This is different from the "Attachment Title" which is never displayed publicly.
- This lines up with how the classic editor handles the title attribute (which is currently unavailable in Gutenberg)
- While adding this to add compatibility to the classic editor, help text and a link to the w3c page explaining that it should not be used for critical information was added as title has historically been abused for accessibility purposes.

2019-10-30 14:31 UTC, mkaz commented
The code change looks good, however I think the extra text and link is confusing. Especially since we have almost the same text above in the ALT field. It is hard as a user to parse and figure out what I'm supposed to do. See this screenshot.

![Screenshot from 2019-10-30 06-43-25](https://user-images.githubusercontent.com/45363/67866883-d5543b00-fae6-11e9-83b3-fd64c11f7ec6.png)

This is what the fields look like in the Media Uploader, and there is no extra contextual info around title there.

![Screenshot from 2019-10-30 06-55-27](https://user-images.githubusercontent.com/45363/67867057-10566e80-fae7-11e9-9307-b56f1cee0944.png)

I thinking remove the extra text around the Title field will make it easier for the user, also gets the feature in so the users can set the title which is an accessibility win. We can solve the contextual help by addressing @youknowriad comment about using a (i) icon in a separate isuse.

2019-11-01 16:25 UTC, merged