Pass the post being edited to the enqueue_block_editor_assets action
WordPress/gutenberg pull request #11117
Opened 2018-10-26 13:59 UTC by petenelson

## Description
Passes the post being edited to the enqueue_block_editor_assets action.

## How has this been tested?
These changes have not been tested.

## Checklist:
- [ ] My code is tested.
- [X] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [X] My code has proper inline documentation.

2018-10-26 14:21 UTC, adamsilverstein commented
@petenelson Looks good to me, can you explain your use case for this? Would the $post object be available as a global?

2018-10-26 14:40 UTC, petenelson commented
`$post` is available as a global, but since it's already being used inside the function that's calling the action, figured it would make sense to pass it along. The custom block I'm currently developing needs some data from the current post and I'm adding it as localized data.

2018-10-26 14:44 UTC, adamsilverstein commented
> since it's already being used inside the function that's calling the action, figured it would make sense to pass it along

Makes sense to me, thanks.

2018-10-26 14:44 UTC, adamsilverstein approved these changes
LGTM

2018-10-28 08:57 UTC, swissspidy requested changes
I‘d follow core coding standards here by adding a new `@since 4.1.1` entry for the added param.

2018-10-29 13:46 UTC, gziolo commented
Is there any place in the docs where it would make sense to mention this change?

2018-11-06 13:07 UTC, danielbachhuber requested changes
I'm not sure it makes sense to pass the `$post` to `enqueue_block_editor_assets`. What happens when the block editor is used to manage sidebars, etc.? It feels like `enqueue_block_editor_assets` should emulate `wp_enqueue_scripts` as much as possible.

2018-11-06 16:12 UTC, felixarntz requested changes
While I can see that having the `$post` in the filter is useful, I also agree with @danielbachhuber's concern which is about forward-compatibility. When the block editor is used for non-post content (which it likely will be in the future in one way or another), we'd get ourselves into trouble now by making this a hook parameter.

Since a hook callback for `enqueue_block_editor_assets` could easily detect whether there is a current post and then use it, I'd say let's hold off of this, as we don't wanna get ourselves to require clunky hook signatures in the future.

2018-11-06 21:43 UTC, gziolo commented
Should we close it in that case?

2018-11-08 11:18 UTC, closed without merging