Fix rich-text package dependencies
WordPress/gutenberg pull request #11122
Opened 2018-10-26 14:57 UTC by iseulde

## Description
Currently `@wordpress/blocks` is not added as a dependency. @nosolosw does this fix your issue?

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

2018-10-26 15:16 UTC, oandregal approved these changes
It does! The console no longer shows the `Uncaught TypeError: Cannot read property 'normalizeIconObject' of undefined at registerFormatType (register-format-type.js:77)` error when Gutenberg loads.

I'm approving although e2e tests haven't finished yet.

2018-10-26 15:19 UTC, nosolosw commented
mmm, e2e tests render this error related to the `escape-html` package:

![screenshot from 2018-10-26 17-18-21](https://user-images.githubusercontent.com/583546/47575815-3630bc80-d943-11e8-99ed-79338cb5a3c0.png)

2018-10-26 15:20 UTC, oandregal requested changes
Changes look good and fix the problem. I see some e2e errors that may be related?

2018-10-26 20:05 UTC, aduth commented
I'd expect there to be some changes to `package-lock.json` included here.

2018-10-29 06:04 UTC, pento commented
Oh, this would be the bug I'm running into when trying to update Core's packages. 🙂

2018-10-29 06:31 UTC, pento commented
Webpack should be able to handle the circular dependencies, it's `WP_Dependencies` which has issues. 🙂

2018-10-29 07:31 UTC, pento commented
Well, that's good to know. Removing the `wp-rich-text` dependency from `wp-blocks`, and adding a `wp-blocks` dependency to `wp-rich-text` fixes this issue in Core.

2018-10-29 10:39 UTC, gziolo commented
Closing in favor of #11197.

2018-10-29 10:50 UTC, closed without merging