Add `has-background` classes to pullquote and Media & Text blocks
WordPress/gutenberg pull request #11228
Opened 2018-10-30 00:05 UTC by chrisvanpatten

Fixes #11172.

This adds `has-background` classes to the pullquote and Media & Text blocks.

I also did some light refactoring to try to make the code easier to read (which did make it easier to write the PR) and made it so neither block has an inline `background-color` style if using a named color value.

I expect the tests on this are going to fail because I didn't update any snapshots; I plan to fix that up in the morning.

2018-10-30 03:03 UTC, chrisvanpatten commented
Hmm… weirdly, the e2e tests pass but now the unit tests fail... I will take another look in the morning but if anyone sees an obvious mistake please feel free to push to this branch 👍 For now, bed beckons. 🛌

2018-10-30 11:52 UTC, chrisvanpatten commented
Tests should pass now. Got tripped up the `classnames` doesn't return `undefined`, just an empty string, when there are no classes to apply. Super irritating (and weird that I didn't notice this until today).

In any event, ready for a review ❤️

2018-10-30 12:34 UTC, chrisvanpatten commented
![screenshot 2018-10-30 at 08 33 59](https://user-images.githubusercontent.com/1231306/47718350-8eefa600-dc1e-11e8-982a-f2d5bc86463e.png)

Not clear why Travis failed, because it says the tests passed…

Going to restart the build and see what happens…

2018-10-30 12:39 UTC, youknowriad commented
@chrisvanpatten That's because master was broken. It should be fixed now, if the tests don't pass, try to rebase.

2018-10-30 13:28 UTC, chrisvanpatten commented
Thanks for the tip @youknowriad — tests are now passing!

2018-11-19 18:25 UTC, aduth requested changes
In brief testing, this invalidates a Media & Text block which had been previously saved with a background color, when loaded in this branch. I'd think this shouldn't be happening generally, as maybe we should consider _additional_ classes as not-invalidating. Without such a solution or a block deprecation, I don't think this should go through in its current form.

2018-11-19 19:14 UTC, chrisvanpatten commented
> In brief testing, this invalidates a Media & Text block which had been previously saved with a background color, when loaded in this branch. I'd think this shouldn't be happening generally, as maybe we should consider additional classes as not-invalidating. Without such a solution or a block deprecation, I don't think this should go through in its current form.

That's totally fair. I agree that we shouldn't invalidate blocks by classNames changing but unless there's a mechanism in Gutenberg core I don't think it's worth pushing this in.

(It could definitely be fixed with a deprecation, but that feels like using an impact driver when you really need a jeweler's screwdriver.)

2018-11-19 19:35 UTC, aduth commented
@samikeijonen Correct, at least in the current validation procedure. As mentioned in my previous comment, this is probably too heavy-handed. The validator errs on the side of caution when it comes to semantic differences in markup, of which even an added class could fall under (I can imagine a scenario where an added class has a "destructive" effect). 

Generally speaking, _adding_ a class could probably be exempted from the validation behavior, or at least accounted for by the behavior of `customClassName`.

2018-11-21 19:34 UTC, aduth commented
On second thought, while all of the above is still true, given the way a deprecation works, it's something that if we were to add one now, at the point we resolve the framework-level issue of handling additional classes, we could easily drop the deprecation without concern.

Is adding a deprecation something you'd be able to do here?

2018-11-22 13:18 UTC, samikeijonen commented
> Is adding a deprecation something you'd be able to do here?

That was question for @chrisvanpatten I assume?

> at the point we resolve the framework-level issue of handling additional classes, we could easily drop the deprecation without concern.

That would be wonderful if at some point we could add classes without deprecation logic.

2018-11-22 17:03 UTC, chrisvanpatten commented
Right now I don’t have the bandwidth to take this further but I’m more than happy to let someone take over the PR!

2019-02-01 09:41 UTC, gziolo commented
@jorgefilipecosta would you mind taking it over?

2019-02-01 12:08 UTC, jorgefilipecosta commented
Sure I will catch with the discussions and try to take the PR to the finish line. Thank you to all those involved.

2019-02-01 14:39 UTC, chrisvanpatten commented
Thanks @gziolo @jorgefilipecosta 🎉 ❤️

2019-02-19 11:48 UTC, jorgefilipecosta commented on packages/block-library/src/media-text/edit.js
> +			backgroundColor: backgroundColor.class ? undefined : backgroundColor.color,
It was decided to use inline color styles in the editor so even if the theme developer is not loading the editor styles with the color classes, the color is still viewable in the editor. So I will revert this line change during the update.

2019-02-27 10:46 UTC, jorgefilipecosta commented
This PR is updated and ready for a review.

2019-03-11 19:30 UTC, aduth commented
Could you rebase this one? It has the `gutenberg-mobile` branch from eons ago, so I'd have a hard time guaranteeing it still works as-is.

I'm still a bit reluctant on the deprecations, still all previous comments held true, I have doubts we'd know to drop those deprecations once we improve the validation. I'd like to set some time aside looking at the validation, though still not want to let this one be blocked. I'll see what I can do there this week.

2019-07-17 09:55 UTC, mkronenfeld commented
@jorgefilipecosta Any progress since February? This little class attribute has a huge impact for page layouts, since every other layout block with background color has it, too 😅

2019-09-23 14:56 UTC, jorgefilipecosta commented
Hi @chrisvanpatten, I tried to update this PR but when I tried to push to your fork I got the following error:
```
Pushing to https://github.com/TomodomoCo/gutenberg/
remote: Permission to TomodomoCo/gutenberg.git denied to jorgefilipecosta.
fatal: unable to access 'https://github.com/TomodomoCo/gutenberg/': The requested URL returned error: 403
Completed with errors, see above
```
It seems the option to  Allow edits from maintainers was disabled.


I created another PR so I could continue these changes https://github.com/WordPress/gutenberg/pull/17529.

2019-09-23 14:56 UTC, closed without merging