Fix: "View as" link is not updated after the post is updated and the permalink is changed
WordPress/gutenberg pull request #11262
Opened 2018-10-30 19:21 UTC by jorgefilipecosta

Fixes: https://github.com/WordPress/gutenberg/issues/7275

The editor contains a "View as" pointing to the post permalink on the top bar.
This link comes from the page rendered on the server. When the post is updated with a permalink change the page is not rendered again so the "View as" link continued to be the same.
This PR adds an effect to update the dom of the "View as" link to contain the new permalink when the post is saved with success and the permalink was changed.

## How has this been tested?

Create a new post, and publish it.
Reload the editor and verify we have a "View as" link in the top bar.
Change the post permalink and press update, verify that when the post is saved with success the View as link points to the new permalink.

2018-11-05 08:50 UTC, youknowriad requested changes

2018-11-05 08:50 UTC, youknowriad commented on packages/editor/src/store/effects.js
> -	REQUEST_POST_UPDATE_SUCCESS: requestPostUpdateSuccess,
Is the old effect `requestPostUpdateSuccess` not necessary anymore?

`updateViewAsPermalink` seems undefined right?

2018-11-05 08:50 UTC, youknowriad commented on packages/editor/src/store/effects/posts.js
> +};
Can we move this effect to the `edit-post` module instead? Ideally, the `editor` package has no knowledge about any WP context.

2018-11-06 22:15 UTC, jorgefilipecosta commented
Hi @youknowriad thank you for your review, this PR is now using a different approach attending to your feedback.

2018-11-07 08:54 UTC, youknowriad approved these changes
LGTM 👍

2018-11-07 10:43 UTC, merged