Fix: Make it impossible to use the UI to add a reusable block inside the same reusable block
WordPress/gutenberg pull request #11316
Opened 2018-10-31 16:00 UTC by jorgefilipecosta

Fixes client-side problems in https://github.com/WordPress/gutenberg/issues/11206.

It was possible to use the UI to add a reusable block inside itself. This PR addresses this problem.

In order to address this problem, a new selector isAncestorOf is created.

## How has this been tested?
Add a columns block write some paragraphs inside it.
Make the columns block reusable block and save it.
Edit the reusable block add a new paragraph use the slash inserter "/" on the new paragraph and verify it is not possible to insert the same reusable block. (On master it was and the editor crashed).

2018-11-12 05:59 UTC, noisysocks requested changes

2018-11-12 05:59 UTC, noisysocks commented on packages/editor/src/store/selectors.js
> +export const isAncestorOf = createSelector(
Do we need to export this? It looks like it's only used by `getInserterItems`.

2018-11-12 05:59 UTC, noisysocks commented on packages/editor/src/store/selectors.js
> + * @param {Object} state    Editor state.
nit: These `@param` comments don't align.

2018-11-12 05:59 UTC, noisysocks commented on packages/editor/src/store/selectors.js
> +				return false;
From memory, `getInserterItems` has some fairly thorough unit tests. Let's keep that up and add a test case for this new edge case.

2018-11-12 06:01 UTC, noisysocks commented
> Fixes client-side problems in #11206.

Do you think it's worthwhile having a server-side fix? How would one work?

2018-11-14 23:21 UTC, jorgefilipecosta commented
Thank you for your review @noisysocks 👍  All the feedback was addressed.

> Do you think it's worthwhile having a server-side fix? How would one work?

For now, I addressed the client-side problem as it is possible to use the UI to trigger it. So after this PR, the bug will only happen using code.

I think the server side problem is hard to trigger/and In my perspective seems something a normal user would not do (unless trying to trigger the bug). One possible solution for the problem would be having a hook on the server the executes when saving posts and if it is saving a reusable block, it would parse the blocks inside iterate on the tree and check if there is not a block referencing its own id.

2018-11-16 04:37 UTC, noisysocks approved these changes

2018-11-16 10:13 UTC, merged