Parser: Use a non-greedy matcher to extract the block args
WordPress/gutenberg pull request #11355
Opened 2018-11-01 07:19 UTC by pento

## Description

If the block has been serialised with a very long args string, it can cause a `PREG_JIT_STACKLIMIT_ERROR` in PCRE when trying to match the block comment.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards.
- [x] My code has proper inline documentation.

2018-11-01 07:32 UTC, pento commented
Interestingly, fixing this bug exposes a new one.

In my testing, the previous regex could handle up to ~10,000 characters in the args before triggering a `PREG_JIT_STACKLIMIT_ERROR`. With the new regex, it now handles up to just under 1,000,000 characters in the args, before triggering a `PREG_BACKTRACK_LIMIT_ERROR`.

The new error is caused by the non-greedy match added in this PR, as non-greedy matches need to backtrack every time they don't match the end of the pattern.

So, I guess the question is: are we okay with a limit of 1MiB stored in the block args? 🙂

2018-11-01 15:25 UTC, dmsnell requested changes
See my comment above

2018-11-01 16:40 UTC, dmsnell commented
@pento I didn't want to hijack your PR but I did want to play around and test my suggestions so I created #11369.

as of yesterday we now have a test suite that all parsers can run again, so I hope we end up putting new tests there instead of on specific parser implementations that may only get hit by one of the four implementations existing currently in core (PHP/JS of spec/default)

2018-11-01 20:20 UTC, dmsnell commented
Comparing the default PHP parser from `master` against the one in this branch (using #6831)

![comparator-fnuoaerzsg now sh_ 2](https://user-images.githubusercontent.com/5431237/47877176-8511a280-ddd8-11e8-8945-9c5ea2490dfc.png)

Comparing the default JS parser from `master` against the one in this branch (using #6831)

![comparator-fnuoaerzsg now sh_](https://user-images.githubusercontent.com/5431237/47877331-d883f080-ddd8-11e8-9e3c-b4ae9684f141.png)

My conclusion is that there is no significant change in runtime performance in the normal cases. I don't have the catastrophic cases in the document library.

2018-11-04 00:17 UTC, pento commented
Closing in favour of #11369.

2018-11-04 00:17 UTC, closed without merging