Add stylelint to lint `*.scss` files per WordPress Coding Standards
WordPress/gutenberg pull request #1151
Opened 2017-06-13 00:38 UTC by ntwb

First pass at adding stylelint to lint SCSS files per WordPress CSS Coding Standards

References:
• https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/
• https://github.com/stylelint/stylelint
• https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress

2017-06-13 13:52 UTC, aduth commented on blocks/editable/style.scss
> +
What's the guideline that directs this blank line here? Throughout the changes I'm inferring a guideline of "always add a newline before nested selector". Is that documented somewhere? Looks a bit out-of-place in some cases, particularly in contrast to non-nested selector styles not needing the new line.

2017-06-13 13:52 UTC, aduth commented on blocks/editable/style.scss
> +
Similarly, what's the guideline for the newline here? Doesn't follow my inferred guideline from my previous comment.

2017-06-13 13:52 UTC, aduth commented on docs/tinymce-per-block/src/assets/stylesheets/main.scss
> -@import 'variables';
I think we ought to exclude `docs` from these rules. They're more legacy prototypes than actively maintained.

2017-06-22 00:50 UTC, ntwb commented on docs/tinymce-per-block/src/assets/stylesheets/main.scss
> -@import 'variables';
Right, shall do 👍

2017-06-22 00:53 UTC, ntwb commented on blocks/editable/style.scss
> +
I agree that it does look out of place in places, it's been a tough one to solve

I've a [specific set of issues](https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/milestone/2) relating to _new lines_ that I need to run through, hopefully I can get to this in the next few days, I'll then refresh this PR an we can can go from there

2017-06-22 00:53 UTC, ntwb commented on blocks/editable/style.scss
> +
See above

2017-06-22 00:54 UTC, ntwb commented
Sorry for the delay in addressing your concerns @aduth, per the review comments above I hope to get to refresh this PR in the next few days 🤞

2017-09-22 10:20 UTC, gziolo requested changes
This one got a bit outdated :( Should we rebase and take another try to get it in?

2017-09-23 07:37 UTC, ntwb commented
I'll create a fresh PR once I've update the `stylelint-config-wordpress` SCSS rules

2017-09-23 07:37 UTC, closed without merging