Update More block description
WordPress/gutenberg pull request #11587
Opened 2018-11-07 14:38 UTC by Soean

## Description
Updates the description of the More block.
Fixes: #11458

Old: 
`Want to show only an excerpt of this post on your home page? Use this block to define where you want the separation.`
New: 
`Do you want to show only an excerpt of this post on your homepage? Then use this block to define where the separation should take place.`

2018-11-08 11:01 UTC, gziolo commented
It changes more than `home page` to `homepage`. @alexislloyd what's your take on the proposed change? It looks like you iterated on it a bit earlier, so I would expect this PR to be scoped to only fix the way `home page` is used.

2018-11-08 11:20 UTC, swissspidy commented
Only fixing `homepage` everywhere in a more scoped fashion makes sense.

We can then improve the text in a separate PR. Could we then get rid of the "post" bit of the description as well please? Otherwise it's not accurate for other post types. I would replace it with "content".

2018-11-08 13:01 UTC, tofumatt requested changes
I don't like block descriptions that lead with questions. We use an entire sentence to ask the user if this is the block they want to be using before telling them what it does; the question is an indirect way of asking them and I don't think it's very instructive 😄

2018-11-08 13:01 UTC, tofumatt commented on packages/block-library/src/more/index.js
> +	description: __( 'Do you want to show only an excerpt of this post on your homepage? Then use this block to define where the separation should take place.' ),
A few thoughts:

1. the leading question only very indirectly explains what this does; we should just outright state what the block does and how it works.
2. should we be saying "post" and "homepage"? Some people don't use the archives listing on their homepage and Gutenberg edits more than just post content.

Here's my suggestion:

```suggestion
	description: __( 'Do you want to show only an excerpt of this post on your homepage? Then use this block to define where the separation should take place.' ),
	description: __( 'Mark the excerpt of this content. Content before this block will be shown in the excerpt on your archives page.' ),
```

2018-11-08 13:02 UTC, tofumatt commented on packages/block-library/src/more/index.js
> +	description: __( 'Do you want to show only an excerpt of this post on your homepage? Then use this block to define where the separation should take place.' ),
I guess we could use "signify" instead of "mark" if that's an unclear verb here. 🤷‍♂️

2018-11-09 11:30 UTC, gziolo commented
I updated `home page` with `homepage` with #11661 to land it in 4.3 and resolve the original issue. Feel free to continue discussion on the improvements to this description without the pressure of time :)

2018-11-13 14:19 UTC, tofumatt approved these changes

2018-11-13 14:19 UTC, tofumatt approved these changes
Looks good, I say :shipit:

2018-11-19 08:51 UTC, merged