CSS coding standards for font-weight
WordPress/gutenberg pull request #11715
Opened 2018-11-10 13:51 UTC by Rahmon

## Description

I've updated font-weight for numeric values (normal -> 400 and bold -> 600)

Closes: #11687 

## How has this been tested?
This has been tested with "npm test" and manually on Chrome and Firefox

## Types of changes
Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

2018-11-12 09:27 UTC, Soean approved these changes

2018-11-12 09:35 UTC, jasmussen requested changes
According to https://css-tricks.com/almanac/properties/f/font-weight/, "bold" maps to 700, not 600. Also, let's make sure we test this visually before we merge — I'm, 73% sure that there are specific instances where `600` was used instead of `bold`, because the semi bold version was desired.

2018-11-12 09:36 UTC, jasmussen commented
Thanks so very much for this PR! Really appreciate it. I left a comment that we should make sure to visually test that this doesn't change anything, as we're past the UI freeze. Bold is supposedly not the same as 600, so let's just be absolutely sure. 

If you are busy and need help wrapping up those changes, let me know and I can volunteer to fix this up.

2018-11-12 09:45 UTC, Rahmon commented
@jasmussen 

I've used 600 because in the issue (#11687) @afercia said 600 to bold. So do I need update to 700?

2018-11-12 09:50 UTC, jasmussen commented
Good question. His reasoning is that core uses 600 for bold, which certainly makes sense from a consistency point of view. Let me take this for a quick visual testing spin and revisit.

2018-11-12 09:53 UTC, Soean commented
Maybe its a typo, the link to the Coding standards says **bold -> 700**: https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#values

2018-11-12 09:57 UTC, ntwb commented
> Maybe its a typo, the link to the Coding standards says bold -> 700: make.wordpress.org/core/handbook/best-practices/coding-standards/css/#values

Not a typo, as mentioned above:
> According to css-tricks.com/almanac/properties/f/font-weight, "bold" maps to 700, not 600.

2018-11-12 09:59 UTC, Rahmon commented
> Maybe its a typo, the link to the Coding standards says **bold -> 700**: https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#values

I saw this link and I'd confused... :confused:

2018-11-12 10:05 UTC, afercia commented
Background: core used "Open Sans" where 600 mapped to the Open Sans "semi bold" weight. Most of the CSS in core still uses "600". Actually, it depends on the font. If the font doesn't provide a "600" font weight, browsers will fall back to bold anyways.

See also https://github.com/WordPress/gutenberg/issues/5848

More importantly, see https://core.trac.wordpress.org/changeset/37740

2018-11-12 10:21 UTC, jasmussen commented
Thanks for the history. I just took this this for a visual spin, and my aging eyes see no visual regressions. 

As such, I'm ready to approve this PR. But per comments by @ntwb and @Soean let me know what you think is the best approach here. 600 and 700 are both fine with me — just need to know we're doing the right thing, since it's about code quality.

2018-11-12 10:40 UTC, jasmussen approved these changes
In effort to keep things moving, approving this per discussion points.

If this was in error, and it should be 700 instead of 600, feel free to ping me and I'll submit a PR to change that.

2018-11-13 10:49 UTC, gziolo commented
> If this was in error, and it should be 700 instead of 600, feel free to ping me and I'll submit a PR to change that.

Why not use variables instead of those hardcoded values?

> Per the above, happy to see this merged as is, we should follow this up on Trac IMHO

Yes, but let's consider my previous comment.

2018-11-13 10:49 UTC, merged