Use block icons in media placeholders
WordPress/gutenberg pull request #11788
Opened 2018-11-13 01:29 UTC by ZebulanStanphill

## Description
This PR changes the media placeholders of the media blocks to use the corresponding icon of each block, instead of using Dashicons. Since the icons are now being used by both the `index.js` and (if it exists) `edit.js` of each of these blocks, I have moved these icons into `icon.js` files for each block, so the icons are not defined twice and can be imported by multiple other modules.

List of blocks this PR affects:
- Audio
- Cover
- File
- Gallery
- Image
- Media & Text
- Video

I also took the opportunity to reorganize the imports in the files I modified: they are now organized alphabetically, and imports that were previously incorrectly listed under "Internal dependencies" are now listed under "WordPress dependencies".

## Screenshot
![image](https://user-images.githubusercontent.com/19592990/48384717-35bd5300-e6b1-11e8-8044-b65c347f3a82.png)

## Related issues and PRs
- Replaces #9646

2018-11-13 16:12 UTC, ZebulanStanphill commented
Tests are passing now. Thanks for restarting them, @earnjam! :slightly_smiling_face:

2018-11-13 16:34 UTC, earnjam commented
They feel just a bit crowded to the text compared to the old icons. Flagged for design feedback

See screenshots for comparison:

<img width="300" alt="screen shot 2018-11-13 at 11 29 50 am" src="https://user-images.githubusercontent.com/4267290/48427795-94c5ab00-e737-11e8-80ba-ad3ee2c3acca.png"> <img width="300" alt="screen shot 2018-11-13 at 11 29 09 am" src="https://user-images.githubusercontent.com/4267290/48427793-92fbe780-e737-11e8-9035-87a78ac43b93.png">

2018-11-15 17:50 UTC, melchoyce commented
Good catch, @earnjam — the icons definitely need some additional space. Does Gutenberg not automatically provide the correct spacing between icon + label for placeholder blocks? I assumed it would take care of that kind of thing for folks.

2018-11-15 18:31 UTC, ZebulanStanphill commented
@melchoyce I had assumed it would as well. I am using the `<BlockIcon />` component. If I don't use it and just use the `<SVG>` component directly, then the icons grow ridiculously big. Should I be using a component other than the `<BlockIcon />` component?

2018-11-15 21:45 UTC, mtias commented
> I assumed it would take care of that kind of thing for folks.

Should be applied at the placeholder component level. Right now it addresses svgs that are dashicons, not any svg. Should be easy, I can look into it tomorrow.

2018-11-15 22:42 UTC, mtias commented
Fix for it here: https://github.com/WordPress/gutenberg/pull/11947

2018-11-16 00:13 UTC, ZebulanStanphill commented
Rebased and resolved merge conflicts.

Thanks for the margin fix PR, @mtias! :smile:

2018-11-22 04:59 UTC, ZebulanStanphill commented
Rebased and resolved merge conflicts again.

2019-02-04 13:45 UTC, gziolo reviewed
Code wise it looks quite good. I must admit that I really like the fact that icons were moved to their own file. I can perform the more in-depth review as soon as this PR gets ✅ from one of the designers.

2019-02-04 14:07 UTC, kjellr requested changes
Thanks for sticking with this, @ZebulanStanphill. It's nice to get these icons all synced up.  

Design-wise, this looks pretty good. Just a minor note: All of these icons seem just a little bit too low compared to the text. The icons need to be moved up 1px in order to be centered visually: 

**Current:** 
<img width="635" alt="screen shot 2019-02-04 at 9 04 59 am" src="https://user-images.githubusercontent.com/1202812/52213109-2a1a9c00-285c-11e9-9174-20e215e39b43.png">

**After:** 
<img width="670" alt="screen shot 2019-02-04 at 9 05 55 am" src="https://user-images.githubusercontent.com/1202812/52213111-2c7cf600-285c-11e9-8422-d9a607524ad2.png">


I have one other question for everyone: should we actually be using an image icon within the Media + Text block here?

<img width="683" alt="screen shot 2019-02-04 at 9 07 33 am" src="https://user-images.githubusercontent.com/1202812/52213171-53d3c300-285c-11e9-8256-ee8ce007c89b.png">

In this case, that placeholder area is for "Media", not specifically to "Media + Text" like the icon implies. 

Thanks again!

2019-02-04 15:03 UTC, melchoyce commented
> In this case, that placeholder area is for "Media", not specifically to "Media + Text" like the icon implies.

The "Content" on the right is the text placeholder, right?

2019-02-04 15:41 UTC, melchoyce commented
Oh, I misunderstood — the label and icon should _just_ be changed within the image block placeholder, got it. I think that makes sense 👍

2019-02-05 04:35 UTC, ZebulanStanphill commented
Rebased PR.

@kjellr Regarding the position of the icons, I checked, and it looks like it is actually the text that is not centered. Additionally, the icons themselves appear to be drawn slightly higher in their SVG viewbox than you might expect:
![untitled](https://user-images.githubusercontent.com/19592990/52253014-093d5f80-28cb-11e9-9f18-d19ef7ba02a2.png)
![image](https://user-images.githubusercontent.com/19592990/52253178-ed868900-28cb-11e9-9cd9-a9398fece3ed.png)

I don't know what the best way to adjust this would be. I don't think it really matters that much anyway, though.

As for the Media & Text block placeholder, if I'm not supposed to use the block icon, then what should I use? The media area accepts both images and videos.

2019-02-05 13:19 UTC, gziolo reviewed
I shared suggestions for some stylistic changes. Otherwise, it looks good code wise.

_Aside:_ in retrospect, I think that we should never allow elements to be defined as an icon for the block. Instead, we should be using components:
```js
const Icon = () => <SVG ...>...</SVG>;
```
However, it's too late to change that.

2019-02-05 13:19 UTC, gziolo commented on packages/block-library/src/audio/edit.js
> +					icon=<BlockIcon icon={ icon } />
Can it follow other definitions of props?:
```suggestion
					icon={ <BlockIcon icon={ icon } /> }
```

2019-02-05 13:19 UTC, gziolo commented on packages/block-library/src/file/edit.js
> +					icon=<BlockIcon icon={ icon } />
Can it follow other definitions of props?:
```suggestion
					icon={ <BlockIcon icon={ icon } /> }
```

2019-02-05 13:19 UTC, gziolo commented on packages/block-library/src/gallery/edit.js
> +						icon=<BlockIcon icon={ icon } />
Can it follow other definitions of props?:
```suggestion
						icon={ <BlockIcon icon={ icon } /> }
```

2019-02-05 13:19 UTC, gziolo commented on packages/block-library/src/image/edit.js
> +						icon=<BlockIcon icon={ icon } />
Can it follow other definitions of props?:
```suggestion
						icon={ <BlockIcon icon={ icon } /> }
```

2019-02-05 13:19 UTC, gziolo commented on packages/block-library/src/media-text/media-container.js
> +				icon=<BlockIcon icon={ icon } />
Can it follow other definitions of props?:
```suggestion
				icon={ <BlockIcon icon={ icon } /> }
```

2019-02-05 13:19 UTC, gziolo commented on packages/block-library/src/video/edit.js
> +					icon=<BlockIcon icon={ icon } />
Can it follow other definitions of props?:
```suggestion
					icon={ <BlockIcon icon={ icon } /> }
```

2019-02-05 14:34 UTC, kjellr commented
> Regarding the position of the icons, I checked, and it looks like it is actually the text that is not centered [...] I don't know what the best way to adjust this would be.

I think the simplest way to fix this would be to add `align-items: center;` to the `components-placeholder__label`. That seems to properly align things for me.

> As for the Media & Text block placeholder, if I'm not supposed to use the block icon, then what should I use? The media area accepts both images and videos.

This is a tough one — I'm not sure we actually have a Material-based icon for that yet. Maybe something like this? 

<img width="281" alt="screen shot 2019-02-05 at 9 20 09 am" src="https://user-images.githubusercontent.com/1202812/52279336-594a0f80-2927-11e9-91dc-438ce019fc08.png">

([SVG](https://cloudup.com/cA67x4EL0it))

^ That could use some extra eyes though, as it's not a straight-up Material icon. I took [the `image_search` icon](https://material.io/tools/icons/?search=image_search&icon=image_search&style=baseline), and added the play icon instead of a search icon.

2019-02-05 15:13 UTC, ZebulanStanphill commented
Addressed feedback.

@kjellr I don't know... that icon mockup still seems too image-oriented. Come to think of it... what if the media area in the Media & Text block just didn't have an icon at all? Would that be alright?

2019-02-05 16:14 UTC, kjellr commented
Eliminating an icon altogether seems a little weird to me. Interested in other people's takes though. 

Another possible Images/Video icon direction: 

<img width="189" alt="screen shot 2019-02-05 at 11 12 58 am" src="https://user-images.githubusercontent.com/1202812/52286865-06785400-2937-11e9-8bc5-e5a83bd79152.png">

<img width="190" alt="screen shot 2019-02-05 at 11 13 56 am" src="https://user-images.githubusercontent.com/1202812/52286917-2740a980-2937-11e9-9715-a46dc03c4688.png">

2019-02-05 16:16 UTC, ZebulanStanphill commented
@kjellr Ooh, I like those mockups. I think that kind of icon would work.

2019-02-05 16:21 UTC, melchoyce commented
I think that top icon could work — and I foresee a mixed image/video icon being useful in the future.

2019-02-06 04:19 UTC, ZebulanStanphill commented
@kjellr I have now updated the Media & Text block placeholder to use that new icon. :slightly_smiling_face:

2019-02-06 07:31 UTC, gziolo approved these changes
On the code level, all those changes look good. I like that icons were moved to their own file 👍 

I'm leaving final ✅ to @melchoyce and @kjellr who have better idea how those icons should integrate :)

2019-02-06 15:01 UTC, kjellr approved these changes
Looks great, thank you @ZebulanStanphill! I still may iterate on that image/video icon a little bit, but that can be handled separately. 👍 

![screen-shot-2019-02-06-at-9 58 23-am](https://user-images.githubusercontent.com/1202812/52350213-055a2c00-29f6-11e9-8319-5788cc7c070e.gif)

2019-02-06 15:01 UTC, merged