Add 'innerBlocks' support for transforms
WordPress/gutenberg pull request #11979
Opened 2018-11-16 13:10 UTC by Luehrsen

## Description
This PR aims to provide support for 'innerBlocks' in transform rules. The proposed syntax is like this.

```
transforms: {
	from: [
		{
			type: 'block',
			blocks: ['agncy/split'],
			transform: function( attributes, innerBlocks ) {
                           return createBlock( 'wpm/split', attributes, innerBlocks );
                        },
		}
	]
},
```

## How has this been tested?
This PR has not yet been tested, tests are in progress. 

## Types of changes
- Added an attribute to the transform function to regard innerBlocks
- Catched a possible error while rendering the block switcher where 'blocks' could be undefined due to a block not being registered

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

2018-11-16 14:08 UTC, Luehrsen commented
I consider this PR more or less done from a code standpoint, as it is really minor. 

However, I have not yet written (possible) e2e tests, as I have no idea how to do that. But I've updated the 'inner-blocks-templates' test plugin to add an appropriate block to test my two changes.

2018-11-16 17:07 UTC, jorgefilipecosta reviewed
Nice changes @Luehrsen, thank you for your contribution 👍 
Things tested well and the code looks good.
Given that we already have samples created here to be used in the tests, would it be possible to add a sample to https://github.com/WordPress/gutenberg/blob/master/docs/block-api.md#transforms-optional and document this enhancement to the API?

2018-11-16 17:34 UTC, Luehrsen commented
@jorgefilipecosta Done.

While reviewing that doc-page: Aren't the ES5 examples wrong in terms of curly-braces and 'content' in reality being 'attributes'?

2018-12-13 15:50 UTC, aduth requested changes
API-wise, this looks like a reasonable change which aligns with the general pattern of a "name, attributes, innerBlocks" triple when the name is already known.

Could you make the following changes?

- Additional unit tests for `switchToBlockType` in the `test/factory.js` file to cover new functionality
- A note in `packages/blocks/CHANGELOG.md` describing the new feature, bumping to a new minor "Unreleased" version ([reference](https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md#maintaining-changelogs))

2019-01-08 08:34 UTC, Luehrsen commented
@aduth I have updated the changelog as requested, but I am a total noob in terms of TDD, so any help with the unit test would be MUCH appreciated.

2019-01-09 19:38 UTC, aduth commented on packages/tests-e2e/plugins/inner-blocks-templates/index.js
> +					blocks: ['test/i-dont-exist', 'test/test-inner-blocks-no-locking', 'test/test-inner-blocks-locking-all', 'test/test-inner-blocks-paragraph-placeholder'],
Nitpick: This does not adhere to style standards. There should be a space after `[` and before `]`. There's another instance below as well in the `to` definition.

2019-01-09 19:38 UTC, aduth commented on packages/blocks/CHANGELOG.md
> +- `innerBlocks` is no available as a second attribute in the transform function
Typo: "no" should be "now". Makes it sound as the opposite of an introduced new feature 😅

2019-01-09 19:38 UTC, aduth commented on packages/blocks/CHANGELOG.md
> +## 6.0.5 (Unreleased)
Under SemVer, new functionality qualifies as a minor patch bump. Patch bumps are reserved for bug fixes.

https://semver.org/

```suggestion
## 6.1.0 (Unreleased)
```

2019-01-24 19:02 UTC, aduth approved these changes
I rebased and force-pushed to resolve conflicts and add missing unit tests.

Writing the test for the multi-blocks, it became apparent that it's super goofy to pass as arguments two arrays of the `attributes` and `innerBlocks` of the blocks being transformed, rather than just the array of blocks themselves. Alas, it seems what we're forced into doing to keep backward-compatibility.

2019-01-29 07:37 UTC, merged