Classic Editor plugin url should be translatable
WordPress/gutenberg pull request #11992
Opened 2018-11-16 18:17 UTC by dixitadusara

## Description
I have tried to make Classic Editor plugin URL translatable. Let me know if any changes require.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

2018-11-16 20:31 UTC, mkaz commented
Why does the URL need to be translatable?

2018-11-17 05:29 UTC, dixitadusara commented
I have submitted PR for issue #11983.

2018-11-17 11:55 UTC, swissspidy commented
@mkaz The plugin directory is available in multiple locales. For the German translation the correct link would be `https://de.wordpress.org/plugins/classic-editor/`, for example.

2018-11-17 11:58 UTC, swissspidy requested changes
Left notes about how this should be handled correctly.

2018-11-17 11:58 UTC, swissspidy commented on gutenberg.php
> +				__( 'The Block Editor requires JavaScript. Please try the <a href="https://wordpress.org/plugins/classic-editor/">Classic Editor plugin</a>.', 'gutenberg' )
URLs should not be part of translatable strings. We need to use a placeholder for this and make `'https://wordpress.org/plugins/classic-editor/'` translatable separately.

So the correct change would look like this:

```php
printf(
  // Translators: %s: https://wordpress.org/plugins/classic-editor/
  __( 'The Block Editor requires JavaScript. Please try the <a href="%s">Classic Editor plugin</a>.', 'gutenberg' ),
  __( 'https://wordpress.org/plugins/classic-editor/', 'gutenberg' )
);

2018-11-17 12:42 UTC, dixitadusara commented
Please review PR #12013

2018-11-17 12:44 UTC, swissspidy commented
Closing in favor of #12013 then.

2018-11-17 12:44 UTC, closed without merging