Extract the attributes from the editor's state shape to enhance performance
WordPress/gutenberg pull request #12268
Opened 2018-11-24 12:06 UTC by youknowriad

Implements https://github.com/WordPress/gutenberg/issues/11782#issuecomment-441024806

I did notice better performance while typing on blocks.

The PR still needs some polish but it's ready to be tested.

cc @sgomes @gziolo

2018-11-24 12:15 UTC, sgomes commented
Thanks, @youknowriad ! I've got a similar set of changes I'm working on, and are nearly done save for the tests, which still need some fixes. I also modified some of the other selectors to not rely on attributes, wherever possible, and added some memoization here and there.

For improvements, I measured 30% better results before I started fixing the tests; I'll run some benchmarks again once I'm finished there.

Shall I post a WIP of this on Monday so that we can compare PRs and decide which one to go with?

2018-11-26 01:12 UTC, noisysocks requested changes
The approach makes a lot of sense to me, and I am seeing a 1.6x (18 ms to 11 ms) reduction in time spent evaluating JavaScript while processing `keypress` events which is super encouraging.

I'm reluctant to include this in 5.0 since this has the potential to introduce unexpected regressions very late into the release process.

I'm seeing a few bugs when I test locally.

---

#### Pressing <kbd>Backspace</kbd> causes blocks to unexpectedly merge

![backspace](https://user-images.githubusercontent.com/612155/48987451-1fb09780-f173-11e8-901f-e601f613cc62.gif)

1. Create a new post
1. Type some text
1. Press <kbd>Enter</kbd> to create a new paragraph
1. Type some more text
1. Press <kbd>Backspace</kbd>

Expected result: The last character should be deleted.
Actual result: The two paragraph blocks merge.

#### Autosaves fail

1. Create a new post
1. Type some text
1. Without deselecting the block, wait for an autosave to happen

Expected result: The post should autosave.
Actual result: The autosave fails and an _Updating failed_ message appears.

#### Changing an existing block does not mark the post as dirty

1. Create a new post
1. Enter a title
1. Type some text into the initial paragraph block
1. Deselect the block
1. Click _Save Draft_
1. Re-select the block and modify its text

Expected result: The _Save Draft_ button should become active.
Actual result: The _Save Draft_ button remains disabled.

#### The / inserter no longer works

1. Create a new post 
1. Select the initial paragraph block
1. Type <kbd>/</kbd>

Expected result: The block autocompleted should appear.
Actual result: A / is typed and nothing else.

2018-11-26 09:57 UTC, gziolo commented on packages/editor/src/store/reducer.js
> +}
Yes, it would be much cleaner 👍

2018-11-26 09:57 UTC, gziolo commented on packages/editor/src/store/selectors.js
> +		state.editor.present.blocks.order,
Does order matter for the inserter items? Can we reason differently about nested blocks where it could have an impact? Do I miss anything?

2018-11-26 09:57 UTC, gziolo commented on packages/editor/src/store/selectors.js
> +		state.editor.present.blocks.byClientId,
The same about the order as above.

2018-11-26 17:40 UTC, youknowriad commented
Closing in favor of #12312

2018-11-26 17:40 UTC, closed without merging