Don't show "Change Permalinks" button for static front page
WordPress/gutenberg pull request #12500
Opened 2018-12-01 13:49 UTC by swissspidy

## Description

Hides the "Change Permalinks" button when editing the page that is set to be the static front page. You can't edit the slug for something that's being accessed via `https://example.com` only.

Fixes #12498.

## How has this been tested?
Tested this manually by changing the static front page settings and editing the page in Gutenberg.

## Screenshots

<img width="462" alt="screenshot 2018-12-01 at 14 43 54" src="https://user-images.githubusercontent.com/841956/49328878-c59b4200-f577-11e8-8f51-01cf3463ce55.png">
<img width="638" alt="screenshot 2018-12-01 at 14 43 40" src="https://user-images.githubusercontent.com/841956/49328879-c633d880-f577-11e8-8376-3fc8fa6b3b51.png">

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

2018-12-11 20:02 UTC, aduth reviewed
Implementation-wise, should this require the addition of a new field to the post endpoint, or rather should we consider using the setting value† and comparing it to the current post ID?

† It's not clear to me whether this is currently available, but seems like a reasonable expectation from `/wp/v2/settings`. Alternatively there is the `home` or `url` field from the root REST endpoint to compare against the post's URL.

2018-12-11 20:08 UTC, TimothyBJacobs commented
+1 to using the settings endpoint.

2018-12-13 08:58 UTC, swissspidy commented
Makes sense. Will update the PR accordingly.

2019-02-06 11:15 UTC, gziolo requested changes
I also see other comments now. So it seems to be doable without applying PHP changes and might validate the need of introducing `isFrontPage` selector 😅 

@swissspidy do you plan to revisit it in the near future? I'd be happy to help move forward with it.

2019-02-06 11:15 UTC, gziolo commented on lib/rest-api.php
> +	$response->data['is_front_page']      = 'page' === get_option( 'show_on_front' ) && (int) get_option( 'page_on_front' ) === $post->ID;
It looks like this function is now deprecated so this change should be applied directly in core:
https://github.com/WordPress/gutenberg/blob/master/lib/rest-api.php#L102

2019-02-06 11:15 UTC, gziolo commented on packages/editor/src/components/post-permalink/index.js
> +			isFrontPage: isFrontPage(),
It seems like this could follow other props and use `getEditedPostAttribute( 'is_front_page' )` directly.

2019-02-06 13:33 UTC, swissspidy commented
I haven't had time recently, but happy to revisit this. Need to dig back into Gutenberg code first though, so any help is appreciated.

2019-02-06 20:33 UTC, aduth commented
I think a first step we'll need here is the addition of `page_on_front` and `page_for_posts` option values to be made available from the `/wp/v2/settings` endpoint.

>Alternatively there is the `home` or `url` field from the root REST endpoint to compare against the post's URL.

To this point in my earlier comment, I think it could possibly work, but I think it's not enough to allow us to apply a similar treatment to the "Posts page".

2019-04-24 11:54 UTC, gziolo commented
@swissspidy I don't see any progress on this PR. Do you plan to work on it or would it be a better idea to close it and let other contributors to work on it based on your work and feedback shared in this PR?

2019-04-24 15:26 UTC, swissspidy commented
Unfortunately I don't have time to work on this at the moment. If someone else does, that would be greatly appreciated.

2019-04-24 15:26 UTC, closed without merging