Autop: Fix RegExp escaping copy/paste error
WordPress/gutenberg pull request #12614
Opened 2018-12-05 13:11 UTC by johngodley

[autop](https://github.com/WordPress/gutenberg/tree/master/packages/autop) contains a bunch of regular expressions copied from [core WordPress](https://core.trac.wordpress.org/browser/tags/4.9.8/src/wp-includes/formatting.php#L439). However, in JavaScript when `RegExp` is used the escaped regular expression characters need double-escaping because it's a string.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp for examples, and also elsewhere in [autop](https://github.com/WordPress/gutenberg/blob/master/packages/autop/src/index.js#L362).

This PR adds the extra backslashes.

Fixes #12610

## How has this been tested?
An extra unit test has been added that fixes #12610 which was caused by the missing backslash.

We really need extra unit tests for each of the changed instances so that it can't happen again.

2018-12-05 13:52 UTC, aduth commented
> If core has unit tests for `wpautop` then we could think about bringing them over.

The implementation wasn't the only thing which was ported over verbatim 😅 The tests are directly aligned with those in the PHP code.

https://github.com/WordPress/wordpress-develop/blob/master/tests/phpunit/tests/formatting/Autop.php

2018-12-05 13:53 UTC, aduth approved these changes
Nice find and fix 👍

2018-12-05 13:58 UTC, aduth requested changes
Actually, one thing worth checking. While it may be a non-issue, there's a difference in what's produced between the PHP and JS implementations.

Looking at https://github.com/WordPress/gutenberg/issues/12610#issuecomment-444489264, there's an `\n` character _inside_ the resulting markup's `</p>`, which is not present in the added test here. Should it be?

2018-12-05 14:00 UTC, aduth approved these changes
Ah, disregard, the explanation for the previous is the treatment of `\n` in single-quotes vs. double-quotes in PHP. It looks as expected with double-quoting:

```
wp> wpautop("Testing freeform block with some\n<div class=\"wp-some-class\">content</div>");
=> string(81) "<p>Testing freeform block with some</p>
<div class="wp-some-class">content</div>
"
```

2018-12-05 23:11 UTC, zachhale approved these changes
Great catch! I just ran into this as well and this fix looks good.

2019-01-14 18:12 UTC, zachhale commented
This is also causing issues for me. Is there a path to merging this?

2019-01-15 15:06 UTC, aduth commented
Yes, let's get it merged! I'll plan to do a rebase in case there were more recent snapshot changes which would need to be reflected here.

2019-01-15 15:43 UTC, merged