Update broken links
WordPress/gutenberg pull request #12660
Opened 2018-12-06 21:57 UTC by cagdasdag

There was 2 broken links. I changed same way with Data Module Reference page.

## Description
There was 2 broken links. I changed same way with Data Module Reference page.

## How has this been tested?
I changed same way with Data Module Reference page. It can't be problem because I looked to this page: https://github.com/WordPress/gutenberg/edit/master/docs/designers-developers/developers/data/README.md

## Screenshots 

## Types of changes

Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- My code follows the WordPress code style.
- My code follows the accessibility standards.
- My code has proper inline documentation.

2018-12-06 22:27 UTC, chrisvanpatten approved these changes
Excellent catches; thank you!

2018-12-07 12:11 UTC, chrisvanpatten requested changes

2018-12-07 12:11 UTC, chrisvanpatten commented on docs/designers-developers/developers/block-api/README.md
> +All blocks must be registered before they can be used in the editor. You can learn about block registration, and the available options, in the [block registration](../../docs/designers-developers/dev
Re-looking at this in the sober light of day and I realised the paths aren't deep enough. Actually needs to go up 4 levels, like so:

```suggestion
All blocks must be registered before they can be used in the editor. You can learn about block registration, and the available options, in the [block registration](../../../../docs/designers-developers/developers/block-api/block-registration.md) documentation.
```

2018-12-07 12:11 UTC, chrisvanpatten commented on docs/designers-developers/developers/block-api/README.md
> +The `edit` and `save` functions define the editor interface with which a user would interact, and the markup to be serialized back when a post is saved. They are the heart of how a block operates, so
```suggestion
The `edit` and `save` functions define the editor interface with which a user would interact, and the markup to be serialized back when a post is saved. They are the heart of how a block operates, so they are [covered separately](../../../../docs/designers-developers/developers/block-api/block-edit-save.md).
```

2018-12-07 14:54 UTC, chrisvanpatten approved these changes
Good to go; thanks so much @cagdasdag!

2018-12-07 15:08 UTC, cagdasdag commented
Thanks you so much for your interest @chrisvanpatten  :)

2018-12-07 15:09 UTC, merged