Scripts: Add lint-style script based on stylelint
WordPress/gutenberg pull request #12722
Opened 2018-12-09 17:07 UTC by gziolo

## Description
This PR adds `lint-style` to `wp-scripts` exposed by `@wordpress/scripts` package.

It helps enforce coding style guidelines for your style files. It uses [stylelint](https://github.com/stylelint/stylelint) with the set of default rules provided. You can override them with your own rules as described in [stylelint user guide](https://github.com/stylelint/stylelint/docs/user-guide.md).

## How has this been tested?
`npm run lint-css` still works properly in the repository.
`./node_modules/.bin/wp-scripts lint-style '**/*.scss'` also works properly

2018-12-09 19:10 UTC, adamsilverstein commented on packages/scripts/CHANGELOG.md
> +- Added support for `lint-style` script ([#XXXXX](https://github.com/WordPress/gutenberg/pull/XXXXX))
Assuming we need to add the PR# here?
```suggestion
- Added support for `lint-style` script ([#12722](https://github.com/WordPress/gutenberg/pull/12722))
```

2018-12-09 19:50 UTC, adamsilverstein approved these changes

2018-12-09 19:50 UTC, adamsilverstein commented
Looks good to me!

2018-12-09 23:18 UTC, ntwb commented on packages/scripts/README.md
> +* `npm run lint:js` - lints JavaScripts files in the whole project's directory.
```suggestion
* `npm run lint:js` - lints JavaScript files in the entire project's directories.
```

2018-12-09 23:35 UTC, ntwb commented
The `.stylelintrc.json → packages/scripts/config/.stylelintrc.json` change copies the Gutenberg specific `.stylelintrc.json` stylelint configuration to be distributed by `@wordpress/scripts` 

This file should remain in its current location and a new file should be created at `packages/scripts/config/.stylelintrc.json` that contains:

```json
{
	"extends": "stylelint-config-wordpress"
}

```

The `README.md` should be updated to:

```md
It uses [stylelint](https://github.com/stylelint/stylelint) with the [stylelint-config-wordpress](https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress) configuration per the [WordPress CSS Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/).
```

2018-12-09 23:36 UTC, ntwb requested changes
The notes at https://github.com/WordPress/gutenberg/pull/12722#issuecomment-445585669 should be addressed before merge

2018-12-10 20:40 UTC, gziolo commented
Thanks @ntwb for sharing your feedback. I'm in transit and will get back to it later this week. Unless you want to apply proposed changes yourself :)

2018-12-12 09:41 UTC, gziolo commented
> I originally wrote the above and what I was going to write here was about using `lint-style` as the command instead of `lint-css`, expanding on this thinking, we would want to add `lint-scss` for the scss config and then have `lint-style` run both `lint-css` and `lint-scss`?

What would be the difference? I assumed they are the same in the context of Gutenberg.

2018-12-12 09:44 UTC, gziolo commented on packages/scripts/README.md
> +* `npm run lint:css` - lints CSS files in the whole project's directory.
```suggestion
* `npm run lint:css` - lints CSS files in the entire project's directories.
```

2018-12-12 09:45 UTC, gziolo commented
@ntwb I applied all your suggestions in 668eebbfe647892f8d878d23067a2a9a82eb83f4.

2018-12-12 22:51 UTC, ntwb approved these changes

2018-12-19 11:38 UTC, ntwb approved these changes

2018-12-19 11:40 UTC, merged