Updating Embed URLs to Strip Trailing Slashes
WordPress/gutenberg pull request #12739
Opened 2018-12-09 21:01 UTC by alpinealex

## Description
Updating oEmbed URLs to have the trailing slash stripped from them to prevent the "Sorry, we could not embed that content." when the url is actually a valid embeddable URL.

## How has this been tested?
Manually - Adding new embed blocks to the page and testing different valid and invalid embed urls, with and without trailing slashes to ensure behavior still works as expected

## Types of changes
Bug fix (non-breaking change which fixes an issue): #12664

## Checklist:
- [X ] My code is tested.
- [X] My code follows the WordPress code style.
- [ X] My code follows the accessibility standards.
- [X ] My code has proper inline documentation.

2018-12-14 13:16 UTC, notnownikki requested changes
I'd rather this removed the trailing slash if the embed failed, just so we can support embed URLs that do end with a trailing slash. That should be easy enough to do in `componentDidUpdate`.

Also, please add an e2e test for the behaviour :)

2018-12-14 16:45 UTC, alpinealex commented
@notnownikki That makes sense. I'll give it a go and push an update once its ready.

2019-02-06 11:20 UTC, gziolo commented
@alpinealex do you plan to revisit this PR? It has been almost 2 months since the last update.

2019-02-06 14:18 UTC, arod2634 commented
@gziolo I don't think I'll be able to get to this anytime soon. Feel free to pass on to someone else if there is desired.

2019-02-07 08:08 UTC, gziolo commented
Thanks for your time invested to fix this issue. I will close this PR to let someone else take it as a starting point and open their own branch. Feel free to reopen and continue when you find some time for it 👍

2019-02-07 08:08 UTC, closed without merging