Add inspector controls
WordPress/gutenberg pull request #1278
Opened 2017-06-19 20:16 UTC by paulwilde

This is a rebased version of #1202 whilst also including #1198.

2017-06-20 17:54 UTC, aduth commented
There are some failing tests here due to missing `key` prop and trailing spaces:

https://travis-ci.org/WordPress/gutenberg/jobs/244678746

As a quality-of-life tip, when rebasing, you needn't create a separate pull request, but rather can force push atop your existing branch (e.g. `git push -f origin add/inspector-controls`)

2017-06-21 14:06 UTC, aduth requested changes

2017-06-21 14:06 UTC, aduth commented on blocks/inspector-controls/checkbox-control/index.js
> +			<label className="blocks-checkbox-control__label" htmlFor={ id }>
Missed this before. We shouldn't combine approaches of implicit and explicit labelling, between `htmlFor` and nesting input as a child of the label. From previous conversations with @afercia , `htmlFor` should be our preferred approach as it is better supported by screen readers.

https://github.com/WordPress/gutenberg/pull/527#discussion_r113741025

2017-06-21 20:13 UTC, aduth approved these changes

2017-06-21 20:14 UTC, aduth commented
This looks good to me 👍

2017-06-21 20:15 UTC, aduth commented on blocks/inspector-controls/toggle-control/index.js
> +import Toggle from 'components/form-toggle';
Minor: We should import from the top-level, i.e. `import { withInstanceId, Toggle } from 'components';`

2017-06-21 20:15 UTC, aduth commented on blocks/inspector-controls/select-control/index.js
> +import { isEmpty } from 'lodash';
`lodash` is an external dependency, not a WordPress dependency.

2017-06-21 20:16 UTC, aduth commented on blocks/inspector-controls/radio-control/index.js
> +import { isEmpty } from 'lodash';
Same note about Lodash from previous.

2017-06-21 20:42 UTC, aduth commented on blocks/inspector-controls/toggle-control/index.js
> +import { withInstanceId, Toggle } from 'components';
Oof, while this is preferred, we're also not currently exporting `Toggle` from `components/index.js` as we should be.

2017-06-23 10:09 UTC, youknowriad commented
I took the liberty to update this to fix the ToggleControl issue. I'm going to merge this to unblock #1191

Thanks awesome work here.

2017-06-23 10:14 UTC, merged