Add a line to PR template for developer documentation
WordPress/gutenberg pull request #12822
Opened 2018-12-12 17:51 UTC by mkaz

## Description

A meta change that applies only to Github repo, adding a line to the PR template around developer documentation.

Developer documentation is critical for making a platform extendable, developers need to know the proper way to extend a feature, or in a sense that does may not even exist.

We discussed the importance of documentation in #docs Slack channel, and thought updating PR template is one way to call out to developers to keep it in mind.

2018-12-12 18:03 UTC, chrisvanpatten requested changes
Love this idea. It's a nice subtle nudge. (Why didn't I think of this?!)

2018-12-12 18:03 UTC, chrisvanpatten commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I've included developer documentation when appropriate <!-- Handbook: https://wordpress.org/gutenberg/handbook/designers-developers/ -->
Adding a period so we're consistent.

```suggestion
- [ ] I've included developer documentation if appropriate. <!-- Handbook: https://wordpress.org/gutenberg/handbook/designers-developers/ -->
```

2018-12-12 18:11 UTC, chrisvanpatten approved these changes
LGTM; hoping to get a maintainer ✅ as well.

2018-12-13 10:01 UTC, gziolo approved these changes
Second that 👍

2018-12-13 18:36 UTC, merged