Add JSHint ESLint config
WordPress/gutenberg pull request #12840
Opened 2018-12-13 13:02 UTC by ntwb

## Description

This pull request is a follow up to #12763 and seeks to add a new `jshint` ESLint shared configuration of the existing WordPress [`.jshintrc`](https://core.trac.wordpress.org/browser/trunk/.jshintrc) file.

This pull request makes available a "drop-in" ESLint JSHInt configuration that will allow WordPress to easily transition away from JSHint to ESLint per the [#WP31823](https://core.trac.wordpress.org/ticket/31823) ticket whilst the significant legacy JavaScript is updated to adhere to the WordPress JavaScript Coding Standards in the `@wordpress/eslint-plugin/recommended` ESLint configuration.

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

2018-12-13 13:07 UTC, youknowriad commented
Not certain how I feel about adding this to the package, if it's for legacy purpose, I propose using it in WordPress directly in addition to the eslint package, instead of adding it to the reusable package

2018-12-14 09:30 UTC, ntwb commented
I included it in the package as for any existing plugin, theme, or core that is looking to update their build tooling to switch from JSHint to ESLint can do so using a backwards compatible set of rules.

The rules themselves in the configuration are not all similarly named so without some knowledge of JSHint and ESLint making such a ruleset configuration would not be a trivial task. This same approach would be required to have to first disable all the unrequired rules included in `@wordpress/eslint-plugin/recommended` to then add the rules I've proposed in this PR.

I fully plan to use this ruleset myself in the plugins I'm associated with whilst the teams get familiar with ESLint work can begin on migrating to the full `@wordpress/eslint-plugin/recommended` configuration as time permits.

2018-12-14 12:02 UTC, gziolo requested changes
I think we should clarify when `jshint` config should be used. Otherwise I think the explanation @ntwb shared makes a lot of sense. We can remove this config when introducing next breaking change as it looks like a temporary addition.

2018-12-16 13:04 UTC, ntwb commented on packages/eslint-plugin/README.md
> +An ESLint equivalent of WordPress' `.jshintrc` JSHint configuration is also available by defining your own project's `.eslintrc` file as:
Great suggestion, thanks

2018-12-17 11:34 UTC, gziolo approved these changes
Code wise looks good to me. It just needs the decision whether we want to have it included. I am personally fine with having it introduced.

2018-12-18 14:01 UTC, youknowriad commented
You all convinced me, I'm fine to include now. We can remove it later if needed.

2018-12-19 08:25 UTC, merged