Updated all references of classic editor to be a proper noun (Classic Editor)
WordPress/gutenberg pull request #12856
Opened 2018-12-13 21:22 UTC by garrett-eclipse

## Description
This PR is mostly text change and no functionality change. It updates all reference to 'classic editor' and 'Classic editor' to be a proper noun 'Classic Editor' so as to be consistent with the current naming convention in core.

## How has this been tested?
Only tested that it didn't break anything.

## Types of changes
Mostly comment changes, there was one string change and a couple translator comment changes.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

2018-12-13 21:32 UTC, chrisvanpatten approved these changes
Looks good to me; seems like a simple/sensible change.

2018-12-13 21:41 UTC, garrett-eclipse commented
Thanks for the review @chrisvanpatten

2018-12-13 21:43 UTC, aduth commented
cc @pento , who I know holds opinions on the matter 😄 

>`Classic Editor` is the plugin, `classic editor` is the UI.

https://wordpress.slack.com/archives/C02RQBWTW/p1542961107095100

([link requires registration](https://make.wordpress.org/chat/))

2018-12-13 21:45 UTC, chrisvanpatten commented
That's a fair point. I think in most of these cases it's still reasonable to use proper noun Classic Editor, but perhaps change text like "in the Classic Editor" to "in Classic Editor" so it's clearer it's referring to a specific plugin/experience.

2018-12-13 22:04 UTC, garrett-eclipse commented
Thanks guys, I'll update once the convention is set. I also have a ticket in core for similar strings;
https://core.trac.wordpress.org/ticket/45634#comment:2
*I'll hold on any patching until I understand the convention.

2018-12-14 13:13 UTC, chrisvanpatten requested changes
Based on @Pento's comment, and after a re-read and re-understanding of the issue, it does seem appropriate for all these cases to be lower case.

However closing the PR would not be enough as there are a few instances in these files where we have `Classic editor` which should instead be `classic editor` (all lower). I noticed it in the meta box compatibility readme and in gutenberg.php

Are you able to update those instances?

2018-12-15 19:54 UTC, garrett-eclipse commented
Thank you @pento I appreciate that, the context is key there for sure. So 'Classic Editor' as a proper noun should only be used in reference to the plugin and in that case wouldn't be translated. And 'classic editor' as a ui reference is a descriptor for an object so would be lowercase, unless it's the first term in a sentence, and it would be considered translatable.
*Can you confirm that 'Classic Editor' the plugin shouldn't be translated but 'classic editor' the ui interface should? If so I'll look into introducing translator notes and best practices as @swissspidy suggested;
https://core.trac.wordpress.org/ticket/45634#comment:6

I'll circle back on core ticket (https://core.trac.wordpress.org/ticket/45634#comment:6) as it seems those references and the ones to 'block editor' are concerning the ui and should be lowercase and translated.

And in TwentyNineteen It's hard to tell if 'classic editor toolbar' is refering to UI or plugin so will have to look at that PR;
https://github.com/WordPress/twentynineteen/pull/740

CC @faisal-alvi - I'm looking at the PR/patches you provided (thank you) and just trying to make sure the convention @pento put forward adheres across the board.

2018-12-15 19:55 UTC, garrett-eclipse commented
Thanks @chrisvanpatten and @aduth as well I feel like I'm understanding the convention more and will probably convert this ticket to introducing translator comments to indicate to i18n the context

2018-12-18 16:11 UTC, chrisvanpatten commented
@garrett-eclipse If the new approach will be a big difference from this PR would you be okay to close it and open a new one? Just to keep things easier to track. Thanks 👍

2018-12-18 18:05 UTC, garrett-eclipse commented
Thanks @chrisvanpatten, sounds like a plan, I'll circle back on this when I have a chance to setup a new PR.

2018-12-18 18:05 UTC, closed without merging