REST Block Renderer: Accept the className attribute by default and add a filter
WordPress/gutenberg pull request #13249
Opened 2019-01-08 21:48 UTC by akirk

## Description
When creating a block with a `ServerSideRender` component and using the "Additional CSS Class" block option, the rendering breaks with this HTTP response:
```
{"code":"rest_invalid_param","message":"Invalid parameter(s): attributes","data":{"status":400,"params":{"attributes":"className is not a valid property of Object."}}}
```
## How has this been tested?

The above HTTP request works fine with this patch applied.

## Screenshots

<img width="431" alt="screenshot 2019-01-08 at 22 42 28" src="https://user-images.githubusercontent.com/203408/50860636-c1dcb580-1396-11e9-80a2-21ddb4d53e66.png">

<img width="267" alt="screenshot 2019-01-08 at 22 40 51" src="https://user-images.githubusercontent.com/203408/50860546-922dad80-1396-11e9-913a-e2844dcc66fa.png">

## Types of changes
This adds the `className` attribute by default. It also adds a filter that allows more properties to be added (for example when using https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#editor-blockedit)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows the accessibility standards.
- [x] My code has proper inline documentation.
- [x] I've included developer documentation if appropriate.

2019-01-09 00:15 UTC, Soean requested changes
Minor changes to match the WPCS

2019-01-09 00:15 UTC, Soean commented on lib/class-wp-block-type.php
>  					'layout' => array(
```suggestion
					'layout'    => array(
```

2019-01-09 00:15 UTC, Soean commented on lib/class-wp-block-type.php
>  				'layout' => array(
```suggestion
				'layout'    => array(
```

2019-01-09 15:20 UTC, akirk commented
Submitted to core based on @youknowriad's recommendation in the #core-editor chat: https://core.trac.wordpress.org/ticket/45882

2019-01-09 15:20 UTC, closed without merging

2019-05-17 03:40 UTC, phpbits commented
Custom attributes added via `blocks.registerBlockType` JS filter are having the same error. JS filters should communicate to PHP displays or add similar filters for server side rendering. Thanks!