Update/stricter block validation
WordPress/gutenberg pull request #1345
Opened 2017-06-21 18:14 UTC by njpanderson

This is a PR for resolution to issue #362.

2017-06-26 17:01 UTC, njpanderson commented
Anyone fancying a look at this? It's regarding #362.

2017-06-27 08:43 UTC, youknowriad commented on blocks/api/registration.js
> +			( settings && typeof settings.save !== 'function' ) ) {
Could we write this like?

```js
if ( 
  ! settings  ||
  ( settings && typeof settings.save !== 'function' )
)
```

I think this pattern is the one used in the Gutenberg code

2017-06-27 08:45 UTC, youknowriad commented on blocks/api/registration.js
> +			( settings && typeof settings.save !== 'function' ) ) {
Minor: should we use `isFunction` from `lodash`? It handles a special case for us.

2017-06-28 06:38 UTC, njpanderson commented
Have amended, @youknowriad.

2017-06-28 09:25 UTC, youknowriad commented on blocks/api/registration.js
> +			( settings && ! isFunction( settings.save ) ) ) {
Could we put this test in one line too?

2017-06-28 09:26 UTC, youknowriad commented on blocks/api/registration.js
> +	if ( settings && 'edit' in settings && ! isFunction( settings.edit ) ) {
I guess the `settings` test is useless here, because we already checked for its existence above?

2017-06-29 17:44 UTC, njpanderson commented
Both issues sorted in latest push.

2017-06-29 17:58 UTC, youknowriad approved these changes
LGTM 👍  Thanks for the updates

2017-06-29 17:59 UTC, youknowriad commented
@nylen do you have any other thoughts on this. I know you're behind the validation we had in the first place.

2017-06-29 19:56 UTC, nylen requested changes
Generally seems fine to me. Some notes above. We should also make sure similar validation is in place on the server side, but for now this would be for the `render` function.

2017-06-29 19:56 UTC, nylen commented on blocks/api/registration.js
> +	if ( ! settings || ( settings && ! isFunction( settings.save ) ) ) {
The `settings &&` check here is redundant - by this point in the conditional, we already know that `settings` is set.

2017-06-29 19:56 UTC, nylen commented on blocks/api/registration.js
> +			'A "save" function must be created within the block settings.'
Let's clean up this message a bit:

> The "save" property must be specified and must be a valid function.

2017-06-29 19:56 UTC, nylen commented on blocks/api/test/factory.js
> +	const defaultBlockType = { save: noop };
`defaultBlockSettings` would be a better name here and below.

2017-06-29 19:57 UTC, nylen commented
> We should also make sure similar validation is in place on the server side, but for now this would be for the `render` function.

To clarify: this is fine for a separate PR.

2017-06-30 19:37 UTC, njpanderson commented
@nylen / @youknowriad - Both changes above have been made.

2017-07-03 09:59 UTC, nylen approved these changes
Looks good to me. Thanks for working on this!

2017-07-03 10:00 UTC, merged

2017-07-04 14:38 UTC, swissspidy commented
Note that because of this there's a bunch of warnings when running the unit tests.

2017-07-05 08:20 UTC, swissspidy commented
Can de `validate-block-settings` branch be deleted?

2017-07-05 18:40 UTC, njpanderson commented
Apologies - I've been quite tied up for a few days.

Branch has been deleted.

In answer to your remark regarding warnings, @swissspidy - I'd fixed all of them on the tip of my branch but I suspect due to the lead time more old patterns of use for the registration have crept in. Not sure who's down for fixing them but happy to work on another issue for it if there is one.

2017-07-06 22:16 UTC, nylen commented
These warnings should really be errors that fail the build, which will prevent them from reoccurring.  See #1769.