Add toggle for post sticky status on editor #1313
WordPress/gutenberg pull request #1374
Opened 2017-06-22 14:14 UTC by jasonagnew

Added a toggle under Post Settings -> Status & Visibility for post sticky status.

http://share.agnew.co/lqC7JP

Should this option show if the post is not set to Public?
If the post is set to Private or Password Protected should we set Sticky back to false?

Fixes: #1313

2017-06-23 11:25 UTC, youknowriad requested changes
Thanks for the PR. This works great.

One point though needs to be addressed. I think the `sticky` toggle is only enabled for the "post" post type, we should make sure to hide the toggle for other post types

2017-06-23 11:25 UTC, youknowriad commented on editor/sidebar/post-sticky/index.js
> +	const onTogglePostSticky = () => props.editPost( { sticky: ! postSticky } );
Minor: I'd personally bake this in the `mapStateToDispatch` providing a `onTogglePostSticky` prop instead that way the `PostSticky` presentational component would deal only with the sticky value and a simple callback. Doesn't need to know about `editPost`.

2017-06-26 10:09 UTC, jasonagnew commented
@youknowriad Thanks for the feedback, I've made those changes. I wasn't completely sure best way to do `onTogglePostSticky` in `mapStateToDispatch` but I gave it a go.

2017-06-26 11:08 UTC, youknowriad commented on editor/sidebar/post-sticky/index.js
> +			postType: getEditedPostAttribute( state, 'type' ),
Minor: Should we use the newly introduced `getCurrentPostType` selector?

2017-06-26 11:11 UTC, youknowriad commented on editor/sidebar/post-sticky/index.js
> +				dispatch( editPost( { sticky: ! postSticky } ) );
Yeah, you're right, this looks a bit weird to have  `!` here. Thinking we should rename `onTogglePostSticky` to `onUpdateSticky` and directly pass the updated value. Thoughts?

2017-06-26 12:42 UTC, jasonagnew commented
Hey @youknowriad Thanks for your patience. I updated it to use the new `getCurrentPostType` selector and I think calling it `onUpdateSticky` and moving the logic means it works the same as `PostSchedule`

2017-06-26 12:48 UTC, youknowriad approved these changes
Nice 👍 Let's get this merged.

Thanks for working on this.

2017-06-26 12:50 UTC, merged