Check that .rel is available too
WordPress/gutenberg pull request #13983
Opened 2019-02-20 19:13 UTC by hypest

## Description
`node.rel` can be missing on native mobile so, guard for it.

## How has this been tested?
Using this gutenberg-mobile PR: TBD

## Types of changes
Adds a guard for `node.rel` to be present before setting it.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

2019-02-20 20:02 UTC, aduth requested changes
What's meant by "available"? In a browser, an anchor node may not have an assigned `rel` attribute, at which point `node.rel` would be an empty string, thus falsey and as proposed here skipping the expected logic to assign the `'noreferrer noopener'` value. It seems to me the entire purpose for this code to exist in the first place is to be assigning that value when not otherwise assigned. But if that's the case, then why aren't unit tests failing?

2019-02-20 21:03 UTC, koke commented
@hypest I think this is a bug in jsdom-jscore. The error message we are seeing has an error message that’s coming from JavascriptCore and [html.js:110](
https://github.com/iamcco/jsdom-jscore-rn/blob/master/lib/jsdom/level2/html.js#L110)

If you look at the getter in [line 95](
https://github.com/iamcco/jsdom-jscore-rn/blob/master/lib/jsdom/level2/html.js#L95) you can see that they are checking if normalize is available before calling it and referencing [this old issue](
https://github.com/jsdom/jsdom/pull/491). Since that is not defined and `n` is actually the `rel` string, it seems like it’s calling [String.prototype.normalize()](
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) with an invalid argument (the rel value)

2019-02-21 00:16 UTC, hypest commented
> It seems to me the entire purpose for this code to exist in the first place is to be assigning that value when not otherwise assigned.

Hmm, that makes sense @aduth , I didn't look at it like that before. Under that light yeah, this change so far is just wrong. Will revise or drop the PR altogether! Thanks for the review pass!

2019-02-21 00:28 UTC, hypest commented
> I think this is a bug in jsdom-jscore.

Ahh, it does look like that @koke , I see. Indeed, it seems that the failing call had to be guarded by a check for (not) String but it's not.

The jsdom-jscore library we're using hasn't been updated for the last 4 years so, it seems we'll need to fork it to accommodate us at the time being. I will close this PR and fork+patch the library instead. We can explore options after fixing this.

2019-02-21 00:28 UTC, closed without merging

2019-02-21 18:52 UTC, aduth commented
It's still curious to me that the build was passing. My previous comment was in-part a not-so-subtle hint that we should improve coverage, but in fact there are tests which are meant to verify its behavior:

https://github.com/WordPress/gutenberg/blob/211f65dd854fc1f7d7e54782863ad0629abeff41/packages/blocks/src/api/raw-handling/test/phrasing-content-reducer.js#L24-L28

¯\\\_(ツ)_/¯