Updates example code references
WordPress/gutenberg pull request #14007
Opened 2019-02-21 13:37 UTC by AdamMarton

See original issue fore more details: https://github.com/WordPress/gutenberg/issues/14005

## Description
Updates references to the [actual repository](https://github.com/WordPress/gutenberg-examples) linked in [Blocks Tutorial](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/).

## How has this been tested?
Manually.

## Screenshots 

## Types of changes
References in code snippets.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

2019-02-22 02:18 UTC, mkaz requested changes

2019-02-22 02:18 UTC, mkaz commented on docs/designers-developers/developers/tutorials/block-tutorial/writing-your-first-block-type.md
> +	register_block_type( 'gutenberg-examples/01-basic', array(
The gutenberg-examples repo calls the block `example-01-basic`, it does duplicate the example name

```suggestion
	register_block_type( 'gutenberg-examples/example-01-basic', array(
```

2019-03-22 15:28 UTC, gziolo commented on docs/designers-developers/developers/tutorials/block-tutorial/writing-your-first-block-type.md
> +	register_block_type( 'gutenberg-examples/example-01-basic', array(
```suggestion
register_block_type( 'gutenberg-examples/example-01-basic', array(
```

2019-03-22 15:30 UTC, gziolo commented on docs/designers-developers/developers/tutorials/block-tutorial/writing-your-first-block-type.md
> +		plugins_url( '01-basic/block.js', __FILE__ ),
```suggestion
		plugins_url( 'block.js', __FILE__ ),
```

2019-03-22 15:32 UTC, gziolo commented
@mkaz and @AdamMarton - there are two issues I spotted which should be addressed and this should be good to go.

2019-03-23 03:31 UTC, mkaz commented
This PR is out of date and will be replaced by the major update to the block tutorial in #14584 
The other PR updates all the sections to match the new changes in Gutenberg Examples.

2019-03-25 07:14 UTC, gziolo commented
Let's focus on #14584 in that case. I'm closing this PR. @AdamMarton thank you for your contribution and helping to improve documentation 🙇

2019-03-25 07:14 UTC, closed without merging