Added minimum font-size - prevent negative values
WordPress/gutenberg pull request #14246
Opened 2019-03-05 19:52 UTC by Popardowski

## Description
Added minimum font-size value to the 'font-size-picker' to prevent negative values. Set number input "min" attribute to 9 px as reasonable minimum font-size.

## Types of changes
Fixing negative font sizes that makes text 'disappear'.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

2019-03-05 19:56 UTC, chrisvanpatten commented
Thanks for the PR @Popardowski!

I'd be curious to hear what other maintainers/reviewers thing but personally I think it'd be good to still allow font sizes between 0 and 9 (in other words make the minimum 0). While those use-cases are probably rarer, I'm not sure it's good for us to be too prescriptive here since the idea of the custom size is that it would be custom. Putting a limitation on "custom" feels a little wrong to me.

Good catch though; definitely important that we don't allow negatives!

2019-03-06 07:18 UTC, Popardowski commented
@chrisvanpatten I've stuck on that minimum 9 px font-size since Opera didn't render smaller fonts .. many years ago 🙃

2019-04-24 14:04 UTC, aduth requested changes
Could you share more information about the Opera bug and whether it would remain relevant today? My primary concern here would be to resolve the issue of negative values, which are invalid by the specification:

>A length value specifies an absolute font size (independent of the user agent’s font table). **Negative lengths are invalid.**

https://www.w3.org/TR/css-fonts-4/#font-size-prop

For that reason, I'd suggest to assign the `min` to `0`.

2019-04-24 16:47 UTC, Popardowski commented
@aduth 
> Could you share more information about the Opera bug and whether it would remain relevant today? 

That was more like a feature of the Opera that doesn't display fonts smaller than 9px (in their mind that text was/is unreadable). That could be changed in the browser settings, but as I see that options has gone. 

Anyway I would ignore that Opera's issue and set the `min` to `0` as well.

2020-03-19 08:45 UTC, youknowriad commented
Looks like this PR is still relevant. Is the action item to use min="0" and ship?

2020-03-26 21:26 UTC, aduth commented
Yes, sorry I apparently failed to follow-up on the previous response. I think `min="0"` is sensible.

2020-05-08 01:33 UTC, ZebulanStanphill commented
#21815 (which got merged 2 weeks ago) set a minimum font size, so I'm closing this PR.

2020-05-08 01:33 UTC, closed without merging