Fix: Pasting captions without an image fails
WordPress/gutenberg pull request #14365
Opened 2019-03-10 23:53 UTC by dmsnell

Fixes #13527
See original work in #12315

When pasting content which includes the `[caption]` shortcode we assume
that the content is well-formed (that there is not only an `<img />` in
there but also in the first position).

In this patch we're going to resolve the problem by rewriting the code
to specifically remove `IMG` nodes instead of removing the first
`Element` node.

In this commit we're adding some failing tests.

> LANNISTER MOB <

## Testing

So far we can test by running the unit-test suite on the affected file.

```bash
npm run test-unit packages/block-library/src/image
```

2019-03-11 10:46 UTC, gziolo approved these changes
Awesome teamwork Lannister! Thanks for fixing it with the unit test included. I'd love to see more PRs like this in the future :)

2019-03-11 10:49 UTC, gziolo requested changes
Too soon. There is a failing unit test:

```
FAIL test/integration/blocks-raw-handling.spec.js (12.199s)
  ● rawHandler › should convert a caption shortcode with link
    expect(value).toMatchSnapshot()
    Received value does not match stored snapshot "rawHandler should convert a caption shortcode with link 1".
    - Snapshot
    + Received
      "<!-- wp:image {"id":754,"align":"none"} -->
    - <figure class="wp-block-image alignnone"><a href="http://build.wordpress-develop.test/wp-content/uploads/2011/07/100_5478.jpg"><img src="http://build.wordpress-develop.test/wp-content/uploads/2011/07/100_5478.jpg?w=604" alt="Bell on Wharf" class="wp-image-754"/></a><figcaption>Bell on wharf in San Francisco</figcaption></figure>
    + <figure class="wp-block-image alignnone"><a href="http://build.wordpress-develop.test/wp-content/uploads/2011/07/100_5478.jpg"><img src="http://build.wordpress-develop.test/wp-content/uploads/2011/07/100_5478.jpg?w=604" alt="Bell on Wharf" class="wp-image-754"/></a><figcaption><a href="http://build.wordpress-develop.test/wp-content/uploads/2011/07/100_5478.jpg"></a> Bell on wharf in San Francisco</figcaption></figure>
      <!-- /wp:image -->"
      271 | 	it( 'should convert a caption shortcode with link', () => {
      272 | 		const HTML = readFile( path.join( __dirname, 'fixtures/shortcode-caption-with-link.html' ) );
    > 273 | 		expect( serialize( rawHandler( { HTML } ) ) ).toMatchSnapshot();
          | 		                                              ^
      274 | 	} );
      275 | 
      276 | 	it( 'should convert a caption shortcode with caption', () => {
      at Object.toMatchSnapshot (test/integration/blocks-raw-handling.spec.js:273:49)
```

It looks like image should be removed together wit all wrapping html tags like anchor in this case.

2019-03-15 22:30 UTC, gwwar commented
@gziolo this is ready for another look. I also added another unit test to account for the extra case.

2019-03-18 06:42 UTC, gziolo approved these changes

2019-03-18 06:44 UTC, gziolo commented
Thanks for addressing my comment. This change fixes this newly introduced side effect of improved handling 👍

2019-03-18 06:44 UTC, merged