Modal Component: rename to Dialog
WordPress/gutenberg pull request #14437
Opened 2019-03-14 15:41 UTC by drw158

## Description
I have renamed everything from `modal` to `dialog` in the components package folder.

I'm not sure what all needs to be done to do this. This PR is to get the conversation going.

See #14195

## How has this been tested?
This PR has not been tested.

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

2019-03-14 17:42 UTC, aduth commented
To note, this is a breaking change, and will need a backwards-compatibility story.

2019-03-22 15:55 UTC, afercia commented
No strong objections. Worth noting design terminology is often different (and not so accurate) compared to technical terminology.

"Modal" is certainly a behavior. This kind of UI is more appropriately a "Dialog Window". Worth noting that dialogs can be [non-modal or modal](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal). Thus, to accurately describe this component, the correct term would be "modal dialog".

2019-03-25 09:24 UTC, gziolo requested changes
> To note, this is a breaking change, and will need a backwards-compatibility story.

This might be very complex as this PR changes not only the name of the component but also all CSS class names.

Is there any way to keep the existing component unchanged and introduce `Dialog` component which would co-exist in harmony? @youknowriad any thoughts on this backward compatibility challenge? :)

2019-03-25 09:24 UTC, gziolo commented on packages/components/src/modal/README.md
> +# Dialog
Folder name should be updated as well. At the moment it's: ` packages/components/src/modal`.

2019-03-25 09:24 UTC, gziolo requested changes
> To note, this is a breaking change, and will need a backwards-compatibility story.

This might be very complex as this PR changes not only the name of the component but also all CSS class names.

Is there any way to keep the existing component unchanged and introduce `Dialog` component which would co-exist in harmony? @youknowriad any thoughts on this backward compatibility challenge? :)

2019-03-25 09:42 UTC, youknowriad commented
I think the minimum here is:

 - Proxy `wp.components.Modal` to `wp.components.Dialog`.
 - Keep the old classNames in places (duplicate all the classNames)
 - Write a devnote about this change.

Separately as raised in #core-editor discussions too:

 - We should write a document in the handbook to clearly explain what is considered an official API and what is not.

2019-04-24 11:46 UTC, gziolo commented
@drw158 do you still plan to work on this one or should we close this PR and the parent issue based on the feedback received?

2019-04-24 14:25 UTC, drw158 commented
It still should be done, but I don't have the technical knowledge to complete the tasks needed to get this done. I would prefer to keep the issue open until the issue is resolved. The PR can be closed until someone is able to work on it.

2019-04-24 14:25 UTC, closed without merging