Button: Add "Start on a new line" option (#1473)
WordPress/gutenberg pull request #1512
Opened 2017-06-27 16:54 UTC by truongwp

2017-06-27 16:56 UTC, truongwp commented
I will pull and rebase to avoid marge commit.

2017-09-22 13:18 UTC, gziolo commented
It looks like it addresses #1473. Can you rebase with master and provide testing instructions? I'm happy to help to land it into master.

2017-09-22 13:19 UTC, gziolo requested changes
It looks like it addresses #1473. Can you rebase with master and provide testing instructions? I'm happy to help to land it into master.

2017-09-23 01:49 UTC, truongwp commented
@gziolo I rebased with master. Below is the problem and the test case:

I want to align my button to the right, then next line is a paragraph, like this:

![selection_001](https://user-images.githubusercontent.com/19748318/30769062-c44126f0-a03b-11e7-9217-799507685d8a.png)


But if I align my button right, it floats and the second paragraph goes beside the button:

![selection_002](https://user-images.githubusercontent.com/19748318/30769064-c876df3a-a03b-11e7-841e-7018579bf7fb.png)

2017-09-23 08:51 UTC, youknowriad commented
related #1473

2017-09-25 10:07 UTC, gziolo commented
> With the "Start on a new line" option, the button is always on a line, even when floats left, right. We can discuss about "Start on a new line" phrase. I can't find a better phrase.

@karmatosed or @jasmussen any suggestions on the name this option?

2017-09-25 11:19 UTC, truongwp commented
What about this phrase: "Stand on a line"

2017-09-25 11:52 UTC, jasmussen commented
> What about this phrase: "Stand on a line"

I like that.

2017-09-25 12:25 UTC, youknowriad commented
Just a note that this is probably something we can handle as an "extension" to blocks, the same way we're thinking of refactoring the custom className and anchor properties. See here for more details https://github.com/WordPress/gutenberg/issues/2474#issuecomment-327875802

2017-09-25 14:32 UTC, gziolo approved these changes

2017-09-25 14:33 UTC, gziolo commented
Code looks good, it works as advertised. It only needs option name to be updated and should be good to merge. Thank you very much for working on that one.

2017-09-25 14:38 UTC, truongwp commented
@gziolo Thank you. Do I need to update the commit to change option name?

2017-09-25 15:19 UTC, gziolo commented
That would be the best. You can also add another commit and we can squash before merge.

2017-09-25 15:27 UTC, truongwp commented
I updated the commit with option text is "Stand on a line"

2017-09-26 08:12 UTC, gziolo commented on blocks/library/button/index.js
> +					{clearControl}
@truongwp one more little thing before we merge. Can you add spaces around `clearControl` to satisfy WordPress coding guidelines? I missed that yesterday, thanks!

2017-09-26 08:18 UTC, truongwp commented
@gziolo I added spaces around `clearControl`. Just wait CI to check code :D

2017-09-26 09:14 UTC, gziolo commented
Travis CI seems to be unhappy with this change which is surprising and completely unexpected. I'm trying to find out what has happened on Slack's #core-editor channel.

2017-09-26 09:17 UTC, truongwp commented
Sometimes I meet this error. I think it isn't coding error.

2017-09-29 02:19 UTC, truongwp commented
I moved "Stand on a line" options to below of block description.

2017-10-02 09:42 UTC, gziolo commented
This is how it looks like at the moment:

![screen shot 2017-10-02 at 11 38 07](https://user-images.githubusercontent.com/699132/31071921-33fdfcbc-a766-11e7-9919-0e3804aade08.png)


> I moved "Stand on a line" options to below of block description.

@jasmussen I'm not familiar with the patterns here, can you confirm it fits well?

Another question is if we should remove ```max-width: 370px``` when `Stand on a line` is enabled? It seems like it should take all space in such case, similar to when it's center aligned.

2017-10-06 09:47 UTC, gziolo commented
Okey, it looks like this width issue is unrelated to this change. So let's fix it in another PR if we agree that it makes sense. Merging this one as it is. @truongwp thanks for your contribution 👍

2017-10-06 09:47 UTC, merged