Remove aria-label from block inserter list item
WordPress/gutenberg pull request #15382
Opened 2019-05-01 23:42 UTC by brentswisher

## Description
Removed an aria-label that was flagged as unnecessary in item WUT-18 of the WPCampus accessibility audit. Fixes #15337.

**Note:**
There is a code comment from @ellatrix that the aria-label was added to handle IE11 and JAWS2018. I do not have access to that configuration, so it should be tested by someone who does before this is merged to prevent a possible recursion. 

In my opinion, if the aria-label makes it work in IE11/Jaws that should override the potential issue brought up in the audit and it should stay.

## How has this been tested?
Tested with Apple VoiceOver on a Mac and it still reads out the button text correctly when navigated to with the keyboard. 

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate.

2019-05-06 07:57 UTC, gziolo requested changes
It looks like a big number of e2e tests depend on the `aria-label` attribute removed in this PR. You can run `npm run test-e2e` to see more details. I think there are a few places where it would have to be updated to make it pass. This label is also present in the `span` so it should be a straightforward change.

2019-05-06 08:25 UTC, ellatrix commented
@brentswisher I didn't add this code. I just moved it. After tracking it down, it turns out it was added in #5828.

2019-05-06 13:17 UTC, afercia commented
That comment was added by me 🙂 See https://github.com/WordPress/gutenberg/issues/15337#issuecomment-489424090

> The `aria-label` and the visible text use the same variable. Originally introduced in #5828 to fix an issue specific to Internet Explorer 11 and JAWS, see #5827. Should be tested again to make sure it's still relevant.

2019-05-06 13:52 UTC, afercia reviewed
Tested again with Internet Explorer 11 and JAWS 2018. Looks like the `aria-label` fix is no longer necessary. From an accessibility perspective can be removed safely.
Pending fixes for the tests :)

2019-05-07 02:19 UTC, talldan commented
Hey @brentswisher, it looks like you might have pushed a branch `masterer` related to this PR:
https://github.com/WordPress/gutenberg/tree/masterer

Not sure how it happened 😄. Is it something that can be deleted?

2019-05-07 14:13 UTC, brentswisher commented
That's weird, I have no idea where that came from or how I managed to get it in the main Gutenberg repo! It's obviously a typo of some kind on my part, but I don't seem to have permission to delete it. If you could remove it and hide my shame from the world @talldan it would be much appreciated!

2019-05-10 08:54 UTC, talldan commented
I deleted it. No-one will ever know 😄

2019-05-10 18:48 UTC, brentswisher commented
@gziolo I've added fixes for the end-to-end tests. All the tests pass now, but I haven't worked with the e2e test suite much before, so a review would be very appreciated to see if there is a better way to do this :)

I contemplated refactoring into a 'clickBlockInserterButton' utility, but most tests use insertBlock anyways so it seemed a little overkill.

The [third commit](https://github.com/WordPress/gutenberg/pull/15382/commits/5fafed98088bc027ddd489b85a133adb65799ec4
) fixes an issue in block-hierarchy-navigation.test.js, but I am not sure if that is related to my changes or not. I was experiencing it intermittently locally on my master branch as well, but it consistently happened in my new branch. 

I watched the test run in non-headless mode to see what was happening and it...passed. I watched again without slowmo enabled and it appeared the space was getting clicked before the block navigation opened. I wasn't sure if I should open another issue or commit it here, but hopefully that gives some background at least.

2019-05-13 09:26 UTC, gziolo commented on packages/e2e-tests/specs/block-hierarchy-navigation.test.js
> +		await page.waitForSelector( '.editor-block-navigation__container' );
I think I have PR where I included the same logic inside `openBlockNavigator`, I can refactor once I work on merging my own PR :)

2019-05-13 09:26 UTC, gziolo approved these changes

2019-05-13 09:27 UTC, gziolo commented
@brentswisher, excellent work refactoring all those existing e2e tests to ensure they still pass with this `aria-label` attribute removed 👍

2019-05-13 09:27 UTC, merged