Removes redundant aria-label from block inserter
WordPress/gutenberg pull request #15461
Opened 2019-05-06 13:51 UTC by getdave

Closes https://github.com/WordPress/gutenberg/issues/15337

Removes the (potentially) redundant aria-label from the block inserter. This needs testing in IE11 and JAWs as it was [originally added](https://github.com/WordPress/gutenberg/pull/5828) to work around an edge cases there.

## Description
Removed `aria-label` attribute.

2019-05-06 14:01 UTC, gziolo commented
This PR duplicates https://github.com/WordPress/gutenberg/pull/15382 and will suffer from the same issues with e2e tests.

2019-05-08 17:49 UTC, afercia commented
Accessibility feedback was given on https://github.com/WordPress/gutenberg/pull/15382#pullrequestreview-233990699 🙂

2019-05-10 08:10 UTC, gziolo commented
I copied this comment from https://github.com/WordPress/gutenberg/pull/15382#pullrequestreview-233862113:

> It looks like a big number of e2e tests depend on the `aria-label` attribute removed in this PR. You can run `npm run test-e2e` to see more details. I think there are a few places where it would have to be updated to make it pass. This label is also present in the `span` so it should be a straightforward change.

At least the following test util needs to be updated to fix failing e2e tests:
https://github.com/WordPress/gutenberg/blob/ae0d1e96616d80a1974f101147c37fcf041a1740/packages/e2e-test-utils/src/insert-block.js#L21

2019-05-10 08:11 UTC, gziolo requested changes
See my previous comment.

2019-05-13 09:32 UTC, gziolo commented
This issue was fixed in https://github.com/WordPress/gutenberg/pull/15382. @getdave, thanks for opening this PR 🙇  I will close it as it is no longer necessary.

2019-05-13 09:32 UTC, closed without merging