Update browserlist supported browsers matrix
WordPress/gutenberg pull request #1572
Opened 2017-06-29 01:02 UTC by ntwb

WordPress supported browsers: https://make.wordpress.org/design/handbook/design-guide/browser-support/

2017-06-29 06:46 UTC, swissspidy requested changes

2017-06-29 06:46 UTC, swissspidy commented on .babelrc
> +					"last 2 Opera versions"
You're missing a comma here

2017-06-29 07:00 UTC, ntwb commented on .babelrc
> +					"last 2 Opera versions"
Hehehe, copy and paste fail 😝

2017-07-03 09:47 UTC, aduth commented
>WordPress supported browsers: https://make.wordpress.org/design/handbook/design-guide/browser-support/

The referenced article doesn't mention any of the browsers added here? Edge makes sense to me, of course. Similarly, Opera (assuming it continues to receive updates) and `1%` seem as "good ideas". Is that the intent of these changes? Should we seek to update the browser support handbook document to reflect Edge and Opera too, then?

2017-07-03 15:49 UTC, ntwb commented
Yes, the handbook should be updated, the specifics of the browsers not mentioned are detailed further in this ticket: [#WP37651](https://core.trac.wordpress.org/ticket/37651)

2017-07-03 15:52 UTC, aduth approved these changes

2017-07-12 03:05 UTC, merged