Insert link accessibility #694
WordPress/gutenberg pull request #1575
Opened 2017-06-29 05:06 UTC by mehigh

2017-06-29 07:49 UTC, swissspidy commented on blocks/editable/format-toolbar.js
> +						<label className="screen-reader-text" htmlFor="editable-format-toolbar__link-input">URL</label>
This should be `{ __( 'URL' ) }` so it's translatable

2017-06-29 07:49 UTC, swissspidy commented on blocks/library/button/index.js
> +						<label className="screen-reader-text" htmlFor="editable-format-toolbar__link-input">URL</label>
This should be `{ __( 'URL' ) }` so it's translatable.

2017-06-29 08:10 UTC, mehigh commented
Thank you @swissspidy. 
I've handled your feedback.

2017-06-29 14:02 UTC, youknowriad commented on blocks/editable/format-toolbar.js
> +							id="editable-format-toolbar__link-input"
Ids should contain a unique uuid. We should consider using the `[withInstanceId](http://gutenberg-devdoc.surge.sh/?selectedKind=Higher%20Order%20Components&selectedStory=withInstanceId&full=0&down=1&left=1&panelRight=1&downPanel=storybooks%2Fstorybook-addon-knobs)` HoC

2017-06-29 14:06 UTC, mehigh commented on blocks/editable/format-toolbar.js
> +							id="editable-format-toolbar__link-input"
Thank you for the linked reference. I'll update the PR to contain it.

2017-07-01 12:48 UTC, mehigh commented on blocks/editable/format-toolbar.js
> +							id="editable-format-toolbar__link-input"
@youknowriad 
I attempted to make use of withinstanceId, but this fails to work.

I imported the component, and loaded it in the render function as a parameter, but I wasn't able to. I'm not sure whether this ID is needed to be passed into the constructor, or somewhere else, but I'm not able to figure out how to do that.

This is where I attempted to do this:
https://github.com/xwp/gutenberg/commit/7aef0027a2361defb8e1011b990b8257956ec9ed

The error I get is:
format-toolbar.js:121 Uncaught TypeError: Cannot read property 'instanceId' of undefined

I also double-checked and the "editable-format-toolbar__link-modal" only shows up once at all time in the DOM. When trying to add a new link the previous link modal is removed from the DOM before adding the new modal, therefore an ID isn't required in this particular case.

I haven't committed the uuid in this PR, so the feature is still fully functional.

2017-07-01 13:12 UTC, swissspidy commented on blocks/editable/format-toolbar.js
> +							id="editable-format-toolbar__link-input"
@mehigh Instead of `export default FormatToolbar;` you'd need to use `export default withInstanceId( FormatToolbar );` in order to make it work.

2017-07-01 13:27 UTC, mehigh commented on blocks/editable/format-toolbar.js
> +							id="editable-format-toolbar__link-input"
Thank you. I'll give that a try.

2017-07-01 20:04 UTC, mehigh commented
@swissspidy 
I was able to get instanceId working. 
I had to look at a few other JS files where this was used to figure out that I need to spread that property into here:
const { formats, focusPosition, enabledControls = DEFAULT_CONTROLS**, instanceId** } = this.props;

Even after adding the export default withInstanceId I couldn't pass **instanceId** as a parameter to the render() function, where I needed to make use of it.

Instance ID appearing (it was 10 in that example):
![Instance ID appearing](http://files.urldocs.com/share/instance-id-working/instance-id-working.png)

Thank you for your reviews.

2017-07-03 13:54 UTC, afercia commented
@mehigh thanks! Looks good to me, I think the only thing left is that also the input field for the button block needs a unique ID. 

<img width="736" alt="screen shot 2017-07-03 at 15 43 28" src="https://user-images.githubusercontent.com/1682452/27795800-c5ad39bc-6007-11e7-915e-f7ace021c0db.png">

2017-07-03 20:35 UTC, mehigh commented
@afercia 
In believe you read the updated PR description, right? :)
> "I wasn't able to figure out where is the "blocks/library/button/index.js" actually used. It has in the edit function a form with a class of editable-format-toolbar__link-modal, just like the one generated with the insert/edit URL."
Thanks for pointing out on where was that URL editing pop-out actually used. 

The button component doesn't have an export statement, so I'm curious on whether the withInstanceId works within it or not. I'll have to test it and see.

2017-07-04 07:11 UTC, afercia commented
@mehigh updating the description doesn't trigger a notification ;)

And yes, because of the way the button block uses the link inline toolbar, I'm not sure there's a way to use `withInstanceId` at the moment. On the other hand, the link inline toolbar should probably be a reusable component. Right now, there are two link toolbar that just "look" the same, but they're two different implementations. This is a bit out of the scope of this issue and should probably be addressed in a separate issue. I'd also like to ping @aduth @youknowriad to ask if there are plans to rework the link inline toolbar as a component.

2017-07-04 08:18 UTC, mehigh commented
I was curios that your comment was spot on to the addition I made to the description. Wanted  to check whether that triggered your response :).

I'll await for input from aduth / youknowriad and see whether this can be brought home and merged in.

2017-07-12 18:20 UTC, mehigh commented
@aduth / @youknowriad 
Since the 2nd usage of the URL entry doesn't support withInstanceId, I suggest we leave the current implementation as it's accessible and maybe revise in a different ticket if it's decided to merge the two together.
Hope to move this forward.

2017-07-13 19:45 UTC, aduth commented
A block's `edit` property is a component, meaning that it can be wrapped with `withInstanceId` to inject an `instanceId` prop.

```diff
diff --git a/blocks/library/button/index.js b/blocks/library/button/index.js
index d49c0344..0d4f9b0e 100644
--- a/blocks/library/button/index.js
+++ b/blocks/library/button/index.js
@@ -2,7 +2,7 @@
  * WordPress dependencies
  */
 import { __ } from 'i18n';
-import { IconButton } from 'components';
+import { IconButton, withInstanceId } from 'components';
 
 /**
  * Internal dependencies
@@ -36,9 +36,10 @@ registerBlockType( 'core/button', {
 		}
 	},
 
-	edit( { attributes, setAttributes, focus, setFocus, className } ) {
+	edit: withInstanceId( ( { attributes, setAttributes, focus, setFocus, className, instanceId } ) => {
 		const { text, url, title, align } = attributes;
 		const updateAlignment = ( nextAlign ) => setAttributes( { align: nextAlign } );
+		const inputId = `editable-format-toolbar__link-input-${ instanceId }`;
 
 		return [
 			focus && (
@@ -61,10 +62,15 @@ registerBlockType( 'core/button', {
 					<form
 						className="editable-format-toolbar__link-modal"
 						onSubmit={ ( event ) => event.preventDefault() }>
-						<label className="screen-reader-text" htmlFor="editable-format-toolbar__link-input">{ __( 'URL' ) }</label>
+						<label
+							className="screen-reader-text"
+							htmlFor={ inputId }
+						>
+							{ __( 'URL' ) }
+						</label>
 						<input
 							className="editable-format-toolbar__link-input"
-							id="editable-format-toolbar__link-input"
+							id={ inputId }
 							type="url"
 							required
 							value={ url }
@@ -76,7 +82,7 @@ registerBlockType( 'core/button', {
 				}
 			</span>,
 		];
-	},
+	} ),
 
 	save( { attributes } ) {
 		const { url, text, title, align = 'none' } = attributes;
```

Alternatively, we can split this out into a separate component. Like @afercia mentions, we should probably create a common component for applying links to avoid managing separate implementations between the formatting toolbar and button link.

I think the patch above is a reasonable interim solution for now.

2017-07-13 19:45 UTC, aduth requested changes
https://github.com/WordPress/gutenberg/pull/1575#issuecomment-315182274

2017-07-13 20:49 UTC, mehigh commented
Thank you, @aduth for the review and for pointing it out how the ID property can be passed through the edit component. I'll amend the PR tomorrow or on Monday.

2017-07-17 06:48 UTC, mehigh commented
@aduth changes have been applied, while adjusting the ID to "editable-format-toolbar__button-link-input-XX" from "editable-format-toolbar__link-input-" in order to avoid a potential clash with the toolbar link form input, as they share different set of IDs. 
Thank you for your thorough explanation.

2017-07-18 08:38 UTC, closed without merging

2017-07-18 08:41 UTC, mehigh commented
I tried to rebase this to squash all of the merge master commits, but it yielded too many conflicts. 
@aduth everything is available here:
https://github.com/WordPress/gutenberg/pull/1933