Fix missing closing tag for RegistryConsumer example
WordPress/gutenberg pull request #16153
Opened 2019-06-13 10:26 UTC by ocean90

The code block for https://github.com/WordPress/gutenberg/tree/b354644/packages/data#RegistryConsumer is missing the closing backticks.

2019-06-13 13:45 UTC, youknowriad approved these changes
Thanks

2019-06-13 13:46 UTC, youknowriad requested changes
Actually, it seems that this documentation is generated and should be instead fixed in the source (JSDoc of the function itself)

2019-06-25 17:09 UTC, aduth commented
> Actually, it seems that this documentation is generated and should be instead fixed in the source (JSDoc of the function itself)

Specifically, here:

https://github.com/WordPress/gutenberg/blob/56de120cf56836c227710baf335323c21efc9ac5/packages/data/src/components/registry-provider/context.js#L23-L43

Changing the file and running `npm run docs:build` should have the intended effect.

2019-06-25 18:40 UTC, youknowriad approved these changes

2019-06-25 18:41 UTC, youknowriad commented
I actually just tried running `npm run docs:build` locally, and it seems that change is reverted. I wonder if there's an error in the docs tool.

2019-06-25 18:42 UTC, youknowriad commented
Nevermind, I had an outdated branch.

2019-06-25 18:42 UTC, merged