Change wording, add a second block to the template and mention block.…
WordPress/gutenberg pull request #16237
Opened 2019-06-20 15:12 UTC by retrorism

…json as a resource for attributes
https://github.com/WordPress/gutenberg/issues/6190

## Description

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

2019-08-05 10:45 UTC, draganescu requested changes

2019-08-05 10:45 UTC, draganescu commented on docs/designers-developers/developers/block-api/block-templates.md
> +The following example in JavaScript creates a new custom block using [InnerBlocks](/packages/block-editor/src/components/inner-blocks/README.md) and templates. When this block is inserted, this block
`When this block is inserted, it creates a set of blocks based off the template.`

2019-08-05 10:45 UTC, draganescu commented on docs/designers-developers/developers/block-api/block-templates.md
> +Templates are especially useful in combination with blocks that store custom post_meta to a post type. See the [Meta Block Tutorial](/docs/designers-developers/developers/tutorials/metabox/meta-block
The 1st sentence is a bit unclear.

2020-11-14 16:51 UTC, gziolo commented
It looks like this PR was abandoned. I’m closing it for now. It can be reopened at any time with the refreshed code according to the feedback shared. Thank you for contribution.

2020-11-14 16:51 UTC, closed without merging