Block Editor: Reimplement BlockEditorProvider using hooks
WordPress/gutenberg pull request #16357
Opened 2019-06-28 21:00 UTC by aduth

This pull request seeks to refactor the `BlockEditorProvider` component to use React hooks in order to sync blocks value as effects leveraging existing data hooks for value subscriptions.

The hope with this change was to simplify the logic flow, but I'd also hoped for some performance optimization to come from this simplification. However, it doesn't appear to have any benefit and in-fact has a minor negative impact (~106ms to 109ms average time to type via `npm run test-performance`). It's unclear to me why this would be the case. While I've not dug into it, I'm curious if `useSelect` is as performance-optimized as it can be in cases where a component renders for reasons other than state changes (i.e. does it call the mapping selector even though state hasn't changed?).

If the performance degradation cannot be resolved, I'm not sure whether it's worth moving forward with these changes.

If we do move forward with these changes, I think we could explore further flattening to reimplement the internal `withRegistryProvider` higher-order component as a hook.

**Testing Instructions:**

Verify there are no regressions in standard usage (particularly via blocks updates, reusable blocks, etc).

2020-04-18 23:31 UTC, ZebulanStanphill requested changes

2020-04-18 23:31 UTC, ZebulanStanphill commented on packages/block-editor/src/components/provider/index.js
> +	onInput = () => {},
Microoptimization: Instead of creating 2 separate functions these could both reference a dummy empty function.

2020-04-18 23:31 UTC, ZebulanStanphill commented on packages/block-editor/src/components/provider/index.js
> +	} );
A big optimization that could be made here is adding an empty dependency array to this `useSelect`.

2020-04-18 23:31 UTC, ZebulanStanphill commented on packages/block-editor/src/components/provider/index.js
> +	const previousBlocks = useRef( blocks );
This looks like a use-case for a [`usePrevious`](https://usehooks.com/usePrevious/) hook. I'm actually using one already in #21181, and I wonder if we should add it to `@wordpress/compose`.

2020-04-18 23:31 UTC, ZebulanStanphill commented on packages/block-editor/src/components/provider/index.js
> +import { useSelect, useDispatch } from '@wordpress/data';
Nitpick: I think imports should be in alphabetical order.

```suggestion
import { useDispatch, useSelect } from '@wordpress/data';
import { useEffect, useRef } from '@wordpress/element';
```

2020-06-16 16:35 UTC, ZebulanStanphill commented on packages/block-editor/src/components/provider/index.js
> +	onInput = () => {},
Specifically, the `noop` function provided by Lodash could be used here.

2020-06-16 16:36 UTC, ZebulanStanphill commented on packages/block-editor/src/components/provider/index.js
> +	const previousBlocks = useRef( blocks );
`usePrevious` has now been added to the `@wordpress/compose` package, so it could definitely be used here.

2020-06-16 16:43 UTC, noahtallen commented
I converted the block editor provider to use hooks in #21368. This PR could probably be changed to introduce any performance optimizations suggested?

2020-06-17 21:40 UTC, ZebulanStanphill commented
Thanks for pointing that out, @noahtallen. I've opened #23255 to add missing dependency arrays to `useSelect` calls throughout the codebase.

Seeing as that the original purpose of this PR has already been fulfilled by another PR, I'm closing this one. Thanks for making this PR, @aduth, even if it didn't end up being used in the end. :heart:

2020-06-17 21:40 UTC, closed without merging