New ISSUE_TEMPLATE.md file #1637
WordPress/gutenberg pull request #1638
Opened 2017-07-01 23:09 UTC by DevinWalker

## PR Overview

Added an `ISSUE_TEMPLATE.md` file as a baseline. This is the one we use in our projects and it has been working pretty nicely for us. 

If you have any suggested edits, just let me know! 

Ref: #1637

2017-07-02 03:33 UTC, ntwb requested changes
Also see #1637

2017-07-02 03:33 UTC, ntwb commented on .github/ISSUE_TEMPLATE.md
> +## Issue Overview
Probably above this should be a link [CONTRIBUTING.md](https://github.com/WordPress/gutenberg/blob/master/CONTRIBUTING.md)

2017-07-02 03:33 UTC, ntwb commented on .github/ISSUE_TEMPLATE.md
> +## Steps to Reproduce (for bugs)
I'd reorder this, the sections should be in the order of:

`## Steps to Reproduce (for bugs)`
`## Expected Behavior`
`## Current Behavior`

It allows the issue reader to gain an overview of the events that led up to the "current behaviour" they see

2017-07-02 18:19 UTC, DevinWalker commented on .github/ISSUE_TEMPLATE.md
> +## Steps to Reproduce (for bugs)
That makes sense to me!

2017-07-03 08:53 UTC, youknowriad commented
Should we add a comment asking to look for duplicates before opening an issue?

2017-07-03 18:10 UTC, DevinWalker commented
@youknowriad yes, that's definitely a good idea. I'll add that text.

2017-07-04 14:08 UTC, swissspidy commented on .github/ISSUE_TEMPLATE.md
> +- Disabled all plugins to ensure it's not a plugin conflict issue.
s/Disabled/Disable

2017-07-04 14:24 UTC, merged