Slimmer top/bottom spacing inside notices
WordPress/gutenberg pull request #16589
Opened 2019-07-15 12:19 UTC by kjellr

Currently, our Notice component ships with `1em` of padding on the top and bottom of the content area: 

<img width="269" alt="Screen Shot 2019-07-15 at 8 16 25 AM" src="https://user-images.githubusercontent.com/1202812/61215427-dba9dd00-a6d8-11e9-82a0-d0d115794f3b.png">

This results in a lot of extra room on the top and bottom of the text: 

<img width="277" alt="Screen Shot 2019-07-15 at 8 11 25 AM" src="https://user-images.githubusercontent.com/1202812/61215450-f0867080-a6d8-11e9-8a1b-21d6c3c68fad.png">

This PR changes that spacing to `$grid-size-small`, to balance it out with the spacing on the sides, and to align to our standard spacing increments, instead of `1em`: 

<img width="276" alt="Screen Shot 2019-07-15 at 8 12 57 AM" src="https://user-images.githubusercontent.com/1202812/61215502-157ae380-a6d9-11e9-8d43-ddae83764b87.png">

2019-07-15 13:58 UTC, aduth approved these changes
Code-wise this looks good, and I agree the padding is both too much and inconsistent with the rest of the admin.

I was curious where the original values might have come from, and I note that the rest of the admin uses a _total_ of 1em margin for paragraphs in a notice:

https://github.com/WordPress/wordpress-develop/blob/master/src/wp-admin/css/common.css#L1388

I don't know if we care to mimic this, or if it's necessary to adjust other style values here (there's default padding on the notice itself, in addition to the margin of the content).)

2019-07-15 14:37 UTC, chrisvanpatten commented
This has been bugging me for a while but I've been too busy to fix it, so I'm very happy to see this PR! Thanks @kjellr!

2019-07-15 15:07 UTC, youknowriad requested changes
<img width="102" alt="Capture d’écran 2019-07-15 à 4 07 22 PM" src="https://user-images.githubusercontent.com/272444/61226663-be95fe00-a71a-11e9-8f92-b706ba5603fa.png">

I knew there was some back and forth here. It looks like this breaks the alignment of the "close" button in the regular notices of the editor.

Try 

```
wp.data.dispatch('core/notices').createNotice(
		'info',
		'Post published.', // Text string to display.
		{
			isDismissible: true, // Whether the user can dismiss the notice.
			// Any actions the user can perform.
            actions: [
				{
					onClick: () => console.log( 'test' ),
					label: 'View post'
				}
			]
		}
	);
```

2019-07-16 12:40 UTC, kjellr commented
@youknowriad good catch. I pushed a new change that sets the top/bottom margins to `$grid-size` when they're inside of the `components-notice-list`. This keeps that close button in the right space, and also ensures that notices up there are a bit taller than the Sidebar's tabbed nav area (I remember this being a concern before, since we don't want the notices to be interpreted as an extension of that bar): 

<img width="960" alt="Screen Shot 2019-07-16 at 8 33 55 AM" src="https://user-images.githubusercontent.com/1202812/61295126-59d3b580-a7a5-11e9-8cd9-09f9a4c0ddd7.png">

<img width="278" alt="Screen Shot 2019-07-16 at 8 34 10 AM" src="https://user-images.githubusercontent.com/1202812/61295131-5b9d7900-a7a5-11e9-802f-215fe08de526.png">

2019-07-16 12:47 UTC, youknowriad approved these changes
Thanks for the fix

2019-07-16 13:22 UTC, chrisvanpatten approved these changes
Looks great! 🚢

2019-07-16 13:33 UTC, merged

2019-07-16 13:33 UTC, kjellr commented
Thanks everyone!