Docs: Add section about adding new dependencies to WordPress packages
WordPress/gutenberg pull request #16876
Opened 2019-08-02 09:37 UTC by gziolo

## Description
This PR adds a section about adding new dependencies to WordPress packages. See new section's preview:
https://github.com/WordPress/gutenberg/blob/a300ed9530b7b4746924194b75117678e3592cc7/packages/README.md#adding-new-dependencies

I came up to the conclusion that this needs to be explained explicitly after talking to @dsifford. He had some issues when he wanted to add a new dependency to one of the packages. I hope all the proposed changes will make it easier for future contributors.

2019-08-02 18:08 UTC, dsifford approved these changes
LGTM :+1:

2019-08-03 15:34 UTC, chrisvanpatten requested changes
A few grammar nits, but this is great and super helpful!

2019-08-03 15:34 UTC, chrisvanpatten commented on packages/README.md
> +There are two types of dependencies that you might want to add to one of the existing WordPress package.
```suggestion
There are two types of dependencies that you might want to add to one of the existing WordPress packages.
```

2019-08-03 15:34 UTC, chrisvanpatten commented on packages/README.md
> +Production dependencies are stored in the `dependencies` section of `package.json` file of the package's folder. The simplest way to add such dependency to one of the packages is to run a very conven
```suggestion
Production dependencies are stored in the `dependencies` section of the package’s `package.json` file. The simplest way to add such a dependency to one of the packages is to run a very convenient [lerna add](https://github.com/lerna/lerna/tree/master/commands/add#readme) command from the root of the project.
```

2019-08-03 15:34 UTC, chrisvanpatten commented on packages/README.md
> +This command adds the latest version of `lodash` as a dependency to the `@wordpress/a11y` package which is located in `packages/a11y` folder.
```suggestion
This command adds the latest version of `lodash` as a dependency to the `@wordpress/a11y` package, which is located in `packages/a11y` folder.
```

2019-08-03 19:57 UTC, gziolo commented
> A few grammar nits, but this is great and super helpful!

They should hire you at Grammarly to improve their system which catches grammar issues, thanks for all corrections. 😄

2019-08-03 21:24 UTC, chrisvanpatten approved these changes
🚢!

2019-08-05 02:35 UTC, merged