Fix/17203 notices type docs
WordPress/gutenberg pull request #17206
Opened 2019-08-26 21:20 UTC by simono

## Description
Fix documentation errors as explained in #17203.

## Types of changes
- fixes docs

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

2019-08-27 07:13 UTC, ocean90 requested changes

2019-08-27 07:13 UTC, ocean90 commented on packages/notices/src/store/selectors.js
>   * @property {WPNoticeAction[]} actions User actions to present with notice.
Just noticed that `speak` is missing as well. Can you please add as part of this PR?

2019-08-27 09:25 UTC, ocean90 approved these changes

2019-08-27 13:12 UTC, dsifford approved these changes
See comments.

2019-08-27 13:24 UTC, simono commented on packages/notices/src/store/actions.js
> + * @param {?string}                options.type          Type of notice, one of
From what I understand it's nullable and gets a default value if it's null, see https://github.com/WordPress/gutenberg/blob/132d2d4cf1b24511d821e6e1fe2203fb4c18d201/packages/notices/src/store/actions.js#L38

Or did I miss something?

2019-08-29 09:18 UTC, simono commented on packages/notices/src/store/actions.js
> + * @param {?string}                options.type          Type of notice, one of
Ok, thanks for the clarification :)

I can update this PR and change the params from nullable to optional with default. Would that be helpful @dsifford?

2019-08-29 20:24 UTC, simono commented on packages/notices/src/store/actions.js
> + * @param {?string}                options.type          Type of notice, one of
I've updated the PR and fixed the params in `notices/src/store/actions.js`.

2019-08-30 04:52 UTC, gziolo commented
Travis job fails. It looks like you need to run “npm run docs:build” to refresh docs.

2019-08-30 07:55 UTC, simono commented
Thanks for the heads-up @gziolo 
The build passed now.

Just out of curiosity: Why are those generated docs in version control?

2019-08-30 08:48 UTC, gziolo commented
> Just out of curiosity: Why are those generated docs in version control?

We use GitHub source to power developer docs: https://developer.wordpress.org/block-editor/data/data-core-notices/ but at the same time, you can browse them on GitHub. Ideally, bot should run `npm run docs:build` and add a commit to your PR when necessary. I hope we will get there one day :)

2019-08-30 08:48 UTC, merged

2019-08-30 08:49 UTC, gziolo commented
Congrats on your first code contribution to Gutenberg 🎉

2019-08-30 09:07 UTC, simono commented
Thanks for the merge and all the help @gziolo