Tests: Refactor tests to use only Jest API
WordPress/gutenberg pull request #1788
Opened 2017-07-07 16:34 UTC by gziolo

This is a follow up for #1382. This PR performs all remaining refactorings to get rid of Mocha specific code:
- Sinon test doubles
- Sinon fake timers
- Chai assertions
- Chai lifecycle methods

This change makes test execution a bit faster:

> real    **0m4.529s**
> user    0m22.167s
> sys     0m1.724s

### Testing
Make sure `npm test` passes.

2017-07-07 16:41 UTC, gziolo commented
@nb This concludes Mocha to Jest migration for Gutenberg! This PR gives an overview how much code would be updated in the context of Automattic/wp-calypso. Unforntunately sinon changes aren't covered with `jest-codemods`. Maybe there are other codemods, because it was quite easy to change manually. Most of the changes were applied with the combination:
```bash
# jest-codemods <file-path>
# npm run lint -- --fix space-in-parens

2017-07-07 22:36 UTC, nylen requested changes
Some minor revisions needed but overall I'm a fan.  Can we now also remove `mocha: true` from the eslint config?

2017-07-07 22:36 UTC, nylen commented on blocks/api/test/serializer.js
>  import { createElement, Component } from 'element';
This section should now be titled `WordPress dependencies`, not `External dependencies`.

2017-07-07 22:36 UTC, nylen commented on blocks/library/freeform/test/naiveCss2Jsx.js
>  import { naiveCss2Jsx } from '../format-list';
This section should now be titled `Internal dependencies`, not `External dependencies`.

2017-07-07 22:36 UTC, nylen commented on editor/block-mover/test/mover-label.js
>  import { getBlockMoverLabel, getMultiBlockMoverLabel } from '../mover-label';
This section should now be titled `Internal dependencies`, not `External dependencies`.

2017-07-07 22:36 UTC, nylen commented on editor/test/actions.js
> - */
This section should now be titled `Internal dependencies`, not `External dependencies`.

2017-07-07 22:36 UTC, nylen commented on editor/utils/test/dom.js
>  import { isEditableElement } from '../dom';
This section should now be titled `Internal dependencies`, not `External dependencies`.

2017-07-07 22:36 UTC, nylen commented on editor/utils/test/undoable-reducer.js
>  import { undoable, combineUndoableReducers } from '../undoable-reducer';
This section should now be titled `Internal dependencies`, not `External dependencies`.

2017-07-07 22:36 UTC, nylen commented on editor/utils/test/url.js
>  import { addQueryArgs } from '../url';
This section should now be titled `Internal dependencies`, not `External dependencies`.

2017-07-07 22:36 UTC, nylen commented on element/test/index.js
>  import { createElement, renderToString, concatChildren, switchChildrenNodeName } from '../';
This section should now be titled `Internal dependencies`, not `External dependencies`.

2017-07-07 22:36 UTC, nylen commented on CONTRIBUTING.md
> +Tests for JavaScript use [Jest](http://facebook.github.io/jest//) as the test runner. If needed, you can also use [Enzyme](https://github.com/airbnb/enzyme) for React component testing.
Super minor: Double slash in this URL.

2017-07-07 22:36 UTC, nylen commented on blocks/test/full-content.js
> +			).toEqual( parserOutputExpected );
When these tests fail, debugging them is pretty tricky without these messages in place.  Let's preserve them (this one and the 2 below it), even if we have to do it via a `try / catch` or some other non-pretty mechanism.

Context: https://github.com/facebook/jest/issues/1965

2017-07-07 22:36 UTC, nylen commented on components/form-token-field/test/index.js
> -		it( 'should manage the selected suggestion based on both keyboard and mouse events', test( function() {
What was this `test()` wrapper?

2017-07-07 22:36 UTC, nylen commented on editor/block-mover/test/mover-label.js
> +            );
The new indentation here looks wrong.  In fact, I would expect this to cause a lint error and we should investigate why it isn't.

2017-07-07 22:36 UTC, nylen commented on editor/test/state.js
> +			expect( Object.keys( state ) ).toEqual( expect.arrayContaining( [
Not a critique for this PR, but I'm not a huge fan of this syntax.

2017-07-07 22:36 UTC, nylen commented on package.json
> -    "sinon-test": "^1.0.2",
:tada: :tada: :tada:

2017-07-07 22:36 UTC, nylen commented on package.json
> -    "chai": "^3.5.0",
:tada:

2017-07-07 22:36 UTC, nylen commented on package.json
> -    "dirty-chai": "^1.2.2",
:tada:

2017-07-08 00:43 UTC, nb commented
Great work, @gziolo. The `sinon` changes don't worry me much.

I have a feeling we will get the most benefits from `jest` if we start using snapshots for component/integration tests, any chance we can try this in Gutenberg? Maintaining all of those fixtures… 💣

2017-07-08 04:28 UTC, ntwb commented on editor/block-mover/test/mover-label.js
> +            );
Both lines 22 & 23 here are indented with spaces and not tabs

As to why ESLint is missing that I've no idea /shrug

2017-07-08 09:52 UTC, nb approved these changes

2017-07-08 11:08 UTC, gziolo commented on editor/test/state.js
> +			expect( Object.keys( state ) ).toEqual( expect.arrayContaining( [
I would blame `jest-codemod` here. I'm sure we can refactor later using [expect.objectContaining ]https://facebook.github.io/jest/docs/en/expect.html#expectobjectcontainingobject).

2017-07-08 11:09 UTC, gziolo commented on components/form-token-field/test/index.js
> -		it( 'should manage the selected suggestion based on both keyboard and mouse events', test( function() {
Sinon exposes `test` method to enable fake timers. We have fake timers enabled by default in the current Jest configuration.

2017-07-08 11:12 UTC, gziolo commented on blocks/api/test/serializer.js
>  import { createElement, Component } from 'element';
I see. `jest-codemods` wasn't smart enough to use those conventions :)

2017-07-08 15:16 UTC, gziolo commented on blocks/test/full-content.js
> +			).toEqual( parserOutputExpected );
This is what I see when I make JSON.parse throw an error:

> ● full post content fixture › core__html
> 
>     SyntaxError: Unexpected token x in JSON at position 0
>         at Object.parse (native)
>       
>       at Object.<anonymous> (blocks/test/full-content.js:123:36)
>       at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
>       at process._tickCallback (internal/process/next_tick.js:109:7)

It seems okey from my perspective. We can also code our own matcher which would print error using [expect.extend](https://facebook.github.io/jest/docs/en/expect.html#expectextendmatchers).

2017-07-08 15:27 UTC, gziolo commented on element/test/index.js
>  import { createElement, renderToString, concatChildren, switchChildrenNodeName } from '../';
I'm wondering if it would be possible to add Eslint rule that would verify such use case.

2017-07-08 15:53 UTC, gziolo commented
@nylen Thanks for catching all issues introduced with `jest-codemods` run. I fixed all of them. I also added `try` / `catch` clause to make sure we display more user friendly message with removed debug like:
> format( 'File \'%s.parsed.json\' does not match expected value', f )

Let me know if that works for you until Jest adds a better way to do it.

2017-07-09 08:53 UTC, nb commented
> > I guess the best way would be to refactor this code to use snapshots instead. We can do it in the follow up PR.

What’s your thinking about what tests should use snapshots? A lot of the tests touched in this PR should better stay the way they are. Converting component and fixture tests to snapshots would be awesome, though. Agreed that a separate PR is better.

2017-07-09 16:07 UTC, nylen commented on editor/test/state.js
> +			expect( Object.keys( state ) ).toEqual( expect.arrayContaining( [
The `toEqual( expect.someWeirdObject` syntax in general is strange.  Again not something we can really change here.

2017-07-09 16:08 UTC, nylen commented on blocks/test/full-content.js
> +			).toEqual( parserOutputExpected );
A JSON parse error is not a realistic failure mode here.  When these tests fail, we have a valid JSON object but a mismatch in its content.  Or a mismatch in the serialized string content.  It's difficult to tell the difference between these two, so we need to keep some code that prints the filename.

I see that this is done in the latest version of the PR. :+1:

2017-07-09 16:31 UTC, nylen commented
> Let me know if that works for you until Jest adds a better way to do it.

In 4e481fe I've also preserved the original error message which contains the actual+expected values and the differences between them.

Thanks for working on this; it's looking good to me.

2017-07-09 16:31 UTC, nylen approved these changes

2017-07-10 06:46 UTC, gziolo commented
> In 4e481fe I've also preserved the original error message which contains the actual+expected values and the differences between them.

Yes, it makes perfect sense. 👍 

> What’s your thinking about what tests should use snapshots? A lot of the tests touched in this PR should better stay the way they are. Converting component and fixture tests to snapshots would be awesome, though. Agreed that a separate PR is better.

@nb I rather consider snapshot testing as complementary. When you develop component, you should also use TDD techniques and introduce snapshot based tests once you have something working to make sure it doesn't change later. Definitely tests where you create tons of fixtures are perfect match to use snapshots, too.

2017-07-10 06:47 UTC, merged

2017-07-10 10:03 UTC, nb commented
> I rather consider snapshot testing as complementary. 

This sounds like too many tests  – why can't we use snapshots to TDD components? We should start with some small output and then build up.

2017-07-10 17:00 UTC, gziolo commented
> This sounds like too many tests – why can't we use snapshots to TDD components? We should start with some small output and then build up.

Let's see how it goes. I don't have any experience with snapshots so I'm only blindly predicting :D
I opened #1841 which is a perfect use case for snapshots!