Fix issue-7378 - change name of accumulated variables when using redu…
WordPress/gutenberg pull request #17893
Opened 2019-10-11 04:59 UTC by lozinska

…ce function

## Description

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

2019-10-11 06:35 UTC, gziolo requested changes
Thank you for working on this nice code style improvements. It's going in the right direction.

There are some issues that need to be resolved. You can see them on – our Continues Integration:
- https://travis-ci.com/WordPress/gutenberg/jobs/244576166 - there are some linting issues discovered, you can see them locally with `npm run lint-js`
- https://travis-ci.com/WordPress/gutenberg/jobs/244576169 - there are some failing unit tests, you can run them locally with `npm run test-unit`

It looks like the only place where the name of the variable should be updated is inside the callback which is passed as param to the `reduce` function. It might be a bit confusing as we are using `reduce` function from `lodash` library or `reduce` from `Array` object which works a bit differently.

```js
// array.reduce(callback(accumulator, currentValue[, index[, array]])[, initialValue]);
[ 1, 2 ].reduce( function( accumulator, n ) {
  return accumulator + n;
}, 0 );

// lodash.reduce(collection, [iteratee=_.identity], [accumulator]);
lodash.reduce( [ 1, 2 ], function( accumulator, n ) {
  return accumulator + n;
}, 0 );
```

2019-10-11 14:39 UTC, lozinska commented
@gziolo Thank you for your reply. I definitely will correct it and send a pull request, later today. Thank you

2019-10-14 07:50 UTC, gziolo commented on packages/block-library/src/columns/deprecated.js
> +			const columns = innerBlocks.reduce( ( resultAccumulator, innerBlock ) => {
It seems like `resultAccumulator` could be simplified to just `accumulator`. They `result` prefix doesn't sound like it brings additional context here.

2019-10-14 07:50 UTC, gziolo commented on packages/block-library/src/index.native.js
> +].reduce( ( memoAccumulator, block ) => {
A similar note here. It feels like `memoAccumulator` could be shortened to `accumulator` and it will read well enough.

2019-10-14 07:52 UTC, gziolo reviewed
Nice improvements. Can we address two more comments where I suggest we remove redundant prefixes `result` and `memo` from the variable names?

Otherewise, it looks great. Many thanks for cleaning up the code.

2019-10-15 02:34 UTC, lozinska commented
Thank you for your reply and suggestions, definitely I will fix that

2019-10-15 06:30 UTC, gziolo approved these changes
Nice one. Thank you for working on it 💯

2019-10-15 06:30 UTC, merged