Change BaseControl sibling selector to use margin-top
WordPress/gutenberg pull request #17985
Opened 2019-10-17 01:54 UTC by chrisvanpatten

## Description
Changes the BaseControl sibling selector to use margin-top instead of margin-bottom for consistent spacing. Fixes #17984.

## How has this been tested?
Confirmed in CSS via web inspector and in local development environment.

## Screenshots

**Before:**

**<img width="285" alt="Screen Shot 2019-10-16 at 9 30 05 PM" src="https://user-images.githubusercontent.com/1231306/66970644-2fbbb900-f05c-11e9-920c-285accb2d90f.png">**|**<img width="285" alt="Screen Shot 2019-10-16 at 9 30 56 PM" src="https://user-images.githubusercontent.com/1231306/66970691-537eff00-f05c-11e9-9734-050bba9b201f.png">**
:-----:|:-----:

**After:**

**<img width="287" alt="Screen Shot 2019-10-16 at 9 32 33 PM" src="https://user-images.githubusercontent.com/1231306/66970757-89bc7e80-f05c-11e9-9e86-f9fdafece1b4.png">**|**<img width="286" alt="Screen Shot 2019-10-16 at 9 32 39 PM" src="https://user-images.githubusercontent.com/1231306/66970767-8fb25f80-f05c-11e9-8749-c69d78da4eb2.png">**
:-----:|:-----:

## Types of changes
Small CSS bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

2019-10-17 07:44 UTC, youknowriad reviewed
I haven't tested but this makes sense.

2019-10-17 08:38 UTC, jasmussen requested changes
In principle, this seems fine. 

However the sad thing with all small changes is, they're never small. This happens:

<img width="313" alt="Screenshot 2019-10-17 at 10 34 36" src="https://user-images.githubusercontent.com/1204802/66992398-0df91b00-f0ca-11e9-8d50-1debf437ef63.png">

<img width="929" alt="Screenshot 2019-10-17 at 10 34 56" src="https://user-images.githubusercontent.com/1204802/66992404-0f2a4800-f0ca-11e9-8839-62aa747b2770.png">

I imagine that some plugins rely on the current configuration as well, so this will probably need a dev note too.

Thank you for the PR! 🤟

2020-01-21 19:27 UTC, ItsJonQ commented
👋 Hallooo!! Just checked out this PR.

> In principle, this seems fine... However the sad thing with all small changes is, they're never small.

@jasmussen That's been my experience as well.

Assumed margin (top or bottom) via DOM order is normally okay for simpler use-cases. By simpler use cases, I mean when most sibling DOM element rendering is consistent or has only a handful of variation. For example, items that appear within a blog post.

However, for more app-like UI, it's very difficult to predict how/when elements may need to render above, below, or next to each other, with layout rules defined by `display: flex`, `float`, `position`, or anything in between.


@chrisvanpatten I really appreciate your intention + initiative here.

> Changes the BaseControl sibling selector to use margin-top instead of margin-bottom for **consistent spacing**.

If I may, by "consistent spacing", I feel like you don't necessarily mean specific `px` values, but rather... the darn thing should look/work the same. Every time. So we never have to think about it again 😂 

This is a long shot, but I think a good solution would be for margins to be defined explicitly - either by using a layout-based Component or ad-hoc - both using a predefined set of layout/spacing values (e.g. 4px, 8px, etc...). Of course, this would involve removing the margins for `BaseControl`, which will most likely also break a bunch of things 😛 .

---

As for this PR, I'm not sure how to proceed, as changing the margin from bottom to top solves some use cases, but has unintended side effects for others.

2020-01-22 02:50 UTC, chrisvanpatten commented
@ItsJonQ Thanks for taking a look!

> If I may, by "consistent spacing", I feel like you don't necessarily mean specific px values, but rather... the darn thing should look/work the same.

Yes exactly. I’m less concerned with either actual size/value, and more concerned that spacing is treated consistently.

That said, I’ve obviously let this grow stale because I haven’t been totally confident in my solution for all the reasons you hit upon. It solves some cases but risks introducing other regressions. I also agree with what you hinted at — this is probably best addressed in a more holistic way, ideally at the component level.

So with that in mind I think I’ll close this PR, although I’m happy to also open an issue for discussion of this problem at a higher level. And if this solution seems like a viable path at a later point, we can always reopen or revisit.

2020-01-22 02:50 UTC, closed without merging

2020-01-22 02:56 UTC, chrisvanpatten commented
I will also say, for posterity, that I believe the current behaviour is a mistake. Not a mistake of the “I disagree with this” variety, but I actually think it’s a genuine bug — but unfortunately, it’s a bug that we’ve come to depend on in certain circumstances. As a result, it’s tricky to fix, because the solution inevitably breaks the things which assumed the bug was intended behaviour 😅