Fix handling of pasted images and prevent thumbnail uploads
WordPress/gutenberg pull request #18215
Opened 2019-10-31 14:58 UTC by koke

## Description

Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/1510

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

2019-10-31 16:17 UTC, SergioEstevao approved these changes
Testing this is in the WP-iOS and it's looking good.

2019-10-31 17:07 UTC, etoledom reviewed
Testing this PR, the low-res image is not uploaded anymore, but there's still an issue where the image URL stays as the local `file://` url.

This can be reproduced by publishing/saving as draft while the upload is in progress, and opening the editor again before the upload finishes, and also by switching to HTML mode, waiting until the upload finishes, and going back to the visual mode.

![file_url](https://user-images.githubusercontent.com/9772967/67969246-33793f00-fc09-11e9-8453-f39c1131fc43.gif)

2019-10-31 17:16 UTC, SergioEstevao commented
Humm when switching to HTML mode I think we are missing a hook to update post content inside GB HTML editor when an upload finishes. I do believe this was an existing bug on previous releases no?

2019-10-31 17:23 UTC, etoledom commented
> Humm when switching to HTML mode I think we are missing a hook to update post content inside GB HTML editor when an upload finishes. I do believe this was an existing bug on previous releases no?

I think so. Probably these two scenarios will need different solutions.

Btw, the gif shows the Image block, but with the Media&Text blog, the image that stays is the low-res one. Is not uploaded anymore but the uploaded image is not reflected on the final HTML.

For the dismiss scenario, I was thinking about keeping the instance of gutenberg alive, until the post is published/saved. This would save us from the re-opening problem, and it would also help us updating the final HTML after the upload finishes (without reopening the editor).

Not sure how crazy is that idea 😱

For the HTML mode, I think that having the upload listener somewhere in the root (not inside a block) would help.

2019-10-31 17:30 UTC, SergioEstevao commented
> For the HTML mode, I think that having the upload listener somewhere in the root (not inside a block) would help.

I think it will be easier to have an listener on the HTML component and do a search replace for the image. It's what we do in the main app for Aztec and background upload.

2019-10-31 17:31 UTC, SergioEstevao commented
> For the dismiss scenario, I was thinking about keeping the instance of gutenberg alive, until the post is published/saved. This would save us from the re-opening problem, and it would also help us updating the final HTML after the upload finishes (without reopening the editor).

This is risky what will happen if the user opens another post meanwhile?

2019-10-31 17:51 UTC, SergioEstevao commented
Anyway I don't think these bugs are related to this change or the original sync rich text PR. I think we should merge this PR and open two tickets for the issues you found @etoledom .

2019-10-31 18:10 UTC, etoledom commented
Previously, in the same two scenarios, the final html had a proper image url. The problem was that the url was from the caption image wrongly uploaded.

Now that the caption image is not longer uploaded, the local file url stays in the final html.

I’m not completely sure which one does less harm, but being able to save and publish a post with a local file url doesn’t look good 🤔

2019-10-31 20:26 UTC, SergioEstevao commented
> Now that the caption image is not longer uploaded, the local file url stays in the final html.

When you say caption image are you referring to the thumbnail image?

2019-11-01 07:48 UTC, etoledom commented
> When you say caption image are you referring to the thumbnail image?

Yes! That's it

2019-11-01 08:33 UTC, etoledom approved these changes
Since this PR also fixes the broken copy paste from Photos app, let's go with it! ✅ 

We can track these two other issues separately. 👍

2019-11-01 09:24 UTC, pinarol commented on packages/block-library/src/media-text/media-container.native.js
> +		if ( mediaId && mediaUrl && mediaUrl.indexOf( 'file:' ) === 0 && mediaType === MEDIA_TYPE_IMAGE ) {
We should remove `mediaType === MEDIA_TYPE_IMAGE` it was a condition for `requestMediaImport `

2019-11-01 09:39 UTC, pinarol requested changes
We should fix the the conditions to call mediaUploadSync() in media-text, otherwise video upload will not work when we close/reopen post

2019-11-01 10:09 UTC, pinarol approved these changes
Tested with media-text, image and video.

Working good

2019-11-01 10:16 UTC, merged

2019-11-01 10:34 UTC, etoledom commented
And update on https://github.com/WordPress/gutenberg/pull/18215#pullrequestreview-310042627:

After more testing, the issue that refers to:
> This can be reproduced by publishing/saving as draft while the upload is in progress, and opening the editor again before the upload finishes.

... was a confusion. The upload is properly continuing, and the proper remote image URL is synced when the upload finishes.

The confusion was given that, when the upload reaches 0.999%, the backend will spend some time processing the image, and we won't receive further updates until it finishes. If the post is re-opened in this period, gutenberg won't receive any update and the UI won't show any progress.

This period can get quite long if the image is big, around 15-20(s) on my tests. Making this more confusing.

In this period, is also not possible to publish the post with the provisional local `file:` url. The publish logic will always wait until the media upload finishes.

Given that this was not a real issue, we have decided to go ahead with this PR.

2019-11-01 11:11 UTC, hypest commented
Nice collaboration on this PR @koke @SergioEstevao @etoledom @pinarol 👏