Update CONTRIBUTORS.md
WordPress/gutenberg pull request #1822
Opened 2017-07-09 14:12 UTC by ahmadawais

Got wrong props for REST API contribution since my username at WP.org is different than what I have on GitHub. It's one of those better safe than sorry PR's for me ;)

2017-07-09 23:31 UTC, ntwb commented
@ahmadawais, I've just merged #1350 which adds a new column for w.org usernames.

Could you rebase this PR and add your w.org username in the new column please?

2017-07-09 23:32 UTC, ntwb requested changes
See comment above

2017-07-09 23:50 UTC, ahmadawais commented
@ntwb Thanks for that. I just updated the patch! Kindly, merge it :)

2017-07-10 00:01 UTC, ntwb approved these changes

2017-07-10 00:01 UTC, merged