NavigationMenu: set appender color
WordPress/gutenberg pull request #18327
Opened 2019-11-06 16:12 UTC by retrofox

## Description

It sets the appender color when the navigation menu has defined a text color.

## How has this been tested?
Apply text color from the colors selector and confirm that the color is being applied at the appender as well.

## Screenshots 

**before**

<img width="400" alt="Screen Shot 2019-11-06 at 1 09 39 PM" src="https://user-images.githubusercontent.com/77539/68315587-c34e3b80-0096-11ea-8e62-23ad375c1a51.png">

<img width="400" alt="Screen Shot 2019-11-06 at 1 08 44 PM" src="https://user-images.githubusercontent.com/77539/68315588-c3e6d200-0096-11ea-9ec0-0e36a0c10060.png" />

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

2019-11-07 00:37 UTC, obenland commented
By adjusting the appender color we set ourselves up for a situation where the contrast with the background is so low that it won't be visible and hampers usability.

I wonder if instead, we should give it a white or black background and border and keep it the opposite color to make it always visible. Something like this?

<img width="244" alt="image" src="https://user-images.githubusercontent.com/1398304/68349949-ad9b3f00-00b3-11ea-98b8-94c90fbae7d2.png">

2019-11-07 08:54 UTC, draganescu commented
I added the design labels as this might be an approach that impacts future blocks as well.

2019-11-07 08:55 UTC, draganescu requested changes
the code is fine, but the solution needs to be confirmed by some design argument.

2019-11-08 12:23 UTC, retrofox commented
Testing with twenty-twenty I see how that the appender looks, pretty similar how @obenland [mentioned before](https://github.com/WordPress/gutenberg/pull/18327#issuecomment-550566071):

![image](https://user-images.githubusercontent.com/77539/68476367-3d9ecd00-0209-11ea-8b5c-0da58a5b1377.png)

2019-11-08 23:13 UTC, karmatosed commented
I like the idea of a white background for it, means it's more consistent with expected appenders. My only wonder is other appenders on that page might not have it.

![image](https://user-images.githubusercontent.com/253067/68516865-2dc0d080-027d-11ea-9add-2eba8d7b7315.png)

This is an example.

We do seem to colour one and not the other so there might be history there we can fall on:

![image](https://user-images.githubusercontent.com/253067/68516929-6e204e80-027d-11ea-8962-fe0109b193e8.png)

2019-11-09 14:56 UTC, retrofox commented
> I like the idea of a white background for it, means it's more consistent with expected appenders. My only wonder is other appenders on that page might not have it.

Right, consistency is a valid point. Coloring the appender with the  text color (first approach on this PR) maybe make more sense?

2019-12-19 16:07 UTC, karmatosed commented
> Right, consistency is a valid point. Coloring the appender with the text color (first approach on this PR) maybe make more sense?

This feels like maybe best yes.

2020-01-15 23:50 UTC, apeatling commented
The one issue with using text color is that it might still have low contrast if the user selects a low contrast text color. Having said that since it's a user selection I think that seems okay.

2020-01-16 12:05 UTC, retrofox commented
> The one issue with using text color is that it might still have low contrast if the user selects a low contrast text color. Having said that since it's a user selection I think that seems okay.

Yes, any control should be accessible beyond the user customization. Maybe, by mistake, the user sets a wrong combination and stop seeing the appender button. Anyway, this possibility can happen in the current implementation.

2020-01-16 13:43 UTC, retrofox commented
Also, we should keep in mind the probably the styles will change soon according to changes suggeated here https://github.com/WordPress/gutenberg/pull/19681

2020-01-29 18:35 UTC, shaunandrews commented
> I wonder if instead, we should give it a white or black background and border and keep it the opposite color to make it always visible.

I think this is the best solution. This is how the inserter works normally when using a theme with a dark background, always showing a white background behind the + icon.

2021-03-15 11:23 UTC, jasmussen commented
Since the appender now has a black background, can we close this one?

2021-03-15 11:44 UTC, draganescu commented
Yes.

2021-03-15 11:44 UTC, closed without merging