Navigation: Have submenu inherit background color
WordPress/gutenberg pull request #18465
Opened 2019-11-12 22:16 UTC by obenland

Fixes a bug in Twenty Twenty where list items are indented with margins, revealing the white background color od submenu `ul` elements.

## Screenshots 
**Before:**
![Screen Shot 2019-11-12 at 2 12 49 PM](https://user-images.githubusercontent.com/1398304/68715420-d1003700-0556-11ea-999e-ecf83051aa70.png)

**After:**
![Screen Shot 2019-11-12 at 2 13 02 PM](https://user-images.githubusercontent.com/1398304/68715421-d198cd80-0556-11ea-9f80-68fb5f2ebac0.png)

## Types of changes
CSS-only bug fix (non-breaking change which fixes an issue)

2019-11-12 23:41 UTC, tellthemachines requested changes
By default, the nav has no `background-color` set. Also by default, the value of `background-color` is `transparent. This results in a transparent submenu:

<img width="536" alt="Screen Shot 2019-11-13 at 10 31 04 am" src="https://user-images.githubusercontent.com/8096000/68719841-58a28000-0601-11ea-8600-d638e495b1c1.png">

To fix this, we need to make sure that `<nav>` always has a `background-color` set (we probably have to set it inline, and default to whatever the theme background color is), and then set `background-color` to `inherit` for _all_ of its child `<ul>` and  `<li>` elements.

2019-11-13 00:09 UTC, obenland commented
> To fix this, we need to make sure that <nav> always has a background-color set (we probably have to set it inline, and default to whatever the theme background color is)

I'm afraid that won't work either, tons of themes have a white background for their content area and a different color for their site background. Maybe this needs to be a Twenty Twenty-specific fix. And for the rest we hope they use paddings to indent list items and not margins.

2019-11-13 00:15 UTC, obenland commented
@tellthemachines 0ca682f226298989bc3d71fc150b1501831c77bb could work.

2019-11-13 00:38 UTC, tellthemachines commented
> @tellthemachines [0ca682f](https://github.com/WordPress/gutenberg/commit/0ca682f226298989bc3d71fc150b1501831c77bb) could work.

The problem is not Twenty Twenty-specific, it's just super obvious in Twenty Twenty because its background isn't white 😅 
If we leave the background set to white, it will still look broken in Twenty Twenty, unless the user sets a custom background. But if we remove the background or set it to inherit, it will look broken on every single theme, unless the user sets a custom background. So on the whole doing nothing will cause less breakage 🤔 
The problem is we're in this weird hybrid area where we're defining very opinionated styles (such as the dropdown for submenus) but leaving other aspects of styling (such as colour scheme) up to themes. But it doesn't work so well because in CSS-land all these things are interrelated. Ultimately it might be preferable to not define dropdowns as default, and leave that up to the theme styles too 🤷‍♀ 

To the problem at hand: do we have access to the theme content area colour, if it exists? Should we even assume that the nav is going to be placed within the content area? 

If there's no good way of solving this, I'm more inclined to leave the dropdown background white by default than make it transparent, because the transparency makes it much harder to read, whereas the white only looks a bit off it the background is a different colour.

2019-11-13 00:39 UTC, tellthemachines approved these changes
Approving the latest changes based on my previous comment!

2019-11-13 11:15 UTC, retrofox commented on packages/block-library/src/navigation-menu/style.scss
> +	.has-background-color + ul {
:100:

2019-11-13 11:15 UTC, retrofox approved these changes
LGTM 👍

2019-11-13 11:16 UTC, merged