Adding border to table header & footer #18767
WordPress/gutenberg pull request #19136
Opened 2019-12-13 20:34 UTC by dpkm95

## Description
Added 2px border-bottom to header and border-top to footer. Design suggested by @shaunandrews in #18767 
![image](https://user-images.githubusercontent.com/7881389/70829991-fd9cae00-1da3-11ea-8534-75747baa3ce0.png)

## How has this been tested?

## Screenshots 
<img width="615" alt="Screen Shot 2019-12-13 at 12 31 52 PM" src="https://user-images.githubusercontent.com/7881389/70830258-aba85800-1da4-11ea-8cfe-7be7794d9dd5.png">
<img width="614" alt="Screen Shot 2019-12-13 at 12 31 39 PM" src="https://user-images.githubusercontent.com/7881389/70830259-aba85800-1da4-11ea-8174-caaabbe9a0ec.png">
<img width="616" alt="Screen Shot 2019-12-13 at 12 31 11 PM" src="https://user-images.githubusercontent.com/7881389/70830260-ac40ee80-1da4-11ea-93e4-a7b0563bc72a.png">
<img width="628" alt="Screen Shot 2019-12-13 at 12 30 54 PM" src="https://user-images.githubusercontent.com/7881389/70830262-ac40ee80-1da4-11ea-9fc8-e228c43735e1.png">

## Types of changes
CSS changes limited to editor view.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR. .

2019-12-13 20:35 UTC, dpkm95 commented
@ajitbohra I see there are no failing tests after after my change. Do you need me to add a snapshot test for table component? I see it's only added in block-library/embed. Is there any reason why snapshot tests are not added pervasively?

2019-12-15 02:55 UTC, dpkm95 commented
@talldan do you have any feedback on this pr?

2019-12-16 16:02 UTC, shaunandrews commented
I like it. I wonder if it would stand out just a _little_ more at 3px?

2019-12-17 05:59 UTC, dpkm95 commented
@shaunandrews this is how it looks 2px vs 3px -
<img width="1152" alt="Screen Shot 2019-12-16 at 9 48 33 PM" src="https://user-images.githubusercontent.com/7881389/70968894-5643a380-204f-11ea-908c-5171297999f1.png">
<img width="1152" alt="Screen Shot 2019-12-16 at 9 48 33 PM copy" src="https://user-images.githubusercontent.com/7881389/70968899-5a6fc100-204f-11ea-9c1d-e0a01adbee42.png">

2019-12-18 08:13 UTC, talldan commented
I tried it out with the Gutenberg Starter Theme (https://github.com/WordPress/gutenberg-starter-theme):
![Screen Shot 2019-12-18 at 4 09 31 pm](https://user-images.githubusercontent.com/677833/71068077-d7ff1280-21b0-11ea-9e24-f91b08fa7193.png)

At the moment the style is only applied in the editor, and I think the styles should be consistent when also viewing the post. @dpkm95 To do that, these styles could be added to the table block's theme.scss file, which should apply to both the editor and the post. That file is generally for slightly more opinionated styles that are optional for themes to use.

2019-12-18 17:34 UTC, dpkm95 commented
@talldan thanks for the feedback. Do you like 2px or 3px border? +@shaunandrews.
@talldan I'm facing an issue when I move it to style.scss[0]. In preview & render view the themes/twentytwenty/style.scss loads after block-library/table.style.scss[1], it should be other way around as it is in editor view[2]. Is this done for a reason? If not how to fix it?

[0]<img width="586" alt="Screen Shot 2019-12-18 at 9 22 45 AM" src="https://user-images.githubusercontent.com/7881389/71109149-812a1680-2179-11ea-8f08-f8e14278d45b.png">

[1] ![image](https://user-images.githubusercontent.com/7881389/71109017-3b6d4e00-2179-11ea-9583-a3f7278855aa.png)

[2] <img width="327" alt="Screen Shot 2019-12-18 at 9 26 27 AM" src="https://user-images.githubusercontent.com/7881389/71109047-4922d380-2179-11ea-9f97-1c276c650468.png">

2019-12-18 17:53 UTC, shaunandrews commented
> Do you like 2px or 3px border?

I have a slight preference for the 3px visually. Maybe others have differing opinions, I'll get more eyes.

2019-12-18 19:49 UTC, shaunandrews commented
A few more people chimed in on Slack — lets go with 3px.

2019-12-19 07:38 UTC, talldan commented
@dpkm95 As mentioned above, this should go in the theme.scss stylesheet, not the style.scss stylesheet.

In terms of Twenty Twenty, it was a surprise to me, but it looks like that theme doesn't support default block styles:
https://developer.wordpress.org/block-editor/developers/themes/theme-support/#default-block-styles

Any changes added to the theme.scss won't be visible when viewing a post in Twenty Twenty. It's up to the theme to add styling as it sees fit.

My recommendation would be to use a different theme to test this feature. Generally a good one to use is the Gutenberg Starter Theme (https://github.com/WordPress/gutenberg-starter-theme), as it's more of a base theme than other themes. You can download it from the repo using the `Clone or Download` button, and then upload that directly into your dev environment.

Twenty Nineteen also seems to work fine. I also tried a few older themes, but they seem to have `border-collapse: separate;` specified which stops them working correctly.

2019-12-20 02:09 UTC, dpkm95 commented
@talldan thanks for the clarification, It works for me with gutenberg-starter-theme! I've moved the styles to theme.scss, can you please review the pr.

2019-12-20 08:42 UTC, talldan commented
@dpkm95 Looking good! What do you think about also adding the placeholder text for the header and footer cells as described in this comment - https://github.com/WordPress/gutenberg/issues/18767#issuecomment-561771034?

2019-12-21 08:49 UTC, dpkm95 commented
@talldan I've updated pr with placeholder. Thanks for the review!

2020-01-06 04:28 UTC, talldan approved these changes
This looks good to me, thanks for all your hard work @dpkm95!

2020-01-06 08:02 UTC, Soean requested changes
The placeholders should be translatable. You can add the translation function like this: `__( 'placeholder label' )`

2020-01-06 08:02 UTC, Soean commented on packages/block-library/src/table/edit.js
> +								placeholder = 'Footer label';
This string should also be translatable.

2020-01-06 22:47 UTC, dpkm95 commented on packages/block-library/src/table/edit.js
> +								placeholder = 'Header label';
@Soean thanks

2020-01-06 22:48 UTC, dpkm95 commented
> This looks good to me, thanks for all your hard work @dpkm95!

Thanks @talldan looking forward to more contributions!

2020-01-06 23:12 UTC, dpkm95 commented
latest pr: https://github.com/WordPress/gutenberg/pull/19450 with correct github user & email

2020-01-06 23:12 UTC, closed without merging

2020-01-07 01:10 UTC, talldan commented on packages/block-library/src/table/edit.js
> +								placeholder = 'Header label';
Good catch!