Adds the new replace flow to the video block
WordPress/gutenberg pull request #19162
Opened 2019-12-16 11:28 UTC by draganescu

## Description
There is a new replace flow offered by a component which is currently implemented in the Image Block. This PR implements the new flow in the Audio Block.

## How has this been tested?
Tested locally.

## Screenshots 

<img width="642" alt="Screenshot 2019-12-16 at 13 27 34" src="https://user-images.githubusercontent.com/107534/70903605-e3630a00-2007-11ea-83dd-859ee439b1ab.png">

2019-12-29 17:39 UTC, Soean requested changes
The replacement flow works great 👍. If we don't use the state `editing` anymore, we can remove it from this component.

2020-01-06 09:31 UTC, draganescu commented
Hi @Soean I removed the useless state in [960fdaa](https://github.com/WordPress/gutenberg/pull/19162/commits/960fdaaeacc7d52fcbfccaef87c53ac6b9b3d9b8). Thank you for reviewing all these!

2020-01-06 18:59 UTC, Soean approved these changes
Works great.
We can remove some old comments. Maybe we can do it in another PR.

2020-01-06 18:59 UTC, Soean commented on packages/block-library/src/video/edit.js
>  		// edit component has its own src in the state so it can be edited
The `src` state was removed in #6820, so we can remove this comment.

2020-01-06 18:59 UTC, Soean commented on packages/block-library/src/video/edit.js
> +		// Set the block's src from the edit component's state
We also can remove this comment, it's not valid since #6820

2020-01-07 09:23 UTC, Soean approved these changes
Works great, so we can merge it.

2020-01-07 09:37 UTC, merged