Moved "Welcome guide" link to options modal dialog
WordPress/gutenberg pull request #19499
Opened 2020-01-07 22:27 UTC by mapk

## Description
Fixes #19443. 

Move the Welcome Guide link to the Option modal dialog. It is now under the "General" category next to the "Inserter Help Panel" which seems fitting. This is in an effort to help alleviate the redundancy of two "Tools" sections in the interface as recorded in https://github.com/WordPress/gutenberg/issues/19409.

## How has this been tested?
Tested locally.

## Screenshots

**Option modal dialog**

![Screen Shot 2020-01-07 at 2 25 37 PM](https://user-images.githubusercontent.com/617986/71934582-a1863900-3159-11ea-8c6c-fd7463dbe61a.png)

**Gif of interaction**

![welcome-guide 2020-01-07 14_21_28](https://user-images.githubusercontent.com/617986/71934603-ab0fa100-3159-11ea-8fe0-ee6b4743b351.gif)

## Types of changes
Moving a link from one location to another. Non-breaking, maybe?

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

2020-01-07 22:29 UTC, mapk commented
One concern I have is that by adding this to the Option modal dialog, when I click to check this feature "on", the dialog disappears immediately and the Welcome Guide appears.

Is this okay a11y-wise? Design-wise?

2020-01-16 04:45 UTC, noisysocks requested changes

2020-01-16 04:45 UTC, noisysocks commented on packages/edit-post/src/plugins/index.js
> -import WelcomeGuideMenuItem from './welcome-guide-menu-item';
Let's delete the `packages/edit-post/src/plugins/welcome-guide-menu-item` directory as part of this PR.

2020-05-01 21:48 UTC, enriquesanchez commented
>One concern I have is that by adding this to the Options modal dialog, when I click to check this feature "on", the dialog disappears immediately and the Welcome Guide appears.

I think this could cause issues due to the unexpected focus loss. Because the checkmark is not really a button or link, users wouldn't be expecting for it to move them elsewhere in the UI.

I think we could work around that by using a link instead.

2020-05-05 15:14 UTC, mapk commented
@enriquesanchez I'm willing to try that route if it helps minimize the links under the Tools section in the Options popover. Let's make it a link.

2020-05-06 06:29 UTC, noisysocks commented
Before https://github.com/WordPress/gutenberg/pull/18041 we had it so that persisting the option wasn't done until the modal was closed. In other words, the user would toggle the checkbox, press X, and _then_ see the welcome guide appear.

2020-05-06 15:34 UTC, enriquesanchez commented
@noisysocks That is a good point. 

If I check the option and see the Welcome Guide modal, it means that once I'm finished going through the steps this option will be again turned off, correct?

I ask because I'm trying to figure out if a checkbox is the right control for this. If this is not a "persistent" setting, should it be a setting at all?

To me, the current behavior feels more appropriate.

If we wanted to take it a step further, we could even change the link to "See the Welcome Guide".

2020-05-06 20:22 UTC, mapk commented
If we can keep it a checkbox, I prefer that option. It will align with the other settings better.

2020-05-07 04:48 UTC, noisysocks commented
> If I check the option and see the Welcome Guide modal, it means that once I'm finished going through the steps this option will be again turned off, correct?

Correct, if we implement something similar to what was done before https://github.com/WordPress/gutenberg/pull/18041.

2020-09-01 21:32 UTC, napolitano commented
Please don't take it too badly if I post a few thoughts about the "Welcome Guide" in the following, free of the liver. But after searching half of the internet in vain for a *useful* solution to permanently disable this feature, I'm a bit annoyed - because this Welcome Guide has hindered me several times in the last days.
 
So here are some thoughts from the point of view of a Wordpress user (of course purely subjective without claiming to be valid for all or the majority of users):

- The "Welcome Guide" has very little value from the user's point of view. It is not very helpful for new users and superfluous for experienced users
- The "Welcome Guide" - when displayed - hinders the use of Wordpress and forces an interaction
- The "Welcome Guide" is displayed without being asked - for example, there is no query during installation whether such functionality is desired
- There is currently no way to turn it off permanently - for example via wp-config or the menu option "Settings

Personally, I find the Welcome Guide very annoying and in my personal opinion it is not helpful to promote the editor "Gutenberg" in a positive way - at least not in its current form.

My advice to all involved would be - even before any redesigns & Co. are discussed - to make this "feature" safely disableable for the time being. Ideally via a graphical switch on the "Settings" page - or at least via a configuration option in wp-config.php to allow experienced users to turn it off.

This also gives you time to think about the feature as a whole. The Welcome Guide in its current form brings almost nothing to new users - a guided tour with context bubbles that show where to find features and what to use them for would certainly be more beneficial for this target group - and a query "Do you already have experience with the Gutenberg Editor?" during the installation, in order to activate such a tour, would be great.

2020-09-02 17:01 UTC, mapk commented
I, too, believe it would be appropriate to automatically check "off" the Welcome Guide after someone has gone through it or dismissed it. Yes, this makes the checkbox interaction a little awkward, so I'm open for alternatives like a link. But my big desire here is to move it from the first "Options" popover into the second "Options" modal.

2020-11-17 16:45 UTC, mapk commented
There's been some recent changes to the Options modal, so we should evaluate if this is still a good solution or not. I'd like to continue to make sure we're grouping settings effectively and logically. I'll have another look at this soon.

2022-07-27 23:03 UTC, annezazu commented
A ton has changed in this general experience since this PR was opened. Closing this out as a result due to inactivity.

2022-07-27 23:03 UTC, closed without merging