Add tag selector to lastest posts widget, add tag selector to queries
WordPress/gutenberg pull request #19755
Opened 2020-01-19 19:25 UTC by eriktdesign

## Description
Add a selector to filter by tags to the Latest Posts block. Modeled on the Categories filter, works the same way.

## How has this been tested?
Tested in WP 5.3.2 on TwentyTwenty using Local running PHP 7.3.2. Passes the test suite. Added a file in the QueryControls module called tag-select.js -- it is a nearly exact copy of category-select.js, just changes variable names to use tags.

## Screenshots 
![image](https://user-images.githubusercontent.com/730032/72686932-42b0b000-3ac7-11ea-97e2-a41bf1e35701.png)

## Types of changes
New feature: Adds a Tag selection dropdown to the "Latest Posts" block
New feature: Add tag selection to QueryControl

## Checklist:
- [X ] My code is tested.
- [X ] My code follows the WordPress code style. 
- [X ] My code follows the accessibility standards. 
- [X ] My code has proper inline documentation. 
- [X ] I've included developer documentation if appropriate. 
- [X ] I've updated all React Native files affected by any refactorings/renamings in this PR. .

2020-01-19 19:25 UTC, eriktdesign commented
Fixes #13027

2020-01-19 19:26 UTC, eriktdesign commented
First ever PR on Gutenberg!

2020-02-19 13:03 UTC, draganescu requested changes
I have rebased and tested this and the problem is that the posts don't appear because of a bad argument to get_posts. 

However even fixing that, I am unsure of tags being best selected by a dropdown, we should have an autosuggest open entry field. Tags, unlike categories, tend to be many, and that select would become impossible to track with the mouse.

2020-02-19 13:03 UTC, draganescu commented on packages/components/src/query-controls/tag-select.js
> +		<TreeSelect
I wonder if this is the best form input to use. Isn't the one used at document level tag assignment better `TokenInput` ?

2020-02-19 13:08 UTC, draganescu commented
Howdy @eriktdesign and congrats on your first PR here and welcome! I have added a review with two requests but other than that things look all right :)

This will be an important addition to the next phase of the`LatestPosts` block (see the overview issue #20046). Be sure to check that overview issue out as well :)

2020-03-19 09:16 UTC, draganescu commented
Since there has been almost a month of no activity here and given that #20785 is more advanced into implementing multiple tag filters I will close this PR. Thank you @eriktdesign. This was the base PR for #20785!

2020-03-19 09:16 UTC, closed without merging