Docs: Contributor Guide update subpages
WordPress/gutenberg pull request #19939
Opened 2020-01-29 05:25 UTC by mkaz

## Description

Continues updates to Contributor Guide, see previous work in #19853 
These changes update the main sub-pages of the guide, providing consistent info at the top for each section.

* [Main Contributor Guide page](https://github.com/WordPress/gutenberg/tree/update/docs-contrib-dev/docs/contributors) minor change for formatting, adding bold to start of bullet list

* [Code Contribution](https://github.com/WordPress/gutenberg/blob/update/docs-contrib-dev/docs/contributors/develop.md) changes rename page to the type of contribution, not the person, this is inline with Design and Documentation. Add Discussion, Development Hub sections. Remove Grammar and Scripts links from resources since not related to Contributing, will surface elsewhere. Remove Localizing since i18n is now linked to from top section and translating is different than contributing code.

* [Design Contrubtion](https://github.com/WordPress/gutenberg/blob/update/docs-contrib-dev/docs/contributors/design.md) update top section with discussion area.

* [Documentation Contribution](https://github.com/WordPress/gutenberg/blob/update/docs-contrib-dev/docs/contributors/document.md) update top section with discussion area. Add section for two types of documentation User vs Developer. Add link to Git workflow and additional explanation with an update example. 

@bph If you can take a look at the short explanation on how to contribute to Gutenberg User docs, I'm not real happy with what I have now, which basically says ask in Slack. Is there an existing page or link for better info? I think tasks are tracked in Trello or Google Docs, hence the "ask in Slack" which they can get access and links.

## How has this been tested?

Documentation. Browse live on branch see links above to each page.

2020-01-29 15:02 UTC, bph commented
@mkaz 

> User documentation is information on how to use the Editor as an author publishing posts. For contributing to user docs, follow docs blog above to see priorities. Ask in #docs channel for latest list of priorities for user docs.

That's right now the process. It's not ideal, and end users certainly won't go through the trouble of creating a slack account. We are aware of that: We have been thinking about adding a feedback section right on each page so people can leave a note there we then triage and add to the to-do-list. The respective meta ticket is here: https://meta.trac.wordpress.org/ticket/4915

That's just for background, though. Right now I don't have a better way to connect, than Docs Channel.

2020-01-29 21:37 UTC, mkaz commented
Thanks @bph for the response. Not a problem, it takes time to get the processes right, and always iterated upon. As long as we're sending people to the right spot to get answers that's a plus for now.

2020-02-09 19:27 UTC, chrisvanpatten requested changes
Some small nits on formatting/grammar. Awesome improvements!

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/design.md
> +Real-time discussions for design take place in the `#design` channel in [Slack](https://make.wordpress.org/chat). Weekly meetings for Design are on Weds at 19:00UTC.
```suggestion
Real-time discussions for design take place in the `#design` channel in [Make WordPress Slack](https://make.wordpress.org/chat) (registration required). Weekly meetings for the Design team are on Wednesdays at 19:00UTC.
```

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/design.md
> +## How Can Designers Contribute
```suggestion
## How Can Designers Contribute?
```

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/design.md
> +The Gutenberg project uses Github for managing code and tracking issues. The main repository is at: [https://github.com/WordPress/gutenberg](https://github.com/WordPress/gutenberg).
```suggestion
The Gutenberg project uses GitHub for managing code and tracking issues. The main repository is at: [https://github.com/WordPress/gutenberg](https://github.com/WordPress/gutenberg).
```

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/design.md
> +This section outlines the design principles and patterns of the editor interface--to explain the background of the design, inform future improvements, and help people design great blocks.
```suggestion
This section outlines the design principles and patterns of the editor interface—to explain the background of the design, inform future improvements, and help people design great blocks.
```

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/develop.md
> +Real-time discussions for development take place in `#core-editor` and `#core-js` channels in [Slack](https://make.wordpress.org/chat). Weekly meetings for Editor are on Weds at 14:00UTC, and for Jav
```suggestion
Real-time discussions for development take place in `#core-editor` and `#core-js` channels in [Make WordPress Slack](https://make.wordpress.org/chat) (registration required). Weekly meetings for the editor component are on Wednesdays at 14:00UTC, and for the JavaScript component on Tuesday at 14:00UTC, in their respective Slack channels.
```

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/develop.md
> +The Gutenberg project uses Github for managing code and tracking issues. The main repository is at: [https://github.com/WordPress/gutenberg](https://github.com/WordPress/gutenberg).
```suggestion
The Gutenberg project uses GitHub for managing code and tracking issues. The main repository is at: [https://github.com/WordPress/gutenberg](https://github.com/WordPress/gutenberg).
```

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/document.md
> +Real-time discussions for documentation take place in the `#docs` channel in [Slack](https://make.wordpress.org/chat). Weekly meetings for Documentation are on Mon at 54:00UTC.
```suggestion
Real-time discussions for documentation take place in the `#docs` channel in [Make WordPress Slack](https://make.wordpress.org/chat) (registration required). Weekly meetings for the Documentation team are on Mondays at 14:00UTC.
```

Pretty sure 14:00 is correct!

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/document.md
> +The Gutenberg project uses Github for managing code and tracking issues. The main repository is at: [https://github.com/WordPress/gutenberg](https://github.com/WordPress/gutenberg).  To find document
```suggestion
The Gutenberg project uses GitHub for managing code and tracking issues. The main repository is at: [https://github.com/WordPress/gutenberg](https://github.com/WordPress/gutenberg).  To find documentation issues to work on, browse [issues with documentation label](https://github.com/WordPress/gutenberg/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22%5BType%5D+Documentation%22+).
```

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/document.md
> +
```suggestion
```

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/document.md
> +1. [User documentation](https://wordpress.org/support/article/wordpress-editor/) is information on how to use the Editor as an author publishing posts. For contributing to user docs, follow docs blog
```suggestion
1. [User documentation](https://wordpress.org/support/article/wordpress-editor/) is information on how to use the Editor as an author publishing posts. For contributing to user docs, follow the docs blog, or ask in the #docs Slack channel, to understand the current priorities.
```

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/document.md
> +2. [Block Editor Handbook](https://developer.wordpress.org/block-editor/) is everything related to the Gutenberg project including: developing, extending, and--what you are reading right now--contrib
```suggestion
2. [Block Editor Handbook](https://developer.wordpress.org/block-editor/) is everything related to the Gutenberg project including: developing, extending, and—what you are reading right now—contributing specific to Gutenberg.
```

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/document.md
> +4. Commit change
```suggestion
4. Commit your changes.
```

2020-02-09 19:27 UTC, chrisvanpatten commented on docs/contributors/document.md
> +5. Create a pull-request with "Documentation" label.
```suggestion
5. Create a pull request with "Documentation" label.
```

2020-02-10 17:06 UTC, chrisvanpatten approved these changes
Looks great!

2020-02-10 18:16 UTC, merged