Fixes js warning when using select control and change onBlur to onChange
WordPress/gutenberg pull request #2000
Opened 2017-07-25 09:52 UTC by truongwp

This PR fixes js warning `Use the defaultValue or value props on <select> instead of setting selected on <option>` when using select control, and change onBlur to onChange like other controls.

2017-07-25 12:08 UTC, aduth requested changes

2017-07-25 12:08 UTC, aduth commented on blocks/inspector-controls/select-control/index.js
> +function SelectControl( { label, selected, instanceId, onChange, options = [], ...props } ) {
There's a lint warning that `selected` is unused.

I think we'll want to promote the idea of [Controlled Components](https://facebook.github.io/react/docs/forms.html#controlled-components) for inputs and encourage the developer to pass the value explicitly.

The React docs touch on the issue that existed here, and their workaround:

https://facebook.github.io/react/docs/forms.html#the-select-tag

2017-07-25 12:08 UTC, aduth commented on blocks/inspector-controls/select-control/index.js
> +				onChange={ onChangeValue }
While we chose `onBlur` in the case of the Mode Switcher, we still opt in to the rule and ideas behind `jsx-a11y/no-onchange`:

https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-onchange.md

There's some related ongoing discussion at #392.

I'm not sure we'd want to make the move from `onBlur` to `onChange` in this case.

2017-07-27 03:03 UTC, truongwp commented
@aduth ok, I changed onChange back to onBlur

2017-07-27 18:29 UTC, aduth commented
Thanks @truongwp . We'll still need to address https://github.com/WordPress/gutenberg/pull/2000#discussion_r129285229, which is related to the failing build.

2017-07-28 22:07 UTC, mattheu commented
I came  across this - whilst investigating something which turned out to be user error (I was thrown by having to use onBlur not onChange)

I'm not sure I understand the need for this change as it is now. I don't see why you would remove the ability to set the selected value.

2017-07-30 16:41 UTC, mattheu commented
Actually I see now what you're trying to do here. However its missing one line... you also need to set the value property on the `select` element, with the value of `selected`. This fixes issues with the build failing.

As documented here: https://facebook.github.io/react/docs/forms.html#the-select-tag

```
<select
	id={ id }
	className="blocks-select-control__input"
	onBlur={ onBlurValue }
    value={ selected }
	{ ...props }
>
```

2018-01-27 18:58 UTC, gziolo commented
@truongwp or @mattheu do you plan to finish this PR or should someone else take it over?

2018-01-28 16:33 UTC, truongwp commented
Sorry because I'm so busy. I will check it. Thank you.

2018-01-30 08:18 UTC, youknowriad commented
We're using a controlled SelectControl which means we need `value` and `onChange`. A similar behavior could be achieved with an uncontrolled component using `defaultValue`  and `onBlur` but we might miss some bugs where the `onChange` handler wouldn't update the provider value properly. 

So I prefer if we keep the current setup (aka `value` and `onChange`) that way, a block author would know if he/she's persisting the attribute change properly.

Thanks for working in this PR. I'm closing as not needed anymore, let me know if I missed anything here.

2018-01-30 08:18 UTC, closed without merging