Move block server-side logic into same directory as client-side logic
WordPress/gutenberg pull request #2014
Opened 2017-07-25 21:41 UTC by westonruter

When working with dynamic blocks it is not ideal for the JS and PHP logic to be separated out in two separate locations. Ideally the dynamic block server rendering logic as well as unit tests could be placed right inside of the same directory as the client logic. 

This would also impact the Latest Comments block: #1931.

2017-07-26 13:19 UTC, aduth requested changes
See also: #1095

We need to remove this line:

https://github.com/WordPress/gutenberg/blob/44ad46a/bin/build-plugin-zip.sh#L71

And ensure that block PHP files are included in the generated plugin.

2017-07-28 22:35 UTC, westonruter commented
@aduth thanks for that. Fixed in https://github.com/WordPress/gutenberg/pull/2014/commits/bfe31c27e731615c1c3d9c7e8fd00c6fb8b17b74

2017-07-31 13:35 UTC, aduth approved these changes
Verified package plugin loads block correctly.
Verified `composer lint` surfaces issues in the block PHP file.

2017-07-31 13:35 UTC, aduth commented on gutenberg.php
> -	// Register server-side code for individual blocks.
Should we preserve this comment?

2017-07-31 20:03 UTC, merged