Update Documentation
WordPress/gutenberg pull request #2046
Opened 2017-07-27 04:19 UTC by MaedahBatool

Hey,
There were some punctuation and grammatical mistakes which I corrected. Kindly review them. :)

2017-07-27 05:25 UTC, nylen requested changes

2017-07-27 05:25 UTC, nylen commented on README.md
> +This is the development hub for the <a href="https://make.wordpress.org/core/2017/01/04/focus-tech-and-design-leads/">editor focus in the core</a>. Gutenberg is the project name. If you want the late
This is correct as it's currently written. "in core" means "in WordPress core".

2017-07-27 05:25 UTC, nylen commented on README.md
> +> The editor will endeavor to create a new page and post building experience that makes writing rich posts effortless, and has “blocks” to make it easy what today might take shortcodes, custom HTML,
This is the British spelling. It's fine as currently written.

2017-07-27 05:25 UTC, nylen commented on README.md
> +- <a href="http://gutenberg-devdoc.surge.sh/">Documentation: Creating Blocks, Reference, and Guidelines</a>
This is an Oxford comma. It's optional, so it's fine as currently written.

2017-07-27 05:25 UTC, nylen commented on README.md
> +One thing that sets WordPress apart from other systems is that it allows you to create as rich a post layout as you can imagine -- but only if you know HTML & CSS and build your own custom theme. By
:+1:

2017-07-27 05:25 UTC, nylen commented on README.md
> +Every block can be _inspected_ by clicking it. And every block has advanced layout options available in the inspector; text might have drop-cap, the image might have fixed position scrolling. As such
"the image" - `image` refers to a specific block type, same as `text`. We can put backticks `\`` around them but they are correct as currently written.

"into" - :+1:

2017-07-27 07:39 UTC, MaedahBatool commented on README.md
> +This is the development hub for the <a href="https://make.wordpress.org/core/2017/01/04/focus-tech-and-design-leads/">editor focus in the core</a>. Gutenberg is the project name. If you want the late
Okay!

2017-07-27 07:40 UTC, MaedahBatool commented on README.md
> +> The editor will endeavor to create a new page and post building experience that makes writing rich posts effortless, and has “blocks” to make it easy what today might take shortcodes, custom HTML,
👍

2017-07-27 07:40 UTC, MaedahBatool commented on README.md
> +- <a href="http://gutenberg-devdoc.surge.sh/">Documentation: Creating Blocks, Reference, and Guidelines</a>
👍

2017-07-27 18:36 UTC, aduth commented on README.md
> +This is the development hub for the <a href="https://make.wordpress.org/core/2017/01/04/focus-tech-and-design-leads/">editor focus in the core</a>. Gutenberg is the project name. If you want the late
We could be more explicit about "in WordPress core" if it's likely to cause confusion.

2017-09-21 15:56 UTC, gziolo commented
@MaedahBatool do you plan to fix the remaining issues?

2017-12-14 21:13 UTC, karmatosed commented
Closing as no movement on this for a while. We can reopen if someone wants to pick up the changes.

2017-12-14 21:13 UTC, closed without merging