Fix Core Columns butting up against viewport on smaller screens
WordPress/gutenberg pull request #20589
Opened 2020-03-02 15:41 UTC by getdave

On smaller screens, the Core Columns block butts up against the edges of the viewport (unless it has a background set) on both Editor and Frontend.

<img width="501" alt="Screenshot 2020-03-02 at 15 34 35" src="https://user-images.githubusercontent.com/444434/75691010-a5d35c00-5c9b-11ea-80a3-2e0f3e2ac3e0.png">

This PR aims to fix this by introducing left/right spacing around the Block on smaller viewports. This has to be handled differently between Editor and Frontend/Theme due to the way background padding is applied.

<img width="501" alt="Screenshot 2020-03-02 at 15 33 38" src="https://user-images.githubusercontent.com/444434/75691647-40339f80-5c9c-11ea-8d98-6dba71c65d38.png">

This has been tested using the Gutenberg Starter Theme.

## How has this been tested?

Switch to "Code View" and paste in the following test Block definitions:

```

<div class="wp-block-columns alignwide">
<div class="wp-block-column">
<p><strong>Align Wide<br></strong><em>Smoked salmon topped with crème fraîche, dill and capers<br></em>$15.00</p>
</div>

<div class="wp-block-column">
<p><strong>Pork Rillettes<br></strong><em>With quick pickle of dried apricots and pistachio crumble<br></em>$14.00</p>
</div>

<div class="wp-block-column">
<p><strong>Provençal Vegetable Tart<br></strong><em>With seasonal vegetables<br></em>$12.50</p>
</div>
</div>

<div class="wp-block-columns alignwide has-background has-text-color has-luminous-vivid-amber-background-color has-very-dark-gray-color">
<div class="wp-block-column">
<p><strong>Align Wide + Background<br></strong><em>Smoked salmon topped with crème fraîche, dill and capers<br></em>$15.00</p>
</div>

<div class="wp-block-column">
<p><strong>Pork Rillettes<br></strong><em>With quick pickle of dried apricots and pistachio crumble<br></em>$14.00</p>
</div>

<div class="wp-block-column">
<p><strong>Provençal Vegetable Tart<br></strong><em>With seasonal vegetables<br></em>$12.50</p>
</div>
</div>

<div class="wp-block-columns">
<div class="wp-block-column">
<p><strong>Align Default<br></strong><em>Smoked salmon topped with crème fraîche, dill and capers<br></em>$15.00</p>
</div>

<div class="wp-block-column">
<p><strong>Pork Rillettes<br></strong><em>With quick pickle of dried apricots and pistachio crumble<br></em>$14.00</p>
</div>

<div class="wp-block-column">
<p><strong>Provençal Vegetable Tart<br></strong><em>With seasonal vegetables<br></em>$12.50</p>
</div>
</div>

<div class="wp-block-columns alignfull">
<div class="wp-block-column">
<p><strong>Align Full<br></strong><em>Smoked salmon topped with crème fraîche, dill and capers<br></em>$15.00</p>
</div>

<div class="wp-block-column">
<p><strong>Pork Rillettes<br></strong><em>With quick pickle of dried apricots and pistachio crumble<br></em>$14.00</p>
</div>

<div class="wp-block-column">
<p><strong>Provençal Vegetable Tart<br></strong><em>With seasonal vegetables<br></em>$12.50</p>
</div>
</div>

<p class="has-background has-luminous-vivid-orange-background-color">Comparr to this please</p>

```

* On `master`- resize screen to a small viewport 
* Notice how the Columns Block edge butt up against viewport.
* Switch to this PR.
* Resize screen again.
* Notice how the Columns Block edges no longer butt up against viewport.

Do the same on both Editor and when viewing post on Frontend.

## Screenshots 

## Types of changes
Bug fix (non-breaking change which fixes an issue).

Could possibly break some Themes.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-03-02 17:36 UTC, aduth commented
For prioritization' sake, do you have a sense whether this is a regression of recent changes to the column(s) block(s) in #19515 or #20169?

2020-03-02 21:58 UTC, jeryj commented
When I check using the gutenberg starter theme, my editor preview isn't as nicely aligned as your screenshot:
<img width="498" alt="Screen Shot 2020-03-02 at 3 54 14 PM" src="https://user-images.githubusercontent.com/967608/75721617-4c206100-5c9e-11ea-943c-626d10813784.png">

As a potential help in figuring out why that is, my `master` doesn't even show the yellow/orange-ish background at all. The alignment on the full-width does butt up against the side of the window though:
<img width="404" alt="Screen Shot 2020-03-02 at 3 54 39 PM" src="https://user-images.githubusercontent.com/967608/75721712-73772e00-5c9e-11ea-84cf-f99cc8f67130.png">

2020-03-02 22:06 UTC, jeryj requested changes
I'm not sure if I tested correctly due to my screenshots being different from yours. Some more eyes on it would be good. If mine ends up not being right I'll remove the change request. Otherwise it's just two tiny comment spelling corrections 👍

2020-03-02 22:06 UTC, jeryj commented on packages/block-library/src/columns/style.scss
> +// overide generic `.entry-content *` rule
overide should be override

2020-03-02 22:06 UTC, jeryj commented on packages/block-library/src/columns/style.scss
> +		}
It looks like if it's an align-full block, that this padding applies, making it butt up against the window on the front-end:
<img width="1585" alt="Screen Shot 2020-03-02 at 4 02 18 PM" src="https://user-images.githubusercontent.com/967608/75722230-6b6bbe00-5c9f-11ea-8f1e-fafe5c674e4e.png">

2020-03-03 08:43 UTC, jasmussen requested changes
Thank you! This improves things, but I don't think it's the right fix, and I think the regression was potentially due to #17877 — sorry about that.

Specifically if I inspect, the margins look correct a great deal of the way down:

<img width="568" alt="Screenshot 2020-03-03 at 09 33 44" src="https://user-images.githubusercontent.com/1204802/75757330-6efc5500-5d32-11ea-9907-9dfdb715ea41.png">

<img width="571" alt="Screenshot 2020-03-03 at 09 34 18" src="https://user-images.githubusercontent.com/1204802/75757340-73287280-5d32-11ea-8ca4-2f945a16fe9a.png">

So what makes the text butt out like that?

This rule:

<img width="390" alt="Screenshot 2020-03-03 at 09 34 00" src="https://user-images.githubusercontent.com/1204802/75757353-7ae81700-5d32-11ea-9a2a-7f684381d40e.png">

That margin-left: -14px (probably -$block-padding in the code) looks like a remnant of when it was necessary to compensate for the left/right margins that have been refactored. 

**And then I git pulled. The above is no longer accurate it seems.** So, master is different now, possibly due to improvements in #20597. 

Now the text only buts out if the columns block is full-wide, and then honestly it seems expected? Because it does so on desktop breakpoints also:

<img width="1463" alt="Screenshot 2020-03-03 at 09 42 37" src="https://user-images.githubusercontent.com/1204802/75757843-648e8b00-5d33-11ea-8bc8-596d05064aa2.png">

To phrase it differently, there was definitely an issue, but the issue has either changed or even become obsolete overnight. Let me know what you think of master.

2020-03-03 09:39 UTC, getdave commented
> For prioritization' sake, do you have a sense whether this is a regression of recent changes to the column(s) block(s) in #19515 or #20169?

@aduth I'm afraid I don't. However, there's a lot of changes to widths and spacing in those PRs so it could be they caused this. I might try testing altering a few of those properties (esp. `margin` changes) to see if that caused it.

I would also say that's it is extremely easy to introduce this kind of regression given the number of variants (Editor, Frontend, different Themes...etc). Not sure how we solve or guard against this...

2020-03-03 09:44 UTC, getdave commented
> To phrase it differently, there was definitely an issue, but the issue has either changed or even become obsolete overnight. Let me know what you think of master.

@jasmussen Thanks for this. I've pulled `master` this morning and (testing as per instructions above) it's all fixed!

I'm still concerned this issue could be prevalent [on certain Themes](https://github.com/Automattic/themes) so I'll dig into that, but for now I'm happy to close this out. 🎉 

![Uploading Screenshot 2020-03-03 at 09.42.23.png…]()

<img width="499" alt="Screenshot 2020-03-03 at 09 42 38" src="https://user-images.githubusercontent.com/444434/75762932-65272180-5d33-11ea-964f-64c4517373ec.png">

2020-03-03 09:44 UTC, closed without merging

2020-03-03 09:57 UTC, jasmussen commented
Yep. There was a dev-note attached to the margin change, but it is unfortunate that it had to happen. The silver-lining is, however, that the margin math is vastly simpler now.