Top Bar Inserter: Add more space between the inserter button and the tools button.
WordPress/gutenberg pull request #20685
Opened 2020-03-06 16:32 UTC by shaunandrews

Right now, the Tools button is right up against the Inserter button in the top toolbar:

<img width="226" alt="image" src="https://user-images.githubusercontent.com/191598/76102515-1d580280-5f9e-11ea-9554-9f2bd95d43c4.png">

Its feeling a little cramped. This PR adds 8px of margin to the right of the Inserter button:

<img width="201" alt="Screen Shot 2020-03-06 at 11 30 14 AM" src="https://user-images.githubusercontent.com/191598/76102544-28ab2e00-5f9e-11ea-8c88-32f415f8748a.png">

2020-03-06 19:11 UTC, ZebulanStanphill commented
If this is an issue, then I think it should be solved generically, rather than with a one-off adjustment for this specific use-case.

2020-03-08 15:08 UTC, mtias commented
I think we need more space tot he left as well.

![image](https://user-images.githubusercontent.com/548849/76165371-dfeaa500-6156-11ea-86a9-e567ab1525e3.png)

The button with the background is in itself heavier than the rest, so it'd likely need optical adjustments specific to it.

2020-03-09 07:39 UTC, jasmussen approved these changes
OMG I can't believe how I somehow regressed this! Update to use the variable I suggested and ship this as fast as you can.

2020-03-09 07:39 UTC, jasmussen commented on packages/edit-post/src/components/header/style.scss
> +		margin-right: 8px;
This should be `$grid-unit-10`.

2020-03-09 07:52 UTC, jasmussen requested changes
Actually in my excitement to approve this — I just spun up master and saw how this had somehow regressed, I missed good points from Matías and Zeb.

First off, with the fullscreen button, it does deserve a little padding. It's 16px now, Matías mockup shows 22px, but we should just apply the grid and go 24px there. That's `$grid-unit-20`. If you add that, and replace the margin on the right with `grid-unit-10` as mentioned, I think this is good to go as a first pass.

Zeb's comment:

> If this is an issue, then I think it should be solved generically, rather than with a one-off adjustment for this specific use-case.

In #20575 I have a note to "Explore 32px buttons in the header". One of the G2 efforts that is core to the design is to try and align everything to a 12px grid, so 12, 24, 36, 48. This grid is compatible with the icon size, and it's compatible with the 24px minimum button size, and it helps provide rhythm. 

Most of the buttons in the toolbar as they exist today follow this. They have 24px icons, with 6px clearance around them making them 36px. 

However there's an inconsistency with primary buttons currently. The inserter plus is 32px because it optically weights the size to be notable but not overwhelming. But its footprint is not yet 36px, i.e. it should have 2px clearance around itself to fit that space and match the grid. Additionally it might be worth exploring making the Publish button 32px tall vs. 36px as it is now, to match that.

So we should follow up with a PR to pixel-massage those.

2020-03-09 14:45 UTC, jasmussen commented
Created https://github.com/WordPress/gutenberg/pull/20730 as an alternative. Same as this one, with props to Shaun, but created so it can make the RC while it's still night for Shaun :)

2020-03-09 17:47 UTC, shaunandrews commented
Thanks for picking this up while I peacefully slept :)

2020-03-09 17:47 UTC, closed without merging