Add CPT selector tp Latest Posts
WordPress/gutenberg pull request #20831
Opened 2020-03-12 13:25 UTC by Ringish

## Description

Adds a post type selector to the `LatestPosts` (in the `QueryControls`) block as described at #9013 and mentioned in #20046. 

## How has this been tested?

I've tested a few different scenarios where you would choose specific post types in the `LatestPosts` block.
## Screenshots 
![Skärminspelning-2020-03-12-kl -14 23 38](https://user-images.githubusercontent.com/3396172/76526052-3d3f6880-646d-11ea-8269-a2714720773c.gif)

## Types of changes

New feature 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-03-13 06:26 UTC, draganescu requested changes
Looks great. The only major change is that json file that got entirely commited and maybe we should rename that category related variable in the other PR.

Testing locally I noticed all post types are shown, including system types, which should be hidden:

<img width="259" alt="Screenshot 2020-03-13 at 08 29 56" src="https://user-images.githubusercontent.com/107534/76596467-ee461180-6506-11ea-969b-82f4e0b4333d.png">

Normally from that list only Posts and Pages are thing one would want to filter on.

2020-03-13 06:26 UTC, draganescu commented on packages/block-library/src/latest-posts/block.json
> +    "name": "core/latest-posts",
It looks like this file has been reformatted and for no good reason. We should revert this change to only include 

```
 "postType": {
   "type": "string"
 },
```

It's probably an editor spaces setting issue :)

2020-03-13 06:26 UTC, draganescu commented on packages/block-library/src/latest-posts/edit.js
> +		const categorySuggestions = categoriesList.reduce(
you changed this here from [my comment](https://github.com/WordPress/gutenberg/pull/20832#discussion_r391647710) in the other PR right?

2020-03-13 06:26 UTC, draganescu commented on packages/block-library/src/latest-posts/edit.js
> +							suggestions={ Object.keys( categorySuggestions ) }
same, this is from the other PR. if we change in both places we might end up with conflicts 😁

2020-03-13 06:28 UTC, draganescu commented
Trac is also showing a linter issue [here](https://travis-ci.com/github/WordPress/gutenberg/jobs/297335656):

```
gutenberg/packages/block-library/src/latest-posts/edit.js
[0]   471:38  error  'getPostTypes' is assigned a value but never used  no-unused-vars
```

If you setup ESLint in VSCode these will be caught by the editor. Also Gutenberg has some git pre-commit hooks that catch these before the commit, I wonder why they don't run for you.

2020-08-24 14:12 UTC, ntsekouras commented
Hey @Ringish. Thanks for all the work you've done so far in this PR! Do you think you'll find some time to wrap it up? It will be needed to enhance query related functionality.

2020-11-01 16:01 UTC, paaljoachim commented
How is this PR coming along?

Order of controls should probably go like this.
User selects the Post Type.
Then category (or multiple) based on the Post Type selected above.
Then tags (if the user wants to add these in).
Order by
Number of posts to show (or all)

![Screen Shot 2020-11-01 at 16 58 59](https://user-images.githubusercontent.com/5323259/97807893-b7726680-1c63-11eb-88ba-a5c5795c8368.png)

Screenshot from https://wordpress.org/plugins/flex-posts/

2020-11-02 08:32 UTC, ntsekouras commented
Hey @paaljoachim - I think the focus has shifted towards making this block a `Query` block variation, which now has support for CPTs (the block has more work enqueued). Check this issue here: https://github.com/WordPress/gutenberg/issues/26193

2020-11-03 14:17 UTC, draganescu commented
I would close this PR as it will be irrelevant even if it's finalized.

2020-11-03 15:17 UTC, paaljoachim commented
Closing this PR based on above comments by Andrei @draganescu and Nik @ntsekouras 
The Add Posts List block will become a variation of the Query block. The issue for that is here: https://github.com/WordPress/gutenberg/issues/26193

2020-11-03 15:17 UTC, closed without merging