Add subtitle block
WordPress/gutenberg pull request #2091
Opened 2017-07-30 18:38 UTC by iseulde

This is used a lot in newspapers. Pull up on article from e.g. https://theguardian.com, and you'll see all articles have a subtitle. In this one, it can be styled based on the category.

This PR just adds the bare bones.

@notnownikki I can't figure out why the tests are failing from just adding a block. Any ideas?

2017-07-31 08:56 UTC, notnownikki commented
Ah, I think I see... we're adding a new block in the common category, and the max number of blocks in the "recent" tab is 8, but now we have more than 8, and we're pushing put one that the test expects.

I'll change the test so that it checks that all the blocks added to recent initially are from the common category, and that will fix this.

2017-08-02 10:07 UTC, sbangnielsen commented
Adding a subtitles block is really nice, but in order for it to be really useful, theme authors would probably need a way to fetch and manipulate it independently of the rest of the content blob in order to display it on frontpages, search pages, archive pages, feeds etc. - like The Guardian.

[The Subtitles plugin](https://github.com/wecobble/Subtitles) works nicely in that respect.

2017-08-03 13:05 UTC, aduth commented on blocks/library/subtitle/index.js
> +import { __ } from 'i18n';
Note with #2172, these need to be updated to prefix the dependencies with `@wordpress/`. You will need to perform a rebase against the latest version of master and apply your changes:

```
git fetch origin
git rebase origin/master
```

2017-12-14 21:15 UTC, karmatosed commented
I think this would be useful. Can we maybe clean up the conflicts and work on getting this ready?

2017-12-15 11:17 UTC, iseulde commented
Yeah, I think it would be very useful too, though I'm still unsure about the name and potential confusion with other concepts.

The primary reason I created this is to allow for something like a standfirst (subhead) in newspapers and themes like Twenty Sixteen, so the theme can style it differently from the main body text. Maybe subtitle is a bit too broad of a name for this.

The other issue is that, in a lot of cases, this is equivalent to the summary, which makes me wonder if we shouldn't just add that as a block and sync it with the summary field. This may not always be desirable though. If I remember correctly (sorry if I don't), @Helen had a view on this when Twenty Sixteen came out.

2017-12-15 11:20 UTC, iseulde commented
Actually, after looking at some examples, standfirst is definitely different from a summary on the front page.

2017-12-15 12:23 UTC, iseulde commented
Rebased with some additions like transform to paragraph, description, and renamed it "subhead" for US English.

2018-01-04 21:28 UTC, karmatosed commented
I did a little design review on this today. What we currently have is:

![2018-01-04 at 20 29](https://user-images.githubusercontent.com/253067/34583513-ef603bd2-f18f-11e7-868d-25876472ed7b.png)

Could we perhaps italic and make the font a shade lighter? I feel it should be distinctive from the paragraph. I also think having less spacing than a paragraph makes it belong more to the heading. I am thinking something like this:

![artboard](https://user-images.githubusercontent.com/253067/34585061-2d8079e4-f196-11e7-936c-9b82dcd0e30c.png)

2018-01-05 10:43 UTC, karmatosed requested changes
Suggestions commented.

2018-01-08 11:09 UTC, iseulde commented
I think eventually the position will not matter, the author has the freedom to  place this wherever they see fit, or it could be locked in a certain place by the theme? Related: #2089, where the title is also movable.

@karmatosed Do you have any specific recommendations for the styling. Also, isn't this up to the theme to style then, or should we force front-end styles?

2018-01-08 15:19 UTC, karmatosed commented
>  Do you have any specific recommendations for the styling. Also, isn't this up to the theme to style then, or should we force front-end styles?

I think in this case having a default style makes sense, we do it for other styling. What about what I suggested above?

2018-01-08 21:26 UTC, iseulde commented
Yeah, I meant more specific than "a shade lighter". I guess I'll use `opacity: .75`. It's a bit random.

2018-01-09 19:58 UTC, karmatosed commented
@iseulde ah sorry, I added a screenshot of what I was thinking. Maybe go with the same color as the captions?

2018-01-11 10:47 UTC, iseulde commented
@karmatosed Updated. I don't know how to make it appear closer to the title in all themes without setting a negative margin and messing up the styles in Gutenberg. We'll also have to set opacity for to make it lighter on the front-end as we can't use fixed colours there.

2018-01-12 19:34 UTC, karmatosed commented
@iseulde Thanks. I agree, for now then let's leave the negative margin, probably best.

2018-01-19 13:43 UTC, iseulde commented
@karmatosed I haven't added the negative margin. I don't think adding it is a good idea as every theme is different, we might end up overlapping with the previous heading.

2018-01-19 16:03 UTC, karmatosed approved these changes

2018-01-19 16:59 UTC, iseulde commented
Thanks!

2018-01-19 17:00 UTC, merged