Revert #20658) due to issues with image placement and selection
WordPress/gutenberg pull request #21160
Opened 2020-03-26 01:39 UTC by roo2

We deployed GB 7.7.1 to live sites and had reports of issues with image selection from HEs

https://github.com/WordPress/gutenberg/issues/21152
https://github.com/WordPress/gutenberg/issues/21114

more context:

p1585134931014700-slack-wpcom-happy-announce

I tracked it down to being caused by this commit by trial and search through the git history.

I wasn't able to quickly solve the issue surgically, so for now I would like to revert the entire changeset and get the fix out ASAP. I'm currently testing the revert locally and all seems fine, it looks like the commit was refactoring and other code hasn't built on it too much yet 😄 

## Description
Reverts #20658 

## How has this been tested?
Currently going through the affected elements and testing their behaviour WRT positioning and selectability.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-03-26 07:46 UTC, youknowriad commented
It would be good to try to understand the difference in markup causing this issue. There's already some PRs building on top of this change. Notably #20721

2020-03-26 08:01 UTC, ellatrix commented
I don't like that we're reverting this. Let's at least try to fix the issues first.

2020-03-26 08:11 UTC, ellatrix requested changes
Ok, allow me some time to investigate. :)

2020-03-27 07:15 UTC, roo2 commented
Ahh yep I see the more thorough fix #21160, maybe I was a bit hasty to make this the other night the other night :)

2020-03-27 07:15 UTC, closed without merging