Env: Swap out deprecated dep `request`
WordPress/gutenberg pull request #21398
Opened 2020-04-04 12:07 UTC by jessie-ross

## Description
The NodeJS module `request` is deprecated, replace with `got`.
Fixes #21336.

## How has this been tested?
I have tested this locally by manually running the two involved functions `downloadZipSource` and `downloadWordPressZip`.

## Screenshots
![Screen Shot 2020-04-04 at 7 10 41 pm](https://user-images.githubusercontent.com/971886/78450215-a6527e80-76af-11ea-8e05-64a141e7ec25.png)

## Types of changes
Bug Fix: Replacing a dep for the env package, shouldn't be end-user facing.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-04-04 12:12 UTC, jessie-ross commented
While we are here I should note a problem with the `downloadZipSource` - if it is to be used more generally: It expects the zip file to have exactly one folder in it, if not it will take the last file it sees, be it a file or folder and move it to `source.path`.

https://github.com/WordPress/gutenberg/blob/001f700abe75054a7ec59cd1a9957dcebf684730/packages/env/lib/download-source.js#L143-L149

Note that copyDir will happily copy a file instead of a folder.

2020-04-06 04:07 UTC, noisysocks requested changes
Thanks for the PR @jessie-ross! This is looking really good and I confirmed that running `wp-env start` with a ZIP source still works.

2020-04-06 04:07 UTC, noisysocks commented on packages/env/lib/download-source.js
> +	const resStream = got.stream( source.url );
Let's name this `responseStream` so there's no confusion over what `res` means.

2020-04-06 04:07 UTC, noisysocks commented on packages/env/lib/download-source.js
> +	resStream.on( 'downloadProgress', ( x ) => onProgress( x.percent ) );
What is `x`? Let's give it a meaningful name or use destructuring.

```suggestion
	resStream.on( 'downloadProgress', ( { percent } ) => onProgress( percent ) );
```

2020-04-06 06:49 UTC, jessie-ross commented
@noisysocks, thanks for catching those!

I have updated the commit.

2020-04-06 06:54 UTC, noisysocks approved these changes

2020-04-06 06:59 UTC, noisysocks commented
Travis CI has failed with some linting errors. If you run `npm run format-js packages/env/lib/download-source.js` and commit the changes it should be fixed.

```
[0] /home/travis/build/WordPress/gutenberg/packages/env/lib/download-source.js
404[0]   136:59  error  Replace `·onProgress(·percent·)·` with `⏎↹↹onProgress(·percent·)⏎↹`  prettier/prettier
```

2020-04-06 13:23 UTC, jessie-ross commented
@noisysocks, It is passing now - I had to update the package-lock as well.

Ready except for the package-lock, but it seems to change quite frequently. 
Does it just need to be rebased and merged quickly or is there another process around it?

2020-04-07 05:07 UTC, noisysocks commented
Just have to rebase and try again. I'll fix it up on my end so that there's no slow back-and-forth.

Thanks for the fix and congrats on your first PR! 🎉

2020-04-07 05:07 UTC, merged