Update/fix timepicker styling
WordPress/gutenberg pull request #22043
Opened 2020-05-01 21:36 UTC by jgcaruso

## Description
The height of the AM/PM buttons when using the standalone `TimePicker` is higher than the rest of the input controls than when it is used in the full `DateTimePicker` component. This PR fixes the scss definition so the existing height override is also applied to the `TimePicker` when used on its own.

Stories were also added to the component so it can be viewed in Storybook.

## How has this been tested?
This was tested in Storybook to ensure the changes render correctly, as well existing uses of the component (the DateTime picker when choosing a publish time for a post) were tested to ensure their look has not changed.

Test environment used was `npx wp-env start`

## Screenshots
**BEFORE**
_in InspectorControl usage_
<img width="298" alt="Screen Shot 2020-04-29 at 4 32 41 PM" src="https://user-images.githubusercontent.com/4081020/80843123-77a5c600-8bd1-11ea-873c-9bd43e8805d3.png">

_in storybook_
<img width="305" alt="Screen Shot 2020-05-01 at 5 22 53 PM" src="https://user-images.githubusercontent.com/4081020/80842775-7fb13600-8bd0-11ea-9f6c-1fcea936d1d9.png">

**AFTER**
_in storybook_
<img width="304" alt="Screen Shot 2020-05-01 at 5 18 59 PM" src="https://user-images.githubusercontent.com/4081020/80842797-8b046180-8bd0-11ea-8675-186eb53fa96f.png">

**Editor Use Of DateTime Unchanged**
<img width="382" alt="Screen Shot 2020-05-01 at 5 22 35 PM" src="https://user-images.githubusercontent.com/4081020/80842783-863fad80-8bd0-11ea-9c67-871374b3df1a.png">

## Types of changes
Bug fix (styling change)
New feature (introduce Storybook stories)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-05-07 01:00 UTC, earnjam requested changes
Thanks for the PR @jgcaruso. The storybook addition is helpful for identifying the issue and showing that it's resolved by the PR. 

I just have one small suggestion to tighten up the CSS a bit and then I think this is in good shape.

2020-05-07 18:20 UTC, jgcaruso commented on packages/components/src/date-time/style.scss
> +.components-datetime__time {
👍

2020-06-24 18:34 UTC, jgcaruso commented on packages/components/src/date-time/style.scss
> +.components-datetime__time {
Hey @earnjam just wondering if theres anything else I need to do to this PR, or if I should have marked this comment as `resolved` ? I've made the requested code change and I think its good to go.

Unless its just in the queue for merging and just hasn't happened yet?

2023-06-10 02:11 UTC, t-hamano commented
Hi @jgcaruso,

I am very sorry for the delay in contacting you. I came across this PR when I was checking out PRs.

It seems that since this PR was submitted, there have been various design changes and fixes in the DateTime-related components. Currently, [DateTimePicker](https://wordpress.github.io/gutenberg/?path=/story/components-datetimepicker--default), [TimePicker](https://wordpress.github.io/gutenberg/?path=/story/components-timepicker--default), and [DatePicker](https://wordpress.github.io/gutenberg/?path=/story/components-datepicker--default) all Storybooks exist.

Also, this problem does not appear to be a problem with the latest trunk.

![date-time-picker](https://github.com/WordPress/gutenberg/assets/54422211/84383c11-0bef-4aff-b4df-2ca052b192b2)

It is with great regret that we are closing this PR. If there is anything I have missed, please feel free to comment at any time.

2023-06-10 02:11 UTC, closed without merging

2023-06-11 02:33 UTC, jgcaruso commented
> Hi @jgcaruso,
> 
> 
> 
> I am very sorry for the delay in contacting you. I came across this PR when I was checking out PRs.
> 
> 
> 
> It seems that since this PR was submitted, there have been various design changes and fixes in the DateTime-related components. Currently, [DateTimePicker](https://wordpress.github.io/gutenberg/?path=/story/components-datetimepicker--default), [TimePicker](https://wordpress.github.io/gutenberg/?path=/story/components-timepicker--default), and [DatePicker](https://wordpress.github.io/gutenberg/?path=/story/components-datepicker--default) all Storybooks exist.
> 
> 
> 
> Also, this problem does not appear to be a problem with the latest trunk.
> 
> 
> 
> ![date-time-picker](https://github.com/WordPress/gutenberg/assets/54422211/84383c11-0bef-4aff-b4df-2ca052b192b2)
> 
> 
> 
> It is with great regret that we are closing this PR. If there is anything I have missed, please feel free to comment at any time.
> 
> 

Hey there,

No problem at all. I think a while back I noticed the code had significant changes and the issue was no longer present. 

I honestly thought I had abandoned this PR but I guess it's been open this whole time.