Fix insert tab scrolling
WordPress/gutenberg pull request #2212
Opened 2017-08-04 06:29 UTC by tg-ephox

fixes: https://github.com/WordPress/gutenberg/issues/1926

2017-08-04 07:43 UTC, youknowriad commented on editor/inserter/menu.js
> +				<div ref={ ( r ) => this._tabContainer = r } role="menu" className="editor-inserter__content">
Do you think we can remove the `_`, we're not using this convention for the private properties?
Can we avoid small variables like `r` maybe `ref` ?

2017-08-04 07:44 UTC, youknowriad reviewed
Thanks for fixing this, it works great.
Do you think we could extract this to a `HoC` or an utility to apply it elsewhere if needed?

2017-08-04 15:47 UTC, aduth reviewed
An improvement on the current situation, but still not entirely convinced we need per-tab-scroll-memory https://github.com/WordPress/gutenberg/issues/1926#issuecomment-316177784

2017-08-04 15:47 UTC, aduth commented on editor/inserter/menu.js
> +				<div ref={ ( r ) => this._tabContainer = r } role="menu" className="editor-inserter__content">
Would also be good to break up into multiple lines.

2017-08-04 15:47 UTC, aduth commented on editor/inserter/menu.js
> +		this.didSwitchTab = true;
I don't think we need this variable. Instead, `componentDidUpdate` receives the previous state as an argument, so we can check whether tab changed:

```js
componentDidUpdate( prevProps, prevState ) {
	// ...

	const didSwitchTab = this.state.tab !== prevState.tab;
	if ( didSwitchTab ) {
		// ...
```

2017-08-04 15:49 UTC, aduth commented
>Do you think we could extract this to a HoC or an utility to apply it elsewhere if needed?

Not entirely sure this is warranted. Not sure the general use case has presented itself.

2017-08-07 00:18 UTC, tg-ephox commented on editor/inserter/menu.js
> +		this.didSwitchTab = true;
You're right, that's a lot cleaner!

2017-08-07 01:54 UTC, tg-ephox commented
@aduth I was thinking of this from the perspective of browser tabs, where the scroll position is obviously maintained when tabs are switched. However I'm happy to change this to reset `scrollTop` when tabs are switched if this is preferred.  I also made the other changes you noted in the review.

2017-08-07 18:47 UTC, aduth requested changes
This works really well. Aside from one unused variable, this looks good to merge.

2017-08-07 18:47 UTC, aduth commented on editor/inserter/menu.js
> +		this.didSwitchTab = false;
This is unused now and should be removed.

2017-08-08 12:19 UTC, aduth approved these changes

2017-08-08 12:19 UTC, merged