Fix typo
WordPress/gutenberg pull request #22254
Opened 2020-05-10 19:22 UTC by carloslfu

## Description
Fix typo

2020-05-11 09:14 UTC, Soean approved these changes
Good catch, thanks for your contribution.

2020-05-13 23:12 UTC, earnjam requested changes
Thanks @carloslfu! I had one small suggestion in that sentence we should fix at the same time as this.

2020-05-13 23:12 UTC, earnjam commented on packages/keyboard-shortcuts/README.md
> +Keyboard shortcuts is a generic package that allow registering and modifying shortcuts.
While we're fixing that, there is a small subject-verb agreement error here too we should fix. 
```suggestion
Keyboard shortcuts is a generic package that allows registering and modifying shortcuts.
```

2020-05-14 08:31 UTC, earnjam approved these changes
Thanks!

2020-05-14 08:34 UTC, merged