Fix am / pm i18n's bug
WordPress/gutenberg pull request #22963
Opened 2020-06-06 07:37 UTC by miminari

## Description
See #22924 
I changed the string 'AM' and 'PM'to  `__()` for i18n.

## How has this been tested?
1. Make the setting of time to `g:i A`, and the language to Japanese.
2. Create a new post.
3. Document > Publish
4. You can change AM='午前', PM='午後' and that's current color.

## Screenshots
![Kapture 2020-06-06 at 16 12 23](https://user-images.githubusercontent.com/487207/83938865-3aa5a280-a813-11ea-8435-1d763a847945.gif)

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.

2020-06-06 08:43 UTC, torounit commented
@miminari 

It's helpful.

https://github.com/moment/moment/blob/a0f3c74374b638b769d9ab1ae54ba5266ef0976f/moment.js#L1996-L2002

2020-06-06 10:58 UTC, miminari commented
Thanks, @torounit .
I changed the way to the 'am' state value to just string 'AM' or 'PM'.

2020-06-07 18:59 UTC, torounit requested changes

2020-06-07 18:59 UTC, torounit commented on packages/components/src/date-time/time.js
> +		const am = selected.format( 'A' ) === __( 'AM' ) ? 'AM' : 'PM';
I think it's better to compare it to the numbers.
If the translation in moment.js is different from the translation in WordPress, a problem occurs.

2020-06-07 18:59 UTC, torounit commented on packages/components/src/date-time/time.js
> +		const am = selected.format( 'A' ) === __( 'AM' ) ? 'AM' : 'PM';
It is better to compare it with `selected.format("H")` .

2020-06-09 14:29 UTC, torounit commented
@miminari 
Looks good!

2020-06-09 14:29 UTC, torounit approved these changes

2020-06-09 14:50 UTC, miminari commented
@torounit Thank you for your review!

2020-06-20 08:47 UTC, merged