Block Editor: Add missing @param docs
WordPress/gutenberg pull request #22981
Opened 2020-06-07 14:14 UTC by mkaz

## Description

Updates three components in block-editor fixing missing @param docs

See: #22907

## How has this been tested?

Test running:

`npm run lint-js packages/block-editor/src/components/color-style-selector/index.js packages/block-editor/src/components/inserter/index.native.js packages/block-editor/src/components/writing-flow/index.js`

Previous warnings:

## Types of changes

JSDoc changes.

2020-06-07 15:05 UTC, ocean90 requested changes

2020-06-07 15:05 UTC, ocean90 commented on packages/block-editor/README.md
> +-   _props.children_ `WPElement`: Children to be rendered
```suggestion
-   _props.children_ `WPElement`: Children to be rendered.
```

2020-06-07 15:05 UTC, ocean90 commented on packages/block-editor/src/components/color-style-selector/index.js
> + * @param {Object} props.BackgroundColor Background color componnet that wraps icon.
```suggestion
 * @param {Object} props.BackgroundColor Background color component that wraps icon.
```

2020-06-07 15:05 UTC, ocean90 commented on packages/block-editor/src/components/writing-flow/index.js
> + * @param {WPElement} props.children Children to be rendered
```suggestion
 * @param {WPElement} props.children Children to be rendered.
```

2020-06-07 18:31 UTC, ocean90 approved these changes

2020-06-07 19:20 UTC, merged

2020-06-08 08:36 UTC, youknowriad commented
(For the record, I'm changing all the type labels to make sure these PRs should in the same "Documentation" section when the changelog in generated)