fix #19940. Added common steps of plugin translation
WordPress/gutenberg pull request #23535
Opened 2020-06-27 13:54 UTC by atachibana

## Description

This PR will fix issue #19940 of @mkaz. 
For new translators, added general description about WordPress Translation and link to Polyglots handbook.

## How has this been tested?

Spell and grammar were checked on https://www.online-spellcheck.com/result/ba540f6ce8ca06822999f9a1de3c99a599bbe87b
Two links are reachable.

## Screenshots 
n/a

## Types of changes

Added the 1st paragraph.

## Checklist:
- [n/a] My code is tested.
- [n/a] My code follows the WordPress code style. 
- [n/a] My code follows the accessibility standards. 
- [n/a] My code has proper inline documentation. 
- [n/a] I've included developer documentation if appropriate. 
- [n/a] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-06-30 14:04 UTC, mkaz approved these changes
Thanks for updating and the link to more information.

2020-09-14 06:23 UTC, aristath requested changes

2020-09-14 06:23 UTC, aristath commented on docs/contributors/localizing.md
> +
Just some grammar fixes before we can merge this:
```suggestion
As general WordPress Plugins, Gutenberg Plugin is translated via a translation management system at https://translate.wordpress.org. If you are not familiar with this system and translation process, refer to [this document](https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/) first.
```

2021-05-10 06:54 UTC, aristath commented on docs/contributors/localizing.md
> +As general WordPress Plugins, Gutenberg Plugin is translated via translation management system at https://translate.wordpress.org. If you are not familiar with this system and translation process, re
I'm not a native English speaker, but I've got the impression there are some articles & prepositions missing here. A native English speaker should review this before we merge it...

2021-05-11 13:05 UTC, mkaz commented on docs/contributors/localizing.md
> +As general WordPress Plugins, Gutenberg Plugin is translated via translation management system at https://translate.wordpress.org. If you are not familiar with this system and translation process, re
```suggestion
The Gutenberg plugin is translated via the general plugin translation system (GlotPress) at https://translate.wordpress.org. Review the [GlotPress translation process documentation] (https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/) for additional information.
```

2021-07-27 12:31 UTC, aristath approved these changes

2021-07-27 12:32 UTC, aristath commented
The failing test is not related to this PR, I'll go ahead and merge it.

2021-07-27 12:32 UTC, merged

2021-07-28 04:14 UTC, talldan commented
@mkaz @aristath Please could you make sure PRs have appropriate titles and labels when reviewing or merging. Thanks.