Add check for button text before rendering Button block
WordPress/gutenberg pull request #24064
Opened 2020-07-20 16:32 UTC by richtabor

## Description
This PR adds a check for the `text` attribute before rendering the Button block on the front-end. This prevents an empty `<div class="wp-block-button"><a class="wp-block-button__link"></a></div>` from displaying on the front-end. 

Closes #17221

## How has this been tested?
Tested with WP 5.5 RC
Tested to see if we need a deprecation (_not needed_)

## Screenshots 
### Before:
Editor:
<img width="884" alt="Screen Shot 2020-07-20 at 12 18 40 PM" src="https://user-images.githubusercontent.com/1813435/87961564-de75a580-ca83-11ea-9ed7-7d0779e4424b.png">
Front-end:
<img width="956" alt="Screen Shot 2020-07-20 at 12 25 29 PM" src="https://user-images.githubusercontent.com/1813435/87961711-1f6dba00-ca84-11ea-949c-daac990b6b43.png">

### After:
<img width="884" alt="Screen Shot 2020-07-20 at 12 18 40 PM" src="https://user-images.githubusercontent.com/1813435/87961564-de75a580-ca83-11ea-9ed7-7d0779e4424b.png">
<img width="908" alt="Screen Shot 2020-07-20 at 12 18 47 PM" src="https://user-images.githubusercontent.com/1813435/87961604-f4836600-ca83-11ea-8d13-24aeee2bf9ac.png">

## Types of changes

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-07-20 18:47 UTC, ZebulanStanphill commented on packages/block-library/src/button/save.js
> +			{ text && (
This could be simplified to just `return text && (...`. No need for a Fragment and `{`.

2020-07-20 18:49 UTC, ZebulanStanphill commented on packages/block-library/src/button/save.js
> +			{ text && (
Actually, I just had a better idea. Use an early return instead, for example:

```js
if ( ! text ) {
	return null;
}
```

2020-07-20 18:51 UTC, ZebulanStanphill commented on packages/block-library/src/button/save.js
> +			{ text && (
I just realized that the Fragment being the root element may actually be the cause of the test failures. The `wp-block-button` and `aligncenter` classes are not being applied to the `div` anymore.

2020-07-20 19:34 UTC, youknowriad commented
This is probably going to require a deprecated version.

2020-07-20 20:00 UTC, ZebulanStanphill commented
Why? As far as I can tell, this would have no effect on existing blocks until opening them in the editor, at which point they would update to the new markup upon save. The changes here (after applying my suggestions), should have no effect on what markup is considered a valid Button block.

2020-07-20 20:02 UTC, richtabor commented
> This is probably going to require a deprecated version.

I tested for this as well but didn't see it needed one.

2020-07-20 20:20 UTC, youknowriad commented
When you open an existing post on the editor, it performs validation to ensure markup was not updated externally. If it finds a different in the ouput compared to the saved markup, an invalidation issue is triggered. Almost any change to "save" functions of blocks requires a deprecated version. The thing that don't require are additions (with default values that don't impact markup).

I can't test now, but I'll circle back later to confirm.

2020-07-20 20:23 UTC, richtabor commented
> When you open an existing post on the editor, it performs validation to ensure markup was not updated externally. If it finds a different in the ouput compared to the saved markup, an invalidation issue is triggered. Almost any change to "save" functions of blocks requires a deprecated version. The thing that don't require are additions (with default values that don't impact markup).
> 
> I can't test now, but I'll circle back later to confirm.

Yup, understood! I tested just for this - though maybe I missed something?

2020-07-20 20:23 UTC, ZebulanStanphill requested changes
[Switching to an early return (and dropping the Fragment use)](https://github.com/WordPress/gutenberg/pull/24064/files#r457620411) should fix the unit test failures (which are valid).

2020-07-21 08:50 UTC, youknowriad commented
Here's a markup that you can build with master that will produce invalidation

```
<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div><a class="wp-block-button__link">test</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"text":"#2c7ea1","background":"#6da2b9"}}} /--></div>
<!-- /wp:buttons -->
```

You were not experiencing the issue because if you don't apply custom colors, an existing deprecation (with isElligible) was picked up and it was upgrading the markup to the last version.

2021-03-10 13:11 UTC, getsource commented
I added a deprecation and continued this in #29717.

2021-03-11 00:37 UTC, ZebulanStanphill commented
Closing since #29717 was merged. Thanks for the initial work!

2021-03-11 00:37 UTC, closed without merging