Don't re-encode already encoded post titles
WordPress/gutenberg pull request #2407
Opened 2017-08-14 15:32 UTC by notnownikki

Data that comes from the Posts collection is already encoded, ready to output safely, so we set the inner html to avoid encoding twice.

Fixes https://github.com/WordPress/gutenberg/issues/2389

2017-08-14 16:13 UTC, aduth requested changes
It would be best for us to avoid `dangerouslySetInnerHTML` if at all possible if alternatives exist (hence its name).

In this case, there are other options available for unescaping entities:

- https://lodash.com/docs/4.17.4#unescape (only handles a few entities)
- https://www.npmjs.com/package/he (a very large module, probably too large)
- https://github.com/Automattic/wp-calypso/blob/master/client/lib/formatting/decode-entities/browser.js (can be an expensive operation, might ought to be memoized or [shortcut](https://github.com/Automattic/wp-calypso/blob/f645493/client/lib/formatting/index.js#L14))

2017-08-14 16:35 UTC, notnownikki commented
@aduth `lodash` doesn't unescape everything we need, and I agree that `he` is too big... I'll try creating a textarea to use for decoding, and reuse the element so we're not doing element creation for every post.

2017-08-15 17:53 UTC, notnownikki commented on blocks/library/latest-posts/index.js
> +		decodeEntities( html ) {
Yeah... ok, happy to generalize this :)

2017-08-17 09:16 UTC, notnownikki commented
Added an 'entities' module that has 'decodeEntities'.

2017-08-18 19:01 UTC, aduth approved these changes
Looks good 👍 

You may consider reaching out on https://github.com/WordPress/packages/pull/12 to see if we can reconcile requirements here, since I think the new utility falls well under what's being proposed there.

2017-08-21 09:36 UTC, merged