Polish editor PostFormat component.
WordPress/gutenberg pull request #24079
Opened 2020-07-20 21:26 UTC by ZebulanStanphill

## Description
WIP.

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-10-16 05:12 UTC, talldan requested changes
I've reviewed half of this, but as a reviewer I've found this refactor has too many logic changes and parts that won't work the same as before.

A good rule of thumb for a refactor is that it should unit test the same as it did previously (if it had tests).

How about an intermediate PR where we refactor the existing component to hooks without changing logic?

2020-10-16 05:12 UTC, talldan commented on packages/editor/src/components/post-format/index.js
> +				{ suggestedFormat && (
Similar to the previous comment, the code changes `suggestedFormat` to be validated against `supportedFormats` which logically causes an issue when that values doesn't exist in `POST_FORMAT_TITLES`.

Previously the value was sourced from `POST_FORMATS`.

2020-10-17 04:44 UTC, ZebulanStanphill commented
@talldan
> How about an intermediate PR where we refactor the existing component to hooks without changing logic?

Good idea. I'll start splitting out smaller PRs from this one, starting with #26238.

2020-10-19 07:55 UTC, talldan commented
Thanks for doing that. Merged that one just now. What's the next step?

2020-10-20 00:15 UTC, ZebulanStanphill commented on packages/editor/src/components/post-format/index.js
> +export const POST_FORMAT_TITLES = {
Thanks for pointing this out. I'm going to switch back to the array.

Your comment also made me realize that the post formats, even as an array, aren't sorted at all, so I created #26305 to fix that.

2020-10-20 15:02 UTC, ZebulanStanphill commented
@talldan Alright, now that #26305 is merged, I've rebased this PR, and it should be ready for review again. It now contains only code style and optimization tweaks, and should be much easier to review than before.

2022-07-28 00:46 UTC, ZebulanStanphill commented
Ultimately, this PR is basically just nitpicking, and most of the more useful changes have made it into `trunk` via other PRs, so I'm closing this one, since I lack the spare time to spend on it.

2022-07-28 00:46 UTC, closed without merging