Post Excerpt block: Added icon and description to Post Excerpt block
WordPress/gutenberg pull request #24203
Opened 2020-07-24 21:15 UTC by mapk

## Description
Added icon and description to Post Excerpt block.

## How has this been tested?
Tested locally.

## Screenshots 

![Screen Shot 2020-07-24 at 2 14 39 PM](https://user-images.githubusercontent.com/617986/88435912-0cc2f000-cdb8-11ea-8181-9e138ca6f735.png)

## Types of changes
Non-breaking changes.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-07-24 21:29 UTC, mapk commented
I updated the excerpt description to read, "Display a post's excerpt."

2020-07-27 17:37 UTC, MichaelArestad requested changes
This looks good. I think the description is short and sweet. I do have some minor things for you to look into on the icon and then it's good to go. Nice work!

2020-07-27 17:37 UTC, MichaelArestad commented on packages/icons/src/library/post-excerpt.js
> +			fill="#1E1E1E"
I would remove this fill.

2020-07-27 17:37 UTC, MichaelArestad commented on packages/icons/src/library/post-excerpt.js
> +	<SVG fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
Remove this fill as well.  (The fills are defined in the CSS so no need here)

2020-07-27 17:37 UTC, MichaelArestad commented on packages/icons/src/library/post-excerpt.js
> +			clip-rule="evenodd"
I'm not sure about these clip and fill rules. I don't really know if they are needed.

2020-07-27 18:40 UTC, MichaelArestad approved these changes

2020-07-27 18:50 UTC, merged