List View: Design updates
WordPress/gutenberg pull request #24419
Opened 2020-08-06 15:42 UTC by shaunandrews

WIP

<img width="505" alt="image" src="https://user-images.githubusercontent.com/191598/89552028-9d96c400-d7d9-11ea-945a-8cc2068427c9.png">

Still a lot to do, but this PR starts by
- reducing the row height down (48px to 36px), and overall spacing.
- adding the more (...) menu everywhere.
- removing the descender lines.
- arranging movers side-by-side.
- adding a hover affect.

There's still a lot of work to be done. Here's how the changes look in the experimental Navigation screen, which shows the movers:

<img width="293" alt="image" src="https://user-images.githubusercontent.com/191598/89552271-ef3f4e80-d7d9-11ea-844d-597fd2a14841.png">

2020-08-07 07:38 UTC, draganescu commented
Why is it a draft? It contains more than enough changes for an iteration 💯

2020-08-12 21:58 UTC, shaunandrews commented
<img width="573" alt="image" src="https://user-images.githubusercontent.com/191598/90072269-21165080-dcc5-11ea-965e-2ecc8731accd.png">

I pushed some changes:
- Made the popover wider
- Forced nested blocks to always show
- Forced the movers to show
- Switched away from `table` elements to basic `div`'s to have better control over focus and general styling
- Added an alternative for the nested descender indicator, this time its a more subtle series of dots

> Why is it a draft? It contains more than enough changes for an iteration

I'm sure it does. For now, this is kind of a sandbox to see how things feel in practice. It might be mergeable, or maybe we end up splitting it up.

2020-08-13 14:37 UTC, SchneiderSam commented
Sooo cool. Big Game Changer....

I was about to test it with http://gutenberg.run/24419, but unfortunately it does not work. I'm getting an error. I've tried it several times... @aduth

2020-08-13 21:03 UTC, enriquesanchez commented
This looks great and works as expected. I didn't notice any loss in functionality due to the use of `divs`. 

One thing I came across is we'd probably want to truncate or do something about long strings of text:

<img width="387" alt="Screen Shot 2020-08-13 at 16 00 11" src="https://user-images.githubusercontent.com/3276087/90186870-81b59400-dd7e-11ea-8b74-30a1517fcf63.png">

2020-08-14 07:49 UTC, tellthemachines requested changes
This is working pretty well! Just a few comments below.

Also, if we're showing the "More options" menu (I'm not fully convinced we should 😅 ), we'll probably need to hide some of the options. E.g. trying to use "Move to" is awkward from the modal and impossible from the top toolbar navigator.
<img width="580" alt="Screen Shot 2020-08-14 at 5 18 47 pm" src="https://user-images.githubusercontent.com/8096000/90226194-ff989e80-de55-11ea-91c9-928f5a278a03.png">

Finally:

* Lint checks are failing: run `npm run lint-js` once you've finished making changes and fix the resulting errors.
* Treegrid snapshots need updating: run `npm run test-unit -- -u` to update them.

2020-08-14 07:49 UTC, tellthemachines commented on packages/block-editor/src/components/block-navigation/style.scss
>  	display: none;
We can't use `display: none` if the content is meant to be screen reader accessible. 
Current best practice in this repo is to wrap the screen-reader-only component in [VisuallyHidden](https://github.com/WordPress/gutenberg/blob/abbdb2bfae951bed85c568ece12620bacd1e483f/packages/components/src/visually-hidden/README.md#L1). This ensures it'll have the appropriate styling.

2020-08-14 07:49 UTC, tellthemachines commented on packages/components/src/tree-grid/index.js
>  			{ /* Disable reason: A treegrid is implemented using a table element. */ }
Need to update the disable reason here.

2020-08-14 15:12 UTC, paaljoachim commented
Here is the PR for **WIP: Add drag and drop to List View**
https://github.com/WordPress/gutenberg/pull/23952

2020-09-04 09:02 UTC, paaljoachim commented
Can we get an update to how things are going here?
Thanks!

2020-09-09 05:35 UTC, paaljoachim commented
I was finally able to test this out by not using gutenberg.run.

I followed this doc: https://developer.wordpress.org/block-editor/tutorials/devenv/
(Which we added to the core editor yesterday.)

and I am following steps in how to test run a PR. I will later today add an issue and then create a PR for it.

Here is an animated gif. Showing the Navigation screen structure.
![Nav-structure](https://user-images.githubusercontent.com/5323259/92558333-95192980-f26e-11ea-8228-efe25b952077.png)

What is interesting is the clarity in when an element is selected. But the black background color creates a too strong contrast. The black could perhaps be a greyish color instead. As it might just need a much more subtitle background color. I am not sure about the dots. Having the old tree diagram lines seemed easier to follow.
All in all I am not sure about the direction seen in this PR in relation to what I experienced in the Nav screen structure.

2020-09-22 18:28 UTC, noahtallen commented
@shaunandrews is there anything specific we can do to help move this forward?

2020-09-24 19:21 UTC, shaunandrews commented
> is there anything specific we can do to help move this forward?

I likely tried doing _too much_ in this PR. I think we could probably break some of this up into smaller branches, like:

- reducing the row height down (48px to 36px), and overall spacing.
- removing (and potentially replacing) the descender lines.
- arranging movers side-by-side.
- adding a hover affect.

2021-01-06 22:20 UTC, shaunandrews commented
Cherry-picked a few things from this bigger PR into a smaller one over in #28029

2021-02-12 13:25 UTC, draganescu commented
@shaunandrews as the new screen has no list view anymore, is this design update maybe outside of the Navigation editor scope?

2021-02-25 22:33 UTC, shaunandrews commented
I think we'll bring the list view back to the navigation editor, so it still makes sense to improve it as part of that effort.

2021-04-21 08:07 UTC, getdave commented
@draganescu @shaunandrews Should we remove this from `PRs pending review`?

2021-04-22 18:08 UTC, closed without merging