Remove Embeds for Facebook and Instagram
WordPress/gutenberg pull request #24472
Opened 2020-08-10 17:13 UTC by mkaz

## Description

This PR removes the Facebook & Instagram blocks from the inserter. Per Facebook, the [embed APIs are going to require an authentication token](https://developers.facebook.com/docs/plugins/oembed-legacy) so will remove from Gutenberg embeds.

As we've done with other disabled embeds (for example College Humor), the embeds are still included but marked as `{ inserter: false }`

Fixes #24389 

Deadline: October 24, 2020

Core will remove API in WP 5.6

Related: https://core.trac.wordpress.org/ticket/50861

## Types of changes

Move Facebook and Instagram embeds to `others` section in embeds and add `support: { inserter: false }`

We will probably want to update support documentation.

2020-08-10 17:46 UTC, ajitbohra commented
@mkaz merge conflict

2020-08-10 19:01 UTC, mkaz commented
Thanks @ajitbohra - I forgot to update prior,  fixed the code to work properly now with variations.

2020-08-10 23:37 UTC, ajitbohra requested changes

2020-08-10 23:37 UTC, ajitbohra commented on packages/block-library/src/embed/variations.js
> +		// See: https://developers.facebook.com/docs/plugins/oembed-legacy
```suggestion
		// See: https://developers.facebook.com/docs/instagram/oembed-legacy
```

2020-08-11 13:25 UTC, ntsekouras reviewed
Looks good, thanks! -  I'm wondering though how and when this will be communicated with users who already had embed content from Facebook and Instagram. When embed support stops will result in fallback with just a link and there might be a confusion for that.

2020-08-11 13:51 UTC, mkaz commented
@ntsekouras Good questions. First the experience, for existing embeds the API will return either invalid or potential a notice embed that the service has changed, this is up to Facebook/Instagram to return a proper embed response. If the API returns an invalid response, then a simple link will be shown instead of the embed.

As far as communication, [Facebook announced in this post](https://developers.facebook.com/blog/post/2020/08/04/Introducing-graph-v8-marketing-api-v8) and updated their API docs, both of which I know few people will see. 

WordPress will include in release notes, but likewise few users read the release notes. The vast majority of users will first "hear about it" when they notice their embeds are broken. We will also create a WordPress support document to explain, so when people notice the issue they can get the answer.

2020-08-11 14:02 UTC, ntsekouras commented
> We will also create a WordPress support document to explain, so when people notice the issue they can get the answer.

This sounds like a good plan - being proactive!

2020-08-11 14:03 UTC, ntsekouras approved these changes
Thanks @mkaz! 👍

2020-08-12 07:57 UTC, ajitbohra approved these changes

2020-08-12 15:51 UTC, Ayesh commented
I published [oEmbed Plus](https://wordpress.org/plugins/oembed-plus/) today, that takes care of the PHP side of the replacement APIs. I'll look to implement the JS side of it, to see if I can make this plugin provide a seamless transition. Any input is welcome.

2020-09-01 13:06 UTC, aristath approved these changes

2020-09-02 07:08 UTC, merged