Search Block: Add support for setting the border radius
WordPress/gutenberg pull request #25203
Opened 2020-09-09 22:55 UTC by apeatling

Part of: #22071

## Description
Add support for setting the border radius on the search input field and search button in the search block. This is a single setting that will adjust the radius for both together.

![2020-09-09 15 50 41](https://user-images.githubusercontent.com/1464705/92662726-4d1cf580-f2b4-11ea-9291-9f6d0a5b19b7.gif)

## How has this been tested?
Tested locally, all unit tests passing.

## Testing Instructions

* Add a search block.
* Adjust the border radius setting and confirm the input field and button adjust accordingly.
* Confirm the border radius remains in place when changing button position settings.
* Confirm that the border radius renders correctly on the front end of the site.

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-09-09 23:09 UTC, shaunandrews commented
Nice. When the button is inside, could we adjust its border-radius so it's move visually balanced?

When they have the same border-radii, you get this weirdness:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/191598/92663659-dbeb3b80-f2cf-11ea-8235-7d3b2c17bd58.png">

But, if we do some math and adjust the button radius, we can get a much nicer visual:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/191598/92663679-ec9bb180-f2cf-11ea-8479-82bfca0634ec.png">

2020-09-21 20:40 UTC, apeatling commented
✅ Rebased

2020-09-23 06:37 UTC, aaronrobertshaw requested changes
This tests well for me. 

There were just a couple of minor issues though. The PHPCS linting threw up a number of errors and warnings that need to be addressed. There was also a rogue `"` that can be deleted.

I took a stab at adjusting the border radii for the input and button when the button is positioned "inside". There is a PR here: https://github.com/WordPress/gutenberg/pull/25553

Feel free to ignore it if there is a better approach. The one I took only uses a very simple formula, `innerRadius = outerRadius - padding`. It doesn't take into account possible varying border widths, paddings etc that could be overridden by the theme or global styles. Long story short, it's not a perfect solution but might be a start to build from.

2020-09-23 06:37 UTC, aaronrobertshaw commented on packages/block-library/src/search/index.php
> +			$field_styles .= ' width: ' . esc_attr( $attributes['width'] ) . esc_attr( $attributes['widthUnit'] ) . ';"';
We have an extraneous `"` character in this markup.
```suggestion
			$field_styles .= ' width: ' . esc_attr( $attributes['width'] ) . esc_attr( $attributes['widthUnit'] ) . ';';
```

2020-09-23 20:59 UTC, apeatling commented
Looks good @aaronrobertshaw, let's close this in favor of https://github.com/WordPress/gutenberg/pull/25553

2020-09-23 20:59 UTC, closed without merging