change navigation block description
WordPress/gutenberg pull request #25531
Opened 2020-09-22 10:19 UTC by devfle

## Description

Fixes #25013 - In this PR I changed the description of the navigation block.

## How has this been tested?

I have uploaded the changes on my local Wordpress installation and checked the changes. Everything worked fine.

## Screenshots 
Before:
<img width="279" alt="before" src="https://user-images.githubusercontent.com/52854338/93870516-9f571100-fccd-11ea-899f-a56c11cf813c.png">

After:
<img width="279" alt="after" src="https://user-images.githubusercontent.com/52854338/93870544-a716b580-fccd-11ea-84e4-364ee7cf88cc.png">

## Types of changes
New feature (non-breaking change which adds functionality) 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-09-22 10:55 UTC, aristath requested changes
Looks good, the only thing that needs fixed in coding standards :+1:

2020-09-22 10:55 UTC, aristath commented on packages/block-library/src/navigation/index.js
> +					label: __('Contact'),
Spaces should not be removed as per the WordPress Coding Standards
```suggestion
					label: __( 'Contact' ),
```

2020-09-22 10:55 UTC, aristath commented on packages/block-library/src/navigation/index.js
> +					label: __('About'),
```suggestion
					label: __( 'About' ),
```

2020-09-22 10:55 UTC, aristath commented on packages/block-library/src/navigation/index.js
> +					label: __('Home'),
```suggestion
					label: __( 'Home' ),
```

2020-09-22 10:55 UTC, aristath commented on packages/block-library/src/navigation/index.js
> +			description: __('Links shown in a column.'),
```suggestion
			title: __( 'Navigation (vertical)' ),
			description: __( 'Links shown in a column.' ),
```

2020-09-22 10:55 UTC, aristath commented on packages/block-library/src/navigation/index.js
> +			description: __('Links shown in a row.'),
```suggestion
			title: __( 'Navigation (horizontal)' ),
			description: __( 'Links shown in a row.' ),
```

2020-09-22 10:55 UTC, aristath commented on packages/block-library/src/navigation/index.js
> +	keywords: [__('menu'), __('navigation'), __('links')],
```suggestion
	keywords: [ __( 'menu' ), __( 'navigation' ), __( 'links' ) ],
```

2020-09-22 10:55 UTC, aristath commented on packages/block-library/src/navigation/index.js
> +	description: __('A collection of blocks that allow visitors to get around your site.'),
```suggestion
	description: __( 'A collection of blocks that allow visitors to get around your site.' ),
```

2020-09-22 10:55 UTC, aristath commented on packages/block-library/src/navigation/index.js
> +	title: __('Navigation'),
```suggestion
	title: __( 'Navigation' ),
```

2020-09-22 13:28 UTC, devfle commented
Hmm..! That comes from my VS-Code Prettier. I will fix this. Thank you!

2020-09-23 09:03 UTC, aristath approved these changes
Thank you for the changes :)
LGTM :+1:

2020-09-23 10:15 UTC, merged