Adds support to `wp-env` for specifying a source file to use as the `docker-compos.override.yml` file
WordPress/gutenberg pull request #26047
Opened 2020-10-13 03:43 UTC by timnolte

## Description

This fixes #25486 by providing an option to specify a custom Docker Compose configuration file path that will be used as the source for a `docker-compose.override.yml` file in the working directory.

## How has this been tested?

Tested by starting up the local WordPress Gutenberg development environment and:
- Validated successful startup when not configured
- Validated services specified in the generated `docker-compose.override.yml` file, from the configured source file, have started up.

## Types of changes

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

2020-11-16 20:34 UTC, noahtallen requested changes
Sorry for letting this sit for so long!

I would think we only need to copy the override file to the working directory for docker-compose to automatically detect it. But since we are passing the override path to each of the docker-compose commands manually, it seems like we could just set that path directly to the file in the project directory. That way we don't have to copy the file over.

If we do need to copy the file over to add functionality, I don't think we should add any extra yaml packages for it. I think we could just use `fs.copyFile` or something like that since we don't need to use the file in code.

2020-11-16 20:34 UTC, noahtallen commented on packages/env/lib/commands/stop.js
> +	const { dockerComposeOverrideConfigPath } = await initConfig( {
this should be moved to the existing call to `initConfig`, I think

2021-02-22 23:38 UTC, moon0326 commented
Hi, ✋ I'm very interested in this PR. This PR will let us customize the docker build. Any chance this gets updated? Looks like this has been sitting here since last October. Thank you!

2021-02-23 00:04 UTC, timnolte commented
The draft PR was opened then but I believe I have some more work done on this, but. It all of it. I had a lot of other work for 2 of my plugins that took me off of working in finalizing that PR. I'll try to pick it up again soon.

2022-01-21 02:46 UTC, closed without merging