Restore underlines on is-tertiary buttons
WordPress/gutenberg pull request #26524
Opened 2020-10-27 22:17 UTC by enriquesanchez

## Description
Closes #23890.

Restores the underline to the tertiary button styles in the editor.

## How has this been tested?
Tested on lastest versions of Firefox, Chrome and Safari in macOs.

## Screenshots 

<img width="1054" alt="Screen Shot 2020-10-27 at 15 56 16" src="https://user-images.githubusercontent.com/3276087/97367973-a72b4780-186f-11eb-9dd8-89530e676c06.png">

---

<img width="1055" alt="Screen Shot 2020-10-27 at 16 09 18" src="https://user-images.githubusercontent.com/3276087/97367988-ab576500-186f-11eb-9f56-566b4f748d6d.png">

---

<img width="1054" alt="Screen Shot 2020-10-27 at 15 56 16" src="https://user-images.githubusercontent.com/3276087/97368003-b01c1900-186f-11eb-8ad9-f13a180e1da1.png">

---

![2020-10-27 16-03-30 2020-10-27 16_05_08](https://user-images.githubusercontent.com/3276087/97368017-b3170980-186f-11eb-82f3-d81670b9d966.gif)

---

## Types of changes
CSS and visual changes.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-10-28 08:35 UTC, jasmussen commented
This is what I see. For whatever reason, the underlines are 1px closer to the text than they are in your screenshots, but I suspect that's a browser thing. 

<img width="1570" alt="Screenshot 2020-10-28 at 09 34 04" src="https://user-images.githubusercontent.com/1204802/97411570-bc9c8200-1900-11eb-99e6-1fcc9a329168.png">

In any case, I'm happy to try this. There will also be an opportunity to retire the "isLink" button.

2020-10-28 17:34 UTC, enriquesanchez commented
>For whatever reason, the underlines are 1px closer to the text than they are in your screenshots, but I suspect that's a browser thing.

@jasmussen It is a browser thing. And not worth trying `text-underline-offset` since [it's not widely supported, including Chrome](https://caniuse.com/mdn-css_properties_text-underline-offset). 😞

2020-10-28 17:37 UTC, jasmussen commented
All good, was just speculating on the discrepancy!

2021-04-19 10:13 UTC, carolinan approved these changes
The PR can no longer be built just because of its age, and needs to be synced with trunk, but the actual change works well.

2021-04-22 09:27 UTC, aristath commented
Rebased the PR, let's wait for the tests to complete :+1:

2021-04-22 09:34 UTC, aristath approved these changes

2021-04-22 09:51 UTC, jasmussen requested changes
Despite initial excitement about the simplicity of this one, I think we might need to pause it and reflect a bit more. It's pretty late in a cycle, and it's changing a widely used component. The primary concern that has been voiced, is that these are no longer differentiated from regular hyperlinks, confusing the interaction:

<img width="415" alt="Screenshot 2021-04-22 at 11 47 39" src="https://user-images.githubusercontent.com/1204802/115694099-d626ff80-a360-11eb-914e-b1e2b2dde133.png">

That does resurface an issue present on the link button style, which is also important to solve. But it might need more time in the oven.

2024-04-25 21:56 UTC, youknowriad commented
Is this PR still relevant? Should we just close it until we find some consensus in the issue?

2024-04-26 06:25 UTC, closed without merging