[RNMobile] Fix a11y issue in Cover block
WordPress/gutenberg pull request #26727
Opened 2020-11-05 12:40 UTC by lukewalczak

## Description

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2021-02-02 14:45 UTC, dratwas approved these changes
Tested it and works as expected, however, I left one small comment :)

2021-02-02 14:45 UTC, dratwas commented on packages/block-library/src/cover/edit.native.js
> +	const handleScreenReaderToggled = ( enabled ) => {
Do we need that function? Can't we simply use the `setIsScreenReaderEnabled` ?

2021-02-03 11:30 UTC, dratwas requested changes

2021-02-03 11:30 UTC, dratwas commented on packages/block-library/src/cover/edit.native.js
> +		mediaUploadSync();
Please remove it, or the other `useEffect` which invoke `mediaUploadSync` here :)
https://github.com/WordPress/gutenberg/pull/26727/files#diff-efe4dc27db844b16612461b3acc8ac6d6ee9c44a490baf9bb58c03e6f88b77d7R181

2021-02-05 13:09 UTC, dratwas approved these changes

2021-02-08 09:07 UTC, merged

2021-02-10 23:14 UTC, dcalhoun reviewed
Hey @lukewalczak. 👋🏻 I discovered this PR from needing to resolve merge conflicts with my work in #25810. I had actually made some changes related to a11y without realizing the issues were already documented in an Issue or that you were working to address some of these.

That said, from reviewing your work and resolving the merge conflicts, I  believe I identified a few issues. Will you please review my comments to make sure that my changes are appropriate and do not introduce regressions?

Thanks!

2021-02-10 23:14 UTC, dcalhoun commented on packages/components/src/mobile/image/image-editing-button.native.js
> +				<TouchableWithoutFeedback
The changes in this PR may not actually have the desired impact for addressing wordpress-mobile/gutenberg-mobile#2699, for a couple of reasons I have discovered.

1. This edit image button was rendered _beneath_ the image itself, which means it was not reachable when using voice over. I have [relocated it to address this](https://github.com/WordPress/gutenberg/pull/25810/commits/b07e0bccdefe9b3f778d7cdfa9477f270f578509).
    <details>
    <summary>Unreachable edit button</summary>
    
    ![unreachable-edit-image button](https://user-images.githubusercontent.com/438664/107584498-2e53bf80-6bc2-11eb-85e4-6ca22b9610f6.PNG)
    
    </details>
2. I believe wordpress-mobile/gutenberg-mobile#2699 was describing the lack of a label for the _add media button_, which is displayed when no cover media has been set. I have [added a label for this button](https://github.com/WordPress/gutenberg/pull/25810/commits/e96e1d40bd7ba01bb99b402ab825b7c06cf4f954).

    <details>
    <summary>Label-less add button</summary>
    
    ![label-less-add-media-button](https://user-images.githubusercontent.com/438664/107584531-3c094500-6bc2-11eb-8ae7-2cb94bdf1454.PNG)
    
    https://user-images.githubusercontent.com/438664/107584541-3e6b9f00-6bc2-11eb-89cd-183bbf6d65ee.MP4
    
    </details>

2021-02-10 23:14 UTC, dcalhoun commented on packages/components/src/mobile/image/image-editing-button.native.js
> +					accessibilityLabell={ __( 'Edit the cover image' ) }
It looks like there was a typo in the prop name here. Additionally, I have [changed the label](https://github.com/WordPress/gutenberg/blob/0aa90e57954b507a076d23f9d6cd8d0d7c45a48b/packages/components/src/mobile/image/image-editing-button.native.js#L38) to be `Edit image`, as this button is also used for the standard image block.