Rnmobile/refactor/gallery to nested image blocks
WordPress/gutenberg pull request #26823
Opened 2020-11-09 12:02 UTC by dratwas

## Description

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-11-10 14:31 UTC, devdreamsolution approved these changes

2020-11-13 11:19 UTC, dratwas commented
@iamthomasbishop 
Answering the comment from base PR https://github.com/WordPress/gutenberg/pull/25940#issuecomment-725027248

Moved that discussion here to have it in the right place since it is related only to the mobile part.

>@dratwas Assuming you are referring to the dashed child borders, why do we need to remove them? Maybe I'm missing context, but I would expect the bordering to look/work the same way as other innerBlocks do (the screenshot you shared in your comment looks correct).

Maybe I should as in a bit different way, sorry for that. My question should be: "Do we want to fit the innerBlocks with image blocks inside to keep the previous gallery look, or do we want to have default innerBlocks look"

Previous Gallery | Default InnerBlocks
--- | ---
![Simulator Screen Shot - iPhone 11 Pro - 2020-11-13 at 12 14 25](https://user-images.githubusercontent.com/16336501/99066880-fed4ed00-25a9-11eb-91d1-119e62de9fae.png) | ![Simulator Screen Shot - iPhone 11 Pro - 2020-11-13 at 12 08 06](https://user-images.githubusercontent.com/16336501/99066894-0399a100-25aa-11eb-8658-0f5ba97da132.png)

I created the test build for you here: https://github.com/wordpress-mobile/WordPress-iOS/pull/15284#issuecomment-726367909

2020-11-14 03:49 UTC, iamthomasbishop commented
> Maybe I should as in a bit different way, sorry for that. My question should be: "Do we want to fit the innerBlocks with image blocks inside to keep the previous gallery look, or do we want to have default innerBlocks look"

@dratwas Ahh okay, makes sense! My preference would be to utilize the standard innerBlocks UI (with the dashed child borders), so the second screenshot on your [last comment](https://github.com/WordPress/gutenberg/pull/26823#issuecomment-726709097) ("default innerBlocks") looks correct. 

Side note: I was trying to test the build linked in wordpress-mobile/WordPress-iOS#15284 and I'm not seeing the innerBlocks style — maybe it's behind a flag?

2020-11-16 16:50 UTC, dratwas commented
Thanks for the review @iamthomasbishop. I created a new build with the latest changes - https://github.com/wordpress-mobile/WordPress-iOS/pull/15284#issuecomment-726367909

Please test it and leave your thoughts here :)

Side note: I feel like after change from the old implementation (Array.map) to the innerBlocks (FlatList) the performance is noticeably worse. I can observe that when changing the count of images in a row when there are more than 5 images in the gallery.

2020-11-17 22:48 UTC, dratwas commented
Hey, @iamthomasbishop I changed the inline cells with `Apply to all images` and `Cancel` to the ActionSheet. Could you please take a look at the newest build? :) https://github.com/wordpress-mobile/WordPress-iOS/pull/15284#issuecomment-726367909

2020-11-18 04:45 UTC, iamthomasbishop commented
@dratwas That definitely feels better! Which component are we using for this on Android? I'm guessing BottomSheet?

One request: can we change the title/header label ("Gallery block options") to a more specific message/alert text like "Apply to all images in this gallery?". Here's an example (please forgive the quick dirty mock-up that I made on my phone 😅):

![image](https://user-images.githubusercontent.com/1200432/99484025-22d75c00-2925-11eb-9071-1474eabb02ae.jpeg)

One thing that seems like a bug: I'm also seeing an odd looping issue with when I first tap on the block settings icon (but if I kill the app and resume, the issue goes away). Here's a video: https://cloudup.com/cHML3GFceui . Note: it's hard to tell but after I opened the settings sheet, the alert/actionSheet popped up and continued reopening immediately upon closing it.

2020-11-19 12:18 UTC, dratwas commented
Hey, @iamthomasbishop I created new builds for iOS and Android :) Could you take a look?

I fixed the loop and changed the title of the picker.

https://github.com/wordpress-mobile/WordPress-Android/pull/13423#issuecomment-730258624
https://github.com/wordpress-mobile/WordPress-iOS/pull/15284#issuecomment-726367909

2020-11-19 17:23 UTC, iamthomasbishop commented
@dratwas Much much better, thank you! I have one question and it's a minor thing, not a big blocker. I'm curious if we can "pause" changes to the bottomSheet (setting label and sheet height) until _after_ the selection is made on the actionSheet? 

For example, let's say I have the `Link to` setting set to `None`. If I tap on the `Link to` cell and select another option (like `Attachment Page`) from the initial actionSheet, the new option is applied immediately (visible on the sheet) and the height of the sheet changes — _before_ the confirmation step. 

If possible, I'd like to "pause" applying the change until the user has tapped "Apply to all images" on the confirmation sheet. Alternatively, if they tap "Cancel", there should be no visible change.

2020-11-23 15:26 UTC, dratwas commented
Hey @iamthomasbishop 
> I'm curious if we can "pause" changes to the bottomSheet (setting label and sheet height) until after the selection is made on the actionSheet?

Unfortunately in the current implementation - NO :(

This is also a shared code between the web and mobile. It sets attributes immediately and then if the user clicks "cancel" it reverts them. When the user clicks "Apply" then those changes are applied to all images inside. 

If it's not a blocker I would go with the current implementation and create an issue for that. This PR is only a mobile part of the gallery refactoring and I'm afraid that it's already too big. What do you think?

2020-11-24 10:21 UTC, lukewalczak requested changes

2020-11-24 10:21 UTC, lukewalczak commented on packages/block-editor/src/components/media-placeholder/index.native.js
> +								if ( props.onFocus ) {
Maybe add `onFocus` to props destructuring above 🤔

2020-11-24 10:21 UTC, lukewalczak commented on packages/block-library/src/gallery/dirty-image-options.android.js
> +			if ( isVisible && pickerRef.current ) {
```suggestion
			if ( isVisible && pickerRef?.current ) {
```

2020-11-24 10:21 UTC, lukewalczak commented on packages/block-library/src/gallery/dirty-image-options.ios.js
> +};
`dirty-image-options.ios.js` and `dirty-image-options.android.js` look alike, can we somehow unify both files?

2020-11-24 10:21 UTC, lukewalczak commented on packages/block-library/src/gallery/gallery-styles.native.scss
> +	padding-top: 16;
Use grid variable

2020-11-25 00:10 UTC, iamthomasbishop commented
> If it's not a blocker I would go with the current implementation and create an issue for that.

That's totally fine, thanks @dratwas!

2021-07-27 19:31 UTC, chipsnyder commented
Closing this PR in favor of the updated mobile PR https://github.com/WordPress/gutenberg/pull/31306

2021-07-27 19:31 UTC, closed without merging