Add PHP side of the default template type definitions
WordPress/gutenberg pull request #27036
Opened 2020-11-17 12:54 UTC by Copons

## Description

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-11-17 16:34 UTC, gziolo commented
It looks like there is one merge issue to resolve now, but overall it all looks good. Thank you for breaking up #26636 into smaller PRs 😍, I didn't feel confident to accept the previous PR but those changes seem to be a nice improvement. You might still want to validate with someone more familiar with FSE 😅

2020-11-17 20:27 UTC, noahtallen requested changes, later dismissed
Not quite sure what's happening, but the descriptions aren't rendering correctly:

<img width="376" alt="Screen Shot 2020-11-17 at 12 26 11 PM" src="https://user-images.githubusercontent.com/6265975/99443809-2bea0e00-28d0-11eb-8d09-c19bf004cc2c.png">
<img width="1792" alt="Screen Shot 2020-11-17 at 12 26 17 PM" src="https://user-images.githubusercontent.com/6265975/99443811-2c82a480-28d0-11eb-82c6-914f40b24ba6.png">

2020-11-17 20:27 UTC, noahtallen commented on lib/template-loader.php
>  function get_template_types() {
Should we move this function to `default-template-types.php`? Seems similar to e.g. `gutenberg_get_indexed_default_template_types`

2020-11-17 20:27 UTC, noahtallen commented on lib/templates.php
> +	unset( $default_template_types['embed'] );
I know I mentioned this in the previous review, but my opinion is still that we just shouldn't add `embed` to the template type list in the first place if it's somehow different from everything else

2020-11-18 10:36 UTC, Copons commented
> Not quite sure what's happening, but the descriptions aren't rendering correctly:

@noahtallen in the JS counterpart to this PR (#27038) I've updated the description selector from: `excerpt.rendered` to `excerpt.raw`.
I think generally excerpts don't accept HTML (and more so in this case where their usage is "internal", not exposed to the site users), so there should be no need to grab the rendered version and _dangerously_ use it.

2020-11-18 11:17 UTC, gziolo commented
There are some e2e test failures in specs covering reusable blocks. Is there any chance it's related?

2020-11-18 14:40 UTC, Copons commented
> There are some e2e test failures in specs covering reusable blocks. Is there any chance it's related to this PR?

@gziolo I've tried running them a few times, always receiving different fails.

First time there was something going on with the Embed block. This PR shouldn't affect any blocks, but it does remove the `embed` template type from the default types (it's not used, and even manually removed at some point — removal that I've left in the code, in the off chance a third party adds it by filtering the list).
Regardless, a second run cleared those fails, and replaced them with others related to the Inserter, which I'm pretty confident cannot be caused by this PR, as it's PHP-only.

2020-11-19 10:35 UTC, gziolo commented
> Regardless, a second run cleared those fails, and replaced them with others related to the Inserter, which I'm pretty confident cannot be caused by this PR, as it's PHP-only.

Yes, no idea where it's coming from 🙁

2020-11-19 10:39 UTC, gziolo approved these changes

2020-11-19 11:28 UTC, david-szabo97 approved these changes
- Cleaned auto-drafts
- New auto-drafts are created with the correct title and description
- Opened site editor
- Correct template loaded
- Templates title and description match

👍 ✅

2020-11-19 15:00 UTC, merged