Search Block: Add rounded block style
WordPress/gutenberg pull request #27220
Opened 2020-11-24 07:30 UTC by aaronrobertshaw

## Description
Adds a new rounded block style for the search block. This will add a border radius to the search block including adding adjusted border radii to the input and button when the button is placed "inside".

This is an alternate approach to adding border radius block support as suggested in https://github.com/WordPress/gutenberg/pull/25791#discussion_r522811059

Note: This uses a CSS variable for the border radius value. This allows;
- the value to be inherited and used with `calc()` for inner elements
- the user to define the border radius variable within different scopes if it makes sense for different search blocks to have different radius values
- the user to only have to set a single CSS variable rather than override multiple styles

## How has this been tested?
Manually.

1. Add a search block to a post
2. Select the rounded block style from the sidebar
3. Switch between different button positions via the block toolbar option and confirm rounded styles are applied
4. Check the frontend also gets correct styles

## Screenshots
![SearchRoundedStyle](https://user-images.githubusercontent.com/60436221/100061937-8a882c80-2e7a-11eb-895b-b8bf1577a476.gif)

## Types of changes
New feature.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR.

2020-11-30 04:03 UTC, glendaviesnz commented
This tested well for me, my only question was whether there should be some extra padding on left of placeholder text when rounded chosen as text looks slightly odd at the edge of the radius, eg. 

Instead of this:
<img width="246" alt="Screen Shot 2020-11-30 at 5 01 20 PM" src="https://user-images.githubusercontent.com/3629020/100567659-e72d9080-332d-11eb-9d4e-f0ffd28e8f05.png">

does look better:
<img width="239" alt="Screen Shot 2020-11-30 at 5 01 07 PM" src="https://user-images.githubusercontent.com/3629020/100567679-f14f8f00-332d-11eb-83c1-946fa641e35b.png">

Might just be a personal opinion thing so not critical I don't think

2020-11-30 04:07 UTC, aaronrobertshaw commented
> This tested well for me, my only question was whether there should be some extra padding on left of placeholder text when rounded chosen as text looks slightly odd at the edge of the radius

Agreed, I'll make that update. 

I'm also still waiting to see if we go down this path, a separate border radius control to allow custom radius values or the full block support approach. https://github.com/WordPress/gutenberg/pull/25791#issuecomment-732716190

2020-11-30 08:55 UTC, aristath approved these changes
Code looks good, and testing it everything seems to be OK.
If we decide to go with this implementation instead of a separate border-radius control this looks OK to merge :+1:

2020-12-04 16:11 UTC, apeatling commented
I don't think this is the direction we should go in because designers should have more fine grained control of border radius than this in order to create interesting patterns. Other examples of this need are [here](https://github.com/WordPress/gutenberg/issues/26559) and [here](https://github.com/WordPress/gutenberg/issues/26556).

For now I think we should merge the block support for border radius and hold off on this.

2020-12-04 16:13 UTC, apeatling requested changes
I don't think this is the direction we should go in because designers should have more fine grained control of border radius than this in order to create interesting patterns. Other examples of this need are here and here.

For now I think we should merge the block support for border radius and hold off on this.

2020-12-11 06:36 UTC, aaronrobertshaw commented
Closing this now https://github.com/WordPress/gutenberg/pull/25791 has been merged. 

There is a new PR to opt into the border radius support here https://github.com/WordPress/gutenberg/pull/27664. It is simply the extracted search block updates from the border radius support PR.

2020-12-11 06:36 UTC, closed without merging