Add additional information about lock inheritance
WordPress/gutenberg pull request #27834
Opened 2020-12-20 21:30 UTC by PypWalters

## Description
Adds clarity to the documentation concern mentioned here: https://github.com/WordPress/gutenberg/issues/18711

2020-12-22 15:07 UTC, chrisvanpatten requested changes, later dismissed
A few small grammatical/clarity suggestions, but overall this is great.

2020-12-22 15:07 UTC, chrisvanpatten commented on docs/designers-developers/developers/block-api/block-templates.md
> +A block template is defined as a list of block items. Such blocks can have predefined attributes, placeholder content, and be static or dynamic. Block templates allow for specifying a default initial
```suggestion
A block template is defined as a list of block items. Such blocks can have predefined attributes, placeholder content, and be static or dynamic. Block templates allow specifying a default initial state for an editor session.
```

2020-12-22 15:07 UTC, chrisvanpatten commented on docs/designers-developers/developers/block-api/block-templates.md
> +Lock settings can be inherited by InnerBlocks. If `templateLock` is not set in an InnerBlocks area: the locking of the parent InnerBlocks area is used. If the block is a top level block: the locking
```suggestion
Lock settings can be inherited by InnerBlocks. If `templateLock` is not set in an InnerBlocks area, the locking of the parent InnerBlocks area is used. If the block is a top level block, the locking configuration of the current post type is used.
```

2020-12-24 21:50 UTC, youknowriad approved these changes
Thanks 👍

2020-12-24 21:50 UTC, merged