Refresh nonce with heartbeat
WordPress/gutenberg pull request #2790
Opened 2017-09-25 19:20 UTC by adamsilverstein

## Summary
Refresh the wp-api nonce when a new nonce is available, keeping the nonce fresh and the client authorized. Fixes https://github.com/WordPress/gutenberg/issues/2088.

## Description
Add a wp_rest nonce to the heartbeat response when in Gutenberg.
Add a JavaScript callback on jQuery( document ) 'heartbeat-tick' which heartbeat triggers. Update the wp-api nonce if it has changed.

## How Has This Been Tested?
Verified heartbeat returns nonce.
Verified if nonce is different, logic sets it on root endpoint.

2017-09-28 13:39 UTC, ellatrix requested changes
@adamsilverstein This doesn't solve anything as far as I can see. The way I test it is setting the nonce life to 10 seconds. This is low enough to ensure that by the first heartbeat after page load the nonce will be invalid, so it's just like being away for over 24 hours and coming back to an invalid nonce. With this patch, nothing will be sent back. You'll need to hook into `wp_refresh_nonces` (see https://github.com/WordPress/wordpress-develop/blob/4.8.2/src/wp-admin/includes/ajax-actions.php#L2794). `heartbeat_send` is too late.

I wouldn't use jQuery here, we don't want a dependency on jQuery as well. You can just use that native browser API as we don't need to support lower IE versions.

Additionally there are some listing errors.

2017-09-28 16:53 UTC, adamsilverstein commented
@iseulde thanks for testing and the feedback, also for explaining how you tested - I wasn't sure how to do that. I saw `wp_refresh_nonces` and didn’t realize i had to use it, thanks for clarifying.

I thought I saw jQuery already used, I'll switch that and fix the linting errors. :)

2017-09-28 19:00 UTC, adamsilverstein commented
@iseulde actually for the jquery, I am listening for the event triggered by heartbeat:

`jQuery( document ).on( 'heartbeat-tick' )` which is triggered by heartbeat.js using jQuery. Can I listen for the jQuery event using native JS?

2017-09-28 19:11 UTC, adamsilverstein commented
@iseulde I switched the hook to wp_refresh_nonces and verified this actually works correctly - i set my nonce expiration (30 sec) and heartbeat rate (15 sec) low and watched as the nonce expired and got renewed.

Can you please re-test?

2017-09-28 19:28 UTC, iseulde commented
> actually for the jquery, I am listening for the event triggered by heartbeat:

Ah ok, that's unfortunate. :) Do we have proper dependencies set for heartbeat.js?

2017-09-29 02:35 UTC, adamsilverstein commented
> Ah ok, that's unfortunate. :) Do we have proper dependencies set for heartbeat.js?

Yes, in script-loader, we add hearbeat with a jQuery dependency:
`$scripts->add( 'heartbeat', "/wp-includes/js/heartbeat$suffix.js", array('jquery'), false, 1 );`

Is that what you meant?

heartbeat.js has 6 $document.trigger() calls. If we swap out these for [wp.hooks](https://www.npmjs.com/package/@wordpress/hooks), we could remove the jQuery dependency.

2017-10-02 09:30 UTC, iseulde commented
@adamsilverstein I meant here, in Gutenberg. I don't see a Heartbeat dependency. :)

2017-10-05 19:56 UTC, adamsilverstein commented
> I meant here, in Gutenberg. I don't see a Heartbeat dependency. :)

Ah, good point - I was testing on the post page so it must be loading there. i'll check/add the dependency.

2017-10-09 11:15 UTC, adamsilverstein commented
@iseulde I added the heartbeat dependency in https://github.com/WordPress/gutenberg/pull/2790/commits/8e6e42647a0b67c54c69c1bd34ca6ee84c4112e7 - does this work for you now?

2017-10-10 21:56 UTC, iseulde commented
@adamsilverstein I fixed the failing tests, and replaced `wp.api.endpoints.at(0).get( 'nonce' )`, because that's returning `undefined`. Used the settings object instead.

2017-10-10 22:11 UTC, ellatrix approved these changes

2017-10-10 22:11 UTC, merged

2017-10-12 12:42 UTC, adamsilverstein commented
>  replaced wp.api.endpoints.at(0).get( 'nonce' ), because that's returning undefined. Used the settings object instead.

@iseulde Thanks for merging! I think I was testing in trunk and you were maybe on 4.8? The nonce handling changes a little in 4.9 and  I don't think this will work since https://core.trac.wordpress.org/changeset/41553 - I am going to open a new PR that will use more flexible code to use the right approach in all cases.

2017-10-12 12:45 UTC, iseulde commented
Yeah, I'm just on the latest version. :)

2017-10-12 12:47 UTC, adamsilverstein commented
Ok, makes sense and we need it to work there as well, so I'l work on a follow up PR.

2018-10-05 17:46 UTC, getsource commented
I'm having this issue. Is there a different place where it's being tracked?

2018-10-19 04:46 UTC, adamsilverstein commented
@getsource yes, see https://github.com/WordPress/gutenberg/issues/9260