A wether, as it turns out, is a castrated ram
WordPress/gutenberg pull request #28008
Opened 2021-01-06 08:14 UTC by JustinSainton

## Description
A simple documentation change, updating several instances of a mis-applied word throughout the codebase.

## How has this been tested?
Nothing functional changed, only documentation. 

## Types of changes
Only docs.

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2021-01-06 13:34 UTC, ockham approved these changes
Thanks for this! The title made my day :ram: :laughing:

2021-01-06 13:46 UTC, ockham requested changes
Oh, I just noticed that the Static Analysis CI job is actually complaining about the removal of the (auto-generated) whitespace after "`void`:"

2021-01-06 20:04 UTC, ockham commented
Thanks for addressing!

The remaining error in the Static Analysis workflow seems unrelated:

```
 75:4  error  Deprecated functions must be removed before releasing this version  no-restricted-syntax
```

referring to this: https://github.com/WordPress/gutenberg/blob/637c43de571b5648e867f3d4d223712895304041/packages/interface/src/components/interface-skeleton/index.js#L75

I'll investigate some more tomorrow!

cc/ @youknowriad

2021-01-06 20:09 UTC, ockham commented
I've filed an issue here: https://github.com/WordPress/gutenberg/issues/28027

2021-01-07 12:32 UTC, ockham commented
#28027 has been fixed. @JustinSainton Can you rebase the branch on latest `master`? That should fix the issue :slightly_smiling_face:

2021-01-08 00:06 UTC, JustinSainton commented
> #28027 has been fixed. @JustinSainton Can you rebase the branch on latest `master`? That should fix the issue 🙂

sure thing, should be square now! watching the checks with baited breath 🍿

2021-01-08 13:03 UTC, ockham commented
Hmm, looks like the rebase didn't produce quite the right result :sweat_smile: 

![image](https://user-images.githubusercontent.com/96308/104018558-43e85a80-51ba-11eb-9ad7-f4f79cb17091.png)

I'll have another stab at it if you don't mind :smile:

2021-01-08 13:13 UTC, ockham commented
> Hmm, looks like the rebase didn't produce quite the right result 
> 
> ![image](https://user-images.githubusercontent.com/96308/104018558-43e85a80-51ba-11eb-9ad7-f4f79cb17091.png)
> 
> I'll have another stab at it if you don't mind

Ah, I'd missed that this branch is in a fork of the Gutenberg repo (`zao-web`) to which I don't have write access :sweat_smile: 

@JustinSainton Can you try the following for me? On the `zao-web` `master` branch,

```
git fetch upstream
git rebase upstream/master
git push --force-with-lease
```

(assuming that you have added the original Gutenberg repo as your `upstream` remote. If you haven't, you can do so via `git add remote upstream git@github.com:WordPress/gutenberg.git`.)

2021-01-08 14:24 UTC, gziolo commented
The more detailed docs related to updating your branch when using a fork can be found at:
https://github.com/WordPress/gutenberg/blob/master/docs/contributors/git-workflow.md#keeping-your-fork-up-to-date

2021-01-08 15:23 UTC, JustinSainton commented
> The more detailed docs related to updating your branch when using a fork can be found at:
> https://github.com/WordPress/gutenberg/blob/master/docs/contributors/git-workflow.md#keeping-your-fork-up-to-date

Reading this now - thanks so much for that, @gziolo!

> > Hmm, looks like the rebase didn't produce quite the right result
> > ![image](https://user-images.githubusercontent.com/96308/104018558-43e85a80-51ba-11eb-9ad7-f4f79cb17091.png)
> > I'll have another stab at it if you don't mind
> 
> Ah, I'd missed that this branch is in a fork of the Gutenberg repo (`zao-web`) to which I don't have write access 😅
> 
> @JustinSainton Can you try the following for me? On the `zao-web` `master` branch,
> 
> ```
> git fetch upstream
> git rebase upstream/master
> git push --force-with-lease
> ```
> 
> (assuming that you have added the original Gutenberg repo as your `upstream` remote. If you haven't, you can do so via `git add remote upstream git@github.com:WordPress/gutenberg.git`.)

Giving that a go now!

Thank you both for your patience - it's a goal of mine to contribute to Gutenberg more this year, so getting past some of these initial hurdles is hugely helpful. Thank you!

2021-01-08 19:30 UTC, ockham commented
> Giving that a go now!

Seems to have worked now :tada: Lookin' good!

> Thank you both for your patience - it's a goal of mine to contribute to Gutenberg more this year, so getting past some of these initial hurdles is hugely helpful. Thank you!

Thank _you_ -- and welcome to Gutenberg! Looking forward to having you join the party :partying_face:

2021-01-08 19:31 UTC, ockham approved these changes

2021-01-08 20:19 UTC, merged