Fix inline block toolbar keyboard navigation
WordPress/gutenberg pull request #28420
Opened 2021-01-22 12:41 UTC by diegohaz

Closes #26114

## Description

TBD

## How has this been tested?

TBD

## Screenshots 

TBD

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2021-01-25 14:19 UTC, diegohaz commented on packages/block-editor/src/components/rich-text/format-toolbar-container.js
> +				__unstableSlotName={ null }
I'm passing `null` to the slot name so it renders inline in the React tree, and not on a separate slot as it won't find any slot: https://github.com/WordPress/gutenberg/blob/5c24a7d6e5882a1f2b9e0dff787fecfccce01335/packages/components/src/popover/index.js#L627-L635

I don't know if there's a better way to achieve this, but I think we could have an `inline` prop or something on Popover.

2021-01-25 19:16 UTC, alexstine commented
There is only one improvement I will suggest.

Can you modify the PR to allow Alt+F10 open the formatting toolbar if focus in in Caption field? Currently, only Shift+Tab can do this.

Otherwise it is functioning well.

Thanks.

2021-02-04 17:06 UTC, diegohaz commented
@alexstine Thanks for reviewing it! I've added support for Alt+F10.

2021-02-04 23:08 UTC, alexstine commented
@diegohaz I've given it a test, this now seems perfect.

Thanks.

2021-02-08 19:07 UTC, ellatrix requested changes
Hm, I don't think we should put popovers inline in the editor canvas. Would be great to find another way to do this.

2021-02-10 19:56 UTC, diegohaz commented
@ellatrix Thanks for reviewing this. The only other way I can think of is [creating focus trap elements](https://twitter.com/diegohaz/status/1229837604977348612) that will transfer the focus between the image caption editable content and the toolbar and vice-versa. But this technique is rather complex and there are [known issues with VoiceOver](https://twitter.com/diegohaz/status/1252633190956781570) (VO will just ignore these focus trap elements when navigating through elements with VO keys unless you have an unreliable timeout on it).

The safest way I can think of is relying on the DOM order like in this PR. What do you think is the caveat on this?

2021-03-15 13:26 UTC, ellatrix commented
It should align more with how the block toolbar works, which is also not embedded in the content's DOM. Ideally, the UI DOM and the content DOM should be kept separate so the styling is isolated. It's also possible to run into some weird selector issues like :first-child and :last-child if the popover unexpectedly appears in the content.

To align better with the block toolbar, I'd imagine you could reverse tab into the inline toolbar just like you would for the block toolbar. Another reverse tab could put you in the block toolbar. In other to accomplish that, the inline toolbar DOM should be rendered right after the block toolbar DOM.

2021-03-15 14:37 UTC, ellatrix commented
I created #29874. The inline toolbar is actually accessible by keyboard, it's just misplaced. It should be rendered after the block toolbar instead of before.

2021-07-12 15:02 UTC, ajlende commented
Fixed in #31134

2021-07-12 15:02 UTC, closed without merging