Reflect text size in FontSizePicker choices
WordPress/gutenberg pull request #28761
Opened 2021-02-05 01:31 UTC by inc2734

## Description
フォントサイズピッカーの選択肢に文字サイズのstyleが反映されていない。

## Screenshots
<img width="271" alt="スクリーンショット 2021-02-04 15 34 25" src="https://user-images.githubusercontent.com/1094306/106977204-3b754680-679d-11eb-8556-17109d8677a7.png">

## Types of changes
Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2021-02-05 09:12 UTC, talldan requested changes
Thanks for your contribution. This will need to account for the varying ways themes defined font sizes.

2021-02-05 09:12 UTC, talldan commented on packages/components/src/font-size-picker/index.js
> +			fontSize: `min( ${ option.size }px, ${ MAX_FONT_SIZE_DISPLAY } )`,
The `size` is a value defined by the theme. Some themes seem to make this a px value (e.g `12px`) while others just define it as a number (`12`)

It looks like when #26705 was tested it was using a theme that just defined it as a number (Twenty Twenty One). Testing this PR in Twenty Twenty One, and things are broken.

This code will have to check if the `option.size` ends with `'px'`, and only add it if it doesn't.

2021-02-10 07:57 UTC, talldan commented
Hi @inc2734, just wanted to catch up with you on whether you're able to address the feedback on this PR?

No problem if you can't. It is quite a high priority issue, so someone else can take over if you don't have time. Just need to know one way or another.

2021-02-10 08:30 UTC, inc2734 commented
返信に気づいていませんでした。すみません。

プルリクエストの後、調査してみたのですが、master ブランチではこの問題は解決されているようでした。

https://github.com/WordPress/gutenberg/blob/master/packages/components/src/font-size-picker/index.js

I noticed this issue when I was using WordPress 5.6.1 and sent a pull request immediately, but if this issue is fixed in the master branch, I doubt it needs to be fixed in Gutenberg.

2021-02-11 18:16 UTC, gwwar commented
Thanks @inc2734 for helping with this one! I think we can close the PR out since we can't reproduce with the plugin active.

I dug a bit further to see why this was fixed in the Gutenberg plugin, and it looks like in 5.6.1 we're passing in a NaN value to the fontsize onChange function.

<img width="635" alt="Screen Shot 2021-02-11 at 10 01 04 AM" src="https://user-images.githubusercontent.com/1270189/107679475-75d55c80-6c51-11eb-9008-a9a96d3e02d4.png">

This was fixed in
<img width="1521" alt="Screen Shot 2021-02-11 at 10 12 11 AM" src="https://user-images.githubusercontent.com/1270189/107679607-a0271a00-6c51-11eb-9469-4bd287bf8ed5.png">
https://github.com/WordPress/gutenberg/pull/26475/files#diff-3b85bc4bfdaea5cd9cb6173bf9f52656ce4f656e5f846442fd15185a5b78fb1dR102-R106

2021-02-16 04:13 UTC, closed without merging