Polish social links when inside navigation.
WordPress/gutenberg pull request #28836
Opened 2021-02-08 11:54 UTC by jasmussen

The Social Links block, when used inside the Navigation block, is rather broken:

<img width="1235" alt="before" src="https://user-images.githubusercontent.com/1204802/107215907-471a7480-6a0c-11eb-92a7-df6b30ca08af.png">

You can't really insert any items at all, and it fades out to suggest it's selected even when it isn't. This PR fixes that:

![after](https://user-images.githubusercontent.com/1204802/107215963-58fc1780-6a0c-11eb-8db0-b163a83bd9e6.gif)

It:

- Vertically centers the social links block inside the taller navigation block.
- Makes it so the social links placeholder doesn't collapse, making the appender buttons overlap.
- Only "fades out" the social links placeholder state when the block is actually selected. Not just when any ancestor is selected.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2021-02-08 16:59 UTC, mkaz commented on packages/block-library/src/social-links/editor.scss
> +		//position: absolute;
When ready, just delete instead of commenting out. I can understand when iterating and keeping track of changes.

2021-02-08 17:10 UTC, mkaz requested changes
The changes within the navigation block look good and definitely works better.
Though I think there is a regression to the appender when using the block outside of the navigation block.  See GIF below:

![social-links](https://user-images.githubusercontent.com/45363/107255767-81c0e480-69ed-11eb-9a32-dd35ad317293.gif)

2021-02-09 08:54 UTC, jasmussen commented
Thank you for the review! I fixed the comment 😅 

> Though I think there is a regression to the appender when using the block outside of the navigation block. See GIF below:

That's actually separate, and technically intended behavior (see master branch). The sibling inserter, the blue one with a line, now works vertically in addition to horizontally, and shows up between rows of horizontal child blocks when hovering the gutter. You can see this also with the Buttons block, and if #28833 lands, there too.

I agree there's probably some refinement to do here, it's still fiddly and perhaps too easy to invoke. But I think it can be made to work. In any case, it should likely happen separately.

2021-02-09 14:16 UTC, mkaz approved these changes

2021-02-09 14:17 UTC, mkaz commented
Ok, it feels like too many inserters, but as you say that is different and can be addressed later.
This one is working better, and not a regression so :rocket:

2021-02-09 14:18 UTC, merged