Add Items Justification to Social Links
WordPress/gutenberg pull request #28980
Opened 2021-02-12 19:23 UTC by mkaz

## Description

Adds justify toolbar controls to Social Links, allows for justifying items in the menu (left, center, right, and space-between). This matches the navigation and buttons features.

@jasmussen - the .wp-social-links class was hard-coded with a `justify-content: flex-start;` that I removed to get this to work. I'm not sure if we need it since `flex-start` is the default.

## How has this been tested?

1. Add a social links block with some social icons
2. Confirm everything works as expected
3. Apply PR and confirm existing blocks loads and no visual change
4. Use new Justify items menu item and confirm left, center, right, space-between works in editor and while viewing.

## Screenshots

![social-justify](https://user-images.githubusercontent.com/45363/107812456-8dc9e080-6d24-11eb-88ee-2c567d690817.gif)

## Types of changes

- Adds justify toolbar to social inks

2021-02-15 08:02 UTC, jasmussen commented on packages/block-library/src/social-links/save.js
> +		[ `items-justified-${ itemsJustification }` ]: itemsJustification,
Did we discuss the naming of this CSS class? I seem to vaguely recall that we did, but can't recall where we ended. I would've probably preferred something like `has-justification-left` — but maybe there was already an existing CSS class out in the wild?

2021-02-15 08:07 UTC, jasmussen requested changes
All looked cool right up until the end (and removing the flex-start seems fine). Before:

<img width="925" alt="Screenshot 2021-02-15 at 09 01 29" src="https://user-images.githubusercontent.com/1204802/107920194-d70c7100-6f6c-11eb-859e-a41e527e1304.png">

After:

<img width="894" alt="Screenshot 2021-02-15 at 09 02 50" src="https://user-images.githubusercontent.com/1204802/107920198-d8d63480-6f6c-11eb-89d1-6704c022fd44.png">

<img width="888" alt="Screenshot 2021-02-15 at 09 02 54" src="https://user-images.githubusercontent.com/1204802/107920209-db388e80-6f6c-11eb-96a9-7e81295779b2.png">
<img width="760" alt="Screenshot 2021-02-15 at 09 03 00" src="https://user-images.githubusercontent.com/1204802/107920216-dc69bb80-6f6c-11eb-91e9-b94cc801ce52.png">

<img width="865" alt="Screenshot 2021-02-15 at 09 03 04" src="https://user-images.githubusercontent.com/1204802/107920221-dd9ae880-6f6c-11eb-96b9-09a44b46799f.png">

However it doesn't work on the frontend: this should be "space between":

<img width="2266" alt="Screenshot 2021-02-15 at 09 05 54" src="https://user-images.githubusercontent.com/1204802/107920308-091dd300-6f6d-11eb-976e-8c4aba39bcab.png">

It also looks like the flex-start is still output by default on the frontend:

<img width="430" alt="Screenshot 2021-02-15 at 09 03 34" src="https://user-images.githubusercontent.com/1204802/107920332-13d86800-6f6d-11eb-887e-f9ed15dabea2.png">

It looks like the items justification CSS is not output on the frontend at all. 

I have no idea why, because the code looks right.

2021-02-16 22:27 UTC, mkaz commented
@jasmussen I added the justification CSS to the common.scss for block-library and it all works as expected.
One thing I did notice is for centering, if the block is align=center then the social links add a justify-items center also. I'm not sure what should be done here if anything, the behavior is a bid odd when using both align and justify.

2021-02-19 10:02 UTC, jasmussen approved these changes
Ship it!

<img width="1146" alt="Screenshot 2021-02-19 at 11 01 51" src="https://user-images.githubusercontent.com/1204802/108489531-f32c4d00-72a1-11eb-9674-7bec0a75b923.png">

<img width="1132" alt="Screenshot 2021-02-19 at 11 01 40" src="https://user-images.githubusercontent.com/1204802/108489543-f58ea700-72a1-11eb-98ac-285e018420e7.png">

2021-02-19 14:15 UTC, merged