New block: Post comments link
WordPress/gutenberg pull request #29564
Opened 2021-03-04 13:15 UTC by carolinan

## Description

Part of https://github.com/WordPress/gutenberg/issues/22724
Adds a new post comments link block.

## How has this been tested?

I have added the block inside the post content, and viewed the post on the front:
With and without comments, with and without comments enabled.

I have added the block to the index.html file of TT1 Blocks, to make sure that it inherits the context and displays correctly in a query loop.

## Screenshots 
TT1 Blocks, front:
![image](https://user-images.githubusercontent.com/7422055/109969141-d6593600-7cf3-11eb-8cd5-571e14daa932.png)
_The title is showing because the theme does not have a screen-reader-text class._

## Types of changes

New block.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR.

2021-03-04 13:23 UTC, carolinan commented
I haven't learnt how to write the tests yet, saving that for tomorrow 😸

2021-03-31 10:14 UTC, scruffian commented
This looking good. I think it would be good to have an option to customize the text - I might like it to say "Leave a comment" rather than show the number.

It might also be nice to add an option to display an icon next to the link.

2021-04-05 07:23 UTC, jasmussen commented
This is what I see:

<img width="789" alt="Screenshot 2021-04-05 at 09 19 18" src="https://user-images.githubusercontent.com/1204802/113548603-1ca1fd80-95f0-11eb-938a-33ff549320e6.png">

We need a new icon. But I think that's probably something that can wait, and not something that should block this PR. I'd also echo Ben's comment above about a custom phrasing, but also suggest that's something that can wait (I'd like the same customizability for the pagination blocks, for example).

One thing I noticed is that the block isn't inert:

![focusable](https://user-images.githubusercontent.com/1204802/113548699-49561500-95f0-11eb-85ac-2899fd980f39.gif)

I could swear there was precedence in some existing block for making links like that inert using a `Disabled` component, but I can't find it now, and I'm noticing also Latest Posts and others are interactive. So probably that should also not be a blocker.

So I guess this just needs a code review. But would be good to ticket followups. Thank you!

2021-04-06 04:34 UTC, carolinan commented
If the disabled component is used we won't be able to also have an editable text.

2021-04-06 06:50 UTC, jasmussen commented
> If the disabled component is used we won't be able to also have an editable text.

Good point, though we could just put a textfield in the sidebar. While normally putting it directly in the canvas is the best strategy, I have a vague instinct that the sidebar might be where people intuit a rename to be. But this is not a strong opinion, and as noted, it could definitely be a followup.

2021-04-07 05:20 UTC, carolinan commented
The use of links inside the editors may need a more comprehensive review so that the behavior is the same in different blocks.
And if there already are best practices, they need to be documented.
The problem with having the link clickable here is that in the site editor, the linked page is opened inside the iframe.
It can also be confusing with visible links that are not clickable (but can be opened with right click), but it seems like the least bad option.

2021-04-07 05:32 UTC, jasmussen commented
Agreed. We've been talking about a "navigation cursor" you can select from the tools drop-down, which would navigate to link destinations inside the editor, when links are clicked. Sometimes referred to as "browse mode".

2021-04-07 06:08 UTC, aristath requested changes

2021-04-07 06:08 UTC, aristath commented on packages/block-library/src/post-comments-link/edit.js
> +		}
Shouldn't this be using `_n()`? That would account for languages where the plural is not the same for all numbers (in some languages the plural for 2 is different)

2021-04-07 06:08 UTC, aristath commented on packages/block-library/src/post-comments-link/index.php
> +	}
Nitpicking, but could we change the alignment of this to make things line-up a bit more, and have `return` nested 1 level less?

```suggestion
	if (
		! isset( $block->context['postId'] ) ||
		isset( $block->context['postId'] ) &&
		! comments_open( $block->context['postId'] )
	) {
		return '';
	}
```

2021-04-07 06:08 UTC, aristath commented on packages/block-library/src/post-comments-link/index.php
> +	}
This should probably be using `_n()` too.

2021-04-07 06:08 UTC, aristath commented on packages/block-library/src/post-comments-link/index.php
> +		'</div>';
A bit of a nitpick, but `sprintf()` is not really necessary here, and we should avoid concatenating strings like `'</a>' . '</div>'` when they can be combined.

```suggestion
	return "<div {$wrapper_attributes}><a href='{$comments_link}'>{$comment_text}</a></div>";
```

2021-04-07 09:05 UTC, carolinan commented on packages/block-library/src/post-comments-link/edit.js
> +		}
Did you mean like this?
```
if ( commentsCount.length === 0 ) {
		commentsText = __( 'No comments' );
	} else {
		commentsText = sprintf(
		/* translators: %d Number of comments */
		_n(
			'%d comment',
			'%d comments',
			commentsCount
		),
		commentsCount
	);
}

```

2021-04-07 11:12 UTC, carolinan commented on packages/block-library/src/post-comments-link/edit.js
> +		}
Ok that did not work because it now says "1 comments"

2021-04-07 11:51 UTC, carolinan commented on packages/block-library/src/post-comments-link/edit.js
> +		}
The `commentsCount.length i`s also incorrect here

2021-04-14 11:00 UTC, aristath commented on packages/block-library/src/post-comments-link/edit.js
> +				),
The linter is complaining, this needs to change to the below:
```suggestion
				_n( '%s comment', '%s comments', commentsNumber ),
```

2021-04-16 11:59 UTC, aristath approved these changes

2021-04-19 06:55 UTC, merged