Fix for Text Mode toolbar
WordPress/gutenberg pull request #3043
Opened 2017-10-17 21:44 UTC by ShreyaSingh10

## Description

The Text Mode toolbar is entirely visible in every screen resolution
## How Has This Been Tested?

With the help of Chrome Inspector

## Screenshots (jpeg or gifs if applicable):

## Types of changes
## Checklist:

2017-10-19 20:04 UTC, aduth requested changes
It appears beyond just the formatting controls that the entire editor component layout (`.editor-layout__editor`) is potentially hidden behind the fixed editor toolbar on small screens. In visual mode this is offset by some padding on `.editor-visual-editor` but it doesn't seem to be enough. I suggest we add margin to the `.editor-layout__editor`.

Also be mindful of CSS coding guildelines, where the introduced styles should be structured using tabs, not spaces:

https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#structure

2017-10-20 18:37 UTC, ShreyaSingh10 commented
@aduth I have changed the margin to the css class you suggested. Though now it looks aligned slightly to left if you can confirm i will fix that.

2017-10-20 19:52 UTC, aduth commented
I'm going to add a Design Review label because while I agree we should have this margin, it prompts whether we should then adjust the padding of `.editor-visual-editor` in smaller displays. Now there is a fairly large gap between the toolbar and title in mobile viewports in Visual editing mode.

![Gap](https://user-images.githubusercontent.com/1779930/31839342-aa58e042-b5ae-11e7-9d49-b569a40d381c.png)

>Though now toolbar looks aligned slightly to right if you can confirm i will fix that.

I'm not seeing this myself.

2017-10-20 19:55 UTC, aduth commented on editor/modes/text-editor/style.scss
> +@media (max-width: 599px) {
I think we ought to define this style mobile-first with `margin-top: 56px;` and a media query to reset on larger displays. There are a number of [mixins](https://github.com/WordPress/gutenberg/blob/e869a9dcde45197feb9d1ebc1b45047c1da551a5/editor/assets/stylesheets/_mixins.scss#L1-L35) and [variables](https://github.com/WordPress/gutenberg/blob/e869a9dcde45197feb9d1ebc1b45047c1da551a5/editor/assets/stylesheets/_variables.scss#L111-L116) available for this. I think you'll want:

```scss
margin-top: 56px;

@include break-small {
	margin-top: 0;
}
```

...inside the `.editor-layout__editor` selector.

2017-10-23 20:22 UTC, ShreyaSingh10 commented
@aduth I have done the changes.

2017-10-23 22:45 UTC, aduth commented
@jasmussen Do you have any thoughts on how we might best address the gap mentioned in https://github.com/WordPress/gutenberg/pull/3043#issuecomment-338306500 ?

2017-10-24 07:19 UTC, jasmussen commented
Thank you for the PR, and thank you for opening #3041, appreciate it. The ticket certainly does reveal that we haven't given the text mode the love it deserves.

While there are issues in master, I don't think there's an easy fix, and although I appreciate the work done here, I suspect that we'll have to go a bit back to the drawing board when it comes to text mode. There's even disagreement whether the quick tags toolbar should even be there, and given the incoming codemirror implementation in 4.9, I suspect we'll want to redo that section regardless. As such, I would thank you for this PR, but I would not merge it, or even try to fix the implementation as it is today. Since I'm the person who built text mode as it is today, sorry about that ;)

Instead, I will open a new ticket to redesign the text mode once codemirror hits 4.9, and I will link your ticket as well as other past text mode tickets, so we can have a new umbrella ticket for improvements. 

Some of the issues highlighted by this PR can be seen here:

![screen shot 2017-10-24 at 09 14 09](https://user-images.githubusercontent.com/1204802/31929451-659af4ae-b89c-11e7-8175-4cc2bb89ae5b.png)

![screen shot 2017-10-24 at 09 14 13](https://user-images.githubusercontent.com/1204802/31929452-68118ab8-b89c-11e7-8190-a6d85c9279b4.png)

![screen shot 2017-10-24 at 09 14 16](https://user-images.githubusercontent.com/1204802/31929470-7c15018e-b89c-11e7-99a9-6c811edbf016.png)

![screen shot 2017-10-24 at 09 14 26](https://user-images.githubusercontent.com/1204802/31929471-7dbaac46-b89c-11e7-836b-ff0e0d6fb210.png)

![screen shot 2017-10-24 at 09 14 30](https://user-images.githubusercontent.com/1204802/31929472-7fc55f22-b89c-11e7-81ec-2b79a86e2b4c.png)

![screen shot 2017-10-24 at 09 14 33](https://user-images.githubusercontent.com/1204802/31929475-816db2d4-b89c-11e7-8d72-0bdd75c534d9.png)

2018-01-27 18:56 UTC, gziolo commented
@ShreyaSingh10 do you plan to finish this PR or should someone else take it over?

2018-02-14 23:45 UTC, youknowriad commented
Closing as this toolbar has been removed for now. Thanks for the time spent on this PR.

2018-02-14 23:45 UTC, closed without merging