Standardize block styles cursor on hover
WordPress/gutenberg pull request #31188
Opened 2021-04-26 11:28 UTC by devfle

## Description
I have unified the cursor of the block styles when hovering. Previously, a text cursor was displayed no matter what content was in there. This leads to confusion in my opinion. Gutenberg also uses pointer cursor for several interactive elements.

## How has this been tested?
Builded the newest version of gutenberg with my changes and tested it in several browsers.

## Screenshots 
Before:
<img width="498" alt="before" src="https://user-images.githubusercontent.com/52854338/116075163-e3aaf500-a692-11eb-8ea4-e17f6c9d3de8.png">

After:
<img width="376" alt="after" src="https://user-images.githubusercontent.com/52854338/116075179-e9a0d600-a692-11eb-9001-00a9a3435205.png">

## Types of changes

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-04-28 13:59 UTC, JustinyAhin reviewed
I've tested this PR, and it looks fine for me.

2021-05-01 22:53 UTC, devfle commented
> I've tested this PR, and it looks fine for me.

Hi! Thank you for testing! do we have to wait for an other reviewers?

2021-05-03 07:10 UTC, JustinyAhin commented
> > I've tested this PR, and it looks fine for me.
> 
> Hi! Thank you for testing! do we have to wait for an other reviewer? Or do I have any tasks to do?

Yes, I'd say let's wait for another one.

2021-05-03 08:26 UTC, carolinan requested changes, later dismissed
Hi
Changing the cursor style here would affect the editors and not only the block styles panel.

I think it would be better to limit the change and increase the specificity of the cursor style that is used in the block styles panel, so that the .editor-styles-wrapper cursor style does not override it.

See https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-styles/style.scss#L11)









(Also I am not able to build the files, please refresh it so that it is up to date with changes to trunk)

2021-05-03 10:32 UTC, devfle commented
> Hi
> Changing the cursor style here would affect the editors and not only the block styles panel.
> 
> I think it would be better to limit the change and increase the specificity of the cursor style that is used in the block styles panel, so that the .editor-styles-wrapper cursor style does not override it.
> 
> See https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-styles/style.scss#L11)
> 
> (Also I am not able to build the files, please refresh it so that it is up to date with changes to trunk)

Hi,
thanks for your review. However, weighting the CSS rule more doesn't do anything on its own. As long as the element gets the cursor passed directly, the parent style is not passed to the child element (no matter how many CSS classes are placed in front of the element). In my opinion the block-editor-block-preview__container should not set the cursor to "text" anymore, because the component occurs as you said in several places and therefore the styles from the parent element are overwritten everywhere.

I will rebase my branch and add the newest commits of the trunk to it.

2021-05-03 15:21 UTC, carolinan commented
I am not sure we understood each other. My suggestion is to only change the cursor for this component:
 /components/block-styles/style.scss and not at .editor-styles-wrapper.

2021-05-03 17:20 UTC, devfle commented
> I am not sure we understood each other. My **suggestion** is to only change the cursor for this component:
> /components/block-styles/style.scss and not at .editor-styles-wrapper.

I got that. I just thought it made sense to set the value to inherit in all places and have it be inherited by its parent elements.

Thanks for your suggestion. I have adjusted the whole thing now. However, as I mentioned earlier, I had to define a new rule. We don't get this line: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-styles/style.scss#L11
 to override the cursor: text from .editor-styles-wrapper.

2021-05-04 09:09 UTC, jasmussen commented
Thanks for the PR! I wasn't able to spin up the PR, and can't add a ton of value over what Carolina already shared. But I'd ask you also test the Patterns tab:

![patterns](https://user-images.githubusercontent.com/1204802/116982545-35720180-acc9-11eb-8ce2-d1829d32fc8d.gif)

It uses this CSS which I fear might regress if we land this PR as is:

<img width="665" alt="Screenshot 2021-05-04 at 11 06 57" src="https://user-images.githubusercontent.com/1204802/116982576-3dca3c80-acc9-11eb-8219-301a1ecd14cd.png">

2021-05-04 09:18 UTC, devfle commented
> Thanks for the PR! I wasn't able to spin up the PR, and can't add a ton of value over what Carolina already shared. But I'd ask you also test the Patterns tab:
> 
> ![patterns](https://user-images.githubusercontent.com/1204802/116982545-35720180-acc9-11eb-8ce2-d1829d32fc8d.gif)
> 
> It uses this CSS which I fear might regress if we land this PR as is:
> 
> <img alt="Screenshot 2021-05-04 at 11 06 57" width="665" src="https://user-images.githubusercontent.com/1204802/116982576-3dca3c80-acc9-11eb-8219-301a1ecd14cd.png">

Hi! I will fix the cursor in this hover state too. Thank you for the notice :-)

2021-05-04 09:54 UTC, devfle commented
@jasmussen  I checked it again. Nothing is overwritten by my fix. Neither for the Block Patterns, Reusable Blocks and the normal blocks. I have also implemented Carolina's recommendation (see last commit) so that it only applies to the Block Styles. So it should be safe.

2021-05-04 10:01 UTC, jasmussen commented
Awesome! I will let Carolina give the green light when she has a moment. Thanks for the work!

2021-05-06 03:16 UTC, carolinan commented
I have a problem with my local environment where git _rejects_ the checkout of this PR, I will need someone else to do a final test and merge.

2021-05-06 08:17 UTC, jasmussen approved these changes
Very nice, thanks for your work. This is before:

![before](https://user-images.githubusercontent.com/1204802/117265196-44d18600-ae54-11eb-83a8-eb0cd91c9766.gif)

This is after:

![after](https://user-images.githubusercontent.com/1204802/117265212-47cc7680-ae54-11eb-80b1-1c3810728807.gif)

2021-05-10 16:34 UTC, devfle commented
I have rebased the branch and now are all Checks green. Can we merge this :) ?

2021-05-10 16:35 UTC, merged

2021-05-10 16:35 UTC, jasmussen commented
Thank you!