Fix submenu hover issue.
WordPress/gutenberg pull request #31195
Opened 2021-04-26 13:41 UTC by jasmussen

## Description

This is a small followup to #30805, which refactored navigation menu margins and paddings. Turned out that margins weren't a good choice for submenu items:

![before](https://user-images.githubusercontent.com/1204802/116092086-cc293780-a6a5-11eb-8e92-79393ea2d967.gif)

This PR realizes that mistake, and that submenus since they're already inside a box, can be spaced with paddings instead of margins, and look the same, and so it does just that, also fixing the hover issue:

![after](https://user-images.githubusercontent.com/1204802/116092165-dc411700-a6a5-11eb-949d-4dc81da3be70.gif)

## How has this been tested?

Test a navigation menu with no background, then hover submenus.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-04-27 09:31 UTC, getdave requested changes
I tested this and I saw:

* Hover issue is now fixed.
* Menu items still have _very_ large spacing around them.


https://user-images.githubusercontent.com/444434/116219561-a94d6080-a743-11eb-88ab-6bdbbc38efbd.mp4



I think the issue with the spacing is that each item has x2 padding applied:

1. Padding on the `<li>`
2. Padding on the `<a>`.

This doesn't match up with your preview so I assume this is either Theme related or it's a bug. I was using TT1 (standard edition).



**Unrelated**: I found the cursor changing between text selection and pointer as I mouse between different menu items to be rather "noisy". I wonder whether having it remain as "pointer" and then only once the menu item is active would it change to text selection cursor?

2021-04-27 09:31 UTC, getdave commented on packages/block-library/src/navigation-link/style.scss
> +	// Margins in all submenus.
Is it margins now or just "spacing"?

2021-04-27 11:16 UTC, jasmussen commented
Excellent review, thank you, let me take a stab.

> Unrelated: I found the cursor changing between text selection and pointer as I mouse between different menu items to be rather "noisy". I wonder whether having it remain as "pointer" and then only once the menu item is active would it change to text selection cursor?

Can you elaborate on this one? Do you mean when the mouse goes from menu item block to space between blocks to menu item block again? 

Or are you referring to the fact that the editable field of a completed menu item invokes the text selection cursor when hovered? 

If the latter, I think that's an issue that is important to look at separately, as it potentially affects all blocks, including Buttons.

2021-04-27 11:39 UTC, jasmussen commented
Great catch, thank you. Weird how that surfaced here, but should be fixed:

![menu](https://user-images.githubusercontent.com/1204802/116235268-ee7e8c00-a75d-11eb-920d-36027b580cdb.gif)

2021-04-27 14:09 UTC, getdave commented
> Or are you referring to the fact that the editable field of a completed menu item invokes the text selection cursor when hovered?
> 
> If the latter, I think that's an issue that is important to look at separately, as it potentially affects all blocks, including Buttons.

This 👍 and definitely not one for this PR.

As you move your cursor over a `core/navigation-link`, at the point where it hits the text, it changes from a `pointer` cursor to a "text editing/selection" cursor. I feel like it should be

1. Click to select block
2. See cursor to make editable.

I might be wrong though because that might break the "make it obvious it's directly editable" paradigm. I just felt it was a little jarring seeing the cursor change all the time.

2021-04-27 14:20 UTC, getdave submitted a review, later dismissed
Sorry to say but it looks like we might now be in a worse situation because now the margins that apply to `[data-block]` are being inherited on the `core/navigation-link` block and causing huge gaps.

<img width="1454" alt="Screen Shot 2021-04-27 at 15 18 24" src="https://user-images.githubusercontent.com/444434/116257507-04934900-a76c-11eb-8833-6ee8cf391671.png">

I'm not sure what Theme you are on but I'm on latest TT1 that comes with the `wp-env` environment.

2021-04-28 08:03 UTC, jasmussen commented
Oh no! Ack, that's TT1 doing it wrong, meaning I need to override and strengthen the CSS rules. Thanks for the reproduction steps, will push a fix.

2021-04-28 09:02 UTC, jasmussen commented
Alright, what a headache, but thanks again for testing and helping me catch this. The original approach, give or take, worked reasonably well for normal block themes which don't excessivley style the canvas:

![normal themes](https://user-images.githubusercontent.com/1204802/116376939-019e6400-a811-11eb-86f8-1711d2f63143.gif)

But TT1, the non block version as you were testing in, was severely broken:

![tt1 before](https://user-images.githubusercontent.com/1204802/116376974-09f69f00-a811-11eb-8cf9-831359902534.gif)

The problem appears to be that TT1 styles the inner padding of menu items using a CSS variable and high specificity. But it does so based on older markup, is unaware of the Page List block, and it does so with a smaller menu item hit area. In https://github.com/WordPress/gutenberg/pull/31195/commits/5a5bcbbb2913b32cf24ed3137b3d861b0476c5ab, I added CSS to explicitly override that:

![tt1 after](https://user-images.githubusercontent.com/1204802/116377152-301c3f00-a811-11eb-9f4e-495cca27d0b4.gif)

I believe we should be good now, and it's almost even more important to land a fix soon, AND to test in a wide range of themes, including both normal and block themes.

2021-04-28 12:20 UTC, vdwijngaert approved these changes
My stomach turns when hearing "high specificity", but this appears to be the most elegant way of handling it. Tested on TT1 & TT1 Blocks, works fine.

2021-04-28 12:26 UTC, jasmussen commented
Thanks so much!

@getdave does it address your change requests?

2021-04-28 13:52 UTC, jasmussen commented
I think Dave is AFK today. @georgeh my friend, if you have time to test this one with TwentyTwentyOne and provide a thumbs up, I think two green sanity checks would provide a nice context for dismissing Dave's review, so we can land this one before the plugin gets built later today.

2021-04-28 14:00 UTC, georgeh approved these changes
I was able to repro the issue in trunk and confirmed that this fixes the submenu hover issue. LGTM

2021-04-28 14:03 UTC, jasmussen commented
Thanks for the reviews, Dave, Koen and George. I will land this one so we can build a stable plugin, and I will be on the lookout for any followups I need to address.

2021-04-28 14:03 UTC, merged