Navigation Screen: warn the user about unsaved changes
WordPress/gutenberg pull request #31197
Opened 2021-04-26 13:49 UTC by Mamaduka

## Description
Adds warning for users that they will lose unsaved data when navigating away.

See #30322.
Closes #30423.

## How has this been tested?
1. Got to the experimental navigation screen.
2. Change menu name.
3. New warning prompt should appear when navigating away without saving changes.

## Screenshots 
https://user-images.githubusercontent.com/240569/116092388-d273df80-a6b6-11eb-94f6-b2a0d2b01199.mp4

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-05-04 11:37 UTC, getdave requested changes
Nice work here. The concept is great but for some reason the dirty detection seems off in the Core Store.

As you can see below, I make changes and click `Save` and then try to navigate away and it still thinks there are dirty changes.

https://user-images.githubusercontent.com/444434/116997894-53ddfa00-acd5-11eb-9ba0-00cd500102de.mov

Also once this is working, we need to add e2e tests to avoid regressions.

2021-05-04 12:13 UTC, Mamaduka commented
Thanks for the review, @getdave

I'm aware of this issue but not sure what's the best way to fix it. My best guess is that it happens because we're using AJAX.

The same issue affects my other PR https://github.com/WordPress/gutenberg/pull/31119#issue-621863251.

2021-05-05 11:56 UTC, getdave commented
> I'm aware of this issue but not sure what's the best way to fix it

Could you bring it up in open floor of Core Editor chat to see if folks are aware of the Issue?

2021-05-05 14:02 UTC, Mamaduka commented
I did a little more research. I think the state stays "dirty" because of the stub navigation post. See `getNavigationPostForMenu` selector and resolver.

Based on the selector comment, this record - "should only exist on runtime and should never be saved." While this works fine, changes to the record aren't removed from the edited state when saving the menu.

I'm not familiar with this part of the code and unsure of the best next step.

2021-05-06 02:31 UTC, talldan commented
> While this works fine, changes to the record aren't removed from the edited state when saving the menu.

That makes sense. I guess one way would be to simulate the way that saving clears the dirty state.

I wonder how `saveEntityRecord` achieves that:
https://github.com/WordPress/gutenberg/blob/trunk/packages/core-data/src/actions.js#L362

2021-05-06 02:38 UTC, talldan commented
Or I guess it might also be possible to ignore the stub post in the `__experimentalGetDirtyEntityRecords` result, and use a different system for detecting changes to the stub post, but I think it might be beneficial to use the entity system so that undo/redo work as expected.

2021-05-06 06:50 UTC, Mamaduka commented
> Or I guess it might also be possible to ignore the stub post in the __experimentalGetDirtyEntityRecords result

I had the same idea to check edited records for the `menu` store, but that gives us false positives if saving menu items via AJAX fails for some reason.

Looking at the `saveEntityRecords`, I think `receiveEntityRecords` might do the trick. I need to figure out the right arguments.

2021-05-12 06:14 UTC, Mamaduka commented
I was able to resolve the issue — PR #31735.

2021-05-12 14:40 UTC, getdave commented
> #31735

✅ Approved. Let's rebase here and I'll happily re-test for you.

2021-05-12 15:23 UTC, Mamaduka commented
Rebased branch, and it's ready for re-testing.

2021-05-13 09:01 UTC, Mamaduka commented
@getdave I added some basic e2e tests for warning dialog as we discussed.

2021-05-13 10:42 UTC, getdave approved these changes

2021-05-13 10:43 UTC, getdave commented
Great work here @Mamaduka. Everything is working really nicely and the addition of e2e tests should avoid any further issues with dirty state and saving. :shipit:

2021-05-13 10:44 UTC, merged

2021-05-13 11:59 UTC, paaljoachim commented
Associated issue:
As work is happened here around unsaved changes. It would be great to continue onward to:
**Improving multi-entity saving UI method.** (Linked to my comment.)
https://github.com/WordPress/gutenberg/issues/31456#issuecomment-833555791

- Adding a ellipsis drop down menu containing a "Select Template" and a "Discard Changes" options.
- Adding advice on how to proceed with the PR as in code that needs to be added would be helpful.