Autocomplete: Implement and use focus outside utility for managing dismissal
WordPress/gutenberg pull request #3235
Opened 2017-10-30 13:58 UTC by aduth

Fixes #2669
Related: #3174, #2974

This pull request seeks to improve the behavior of Autocomplete close, resolving an issue where block selection on touch devices does not work correctly. Specifically this resolves an issue iOS devices in the current implementation to test where focus has shifted, `relatedTarget` is the popover contents itself (`.components-popover__content`).

These changes include a new `withFocusOutside` higher-order component similar to the one suggested in #2974 to help encapsulate logic of testing whether a blur really causes focus to leave an element. This is meant to help in two ways:

- A blur event's `relatedTarget` is not reliable in IE11 ([CodePen](https://codepen.io/aduth/pen/GOgyZb), https://github.com/facebook/react/issues/3751, https://github.com/facebook/react/issues/6410)
- [Portal](https://reactjs.org/docs/portals.html) content may be rendered elsewhere in the DOM, so testing `relatedTarget` with `Element#contains` is not always reliable. As implemented here and leveraging [portal event bubbling behavior](https://reactjs.org/docs/portals.html#event-bubbling-through-portals), `withFocusOutside` will account for focus shifting into portaled content.

__Testing instructions:__

Repeat testing instructions from #3174, also confirming selection on a touch device (e.g. XCode iOS simulator).

Verify that there are no regressions in clicking or tabbing outside of the paragraph field while an autocomplete suggestions list is open.

2017-10-30 19:43 UTC, ephox-mogran commented
This is so similar to our first iteration of #2948. I see you're going with the `setTimeout` solution, rather than the `focusin` on the document (like how `react-click-outside` works). I think focusin for the document may not detect when we try to focus something not in the DOM (or not focusable) and it defaults to `body`, so it's probably for the best.

2017-10-30 19:56 UTC, aduth commented
>This is so similar to our first iteration of #2948.

Yes, h/t could have been more explicit, but #2974 was mentioned as inspiration here. 👍

2017-10-30 20:06 UTC, ephox-mogran commented
No problem at all. Your solution for that issue was a lot nicer than this approach for that issue would have been.

2017-11-07 19:32 UTC, aduth commented
Rebased with consideration of #2896. @EphoxJames could you give this one a look over given updates to the Autocomplete?

2017-11-08 00:55 UTC, BoardJames requested changes
Clicking in a different part of the paragraph block does not close the popup. I suggest keeping the onClose handler for Popover though you could also just detect any clicks that aren't on the popover.

2017-11-08 18:14 UTC, aduth commented
Good call @EphoxJames , ideally we'd not need both the click-outside detection of the popover and the focus-outside detection of the autocomplete component, but since the popover never truly receives focus it would appear we unfortunately do need to handle both.

2017-11-09 00:26 UTC, BoardJames approved these changes

2017-11-09 15:22 UTC, merged