Increase external media link input width, and increase top value of globe icon
WordPress/gutenberg pull request #32667
Opened 2021-06-14 14:45 UTC by tjcafferkey

Fixes https://github.com/WordPress/gutenberg/issues/32249

## Description

* Increase the width of the external media input element
* Increase top value of globe icon

## How has this been tested?

* Create a new post or edit an existing post
* Add "Image" block and select "Insert from URL" option
* Enter an image URL
* Click "Edit" to edit the URL. Box should expand to make the input more usable.

## Screenshots 

<table>
<tr>
	<td>Before</td>
	<td>After</td>
</tr>
<tr>
	<td>
![external-media-before](https://user-images.githubusercontent.com/8639742/121911095-56e1f680-cd27-11eb-9ae2-9c5f85a0f2b9.gif)
</td>
	<td>
![external-media-after](https://user-images.githubusercontent.com/8639742/121911127-606b5e80-cd27-11eb-8e82-9d63d83c6513.gif)
</td>
</tr>
</table>

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-06-15 07:44 UTC, tjcafferkey commented
Failing E2E tests appear unrelated? Is there any way I can restart these?

2021-07-23 13:24 UTC, tjcafferkey commented
>Failing E2E tests appear unrelated? Is there any way I can restart these?

cc @getdave

2021-07-23 15:14 UTC, getdave commented
Yep. Click on failing test details link. Then click restart tests.

2021-07-30 08:38 UTC, getdave requested changes
Thanks for looking into fix this. Being able to see the full URL when in "edit" mode is very important.

Unfortunately whilst this works well on larger screens, on smaller viewports there appears to be a severe bug whereby the modal visually "vibrates".

https://user-images.githubusercontent.com/444434/127626375-20a3f551-2045-4250-b594-18b2bb0a2831.mp4

This appears to be due to some circular logic in the JS which causes a `style` attribute to be repeatedly set/unset.

![Screen Capture on 2021-07-30 at 09-37-47](https://user-images.githubusercontent.com/444434/127626205-5510ae73-9b76-4fe9-850a-bf7db43f3dbf.gif)

If we can find a way to resolve that then we'll be in a good place. I think maybe it's the `min-width` you've set on the `.block-editor-link-control__search-input` which you'll need to apply (using a progressive enhancement approach) _only_ on larger viewports.

2021-07-30 08:38 UTC, getdave commented on packages/block-editor/src/components/media-replace-flow/style.scss
> +		}
<img width="919" alt="Screen Shot 2021-07-30 at 09 28 06" src="https://user-images.githubusercontent.com/444434/127624981-5bb758c7-6ec7-4e50-86a3-384796e79403.png">

Not sure this is necessary any longer as I was unable to replicate. I merged a PR recently which sorted out all this globe icon alignment so hopefully that's done it.

2021-08-13 10:30 UTC, getdave commented
@tjcafferkey Anything I can do to help this along?

2021-08-13 13:15 UTC, tjcafferkey commented
Sorry @getdave I have been AFK for a few weeks. I will be picking this back up. Thanks for checking in though.

2021-10-04 08:10 UTC, getdave commented
@tjcafferkey How's this PR coming along? Can I help at all?

2023-08-10 07:22 UTC, closed without merging