Workflows: Allow point releases after a new RC is out
WordPress/gutenberg pull request #32821
Opened 2021-06-18 15:35 UTC by ockham

## Description

Re-enable manually triggered workflows on forks, to allow for better testability of changes to those workflows.

See https://github.com/WordPress/gutenberg/pull/32114#issuecomment-864013314 for background.

Based on https://github.com/WordPress/gutenberg/pull/32560; mostly since I hope to merge that PR soon and was too lazy to rebase.

## How has this been tested?

Fork GB, and try running release creation on your fork (using this branch). It's what I did to test https://github.com/WordPress/gutenberg/pull/32560, so see the links to GHA workflows on my fork under the "How has this been tested?" section of that PR 😬

2021-06-23 18:07 UTC, desrosj requested changes
It seems like with the other recent changes made elsewhere, the first job in this workflow will always run regardless of where the run is being requested. I think we'll need to revise this a bit to account for that.

I think that `compute-stable-branch` could check for the WordPress/Gutenberg repository. I don't know if there's any benefit for allowing this to run on forks.

2021-06-23 21:28 UTC, ockham commented
> It seems like with the other recent changes made elsewhere, the first job in this workflow will always run regardless of where the run is being requested. I think we'll need to revise this a bit to account for that.

Thanks @desrosj, good spot -- I forgot about the newly added step when rebasing 😅 
 
> I think that `compute-stable-branch` could check for the WordPress/Gutenberg repository. I don't know if there's any benefit for allowing this to run on forks.

It's required for the manually triggered workflow (to select the release branches from which we allow publishing a release, per #32560). For that reason, I'd like to be able to run it on forks also -- otherwise, we won't be able to test this workflow on forks once again 😅 

I'll guard with a `github.event_name == 'workflow_dispatch'` check, as for the other steps. That way, it'll only be run when triggered manually (but not on PR creation, or pushing a commit).

2021-06-23 21:31 UTC, ockham commented
> I'll guard with a `github.event_name == 'workflow_dispatch'` check, as for the other steps. That way, it'll only be run when triggered manually (but not on PR creation, or pushing a commit).

d3a6583

2021-07-06 21:18 UTC, ockham commented
@desrosj Would you mind giving this another quick look? 😊 🙏

2021-07-07 13:25 UTC, desrosj approved these changes
This looks good!

My only question is around `compute-stable-branches` only running on `workflow_dispatch`. Is this correct? I guess I assumed that the version bumps and packaging happened automatically when tagging/releases occurred.

2021-07-07 14:30 UTC, ockham commented
> This looks good!

Thank you! 🎉 
 
> My only question is around `compute-stable-branches` only running on `workflow_dispatch`. Is this correct?

Yep! 👍 

> I guess I assumed that the version bumps and packaging happened automatically when tagging/releases occurred.

We were considering that kind of flow at some point, but decided for the current flow instead: The release is triggered manually, the workflow creates the version bump commit, builds the plugin, and attaches it as an asset to a release draft. The tag is only created by GH once the release is published. (That's more of a GH feature than a GH Actions one; it's possible to specify a tag that doesn't exist yet in a release draft, and GH will happily create it for the given ref when the release is published).

2021-07-07 15:30 UTC, merged