Added janw-me to the Codeowners for the PHP FSE folder.
WordPress/gutenberg pull request #32990
Opened 2021-06-25 13:29 UTC by janw-me

I'd like to get the updates for this folders.
I apologize if this is the wrong approach.

2021-08-25 18:32 UTC, priethor requested changes
Hi @janw-me !

This would be one way of getting notifications, although you would also get added as a reviewer on every PR that affects files in that folder.

As an alternative, if you are only interested in getting notifications once changes to that folder happen in `trunk`, there's also the possibility of setting up an RSS feed with the following URL:
`https://github.com/WordPress/gutenberg/commits/trunk/lib/full-site-editing.atom`

However, in case you do want to be added to the code owners, I left a review to address the changes.

2021-08-25 18:32 UTC, priethor commented on .github/CODEOWNERS
> +/lib/full-site-editing                          @timothybjabocs @spacedmonkey @janw-me
Should `@spacedmonkey` and `@timothybjacbos` also be added as code owners? As far as I understand from your request, you should be the only one added, isn't that so?

2021-08-26 13:06 UTC, janw-me commented
Hi @priethor

Thank you for the atom feed. That's quite usefull.
But if it's allowed I'd like to be pinged before it's merged.

2021-08-26 13:08 UTC, janw-me commented on .github/CODEOWNERS
> +/lib/full-site-editing                          @timothybjabocs @spacedmonkey @janw-me
Yes, I only should be enough. I can't remember why I added the others :thinking:
I pushed a commit to fix this.

2021-08-26 14:36 UTC, priethor approved these changes

2021-08-26 14:37 UTC, merged