Fixed column count problem when removing an image from gallery
WordPress/gutenberg pull request #3300
Opened 2017-11-01 22:25 UTC by jorgefilipecosta

Aims to close https://github.com/WordPress/gutenberg/issues/3274.
When removing an image from the gallery if the number of images becomes less than the number of columns, the number of columns was not updating. This is inconsistent because we set the maximum number of columns allowed to the number of images.

## Before
![nov-01-2017 22-23-36](https://user-images.githubusercontent.com/11271197/32300872-6249fde6-bf53-11e7-8183-07f93e88e967.gif)

## After
![nov-01-2017 22-23-22](https://user-images.githubusercontent.com/11271197/32300894-7febc33e-bf53-11e7-8aec-84fd072682ac.gif)

2017-11-01 23:29 UTC, Soean commented
Thanks @jorgefilipecosta this PR works well and fixes the bug I described in #3274.

2017-11-02 00:00 UTC, aduth requested changes
There's an issue here. The `columns` attribute does not have a default value, so unless the user first explicitly chooses a column value before removing an image from the gallery, a value of `NaN` will be assigned as the `columns` attribute, since:

```js
isNaN( Math.min( 2, undefined ) ) === true;
```

2017-11-02 00:34 UTC, jorgefilipecosta commented
Hi @aduth, thank you for your review and catching this problem. You are right the default value displayed in the slider is not set in the attributes it is computed before passing it to the slider, so no default value exists on the attribute. I added a safety check for this case.

2017-11-02 00:39 UTC, aduth commented
Should we just assign a default value for `columns` ?

2017-11-02 00:52 UTC, jorgefilipecosta commented
Not certain if a static default value is good for this case. If no attribute is set we use the minimum of 3 and the number of images. So if we have two images default is two if we have three images default is three. If the user never used the slider to set a value and we had two images and then we add a new image, default value passes automatically from two to three. If we use a static default value we lose this feature.

2017-11-02 15:10 UTC, aduth approved these changes
>If no attribute is set we use the minimum of 3 and the number of images.

Okay, I wasn't too familiar with this existing behavior. In that case, and since we're respecting this after removing an image, this looks good 👍

2017-11-02 22:52 UTC, merged

2017-11-02 22:53 UTC, jorgefilipecosta commented
Thank you @aduth it was merged :)