I18n: Make preview popup loader strings translateable
WordPress/gutenberg pull request #3301
Opened 2017-11-01 23:56 UTC by Soean

## Description
Adds translate functions to the text strings in the preview popup loader.

2017-11-02 12:13 UTC, aduth commented on editor/header/preview-button/index.js
> +				<p>${ __( 'Please wait&hellip;' ) }</p>
Unlike with React, we don't get string escaping for free here, so there is a potential risk with inserting this into raw markup.

https://codex.wordpress.org/I18n_for_WordPress_Developers#HTML

We may need to consider patterns for sanitization.

2017-11-02 17:56 UTC, aduth commented on editor/header/preview-button/index.js
> +				<p>${ __( 'Please wait&hellip;' ) }</p>
Related: https://github.com/WordPress/packages/pull/12

2018-03-06 18:58 UTC, aduth requested changes
@Soean Are you able to revisit this one? Should we just close it?

2018-03-06 18:58 UTC, aduth commented on editor/header/preview-button/index.js
> +				<p>${ __( 'Please wait&hellip;' ) }</p>
We could also generate this with `wp.element.renderToStaticMarkup` as an element.

Or just [Lodash `_.escape`](https://lodash.com/docs/4.17.5#escape)

2018-07-05 13:22 UTC, tofumatt commented
Looks like this PR has got stale, so closing it for now. If you can revisit it feel free to re-open this PR or open a new PR.

2018-07-05 13:22 UTC, closed without merging

2018-07-05 13:35 UTC, tofumatt commented
Closed this but filed #7725 to track this issue.