Prevent entering invalid values in the Query Loop block config
WordPress/gutenberg pull request #33285
Opened 2021-07-08 11:51 UTC by youknowriad

closes #33270 

Right now, you can enter `0` in the Query Loop per page config which will result in an infinite loop breaking the block.
This PR fixes that by adding some validation to the Query Loop Config inputs.

This more a stop gap fix for 5.8. I think a better solution would be to do that validation automatically in the `NumberControl` component. I tried this quickly but felt a bit impactful for 5.8 given how complex that component looks (not sure if that complexity is needed tbh) so I think I'd rather leave this for our components devs if you all have time, what do you think @ciampo @sarayourfriend. 

**Testing instructions**

 - Insert a query loop block
 - pick a variation
 - click the "Display settings" button in the toolbar and change the settings and try putting 0 I n the "items per page".
 - No error is displayed and the value reverts when you focus out of the input.

2021-07-08 12:06 UTC, ntsekouras approved these changes
Let's go with this one that checks other inputs as well. Although the crashing comes only from `perPage` due to the logic for initial setup of this attributes, which should be handled better in [this issue](https://github.com/WordPress/gutenberg/issues/30369).

Thanks Riad

2021-07-08 13:56 UTC, sarayourfriend requested changes
To match the HTML API, the min and max should be inclusive of the validated value, not exclusive as you have it here.

Demo here: https://codesandbox.io/s/empty-platform-h2qvj?file=/src/App.js

Also I created an issue to add a baseline validation based on the `min/max` props: https://github.com/WordPress/gutenberg/issues/33291

2021-07-08 14:07 UTC, youknowriad commented
I think they are inclusive in this PR (unless I'm misunderstanding). The codepen link seems wrong.

2021-07-08 14:16 UTC, sarayourfriend approved these changes
I'm sorry, I misread the code, you already have it as inclusive of the min and max, never mind, LGTM!

2021-07-08 15:48 UTC, sarayourfriend commented
It seems like the `NumberControl` is already meant to support this validation:

https://github.com/WordPress/gutenberg/blob/dacdf41926254ca11f592e204d6c7307d4641d75/packages/components/src/number-control/test/index.js#L68-L96

2021-07-09 11:02 UTC, youknowriad commented
@sarayourfriend interesting! even in keydown (which I didn't experience) it sounds weird/wrong to me, what if the limit is 100 < x < 200 and I type something like `1` in the input, it should allow me to finish my number even if `1` is inferior to 100.

For 5.8, I'm going to land this stop gap solution and we should fix this properly in #33291.

2021-07-09 13:00 UTC, sarayourfriend commented
> even in keydown (which I didn't experience) it sounds weird/wrong to me

Oh it's only on the Enter key down, not _any_ key down. So you can finish your number being input for sure, but when you hit enter it will "clamp" the value.

It even seems like it's meant to do the same thing on blur as well: 


https://github.com/WordPress/gutenberg/blob/ad0cc77c85a16a45b33a1d3855a15a0207beb34e/packages/components/src/input-control/input-field.js#L92-L109

Notice how it calls `handleOnCommit` which in turn "commits" the value, causing the NumberControl's reducer to kick in and do the clamping. But it only does this when `isPressEnterToChange` is true, which is counter intuitive to me. Perhaps that's where the bug is?

In any case, this will take some digging to discover the correct solution to it. It doesn't seem like it should take much new code to fix this problem.

2021-07-12 09:38 UTC, merged