Query Pagination: do not render pagination container if there's no pagination
WordPress/gutenberg pull request #33635
Opened 2021-07-22 20:56 UTC by jffng

## Description
This PR adds a render callback to the query pagination block. This way, the pagination container element is only rendered if pagination exists.

I think rendering an empty container in most cases is harmless, but is it better to actually not add anything to the DOM if there isn't content present? 

This is an attempt to solve https://github.com/Automattic/themes/issues/4268 where we style the wrapper only when pagination is present.

## How has this been tested?
1. Create a post or index template with the following query block markup on a site with fewer than five posts:

2. 
```

<main class="wp-block-query">
	
		
		
		
		
	
	
	
	
	
	
</main>

``` 

2. Verify that no pagination container is rendered 
3. Verify relevant block attributes ("wide" in the above example) are present on the wrapper

## Screenshots 

## Types of changes
Bug fix? 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-07-22 21:02 UTC, jffng commented on packages/block-library/src/query-pagination/index.php
> +	if ( empty( $content ) || ctype_space( $content ) ) {
For some reason the `$content` is a long string of whitespace when it's empty, so I added the `ctype_space` condition.

2021-08-13 08:34 UTC, scruffian commented
The problem I am seeing with this is that when the block has already been saved it contains content like this:

```<div class="wp-block-query-pagination alignwide"> </div>```

Do we need to check for $content at all, or can we always just do a server rendering?

2021-08-13 13:24 UTC, jffng commented
I see what you mean. But if we don't check $content, how else could we avoid rendering an empty container?

2021-08-13 13:35 UTC, scruffian commented
Hmm. I guess the alternative is to check for `<div class="wp-block-query-pagination alignwide"> </div>`

2021-08-25 09:22 UTC, scruffian commented
Thinking about this some more, I think it's good. If won't deal with blocks that have already been saved, but it will work for new blocks.

2021-08-25 09:22 UTC, scruffian approved these changes

2021-09-07 09:30 UTC, Mamaduka requested changes
Hi, @jffng

I think this change will require deprecation as well and maybe test/snapshot updates.

PR also fixes #30522.

2021-09-28 18:47 UTC, jffng commented
Closing in favor of #35092

2021-09-28 18:47 UTC, closed without merging