Block Styles: Fix long strings of text without spaces overflow the block
WordPress/gutenberg pull request #34222
Opened 2021-08-23 08:16 UTC by arthur791004

## Description

Currently, some of the themes set the `word-break: break-word;` or `overflow-wrap: break-word;` css to the heading block or paragraph block. For example, `Independent Publisher 2` sets `word-break: break-word` [here](https://github.com/Automattic/themes/blob/1ca042362f230f0169732d36fec2115179420acb/independent-publisher-2/style.css#L1191) to `.entry-content` and heading and paragraph inherit that property. However, some of the themes (Twenty Twenty-One, Blank Canvas and so on) don't set that property so that the multi-line strings without spaces make the pages broken and generate the horizontal scrollbar on mobile devices.

## How has this been tested?

1. Create or Edit a post
2. Insert the following blocks
   * multi-line strings without spaces as heading
   * multi-line strings without spaces as paragraph 
   * multi-line strings without spaces as heading or paragraph inside cover block
3. Open Chrome Developer Tools and change to mobile view
4. Check the multi-line strings break the page and generate horizontal scrollbar or not

## Screenshots 

| Before | After |
| - | - |
| <img width="300" src="https://user-images.githubusercontent.com/13596067/130409908-dad47ed2-e33f-44b5-a4af-77c241bdbcec.png" /> | <img width="300" src="https://user-images.githubusercontent.com/13596067/130409963-33c95c17-4ac8-41da-9df0-55c2cc0a553d.png" /> |

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-08-23 23:35 UTC, roo2 commented
@arthur791004 one of the automated checks flagged https://github.com/WordPress/gutenberg/pull/34222/files#diff-3721697b4de86118e261dd67207c3022a76cb2882ed34fea6de180206c427601

It looks like the difference is actually line breaks in the returned string, I wonder if the css is actually loaded by the tests and having this effect

2021-08-24 01:08 UTC, roo2 commented
I tested this locally with a8c-wp-env and found that twenty-twentyone and blank canvas weren't demonstrating the issue.

The rule affecting the `.block-editor-block-list__layout .block-editor-block-list__block` was giving them correct wrapping
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-list/style.scss#L123
```
.block-editor-block-list__layout .block-editor-block-list__block {
    position: relative;
    overflow-wrap: break-word;
}

```

Do you have more specific repro instructions?

2021-08-24 01:09 UTC, roo2 commented
original issue: https://github.com/Automattic/wp-calypso/issues/51249

2021-08-24 02:40 UTC, arthur791004 commented
@roo2 Oops...I'm sorry for that I forgot to say that the problem only happens when you **view** the post 😅

2021-08-24 20:56 UTC, roo2 commented
> only happens when you view the post
Ahh of course! sorry I missed that. I can reproduce the issue with Headings on the live site but not in the editor, with or without the cover block.
<img width="330" alt="Screen Shot 2021-08-25 at 6 54 18 am" src="https://user-images.githubusercontent.com/22446385/130688589-8132d1ab-6195-4ac9-bb50-1d5b7c5668f6.png">

2021-08-24 21:14 UTC, roo2 commented
I found that the issue also affects very long links in lists
1. Add a list element
2. Add a very long unbroken link
3. View in preview/live site on mobile 

<img width="325" alt="Screen Shot 2021-08-25 at 7 12 26 am" src="https://user-images.githubusercontent.com/22446385/130690791-76f7a21d-cfcb-4c4f-b6bf-f01c1417d62b.png">

2021-08-25 03:50 UTC, arthur791004 commented
@roo2 Good catch 👍  I also tested the list before but I found that it works well because I wrap the string into paragraph 😅
I fix the problem in the list, thank you!

2021-08-27 03:40 UTC, roo2 requested changes
While we're here, there's one more fix we can make. The `Quote` and `Pullquote` block both have "Citation" fields, which are currently not wrapping.

<img width="468" alt="Screen Shot 2021-08-27 at 1 09 39 pm" src="https://user-images.githubusercontent.com/22446385/131065954-861fba6e-f1bf-43f2-84d1-cb56d066dca7.png">

I tested in Chrome Safari and Firefox and can't find any other blocks that need this fix

2021-08-27 03:40 UTC, roo2 commented on packages/block-library/src/button/style.scss
> +	word-break: break-word; // overflow-wrap doesn't work well if a link is wrapped in the div, so use word-break here.
I tested that buttons needs `word-break` in order to wrap correctly wheras headings will wrap with `overflow-wrap` alone (Tested in Chrome). 👍 

But I couldn't work out why this is the case. I think that the comment is good for this interesting case. 👍

2021-08-27 08:03 UTC, arthur791004 commented
> While we're here, there's one more fix we can make. The Quote and Pullquote block both have "Citation" fields, which are currently not wrapping.

Good catch 👍  I've fixed it, thank you!

![image](https://user-images.githubusercontent.com/13596067/131094182-fc102a72-1522-4d99-81cb-a4038eb8446b.png)

2021-09-02 04:59 UTC, kevin940726 approved these changes
LGTM 👍. Tested with headings in twentytwentyone. Though I don't know if it has any other side effects.

I'd say let's merge it and observe the impacts in prod.

2021-09-02 05:06 UTC, merged

2022-01-14 20:10 UTC, benbreedlove commented
Hey, so sorry to bring this back up, I only just ran into the changes from this branch last week. I wanted to check that you did precisely what you wanted to, here. Changing the default behaviors of all headers, lists, and paragraphs from W3C recommendations is possibly a larger change than you meant to make. Particularly I'm looking at the selectors that target `p`, `h1` through `h6`, `ol` and `ul` globally. Did you perhaps mean for those items to be more particularly targeted? Thanks for your time.

2022-02-10 13:40 UTC, JakePT commented
I just ran into an issue caused by this change. This was on a theme that has not adopted FSE or anything like that, so this really seems like an overstep to me, to make this decision on behalf of all themes and affect global styles like this.

2022-02-11 12:51 UTC, arthur791004 commented
@JakePT Do you have the steps to reproduce your issue?

2022-02-14 04:56 UTC, JakePT commented
@arthur791004 Well the issue was just that the theme's CSS did not have `overflow-wrap: break-word;` on it before the update, and after the update it did. 

This particulate site had some large text on desktop in a div that was slightly too small. This wasn't a problem because the text just overflowed a little bit and displayed fine, but after the update the words were broken so that the text could wrap. This looked much much worse.

This change doesn't just affect headings that run out of space on mobile, it affects all headings at all times, including on desktop where text overflowing does not automatically mean that the text is being cropped.

2022-03-28 21:04 UTC, yaronuliel commented
Agreeing with @JakePT , the css rules apply to global tags `h1, h2, h3, h4, h5, h6` and `p` - and affect nodes that has nothing to do with blocks.
Generally speaking, a library shouldn't apply rules that affect elements beyond the scope of the library. I had a site affected by it in production after upgrading WordPress version

2022-03-29 09:48 UTC, arthur791004 commented
I'm sorry for the late reply. I totally agree with you all that I should not change the default behavior for p, h1 through h6, ol and ul. I'll revert the change for those elements.