Update overall plugin description
WordPress/gutenberg pull request #34850
Opened 2021-09-15 16:44 UTC by annezazu

## Description
This is an update to the overall plugin description to do the following:
- Ensure the content is up to date (correct phases, links to 2020 items, adjust descriptions in light of FSE etc).
- Add in more context and helpful hints around when you need to use the plugin to better direct folks.
- Add in extra links to make it easier to get involved with contributing and staying up to date.
- Clean up the language to make it a bit simpler.

If anyone has any suggestions for links to add under "where can I learn more", please share! 

## How has this been tested?

## Screenshots 

## Types of changes

Enhancement

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-09-16 12:07 UTC, aristath requested changes

2021-09-16 12:07 UTC, aristath commented on readme.txt
> +The block editor first became available in December 2018, and we’re always hard at work refining the experience, creating more and better blocks, and laying the groundwork for the future phases of wo
Suggestion for minor tweaks. English is not my native tongue but I feel this reads a bit better. I'll leave it to the native speakers though :+1: 
```suggestion
The block editor first became available in December 2018. We’re always hard at work refining the experience, creating more and better blocks, and laying the groundwork for the future phases of work. Each WordPress release comes ready to go with the stable features from multiple versions of the Gutenberg plugin, so you don’t need to use the plugin to benefit from the work being done here. However, if you’re more adventurous and tech-savvy, the Gutenberg plugin gives you the latest and greatest, so you can join us in testing bleeding-edge features, start playing with blocks, and maybe get inspired to build your own.
```

2021-09-16 12:07 UTC, aristath commented on readme.txt
> +- **User Documentation:** Review the <a href="https://wordpress.org/support/article/wordpress-editor/">WordPress Editor documentation</a> for detailed docs on using the editor as an author to create
```suggestion
- **User Documentation:** Review the <a href="https://wordpress.org/support/article/wordpress-editor/">WordPress Editor documentation</a> for detailed instructions on using the editor as an author to create posts, pages, and more.
```

"docs" feels weird to me because it follows the "documentation" text in the link. Would "instructions" be suitable?

2021-09-16 12:07 UTC, aristath commented on readme.txt
> +The development hub for the Gutenberg project can be found at: https://github.com/wordpress/gutenberg Discussions for the project are on the <a href="https://make.wordpress.org/core/">Make Core Blog<
```suggestion
The development hub for the Gutenberg project can be found at <a href="https://github.com/wordpress/gutenberg">https://github.com/wordpress/gutenberg</a>. Discussions for the project are on the <a href="https://make.wordpress.org/core/">Make Core Blog</a> and in the #core-editor channel in Slack, <a href="https://make.wordpress.org/core/tag/core-editor-agenda/">including weekly meetings</a>. If you don’t have a slack account, you can <a href="https://make.wordpress.org/chat/">sign up here</a>.
```

2021-09-16 12:07 UTC, aristath commented on readme.txt
> +View <a href="https://developer.wordpress.org/block-editor/principles/versions-in-wordpress/">the Versions in WordPress</a> document to get a table showing which Gutenberg plugin version is included
Movin "the" outside the link

```suggestion
View the <a href="https://developer.wordpress.org/block-editor/principles/versions-in-wordpress/">Versions in WordPress</a> document to get a table showing which Gutenberg plugin version is included in each WordPress release.
```

2021-09-18 16:12 UTC, annezazu commented on readme.txt
> +- **User Documentation:** Review the <a href="https://wordpress.org/support/article/wordpress-editor/">WordPress Editor documentation</a> for detailed docs on using the editor as an author to create
Great call out and update!

2021-09-18 16:15 UTC, annezazu commented
Thanks so much for reviewing and adding in suggestions @aristath !

2021-09-20 06:28 UTC, aristath approved these changes

2021-09-20 15:18 UTC, merged