Navigation Screen: Display error notice inside modal
WordPress/gutenberg pull request #34884
Opened 2021-09-16 14:46 UTC by Mamaduka

## Description
The default notices appear under the modal screen overlay. PR updates the `AddMenu` component to use local notices and display them inside the form.

The success still displays the Snackbar message.

Fixes #31100.

## How has this been tested?
1. Go to the experimental Navigation screen.
2. Try to create a new menu with the name that already exists.
3. The form should display an error notice inside the modal.

## Screenshots 
![CleanShot 2021-09-16 at 18 20 49](https://user-images.githubusercontent.com/240569/133631982-d516d643-10da-43d5-8ae6-bf3e33c9cb9c.png)

## Types of changes
Bugfix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-09-16 14:53 UTC, Mamaduka commented
Side note: I think we should update the modal design to match other "action modals" in editors.

The template modal example and similar conversation for Gallery block https://github.com/WordPress/gutenberg/pull/34606#issuecomment-914025909
![CleanShot 2021-09-16 at 18 35 53](https://user-images.githubusercontent.com/240569/133634587-339dd7b0-2ad9-459d-9a5f-5f9f551889d8.png)

2021-09-16 15:05 UTC, getdave requested changes
Nice work noticing and fixing this.

Nit: I spotted one thing. If I enter and invalid entry and the notice is already displayed and then it's not obvious why submit isn't working. This is because the notice doesn't disappear when the text in the input is changed.


https://user-images.githubusercontent.com/444434/133636846-c380d0b5-5ac3-4b79-a6bb-95d4bb6e3be3.mp4



Perhaps it should clear the notice as soon as new text is entered. That way if you enter another invalid value it's more obvious why it has failed.

2021-09-16 15:15 UTC, Mamaduka commented
Good point, Dave.

I also thought that maybe we should drop client-side validation in favor of the REST error response. It should fix the issue you mentioned.

https://github.com/WordPress/gutenberg/blob/adac4e7299f98e9a497eb58da14520aa7e47953a/packages/edit-navigation/src/components/header/add-menu-form.js#L35-L45

2021-09-16 16:16 UTC, javierarce commented
I also spotted another problem: if you create a menu with one or more spaces as the name, you get the error message behind the modal.

> Side note: I think we should update the modal design to match other "action modals" in editors.

+1, good idea

2021-09-16 16:25 UTC, Mamaduka commented
> I also spotted another problem: if you create a menu with one or more spaces as the name, you get the error message behind the modal.

That's one of the reasons I'm suggesting using server-side validation. There are various reasons the Menu creating might fail.

2021-09-16 16:52 UTC, Mamaduka commented
@getdave, @javierarce If that's okay with you, I would instead add server-side error notices as a follow-up PR to make it easier to review.

2021-09-17 07:59 UTC, talldan commented
I gave it a test and it looks really good so far.

It'd be good to look at improving the error message from the server for an empty menu name - "A name is required for this term.".

The error for a duplicate menu is the same as on the client, so could potentially switch to using only server errors. Equally I think it would be fine to improve the client side validation to cover more cases.

Do you plan to work on that as an alternative PR, @Mamaduka, or something built on top of this one?

2021-09-17 08:00 UTC, Mamaduka commented
> Do you plan to work on that as an alternative PR, @Mamaduka, or something built on top of this one?

The second PR will build on top of this one.

2021-09-17 08:30 UTC, getdave approved these changes
Approving pending follow up with server side API responses. Nice work!

2021-09-17 09:05 UTC, merged