Fix/32787 gradientbackground with background image
WordPress/gutenberg pull request #35036
Opened 2021-09-22 11:18 UTC by HILAYTRIVEDI

## Description
The background in the styling files changed to the background-image to remove the shorthand properties
## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards.

2021-10-13 17:40 UTC, ajlende requested changes
It looks like you have some social links changes mixed up with the `background` to `background-image` changes.

If you can remove 0c105ac from the list of changes and resolve the conflicts with trunk, I think this would be good to go.

2022-03-31 10:12 UTC, HILAYTRIVEDI reviewed
Files of different commit is removed

2022-12-08 12:54 UTC, priethor commented
@ajlende can you re-review this PR to validate your earlier feedback is addressed?

2025-08-04 07:34 UTC, Mamaduka commented
The PR still contains unrelated changes and moves files from blocks.

Should we close this as "stale"? It's been years without any updates.

2025-08-21 04:55 UTC, Mamaduka commented
Closing as "stale".

2025-08-21 04:55 UTC, closed without merging