Polish ResizableBox and convert it to TypeScript.
WordPress/gutenberg pull request #35062
Opened 2021-09-22 20:19 UTC by ZebulanStanphill

## Summary
This PR converts the `ResizableBox` component to TypeScript and cleans some stuff up along the way.

## List of changes
- Converted `ResizableBox` and its sub-components to TypeScript.
- Moved some constant CSS class/style objects out of `ResizableBox` component function so they aren't duplicated for every instance.
- Fixed several cases where `null` properties were included in `React.CSSProperties` objects, which expect `undefined` for empty values.
- Corrected several types that weren't explicit about allowing nullish values.
- Fixed a stylelint complaint in `resize-tooltip/styles/resize-tooltip.styles.js `.
- Enabled `strictNullChecks` for `@wordpress/components`. (Might revert this if tests reveal type errors in other components.)

## How has this been tested?

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-10-06 15:51 UTC, sarayourfriend requested changes
Thanks for this contribution! It's great to see more people contribution to the TypeScript types in the components package. There are a few things that need to change before this is mergable though. Otherwise, great work!

2021-10-06 15:51 UTC, sarayourfriend commented on packages/components/src/resizable-box/index.tsx
> +	},
Because `props` is spread into `Resizable` we should document that those types are also part of the definition for ResizableBox.

Also, it would probably improve readability (and be more in line with other examples in the components package) to not inline the type definition.

2021-10-06 15:51 UTC, sarayourfriend commented on packages/components/src/resizable-box/resize-tooltip/index.tsx
> -				isVisible={ isVisible }
Why remove these props?

2021-10-06 15:51 UTC, sarayourfriend commented on packages/components/src/resizable-box/resize-tooltip/index.tsx
>  		...props
Ditto here re: spread props. The type definition for the props object should include the props from the component that we spread these props into.

2021-10-06 15:51 UTC, sarayourfriend commented on packages/components/src/resizable-box/resize-tooltip/label.tsx
> +		...props
Here as well re: spread props type.

2021-10-06 15:51 UTC, sarayourfriend commented on packages/components/src/resizable-box/resize-tooltip/styles/resize-tooltip.styles.js
> +		color: #fff;
If we're already updating this it should use the `white` color from the COLORS object.

2021-10-06 15:51 UTC, sarayourfriend commented on packages/components/src/resizable-box/resize-tooltip/utils.ts
> +// @ts-check
Adding `ts-check` to a `ts` file is redundant.
```suggestion
```

2021-10-06 15:51 UTC, sarayourfriend commented on packages/components/src/resizable-box/resize-tooltip/utils.ts
>   * @return {UseResizeLabelProps} Properties for hook.
We can remove the JSDoc type annotations completely as they are redundant with the TS annotations.

2021-10-06 15:51 UTC, sarayourfriend commented on packages/components/src/resizable-box/resize-tooltip/utils.ts
> + * @param {GetSizeLabelArgs} props
Ditto here, we should remove the JSDoc type annotation.

2021-10-06 15:54 UTC, ZebulanStanphill commented on packages/components/src/resizable-box/resize-tooltip/index.tsx
> -				isVisible={ isVisible }
They're not used, and the logic relating to them has been moved a few lines up to `useResizeLabel` and the `if ( ! isVisible )` check.

2021-10-06 16:42 UTC, ZebulanStanphill commented on packages/components/src/resizable-box/resize-tooltip/utils.ts
> +// @ts-check
Forgot to remove this while testing, haha. Thanks.

2021-10-06 17:07 UTC, ZebulanStanphill commented on packages/components/src/resizable-box/index.tsx
> +	},
Done.

2021-10-06 17:09 UTC, ZebulanStanphill commented on packages/components/src/resizable-box/resize-tooltip/index.tsx
>  		...props
Whoops, forgot to do this one in the latest commit. Hang on...

2021-10-06 17:27 UTC, ZebulanStanphill commented on packages/components/src/resizable-box/resize-tooltip/index.tsx
>  		...props
Alright, done.

2021-10-06 17:29 UTC, ZebulanStanphill commented on packages/components/src/resizable-box/resize-tooltip/utils.ts
>   * @return {UseResizeLabelProps} Properties for hook.
I was able to remove the `@return`, but trying to remove the `@param` causes ESLint to complain:
```
Missing JSDoc @param "root0" declaration. eslint(jsdoc/require-param)
```

I could remove the entire docblock, but that would get rid of the function description.

2021-10-06 18:01 UTC, sarayourfriend commented on packages/components/src/resizable-box/resize-tooltip/utils.ts
>   * @return {UseResizeLabelProps} Properties for hook.
Oh sorry, I meant to just remove the type annotation, not the actual JSDoc themselves. We should preserve the JSDoc for the prop names and the return description, just remove everything between the `{}` including the curly braces themselves.

2021-10-06 20:06 UTC, ZebulanStanphill commented on packages/components/src/resizable-box/resize-tooltip/utils.ts
>   * @return {UseResizeLabelProps} Properties for hook.
Thanks for clarifying. I've added back the return descriptions.

However, I can't remove the `{}` part from `@param` without getting these ESLint errors:
![image](https://user-images.githubusercontent.com/19592990/136275179-e7700a3b-b551-4364-8f4a-2a7662493981.png)

Adding a description after the `props` name doesn't fix it, and of course I can't entirely remove the `@param` line either, as mentioned before.

2021-10-06 20:08 UTC, ZebulanStanphill commented on packages/components/src/resizable-box/resize-tooltip/styles/resize-tooltip.styles.js
> +		color: #fff;
I went with `COLORS.ui.textDark`, since that was already being used a few lines above. That makes sense, right?

2021-10-07 16:11 UTC, sarayourfriend commented on packages/components/src/resizable-box/index.tsx
> +import type { ResizableProps } from 're-resizable';
These can be combined into a single import I think?

```suggestion
import { Resizable, ResizableProps } from 're-resizable';
```

2021-10-07 16:12 UTC, sarayourfriend commented on packages/components/src/resizable-box/resize-tooltip/utils.ts
>   * @return {UseResizeLabelProps} Properties for hook.
Right, I think you just need to add back each of the `props.x` declarations and descriptions, but without the type annotation and then it will stop complaining.

2021-10-07 16:12 UTC, sarayourfriend commented on packages/components/src/resizable-box/resize-tooltip/styles/resize-tooltip.styles.js
> +		color: #fff;
I think so!

2021-10-07 21:00 UTC, ZebulanStanphill commented on packages/components/src/resizable-box/index.tsx
> +import type { ResizableProps } from 're-resizable';
That's what I did at first, but ESLint complained:
![image](https://user-images.githubusercontent.com/19592990/136460364-9a2522a0-acfc-44ae-b893-c54d82c6accb.png)

I don't really understand what the issue was, or if there even is an actual issue and not just an ESLint issue, but using `import type` worked. It looks like `eslint-plugin-import` is out-of-date (the version in Gutenberg's main `package.json` is `2.23.4`, but the latest release is [`2.24.2`](https://github.com/import-js/eslint-plugin-import/blob/main/CHANGELOG.md#2242---2021-08-24), so maybe that's the issue?

2021-10-07 21:12 UTC, ZebulanStanphill commented on packages/components/src/resizable-box/resize-tooltip/utils.ts
>   * @return {UseResizeLabelProps} Properties for hook.
Alright, done.

2021-10-07 23:09 UTC, sarayourfriend commented on packages/components/src/resizable-box/index.tsx
> +import type { ResizableProps } from 're-resizable';
Huh... that's weird. It seems like it's probably an eslint configuration issue with TypeScript 🤔 `import/named` is likely looking at the real JavaScript exports and ignoring the TS type exports (which would be in a separate `.d.ts` file for a compiled package).

2021-10-13 14:43 UTC, ZebulanStanphill commented on packages/components/src/resizable-box/index.tsx
> +import type { ResizableProps } from 're-resizable';
I figure it's not a blocker for merge, though, right?

2021-10-13 15:14 UTC, sarayourfriend approved these changes
LGTM! Thanks again for this.

2021-10-13 15:14 UTC, sarayourfriend commented on packages/components/src/resizable-box/index.tsx
> +import type { ResizableProps } from 're-resizable';
Nope, not at all!

2021-10-13 15:15 UTC, merged