Add/ Comment Avatar Core Block
WordPress/gutenberg pull request #35396
Opened 2021-10-06 11:54 UTC by c4rl0sbr4v0

This is the follow-up of a previous PR that was not following the workflow standards.

 https://github.com/WordPress/gutenberg/pull/35180

## Description

Feel free to test and comment the editor part.

We added a new Post Comment Avatar block. Related to issue #30575.

## How has this been tested?

WordPress Version: 5.8.1 <br>
Gutenberg Version: 11.6.0-rc.1 <br>
Database: MySQL 8.0.16 <br>
Web Server: nginx <br>
PHP Version: 7.3.5 <br>

## Screenshots 
## Types of changes

Type Experimental
New feature Site Editor
Needs Accessibility Feedback (Although I tried with both keyboard and voice over and seems to be fine)
Needs Testing

## Checklist:
- [ ] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate.

2021-10-06 14:57 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/index.php
> +	$inline_styles = styles_for_comment_avatar( $attributes );
With this approach we have on frontend this structure:
```
<div class="wp-block-comment-avatar" style="padding-applied">
  <img style="border" width height class="advanced-field-custom-class" />
<div>
```

Would be this a good structure for the component? 

How it would be with a wrapper with padding option:
![padding_inside_wrapper_div](https://user-images.githubusercontent.com/37012961/136228982-eaa09f6a-15e8-4210-b820-f16be7330b40.png)

Padding without a wrapper, putting the padding on the img tag:
![padding_inside_img_tag](https://user-images.githubusercontent.com/37012961/136228660-c330a404-e414-4f77-8ac6-22e534d0ae86.png)

2021-10-07 08:38 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/index.php
> +	$inline_styles = styles_for_comment_avatar( $attributes );
@jameskoster , I’d love to hear your thoughts on using this structure for the block for the padding issue. Thank you very much!

2021-10-07 09:09 UTC, gziolo reviewed
Nice work. I left some minor comments related to the code.

You will have to add test fixtures for the new block as noted in the failing unit test:

<img width="1048" alt="Screen Shot 2021-10-07 at 11 09 45" src="https://user-images.githubusercontent.com/699132/136355143-60ccbd78-91f0-4f71-b85a-f5b17e86c718.png">

You can find more details at https://github.com/WordPress/gutenberg/tree/trunk/test/integration/fixtures/blocks#readme.

2021-10-07 09:09 UTC, gziolo commented on lib/blocks.php
> +				'comment-avatar.php'            => 'core/comment-avatar',
It would be nice to keep names aligned:
```suggestion
				'post-comment-avatar.php'            => 'core/post-comment-avatar',
```

What's the relationship between Post Comment Author and Post Comment Avatar? Can you extend the PR's description to better explain the goals here?

2021-10-07 09:09 UTC, gziolo commented on packages/block-library/src/comment-avatar/index.php
> +	$alt    = $comment->comment_author . __( ' Avatar' );
It would be better to use `printf` here and make the author a placeholder in the translation. See: 
https://codex.wordpress.org/I18n_for_WordPress_Developers#Placeholders

2021-10-07 09:09 UTC, gziolo commented on packages/block-library/src/comment-avatar/index.php
> +function styles_for_comment_avatar( $attributes ) {
This function is going to be copied to WordPress core so it needs to be more specific to avoid conflicts with plugins and other functions in WordPress core. You can look at other files to see patterns used, but prefixing the function with `block_core_post_comment_avatar_` should do the trick.

2021-10-07 09:18 UTC, cbravobernal commented on lib/blocks.php
> +				'comment-avatar.php'            => 'core/comment-avatar',
> Keep names aligned: 

There will be an imminent refactor, removing the post prefix in all comment blocks. [See comment](https://github.com/WordPress/gutenberg/issues/34994#issuecomment-929291106)

> Relationship between Post Comment Author and Post Comment Avatar

Avatar is just the image of the author of the comment. It can be edited in size, padding and border-radius. The author would be a combination of Avatar, Name and maybe a little description. Of course, I can extend the PR's description. Will do it!

2021-10-07 10:02 UTC, gziolo commented on lib/blocks.php
> +				'comment-avatar.php'            => 'core/comment-avatar',
> There will be an imminent refactor, removing the post prefix in all comment blocks. See comment

I wasn't aware of that. I guess we will have to deprecate all existing blocks then. They are experimental and only available in the Gutenberg plugin so it shouldn't be that big of a deal.

2021-10-07 10:06 UTC, gziolo commented on packages/block-library/src/comment-avatar/block.json
> +	"usesContext": [ "commentId" ],
Given that this block becomes very granular. Would it be possible to read from the outer block's context the data necessary:
- `author_avatar_urls`
- `author_name`

I don't know how flexible `providesContext` is and if it is easy to achieve. Anyway, an idea worth considering here.

2021-10-07 10:07 UTC, gziolo commented on packages/block-library/src/comment-avatar/edit.js
> +							right: isRTL() ? false : true,
It should be enough to have:
```suggestion
							right: isRTL(),
```
Unless `isRTL` doesn't return a boolean value.

2021-10-07 10:11 UTC, gziolo commented on packages/block-library/src/comment-avatar/edit.js
> +						imageWidth={ maxSize }
What happens when `maxSize` is `null`?

2021-10-07 10:12 UTC, gziolo commented on packages/block-library/src/comment-avatar/edit.js
> +							src={ avatarUrls[ avatarUrls.length - 1 ] }
What's the decision process to always pick the last item in the array?

2021-10-07 10:38 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/edit.js
> +							src={ avatarUrls[ avatarUrls.length - 1 ] }
I took the biggest one. As if the user resizes above the maximum, it starts to lose image quality. 

Should I do this dynamic with all the sizes we have? I mean decreasing to smaller sizes if the width set by the user is smaller than 96 or 48.

Also, I still have to check what happens when custom plugins or themes apply a filter that affects the size of the avatar. 
`add_filter( 'get_avatar', ....`
`get_avatar_url()`
etc

2021-10-07 10:54 UTC, gziolo commented on packages/block-library/src/comment-avatar/edit.js
> +							src={ avatarUrls[ avatarUrls.length - 1 ] }
It's highly possible that there is a setting for a default avatar preset. I don't know how that differs from regular images though.

2021-10-07 11:08 UTC, jameskoster commented on packages/block-library/src/comment-avatar/index.php
> +	$inline_styles = styles_for_comment_avatar( $attributes );
Probably best to get a themers input here. Paging @kjellr :D 

I think all of the style properties should be applied to the image, but perhaps the wrapper would be helpful in situations where a pseudo element is desirable for styling purposes? Maybe that should just be filterable though, like it is in get_avatar()?

2021-10-07 13:36 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/index.php
> +	$inline_styles = styles_for_comment_avatar( $attributes );
The only problem is that applying padding to an image reduces its defined size. Well, you will have it, but more the container than the image itself. It's kind of tricky, but it should also make sense to apply all the styles on the img tag.

Let's see other inputs!

2021-10-07 13:53 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/edit.js
> +						imageWidth={ maxSize }
Size percentages get all marked and the avatar disappear 🤦‍♂️ 

![maxSizeNull](https://user-images.githubusercontent.com/37012961/136396290-5de75d5d-f810-4eaf-a491-1c5770f066bf.png)

There was some debate about what to do with the max size of the Avatar. [Comment](https://github.com/WordPress/gutenberg/pull/35180#discussion_r719450625)

It seems that now in WP Core we have them hardcoded, ¿maybe hardcoding the default value is the correct approach?

```
/**
 * Retrieves the pixel sizes for avatars.
 *
 * @since 4.7.0
 *
 * @return int[] List of pixel sizes for avatars. Default `[ 24, 48, 96 ]`.
 */
function rest_get_avatar_sizes() {
	/**
	 * Filters the REST avatar sizes.
	 *
	 * Use this filter to adjust the array of sizes returned by the
	 * `rest_get_avatar_sizes` function.
	 *
	 * @since 4.4.0
	 *
	 * @param int[] $sizes An array of int values that are the pixel sizes for avatars.
	 *                     Default `[ 24, 48, 96 ]`.
	 */
	return apply_filters( 'rest_avatar_sizes', array( 24, 48, 96 ) );
}
```

2021-10-07 14:03 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/edit.js
> +							src={ avatarUrls[ avatarUrls.length - 1 ] }
It is hardcoded on the system. TwentyNineteen theme, for example, has its own function that returns an integer, 60, and then applies to the function get_avatar()

`return sprintf( '<div class="comment-user-avatar comment-author vcard">%s</div>', get_avatar( $id_or_email, twentynineteen_get_avatar_size() ) );`

In `wp-includes/pluggable.php` you have this function:

```
function get_avatar( $id_or_email, $size = 96, $default = '', $alt = '', $args = null ) {
		$defaults = array(
			// get_avatar_data() args.
			'size'          => 96,
 ...
```

I will try try `apply_filters( 'pre_get_avatar', string|null $avatar, mixed $id_or_email, array $args )` and see what happens also!

2021-10-07 14:56 UTC, jameskoster commented on packages/block-library/src/comment-avatar/index.php
> +	$inline_styles = styles_for_comment_avatar( $attributes );
That's how padding works on other elements, no? 🤔 

Whether padding will "decrease" the image size is dependent on the themes `box-sizing` property I think.

2021-10-07 16:04 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/index.php
> +	$inline_styles = styles_for_comment_avatar( $attributes );
Yes, as you mention,  it is its default behaviour. Only I felt kind of weird in this case.
But also, there will be parent elements like Comment Author, Comment Element, Comment Loop, so it is a good idea to have only the image.

Let's code it that way. It will also reduce the code a lot.

2021-10-08 10:02 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/block.json
> +	"usesContext": [ "commentId" ],
For this case, I think `providesContext`seems to fit more with attributes (set by the user).
I could not find any good example of data fetched using useEntityProp and passing it as Attribute so that way can be passed as context.
Maybe could we also check how will work [Comment Template](https://github.com/WordPress/gutenberg/issues/35000) and if needed, update Avatar after.

2021-10-08 11:18 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/edit.js
> +						imageWidth={ maxSize }
I created a plugin in order to test a get_avatar filter in order to increase the size: 
```
function plugin_avatars_filter_get_avatar_really_big( $avatar, $id_or_email, $size, $default, $alt ) {
	$sizex10 = $size * 10;
	$url = get_avatar_url($id_or_email);
	$pattern = "(width|height\s*=\s*[\"'](.*?)[\"'])";
	$replacement = "width='{$sizex10}' height='{$sizex10}'";
	$bigavatar = preg_replace($pattern, $replacement, $avatar);
	return $bigavatar;
};

add_filter( 'get_avatar', 'plugin_avatars_filter_get_avatar_really_big', 3, 5);
```
Editor:
![Screenshot 2021-10-08 at 13 16 14](https://user-images.githubusercontent.com/37012961/136547464-b1c57069-2354-4df6-a79e-e6751bf9bbf5.png)


Frontend:
![Screenshot 2021-10-08 at 12 58 56](https://user-images.githubusercontent.com/37012961/136547470-2615ac81-288b-4680-a75a-4f67704b5cbf.png)
It will override the attributes set by the editor only on the frontend, is that's the expected result? 

On the block editor, the filter is not being applied as we get the default size from the get_avatar_data. So the editor would not correspond with the frontend result.
Maybe if the plugin filters get_avatar_data the resize could work in both approaches.

Most of them just update the URL, not the size, size is usually handled by the themes. This PR should not affect them, as old ones rely on the get_avatar function, and block-based ones will work with this new component.

Should I keep working on that? or better leave it for another PR or wait for the user's feedback or to see how the comments block is evolving.

Thanks! Ping @gziolo @ntsekouras

2021-10-14 08:26 UTC, gziolo commented on lib/blocks.php
> +				'comment-avatar.php'            => 'core/comment-avatar',
Reading again the comment from @mtias:

> As we work through these, I'd like to drop all the "Post" prefixes and just settle on "Comment Content", "Comment Author", etc.

Maybe we should update `title` and `description` as the first step, but leave folder names, file names, and block names prefixed with `post-` so we don't have to worry about backward compatibility for now.

2021-10-14 11:32 UTC, gziolo commented on packages/block-library/src/comment-avatar/block.json
> +	"usesContext": [ "commentId" ],
Let’s leave it as is for now. It aligns with other blocks.

2021-10-14 11:54 UTC, gziolo reviewed
It looks like the only remaining decision is to settle on how we handle avatar sizes. 

The other concern is how to deal with backward compatibility challenges related to the fact that `get_avatar` function uses hooks internally. The HTML code in the editor might differ with what PHP outputs.

2021-10-14 11:54 UTC, gziolo commented on packages/block-library/src/comment-avatar/block.json
> +	"attributes": {
One thing I’m not sure about is whether we should use `width` & `height` here or maybe keep using a single `size` attribute as it is now in PHP. It looks like avatars are squares. The other option could be to link width and height when modifying and leave the option to make the avatar square as an option. @jameskoster what do you think?

2021-10-14 11:54 UTC, gziolo commented on packages/block-library/src/comment-avatar/edit.js
> +export default ( { attributes, context: { commentId }, setAttributes } ) => {
It would be good to add a name for the function so it shows up in React Dev Tools.

2021-10-14 11:55 UTC, gziolo commented on packages/block-library/src/comment-avatar/edit.js
> +						imageWidth={ maxSize }
@carolinan or @aristath, what would you recommend here?

2021-10-14 14:56 UTC, gziolo commented on packages/block-library/src/comment-avatar/edit.js
> +						imageWidth={ maxSize }
I discussed the same issue with @mtias and he made a good point that we need to accept the fact that there is going to be a slightly different output on the frontend when someone uses those filters. In the block-based (FSE) themes world, we are trying to provide full control over the site so people no longer need to use those filters.

2021-10-14 15:36 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/block.json
> +	"attributes": {
Thanks @gziolo for keep taking a look at this PR 😄 

In order to provide more context. PHP has the three attributes, `size` as variable and `width` and `height` inside an array of attributes.

Regarding the block editor. We have enabled by default on the resize component, to be locked using `lockAspectRatio` (this means to increase and decrease both width and height at the same time). Also, there is a `height: auto` CSS property that adjusts the height automatically. 

```
.editor-styles-wrapper img, .editor-styles-wrapper embed, .editor-styles-wrapper object {
    height: auto;
    max-width: 100%;
}
```

The issue of this approach is that, if we don't set the height automatically (allowing having different values for width, height), all of these combinations create a weird user experience, to be honest.

![Screenshot 2021-10-14 at 17 31 45](https://user-images.githubusercontent.com/37012961/137349868-e8c6d71d-b4fe-4db9-a23b-ac3cc80bf60c.png)

By using only one size attribute we would lose:
 - Image resizer
 - Dimensions panel

By using Width - Height we should do:
 - Decide to force or not to force the square. If we are forcing it, we have to add it to the dimensions panel.
 - Decide if force square could be an option. In this case, we should take a look also to the styles, in order not to be applied to the image.

Feel free to comment and give opinions!

2021-10-14 17:15 UTC, jameskoster commented on packages/block-library/src/comment-avatar/block.json
> +	"attributes": {
Hmm, yes, sorry I didn't realise this while working on the original design. Since Gravatar (and the other options like wavatar) always return a square image, we probably shouldn't allow folks to change the aspect ratio (IE set different values for height and width). 

> Decide to force or not to force the square. If we are forcing it, we have to add it to the dimensions panel.

Might we need to consider a 'link' affordance for height and width, similar to figma:


https://user-images.githubusercontent.com/846565/137365118-38fedcf2-5ea7-48da-b425-282b9834603a.mp4

2021-10-15 10:19 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/block.json
> +	"attributes": {
I've seen that the Site Logo block solved this issue with this approach, should we do the same here?

![Screenshot 2021-10-15 at 11 38 36](https://user-images.githubusercontent.com/37012961/137472363-cce6de47-da24-4c10-bb25-eb2e0b37f7cd.png)

That way we can create another issue in order to solve the 'link' for the rest of the images. As I've seen the same issue with the width-height aspect ratio happens on default Image blocks.

Thanks @gziolo @jameskoster for your patience 😄

2021-10-15 10:20 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/edit.js
> +export default ( { attributes, context: { commentId }, setAttributes } ) => {
Done!

2021-10-15 10:20 UTC, cbravobernal commented on lib/blocks.php
> +				'comment-avatar.php'            => 'core/comment-avatar',
Agree with that. Done!

2021-10-15 12:31 UTC, gziolo commented on packages/block-library/src/comment-avatar/block.json
> +	"attributes": {
It works for me, in terms of execution - to have a better experience than before with Comment Avatar block. Then follow-up with the same issue for more than one block.

2021-10-15 12:33 UTC, gziolo commented on lib/blocks.php
> +				'comment-avatar.php'            => 'core/comment-avatar',
I think you missed changes in this file, the rest looks great 😄

2021-10-15 12:39 UTC, jameskoster commented on packages/block-library/src/comment-avatar/block.json
> +	"attributes": {
Agreed.

2021-10-15 15:18 UTC, cbravobernal commented on packages/block-library/src/comment-avatar/block.json
> +	"attributes": {
I changed the code to work on that approach instead. https://www.loom.com/share/60f7c06c6acc4a5995f07beab75b359d

2021-10-15 16:10 UTC, jameskoster commented
Looking great. A couple of thoughts on this one:

Since we have padding and radius, should we also include a background color option, and border controls? These seem to go hand in hand and will give themers the flexibility to create really interesting styles.

The name feels a little awkward, should it be "Comment Author Avatar" or "Commenter Avatar"? 🤔

2021-10-18 15:07 UTC, gziolo reviewed
When testing with Safari (macOS), something doesn't work as expected for the block. After I insert the block and move focus to another block (or refresh the page), I'm no longer able to edit the block.


https://user-images.githubusercontent.com/699132/137758347-c9749d82-e1c7-44cb-8dde-c60e1eae4599.mov

2021-10-18 15:07 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +				<PanelBody title={ __( 'Comment Author Avatar Settings' ) }>
Should we use `Settings` or `Avatar Settings`? The current one is a bit long and repeats the title of the block that is already in the sidebar.

2021-10-18 15:07 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +	const clientWidth = useClientWidth( containerRef );
Does this value depend on the size of the screen? Won't it change when you resize the size of the browser?

2021-10-18 15:07 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +				) : null }
Should it have a fallback when there is no avatar? Some sort of general placeholder?

2021-10-18 15:07 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +	const clientWidth = useClientWidth( containerRef );
Yes, it changes while I resize the browser:

<img width="571" alt="Screen Shot 2021-10-18 at 16 51 41" src="https://user-images.githubusercontent.com/699132/137755543-ea1eabdd-584b-485a-9ec1-b4a18bc964be.png">
<img width="287" alt="Screen Shot 2021-10-18 at 16 52 00" src="https://user-images.githubusercontent.com/699132/137755551-3a6978b8-8992-453e-a6a1-71662a40d970.png">
<img width="301" alt="Screen Shot 2021-10-18 at 16 52 36" src="https://user-images.githubusercontent.com/699132/137755555-984a20fa-25da-4ca9-9266-d83a58be19df.png">

2021-10-18 15:11 UTC, cbravobernal commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +				<PanelBody title={ __( 'Comment Author Avatar Settings' ) }>
I will change it to Avatar Settings

2021-10-18 15:12 UTC, cbravobernal commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +	const clientWidth = useClientWidth( containerRef );
It's taking the max width of the container. Should we put instead a fixed value?

2021-10-18 15:13 UTC, cbravobernal commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +				) : null }
I think WordPress by default is putting always an Avatar. In this case the placeholder would appear while fetching the comment data.

![Screenshot 2021-10-18 at 17 13 29](https://user-images.githubusercontent.com/37012961/137759421-b5d8d9e9-a668-45d3-936d-72abd4eeab0a.png)

2021-10-18 15:18 UTC, cbravobernal commented
> When testing with Safari (macOS), something doesn't work as expected for the block. After I insert the block and move focus to another block (or refresh the page), I'm no longer able to edit the block.
> 
>  Screen.Recording.2021-10-18.at.17.05.30.mov

That should be fixed. It was due to the lack of a div before the resize component. Could you please check it again? I could not reproduce it completely.

2021-10-18 15:23 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +				) : null }
Right, but when there are no avatars after fetching is complete, we should also have this fallback included.

2021-10-18 15:26 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +	const clientWidth = useClientWidth( containerRef );
I don't see my comment. I don't know what would be the best here, but one thing is clear. The max value shouldn't depend on the editor's size max width available.

2021-10-18 15:26 UTC, gziolo commented
> That should be fixed. It was due to the lack of a div before the resize component. Could you please check it again? I could not reproduce it completely.

I had code from 1 hour, so it might be that. I will retest tomorrow 👍🏻

2021-10-19 10:20 UTC, cbravobernal commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +				) : null }
What should we put as fallback? A text?
I will take a look if we can put the default image in an easy way.

2021-10-19 10:25 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +				) : null }
The image. I even wonder whether it should be resizable.

2021-10-19 11:40 UTC, gziolo commented
The block editing works quite nicely. There is something wrong with how padding gets applied in the editor. I can't see also colors applied on the frontend the same way as in the editor.

Editor:

https://user-images.githubusercontent.com/699132/137901941-41353405-a32b-4c0d-84dd-0b60da40e27e.mov

Frontend:

<img width="813" alt="Screen Shot 2021-10-19 at 13 38 36" src="https://user-images.githubusercontent.com/699132/137902278-bb404bc4-fba0-46cf-a2d1-d740c3b3c17d.png">

2021-10-19 15:01 UTC, cbravobernal commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +	const clientWidth = useClientWidth( containerRef );
I will put as maximum the same we have for images, maximum avatar size * 2.5

2021-10-21 10:22 UTC, gziolo approved these changes
Let's tackle the two remaining issues as follow-ups. It will allow us to have all template related blocks to work with.

2021-10-21 10:26 UTC, gziolo requested changes
I almost forgot about the issues with the padding and color I shared in my last comment. That seems more important than the fallback for the avatar and the way to pick the max size for the image.

2021-10-21 10:48 UTC, cbravobernal commented
> I almost forgot about the issues with the padding and color I shared in my last comment. That seems more important than the fallback for the avatar and the way to pick the max size for the image.

I'm pushing the color / background issue right now.

Regarding the padding. It's an issue that happens on all components with fixed size (the padding is bigger than the width of the component. Could we try to set a maximum padding depending on the Avatar size selected?

2021-10-21 11:11 UTC, gziolo commented
> Regarding the padding. It's an issue that happens on all components with fixed size (the padding is bigger than the width of the component. Could we try to set a maximum padding depending on the Avatar size selected?

@jameskoster, what do you think?

2021-10-21 11:27 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/index.php
> +	$wrapper_attributes = WP_Block_Supports::get_instance()->apply_block_supports();
Can you pass the result of `get_block_wrapper_attributes()` as `extra_attr` when calling `get_avatar` instead?

2021-10-21 11:37 UTC, jameskoster commented
It seems to be a quirk of how the padding + width controls interact. 

Since the image has `box-sizing: border-box`, when you add padding the image actually shrinks which makes the size control feel broken. 

Changing this to `box-sizing: content-box` fixes that part – the image dimensions will then always reflect what is set in the controls regardless of whether padding is set or not. 

Then we just need to fix the resize wrapper / handles. Currently the width of the image is applied to `components-resizable-box__container`. We need to update this so that it's width = img width + padding.

Finally, we need to apply the image width to the img itself in the css. The result should look something like this:

<img width="1630" alt="Screenshot 2021-10-21 at 12 36 28" src="https://user-images.githubusercontent.com/846565/138269309-0c8e72fa-2a0d-4ed9-946d-1f58ea94b0e9.png">


---

Side note: That warning on the background color is irrelevant since we're working with an image. We should remove that.

2021-10-25 10:52 UTC, cbravobernal commented on packages/block-library/src/post-comment-author-avatar/index.php
> +	$wrapper_attributes = WP_Block_Supports::get_instance()->apply_block_supports();
That way the background color dissapears due to that `get_avatar()` function is not overwriting the class attribute. As class is defined before, it remains with default classes instead of using the block attribute ones.

That is the reason why asks for a `class` attribute first. I think there are a few components that behaves similar.

This is the `get_avatar()` function part where it handles class and the rest of attributes:
![Screenshot 2021-10-25 at 12 45 16](https://user-images.githubusercontent.com/37012961/138682197-553d486d-87a0-41b7-9d6d-1ea3d46f815e.png)

This is the frontend markup:
![Screenshot 2021-10-25 at 12 42 59](https://user-images.githubusercontent.com/37012961/138682958-eb46d9e1-e251-4aa1-853b-71e1551c5209.png)

Would be a good idea to extend the `get_block_wrapper_attributes()` to return styles and classes separately if needed? Or maybe would be better to add a couple of functions one for classes and one for styles?

In case the first one is a good approach, I could create an issue for that, but that one should be on Trac I think.

2021-10-25 11:08 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/index.php
> +	$wrapper_attributes = WP_Block_Supports::get_instance()->apply_block_supports();
I'm surprised that `get_block_wrapper_attributes` returns a string in the first place. If it would return styles and classes separately, we wouldn't have to worry about the issue you run into. It's probably easier to introduce a lower-level function that returns a single attribute based on the following part of the existing function:

https://github.com/WordPress/wordpress-develop/blob/2382765afa36e10bf3c74420024ad4e85763a47c/src/wp-includes/class-wp-block-supports.php#L171-L203

Something like `get_block_wrapper_attribute_value( 'class', 'foo-class boo-class' )`.

What do you think?

2021-10-25 11:17 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/index.php
> +	$wrapper_attributes = WP_Block_Supports::get_instance()->apply_block_supports();
I see that `apply_block_supports` performs a few computations:
https://github.com/WordPress/wordpress-develop/blob/2382765afa36e10bf3c74420024ad4e85763a47c/src/wp-includes/class-wp-block-supports.php#L93

So it might make more sense to have a function that returns both attributes as values.

2021-10-25 11:18 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/index.php
> +	$wrapper_attributes = WP_Block_Supports::get_instance()->apply_block_supports();
Anyway, it shouldn't be a blocker for this block. Let's tackle it later 😄

2021-10-25 11:26 UTC, gziolo commented
There is one simple issue reported by PHP linter:
<img width="667" alt="Screen Shot 2021-10-25 at 13 24 50" src="https://user-images.githubusercontent.com/699132/138686846-003d135e-5df9-4cab-a0b3-14508293cd51.png">

You can run it locally with:

`npm run lint-php` 

You might need to run `npx wp-env start` first.

2021-10-25 11:41 UTC, cbravobernal commented
> There is one simple issue reported by PHP linter: <img alt="Screen Shot 2021-10-25 at 13 24 50" width="667" src="https://user-images.githubusercontent.com/699132/138686846-003d135e-5df9-4cab-a0b3-14508293cd51.png">
> 
> You can run it locally with:
> 
> `npm run lint-php`
> 
> You might need to run `npx wp-env start` first.

Fixed

2021-10-25 11:42 UTC, cbravobernal commented
> It seems to be a quirk of how the padding + width controls interact.
> 
> Since the image has `box-sizing: border-box`, when you add padding the image actually shrinks which makes the size control feel broken.
> 
> Changing this to `box-sizing: content-box` fixes that part – the image dimensions will then always reflect what is set in the controls regardless of whether padding is set or not.
> 
> Then we just need to fix the resize wrapper / handles. Currently the width of the image is applied to `components-resizable-box__container`. We need to update this so that it's width = img width + padding.
> 
> Finally, we need to apply the image width to the img itself in the css. The result should look something like this:
> 
> <img alt="Screenshot 2021-10-21 at 12 36 28" width="1630" src="https://user-images.githubusercontent.com/846565/138269309-0c8e72fa-2a0d-4ed9-946d-1f58ea94b0e9.png">
> 
> Side note: That warning on the background color is irrelevant since we're working with an image. We should remove that.

This seems to be out of this scope. Should we create another issue for "Fix Width - Padding issues on editor"?

For our case we can just remove the padding option here meanwhile, add it as a feature later.

What do you think? @gziolo @jameskoster ?

2021-10-25 11:59 UTC, jameskoster commented
Yes good point, this issue could affect many blocks as we look to add both padding and width controls to them, so addressing it holistically makes sense to me.

2021-10-26 09:46 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +	const maxSizeBuffer = maxSize * 2.5;
Should the value be approximated to an integer? Example: 99 * 2.5 = 247.5;

2021-10-26 09:49 UTC, gziolo reviewed
I'll give it a spin now. The latest code changes look good 👍🏻

2021-10-26 10:11 UTC, cbravobernal commented on packages/block-library/src/post-comment-author-avatar/index.php
> +	$wrapper_attributes = WP_Block_Supports::get_instance()->apply_block_supports();
Added a Trac issue. I will create and test a PR on the WordPress repo.
https://core.trac.wordpress.org/ticket/54319

2021-10-26 10:16 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/index.php
> +	$height             = isset( $attributes['height'] ) ? $attributes['height'] : '96';
Nitpick: `get_avatar` expects int values.

```suggestion
	$width              = isset( $attributes['width'] ) ? $attributes['width'] : 96;
	$height             = isset( $attributes['height'] ) ? $attributes['height'] : 96;
```

See https://github.com/WordPress/wordpress-develop/blob/4aed27209750cca396241470085eda0dc295f6f0/src/wp-includes/pluggable.php#L2646-L2647.

2021-10-26 10:29 UTC, gziolo commented
There are still issues with the block wrapper that makes it difficult to select the block:


https://user-images.githubusercontent.com/699132/138860439-26bfe6e4-4c5d-4d11-b06f-9a9ee267a1e7.mov

It's impossible to select the placeholder when the block has no valid comment id provided. When the block has valid data, you can select it only by clicking on the image.

2021-10-26 10:31 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +		<p>{ _x( 'Post Comment Author Avatar', 'block title' ) }</p>
The block title used here should be the same as the value in the `block.json` file which is different at the moment:
```json
"title": "Comment Author Avatar",
```

2021-10-26 10:34 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +			<div ref={ containerRef }>{ displayAvatar }</div>
`useBlockProps` is missing:
https://github.com/WordPress/gutenberg/blob/2ecc9a4520f6db14966e2da462bf47f41d267df0/packages/block-library/src/post-comment-author/edit.js#L29
https://github.com/WordPress/gutenberg/blob/2ecc9a4520f6db14966e2da462bf47f41d267df0/packages/block-library/src/post-comment-author/edit.js#L94

2021-10-26 10:36 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +			<div ref={ containerRef }>{ displayAvatar }</div>
I see it is attached it the avatar `img` tag which seems to be the reason why you can only select the block through the image as it has constrained area with the width & height pair.

2021-10-26 10:40 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +	const containerRef = useRef();
Is this `containerRef` necessary? It doesn't seem to be referenced in any place.

2021-10-26 10:58 UTC, cbravobernal commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +	const containerRef = useRef();
It is not, nice catch!

2021-10-26 10:58 UTC, cbravobernal commented on packages/block-library/src/post-comment-author-avatar/edit.js
> +		<p>{ _x( 'Post Comment Author Avatar', 'block title' ) }</p>
Changed!

2021-10-26 11:11 UTC, cbravobernal commented on packages/block-library/src/post-comment-author-avatar/index.php
> +	$height             = isset( $attributes['height'] ) ? $attributes['height'] : '96';
Done!

2021-10-26 15:22 UTC, gziolo commented on packages/block-library/src/post-comment-author-avatar/index.php
> +	$wrapper_attributes = WP_Block_Supports::get_instance()->apply_block_supports();
Nice, thank you!

2021-10-27 10:35 UTC, gziolo approved these changes
We still need to improve how the block can be selected when it occupies the full row. In practice, it might be a less popular option. I suspect that many designs will prefer to use a group block with a flex layout to have a few similar blocks in one line.

Anyway. I think that this PR is good enough to start testing it with other blocks necessary for the Comments Loop block.

2021-10-27 10:36 UTC, merged