Layout block support: Append layout styles to post content in REST API requests
WordPress/gutenberg pull request #35413
Opened 2021-10-07 04:25 UTC by andrewserong

## Description

Fixes #35376

This PR updates the Layout block support to render the layout styles in REST API requests by appending the styles to the end of post content.

In requests to endpoints like the posts endpoint, `wp_footer` isn't output, so in certain circumstances (like rendering the Post Content block in the site editor) blocks depending on the layout styles render incorrectly. The approach in this PR attempts to be as consistent as we can with the approach introduced in #32083, which moved the rendering of the styles from the end of the individual block's content to `wp_footer`.

## How has this been tested?

Manually.

Before applying this PR:

1. Activate a blocks-based theme, e.g. TT1-Blocks
2. Add a post and insert a Social Icons block, and add a bunch of icons with links
3. Publish the post and open up the Site Editor
4. Assuming your theme uses the Query Loop + Post Content blocks in the main index template, you should see the issue reported in #35376 where the layout spacing styles used by the Social Icons block is not rendered within the editor.

After applying this PR:

1. Reload the site editor, and you should see that the styling issue is resolved
2. View the front end of your site — the social icons should still render correctly, and if you view source, you should see that the wp-container styles (e.g. `<style>.wp-container-615e737c1a8f3 > *`) are still rendered in the footer, after script tags, etc.
3. You can also test the REST API endpoint directly by grabbing the post id of your published post. Then, in the site editor, once you've reloaded the page, search the Network tab of dev tools for your post id. You should find a network request for the `posts` API endpoint, used to render the Post Content block within the editor. E.g. on my test site, there's a URL like: http://localhost:8888/index.php?rest_route=%2Fwp%2Fv2%2Fposts%2F1105&_locale=user
4. If you inspect the JSON returned by that endpoint, at the end of the `content.rendered` string, you should see the layout styles are now rendered

## Screenshots 

| Editor before | Editor after |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14988353/136319501-b149f810-7e4b-45e8-a55a-e210fc51bf0b.png) | ![image](https://user-images.githubusercontent.com/14988353/136319512-b1af1344-7f62-4104-aaaf-2af0cda2da05.png) |
| JSON before | JSON after |
| ![image](https://user-images.githubusercontent.com/14988353/136319597-fff06307-1042-4038-a12b-18bcd64ea0a7.png) | ![image](https://user-images.githubusercontent.com/14988353/136319612-2173a7ed-9a49-4214-b22b-483a7bcacb85.png) |

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] My code is tested. (manually)
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-10-07 04:26 UTC, andrewserong commented
@youknowriad and @ellatrix, I've just added you both as reviewers since you've worked on the layout support before. Please let me know if you think there's another way we should handle this instead 🙂

2021-10-07 07:32 UTC, youknowriad commented
Interesting issue, I agree we need to find a consistent solution here but the proposed one is rather too specific for me. I think there might be other block supports (duotone and maybe others?) that have the same behavior as layout and we should try to find something baked into the framework and avoid moving the responsibility to handle this to the block supports them selves.

2021-10-07 07:55 UTC, ramonjd commented on lib/block-supports/layout.php
> +
I'm curious to learn the reason behind using hooks here. 

Is there an advantage, such as a use case where we'd want to use the `wp_render_layout_support_styles` filter elsewhere?

The only difference I see between appending styles via `the_content` filter and return early (before adding the `wp_footer` action) with something like this –

```php
	if ( defined( 'REST_REQUEST' ) && REST_REQUEST ) {
		return $content . '<style>' . $style . '</style>';
	}
```

– is that the style tags are added to the end of the response value and not immediately after the block.

Adding multiple Social Icons blocks to the post (probably a rare case, I know) appends styles to the end like so. 

<img width="600" alt="Screen Shot 2021-10-07 at 6 52 12 pm" src="https://user-images.githubusercontent.com/6458278/136342686-bda66cde-6fca-43a4-a6d6-b472cdcc694c.png">

Whereas returning content with the style appended from the method will append the style tag after its corresponding block container.

I don't see a problem either way. 👍

2021-10-07 08:01 UTC, ramonjd commented
This works well for me @andrewserong 

Thanks for getting a fix in so quickly 🙇 

| Before  | After |
| ------------- | ------------- |
| <img width="300" alt="Screen Shot 2021-10-07 at 6 28 54 pm" src="https://user-images.githubusercontent.com/6458278/136343431-765949a4-7d48-4f1d-84ad-a991b8a7a867.png">  | <img width="300" alt="Screen Shot 2021-10-07 at 6 23 34 pm" src="https://user-images.githubusercontent.com/6458278/136343437-4750e4c9-34ea-4fe7-a6ad-2a6ee3c75f53.png">|

✅ Layout block CSS is appended to the post content in the REST API response.
✅ Social Icons blocks appear as they should in the Post Content Block in the Site Editor
✅ Block Editor styles are unaffected (no change) and frontend appears as it should.

It looks good to me, but keen to hear other's opinion on the approach.

2021-10-07 08:35 UTC, ramonjd commented
>  I think there might be other block supports (duotone and maybe others?) that have the same behavior as layout and we should try to find something baked into the framework and avoid moving the responsibility to handle this to the block supports them selves

That sounds very reasonable 👍 

I can confirm that the [duotone render block callback](https://github.com/WordPress/gutenberg/blob/771b4564ebfdcdd2913b4e30e8d9d6aeaf607e67/lib/block-supports/duotone.php#L326) is also affected:

| Image Block with duotone in Block Editor  | Post Content Block in Site Editor |
| ------------- | ------------- |
| <img width="300" alt="Screen Shot 2021-10-07 at 7 22 50 pm" src="https://user-images.githubusercontent.com/6458278/136347426-0d85621c-4ac5-4775-be22-d4c73212f896.png">  | <img width="300" alt="Screen Shot 2021-10-07 at 7 22 44 pm" src="https://user-images.githubusercontent.com/6458278/136347441-8b4c8c47-bae9-494e-8f1b-fc99d3b870d1.png">  |

Is there an obvious place to relocate the logic to handle this, or to start looking? 

I was thinking, because I don't know any better, that we could roll out a helper method/filter that will do the `REST_API` check and do the work accordingly.

2021-10-07 08:36 UTC, youknowriad commented
To be honest, I don't know. I think @ellatrix moved these styles to the footer initially so she might know better.

2021-10-07 09:45 UTC, andrewserong commented on lib/block-supports/layout.php
> +
Thanks for testing @ramonjd, and great questions! The main reason to add the filter was to attempt to preserve the same behaviour as that introduced in https://github.com/WordPress/gutenberg/pull/32083 which resolved an issue raised in https://github.com/WordPress/gutenberg/issues/30500 where styling was affected if the `style` tags are rendered directly after the individual block.

> Is there an advantage, such as a use case where we'd want to use the wp_render_layout_support_styles filter elsewhere?

I suppose only if we were going to use it as a consistent way of handling the problem for Duotone, etc.

2021-10-07 09:53 UTC, andrewserong commented
Thanks for the feedback, folks!

> I think there might be other block supports (duotone and maybe others?) that have the same behavior as layout and we should try to find something baked into the framework and avoid moving the responsibility to handle this to the block supports them selves.

Very much agreed, it does feel quite brittle if each of the block supports has to worry about how and where they're injecting styles. It'd be nice to have a helper method or two that abstracts the behaviour away.

Let me know if anyone thinks of other ways to approach this, I'm happy to do further digging, too. While I was hacking around with this PR, I tried a few different ideas, including hooking into filtering the REST API response, and ironically the solution using an extra filter and `the_content` looked much cleaner in comparison 😅

I suppose ultimately we need to come up with a consistent approach for block supports that:

* Renders styles in a normal view of the block on the front end of a site
* Renders styles within the rendered content of an API request for a post (or via the `block-renderer` API endpoint)
* Doesn't cause styling issues like the one reported in https://github.com/WordPress/gutenberg/issues/30500

2021-10-07 09:57 UTC, youknowriad commented
That makes sense. 

It makes me wonder about global styles styles though, some of the global styles are also necessary for post content to show up properly and sometimes the distinction about what should be in post content or not is hard to draw.

2021-10-07 09:57 UTC, youknowriad commented
Note that after #35425 the link color styles will also be impacted by this bug.

2021-10-07 21:28 UTC, ramonjd commented on lib/block-supports/layout.php
> +
Thanks for confirming! 👍

2021-10-08 05:33 UTC, andrewserong commented
I'm wrapping up for the week, but out of curiosity, I thought I'd explore the idea of whether the approach in this PR could be generalised and made applicable for the three block supports that currently render either `svg` or styles and append to the post/page via `wp_footer` (and therefore need handling for the REST API) — Layout, Duotone, and Elements.

I've made a start with a draft PR in https://github.com/WordPress/gutenberg/pull/35450, which currently refactors the Layout support a bit to make this possible. I think the approach can be wrangled to also factor in the Duotone and Elements implementations, but the whole concept could still be a bit of hack. I'm curious to see whether I can get it to _technically_ work, but I'm more than happy to get early feedback if anyone thinks it isn't worth pursuing further. Otherwise, I'll keep hacking around / digging in that draft PR next week! 😀

2021-10-08 14:39 UTC, youknowriad commented
A common function sounds good like explored in #35450 but I didn't understand why you had to include the "placeholder" logic there, it could receive the "output" directly?

2021-10-09 00:57 UTC, andrewserong commented
Thanks for taking a look!

> I didn't understand why you had to include the "placeholder" logic there, it could receive the "output" directly?

I was curious to explore the idea of seeing if we could abstract away the unique id generation to the function, too, instead of the block supports having to worry about it. But it's probably doing a bit too much to add that in at the same time (and then adds the complexity of the "placeholder" logic). I'll rework it on Monday to simplify. Cheers!

2021-10-10 20:52 UTC, spacedmonkey requested changes
Hey, I am maintainer of the REST API, so want to chime here. 

First, I don't like the format of this PR, `the_content` is used for every post type, even hidden ones, like menu items. Using it here, is overkill and will fire on many post types that do not need it. Also, the check for REST API, could be improved, as it will not load in preloading middleware. 

Instead of adding to new field the REST API, using a function like [register_rest_field](https://developer.wordpress.org/reference/functions/register_rest_field/). Why does this data need to live in the content field?

If adding a new field doesn't make sense, can I recommend using, [rest_prepare_{$this->post_type}](https://github.com/WordPress/wordpress-develop/blob/6367c01844e34dd372b999beb0e370f52d8c42d5/src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php#L1949). 

Let me know, when you have made the changes and I will re-review

2021-10-10 22:19 UTC, andrewserong commented
Thanks for taking a look @spacedmonkey, much appreciated!

> First, I don't like the format of this PR, the_content is used for every post type, even hidden ones, like menu items. Using it here, is overkill and will fire on many post types that do not need it ... Instead of adding to new field the REST API, using a function like register_rest_field. Why does this data need to live in the content field?

That's a great idea. Preferably we wouldn't be rendering these `style` elements to the content field (it felt messy to me too, but I couldn't quite think of an alternative while I was hacking around last week). I agree, it'd be much nicer if we had a separate field for it. Since this PR primarily intends to fix how blocks are rendered within the editor, using a separate field in the API response sounds much cleaner.

I'll do some exploration either in this PR or in #35450 to see what's possible and will be sure to give you a ping when it's ready for another review!

2021-10-12 05:36 UTC, andrewserong commented
I'm going to close this PR out now, as I've progressed further in moving to a generic utility function approach in #35450, so let's move the discussion over there. Thanks!

2021-10-12 05:36 UTC, closed without merging