Scripts: Remove inject polyfill by default
WordPress/gutenberg pull request #35436
Opened 2021-10-07 16:00 UTC by mkaz

## Description

The default behavior for the scripts when generating the assets.php file was to include the `wp-polyfill` by default. With the dropping of support for IE, this is no longer necessary. So this PR removes adding it by default.

Fixes #35410

## How has this been tested?

Confirm that when using script to generate assets.php script, that `wp-polyfill` is not included in the dependency list.

## Types of changes

This is a breaking change in that any scripts or plugins that rely on the polyfill must now explicitly declare it as a dependency, which they probably should of done in the first place to guarentee compatibility.

2021-10-07 18:38 UTC, gwwar commented
@mkaz for testing do you have an example command of what we should run / see?

For other reviewers, note that the block editors request wp-polyfill regardless of this change (and that this is expected).

![CleanShot 2021-10-07 at 11 31 40@2x](https://user-images.githubusercontent.com/1270189/136443197-3bf4f284-69e4-42b1-adfa-0f35c29e4688.png)

2021-10-07 20:17 UTC, mkaz commented
It is a little tricky to test because you'll need to run the wp-scripts out of the repo, and not NPM.

The before case:

```
npx @wordpress/create-block foo
grep wp-polyfill foo/build/index.asset.php
```

The after case is easiest to duplicate, so working off the same before case

```
cd foo/
// edit: node_modules/@wordpress/scripts/config/webpack.config.js (remove injectPolyfill line 250)
npm run build
grep wp-polyfill build/index.asset.php
```

2021-10-07 20:36 UTC, gwwar commented
Hmm, maybe we can leverage the create block test `npm run test:create-block` and temporarily comment out the `trap cleanup EXIT` line to compare built results.

https://github.com/WordPress/gutenberg/blob/2c7ed62cf440c502df75c93f231633677d378deb/bin/test-create-block.sh#L22

2021-10-07 20:46 UTC, gwwar approved these changes
I tested this by commenting out this [line](https://github.com/WordPress/gutenberg/blob/2c7ed62cf440c502df75c93f231633677d378deb/bin/test-create-block.sh#L3-L7) in test-create-block and ran `npm run test:create-block` in this branch, then again in trunk. As we can see the wp-polyfill is omitted:

branch: esnext-test/build/index.asset.php
```
<?php return array('dependencies' => array('wp-block-editor', 'wp-blocks', 'wp-element', 'wp-i18n'), 'version' => 'daa4176be053b3cf84973d388f68b869');
```

trunk:
```
<?php return array('dependencies' => array('wp-block-editor', 'wp-blocks', 'wp-element', 'wp-i18n', 'wp-polyfill'), 'version' => 'daa4176be053b3cf84973d388f68b869');
```

2021-10-08 07:08 UTC, aristath requested changes
The code is fine I just added a comment to improve the changelog (minor typo). 👍

2021-10-08 07:08 UTC, aristath commented on packages/scripts/CHANGELOG.md
> +- The webpack config was update to no longer include the polyfill by default when creating the assets.php file. If your usage requires the wp-polyfill, you must explictly set it as a dependency. ([#3
Minor tweak for the changelog

```suggestion
- The webpack config was updated to no longer include the polyfill by default when creating the `assets.php` file. If your usage requires the `wp-polyfill`, you must explicitly set it as a dependency. ([#34536](https://github.com/WordPress/gutenberg/pull/35436)]
```

2021-10-08 10:21 UTC, gziolo approved these changes
Nice, thank you for wrangling this change 👍🏻

2021-10-08 12:41 UTC, aristath approved these changes

2021-10-08 13:27 UTC, merged