FSE: Allow child theme.json to be merged with parent theme.json
WordPress/gutenberg pull request #35459
Opened 2021-10-08 11:28 UTC by scruffian

## Description
If a theme has a parent theme, then this applies the child theme.json settings over the top of those for the parent theme.

Co-authored with @MaggieCabrera.

## How has this been tested?
Checkout this PR: https://github.com/Automattic/themes/pull/4807
The child theme behaves the same as before!

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-10-08 12:21 UTC, aristath commented on lib/class-wp-theme-json-resolver-gutenberg.php
> +				$parent_theme_json_class_instance = new WP_Theme_JSON_Gutenberg( $parent_theme_json_data );
```suggestion
				$parent_theme_json_data           = self::read_json_file( get_template_directory() . '/theme.json' );
				$parent_theme_json_data           = self::translate( $parent_theme_json_data, wp_get_theme()->get( 'TextDomain' ) );
				$parent_theme_json_class_instance = new WP_Theme_JSON_Gutenberg( $parent_theme_json_data );
```

2021-10-08 12:21 UTC, mtias commented on lib/class-wp-theme-json-resolver-gutenberg.php
> +			// If this is a child theme we want to combine the theme.json from the child with the theme.json with the parent.
Should it be clarify that child theme takes precedence?

2021-10-08 12:22 UTC, aristath commented on lib/class-wp-theme-json-resolver-gutenberg.php
> +			// If this is a child theme we want to combine the theme.json from the child with the theme.json with the parent.
+1

2021-10-08 12:33 UTC, Mamaduka commented on lib/class-wp-theme-json-resolver-gutenberg.php
> +			if ( is_child_theme() ) {
```suggestion
			if ( wp_get_theme()->parent() ) {
```

The `is_child_theme()` function uses `TEMPLATEPATH` and `STYLESHEETPATH` constants. I believe those were causing some errors in the past.

2021-10-08 12:35 UTC, Mamaduka commented on lib/class-wp-theme-json-resolver-gutenberg.php
> +				$parent_theme_json_data           = self::translate( $parent_theme_json_data, wp_get_theme()->get( 'TextDomain' ) );
```suggestion
				$parent_theme_json_data           = self::translate( $parent_theme_json_data, wp_get_theme()->parent()->get( 'TextDomain' ) );
```

I think `wp_get_theme()->get( 'TextDomain' )` here will refer to current theme - child in this case.

2021-10-08 14:00 UTC, scruffian commented on lib/class-wp-theme-json-resolver-gutenberg.php
> +			// If this is a child theme we want to combine the theme.json from the child with the theme.json with the parent.
Done

2021-10-11 11:55 UTC, oandregal commented
:wave: We need to cover and test a few scenarios here:

1. Parent & child have theme.json => merge child with parent.
2. Parent has no theme.json and child does => return child.
3. Parent & child don't have theme.json => return child (empty).
4. Parent has theme.json but child does not => use parent.

I was testing the second scenario and it reports an error because the parent's `theme.json` does not exist. I've tested this by creating a child theme of TT1-blocks (with `style.css` and `theme.json` files) and then remove the theme.json of TT1-blocks.

2021-10-11 12:28 UTC, oandregal commented
The current `get_theme_data` merges `theme.json` data upon the existing theme supports, if any is provided. This is, we use data provided via `add_theme_support` to retrofit `theme.json`, but the `theme.json` data has higher priority.

At https://github.com/WordPress/gutenberg/pull/34843 I'm working on some code simplifications but we essentially have two code paths:

- in one, we are able to pull the "theme supports" directly from the theme ([see](https://github.com/WordPress/gutenberg/blob/fb481b7e32917d50021332d6e713642993ffaac0/lib/compat/wordpress-5.8/block-editor.php#L172))
- in other, the "theme supports" come from a filter (`block_editor_settings`), and any 3rd party plugin can filter them and some hosts do use it ([see](https://github.com/WordPress/gutenberg/blob/fb481b7e32917d50021332d6e713642993ffaac0/lib/global-styles.php#L112)).

So I was thinking about how the "theme supports" of the parent theme fit in this new scenario.

As far as I've tested, it seems theme supports are inherited by the child. I've tested this by creating a child of TwentyTwentyOne and verifying that the child still has support for line height and links as declared by the parent, as well as it takes palettes from the parent. I've also looked into `gutenberg_get_default_block_editor_settings` and `get_from_editor_settings` to confirm that we only use retrofit things that are declared via "theme supports", hence they'll work fine in the child.

Just wanted to bring it up to make sure others check this as well, in case I've missed anything.

2021-10-11 12:34 UTC, oandregal commented
Follow-up on my comment [above](https://github.com/WordPress/gutenberg/pull/35459#issuecomment-939985334). I've tried to _remove_ theme support in the child theme by doing:

```php
function twenty_twenty_one_child_setup() {
        remove_theme_support( 'experimental-link-color' );
        remove_theme_support( 'custom-line-height' );
}
add_action( 'after_setup_theme', 'twenty_twenty_one_child_setup' );
```

but it didn't work. I still saw the link panel and the line-height control in the block sidebar. Not sure if I'm doing something wrong.

2021-10-15 08:17 UTC, Mamaduka commented
👋  I just pushed some updates. It should fix the issue @oandregal reported when a parent has no theme.json, but the child does.

### Method changes

* The `get_file_path_from_theme` now has "directory" flag, based on this it will return path for `template` or `stylesheet`.
* The `theme_has_support` works the same way and returns true if the parent or child theme has a `theme.json` file.

### In Progress

Currently working on integration tests for this scenario - "Parent & child have theme.json => merge child with a parent."

I think other cases outlined by Andre are straightforward, and we can unit test those with the `WP_Theme_JSON_Gutenberg::merge` method.


### Re: `remove_theme_support`

Andre, you'll need to use higher priority with child theme's remove hook callback. It is because theme support needs to be registered first for WP to remove.

Can you try this example?

```php
function twenty_twenty_one_child_setup() {
        remove_theme_support( 'experimental-link-color' );
        remove_theme_support( 'custom-line-height' );
}
add_action( 'after_setup_theme', 'twenty_twenty_one_child_setup', 15 );
```

2021-10-15 11:10 UTC, Mamaduka commented
I added integration tests for parent/child theme data merging. Let me know if we want to cover more cases.

The `WP_Theme_JSON_Gutenberg` has excellent test coverage as well. I don't think we need more tests there for now.

2021-10-18 13:02 UTC, aristath requested changes

2021-10-18 13:02 UTC, aristath commented on lib/class-wp-theme-json-resolver-gutenberg.php
> +		return is_readable( $candidate ) ? $candidate : '';
Can't we simplify this using `get_theme_file_path()`?

```suggestion
	private static function get_file_path_from_theme( $file_name ) {
		$path = get_theme_file_path( $file_name )
		return is_readable( $path ) ? $path : '';
```

2021-10-18 13:09 UTC, Mamaduka commented on lib/class-wp-theme-json-resolver-gutenberg.php
> +		return is_readable( $candidate ) ? $candidate : '';
That's how I initially did it when I introduced basic FSE support for child themes. But now, data is always merged instead of inherited or entirely overridden.

P.S. Your suggestion will return a boolean instead of the path.

2021-10-18 13:13 UTC, aristath commented on lib/class-wp-theme-json-resolver-gutenberg.php
> +		return is_readable( $candidate ) ? $candidate : '';
Ah OK, now I understand what you did 👍 

> P.S. Your suggestion will return a boolean instead of the path.

Oops... you're right. fixed the suggestion and marking this as resolved 👍

2021-10-18 13:13 UTC, aristath approved these changes

2021-10-18 13:16 UTC, Mamaduka commented on lib/class-wp-theme-json-resolver-gutenberg.php
> +		return is_readable( $candidate ) ? $candidate : '';
Thank you, Ari ❤️

2021-10-18 13:18 UTC, merged

2021-10-19 11:35 UTC, oandregal commented
> ### Re: `remove_theme_support`
> 
> ```php
> function twenty_twenty_one_child_setup() {
>         remove_theme_support( 'experimental-link-color' );
>         remove_theme_support( 'custom-line-height' );
> }
> add_action( 'after_setup_theme', 'twenty_twenty_one_child_setup', 15 );
> ```

@Mamaduka @aristath I've tried with this and it still doesn't work.

This is my setup:

- Created a child theme of TT1-blocks with `style.css` and `functions.php`.
- Added that code to `functions.php`.
- Loaded the editor and I still see the link and line height UI controls.

I've also tried adding a `theme.json` to the child and setting those things to false there and this works as expected.

2021-10-19 11:37 UTC, oandregal commented on phpunit/class-wp-theme-json-resolver-test.php
> +	function test_merges_child_theme_json_into_parent_theme_json() {
Thanks for this!

2021-10-19 11:40 UTC, Mamaduka commented
@oandregal That's interesting.

Let's create a separate issue for tracking. I'll try to have a look tomorrow morning.

2021-10-19 11:48 UTC, oandregal commented on phpunit/class-wp-theme-json-resolver-test.php
> +	function test_merges_child_theme_json_into_parent_theme_json() {
In https://github.com/WordPress/gutenberg/pull/35759 I tweak a bit the test so that we test that single parts can be updated by the child while the untouched parent sections remain the same (the current tests checks that all the child sections override the parent).

2021-10-19 12:27 UTC, oandregal commented
Created https://github.com/WordPress/gutenberg/issues/35762

2021-10-21 08:30 UTC, briceduclos commented
@Mamaduka In the previous version, the `get_file_path_from_theme()` function was calling `get_theme_file_path()`. It allows developers to filter the path of the theme.json file using the `theme_file_path` filter. It is useful as it is the only way to modify the theme.json. Is it possible to reinclude the call to `get_theme_file_path()`?

2021-10-21 08:45 UTC, Mamaduka commented
Hi, @briceduclos. Thanks for contributing!

What's the use case for filtering the `theme.json` path?

The reason I removed `get_theme_file_path` is that it doesn't work with merge logic. The `get_theme_file_path` will always return the file path from the stylesheet/child theme when it's available. It means we were always getting the same file for parent or child, and the merge never happened.

2021-10-21 09:05 UTC, briceduclos commented
@Mamaduka Thanks for the reply. I've built a plugin that includes a setting that allows the user to select a different theme.json file to change the site configuration.

2021-10-21 09:22 UTC, Mamaduka commented
@briceduclos, thanks for the additional details.

@oandregal, do we have a different filter that plugins can use to override theme.json settings?

2021-10-21 09:30 UTC, oandregal commented
Plugins can use the existing filters we use in the Gutenberg plugin, see https://github.com/WordPress/gutenberg/issues/27504#issuecomment-858761483

There's been a few places in which specific filters for global styles have been brought up, but there's been no progress on that front yet. The first step is landing https://github.com/WordPress/gutenberg/pull/34843 that adds an API to get data out from theme.json.

2021-10-21 09:31 UTC, Mamaduka commented
Thanks, @oandregal!