Documentation: add a more detailed guide for react native development
WordPress/gutenberg pull request #35529
Opened 2021-10-11 22:26 UTC by gwwar

This PR adds some clearer first time setup instructions for react native development. I'd also be open to moving this to a separate how-to-guide, if we'd like to keep the current doc brief.

I also have images and video assets I can link to (really necessary for some of the android studio screens) but I'd be interested in knowing where the best place to add this would be. I do see an [assets](https://github.com/WordPress/gutenberg/tree/trunk/docs/assets) folder, but we probably don't want to add image/videos to the repository to avoid bloating repository size.

### Testing Instructions

- Verify that instructions are clear
- If you don't have native development going locally, give the instructions a try!

2021-10-12 10:40 UTC, hypest commented
Thanks for the ping @gziolo and yeah, thanks for opening this ticket @gwwar !

Let me reel in @SiobhyB that has some recent interest in the topic. 👍

2021-10-12 15:42 UTC, gwwar commented
So chatting with @mkaz it sounds like it's not ideal to add image/video assets to the Gutenberg repository (since it'll bloat the repository). One way we can work around this is to add these assets to the media library of one of the WordPress.org blogs.

Let me know if folks prefer keeping this as one setup doc, or if it'd be more ideal to make a separate how to article. And of course if there are simpler steps or if I mis-noted anything! For Android setup in particular it took me quite a while to figure out the right path arguments.

2021-10-12 17:43 UTC, SiobhyB commented
Wow, this is all so detailed and awesome, thank you for the time putting it together @gwwar 🙇‍♀️ 

I like your thoughts on splitting this off into a separate doc. It feels a bit hard to parse at the length it is now and there's a chance not everyone getting set up is going to need these steps (for example, a new contributor already working with React Native will probably have gone through them). We'd also want to link to these detailed steps from the Gutenberg Mobile repository's README. 

So, all in all, a separate doc with _only_ these steps seems like the best move to me. If you agree with that reasoning, let me know if I can help with any part of separating this out and I'll be happy to review again when it's done :)

2021-10-14 22:13 UTC, gwwar commented
Reserving this comment for assets. Folks are welcome to contribute better quality ones. If folks agree, we'll want to add these to the media library of one of the wp.org blogs, then link to them in the how to guide.

![cleanshot-2021-10-07-at-15 32 34402x](https://user-images.githubusercontent.com/1270189/137403960-f3a941c1-82cb-424b-9c5e-8209de695140.png)

![cleanshot-2021-10-07-at-15 20 02402x](https://user-images.githubusercontent.com/1270189/137403874-5106ea07-7710-4a0d-847b-91e2d4217181.png)

https://user-images.githubusercontent.com/1270189/137405310-765ef960-acca-49ed-a2eb-b87b6bb970e9.mp4

<img width="1094" alt="package-manager" src="https://user-images.githubusercontent.com/1270189/137402776-90941bd1-999e-4e95-bb20-4adeea88f793.png">

<img width="1262" alt="show package details" src="https://user-images.githubusercontent.com/1270189/137402862-2c14ed76-b2de-49e5-a670-343c0d5c27e9.png">

<img width="824" alt="screen-shot-2021-04-29-at-3 25 57-pm" src="https://user-images.githubusercontent.com/1270189/137402907-68dd31ff-d26a-4310-9629-f5fbc7fe82dc.png">

![screen-shot-2021-04-29-at-4 53 19-pm](https://user-images.githubusercontent.com/1270189/137402946-196194b7-c4b1-425f-bc52-1a0955a07a35.png)

<img width="811" alt="screen-shot-2021-04-29-at-4 56 24-pm" src="https://user-images.githubusercontent.com/1270189/137402976-821ffa63-e538-4988-ac59-17f57fcbef9d.png">

![avd](https://user-images.githubusercontent.com/1270189/137403015-6e48ba87-aa3d-45bd-bb2e-e20ffb8b5814.png)

![screen-shot-2021-04-30-at-8 16 03-am](https://user-images.githubusercontent.com/1270189/137403078-422ad773-6c9a-4b7f-98f7-ea08a6c20cf9.png)

![screen-shot-2021-04-30-at-8 16 53-am](https://user-images.githubusercontent.com/1270189/137403119-447ab58f-c4df-4776-ab95-2f315a070f42.png)

![screen-shot-2021-04-30-at-8 17 09-am](https://user-images.githubusercontent.com/1270189/137403157-efe2a2d0-ffec-4d50-b55a-5d909583728b.png)

![screen-shot-2021-04-30-at-8 20 58-am](https://user-images.githubusercontent.com/1270189/137403190-4f23b96f-e08a-4678-9f12-4aa848ce57bd.png)

https://user-images.githubusercontent.com/1270189/137403245-8e13acc8-27fa-4876-a52e-d497ab65a29d.mp4

![screen-shot-2021-04-30-at-8 41 54-am](https://user-images.githubusercontent.com/1270189/137403302-af2c1677-e06b-49fc-89dd-3fe18cbbc5a0.png)

https://user-images.githubusercontent.com/1270189/137403353-2a8ded47-5c7c-4f99-b2cc-fa6def4b4990.mp4

![screen-shot-2021-04-30-at-8 50 11-am](https://user-images.githubusercontent.com/1270189/137403378-dd8e08a8-3745-412c-83ce-1611d2458a0a.png)

![android-e2e](https://user-images.githubusercontent.com/1270189/137403475-1e061758-05f2-4177-ba45-3c356e485900.png)

2021-10-14 22:22 UTC, gwwar commented
@SiobhyB sounds good, I've moved instructions into a how-to guide in https://github.com/WordPress/gutenberg/pull/35529/commits/aea287c9808db4f4af7094dc4d3312009e9319b9

Let me know if any of the instructions are incorrect or if we should clarify wording!

2021-10-21 22:46 UTC, gwwar commented on docs/how-to-guides/native-mobile/osx-first-time-setup-guide.md
> +export JAVA_HOME=/Applications/Android\ Studio.app/Contents/jre/jdk/Contents/Home
Reminder to note that this changed to a slightly different path in Arctic Fox
```
export JAVA_HOME="/Applications/Android Studio.app/Contents/jre/Contents/Home"
```

2021-10-25 13:17 UTC, SiobhyB requested changes
Thanks again for all the work on this @gwwar, I've added a few small comments/suggestions throughout, but it generally all looks excellent 🙇‍♀️

2021-10-25 13:17 UTC, SiobhyB commented on docs/how-to-guides/native-mobile/osx-first-time-setup-guide.md
> +In another terminal run the following. The emulator doesn’t need to be launched previously.
```suggestion
In another terminal run the following to launch the demo app in the Android emulator (if the emulator isn't already running, it'll also be launched as part of this command):
```
How about tweaking the wording here? I wasn't clear on the mention of the emulator at first.

2021-10-25 13:17 UTC, SiobhyB commented on docs/how-to-guides/native-mobile/osx-first-time-setup-guide.md
> +See if doctor can fix both "common" and "iOS" issues. At this stage "Android" will still have ❌s for items.
```suggestion
See if `doctor` can fix both "common" and "iOS" issues. (Don't worry if "Android" still has ❌s at this stage, we'll get to those later!)
```
As we can't be certain that the reader won't have their Android set up ready at this point, how about the tweaked wording to account for that?

2021-10-25 13:17 UTC, SiobhyB commented on docs/how-to-guides/native-mobile/osx-first-time-setup-guide.md
> +export ANDROID_HOME=/Users/{your-username}/Library/Android/sdk
@gwwar, I'm curious whether the following paths also work for you? These are what I have in my `~/.zshrc` file, which I got from [the React Native docs:](https://reactnative.dev/docs/environment-setup):

```
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
```
As those are directly from the official docs, I'd lean towards using them, but let me know if they don't work as expected for you.

2021-10-25 13:17 UTC, SiobhyB commented on docs/how-to-guides/native-mobile/osx-first-time-setup-guide.md
> +OSX environment.
```suggestion
OSX environment. For other environments, [the React Native quickstart documentation](https://reactnative.dev/docs/environment-setup) has helpful pointers and steps for getting set up.
```
How about pointing to the RN doc here in case someone needs guidance for other environments?

2021-10-25 21:09 UTC, gwwar commented on docs/how-to-guides/native-mobile/osx-first-time-setup-guide.md
> +export ANDROID_HOME=/Users/{your-username}/Library/Android/sdk
They don't, but let me see if there's a way to consistently install in that directory.

Also is there a smarter way to install needed packages? I had to lookup needed items in the build.gradle file.

2021-10-25 22:44 UTC, gwwar commented on docs/how-to-guides/native-mobile/osx-first-time-setup-guide.md
> +OSX environment.
Updated in https://github.com/WordPress/gutenberg/pull/35529/commits/ada0609a2cc4568a1d4c51b7fb75c48c4ebe583d

2021-10-25 22:44 UTC, gwwar commented on docs/how-to-guides/native-mobile/osx-first-time-setup-guide.md
> +See if doctor can fix both "common" and "iOS" issues. At this stage "Android" will still have ❌s for items.
Updated in https://github.com/WordPress/gutenberg/pull/35529/commits/ada0609a2cc4568a1d4c51b7fb75c48c4ebe583d

2021-10-25 22:44 UTC, gwwar commented on docs/how-to-guides/native-mobile/osx-first-time-setup-guide.md
> +In another terminal run the following. The emulator doesn’t need to be launched previously.
Changes read well to me, updated in https://github.com/WordPress/gutenberg/pull/35529/commits/ada0609a2cc4568a1d4c51b7fb75c48c4ebe583d

2021-10-25 22:49 UTC, gwwar commented on docs/how-to-guides/native-mobile/osx-first-time-setup-guide.md
> +export ANDROID_HOME=/Users/{your-username}/Library/Android/sdk
So I do like the updated paths relative to `$HOME` 👍  I left a note inline on where the SDK home location can be modified. By default a new install on OSX will recommend `$HOME/Library/Android/sdk`

I also had to set JAVA_HOME. I pointed this at what comes with Android studio which is convenient. If there's a better alternative, I'm open to changes.

One other note is that I have a working environment on my Intel Mac but not my new M1. Currently getting stuck here with this trace:
<img width="1222" alt="CleanShot 2021-10-25 at 15 41 53@2x" src="https://user-images.githubusercontent.com/1270189/138781247-8c761d45-e4de-4e5f-8537-ea96e3270032.png">

2021-10-26 10:54 UTC, SiobhyB commented on docs/how-to-guides/native-mobile/osx-first-time-setup-guide.md
> +export ANDROID_HOME=/Users/{your-username}/Library/Android/sdk
> Also is there a smarter way to install needed packages? I had to lookup needed items in the build.gradle file.

I'm afraid the only way I'm aware of is manually looking up the needed packages (I did that through [the docs](https://reactnative.dev/docs/environment-setup) in my case, but your approach is also valid). I had a quick search to see if there were perhaps any Android Studio plugins to automate the process, but wasn't able to find anything. 

> One other note is that I have a working environment on my Intel Mac but not my new M1. Currently getting stuck here with this trace

@twstokes also ran into some problems running the demo app on an M1 and found he needed to install Platform S packages. These were the specific steps here shared:  

* In Android Studio, go to Preferences -> Appearance & Behavior -> System Settings -> Android SDK.
* Check “Show Package Details” at the bottom right.
* If not already selected, under “Android S Preview” check:
  * Android SDK Platform S
  * Google APIs ARM 64
  * Google Play ARM 64
* Click OK.

And a screenshot of his settings:

![screen-shot-2021-07-03-at-12 58 02](https://user-images.githubusercontent.com/2998162/138863109-0d553234-ecfc-40a2-8aac-e0fad63e81a2.png)

Another issue that Tanner came across is a bug that prevents the Android emulator from loading. This was in May, so hopefully, there will have been a fix by now. If not, Tanner followed the workaround outlined in [this Medium article](https://medium.com/mobile-app-development-publication/m1-android-emulator-not-detected-workaround-c7718f08ba99). 

I don't have an M1 but, if installing the Platform S packages doesn't get things working for you, we could see if Tanner or others on the project have further ideas here. Let me know how it goes! (and thank you again for all the work documenting this!)

2021-10-27 19:38 UTC, SiobhyB commented on docs/how-to-guides/native-mobile/osx-first-time-setup-guide.md
> +export ANDROID_HOME=/Users/{your-username}/Library/Android/sdk
Noting for posterity that, following https://github.com/WordPress/gutenberg/pull/36007 and the comment here https://github.com/WordPress/gutenberg/pull/36007#pullrequestreview-791037693, it doesn't seem like separate instructions for M1 are now necessary. 🎉

2021-10-27 19:40 UTC, SiobhyB approved these changes
This all looks good to me @gwwar, pending the updated references to the images you've suggested in your previous comment :)

2021-10-27 22:47 UTC, gwwar commented
Thanks @SiobhyB! I've also added image assets in https://github.com/WordPress/gutenberg/pull/35529/commits/04b03b2c70537331c631f32e655e495df58c99e7

cc @mkaz did you have any recommendations on formatting/readme location or does this look ok to land?

2021-10-28 17:54 UTC, mkaz commented
Looks great! Thanks so much for the updates, it'll make it easier to get more people started and involved 👍 

Can we rename the file to: `osx-setup-guide.md` ? 
Since it still applies even if it's not your first time, makes for a slightly cleaner URL.

Also, you will need to add an entry to `docs/toc.json` (see existing for syntax) and run `npm run docs:build` and commit the generated manifest.json file.

I suppose it doesn't quite matter where in the How to Guides section of the toc.json list. I'm trying to get it in alphabetical order (https://github.com/WordPress/gutenberg/pull/35904). I'll rebase and fix that ticket if yours goes in first.

2021-10-28 18:00 UTC, gwwar commented
Ah I knew I must have been missing something! Thanks @mkaz! updated in fbb0285

2021-10-28 18:03 UTC, mkaz commented
I just realized, since it's a new directory you may also want a README.md, I'm not really sure what it will do without. I'm ok with trying it as it is and we can add a README if needed.

2021-10-28 18:05 UTC, gwwar commented
Sure we can try as is, and see if we need to add an additional README.md as a follow up.

2021-10-28 20:09 UTC, gwwar commented
Going to rebase to see if unit test issues resolve themselves

2021-10-28 23:29 UTC, merged

2021-10-28 23:30 UTC, gwwar commented
Thanks for the reviews @SiobhyB @mkaz !