Improvement: Introducing new filter using which theme authors can modify whether the current theme supports FSE or not.
WordPress/gutenberg pull request #35616
Opened 2021-10-14 05:48 UTC by premanshup

## Description

This PR introduces a new filter `gutenberg_is_fse_theme` inside function `gutenberg_is_fse_theme` using which theme developers can filter whether the theme supports FSE or not.

Update FSE support - 
```
add_filter( 'gutenberg_is_fse_theme', '__return_false' );
add_filter( 'gutenberg_is_fse_theme', '__return_true' );
```

## How has this been tested?

Tested by adding the above filters and checking if they update the output for the function `gutenberg_is_fse_theme` or not. The function's value is updated, so the filter seems to be working as expected.

## Screenshots 

## Types of changes

Improvement (non-breaking change which adds functionality).

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-10-27 08:51 UTC, draganescu commented
Howdy! What is the filter for? The function allows a theme or plugin to know if it is FSE enabled or not. Filtering this can lead to false negatives or false positives.

2021-10-27 16:29 UTC, premanshup commented
> Howdy! What is the filter for? The function allows a theme or plugin to know if it is FSE enabled or not. Filtering this can lead to false negatives or false positives.

@draganescu I was thinking of this filter from the legacy ( non-FSE ) themes perspective, what if they could implement both HTML and PHP file/folder structure?

I'm thinking of a scenario where a theme could provide an option for users to switch from legacy theme to FSE theme or vice-versa.

From my finding, I think this is the main function ( `gutenberg_is_fse_theme` ) that enables/disables FSE support by checking if the index.html file exists or not. 

https://github.com/WordPress/gutenberg/blob/trunk/lib/full-site-editing/full-site-editing.php#L14

I was wondering if we can implement this filter so that legacy themes could be converted to FSE themes if needed or required by the users. I think the folder/file structure for FSE and legacy themes is different. One uses `.html` files and the other one uses `.php` files ( from what I have understood ). Adding this filter could open up new possibilities for existing themes? ( or I could be completely wrong ). My apologies if I'm missing anything here.

2021-10-28 13:53 UTC, premanshup commented
@draganescu Howdy! In addition to this, I have not yet checked how theme.json can be handled in both cases. I think there will be a need to handle the loading of the theme.json file. I will check in detail and see if that can be loaded conditionally as well?

2021-11-16 19:36 UTC, oandregal requested changes
Hey Premanshu, I don't think adding a filter to change whether the `theme.json` exists is a good idea: either it does or doesn't. If you can share your specific needs, someone can probably help to identify how that can be done, what needs to be adapted if anything, etc.

2021-11-25 12:33 UTC, premanshup commented
Hello @oandregal ! Thank you so much for your feedback. I have mentioned my concern here in the [issue](https://github.com/WordPress/gutenberg/issues/36864). Please let me know if we can implement the filter for theme.json based on the two points I have shared in the issue.

2025-04-07 11:23 UTC, Mamaduka commented
These methods are now part of WP core. Any related documentation should be improved, which probably has been fixed during code sync.

I'm going to close the PR. Thanks for contributing, @premanshup!

2025-04-07 11:23 UTC, closed without merging