Try: Remove color inheritance specificity.
WordPress/gutenberg pull request #35725
Opened 2021-10-18 09:55 UTC by jasmussen

## Description

Probably fixes #34648.

#31878 heavily refactored the navigation block CSS to reduce specificity of many selectors, so as to allow global styles to override colors. One part of that was also to override inherited colors. I don't recall the specifics, but this was necessary at the time to fix an issue with colors otherwise not inheriting at all. As a result, if you insert a Site Title block inside navigation, and customize its link color, that doesn't work:

<img width="1270" alt="before" src="https://user-images.githubusercontent.com/1204802/137708807-4b03e025-cd9a-4bbe-84c0-b7968a31fecf.png">

That extra specificity _doesn't appear to be necessary anymore_. And in removing it, things appear to work as they should:

<img width="1270" alt="Screenshot 2021-10-18 at 11 46 29" src="https://user-images.githubusercontent.com/1204802/137708877-8a3b6ed7-3940-46bc-868c-1c601250b250.png">

<img width="1270" alt="Screenshot 2021-10-18 at 11 47 14" src="https://user-images.githubusercontent.com/1204802/137708978-0c56c148-da7f-4d3f-9a0a-9ade12afc695.png">
 
<img width="1270" alt="Screenshot 2021-10-18 at 11 47 21" src="https://user-images.githubusercontent.com/1204802/137708982-70e1fccd-6fd1-4219-99b7-e1421141b9c1.png">

Because the rule was necessary at the time, but doesn't appear to be necessary anymore, it would be good to test this one well.

## How has this been tested?

Here's some test content:

```

```

Please test in a few themes, including Empty Theme and some block themes. In combination with having a site title with a customized link color, please test most of the navigation properties and features, including all the color options, most notably _submenus_ and the mobile responsive _overlay menu_, and verify that the colors defined on the navigation block apply all the way down the hierarchy, unless overridden by an individual block.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-10-18 13:10 UTC, aristath approved these changes
LGTM 👍

2021-10-18 13:48 UTC, jasmussen commented
Thanks so much for the green light. I'm tempted to land this because it's such a small change.

However it's at a sensitive place in the code, so I'd love to just boost the confidence level even more with a few more reviews, if people have time. Thanks!

2021-10-18 16:30 UTC, ockham commented
Thanks a lot, @jasmussen!

I'm seeing the following with TT1 Blocks. This obviously seems fine for the Site Title; I am however not entirely sure about the navigation links. Are they supposed to respect the text color, i.e. should they be red (as the 3rd screenshot in the PR description seems to indicate)?

![image](https://user-images.githubusercontent.com/96308/137770858-7bf8817d-09ee-44b3-8860-d862cf1ac706.png)

2021-10-18 16:35 UTC, ockham commented
Ah, the navigation links are red on the frontend:

![image](https://user-images.githubusercontent.com/96308/137772301-a92838be-ca1d-45af-853f-085cf63a1987.png)

2021-10-18 16:35 UTC, ockham requested changes
See my comments -- seems like we need to tweak this a bit more 😅

2021-10-18 16:37 UTC, jasmussen commented
Yes, excellent catch, I just verified that I see this in trunk:
<img width="1160" alt="Screenshot 2021-10-18 at 18 36 08" src="https://user-images.githubusercontent.com/1204802/137772468-b9e53863-39a2-4312-8e34-578a3b2bc0f5.png">

And this in this branch:
<img width="764" alt="Screenshot 2021-10-18 at 18 36 17" src="https://user-images.githubusercontent.com/1204802/137772480-dd05de42-6fba-450f-bc1b-07198fdabf67.png">

I knew it was too good to be true 🙈 but it is encouraging that things work as they should on the frontend, that's a tip for a fix, probably.

2021-10-18 16:41 UTC, jasmussen commented
So just to chalk up the problem, it appears that this editor style (or theme.json property):
<img width="426" alt="Screenshot 2021-10-18 at 18 38 45" src="https://user-images.githubusercontent.com/1204802/137772879-c765dd18-53f4-42e0-8fd8-27c1e9bb3451.png">

... wins over the rule we tweaked:

<img width="431" alt="Screenshot 2021-10-18 at 18 40 12" src="https://user-images.githubusercontent.com/1204802/137773000-1b369b22-81ec-4647-b7b6-a673c2b48833.png">

... to inherit this inline style attribute:

<img width="413" alt="Screenshot 2021-10-18 at 18 38 53" src="https://user-images.githubusercontent.com/1204802/137772911-acf1eab8-f4a9-4c36-9fd3-b734e3b4aabb.png">

So at least that reminded me why I mentioned needing to override a value from "global styles". I'll need to find a different path forward here, and I'll put my thinking hat on.

2021-10-18 16:58 UTC, jasmussen commented
Alright, I tried targetting a classname instead of an element, to carefuly thread the specificity needle if at all possible. So it's now `.wp-block-navigation .wp-block-navigation-item__content` instead of `.wp-block-navigation a`. That seems to allow the navigation block to inherit theme styles and global styles, but still override those if a user sets them. Here's what I see:
<img width="695" alt="Screenshot 2021-10-18 at 18 49 10" src="https://user-images.githubusercontent.com/1204802/137775324-034ca60a-0849-4011-89f8-29718f0a2ebb.png">
<img width="773" alt="Screenshot 2021-10-18 at 18 49 16" src="https://user-images.githubusercontent.com/1204802/137775339-34f6b2fe-4577-4407-bb77-75a00c582dc3.png">

I had to move a padding rule as well due to a "no-duplicate-selectors" eslint rule catching me. And I'd still appreciate a good testing for this one. It's not a lot of code, but it's a careful balance.

2021-10-18 18:54 UTC, ockham approved these changes
Thanks Joen, this seems to be working well now! Tested with TT1 Blocks (with submenu, also testing the mobile overlay menu), Empty Theme, TT1, Twenty Twenty, Twenty Nineteen.

2021-10-18 18:55 UTC, jasmussen commented
Sweet, thank you, and thanks everyone. I'm going to test this one a bit more tomorrow, then land it.

2021-10-19 09:19 UTC, jasmussen commented
I tested a rebased version of this with TT1 blocks again, empty theme, and Blockbase, and things still appear to work. So I'm going to land this one as is, but I would appreciate those of you receiving this message to help keep an eye out for any text-color/global styles related navigation block issues that might have resulted from this.

2021-10-19 09:19 UTC, merged