Post Comments block: hide the "Comments Closed" message
WordPress/gutenberg pull request #35743
Opened 2021-10-18 21:16 UTC by jffng

## Description
Solves https://github.com/WordPress/gutenberg/issues/35732. 

This PR changes the Post Comments rendering to hide the "Comments are closed" message when the following conditions are met:

- Comments are closed
- There are no comments to display
  
## How has this been tested?

1. Check out this PR: https://github.com/WordPress/twentytwentytwo/pull/127
2. Ensure "Allow comments" is disabled on the post, and no comments exist
3. Verify that no post comments markup is rendered
4. Go to a post with comments and verify they still appear

## Screenshots 

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-10-19 16:45 UTC, scruffian commented
I was seeing a notice when the attribute wasn't set. I added a commit to fix that.

2021-10-21 09:17 UTC, SantosGuillamot commented
I've been taking a look and it seems to be working fine! I think I am not the best person to review the code, but I checked how it works in the editor 🙂 .

> Note that no UI is added in this PR, since I am not sure this approach aligns with the work being doing on the Comments Template block #35000.

Regarding this, there is still not progress on the Comments Template block, but this is for sure something to consider. I will post it there so it isn't missed.

2021-10-21 09:54 UTC, aristath requested changes

2021-10-21 09:54 UTC, aristath commented on packages/block-library/src/post-comments/index.php
> +	}
Would it not be more efficient to early return instead of adding an extra class? 🤔 
This way if the post doesn't have comments and we want to hide comments-closed, no HTML will be rendered (as opposed to printing it and then hide it via CSS)

```suggestion
	if ( ! comments_open( $post_id ) && ! empty( $attributes['hideCommentsClosed'] ) && $attributes['hideCommentsClosed'] ) {
		$args = array(
			'post_id' => $post_id,
			'count'   => true,
		);
		if ( ! get_comments( $args ) ) {
			return;
		}
	}
```

2021-10-21 13:44 UTC, jffng commented on packages/block-library/src/post-comments/index.php
> +	}
I considered an early return, but decided against it because the message would still show if there are comments. 

If we're okay only hiding the message if there are no comments, then I'd much prefer this approach!

2021-10-21 16:15 UTC, kjellr commented on packages/block-library/src/post-comments/index.php
> +	}
I think that’s fine. The issue is just that the message shows when there are no comments _and_ comments are closed.

2021-10-21 16:17 UTC, kjellr commented on packages/block-library/src/post-comments/index.php
> +	}
But actually… should that just be the default behavior of the block then? Rather than something that’s opted into?

- If comments are closed, show the message. 
- If comments are closed *and* there are no comments, don’t show the message.


I can’t think a reason why you would want this message showing up under that second scenario. 🤔

2021-10-25 15:57 UTC, jffng commented
Updated the PR based on the suggestion and logic described [here](https://github.com/WordPress/gutenberg/pull/35743#discussion_r733513542), so no CSS is needed. I also updated the original PR description. It should be ready for another review.

2021-10-25 16:16 UTC, jffng commented
Another thought — what if we got rid of the attribute altogether, and just returned early if comments are closed and there are no comments.

2021-10-25 16:16 UTC, kjellr commented
> Another thought — what if we got rid of the attribute altogether, and just returned early if comments are closed and there are no comments.

Yeah, this seems like the right move to me.

2021-10-26 10:06 UTC, aristath approved these changes
Thank you for the changes!
LGTM 👍

2021-10-26 12:38 UTC, kjellr approved these changes
This works well in my testing too. Should be good to merge once tests pass. 👍

2021-10-26 14:47 UTC, merged