Template Part Block: Add some guards
WordPress/gutenberg pull request #36324
Opened 2021-11-08 20:05 UTC by ockham

Carried over from https://github.com/WordPress/wordpress-develop/pull/1796.
props @hellofromtonya

## Description

Quoting https://github.com/WordPress/wordpress-develop/pull/1796/files#r744135286:

> `file_get_contents()` returns `false` on failure. `_inject_theme_attribute_in_block_template_content()` expects a `string` data type. Within the deeper logic (i.e. in `WP_Block_Parser::next_token()`) the content is passed as the 2nd argument to `preg_match`. That argument requires a non-nullable string.
>
> To avoid possible PHP 8.1 deprecation notices and future PHP 9 fatal error, I'd suggest:

## How has this been tested?
Verify that block-based themes continue to work.

## Types of changes
Code quality

2021-11-09 06:09 UTC, aristath requested changes

2021-11-09 06:09 UTC, aristath commented on packages/block-library/src/template-part/index.php
> +						: '';
`file_get_contents` can return a string, or a false value. With that in mind, this part of the code can be simplified:
```suggestion
				$content = ( $content )
						? _inject_theme_attribute_in_block_template_content( $content )
						: '';
```

2021-11-09 06:15 UTC, aristath commented on packages/block-library/src/template-part/index.php
> +						: '';
Actually they are both valid, and the original - though longer - is more readable so ignore this comment 👍

2021-11-09 06:15 UTC, aristath approved these changes

2021-11-10 13:37 UTC, ockham commented
Thanks @aristath!

2021-11-10 14:28 UTC, merged