Add content values when updating text-columns column-count
WordPress/gutenberg pull request #3643
Opened 2017-11-24 11:10 UTC by Xyfi

## Description

Fixes bug #3630. When the `setAttributes` action is called when updating the column count is incremented, additional content elements are pushed to the array.

I've decided not to delete text in columns that are removed. Is this desirable? Maybe only remove data in removed columns when saving the post?

## How Has This Been Tested?

It has been tested by updating the column count of the Text Columns block, saving it and reloading the editor. If you know a way to unit test this, please advice.

## Screenshots (jpeg or gifs if applicable):

## Types of changes

Bug fix

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

2017-11-27 16:54 UTC, aduth requested changes

2017-11-27 16:54 UTC, aduth commented on blocks/library/text-columns/index.js
> +									content.push( '' );
[`Array#push`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push) is mutative, which is a no-go with React props:

https://reactjs.org/docs/components-and-props.html#props-are-read-only

You'd want to work a copy, for example:

```js
const nextAttributes = { columns: value };
if ( value > content.length ) {
	nextAttributes.content = [
		...content,
		...times( content.length - value, [] ),
	];
}

setAttributes( nextAttributes );
```

See also: https://lodash.com/docs/4.17.4#times

2017-11-27 16:54 UTC, aduth commented on blocks/library/text-columns/index.js
> +									content.push( '' );
Also noting that I don't think we need (or want?) the empty string as a child of `content`, rather an empty array (see `default` value).

2017-12-18 11:19 UTC, Xyfi commented
Since the issue has been solved this PR can be closed.

2017-12-18 11:19 UTC, closed without merging