Block Library: Add the Comments Pagination block
WordPress/gutenberg pull request #36577
Opened 2021-11-17 16:35 UTC by DAreRodz

## Description

This block works as a container for other pagination blocks that render links to navigate through the list of comments. It basically works the same as the [Query Pagination block](packages/block-library/src/query-pagination), but for comments.

It has the same settings:
- changing layout and colors
- choosing different styles for next/prev arrows. 

Will close #35007

## How has this been tested?

1. Modify the Single Post template, adding a Comments Query Loop block
2. Add inside the Comments Pagination block
3. Check that the layout and color settings work (tested only in the editor)
4. Check that the arrow setting works as expected (tested only in the editor)

## Types of changes
- New feature

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] I've tested my changes with keyboard and screen readers. 
- [x] My code has proper inline documentation. 
- [x] I've included developer documentation if appropriate. 
- [x] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-11-17 16:37 UTC, DAreRodz commented on packages/block-library/src/comments-pagination/edit.js
> +	[ 'core/query-pagination-next' ],
These blocks are meant to be changed once the rest of the `comments-pagination` blocks are created.

2021-11-17 16:39 UTC, DAreRodz commented on packages/block-library/src/comments-pagination/edit.js
> +			'core/query-pagination-next',
Again, these blocks should be replaced with the `comments-pagination` ones.

2021-11-17 17:26 UTC, c4rl0sbr4v0 requested changes
Nice job! It seems that we have to include the schema in order to pass the tests.
Also, do we have to create the fixtures? In order to do that, we have to create the core__comments-pagination-block.html with the content that is created on the code editor. Then paste it and then run `npm fixtures:generate`

2021-11-17 17:26 UTC, c4rl0sbr4v0 commented on packages/block-library/src/comments-pagination/block.json
> +{
"$schema": "https://schemas.wp.org/trunk/block.json",

2021-11-17 17:26 UTC, c4rl0sbr4v0 commented on packages/block-library/src/comments-pagination/block.json
> +{
We need to add the schema there.

2021-11-17 22:28 UTC, DAreRodz commented
Thanks for the review @c4rl0sbr4v0 :bow: You're right, I forgot to add the fixture for the new block. Fixed now. :+1:

2021-11-18 08:54 UTC, c4rl0sbr4v0 commented
Next question I have is. Should we merge it before having the other ones (core/comment-pagination-*? How would we approach this?

Leaving as is right now, it does not crash, right?

2021-11-18 11:11 UTC, gziolo commented
> Next question I have is. Should we merge it before having the other ones (core/comment-pagination-*? How would we approach this?

Yes, we can also land this PR without inner blocks and address that in follow-up PRs. If we take that route we should rather hide this block from the inserter temporarily.

2021-11-23 11:46 UTC, aristath commented
The PR needs to be rebased as there are now conflicts with `trunk` 👍

2021-11-25 14:07 UTC, c4rl0sbr4v0 commented
> Yes, we can also land this PR without inner blocks and address that in follow-up PRs. If we take that route we should rather hide this block from the inserter temporarily.
> The PR needs to be rebased as there are now conflicts with trunk 👍

I updated the code with the requests and created a new PR, cherry-picking @DAreRodz commits. It is easier for me than making the updates on their repo. And also I included in this PR a Merge commit without wanting to.

#36872 closes this PR.

2021-11-25 14:07 UTC, closed without merging