[Block Library - Query Pagination] Simplify pagination blocks
WordPress/gutenberg pull request #37125
Opened 2021-12-04 11:12 UTC by ntsekouras

Recently in this PR: https://github.com/WordPress/gutenberg/pull/36681, there were some changes to Query Pagination blocks which aimed to render a hidden placeholder element for design purposes, if I understand correctly for now.

I'm not sure if the problem could be solved with another `layout` (other than the currently used `flex`) but for now we  should at least try to simplify the code to achieve this.

There are some things that need to be investigated:
- [x] center align regression
- [ ] leaked specific block logic to the `layout` abstraction
- [ ] logic inside the `next/previous` pagination blocks

The PR's description will be updated as I'm looking through the needed changes. 

--cc @MaggieCabrera @scruffian  @matiasbenedetto

2021-12-04 11:27 UTC, scruffian commented
@matiasbenedetto started some of this work in https://github.com/WordPress/gutenberg/pull/37113

2021-12-06 16:24 UTC, matiasbenedetto requested changes

2021-12-06 16:24 UTC, matiasbenedetto commented on packages/block-library/src/query-pagination-next/index.php
> +			'style'       => 'visibility:hidden;',
I don't see why an inline style written in PHP is better than a CSS rule. I'm wondering why do you prefer this?

2021-12-06 16:24 UTC, matiasbenedetto commented on packages/block-library/src/query-pagination-previous/index.php
> +			'style'       => 'visibility:hidden;',
Adding PHP logic to add styles doesn't seem to be the best option. I think it adds complexity and makes the elements harder to style with themes.

2021-12-06 16:59 UTC, matiasbenedetto commented
The changes on the logic to output the placeholder, the link, or nothing are not working well with this PR on some edge cases. As I [previously mentioned](https://github.com/WordPress/gutenberg/pull/36681#discussion_r762068371) we need to consider 2 conditions in order to know what we need to render.

Example for the Previous component:
1. Are there contents to paginate:
    - No: Render nothing
    - Yes: Consider the next condition...
2. Are we on the first page:
    - No: Render the Link
    - Yes: Render the Placeholder


With these changes we are rendering Previous and Next links for example when there are no contents to paginate and that's an error:
![image](https://user-images.githubusercontent.com/1310626/144888885-c7c6545f-77f6-4c34-b72c-ac74186ae07b.png)

2021-12-06 17:37 UTC, matiasbenedetto commented
Summarizing the concerns that motivated this PR:

1. Center align regression: Use the CSS from this PR: `&.aligncenter {
		justify-content: center;
	}
	`

2. Leaked specific block logic to the layout abstraction. (Potential fix: https://github.com/WordPress/gutenberg/pull/37113)

3. Logic inside the next/previous pagination blocks (It is working ok how it is right now. Please see the comment: https://github.com/WordPress/gutenberg/pull/37125#issuecomment-986966379)

4. Avoid repeated code. (Potential fix: https://github.com/WordPress/gutenberg/pull/37155)

2021-12-06 18:34 UTC, ntsekouras commented
👋 - thanks for reviewing @matiasbenedetto !

>Summarizing the concerns that motivated this PR:

1 and 2 needs to be fixed, but this PR was mostly about the new added logic there, which seemed to me at first quite complex.

Personally the concept of adding an extra element (hidden wrapper) for design purposes seems a bit odd to me and I'm not really sure if this should be added in the first place. Would another kind of layout be a better fit for these blocks (even if it doesn't exist yet like `grid`)? If yes, could this be something that a theme could accomplish with css overrides until it's properly implemented in `core/GB`?

Then I noticed that especially in the case of `inherit the global` query case there was logic added, which to me it seems like trying to duplicate the [get_next_posts_link](https://developer.wordpress.org/reference/functions/get_next_posts_link/) and [get_previous_posts_link](https://developer.wordpress.org/reference/functions/get_previous_posts_link/).

Having said that, the example you shared about the `next page` link when a custom query has no results at all, is a bug and an extra check of `max_num_pages` should be added.

Because of that bug in this use case (custom query with no results) it was possible to go to a non-existing page and see a similar wrong link for `previous page`. But.. if we fix the above bug, the only way to go to such a page is by changing the `query params` in the `url`. Is this something we should handle more gracefully by adding more complexity? If we go to an archive page and edit manually the url to something like that `http://localhost:8888/page/33333/` we will get a `404` page.

Actually I'm going to close this PR for now and will comment in the original PR with parts of this response and my thoughts.

2021-12-06 18:34 UTC, closed without merging