Accessibility improvements for Columns and Column blocks.
WordPress/gutenberg pull request #37304
Opened 2021-12-11 05:00 UTC by alexstine

## Description

Possible fix for: #30620

Accessibility improvements for Columns and Column blocks.
- Render Columns as grid and Column as gridcell.
- Add note on how to navigate the Columns/Column blocks via aria-describedby.

## How has this been tested?

Tested with NVDA screen reader on Windows 10 in Firefox.

## Screenshots 

## Types of changes

Bug fix

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal).

2021-12-13 13:16 UTC, aristath requested changes

2021-12-13 13:16 UTC, aristath commented on packages/block-library/src/columns/edit.js
> +	const ariaDescribedById = sprintf( '%s-description', clientId );
Do we really need `sprintf` here? 🤔 I believe we can accomplish the same result concatenating with backticks.
```suggestion
	const ariaDescribedById = `${ clientId }-description`;
```

2021-12-13 13:16 UTC, aristath commented on packages/block-library/src/columns/edit.js
> +				of columns.
This will probably need to be translatable
```suggestion
				{ __( 'Use the Left and Right Arrow keys to navigate through the list of columns.' ) }
```

2021-12-13 18:35 UTC, alexstine commented
@aristath Thanks for the review. Conversation is continuing in the issue if this PR will be moving forward or not.

2022-01-12 05:15 UTC, alexstine commented
I may come back to this, but likely not. Looking at making a much bigger change that will hopefully fix this problem for all blocks instead of just Columns. There are others such as Navigation and blocks without contentEditable that really need some fixes.

2022-01-12 05:15 UTC, closed without merging