Add border controls to Site Logo, Cover, and Featured Image blocks
WordPress/gutenberg pull request #37783
Opened 2022-01-07 16:28 UTC by jameskoster

<img width="1242" alt="Screenshot 2022-01-07 at 16 20 52" src="https://user-images.githubusercontent.com/846565/148573664-7d2254b4-6222-486d-aeeb-b7dd015d3940.png">

This PR makes it possible to add border radii, color, width, and style to the following blocks:

* Site Logo
* Cover
* Featured Image

I started with these as other image-related blocks (Image and Comment Author Avatar) already include border controls.

There's an issue to fix with the Site Logo – border width, style, and color properties are being applied to the wrapper rather than the image. I'm not entirely sure what the best fix is here, there would appear to be a few different options cc @aaronrobertshaw for additional insight as I know you've worked on these controls.

Nevertheless, testing instructions are included:

### To test Site Logo

* Insert the Site Logo block
* Add border options like color, width, radius, style
* Check that the correct values are rendered in the Editor and on the frontend

### To test Cover

* Insert a Cover block
* Add border options like color, width, radius, style
* Check that the correct values are rendered in the Editor and on the frontend
* Try adding image and video backgrounds, then check everything still renders correctly

### To test Featured Image

* Edit a post without a featured image set
* Insert the Featured Image block
* Add border options like color, width, radius, style
* Check that the featured image placeholder renders those options on the canvas
* Upload (or select from media library) a featured image
* Ensure the options still render correctly, both on the canvas and on the frontend

2022-02-25 14:33 UTC, ndiego commented
@jameskoster would it be possible to break this PR into three separate PRs, one for each block? The Featured Image and Cover block implementations seem pretty straightforward, leaving just the Site Logo for further discussion.

2022-02-25 15:40 UTC, jameskoster commented
I reverted the Site Logo so we can concentrate on that one separately.

2022-03-16 11:07 UTC, aaronrobertshaw requested changes
Thanks for putting this together @jameskoster 👍 

It might interest you that the Cover block portion of this PR appears to be a duplicate of https://github.com/WordPress/gutenberg/pull/31370. 

The [linked PR](https://github.com/WordPress/gutenberg/pull/31370) was put on the back burner until new color controls were implemented and the border supports refined. It was delayed further when it was decided that the UX around separate controls for border color, width, and style, wasn't great and we should avoid rolling out the support until that was addressed.

There is ongoing work towards refining the border controls into a single component and these PRs should be merged in the near future ( https://github.com/WordPress/gutenberg/pull/37769, https://github.com/WordPress/gutenberg/pull/37770, https://github.com/WordPress/gutenberg/pull/38876 )

My suggestion would be to continue with @ndiego's idea of splitting this PR into one per block, i.e. remove the Cover block changes here.

---

I did also give this PR a test and found the border radius isn't applied cleanly.

This is what I see for the cover block:

<img width="600" alt="Screen Shot 2022-03-16 at 8 54 52 pm" src="https://user-images.githubusercontent.com/60436221/158574483-d832b848-9481-43f4-bc30-8501d8ac0776.png">

The same issue is present for the Featured Image block also.

<img width="600" alt="Screen Shot 2022-03-16 at 9 04 56 pm" src="https://user-images.githubusercontent.com/60436221/158576338-c320ff91-59fb-4587-a362-5e88c9936813.png">

2022-03-16 11:07 UTC, aaronrobertshaw commented on packages/block-library/src/post-featured-image/block.json
> +			}
If all the border controls are in fact to be optional, I think you can omit this part of the configuration.

That said, when the border support panel was first switched to the `ToolsPanel`, the general idea was that any block opting into more than the border radius support should have all its border support features as default controls. 

From memory, this was primarily to address UX issues around the split border color, width, and style controls. The fact this clutters the sidebar was also a driving force in refining the border controls and delaying opting into border support more widely.

Some background and context here can be found in https://github.com/WordPress/gutenberg/pull/34061 and https://github.com/WordPress/gutenberg/pull/36942.

2022-07-28 09:19 UTC, jameskoster commented
Closing in favor of https://github.com/WordPress/gutenberg/pull/42765

2022-07-28 09:19 UTC, closed without merging