Try accessible excerpt
WordPress/gutenberg pull request #3815
Opened 2017-12-05 11:17 UTC by jasmussen

This is an attempt to fix #1371.

CC: @afercia, does this address the fundamental issue?

Screenshot:

<img width="402" alt="screen shot 2017-12-05 at 12 15 10" src="https://user-images.githubusercontent.com/1204802/33604392-1f8c22fe-d9b6-11e7-9863-81fc5f6c3817.png">

Rendered markup:

```
<label for="editor-post-excerpt">Write an excerpt (optional)</label>
<textarea class="editor-post-excerpt__textarea" aria-label="Excerpt" id="editor-post-excerpt"></textarea>
```

2017-12-05 14:54 UTC, aduth requested changes

2017-12-05 14:54 UTC, aduth commented on editor/components/post-excerpt/index.js
>  				aria-label={ __( 'Excerpt' ) }
Is an `aria-label` necessary if an input is labelled by another?

2017-12-05 14:54 UTC, aduth commented on editor/components/post-excerpt/index.js
> +	const excerptTextareaId = 'editor-post-excerpt';
IDs must be unique, which conflicts with React componentization where we don't want to assume how many instances of the component are present on the page. For these cases we should use the `withInstanceId` higher-order component to ensure a unique identifier is available:

https://github.com/WordPress/gutenberg/tree/master/components/higher-order/with-instance-id

2017-12-05 14:54 UTC, aduth commented on editor/components/post-excerpt/index.js
>  )( PostExcerpt );
To the above point on `withInstanceId`, you can either update this line to:

```js
)( withInstanceId( PostExcerpt ) );
```

Or refactor to take advantage of the `compose` feature from `wp.element`:

```js
import { withInstanceId } from '@wordpress/components';
import { compose } from '@wordpress/element';

// ...

const applyConnect = connect(
 	( state ) => {
 		return {
 			excerpt: getEditedPostExcerpt( state ),
 		};
 	},
 	{
 		onUpdateExcerpt( excerpt ) {
 			return editPost( { excerpt } );
  		},
  	}
);

export default compose( [
	applyConnect,
	withInstanceId,
] )( PostExcerpt );
```

2017-12-05 15:31 UTC, afercia commented
@jasmussen thanks. From an accessibility perspective, the new `<label>` element is good, we should remove the `aria-label="Excerpt"` though.

2017-12-06 08:04 UTC, jasmussen commented
Thanks so much for the reviews, both. I've updated to use withInstance to add a unique ID, and I've removed the aria-label.

2017-12-08 11:01 UTC, jorgefilipecosta commented on editor/components/post-excerpt/index.js
> +	const id = 'editor-post-excerpt-' + instanceId;
Minor: normally we try to avoid sum for string concatenation and we use const id = `editor-post-excerpt-${ instanceId }`; instead.

2017-12-08 11:04 UTC, jorgefilipecosta approved these changes
Code changes look good to me, I just left minor non-blocking comments. I did not found any regression during my tests, provided the design changes are ok and the a11y issue is fixed this is good to go.

2017-12-08 11:09 UTC, jorgefilipecosta commented on editor/components/post-excerpt/index.js
> +)( withInstanceId( PostExcerpt ) );
Minor: Normally we use compose in this cases. (the syntax referred by @aduth)

2017-12-11 17:55 UTC, aduth approved these changes

2017-12-12 08:23 UTC, merged