Update the minimum supported version to WordPress 5.8
WordPress/gutenberg pull request #38273
Opened 2022-01-27 09:20 UTC by youknowriad

This PR updates the minimum WP version to 5.8 in the plugin. @gziolo suggested that we should change our policy to support only the last WP version at some point. I'd be happy to make that happen separately once it's all discussed properly.

For now, I'm trying to see what PHP changes we can remove from the plugin: I believe a lot of code from widgets/customizer projects can be removed but it's unclear what has been updated in 5.9 or not.

2022-01-27 10:09 UTC, Mamaduka commented on docs/how-to-guides/themes/create-block-theme.md
>  Requires at least: 5.0
```suggestion
Requires at least: 5.9
```

**suggestion (non-blocking):** Maybe we should also update this to 5.9 as well.

2022-01-27 10:10 UTC, youknowriad commented
I may have been a bit too aggressive 😬 I removed all widgets/customizer code and all code in lib/wordpress-5.8 folders as well. I probably broke some things in the middle but let's test and fix.

2022-01-27 11:21 UTC, Mamaduka reviewed
This looks good. Tested with Classic and Block themes, I've not seen any PHP notices or WSOD.

I think we can also remove these lines:

https://github.com/WordPress/gutenberg/blob/ef22c1636b06ccd4df49e85c4ff56ca18f0ae64a/lib/editor-settings.php#L21-L24

We can also replace `__unstableEnableFullSiteEditingBlocks` with `supportsTemplateMode` on client side.

2022-02-01 01:33 UTC, noisysocks approved these changes
Tested:

- WP 5.9 + Gutenberg
  - ✅ Inserting a post.
  - ✅ Making a change in the site editor with block theme active.
  - ✅ Updating widgets in the widgets editor with classic theme active.
  - ✅ Using the Widget Group block in widgets editor with classic theme active.
  - ✅ Updating widgets in the customizer with classic theme active.
- WP 5.8 + Gutenberg
  - ✅ Inserting a post.
  - ✅ Making a change in the site editor with block theme active.
  - ✅ Updating widgets in the widgets editor with classic theme active.
  - ✅ Using the Widget Group block in widgets editor with classic theme active.
  - ✅ Updating widgets in the customizer with classic theme active.

2022-02-01 01:43 UTC, noisysocks requested changes

2022-02-01 01:43 UTC, noisysocks commented on lib/compat/wordpress-5.8.1/index.php
> -require_once __DIR__ . '/widget-render-api-endpoint/index.php';
Oh, sorry. This ended up landing in WP 5.9 not WP 5.8.1. You'll need to restore the `widget-render-api-endpoint` directory and move it to `wordpress-5.9.`.

2022-02-01 01:51 UTC, noisysocks commented on lib/compat/wordpress-5.8.1/index.php
> -require_once __DIR__ . '/widget-render-api-endpoint/index.php';
Done in ae7f42f.

2022-02-01 04:16 UTC, noisysocks approved these changes

2022-02-01 09:02 UTC, ntsekouras approved these changes
LGTM! Thanks Riad!

2022-02-01 09:02 UTC, merged

2022-02-02 09:28 UTC, youknowriad commented
Thank you folks for the help landing this.

2022-02-09 10:42 UTC, oandregal commented
Hey, the [plugin page](https://wordpress.org/plugins/gutenberg/) still says that it supports 5.7 or higher. Where is that configured?

2022-02-09 10:43 UTC, youknowriad commented
@oandregal I think that's because Gutenberg 12.6 is not yet released.

2022-02-09 10:47 UTC, oandregal commented
Ah, I see, makes sense.