TinyMCE: Use the same version used in Core
WordPress/gutenberg pull request #3840
Opened 2017-12-07 08:09 UTC by youknowriad

This PR updates the TinyMCE script used in Gutenberg to match the TinyMCE used in the classic editor and other metaboxes. The Core version is slightly older (it probably has some bugs already fixed in newer versions) but this change fixes some errors we have right now due to using multiple TinyMCE versions:

 - #3512 No more JS errors when you add some metaboxes
 - #3731 Makes the ACF Wysiwyg field work

I think if we were to update the TinyMCE version, we should find a way to do it globally.

closes #3512 #3731

2017-12-07 23:32 UTC, ephox-mogran requested changes
Just after confirmation that you are intending to still get the plugins from the fiddle azure website. There is an issue #3405 which deals with changing this ... so this seems like a good time to do it. Or is there a reason that you want to keep it?

2017-12-07 23:32 UTC, ephox-mogran commented on lib/client-assets.php
> +	$tinymce_version = '4.6.7';
Yeah, this is going lose a few of the recent fixes. Are you expecting to update before release?

2017-12-07 23:32 UTC, ephox-mogran commented on lib/client-assets.php
> +	wp_register_script( 'tinymce-latest', includes_url( 'js/tinymce/' ) . 'wp-tinymce.php', array( 'jquery' ), false, true );
Is there a reason that you are still getting the plugins from the fiddle below?

2017-12-08 09:29 UTC, youknowriad commented
> so this seems like a good time to do it. Or is there a reason that you want to keep it?

No reason honestly, I was just trying to tackle something else (aligning TinyMCE versions). 

> Yeah, this is going lose a few of the recent fixes. Are you expecting to update before release?

The problem is, I don't know how to update the Core's version without touching Core. If you have some ideas here, that would be great.

2017-12-11 11:52 UTC, iseulde commented
I don’t really feel comfortable reverting to an older version of TinyMCE as there were a lot of fixes that affect Gutenberg in recent versions. Is there a way to remove the original script and re-enqueue it with the latest version? I’m guessing that the script in added without this api in core, and now assumed there by Gutenberg? How do we make sure the dependency is explicit?

2017-12-11 12:10 UTC, youknowriad commented
> Is there a way to remove the original script and re-enqueue it with the latest version?

I don't know :P you have probably more experience with TinyMCE in Core than I have. I'll see if I can find how the script is enqueued in Core and plugins.

> I’m guessing that the script in added without this api in core, and now assumed there by Gutenberg? How do we make sure the dependency is explicit?

I'm not sure I understand, I'm still registering the `tinymce-latest` script in Gutenberg and adding a dependency to it, so it's still an explicit dependency. I changed just the source of the registered script.

2017-12-11 13:25 UTC, iseulde commented
Oh, I looked over `wp_register_script( 'tinymce-latest' ...` :) With this line though, we'll be loading TinyMCE twice?

2018-04-19 19:13 UTC, davisshaver commented
This pull request fixes the location errors with TinyMCE but it does not solve the larger problem quite yet, as in my testing the `wp_editor()` field will parse null in the request to `post.php?post=xxxx&action=edit&classic-editor=1&meta_box=1` with metabox values.

2018-04-19 19:40 UTC, davisshaver commented
so we need to update TinyMCE field before we send the action. We can do this with:

```
if ( window.tinyMCE ) {
    window.tinyMCE.triggerSave();
}
```
I am looking for an appropriate spot to place this

2018-04-20 13:21 UTC, closed without merging