Add transform between cover and media & text
WordPress/gutenberg pull request #38458
Opened 2022-02-02 17:30 UTC by walbo

## Description
Add transform between cover and media & text

## Testing Instructions

1. Insert a Media & Text block and fill with content.
2. Try to transform it to a Cover block.
3. Transform it back to Media & Text

## Screenshots 
![media-cover-tranform](https://user-images.githubusercontent.com/1415747/152205827-3a71f1ca-77bf-4bcc-a82e-f797877c8320.gif)

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

2022-03-28 18:19 UTC, apeatling requested changes
This is a great transform!

One issue I found when testing is the text color. When setting the text color on the media and text block, it is not preserved when doing a transform back to media and text from the cover.

![2022-03-28 11 17 32](https://user-images.githubusercontent.com/1464705/160461448-614c19d9-bf51-436d-a881-22c7c275bb68.gif)

2022-03-29 07:25 UTC, aaronrobertshaw reviewed
These transforms make a lot of sense. Nice work! 👍 

Like @apeatling, I had mixed results when a text color was selected. It appears the main issue is one block opts into color support for text and the other relies on its inner blocks to provide that customization.

Transforming a Media & Text block to a cover block loses the color selection immediately for me. If instead of setting the text color on the Media & Text block, you set it on the inner paragraph, then the color is maintained given the transform doesn't modify the inner blocks.

2022-03-29 07:25 UTC, aaronrobertshaw commented on packages/block-library/src/media-text/transforms.js
> +import { set } from 'lodash';
My understanding is there's a general preference for reducing our use of Lodash, with the view to one day drop it entirely. I think we can avoid the use of `set` here.

2022-04-26 17:42 UTC, walbo commented
> One issue I found when testing is the text color. When setting the text color on the media and text block, it is not preserved when doing a transform back to media and text from the cover.

Yeah, I'm not sure how to solve this since the cover block uses the `isDark` attribute to set a classname that defines the color. Any suggestions?

2022-04-26 17:43 UTC, walbo commented on packages/block-library/src/media-text/transforms.js
> +import { set } from 'lodash';
Yep. Will refactor the code to drop the use of lodash. Didn't know there was an effort to use less lodash 👍

2022-04-28 01:38 UTC, glendaviesnz commented
> > One issue I found when testing is the text color. When setting the text color on the media and text block, it is not preserved when doing a transform back to media and text from the cover.
> 
> Yeah, I'm not sure how to solve this since the cover block uses the `isDark` attribute to set a classname that defines the color. Any suggestions?

I think it would be difficult to fix this without refactoring the Cover block to have a text color option as well as overlay color, and it would make sense to have it opt into the color block supports for this. 

If we were to do this I think that would be a separate PR to this one. It seems like this is a small enough limitation to be able to merge this PR knowing this, and knowing that it will be followed up later once Cover has text color support?

2022-04-28 01:46 UTC, aaronrobertshaw commented
> I think it would be difficult to fix this without refactoring the Cover block to have a text color option as well as overlay color, and it would make sense to have it opt into the color block supports for this.

@glendaviesnz there could be another interim option to this, which I've been exploring this morning. We could have the transform propagate the text color selections onto the inner blocks. If the inner blocks don't opt into color support it has no effect however if the inner block does opt in, the user's color selections are maintained. 

It needs more testing and further thought but it could reduce the impact of the text color issue and allow these transforms to land sooner. 

I'll put together a separate PR extending this one so it can be discussed further in isolation.

2022-04-28 02:27 UTC, aaronrobertshaw commented
As per my last comment, I've created https://github.com/WordPress/gutenberg/pull/40666 to demo the possibility of applying text color selections to inner blocks.

It appears to work Media & Text > Cover > Media & Text. When converting back the inner blocks retain the color selections rather than them being moved back to the Media & Text block, I think this is ok for now. 

Interested to hear what everyone thinks, in particular, about honoring the user made color selections over the `isDark` class etc. I'm inclined to think keeping things looking as the user expects and selected is a good thing.

To move the addition of these transforms forward, I see a few options:

1. Push ahead with this PR as is, accepting the confusing UX when text color selections have been made.
2. Apply alternate approach in [#40666](https://github.com/WordPress/gutenberg/pull/40666) and proceed
3. Hold off on these transforms until we explore the Cover block opting into color block support (even if only for text color)

2022-04-28 20:30 UTC, apeatling commented
I don't think we should hold off because I think this is a beneficial transform even with the loss of text color. I noticed that your PR raised some issues, if we can resolve those then this combined with that change seems like a good approach.

2022-04-29 00:26 UTC, aaronrobertshaw commented
>  I noticed that your PR raised some issues

I'm not sure we can make the UX perfect when transforming Media & Text > Cover > Media & Text. 

I didn't find a means of identifying when we copied the text color onto the inner block versus when the user had set them on the inner block in the initial Media & Text.

That said, it appears we're all leaning towards getting these transforms merged. Mostly likely with https://github.com/WordPress/gutenberg/pull/40666 applied first.

If the Cover block eventually opts into text color block support, the transform can be simplified then.

@walbo are you happy with the above plan? Any thoughts or concerns?

2022-04-29 09:06 UTC, walbo commented
@aaronrobertshaw Sound good to me. Added a comment on #40666

2022-05-03 06:22 UTC, aaronrobertshaw approved these changes
I've merged in the changes from https://github.com/WordPress/gutenberg/pull/40666 and given this another test. 

Looks to be working well for me though it might be good to get another approval from @apeatling or @glendaviesnz given the most recent changes made to this PR were mine.

2022-05-03 13:58 UTC, apeatling approved these changes
LGTM 👍

2022-05-09 07:14 UTC, merged