Allow pasting shortcodes in blocks with content.
WordPress/gutenberg pull request #3883
Opened 2017-12-08 22:03 UTC by jorgefilipecosta

## Description
Until now when pasting a shortcode in existing blocks if the text we paste is plain text the inline pasting mechanism takes place and the shortcode is not parsed and the text is pasted as normal plain text. If the text contains markup the shortcode is parsed.
So if we paste [gallery ids="ID"] in a paragraph with content the text is appended to the paragraph (If copying from here span's are added so this does not happen).
If we paste <div>[gallery ids="ID"]</div> in a paragraph with content the shortcode is parsed and an equivalent block is added.
This change makes sure inline pasting mechanism does not take place if pasting shortcodes.

## How Has This Been Tested?
Add some content to a paragraph or list or heading paste a shortcode verify it is correctly parsed and a block equivalent to the shortcode is added.
Try paste other content besides shortcodes and verify things work as before.

## Screenshots (jpeg or gifs if applicable):

Before: 
![dec-08-2017 21-45-16](https://user-images.githubusercontent.com/11271197/33786992-37930020-dc63-11e7-934b-fc22ba02b629.gif)

After:
![dec-08-2017 21-43-45](https://user-images.githubusercontent.com/11271197/33787005-3f2320b8-dc63-11e7-8134-33ecfe05f655.gif)

2017-12-11 17:27 UTC, mcsf requested changes
I recommend adding tests for this, as there's a lot going on during pasting in general. :)

2017-12-11 17:27 UTC, mcsf commented on blocks/api/raw-handling/index.js
> +	const shortcodesConverted = shortcodeConverter( HTML );
The morphology (esp. the ending in an adjective) irks me a bit. Perhaps renaming and adding a comment:

```js
// An array of HTML strings and block objects. The blocks replace matched shortcodes.
const pieces = …;
```

An alternative could be the quite awkward `htmlAndBlocks`. :)

2017-12-11 17:27 UTC, mcsf commented on blocks/api/raw-handling/index.js
> +	//even if we paste only one shortcode it returns more than one element because empty strings are added
Comment format should be:

```
// If the …
// even if
```

i.e., capitalized sentences and a leading space for each line. Bonus if lines are limited in length (my preference is 78/80 chars, but commonly we see 100 as a hard limit).

2017-12-11 17:27 UTC, mcsf commented on blocks/api/raw-handling/index.js
> +	//even if we paste only one shortcode it returns more than one element because empty strings are added
As for the comment itself, I'd make it terser, e.g. _shortcodeConverter will always return more than one element if shortcodes are matched, as empty HTML strings are included_.

2017-12-11 17:27 UTC, mcsf commented on blocks/api/raw-handling/index.js
> +	const hasShortCodes = shortcodesConverted.length > 1;
Spelling: `hasShortcodes`

2017-12-11 17:27 UTC, mcsf commented on blocks/api/raw-handling/index.js
> +	if ( ! hasShortCodes && ( mode === 'INLINE' || ( mode === 'AUTO' && isInlineContent( HTML ) ) ) ) {
Perhaps refactoring like so:

```js
const isInline = mode === 'INLINE' || ( mode === 'AUTO' && isInlineContent( HTML ) );
const hasShortcodes = …;
if ( ! hasShortcodes && isInline ) {
```

2017-12-11 17:31 UTC, mcsf commented
Referencing related issue #3806.

We can probably go ahead with this fix, but the logic in `raw-handler` is getting less obvious over time. Something to think about.

2017-12-12 18:54 UTC, jorgefilipecosta commented
Hi @mcsf, thank you for your review I tried to address the points you raised. Regarding the tests, it looks like we don't have yet tests for the shortcode parsing mechanism. That mechanism uses window.wp.shortcode, which is not available during test execution. I'm not sure what is the best way to add test cases to it probably we will need to use some mocks.

2017-12-12 19:29 UTC, mcsf commented
Yeah, I think it’s fine to mock it specifically for these tests.

2017-12-12 21:45 UTC, mcsf approved these changes

2017-12-12 21:45 UTC, mcsf commented
I won't block this PR because of the tests, but we should get them in.

2017-12-13 11:07 UTC, merged