Links changed for Develeoper.wordpress.org
WordPress/gutenberg pull request #38841
Opened 2022-02-15 23:29 UTC by bph

On this page: https://developer.wordpress.org/block-editor/how-to-guides/data-basics/
The links in the page body go 404. The .md needed to be removed. 
This results in the links not working when looking on it on the GitHub repo though. 
I feel though, having them not work on the repo is less misleading than the links not working on the final destination of the tutorial 
I am aware that I changed it a few days ago into the other direction. Back then I wasn't aware about this conversion problems from GitHub to developer.wordpress.org

## Description

## Testing Instructions

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

2022-02-16 05:54 UTC, gziolo requested changes
Now, the links are broken when navigating on GitHub. They should be relative to the `/docs/` top-level folder. See: https://github.com/WordPress/gutenberg/tree/trunk/docs/contributors/documentation#using-links.

2022-02-16 20:59 UTC, bph commented
My point was that they are broken on the developer.wordpress.org website now @gziolo :-)

2022-02-18 14:53 UTC, gziolo approved these changes

2022-02-18 14:53 UTC, merged

2022-02-18 14:53 UTC, gziolo commented
I update those links and they work on GitHub as expected. Let's see in the Block Editor Handbook in 15 minutes when it gets synced.