RTL: Flip some dashicons that have directionality
WordPress/gutenberg pull request #3912
Opened 2017-12-11 15:24 UTC by yoavf

## Description
- `editor-outdent`, `editor-indent`, `list-view`, and `editor-ul` can and should be flipped in RTL.
- `editor-ol` (not taken care of yet) needs an RTL version: https://github.com/WordPress/dashicons/issues/250

## How Has This Been Tested?
Manual testing in LTR and RTL mode

## Screenshots (jpeg or gifs if applicable):
**Before:**
<img width="337" alt="before-list" src="https://user-images.githubusercontent.com/844866/33838328-ee90d1c2-de97-11e7-8d82-e9a84d4a3371.png">
<img width="107" alt="before-blocks" src="https://user-images.githubusercontent.com/844866/33838329-eeb987d4-de97-11e7-9437-a90d8f154835.png">

**After**
<img width="666" alt="after-list" src="https://user-images.githubusercontent.com/844866/33838336-f52ade10-de97-11e7-9d82-9448dc707c13.png">
<img width="110" alt="after-blocks" src="https://user-images.githubusercontent.com/844866/33838337-f54c94d8-de97-11e7-9256-8d5d9209a511.png">

## Types of changes
CSS that will affect the RTL version, and will flip the icons.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

2017-12-11 15:29 UTC, mtias commented on components/panel/style.scss
> +body.rtl .gutenberg .dashicon {
this should probably go in a dashicons scss: https://github.com/WordPress/gutenberg/tree/master/components/dashicon

2017-12-11 19:19 UTC, aduth requested changes

2017-12-11 19:19 UTC, aduth commented on components/dashicon/index.js
> +import './style.scss';
This file is generated, so this import would be overwritten next time the Dashicons is updated. It seems like the RTL flipping could be valuable to have in the base Dashicons repository, but in keeping it generic we'd not want to assume the presence of an `.rtl` body class. Would it be reasonable to detect RTL from JavaScript inside the component class and apply an inline style?

https://github.com/WordPress/dashicons/blob/master/sources/react/index-header.jsx
https://github.com/WordPress/dashicons/blob/master/sources/react/index-footer.jsx

2017-12-11 19:19 UTC, aduth commented on components/dashicon/style.scss
> +  &.dashicons-editor-outdent,
Mixed whitespace, tabs and spaces.

2018-01-27 19:00 UTC, gziolo commented
@yoavf do you plan to finish this PR or should someone else take it over?

2018-06-25 11:58 UTC, azaozz commented
May be just me but... https://user-images.githubusercontent.com/844866/33838336-f52ade10-de97-11e7-9d82-9448dc707c13.png looks odd with the numbered list icon in LTR and the bulleted one in RTL. Can we use "proper" RTL icons there? Then we only will need to swap the icons in the CSS, not "mirror" them.

2018-09-13 19:14 UTC, aduth commented
Closing as stale without response.

2018-09-13 19:14 UTC, closed without merging