Add aria label to Nav block on front of site
WordPress/gutenberg pull request #39161
Opened 2022-03-02 13:40 UTC by getdave

## Description

Currently when rendered on the front of the site the Navigation block has no accessible label to identify it. We have a `Menu name` field on the block which is saved to the `post_title` field of the underlying `wp_navigation` post. 

This PR utilises the `Menu name` as the `aria-label` attribute on the main `<nav>` tag on the front of the site (only).

I added an e2e test to provide coverage.

Closes https://github.com/WordPress/gutenberg/issues/24369.

## Limitations

I'm aware of the following:

- Menu names are automatically generated by the block so they may not always be the most descriptive out of the box (although they can be edited in the inspector controls under the `Advanced` section).
- If you reuse the same Navigation Menu (i.e. `wp_navigation) across multiple Navigation block's on the same page then you will have duplicate `aria-label`s. This is probably an edge case. We could add an additional `aria-label` field to the block if necessary but I'm unclear on how we could dedupe names across Nav blocks on a page.

## Testing Instructions

1. New Post.
2. Add Nav block.
3. Add some items.
4. Publish post being sure to save the Navigation Menu in the entity saving flow at the publish step.
5. Switch to front of site.
6. Inspect Nav block `<nav>` tag for presence of `aria-label` attribute.
7. Try renaming the Nav in the editor - under `Advanced` -> `Menu name`.
8. Update the post.
6. Inspect Nav block `<nav>` tag for presence of modified `aria-label` attribute.

## Screenshots 
<img width="900" alt="Screen Shot 2022-03-02 at 13 40 03" src="https://user-images.githubusercontent.com/444434/156372568-24a267a7-54df-48b5-9b33-2ab93e645253.png">

## Types of changes
New feature (non-breaking change which adds functionality) 

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] I've tested my changes with keyboard and screen readers. 
- [ ] My code has proper inline documentation. 
- [ ] I've included developer documentation if appropriate. 
- [ ] I've updated all React Native files affected by any refactorings/renamings in this PR (please manually search all `*.native.js` files for terms that need renaming or removal). 
- [ ] I've updated related schemas if appropriate.

2022-03-02 15:29 UTC, alexstine reviewed
@getdave Thanks for the PR.

I think for me, I would be concerned that the aria-label appearing on the page multiple times could actually do more harm than good. Especially if it sends users mixed messages. E.g. If you named your menu "Main Navigation" and put the block in the header/footer, this is now confusing as usually this wording would only appear at the top of the site.

You are seeing my mistrust of users come out on this. :(

2022-03-02 15:50 UTC, MarcoZehe reviewed
I agree with @alexstine that we wanna be very careful with these. They should be named, yes, but the name should definitely not be duplicated. E. g. if there are several nav blocks, each should have a distinct name.

2022-03-02 21:19 UTC, joedolson reviewed
It seems to me like there's a fair argument that if the *same* navigation menu appears multiple times, it should have the same name. But if not, it shouldn't have a fully unique name, and only be differentiated by order in the DOM, e.g. "Main Navigation (1 of 2)", "Main Navigation (2 of 2)". Having fully unique names would imply that the menus have different content. 

Is it feasible to add menu counts to differentiate if a menu is reused?

2022-03-03 09:44 UTC, getdave commented
Thanks for all the feedback folks. That's super helpful.

So what I'm hearing is that:

1. We should avoid have _identical_ `aria-label`s across a given page. I agree 👍 
2. We can use a numerical identifier to differentiate if the same menu name appears on the page more than once.

Let me know if that is correct.

I'll have to look into how we can do this but it could be possible.

Thanks again all 🙇‍♂️

2022-03-03 12:44 UTC, draganescu commented
We can count on render or store the association between a navigation block and it's navigation CPT in any block template. 

Given that this association does not change often I think counting on render is not a good choice.

Given we already store the navigation data in the DB whenever a navigation block is associated with a CPT we can send that to the API and have all the navigation CPTs have a prop that holds a count of how many navigation blocks are associated.

My proposal is not fancy, I know.

The other way, @getdave @alexstine is to combine the name of the navigation with the name of the parent template part. However this does not block a user to use the same navigation in the same template part multiple times. But for that we could add a warningin the block inspector "You are using this navigation in this template part already". <- I think this option is better than storing in the DB.

2022-03-04 04:21 UTC, alexstine commented
@draganescu I think we should just store it in the DB or run a .length on render. We're talking about super simple information, right?

2022-03-04 06:48 UTC, getdave commented
Following the feedback, I searched the codebase for any prior art on something like this. I found something similar in the Template Part block:

https://github.com/WordPress/gutenberg/blob/ab65bf431643e3cfc237b6634b68a01bae0b81f4/packages/block-library/src/template-part/index.php#L16

Therefore, I've opted to keep things simple and added a commit which implements a very basic method of ensuring a unique ID based on remembering the names of previously rendered menus and appending an ID if the menu has already been rendered.

Eg:

```
My Menu
My Menu 1
My Menu 2
...etc
```

I'd be cautious about adding DB queries here as the block would need to run them on render. That said I'm open to suggestions or alternative PRs if folk believe that would be a better option.

2022-03-08 02:57 UTC, alexstine commented
@getdave Is there any way I could get a test site for this? The navigation block is still pretty inaccessible for me to configure.

2022-03-08 08:09 UTC, draganescu commented
@alexstine isn't it more clear to have the label be Main Navigation Footer compared to Main Navigation 2?

2022-03-08 14:18 UTC, anton-vlasenko requested changes
I've tested this PR using the testing instructions above, and the value of the `aria-label` attribute changed according to the `Menu value` parameter.
Great job.
I only have one small suggestion on how to improve the code.

2022-03-08 14:18 UTC, anton-vlasenko commented on packages/block-library/src/navigation/index.php
> +			$seen_menu_names[ $nav_menu_name ] = $seen_menu_names[ $nav_menu_name ] + 1;
```suggestion
			++$seen_menu_names[ $nav_menu_name ];
```

2022-03-08 17:41 UTC, getdave commented
> isn't it more clear to have the label be Main Navigation Footer compared to Main Navigation 2?

@draganescu I see an argument for looking at this. Indeed, in the future the Nav block may be more aware of its location within a given template. However, I think we'll need to jump through a few more hoops to get to that solution.

This PR does solve the "must be unique" problem. I wonder how we feel about merging and iterating? Is this better than what we have now?

> ...combine the name of the navigation with the name of the parent template part

@draganescu Are you aware of any APIs that might allow us to achieve this? Also noting we'd still need the logic to de-duplicate within a given Template Part.

2022-03-08 17:47 UTC, getdave commented
> @getdave Is there any way I could get a test site for this? The navigation block is still pretty inaccessible for me to configure.

@alexstine I don't have a throw away instance available where I can have this PR running. 

Are you able to 

- switch to `Code View` 
- drop the following into the editor

```
<!-- wp:navigation --><!-- wp:navigation-link {"label":"WP.org","url":"http://www.wordpress.org","kind":"custom","isTopLevelLink":true} /--><!-- wp:navigation-link {"label":"Google","url":"http://www.google.com","kind":"custom","isTopLevelLink":true} /--><!-- wp:navigation-link {"label":"BBC","url":"http://www.bbc.co.uk","kind":"custom","isTopLevelLink":true} /--><!-- /wp:navigation -->
```
- exit code view

As all of the links are to external URLs it should create a configured Nav block for you.

I hope that helps?

2022-03-08 21:59 UTC, alexstine commented
@getdave When I test your built branch with the code you provided, the aria-label is empty.

```
<nav class="wp-container-8 is-responsive wp-block-navigation" aria-label="">
```

Thoughts?

Thanks.

2022-03-09 06:17 UTC, getdave commented
> @getdave When I test your built branch with the code you provided, the aria-label is empty.

Hi @alexstine. I'm really sorry this is proving tricky to test. Let me see what I can do to help. I appreciate your patience.

I suspect what is happening is that the Navigation Menu  _Post_ is not being created from the inner blocks which have been pasted into the Code View.

I think once you exit Code View you will need to **reselect the Nav block** in order for the items to be transformed into a `wp_navigation` post. This might take a few seconds depending on your network connection.

Here's a video of me walking through the process. I hope that is able to help?

https://user-images.githubusercontent.com/444434/157382884-a8b2864e-10aa-4401-9d01-02bf0ec97226.mov

I would suggest these are the new steps:

- new Post
- switch to `Code View` (shortcut: `⇧⌥⌘M`).
- paste the following into the editor:

```
<!-- wp:navigation --><!-- wp:navigation-link {"label":"WP.org","url":"http://www.wordpress.org","kind":"custom","isTopLevelLink":true} /--><!-- wp:navigation-link {"label":"Google","url":"http://www.google.com","kind":"custom","isTopLevelLink":true} /--><!-- wp:navigation-link {"label":"BBC","url":"http://www.bbc.co.uk","kind":"custom","isTopLevelLink":true} /--><!-- /wp:navigation -->
```
- exit code view (shortcut: `⇧⌥⌘M`).
- select the Navigation block
- jump to the `Advanced` section of the block's Inspector controls (right hand siderbar)
- check the `Menu name` field exists and is populated
<img width="1510" alt="Screen Shot 2022-03-09 at 06 12 46" src="https://user-images.githubusercontent.com/444434/157383147-445e8ec3-54d0-43e5-9161-af6f48ba969d.png">
- Publish post - check that the Navigation Menu is saved.
<img width="1510" alt="Screen Shot 2022-03-09 at 06 13 43" src="https://user-images.githubusercontent.com/444434/157383242-cfdcff93-cec9-443c-976d-d0921e526dca.png">
- check from of site for `aria-label`.


This whole problem tells me we need to show a notice when the Navigation menu is created from inner blocks. That way it would be obvious when the operation had succeeded. As things stand there is no visual or auditory feedback that this has happened.

2022-03-10 00:59 UTC, alexstine commented
@getdave This is almost good for me. What I would like to see is every navigation output having a label. E.g.
1. If I add 2 navigation blocks, I can find the first navigation block and then I hear "navigation name 1" on the second menu. What I would like to hear is "navigation name 1", "navigation name 2".
2. If there is only one navigation menu on the page, it should just be the navigation name.

Does this make sense? Probably just needs some conditional tweaking.

In the future, I would like to see authors receive a warning when the same navigation block is added to the content with the same name. I believe we can teach accessibility through a means of guiding. However, this makes our problem better for now which is why I am in favor of this PR. 👍 

Thanks.

2022-03-10 10:29 UTC, getdave commented
> Does this make sense? Probably just needs some conditional tweaking.

I took a look at this and at the moment I can't see a way to achieve it.

When we render a given block X we don't know about any blocks that will be rendered _afterwards_. Therefore when it comes to outputting the block can choose to conditionally add a numeric ID based on other blocks.

Scenario:

1. we come to the block no other Nav blocks have been seen so don't add a number. Result: `My Navigation`.
2. we come to the next block and the previous block has been seen so we add a number. Result `My Navigation 1`.

What we can't do is output `My Navigation` for step 1 and then retrospectively change that to `My Navigation 1` when we detect the 2nd block in step 2.

At the moment I'm a bit stumped. Will ask around for any advice/input.

2022-03-10 11:06 UTC, scruffian approved these changes
This solution looks better than what we have at present. I think we should merge this and follow up with improvements.

2022-03-10 14:21 UTC, joedolson commented
From a user comprehension standpoint, I think it would better if the added count started at 2. Having the first appearance unnumbered is fine, but the 2nd should be numbered based on actual count.

2022-03-10 16:04 UTC, alexstine commented
I must be honest. I am not sure excluding "1" is a good idea especially if the first item would be "2". Can you imagine? A user hears "My Navigation 2" and they are going to start thinking where "My Navigation 1" is. Honestly, I am not sure this is really going to help a lot at the end of the day.

It would be great to have other screen reader users feedback in here.

Maybe it is worth waiting for some type of accessibility check for this block. After all, sometimes the best things are worth waiting for. 👍 

Just my thoughts...

Thanks.

2022-03-10 16:11 UTC, joedolson commented
@alexstine I'm not sure you understood what I was suggesting correctly. Based on @getdave's comment, the first found block doesn't know whether there will be additional, so it can't be numbered. Following on that, the first block would be 'Main', the second would be 'Main 2', because it's the second found block. 

I think this makes a *lot* more sense than the first block being "Main", and the second being "Main 1". To me, that would be very confusing.

2022-03-10 17:40 UTC, alexstine commented
@joedolson 

> I think this makes a lot more sense than the first block being "Main", and the second being "Main 1". To me, that would be very confusing.

Yes, I completely agree.

I still struggle with though if excluding the "1" will cause any confusion. You don't think this could play an issue at all?

2022-03-10 18:34 UTC, joedolson commented
@alexstine I don't know about "no issue". I do think that a count of one is commonly represented by existence, without an actual number present. 

I think that the scenario where only one menu is present including a count would be worse. The presence of "Menu 1" strongly implies that there are more instances of this menu. 

It would be ideal to have the count present on all instances of a menu if there was more than one, but in my opinion, omitting the 1 is not a deal breaker, and is less of a problem than including a count unnecessarily.

2022-03-10 19:42 UTC, anton-vlasenko approved these changes
LGTM!

2022-03-10 23:17 UTC, scruffian approved these changes

2022-03-11 07:11 UTC, alexstine commented
Sounds fair.

@getdave Can you change the code so the second menu on the page gets number "2" to start? First menu will have no number, second will have "2", third will have "3", and so on.

After giving this some thought, I think it is an improvement and we should get it in.

2022-03-11 09:31 UTC, scruffian commented
> Can you change the code so the second menu on the page gets number "2" to start? First menu will have no number, second will have "2", third will have "3", and so on.

I pushed a commit to do this.

2022-03-11 14:17 UTC, alexstine approved these changes
Looks good.

2022-03-14 06:47 UTC, getdave commented
Thanks all. e2e test failure seems unrelated. Will re-run and look to merge.

2022-03-14 09:37 UTC, getdave commented
Looks like [e2e tests have caught an unrelated bug](https://wordpress.slack.com/archives/C02QB2JS7/p1647250113445049).

I'm going to force merge this one.

2022-03-14 09:38 UTC, merged

2022-10-21 18:17 UTC, michaelbourne commented
@getdave is this supposed to work in the Widget context as well?