Fix center aligned images styles
WordPress/gutenberg pull request #39422
Opened 2022-03-14 10:07 UTC by youknowriad

closes #39291 

## What?

Centered image blocks inside containers (group blocks) in a block theme were not centered properly. This PR fixes that.

## How?

The "flow" (default) layout didn't have explicit styles for centered blocks that said, the default rule targeting all children implicitly targeted the centered blocks and added margin autos. That default rule is mainly there for wide/full aligned blocks. That said, that default rule is conditionally rendered, it's only added if the layout of the current container defines "widths", meaning it supports wide and full widths and has a centered content area. 

So the PR defines an explicit rule adding the margins for centered aligned blocks.

## Testing Instructions

1- Insert a group block
2- Insert an image block inside that group block
3- Resize the image so it's small
4- Center the image block
5- It should appear centered on both frontend and editor.

Ideally we should test on different themes (classic and block themes)

2022-03-14 10:08 UTC, youknowriad commented on lib/block-supports/layout.php
> +		$style .= "$selector > .alignright { float: right; margin-inline-start: 2em; margin-inline-end: 0; }";
I updated the the two selectors above and added the `>` there to match the editor. For me that's the right thing to do, it was just something that has been missed originally. We don't intended to define styles for any grand children here, only direct children. (Technically it's not related to this PR but I thought I'd just fix it here)

2022-03-14 10:28 UTC, jasmussen commented
This is testing well for me. Here's a fresh block theme:
<img width="1392" alt="Screenshot 2022-03-14 at 11 26 12" src="https://user-images.githubusercontent.com/1204802/158154195-5b144ffa-77b4-4e45-80e8-8a8428133e55.png">
<img width="1392" alt="Screenshot 2022-03-14 at 11 26 16" src="https://user-images.githubusercontent.com/1204802/158154206-aab2e1a1-ae12-45f2-a935-58a2580e770e.png">

Here's an older block theme that hasn't been updated in a while:
<img width="1392" alt="Screenshot 2022-03-14 at 11 26 31" src="https://user-images.githubusercontent.com/1204802/158154240-340c2096-7124-41c4-a620-3655f51f9b34.png">
<img width="1392" alt="Screenshot 2022-03-14 at 11 26 35" src="https://user-images.githubusercontent.com/1204802/158154246-a4b2d316-a318-449f-be3e-03a65e639f72.png">

Here's TwentyFourteen and TwentyTwenty classic themes:
<img width="1392" alt="Screenshot 2022-03-14 at 11 26 48" src="https://user-images.githubusercontent.com/1204802/158154295-c8520103-5fca-46f0-9dfc-3a63efa81d16.png">
<img width="1392" alt="Screenshot 2022-03-14 at 11 26 52" src="https://user-images.githubusercontent.com/1204802/158154304-4a022f7d-4b1c-449d-830e-312af7b14715.png">

<img width="1392" alt="Screenshot 2022-03-14 at 11 27 14" src="https://user-images.githubusercontent.com/1204802/158154309-6eef6ffb-707f-44c8-995a-0043d1d2f4f0.png">
<img width="1392" alt="Screenshot 2022-03-14 at 11 27 20" src="https://user-images.githubusercontent.com/1204802/158154322-26334d56-63ad-4d1f-8255-0f27da33a462.png">

2022-03-15 08:48 UTC, ocean90 requested changes
For me the image is still not centered when used in a column.

<img width="898" alt="Bildschirmfoto 2022-03-15 um 09 44 23" src="https://user-images.githubusercontent.com/617637/158339646-5a321284-d1dd-4a8f-a86e-df1c08c260ec.png">

Also left/right only works in the editor but on the frontend in the column.

That's maybe the reason why the `>` doesn't exist for left/right alignment classes?

2022-03-15 09:30 UTC, youknowriad commented
@ocean90 I think both of these issues are the same. The column block doesn't output "layout" styles. I think the ideal solution would be for the column block to opt-in into the layout but there might be some side effects to that change.

2022-03-15 09:33 UTC, youknowriad commented
The last commit solves that. It adds "layout" support to the column block. It also means this panel is visible on the sidebar of the column block

<img width="267" alt="Screen Shot 2022-03-15 at 10 32 44 AM" src="https://user-images.githubusercontent.com/272444/158348582-9dd9d5d8-9080-402c-8160-cd966ad99ed0.png">

I think that's fine but wanted to confirm with @jasmussen here

2022-03-15 09:42 UTC, jasmussen commented
I think it's fine as Columns is a container block like group.

I do think there's an opportunity to further refine and clarify the layout panel, and also to generally give a lot of love and attention to the Columns block. But those are separate issues.

2022-03-15 09:55 UTC, ocean90 commented
With the layout setting it's now working for me too. It may can get a bit confusing when seeing three inputs for setting a width though.

<img width="285" alt="" src="https://user-images.githubusercontent.com/617637/158352126-608df603-cb9e-47d3-a5c1-78eca456efcd.png">

Saying that, the editor seems not to respect the width set for the image. Is this a known issue?

| Editor | Frontend |
| --- | --- |
| <img width="927" alt="" src="https://user-images.githubusercontent.com/617637/158352452-e419725d-14b2-4470-bbb1-5b9ed57c5ccc.png"> | <img width="367" alt="" src="https://user-images.githubusercontent.com/617637/158352478-030ae5fe-e635-49ac-9538-5cc26af2ad01.png"> |

2022-03-15 10:00 UTC, youknowriad commented
> Saying that, the editor seems not to respect the width set for the image. Is this a known issue?

I'm not sure I understand the issue here, would you be able to send me some content with that? Those widths define the max-width for child blocks but I know that image blocks can grow beyond their container in Gutenberg (on purpose)

2022-03-15 10:10 UTC, ocean90 commented
> Those widths define the max-width for child blocks but I know that image blocks can grow beyond their container in Gutenberg (on purpose)

I guess you mean when they are resized by the user? Looks like I had mine resized at some point which was causing this. Inserting an image without resizing respects the max-width.

<details>
<summary>Example content</summary>


```html
<!-- wp:image {"align":"center","id":14,"width":512,"height":342,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image aligncenter size-full is-resized"><img src="https://user-images.githubusercontent.com/617637/158354719-55822d17-9449-46f8-a84f-20df1d5b8de3.jpeg" alt="" class="wp-image-14" width="512" height="342"/><figcaption>r3e3ed3</figcaption></figure>
<!-- /wp:image -->

<!-- wp:group {"backgroundColor":"pale-cyan-blue"} -->
<div class="wp-block-group has-pale-cyan-blue-background-color has-background"><!-- wp:image {"align":"center","id":14,"width":512,"height":342,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image aligncenter size-full is-resized"><img src="https://user-images.githubusercontent.com/617637/158354719-55822d17-9449-46f8-a84f-20df1d5b8de3.jpeg" alt="" class="wp-image-14" width="512" height="342"/><figcaption>r3e3ed3</figcaption></figure>
<!-- /wp:image --></div>
<!-- /wp:group -->

<!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. </p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"200px","backgroundColor":"pale-cyan-blue","layout":{"inherit":false,"contentSize":"100px"}} -->
<div class="wp-block-column has-pale-cyan-blue-background-color has-background" style="flex-basis:200px"><!-- wp:image {"align":"center","id":14,"width":205,"height":137,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image aligncenter size-full is-resized"><img src="https://user-images.githubusercontent.com/617637/158354719-55822d17-9449-46f8-a84f-20df1d5b8de3.jpeg" alt="" class="wp-image-14" width="205" height="137"/></figure>
<!-- /wp:image -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button -->
<div class="wp-block-button"><a class="wp-block-button__link">ffffff</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:image {"align":"center","id":14,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image aligncenter size-full"><img src="https://user-images.githubusercontent.com/617637/158354719-55822d17-9449-46f8-a84f-20df1d5b8de3.jpeg" alt="" class="wp-image-14"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

</details>

2022-03-15 10:10 UTC, ocean90 approved these changes

2022-03-15 12:13 UTC, merged