Eslint: Exempt TS files from `jsdoc/require-param`
WordPress/gutenberg pull request #39458
Opened 2022-03-15 12:41 UTC by mirka

## What?

Exempts TypeScript files from the [`jsdoc/require-param`](https://github.com/gajus/eslint-plugin-jsdoc/blob/master/.README/rules/require-param.md) rule.

## Why?

TypeScript files generally have their type information in code rather than in JSDoc comments. The `jsdoc/require-param` rule requires all params to be documented in the JSDoc, which would be redundant in these cases.

For example, `jsdoc/require-param` would consider this an error, because `props` is not documented in the comment:

```ts
/**
 * This is Foo
 */
export function Foo( props: Props ) { ... }
```

## Testing Instructions

- Simple doc comments like the above should not trigger eslint errors in TS files.
- The behavior remains the same for `.js` files.

2022-03-15 13:26 UTC, ciampo commented
Just playing devil's advocate here — Even if the type of a parameter is defined in TypeScript, the `param` rule may still be useful for adding a description to a prop or return value.

Would removing the `jsdoc/require-param` rule make our docs worse?

2022-03-15 14:04 UTC, mirka commented
> Would removing the `jsdoc/require-param` rule make our docs worse?

Not really, in the sense that our jsdoc lint rules are progressively applied. This rule only requires that every parameter is merely _listed_, and even that is only when someone _chooses_ to add a JSDoc for the function in the first place. Something like `@param foo` is enough to satisfy it — no type or description required.

It _may_ act as a prompt for the person to add a param description, but in TS files I think it's a bad place to prompt it because we should encourage people to put param descriptions inline rather than in the JSDocs for the function.

```ts
// Better ✨
type Props = {
  /** My foo */
  foo: boolean;
}
```
I'm fine with scoping the override to the wp-components package only, since other packages might have different needs.

2022-03-15 16:33 UTC, ciampo approved these changes
> Something like `@param foo` is enough to satisfy it — no type or description required.
> ...
> It may act as a prompt for the person to add a param description, but in TS files I think it's a bad place to prompt it because we should encourage people to put param descriptions inline rather than in the JSDocs for the function.

Good observations! I'd personally be ok with the changes from this PR, although I wonder if it's better to wait for @gziolo 's thoughts too.

> I'm fine with scoping the override to the wp-components package only

I don't have a strong option here, it's probably fine to apply them to all TS files.

2022-03-15 16:49 UTC, gziolo commented
> Just playing devil's advocate here — Even if the type of a parameter is defined in TypeScript, the param rule may still be useful for adding a description to a prop or return value.

Yes, that's one thing. The other aspect is the tooling we currently use that extracts params from JSDoc to include them in the auto-generated documentation. @dmsnell and @adamziel, how do you handle the cases where you keep full JSDoc comments for functions but you omit types as they are already encoded in TypeScript? How does it work with the tool that generates API documentation?

2022-03-15 17:51 UTC, dmsnell commented
> we should encourage people to put param descriptions inline rather than in the JSDocs for the function.

Just curious since I'm still rather new to the mix of JSDoc and TypeScript, but why should we encourage inline descriptions? In my limited experience I feel like both constructions have presented approximately the same outcome and experience, and personally I don't mind having the listing of params in the docblock, especially if the descriptions read more like sentences with multiple lines.

```ts
/**
 * @param name   Name of the given steel to process; this
 *               could be one of several common names or
 *               the AISI-SAE specification code.
 * @param cycles How many annealing rounds through which
 *               to run the steel. If omitted will use the
 *               recommendation for the given steel type.
 */
```

vs.

```ts
const process = (
	/**
         * Name of the given steel to process; this
         * could be one of several common names or
         * the AISI-SAE specification code.
         */
	name: string,

	/**
	 * How many annealing rounds through which
	 * to run the steel. If omitted will use the
	 * recommendation for the given steel type.
	 */
	cycles?: number
) => {
	…
}
```

Not a big deal, but even in that example I found the inline comments a bit more tedious for formatting and changing the formatting when the comment changes.

> how do you handle the cases where you keep full JSDoc comments for functions but you omit types as they are already encoded in TypeScript? How does it work with the tool that generates API documentation?

@sarayourfriend and I removed the requirement that JSDoc params list a type. For one, it was redundant with typed parameters; for two, after a quick survey and some consideration, we found that the types in the docs are generally not that helpful. Most are `Object` or `Function` and there's no click-through to jump-to-definition for more complicated types that TypeScript will produce.

It's my strong opinion that JSDocs should intentionally not include typing information when TypeScript provides the types because JSDoc is manual and unconstrained while TypeScript is automated and verified.

That being said I find a lot of value in having explanatory descriptions available for function arguments/parameters and so I find some kind of documentation there crucial, especially in a place like Gutenberg where we often have confusingly-named or outright inaccurately/misleadingly-named arguments.

I'm in favor of keeping the requirement that params have documentation. Our tooling won't discover the inline comments but we've discussed deficiencies in our tooling and a desire to eventually move towards more TypeScript-native tooling which parses the code and extracts all this _and_ provides links to type definitions and the like. My opinion boils down to a more general thought about listing: do people want to require documentation for function arguments? If so then leave this rule in unless we can verify the inline comments. If not then take it out; tinting is really _really_ slow and can be quite annoying when it's wrong (because it assumes it's never wrong, even when presented cases such as the motivation for this very PR).

2022-03-15 20:32 UTC, sarayourfriend requested changes
[TSDoc](https://tsdoc.org/), the TypeScript specific flavor of JSDoc, still requires params to be documented almost exactly the same way as JSDoc, just without the type. You're correct the type information is redundant but it doesn't mean we can change the way we document parameters entirely, especially not if we want to preserve existing developer experience for easy access to docstrings on function and constant declarations. Inline documentation isn't parsed the same way by babel or other AST builders and therefore isn't used by editors the same way for completion suggestions and inline documentation.

[Here is a TypeScript playground that illustrates the difference for editors](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDMAbFBTAInCBnACgChFEB6MxAAwAcBGK5PRYOAJ2TABMYIBDWGADmiAO4ALDEiiS2GRHzmJUqPgFs+zFIihxRYEonoAuRACM4cVBj4GAlIgDehuVBBsk9IgF8iRMgBUASQBiAACNIrqRnSIALTU9IwwzKwcKDz8giISUjqy8oryKuqanDp6BogBZESgkLAIOnhcuDj4BCbmlta2Ds6kru6edD5+-pQAKgCeNPJUKOhg2LiEjGYYqHoK3Pl5kSB4hbtgcFDyMvKtECBqUlAC8NLiAgo0c4paz4UguogQcDUNGs5wAdBNEDg9og8Op5KIYDJqFAWm1VgRGLYuIhTudoddbvdHk0aHBSQA3DBscFAA)

Here are screenshots of each function in the playground being used to illustrate the difference in experience between the two:

**Inline documentation as proposed by this PR**

![inlinedocs](https://user-images.githubusercontent.com/24264157/158465770-c8c6d437-d981-4a0b-9005-043830c5983b.png)

**Standard TSDoc/JSDoc approach**

![tsdocdocs](https://user-images.githubusercontent.com/24264157/158465852-17429a4f-1f64-440e-a906-af4ffb2047c6.png)

If anything, I would suggest enabling the jsdoc linting rule that requires parameter descriptions for typescript files: https://github.com/gajus/eslint-plugin-jsdoc#user-content-eslint-plugin-jsdoc-rules-require-param-description

Additionally, enabling the TSDoc linter could also be a good idea as there are specific TSDoc conventions that can be followed (and could allow for automatic documentation extraction tools like [APIExtractor](https://api-extractor.com/pages/tsdoc/doc_comment_syntax/) in the future).

2022-03-15 20:35 UTC, sarayourfriend commented
The example given in the PR description is indeed annoying and I don't have a good solution for it other than suggesting that adding `@param props - Component props` is minimally invasive and doesn't incur a long-term maintenance cost. In fact, I think the JSDoc linting plugin even considers that rule auto-fixable and will automatically add the param tag with the param name (no description obviously) for you if you enable auto-fixing rules.

2022-03-15 22:09 UTC, dmsnell commented
> [Here is a TypeScript playground that illustrates the difference for editors](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDMAbFBTAInCBnACgChFEB6MxAAwAcBGK5PRYOAJ2TABMYIBDWGADmiAO4ALDEiiS2GRHzmJUqPgFs+zFIihxRYEonoAuRACM4cVBj4GAlIgDehuVBBsk9IgF8iRMgBUASQBiAACNIrqRnSIALTU9IwwzKwcKDz8giISUjqy8oryKuqanDp6BogBZESgkLAIOnhcuDj4BCbmlta2Ds6kru6edD5+-pQAKgCeNPJUKOhg2LiEjGYYqHoK3Pl5kSB4hbtgcFDyMvKtECBqUlAC8NLiAgo0c4paz4UguogQcDUNGs5wAdBNEDg9og8Op5KIYDJqFAWm1VgRGLYuIhTudoddbvdHk0aHBSQA3DBscFAA)

Confirmed with the same behavior in PhpStorm

2022-03-16 07:47 UTC, mirka commented
> Just curious since I'm still rather new to the mix of JSDoc and TypeScript, but why should we encourage inline descriptions?

Good question, I should've noted the reasoning.

One advantage which I think is universally true, is that in an inline JSDoc we can use additional JSDoc tags like `@default` and `@example` _within_ the param documentation. For example, in wp-components we heavily use `@default` to document the default value for our props:

```ts
type Props = {
  /**
   * My foo prop.
   * 
   * @default true
   */
  foo: boolean;
}
```

Another reason, which may or may not be relevant outside of wp-components, is how it interacts with the actual docgen. From our [investigation for wp-components](https://github.com/WordPress/gutenberg/pull/38842), we found that the only viable docgen for our requirements ([`react-docgen-typescript`](https://github.com/styleguidist/react-docgen-typescript)) **does not extract param descriptions unless they are inline**. (I *guess* that makes sense, because otherwise you'd have the problem of which description to prioritize if there were descriptions both in the function-level `@param` and inline.) This behavior may be different for other docgens, and may be less of a concern if you only need to deal with a docgen that you control the implementation of (`@wordpress/docgen`).

In any case, in trying out different docgens I realized that there's a substantial difference in the docgen requirements for React components vs. normal functions, so it might be the case that there is no config that's optimal for both contexts.

2022-03-16 07:48 UTC, mirka commented
> [Here is a TypeScript playground that illustrates the difference for editors](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABDMAbFBTAInCBnACgChFEB6MxAAwAcBGK5PRYOAJ2TABMYIBDWGADmiAO4ALDEiiS2GRHzmJUqPgFs+zFIihxRYEonoAuRACM4cVBj4GAlIgDehuVBBsk9IgF8iRMgBUASQBiAACNIrqRnSIALTU9IwwzKwcKDz8giISUjqy8oryKuqanDp6BogBZESgkLAIOnhcuDj4BCbmlta2Ds6kru6edD5+-pQAKgCeNPJUKOhg2LiEjGYYqHoK3Pl5kSB4hbtgcFDyMvKtECBqUlAC8NLiAgo0c4paz4UguogQcDUNGs5wAdBNEDg9og8Op5KIYDJqFAWm1VgRGLYuIhTudoddbvdHk0aHBSQA3DBscFAA)

The inline comment needs to be a doccomment (`/** … */`), not `// …`:

```ts
function inlineDocs(
  /** `p1` is for indicating when there are llamas in town */
  p1: boolean
) {
  return p1
}
```

2022-03-16 09:15 UTC, mirka commented
Ok, I tested with `@wordpress/docgen` (e.g. with [this file](https://github.com/WordPress/gutenberg/blob/trunk/packages/data/src/redux-store/metadata/utils.ts)), and can confirm that this docgen does not currently extract inline param docs. Furthermore, it doesn't pick up the param *at all* unless it's `@param` tagged in the function-level JSDoc. So we definitely want to keep this lint rule in place for anything that relies on this docgen! 😆 

I limited the scope of the override to wp-components only (https://github.com/WordPress/gutenberg/pull/39458/commits/4deb8857783698a690a73bdaebd4885bccd86e2a). I still think it makes sense in the wp-components context where we're mostly dealing with React components and have a clear reason to prefer inline param docs. I don't love the idea of having to add meaningless noise to satisfy a lint rule that doesn't offer a concrete benefit in the components case. (It also involves moving the props destructuring to happen inside the function body, to avoid having to add a long list of `@param` declarations for every prop.)

What do you all think? Still worth keeping in wp-components?

2022-03-16 11:40 UTC, sarayourfriend commented
@mirka oh sorry, I misunderstood the way inline docs work. They actually are better in some ways than the JSDoc style! You get the parameter documentation per-argument as you're passing it rather than only on the full function. Interesting.

I don't know if the problem with `@wordpress/docgen` could be overcome. It should be possible (even easier) to document parameters from inline comments: https://astexplorer.net/#/gist/bcfb17e9b46ce3a99838b26b56acf899/dbca20f13ef6a1e5d7a44125784348944883cbe5

You wouldn't need to use `comment-parser` at all for it... I guess unless tags like `@defaultValue` were being used for parameters or something. But it should be simpler as you're not having to do the most complex part which was associating a given parameter tag with the parameter (mostly complicated due to object/array destructuring).

2022-03-16 11:40 UTC, sarayourfriend approved these changes

2022-03-16 18:32 UTC, dmsnell commented
> (It also involves moving the props destructuring to happen inside the function body, to avoid having to add a long list of @param declarations for every prop.)

Can you share more about this? It sounds like you are trying to avoid this…

```ts
/** Does something
 * @param {Object}  props
 * @param {string}  props.name  name of thing
 * @param {number}  props.count times to do thing
 * @param {boolean} props.flamp whether or not to flamp it too
 */
const Component = ( props ) => { … }
```

Which, if that's the case, it might be a decent opportunity to create a separate type for the props anyway rather than couple them so tightly to the function's type.

```ts
/** @typedef Props
 * @property {string}  name   name of thing
 * @property {number}  count  times to do thing
 * @property {boolean} flamp  whether or not to flamp it too
 */

/** Some component
 * @param {Props} props component props
 */
const Component = props => { … }

const OtherComponent = ( /** @type Props */ props ) => { … }
```

> in an inline JSDoc we can use additional JSDoc tags like @default and @example within the param documentation

I'm not aware of how to add examples for per-property values of an object such as with component props, but JSDoc _does_ have a default value syntax we can use if we want.

```ts
/** @param {number} [minimum=56] threshold at which process starts */
```

This also works with all cases where we define types, such as in `@property`

---

There's another option that I think may work for you too without giving up what you want and without changing linter rules. It's possible to go ahead and create TypeScript types for a component written in JS and import those types into JSDoc. This has the advantage that we get the flexibility of TypeScript and when we eventually convert over, we won't have to rewrite the JSDoc types as TS types.

```ts
// some JS-only package, without a tsconfig
// types.ts
export interface Props {
	/**
	 * Minimum threshold at which process begins
	 *
	 * @example use a negative number to invert the universe
	 * @default 56
	 */
	minimum?: number;
}
```

```ts
// some JS-only package, in same directory as above
// index.js

/** @typedef {import("./types").Props} MeterProps */


/**
 * Meter with minimum-threshold alarm.
 *
 * @param {MeterProps} props
 */
export default ( props ) => { … }
```

I tested this out and here's what VSCode and PhpStorm are showing me.
![Screen Shot 2022-03-16 at 11 29 23 AM](https://user-images.githubusercontent.com/5431237/158661991-a5541091-c4f0-4e40-9f87-dd6bbe780aff.png)
![Screen Shot 2022-03-16 at 11 30 01 AM](https://user-images.githubusercontent.com/5431237/158662011-3df867d9-5c99-4c9d-b54f-47494f3fb80d.png)
![Screen Shot 2022-03-16 at 11 30 18 AM](https://user-images.githubusercontent.com/5431237/158662025-603aa308-ec37-4ac9-8514-f1b73acd3b80.png)

2022-03-16 18:51 UTC, sarayourfriend commented
@dmsnell That's already how things are done in the components package (at least for newer components or older ones that have had type-checking added since the pattern was established by @ciampo and myself last year), specifically using a `Props` type that is annotated per-property.

I think the idea is that annotating the `@param props - Component props` feels redundant and the jsdoc linter doesn't allow you to add an annotation on the function without also annotating the params. At least that's my reading of what @mirka is describing the problem to be.

2022-03-17 13:52 UTC, mirka commented
@dmsnell 

> `/** @param {number} [minimum=56] threshold at which process starts */`

Ah this is nice, thanks! I don't think I knew that syntax.

Unfortunately [react-docgen-typescript](https://github.com/styleguidist/react-docgen-typescript) disregards JSDoc `@` tags at the function-level, so we don't have much leeway in that regard. I was surprised at how different docgen behavior/limitations could be. Some docgens don't support imported types, for example.

>> (It also involves moving the props destructuring to happen inside the function body, to avoid having to add a long list of `@param` declarations for every prop.)
>
> Can you share more about this?

Nothing big, this was just about how the linter demands a different number of params depending on where the props are destructured:

```ts
/**
 * @param props - Linter needs all the sub-params listed
 * @param props.one
 * @param props.two
 * @param props.three
 */
const Component = ( { one, two, three }: Props ) => { … }
```

versus

```ts
/**
 * @param props - Linter only needs the props obj param
 */
const Component = ( props: Props ) => {
  const { one, two, three } = props;
}
```

2022-03-17 15:45 UTC, merged

2022-03-17 18:48 UTC, dmsnell commented
> Nothing big, this was just about how the linter demands a different number of params depending on where the props are destructured:

Right, which means I think we were talking about the same thing.

Strangely this only impacts ~TS files~ inline attribute types. If we were to take you second example and add the type signature to `props` the linter doesn't complain.

```ts

```

2022-03-17 20:53 UTC, mirka commented
> I guess we use `react-docgen-typescript` for our component playground?

Correct. We're basically trying to leverage TS data to build out interactive documentation for our component library.

> It would seem better if we could somehow limit this exemption to React component props

I'm not _too_ concerned about this at the moment for wp-components, because any non-trivial utility functions tend to be extracted out to `.ts` files. We can reasonably assume that functions inside `.tsx` files are React components.

But I do share your concern, and @ciampo and I will be on high alert for any ill effects that we see from this change. The good thing is that it's largely autofixable if we choose to revert.

Personally I feel that human code reviewers tend to be better safeguards for insufficient/bad docs, and enforcing 100% coverage can sometimes even deter people from adding partial yet sufficient docs, or instead add meaningless noise (`@param fontSize - The font size`). I don't think I'm the only one that sometimes opts for a `// …` comment instead of `/** … */` to document a function because the linter forces me to document all params, and I the human know that that is overkill. That's a clear lose for Intellisense users.

The bulk of the benefit that `require-param` provides (i.e. nudge someone that forgot to document a type for a new param they added) is already covered in TS files, so I actually think we have very little upside for some rather tangible downsides, React or otherwise.

2022-03-17 22:54 UTC, dmsnell commented
> any non-trivial utility functions tend to be extracted out to .ts files. We can reasonably assume that functions inside .tsx files are React components.

A cursory glance turned up 32 functions in `.tsx` files inside of the components directory and I think about half of those don't have any existing JSDoc comments, meaning they are exempted (because our linter is happy to leave you entirely unaware; it mostly cares that if you help a little you must help 100%)

> I don't think I'm the only one that sometimes opts for a // … comment instead of /** … */ to document a function because the linter forces me to document all params

this is really concerning 😆 and I think it's reason enough to take this opportunity to review the tooling entirely. we made the decision recently to stop requiring the types on those parameters project-wide so that people could more naturally slide into TypeScript.

also it seems like the problem is again the tools are defective. I'm puzzled also that we added a second docgen library when we already consume one (not that the one in use by our custom docs-gen is better, it isn't). this just makes knowing the rules hard for everyone, particularly because those tools enforce contradictory styles.

React components aren't the only files butting up against this small inconvenience either. I see it every day in all sorts of files I work in. Are React components really that different?

2022-03-18 11:57 UTC, mirka commented
> I'm puzzled also that we added a second docgen library when we already consume one

The chain of dependency that inevitably leads to `react-docgen-typescript` is quite simple:

1. We want interactive and largely auto-generated component documentation/playgrounds. Unless we roll our own, Storybook is the best choice for this.
2. Storybook currently [supports](https://github.com/storybookjs/storybook/blob/next/addons/docs/react/README.md#typescript-props-with-react-docgen) two TypeScript-ready docgens, one of which is a non-starter due to lack of support for imported types.

Given that we don't have the appetite to build our own Storybook-equivalent from scratch, it makes sense to configure ourselves in a way that plays nice with `react-docgen-typescript`, as long as it doesn't lock us into any non-standard practices or degrade code quality.

Other wp packages have different documentation needs, so there might not be a one-size-fits-all. In an ideal scenario we'd have lint rules that look at JSDoc and inline types as a whole. Defective tooling, indeed.

> React components aren't the only files butting up against this small inconvenience either.

Here's a concrete example of the kind of mess that can happen if we try to "work around" `require-param`, especially in the `react-docgen-typescript` case.

```ts
/**
 * `BaseControl` is a component used to generate labels and help text for components handling user inputs.
 *
 * @param {WrongProps} props
 */
export const BaseControl: FunctionComponent< BaseControlProps > & {
	VisualLabel: typeof VisualLabel;
} = ( { one, two, three } ) => {}
```

- The param type in JSDoc and the inline type is conflicting, but there are no errors thrown. (JSDoc param type is silently ignored)
- I can't just remove the inline type because the docgen needs it.
- The IDE continues to prompt me that "JSDoc types may be moved to TypeScript types."

I guess in React you hit this problem a lot more frequently because of the prevalence of object destructuring.

2022-03-18 20:04 UTC, dmsnell commented
For the record, I agree with your frustrations here and am not trying to argue that.

> try to "work around"

This is where I think we're not on the same page. I'm not trying to say you should add all these things; I'm saying I think we can do better on this in a way that benefits everyone, or disables a faulty tool.

Looking at [the documentation for `eslint-plugin-jsdoc`](https://github.com/gajus/eslint-plugin-jsdoc#require-param) it looks like our use-case is already supported, and through parameters designed to specifically target these kinds of instances instead of implicitly disabling the whole linter for a specific part of the project.

 - `checkTypesPattern` lets us define something like `Props` as an acceptable type for the linter to ignore destructured parameters. This probably isn't the bets way to approach the problem but we could say, for all types starting with a capital letter, don't require `@param` tags for all the properties.
 - `checkDestructured` I believe is the rule in question here. it defaults `true` but we could potentially disable it globally. again, destructuring props is a common pattern. A quick search turned up almost three hundred functions starting with a lower-case name (probably not React) that follow this same pattern.
 - `contexts` lets us limit a rule or rule change to a certain code construct, such as `TSFunction` though it's not available on `check-param-names` or `require-param-name`

I played around with some variations of these and it looks promising. The worst part about the config options is that the ones we want don't exist for `check-param-names`. Someone opened an issue with `eslint` for [this very issue](https://github.com/gajus/eslint-plugin-jsdoc/issues/616).

Maybe we could discuss relaxing the requirement that destructured properties all get a `@param` tag globally?