Editor: Refactor PostFeaturedImage component
WordPress/gutenberg pull request #40126
Opened 2022-04-07 05:32 UTC by Mamaduka

## What?
Follow up to #39973. Rafactors `PostFeaturedImage` component.

Changes in this PR:
* Replaces `withSelect` and `withDispatch` HoC with hooks.
* Moved media details selecting logic into a separate function.
* Improves loading state.

## Why?
Previously it was not clear that the Featured Image started uploading.

## How?
The component now sets the state when the media URL is a blob.

## Testing Instructions
1. Open a Post or Page.
2. Throttle network using DevTools.
3. Drop an image onto the Featured Image component in the Summary panel.
4. Confirm that spinner is displayed immediately.

## Screenshots or screencast 

https://user-images.githubusercontent.com/240569/162127125-751a88a4-861c-4671-87c6-b364ecddae7a.mp4

2022-04-07 07:16 UTC, jasmussen commented
Thanks for this. Given we've reverted the status panel for now, should we maybe seek to cherry-pick the reverted commits into a new PR and integrate this? It will be useful for when #39082 gets picked back up!

2022-04-07 07:19 UTC, Mamaduka commented
@jasmussen, since this is a general improvement, I'm thinking of rebasing, and we can ship this in 6.0. The uploading state issue affects the current trunk as well.

2022-04-07 07:22 UTC, jasmussen commented
Sounds great 👍 👍 — let me know how I best can help.

2022-04-07 07:59 UTC, Mamaduka commented
Rebased and fixed a few minor issues. I think this is ready for review.

2022-04-07 08:43 UTC, jasmussen commented
Even without throttling, I see the same in trunk as in this branch, any idea what I'm doing wrong?
![trunk](https://user-images.githubusercontent.com/1204802/162158491-ea979832-2047-43db-8b4d-595af7207f26.gif)
![this branch](https://user-images.githubusercontent.com/1204802/162158505-aca40d37-6aa0-4d41-b6c1-d875f0ce01a2.gif)

That said, it seems like the time between you drop and the spinner appears, the height of the dropzone collapses to zero making the spinner hover awkwardly above a thin line. I wonder if we should add a min-height to the dropzone.

Also, some of the improvements we did make to the summary panel effort could really benefit this panel still 😅  — but not for this PR.

2022-04-07 09:04 UTC, Mamaduka commented
The issue with the uploading state is more visible on slow connections. You can also try uploading large images and comparing the results with the trunk.

Collapse happens when dropzone is replaced with an image tag, but the image isn't rendered yet.

2022-04-07 09:57 UTC, jasmussen commented
Yep, this is a vast improvement:
![large file](https://user-images.githubusercontent.com/1204802/162173793-ab3b1da1-bdc7-45a8-920b-104313a4fe20.gif)

2022-04-07 10:01 UTC, Mamaduka commented
I think as a follow-up, we can also display images in progress. Like we do for the Image and other media blocks.

2022-04-10 09:47 UTC, Mamaduka commented
I just realized that this would be a breaking change for plugins that use the `editor.PostFeaturedImage` filter and rely on HoC props.

I did a quick search in the WP.org directory, and the change should affect many plugins - https://wpdirectory.net/search/01G09DKAY7BA2V543ZKBHT3NEK.

We can also mention the update in Misc DevNotes.

2022-04-12 11:37 UTC, draganescu requested changes, later dismissed
What are we adding here that is worth the breaking change? Are we making a breaking change just for [refactoring code](https://make.wordpress.org/core/handbook/contribute/code-refactoring/)?

If I am not missing something, the one added functionally is the improvement of the upload state.

a) Can we do it without the breaking change?
b) If we're keen in deprecating HoC props can we do it at least in a few steps?

2022-04-14 17:01 UTC, Mamaduka commented
To be honest, I got carried away with refactoring and only then realized that it was breaking change 😅

> Are we making a breaking change just for [refactoring code](https://make.wordpress.org/core/handbook/contribute/code-refactoring/)?

I thought it was okay to refactor the code to modernize it. WP core does it as well.

> a) Can we do it without the breaking change?

I'm not sure if this would be possible without changing HoC props, so it still would be a breaking change.

P.S. Most plugins I check in the repo don't use these props.

2022-04-15 04:47 UTC, Mamaduka commented on packages/editor/src/components/post-featured-image/index.js
> +	}, [] );
I'm grabbing `mediaUpload` inside the component instead of `withSelect` to avoid introducing another public API prop.

2022-04-15 04:50 UTC, Mamaduka commented
@draganescu, I've updated the code to make it backward compatible. The only "breaking" change is that `onDropImage` is no longer available as a prop. But plugins extending components probably should never use this method.

2022-04-15 09:58 UTC, ntsekouras commented
>@draganescu, I've updated the code to make it backward compatible. The only "breaking" change is that onDropImage is no longer available as a prop. But plugins extending components probably should never use this method.

Unfortunately, after looking at this more it seems we shouldn't introduce any breaking change here and the reason is the existence of the filter `editor.PostFeaturedImage`. We face the similar problem with `BlockListBlock`..

I tried to find a work around for this and the only viable solution I come up with is if we keep the old `onDropImage` as is but internally we use the new one with a different name. It feels hacky but not really sure how else we could do it.. 

Any thoughts? --cc @youknowriad

2022-04-15 11:02 UTC, Mamaduka commented
Thanks, @ntsekouras.

I'm not too fond of a hacky solution as well, but happy to make the required changes, if we all agree on the direction.

P.S. We made similar changes to the `editor.PostTaxonomyType` filter in 5.9 - https://make.wordpress.org/core/2022/01/04/miscellaneous-block-editor-changes-in-wordpress-5-9/#posttaxonomytype-filter

2022-04-15 11:53 UTC, youknowriad commented
I think we need to assess how many plugins are using this hook. If we manage to contact them and ask them for the change, it's easier.

> I tried to find a work around for this and the only viable solution I come up with is if we keep the old onDropImage as is but internally we use the new one with a different name. It feels hacky but not really sure how else we could do it..

I think that could be a good start and if we can wrap the existing props with "proxies" we can trigger a `deprecated` call when the `get` is called.

2022-04-15 11:59 UTC, Mamaduka commented
> I think we need to assess how many plugins are using this hook. If we manage to contact them and ask them for the change, it's easier.

Based on WPdirectory only 16 - https://wpdirectory.net/search/01G09DKAY7BA2V543ZKBHT3NEK. I can check how many of these use the props. But there are always more for client projects and private plugins.

> I think that could be a good start and if we can wrap the existing props with "proxies" we can trigger a deprecated call when the get is called.

I was also looking into how we can leverage proxies for deprecations 😄 I Don't have anything yet, but I think this is a good idea for the future.

I will update the code to use Nik's suggested method. It would be great to have a plan for this kind of situation in the future.

2022-04-18 09:41 UTC, Mamaduka commented
@ntsekouras, I restored all filter props, so it's not a breaking change anymore.

2022-04-28 07:17 UTC, Mamaduka commented
@draganescu, @ntsekouras, I think this is still worth landing even without complete refactoring :)

2022-04-29 10:34 UTC, ntsekouras approved these changes
Really nice improvement George, thanks!

2022-04-29 10:38 UTC, merged

2022-09-19 13:05 UTC, Mamaduka commented
@bph, this is an internal [non-breaking change](https://github.com/WordPress/gutenberg/pull/40126#issuecomment-1101266019) and doesn't require a Dev Note.

2022-09-22 20:42 UTC, bph commented
Thanks @Mamaduka  I'll remove it from the list