Post Comments: Hide block in the inserter
WordPress/gutenberg pull request #40167
Opened 2022-04-07 17:08 UTC by DAreRodz

## What?

Removes the Post Comments block from the inserter, now that we have Comments Query Loop to replace it.

## Why?

That block is being replaced with Comments Query Loop.

## How?

Simply adding `"inserter": false` in block.json.

## Testing Instructions

1. Open a Post or Page, or go to any template.
2. Check that the Post Comments block doesn't appear anymore.

2022-04-08 06:54 UTC, carolinan requested changes
Hi
I believe the title and description should also be updated, like we did for the post comment block?
https://github.com/WordPress/gutenberg/pull/36032

2022-04-08 08:43 UTC, DAreRodz commented
Yup, that would be much better. Thanks for noticing, @carolinan. 😊

2022-04-08 14:04 UTC, carolinan approved these changes

2022-04-08 14:29 UTC, ajitbohra approved these changes

2022-04-08 19:28 UTC, merged

2022-04-11 12:34 UTC, gziolo commented
This PR was cherry-picked for Gutenberg plugin release v13.0 and WordPress 6.0 Beta 1.