Comments Query Loop: Add Post Comments Form block to Comments Query Loop template
WordPress/gutenberg pull request #40256
Opened 2022-04-12 07:52 UTC by SantosGuillamot

## What?
Add the Post Comments Form block to the Comments Query Loop template to ensure it appears directly after inserting the comments in the editor.

Fixes https://github.com/WordPress/gutenberg/issues/40225

## Why?
It's reasonable to assume that, when users add the Comments Loop, they will want to use the Post Comments Form as well. They could always delete it if it isn't needed.

## How?
Just adding the Post Comments Form block to the template.

## Testing Instructions
In trunk:

1. Go to a Post, Page, or Site Editor and add the Comments Query Loop.
1. Check that only the Comment Template and the Comments Pagination blocks are added automatically. You would have to add the Post Comments Form manually.

In the PR branch:

1. Go to a Post, Page, or Site Editor and add the Comments Query Loop.
1. Check that, apart from the Comment Template and the Comments Pagination, the Post Comments Form is added automatically.

2022-04-12 08:10 UTC, c4rl0sbr4v0 approved these changes
LGTM!

2022-04-12 08:26 UTC, paaljoachim commented
WP 5.9.3.
Using this [method to test the PR](https://make.wordpress.org/design/2021/03/03/testing-a-gutenberg-pull-request-pr/) Gutenberg build. 
Twenty Twenty Two.
Chrome


I removed the Post Comments block and added in the Comments Query Loop block. This is what I see:
### Backend
![Screenshot 2022-04-12 at 10 20 47](https://user-images.githubusercontent.com/5323259/162915062-e851b95b-a1c0-4892-a7e8-ffd77033a912.jpg)

### Frontend
![Screenshot 2022-04-12 at 10 24 12](https://user-images.githubusercontent.com/5323259/162915766-7ea9dc15-bb04-4bc8-8abf-681be69b5e1c.jpg)


Looks good!


Btw.
Post comments block should be removed making the Comments Query Loop the default.

2022-04-12 08:26 UTC, paaljoachim approved these changes
Great! It does the job.
Thank you!

2022-04-12 12:30 UTC, paaljoachim commented
The question comes up should this be backported to WP 6.0?
It would in general make it easier for the user if it was included.

2022-04-12 13:00 UTC, gziolo commented
Noting that Post Comment block is still marked as experimental in the Gutenberg plugin:

https://github.com/WordPress/gutenberg/blob/415e404cbf767f6c7b793d216f43444783ab7325/packages/block-library/src/index.js#L265-L276

2022-04-12 13:00 UTC, adamziel commented
@paaljoachim post-comments-form is an experimental block, it would have to be stabilized for this change to be backported.

2022-04-12 13:04 UTC, paaljoachim commented
Alrighty! Thanks for the feedback Greg @gziolo and Adam @adamziel !

2022-04-12 13:41 UTC, c4rl0sbr4v0 commented
I found some differences between the behavior of this block vs the form that is being rendered on the Post Comments block function.

Also, there is a "bug" in Core that, if we have the Core `comment-reply.js` file enqueued. It is having a display issue.

I will create an issue.

2022-04-13 18:14 UTC, michalczaplinski commented
Could you link the issue here @c4rl0sbr4v0 ? 🙂

2022-04-13 19:46 UTC, ockham commented
> Could you link the issue here @c4rl0sbr4v0 ? 🙂

I think Carlos didn't end up filing one after we decided that we'll include most relevant information in #40268. (I _think_ that most of these issues will now be fixed by the latest state of #40268, plus maybe some additional styling of the Post Comments Form block.)

2022-04-13 19:48 UTC, ockham commented
@adamziel and @gziolo If we're going to ship the Comment Query Loop block (and friends, i.e. Comment Template, Comment Author Name, Comment Content, etc) in WP 6.0, we really need the Post Comments Form block. Can we still stabilize it and get it into WP 6.0?

2022-04-13 21:09 UTC, michalczaplinski commented
Thank you @ockham ! :) 

Yup, I saw this now - I was just looking for more context when I first saw this PR!

2022-04-13 21:09 UTC, michalczaplinski commented
Thank you @ockham ! :) 

Yup, I saw this now - I was just looking for more context when I first saw this PR!

2022-04-14 07:10 UTC, gziolo commented
> @adamziel and @gziolo If we're going to ship the Comment Query Loop block (and friends, i.e. Comment Template, Comment Author Name, Comment Content, etc) in WP 6.0, we really need the Post Comments Form block. Can we still stabilize it and get it into WP 6.0?

@priethor, @annezazu - what do you think? I have never tried using the Post Comment Form block so I can’t tell without testing. Is there any demo presenting the block?

2022-04-14 17:26 UTC, ockham commented
@gziolo One thing I'm aware of is that the block is currently displaying the following in the editor:

![image](https://user-images.githubusercontent.com/96308/163441644-cd98bf3c-aad0-405e-b4ca-6155eba8e68d.png)

I.e. we'll need to implement a placeholder that visually represents better what it looks like on the frontend.

2022-04-14 17:27 UTC, ockham requested changes
Note that this PR is blocked since the Post Comments Form [is still marked as experimental](https://github.com/WordPress/gutenberg/pull/40256#issuecomment-1096698340).

See the comments on the PR for further discussion.

2022-04-14 18:33 UTC, ockham commented
> @gziolo One thing I'm aware of is that the block is currently displaying the following in the editor:
> 
> ![image](https://user-images.githubusercontent.com/96308/163441644-cd98bf3c-aad0-405e-b4ca-6155eba8e68d.png)
> 
> I.e. we'll need to implement a placeholder that visually represents better what it looks like on the frontend.

FWIW, there's an old [issue](https://github.com/WordPress/gutenberg/issues/26999) with some mockups for the Post Comments Form.

I forgot to say: We're _not_ going to try to implement a full-fledged, editable, Comments Form Template block (as described in #24221) for now; that would be way beyond scope for WP 6.0.

2022-04-15 08:38 UTC, carolinan commented
Without the comments form block or the post comments block, there is no way to add a comment when a block theme is installed.

Personally, I would prefer if the basic, no template comments form was made stable because I am concerned that the alternative is to revert the addition of the new comment query blocks and revert the deprecation of the post comments block.
Why? Because you would have to use the post comments block for the form, and if you combined the post comments block with the query, the comments would be displayed twice.


(The `post comment` block which was mentioned is deprecated and displayed a single comment, using a comment id)

2022-04-19 11:01 UTC, ockham commented
Thanks @carolinan! I agree with your reasoning 😄  We've [started work](https://github.com/WordPress/gutenberg/pull/40368) required for stabilizing the Post Comments Form block.

2022-04-19 20:04 UTC, ockham commented
I've filed a small PR (https://github.com/WordPress/gutenberg/pull/40452) that marks the Post Comments Form block as stable. We should merge it after https://github.com/WordPress/gutenberg/pull/40368 has been merged, which will then unblock this PR.

2022-04-22 10:33 UTC, ockham commented
https://github.com/WordPress/gutenberg/pull/40368 and https://github.com/WordPress/gutenberg/pull/40452 have been merged, thus unblocking this PR 😄

2022-04-22 10:33 UTC, ockham approved these changes

2022-04-22 10:33 UTC, merged

2022-04-25 14:48 UTC, gziolo commented
Cherry-picked to `wp/6.0` branch for WordPress 6.0 Beta 3 release.