Update docs "Opt-in into UI controls" for context
WordPress/gutenberg pull request #40333
Opened 2022-04-14 03:06 UTC by ALJ

## What?

This PR adds context to the documentation for `appearanceTools`.

## Why?

Based on the discussion here: https://github.com/WordPress/gutenberg/discussions/39586 and this Make post: https://make.wordpress.org/core/2021/12/08/whats-new-in-gutenberg-12-1-8-december/, important context for `appearanceTools` was missing from the docs leading to confusion about the reasons for `appearanceTools` existence.

2022-04-18 16:19 UTC, skorasaurus commented
thanks for catching this and providing a nice, succinct context to `appearanceTools`

2023-03-31 16:59 UTC, skorasaurus requested changes
Sorry one had formally reviewed this; these changes would be appreciated but the document has been updated in other areas since then. 

If you're still interested, you'll need to pull the changes from upstream (the gutenberg repo) first - https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/ and then make your changes.

2025-08-04 08:04 UTC, Mamaduka commented
Thanks for contributing, @ALJ

Do you have time to refresh this patch, or should we close the PR as stale?

2025-08-21 04:56 UTC, Mamaduka commented
Closing as "stale".

2025-08-21 04:56 UTC, closed without merging