Migrate code block test case to playwright
WordPress/gutenberg pull request #40844
Opened 2022-05-05 11:01 UTC by pavanpatil1

## What?

Migrate[ code-test.js](https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/specs/editor/blocks/code.test.js) to its Playwright version.
## Why?

See #38570 for its background.
## How?

See[ MIGRATION.md](https://github.com/WordPress/gutenberg/blob/trunk/test/e2e/MIGRATION.md) for migration steps.
## Testing Instructions

Run` npm run test-e2e:playwright test/e2e/specs/editor/blocks/code.spec.js`

2022-05-06 07:02 UTC, talldan commented
Thanks for working on this @pavanpatil1!

Just a few things to fix in this PR, but on the whole looks good. I'll invite @kevin940726 for any further feedback.

Gutenberg uses the `prettier` code formatter, and it looks like the 'Static Analysis' check is failing because the newly added code isn't formatted. You can run `npm run format` to format files. For an individual file I think the command would be something like `npm run format -- test/e2e/specs/editor/blocks/code.spec.js`.

If you're using an editor like VSCode you can also install a `prettier` plugin and configure it format code automatically.

It also looks like there's a snapshot file used by the old test that needs to be deleted - `specs/editor/blocks/__snapshots__/code.test.js.snap`.

2022-05-06 07:31 UTC, kevin940726 reviewed
Apart from the minor issues Dan already mentioned, it mostly looks pretty good! I just have a small feedback to suggest inlining the `clickBlockAppender` util if possible.

2022-05-06 07:31 UTC, kevin940726 commented on test/e2e/specs/editor/blocks/code.spec.js
> +		await pageUtils.clickBlockAppender();
We usually want to limit the usage of e2e utils if we can inline them directly. If we're just creating a page, I believe we can just click on the appender button directly:

```suggestion
		await page.click( 'role=button[name="Add default block"i]' );
```

The same code has also been used in `copy-cut-paste` tests. This way we don't have to create the `clickBlockAppender` util (unless we really need it in other situations).

2022-05-24 11:41 UTC, pavanpatil1 commented
Hi @kevin940726, I addressed all the shared feedback. However, the CI is failing on Static Analysis (Linting, License, Type checks...) / All (pull_request)`. I followed the steps mentioned here https://github.com/WordPress/gutenberg/pull/40844#issuecomment-1119317835. Formatted the code still it is failing.

2022-06-07 08:07 UTC, kevin940726 requested changes

2022-06-07 08:07 UTC, kevin940726 commented on test/e2e/specs/editor/blocks/code.spec.js
> +	test( 'should paste plain text', async ( { editor, page, pageUtils } ) => {
You can click on the "Details" link in the checks to see where it went wrong. Here's the relevant error message in the link:

```
[1] /home/runner/work/gutenberg/gutenberg/test/e2e/specs/editor/blocks/code.spec.js
[1]   45:53  error  'page' is defined but never used  no-unused-vars
```

`page` is not used here in this test, so we can omit it here.

2022-06-07 08:07 UTC, kevin940726 commented on test/e2e/specs/editor/blocks/code.spec.js
> +	test( 'should paste plain text', async ( { editor, page, pageUtils } ) => {
```suggestion
	test( 'should paste plain text', async ( { editor, pageUtils } ) => {
```

2022-06-07 08:14 UTC, kevin940726 commented
Thank you for working on this and sorry for the late reply 🙇 .

Unfortunately, it seems like this test had already been migrated in https://github.com/WordPress/gutenberg/pull/41136 by @JustinyAhin. Normally, we would want to close the latest one but we forgot about that 😞 . We'll try to pay attention to this kind of problem more in the future. Sorry about it! 🙇 

We're still very grateful for your work, and hope that you can start another PR soon next time ;)

2022-06-07 08:14 UTC, closed without merging

2022-06-07 08:24 UTC, JustinyAhin commented
@pavanpatil1 I'm happy to do a pair coding session with you to work on a migrating couple of tests migration if that interests you :).