CheckboxControl: Covert component to TypeScript
WordPress/gutenberg pull request #40915
Opened 2022-05-08 17:37 UTC by walbo

## What?
Converts the `CheckboxControl` component to TypeScript.

## Why?
Part of the @wordpress/components's TypeScript migration (#35744).

## How?
Refactors the current `CheckboxControl` to TypeScript.

## Testing Instructions
- Run npm run dev and ensure no typing errors
- Fire up the Storybook and confirm the `CheckboxControl` continues to function as expected
- Test the various checkbox controls within the block/site editors in Gutenberg still work

2022-05-10 08:06 UTC, ciampo commented
I won't likely be able to review this PR myself, but I've tagged a few other folks who have experience with previous refactors and should be able to help 💯

2022-05-11 07:00 UTC, noisysocks commented on packages/components/src/checkbox-control/README.md
> +#### indeterminate
For bonus credit you could reformat all of these in the style that newer components have. Basically the type moves to the heading.

```markdown
#### `indeterminate`: `boolean`

If indeterminate is true the state of the checkbox will be indeterminate.

- Required: No
```

2022-05-11 07:00 UTC, noisysocks commented on packages/components/src/checkbox-control/index.tsx
> + *
Extraneous whitespace here.

```suggestion
```

2022-05-11 07:00 UTC, noisysocks commented on packages/components/src/checkbox-control/index.tsx
> + * @example
For some reason you need to remove `@example` in order for the code example to appear in the story's Docs tab.

2022-05-11 07:00 UTC, noisysocks commented on packages/components/src/checkbox-control/types.ts
> +	'className' | 'help'
I believe this `className` is unnecessary. `WordPressComponentProps< ..., 'input', ... >` should already have a `className` property as it intersects `HTMLInputElement`.

2022-05-11 07:17 UTC, noisysocks commented
Nice one! 🌈 

Storybook looks good when I test locally, aside from the example not appearing (https://github.com/WordPress/gutenberg/pull/40915#discussion_r869929288), and I don't see any obvious regressions in the block editor.

Would be nice to add a few simple `testing-library` tests to this component but I suppose that's out of scope.

2022-05-11 16:02 UTC, walbo commented on packages/components/src/checkbox-control/types.ts
> +	'className' | 'help'
Yes, but the `className` is applied to the `BaseControl` component and not the input. Is it still unnecessary?

2022-05-11 16:02 UTC, walbo commented on packages/components/src/checkbox-control/README.md
> +#### indeterminate
Will update 👍

2022-05-11 16:16 UTC, walbo commented
> Would be nice to add a few simple `testing-library` tests to this component but I suppose that's out of scope.

Can do a follow-up PR adding some tests 👍

2022-05-12 01:22 UTC, noisysocks approved these changes

2022-05-12 01:31 UTC, noisysocks commented on packages/components/src/checkbox-control/types.ts
> +	'className' | 'help'
Yes, it is unnecessary. The `props` argument in `CheckboxControl` has type `WordPressComponentProps< CheckboxControlProps, 'input', false >`. `WordPressComponentProps< CheckboxControlProps, 'input', false >` will contain a `className` key regardless of whether `type CheckboxControlProps = Pick< BaseControlProps, 'className' | 'help' >` or `type CheckboxControlProps = Pick< BaseControlProps, 'help' >`.

2022-05-12 02:06 UTC, aaronrobertshaw requested changes
Thanks for tackling this one @walbo 👍 

This one is looking pretty good. I have a few minor tweaks and questions I think it would be good to address before merging.

✅ Readme prop descriptions match types
✅ Storybook examples are all functioning well

❓ I don't think we really need additional simple examples, e.g. `WithLabel`, if we just have default arg values. The conversion guidelines suggest the default story should be an interactive playground for the component. Wouldn't that suffice?

> vii. Use the template for the Default story, which will serve as an interactive doc playground.

❓ A `ref` prop is appearing in the controls and looks to come from `WordPressComponentProps`. 

Not sure if this one makes sense here and we need something like `WordPressComponentPropsWithoutRef`. 

The ref prop is removed from the story and everything appears to function for me if I omit `ref` from the `CheckboxControl` props type. Perhaps @mirka could point to the proper approach here?

❓ The deprecated `heading` prop has a controls table entry. We should probably remove/disable this to discourage its use further.

2022-05-12 02:06 UTC, aaronrobertshaw commented on packages/components/src/checkbox-control/index.tsx
> +	props: WordPressComponentProps< CheckboxControlProps, 'input', false >
```suggestion
	// ref is omitted until we have `WordPressComponentPropsWithoutRef` or add
	// ref forwarding to CheckboxControl.
	props: Omit<
		WordPressComponentProps< CheckboxControlProps, 'input', false >,
		'ref'
	>
```

This might be better done within `types.ts`?

2022-05-12 02:06 UTC, aaronrobertshaw commented on packages/components/src/checkbox-control/index.tsx
>  	// Run the following callback everytime the `ref` (and the additional
```suggestion
	// Run the following callback every time the `ref` (and the additional
```

Small pre-existing typo.

2022-05-12 02:06 UTC, aaronrobertshaw commented on packages/components/src/checkbox-control/stories/index.tsx
> +			expanded: true,
```suggestion
			expanded: true,
			exclude: [ 'heading' ],
```

This should remove `heading` from the controls and docs tables further discouraging its use.

2022-05-12 02:06 UTC, aaronrobertshaw commented on packages/components/src/checkbox-control/types.ts
> +	'className' | 'help'
I'd second that this `className` is redundant.

2022-05-12 15:31 UTC, walbo commented on packages/components/src/checkbox-control/index.tsx
> +	props: WordPressComponentProps< CheckboxControlProps, 'input', false >
I belive the convention have been to use `WordPressComponentProps` in the compontent and not in `types.ts` so adding it here seems right.

2022-05-12 15:35 UTC, walbo commented on packages/components/src/checkbox-control/types.ts
> +	'className' | 'help'
👍 Removed

2022-05-12 16:00 UTC, walbo commented
> ❓ I don't think we really need additional simple examples, e.g. `WithLabel`, if we just have default arg values. The conversion guidelines suggest the default story should be an interactive playground for the component. Wouldn't that suffice?

Yes, I agree. Updated the default story to have the same default args as in the example.

2022-05-13 00:12 UTC, aaronrobertshaw commented on packages/components/src/checkbox-control/index.tsx
> +	props: WordPressComponentProps< CheckboxControlProps, 'input', false >
I don't feel strongly either way though there is a [precedent in the `InputControl`](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/src/input-control/types.ts#L146-L163) for it being in `types.ts`.

2022-05-13 00:17 UTC, aaronrobertshaw approved these changes
Thanks for the speedy turnaround on this @walbo 🚀 

✅ Storybook examples are all functioning well
✅ Simplified examples look good
✅ Readme prop descriptions match types
✅ Deprecated prop no longer advertised in controls or docs
✅ All other review suggestions resolved

Nice work! LGTM 🚢

2022-05-13 08:04 UTC, walbo commented
Thanks for the review and feedback @noisysocks and @aaronrobertshaw. Much appreciated 😃

2022-05-13 08:04 UTC, merged

2022-05-18 13:12 UTC, ciampo commented
Thank you all for collaborating on this one!

> Can do a follow-up PR adding some tests 👍

@walbo , feel to ping when the follow-up PR is ready 🙏