Update: Refactor panel color gradient settings to use a tools panel. Unify color UI.
WordPress/gutenberg pull request #41091
Opened 2022-05-16 17:43 UTC by jorgefilipecosta

This PR updates PanelColorGradientSettings to use the tools panel and makes the color support hook use PanelColorGradientSettings again.
PanelColorGradientSettings keeps almost the same API, only gets a new option isShownByDefault setting that allows one to hide a color option by default.
This refactor makes all the blocks using custom color colors core (cover, navigation, etc...) and the third-party blocks have the same color UI as the blocks relying on the color support hook unifying all the color picking interface.
With this change, we are also able to remove a considerable amount of code.

## How?
I verified I could pick an overlay color for the cover, a color for a paragraph,  and colors for navigation, remove the colors, and reset the color.

2022-05-17 04:16 UTC, aaronrobertshaw requested changes
Very nice work @jorgefilipecosta and a special thanks for the example use of `batch`! I wasn't aware of its availability. 🙇 

In general, this is testing pretty well except for a couple of minor issues.

There is a more significant problem though with switching the color block supports panel to use the updated `PanelColorGradientSettings`. Doing so means the color block support controls are no longer rendered via the grouped `InspectorControls` slot which enables us to inject other color-related controls into that single panel. 

We can revert the color block support to render its controls via the `InspectorControls` slot with only a subset of the code removed in this PR so we still benefit from your work here.

I've included a diff below that includes most of the suggestions from my review, reinstates the slot fill rendering for the color block support, fixes a linter issue etc.

<details>
<summary><strong>Example diff with review suggestions</strong></summary>

```diff
diff --git a/packages/block-editor/src/components/colors-gradients/dropdown.js b/packages/block-editor/src/components/colors-gradients/dropdown.js
index 5c76ccb6f9..b13e22b353 100644
--- a/packages/block-editor/src/components/colors-gradients/dropdown.js
+++ b/packages/block-editor/src/components/colors-gradients/dropdown.js
@@ -7,11 +7,11 @@ import classnames from 'classnames';
  * WordPress dependencies
  */
 import {
+	Button,
 	ColorIndicator,
 	Dropdown,
 	FlexItem,
 	__experimentalHStack as HStack,
-	__experimentalItem as Item,
 	__experimentalToolsPanelItem as ToolsPanelItem,
 } from '@wordpress/components';
 
@@ -45,6 +45,9 @@ const WithToolsPanelItem = ( { setting, children, panelId, ...props } ) => {
 			{ ...props }
 			className="block-editor-tools-panel-color-gradient-settings__item"
 			panelId={ panelId }
+			// Pass resetAllFilter if supplied due to rendering via SlotFill
+			// into parent ToolsPanel.
+			resetAllFilter={ setting.resetAllFilter }
 		>
 			{ children }
 		</ToolsPanelItem>
@@ -70,16 +73,16 @@ const renderToggle = ( settings ) => ( { onToggle, isOpen } ) => {
 	const toggleProps = {
 		onClick: onToggle,
 		className: classnames(
-			'block-editor-tools-panel-color-gradient-settings__dropdown',
+			'block-editor-panel-color-gradient-settings__dropdown',
 			{ 'is-open': isOpen }
 		),
 		'aria-expanded': isOpen,
 	};
 
 	return (
-		<Item { ...toggleProps }>
+		<Button { ...toggleProps }>
 			<LabeledColorIndicator colorValue={ colorValue } label={ label } />
-		</Item>
+		</Button>
 	);
 };
 
diff --git a/packages/block-editor/src/components/colors-gradients/panel-color-gradient-settings.js b/packages/block-editor/src/components/colors-gradients/panel-color-gradient-settings.js
index 1cc4b65ef7..797a6c9463 100644
--- a/packages/block-editor/src/components/colors-gradients/panel-color-gradient-settings.js
+++ b/packages/block-editor/src/components/colors-gradients/panel-color-gradient-settings.js
@@ -43,7 +43,7 @@ export const PanelColorGradientSettingsInner = ( {
 	__experimentalIsRenderedInSidebar,
 	enableAlpha,
 } ) => {
-	const panelId = useInstanceId( PanelColorGradientSettingsInner )
+	const panelId = useInstanceId( PanelColorGradientSettingsInner );
 	const { batch } = useRegistry();
 	if (
 		isEmpty( colors ) &&
@@ -90,8 +90,6 @@ export const PanelColorGradientSettingsInner = ( {
 				} );
 			} }
 			panelId={ panelId }
-			hasInnerWrapper={ true }
-			shouldRenderPlaceholderItems={ true } // Required to maintain fills ordering.
 			__experimentalFirstVisibleItemClass="first"
 			__experimentalLastVisibleItemClass="last"
 		>
diff --git a/packages/block-editor/src/components/colors-gradients/style.scss b/packages/block-editor/src/components/colors-gradients/style.scss
index abac92db1b..20c146ee71 100644
--- a/packages/block-editor/src/components/colors-gradients/style.scss
+++ b/packages/block-editor/src/components/colors-gradients/style.scss
@@ -112,3 +112,7 @@
 		}
 	}
 }
+
+.block-editor-panel-color-gradient-settings__dropdown {
+	width: 100%;
+}
diff --git a/packages/block-editor/src/hooks/color-panel.js b/packages/block-editor/src/hooks/color-panel.js
index 34a8645ea7..d0775abbc4 100644
--- a/packages/block-editor/src/hooks/color-panel.js
+++ b/packages/block-editor/src/hooks/color-panel.js
@@ -6,12 +6,11 @@ import { useState, useEffect } from '@wordpress/element';
 /**
  * Internal dependencies
  */
-import PanelColorGradientSettings from '../components/colors-gradients/panel-color-gradient-settings';
+import ColorGradientSettingsDropdown from '../components/colors-gradients/dropdown';
 import ContrastChecker from '../components/contrast-checker';
 import InspectorControls from '../components/inspector-controls';
 import useMultipleOriginColorsAndGradients from '../components/colors-gradients/use-multiple-origin-colors-and-gradients';
 import { __unstableUseBlockRef as useBlockRef } from '../components/block-list/use-block-props/use-block-refs';
-import { __ } from '@wordpress/i18n';
 
 function getComputedStyle( node ) {
 	return node.ownerDocument.defaultView.getComputedStyle( node );
@@ -63,24 +62,24 @@ export default function ColorPanel( {
 	const colorGradientSettings = useMultipleOriginColorsAndGradients();
 
 	return (
-		<InspectorControls>
-			<PanelColorGradientSettings
+		<InspectorControls __experimentalGroup="color">
+			<ColorGradientSettingsDropdown
 				enableAlpha={ enableAlpha }
+				panelId={ clientId }
 				settings={ settings }
+				__experimentalIsItemGroup={ false }
 				__experimentalHasMultipleOrigins
 				__experimentalIsRenderedInSidebar
 				{ ...colorGradientSettings }
-				title={ __( 'Color' ) }
-			>
-				{ enableContrastChecking && (
-					<ContrastChecker
-						backgroundColor={ detectedBackgroundColor }
-						textColor={ detectedColor }
-						enableAlphaChecker={ enableAlpha }
-						linkColor={ detectedLinkColor }
-					/>
-				) }
-			</PanelColorGradientSettings>
+			/>
+			{ enableContrastChecking && (
+				<ContrastChecker
+					backgroundColor={ detectedBackgroundColor }
+					textColor={ detectedColor }
+					enableAlphaChecker={ enableAlpha }
+					linkColor={ detectedLinkColor }
+				/>
+			) }
 		</InspectorControls>
 	);
 }
diff --git a/packages/block-editor/src/hooks/color.js b/packages/block-editor/src/hooks/color.js
index 52ade28f37..3219e01692 100644
--- a/packages/block-editor/src/hooks/color.js
+++ b/packages/block-editor/src/hooks/color.js
@@ -76,6 +76,60 @@ const hasTextColorSupport = ( blockType ) => {
 	return colorSupport && colorSupport.text !== false;
 };
 
+/**
+ * Clears a single color property from a style object.
+ *
+ * @param {Array}  path  Path to color property to clear within styles object.
+ * @param {Object} style Block attributes style object.
+ * @return {Object} Styles with the color property omitted.
+ */
+const clearColorFromStyles = ( path, style ) =>
+	cleanEmptyObject( immutableSet( style, path, undefined ) );
+
+/**
+ * Clears text color related properties from supplied attributes.
+ *
+ * @param {Object} attributes Block attributes.
+ * @return {Object} Update block attributes with text color properties omitted.
+ */
+const resetAllTextFilter = ( attributes ) => ( {
+	textColor: undefined,
+	style: clearColorFromStyles( [ 'color', 'text' ], attributes.style ),
+} );
+
+/**
+ * Clears link color related properties from supplied attributes.
+ *
+ * @param {Object} attributes Block attributes.
+ * @return {Object} Update block attributes with link color properties omitted.
+ */
+const resetAllLinkFilter = ( attributes ) => ( {
+	style: clearColorFromStyles(
+		[ 'elements', 'link', 'color', 'text' ],
+		attributes.style
+	),
+} );
+
+/**
+ * Clears all background color related properties including gradients from
+ * supplied block attributes.
+ *
+ * @param {Object} attributes Block attributes.
+ * @return {Object} Block attributes with background and gradient omitted.
+ */
+const clearBackgroundAndGradient = ( attributes ) => ( {
+	backgroundColor: undef [...]

2022-05-17 04:16 UTC, aaronrobertshaw commented on packages/block-editor/src/components/colors-gradients/dropdown.js
> +		</Item>
This should be rendering a `Button` as the toggle component as we are no longer rendering an `ItemGroup`.

2022-05-17 04:16 UTC, aaronrobertshaw commented on packages/block-editor/src/components/colors-gradients/dropdown.js
> +			'block-editor-tools-panel-color-gradient-settings__dropdown',
Based on the removed code, shouldn't this class be `block-editor-panel-color-gradient-settings__dropdown`? 

```suggestion
			'block-editor-panel-color-gradient-settings__dropdown',
```

That class is also targeted by a couple of e2e tests e.g. `heading.test.js` & `keep-styles-on-block-transforms.test.js`

2022-05-17 04:16 UTC, aaronrobertshaw commented on packages/block-editor/src/components/colors-gradients/panel-color-gradient-settings.js
> +			shouldRenderPlaceholderItems={ true } // Required to maintain fills ordering.
These should only be needed if rendering `ToolsPanelItem`s via slots which we aren't doing for this panel.

2022-05-17 04:16 UTC, aaronrobertshaw commented on packages/block-editor/src/hooks/color-panel.js
> +			<PanelColorGradientSettings
This removes our ability to render new, ad-hoc or 3rd party color controls into the Color panel. 

Unfortunately, I believe this change needs to be reverted, which in turn reduces some of the code we can delete here handling callbacks. The example use of `batch` in this PR could lead to some cleanup of the ToolsPanel component though, which might allow us to revisit the color block support utils and reduce the code there further as a follow-up.

The ability to render via SlotFill into this color panel is also a potential solution to the odd behaviour with the Cover block overlay and opacity controls after changing `PanelColorGradientSettings` to use the `ToolsPanel` i.e. "reset all" doesn't reset opacity. 

I have some trial code floating around that moves these Cover controls into the Color panel, I'll put that up in a PR for further discussion.

2022-05-17 04:16 UTC, aaronrobertshaw commented on packages/components/src/tools-panel/styles.ts
> +	/* Required to meet specificity requirements */
If we aren't wrapping contents of the non-SlotFill `ToolsPanel` in `PanelColorGradientSettings` as per my comment above, we might be able to avoid this increase in CSS and specificity.

2022-05-17 04:16 UTC, aaronrobertshaw commented on packages/block-editor/src/components/colors-gradients/panel-color-gradient-settings.js
> +	const panelId = useInstanceId( PanelColorGradientSettingsInner )
```suggestion
	const panelId = useInstanceId( PanelColorGradientSettingsInner );
```

My understanding is that the `panelId` is only needed for rendering via slot fills into the `ToolsPanel`. We could probably leave it out here given the `PanelColorGradientSettings` panels aren't leveraging slots.

2022-05-17 04:16 UTC, aaronrobertshaw commented on packages/block-editor/src/components/colors-gradients/style.scss
> -	width: 100%;
We'll still need this and a few of the other styles below if reverting the toggle's CSS class to the original `.block-editor-panel-color-gradient-settings__dropdown`

2022-05-17 07:40 UTC, aaronrobertshaw commented on packages/block-editor/src/hooks/color-panel.js
> +			<PanelColorGradientSettings
Draft PR up in https://github.com/WordPress/gutenberg/pull/41102 for moving the Cover color-related controls to the Color panel.

2022-05-17 22:14 UTC, jorgefilipecosta commented
Hi @aaronrobertshaw, thank you for the review and for providing a patch with your suggestions. I think your suggestions are in the right direction and I applied your patch 👍 Is there any other change you think we should do?

I think your PR enhancing things on the cover block is nice and we should merge it as a follow-up.

2022-05-17 22:14 UTC, jorgefilipecosta commented
Hi @aaronrobertshaw, thank you for the review and for providing a patch with your suggestions. I think your suggestions are in the right direction and I applied your patch 👍 Is there any other change you think we should do?

I think your PR enhancing things on the cover block is nice and we should merge it as a follow-up.

2022-05-18 03:33 UTC, aaronrobertshaw approved these changes
I've re-tested this after the latest updates and it's working well for me 👍 

✅ General color block supports still display and function correctly
✅ Cover block color panel works (opacity reset issue to be addressed via https://github.com/WordPress/gutenberg/pull/41102)
✅ Social Links contrast checker displays within the related panel now
✅ Navigation block color controls work as before
✅ Tested injecting color controls into block supports panel via https://github.com/WordPress/gutenberg/pull/41102

> Is there any other change you think we should do?

I believe this PR covers all we need for now. Anything else should be able to be addressed via a follow-up.

2022-05-18 18:23 UTC, merged

2022-05-18 18:23 UTC, jorgefilipecosta commented
Thank you a lot for the help in this PR @aaronrobertshaw!

2022-06-02 10:56 UTC, rmorse commented
Hey @jorgefilipecosta 

Looking at these latest changes, I can see `ColorGradientSettingsDropdown` is now always wrapped in a `ToolsPaneltem`

This makes using it anywhere else impossible - I'd like to use this in a regular panel, in a custom block.

My code is working with WP 5.9 and 6.0, but trying after this update nothing shows (naturally).

Is it completely necessary to make the change preventing this from working outside a `ToolsPanel`?

Would it make more sense to name the component (or offer a secondary version, wrapped in `ToolsPanelItem`) something like: `ToolsPanelColorGradientSettingsDropdown`?

Its a really useful component and would love to carry on using it.

2022-09-01 14:36 UTC, jorgefilipecosta commented
Hi @rmorse, thank you for reporting this issue. Let's continue the conversation on https://github.com/WordPress/gutenberg/issues/42692.