Fix Nav block text color specificity to override Theme JSON styles
WordPress/gutenberg pull request #41199
Opened 2022-05-20 11:40 UTC by getdave

## What?
Fixes https://github.com/WordPress/gutenberg/issues/41146 by ensuring that Nav block specific text color styles take precedence over inherited Theme JSON styles.

## Why?

In https://github.com/WordPress/gutenberg/issues/41146#issuecomment-1132775573 we learnt that the Theme JSON styles coming from text color styles on the enclosing Group block (the one wrapping the Nav block) were taking precedence over the user selected text color styles on the Nav block.

The block specific user styles should always win out. 

This was happening because the specificity of the Nav block styles was super low.

## How?

The fix employed is to increase the specificity of the selector targetting the Nav item contents, by taking account of the `.has-text-color` class which is applied to the Nav block when a text color is set specifically on the block. 

This still allows the text color to be inherited from the parent Nav block whilst also ensuring it takes precedence on any CSS styles cascading from parent blocks.

## Testing Instructions

- Add a Nav block and some items.
- Wrap the Nav in a Group and set a text color on that group.
- See that the Nav inherits the text color set on the Group
- Now set a specific Text Color on the Nav block which is different to that on the Nav block.
- See that this color is respected.
- Save and check the front end.

## Screenshots or screencast

2022-05-20 12:24 UTC, scruffian commented
I'm not sure about this approach. It seems to me that the behaviour in the editor is the correct behaviour. In CSS if I set a link color in an element then to override it I need to set a different _link_ color in the child - setting a text color in the child won't be enough. 

I think what we need to do is to make it possible to set a link color in the nav block, rather than a text color. This is a bit confusing though as I'm not sure its possible to have text in a navigation block which isn't a link, although one day it probably will be.

2022-05-20 13:34 UTC, getdave commented
> I'm not sure about this approach. It seems to me that the behaviour in the editor is the correct behaviour. In CSS if I set a link color in an element then to override it I need to set a different _link_ color in the child - setting a text color in the child won't be enough.
> 
> I think what we need to do is to make it possible to set a link color in the nav block, rather than a text color. This is a bit confusing though as I'm not sure its possible to have text in a navigation block which isn't a link, although one day it probably will be.

Yeh you're right. It's the link color not the text color that's overwriting the block specific styles. Ok let's add linkcolor support to the Nav block.

2022-05-20 13:47 UTC, getdave commented
@scruffian I added `linkColor` support to the Nav block and adjusted the CSS selector to `has-link-color`.

2022-05-20 13:54 UTC, getdave commented
@scruffian I've noticed the CSS specificity is different in the editor on the Global Styles selector due to it being prepended with `.editor-styles-wrapper`. That's causing the inherit behaviour to be off on the front end.

2022-05-20 19:38 UTC, scruffian commented on packages/block-library/src/navigation/style.scss
>  		color: inherit;
I think we should remove this line. `.wp-block-navigation-item__content` is a class that is used on a link. This line forces links to inherit their color from their parent which is against the pattern of CSS.

2022-05-20 20:01 UTC, scruffian commented
Sorry, I'm not sure the approach here is the right one. The elements API expects the link color to be stored in a very specific attribute:

https://github.com/WordPress/gutenberg/blob/d36ee9642b5d64e08cf088839dd3179d8d310429/lib/block-supports/elements.php#L98

If we do this then we won't need to write any custom code to apply the colors, as the library should take care of that for us.

2022-05-23 08:04 UTC, getdave commented
> If we do this then we won't need to write any custom code to apply the colors, as the library should take care of that for us.

I'm pretty sure the Nav block doesn't follow "the rules" here. All the stuff for text and background color is custom coded. I think this is because the colours aren't intended for the Nav block itself but rather to be inherited by the child blocks.

I can try uses the standard approach you suggest but I deliberately avoided this and followed the patterns that have already been established in the block (e.g. `textColor`).

2022-05-23 08:28 UTC, getdave commented
Some more research reveals that the need for custom colors for the `Submenu and Overlay` is probably the reason why we have a custom `colors` implementation here.

If I add support for `linkColor` using the "standards" way via `block.json` 

```json
"supports": {
    "color": {
        "link": true
    }
}
```

...then I get x2 color controls:

<img width="747" alt="Screen Shot 2022-05-23 at 09 18 24" src="https://user-images.githubusercontent.com/444434/169776963-d86060d4-9592-4573-b4fe-fa9a7ae70a38.png">

In the longer term we may need a wider refactor of how Submenu and Overlay colors are handled. For now though in order to fix this bug I think building on the existing custom implementation would be fine.

2022-05-23 08:33 UTC, getdave commented
Other options:

## Separate Submenu & Overlay colors panel

We can use standard block supports for the text, link and background colors.

Then we can have a dedicated panel for the "custom" color controls for Submenu and Overlay.

<img width="764" alt="Screen Shot 2022-05-23 at 09 31 45" src="https://user-images.githubusercontent.com/444434/169778069-94736c9d-b388-4d87-ba1f-22e41a31bd63.png">

2022-05-23 08:35 UTC, scruffian commented
Ok, this one is going to get complicated. My suggestion is:
- Ship this (or something like it) to fix the bug
- Look into what an ideal solution might look like...

2022-05-23 15:03 UTC, draganescu requested changes
I believe this is a good opportunity to not patch to fix. If I am not mistaken we'd be introducing things that we'll need to remove later.

We already have a system in place and we should try to improve that one for this specific use case:

- properties set on parents should be inherited by children, unless children override them

As far as I understand the global styles system supports this just fine, but the navigation block has a custom implementation. Maybe it's time to remove that and make sure we fit into what the platform currently offers? Probably at the time the global styles system did not offer us a way to implement what we wanted, or whatever was the reason.

I understand that refactoring is a big undertaking and the bug is now, but fixing will require us to support temporary solutions and remove them later, they're not even experimental. Also, I believe the fix now refactor later should only apply to core on critical bugs. Is this color inheritance on one block a critical bug?

2022-05-23 15:03 UTC, draganescu commented on packages/block-library/src/navigation-link/block.json
> +		"customLinlColor",
```suggestion
		"customLinkColor",
```

2022-05-23 15:43 UTC, getdave commented
Thanks for your review @draganescu . It's much appreciated.

> I believe this is a good opportunity to not patch to fix. If I am not mistaken we'd be introducing things that we'll need to remove later.

You are correct. The question is, how much are we really compounding the problem vs being able to move quickly to patch a fix. 

> As far as I understand the global styles system supports this just fine, but the navigation block has a custom implementation.
> Probably at the time the global styles system did not offer us a way to implement what we wanted, or whatever was the reason.

Global Styles has block supports for `color` which supports text, link and background. However there is no way to add custom colors AFAIK.

The Nav block has a custom implementation for these things because we need to support custom color setitngs for overlay and submenu as per https://github.com/WordPress/gutenberg/pull/41199#issuecomment-1134351817.

> I understand that refactoring is a big undertaking and the bug is now, but fixing will require us to support temporary solutions and remove them later, they're not even experimental. Also, I believe the fix now refactor later should only apply to core on critical bugs. Is this color inheritance on one block a critical bug?

I think we owe it to the original reporters and our Themes community to check on the impact of this bug. If it's something that can be "managed" we can go straight to the refactor. If it's critical then we'll need to patch and then refactor.

I would also prefer _**not**_ to compound the existing tech debt 👍

2022-07-01 11:09 UTC, getdave commented
Closing this one as I have a new plan. I will raise a PR shortly.

2022-07-01 11:09 UTC, closed without merging