Reorganize global styles menu
WordPress/gutenberg pull request #41574
Opened 2022-06-07 11:14 UTC by vcanales

Implements the second alternative shown in https://github.com/WordPress/gutenberg/issues/40478
to reorganize the Global Styles panel to keep both Blocks and Browse
styles links in line with the rest of the menu.

Let's iterate over this PR to decide on which of the two options makes
more sense.

### Preview

![Kapture 2022-06-07 at 12 11 51](https://user-images.githubusercontent.com/1157901/172366142-b51e8760-a765-4ad1-94f6-5b2abf20bed0.gif)

2022-06-07 17:48 UTC, critterverse requested changes
Nice! This feels so easy to read and navigate. Curious to hear from @pablohoneyhoney and others who have done a lot of work on the Global Styles panel about whether this seems like the right (small, incremental) next step towards simplifying the panel — especially before potentially adding more items there.

One small note that we don't need the divider line after the "Blocks" item.

2022-06-08 09:23 UTC, vcanales commented
> One small note that we don't need the divider line after the "Blocks" item.

Done!

<img width="281" alt="image" src="https://user-images.githubusercontent.com/1157901/172581628-1616b10e-ec7a-4df1-b94c-416a4a1ef993.png">

2022-06-08 13:07 UTC, critterverse commented
Nice. Pinging [@WordPress/gutenberg-design](https://github.com/orgs/WordPress/teams/gutenberg-design) to get some more eyes on this!

2022-06-16 18:00 UTC, vcanales commented
> Nice. Pinging @WordPress/gutenberg-design  to get some more eyes on this!

Cool! Looking forward to a decision!

2022-06-16 18:12 UTC, javierarce commented
It's great to simplify the sidebar, but I find it weird to have "Browse styles" between Layout and Blocks. Those two items have more things in common than with the "Browse style" one, so I think they should be together.

I think something like the following list makes more sense and would be easier to scan and use:

Browse styles

Typography
Colors
Layout
Blocks

2022-06-17 10:27 UTC, jameskoster commented
I agree that the order doesn't feel quite right. As I understand it Styles are essentially preset configurations for block, layout, typography, and color, and so exist a layer above those areas.

Perhaps not something to figure out here, but I find it a little strange to find a "Styles" section _within_ the "Styles" panel.

2022-06-21 13:39 UTC, mtias commented
I missed the issue that sparked this, but this seems to mix the IA in ways that are more confusing. It's important to keep the Blocks panel separate from the style elements, and the "browse styles" exists at an entirely different level. This design fails to communicate this in any meaningful way.

2022-06-21 13:52 UTC, critterverse commented
@vcanales I think we could close this PR based on the feedback above and revisit this with a reconsidered design approach.

2022-06-21 14:09 UTC, vcanales commented
> @vcanales I think we could close this PR based on the feedback above and revisit this with a reconsidered design approach.

Closing!

2022-06-21 14:09 UTC, closed without merging