Remove broken link- success.docker.com
WordPress/gutenberg pull request #41758
Opened 2022-06-16 05:16 UTC by SavPhill

I have removed the link titled 'How do I enable the remote API for dockerd' which points to: https://success.docker.com/article/how-do-i-enable-the-remote-api-for-dockerd as the success.docker.com domain is no longer available.

## What?

The documentation reference to success.docker.com is no longer available and therefore this causes a broken link in our own documentation.

## Why?

To prevent users accessing a broken link or incorrect link when trying to find addition documentation.

## How?

I have looked for an alternative article in docs.docker.com, but I did not find the article or a close match.
## Testing Instructions

## Screenshots or screencast

2022-06-16 06:39 UTC, alexstine commented
Hmm, this seems tricky to me. I'm not sure we want to be in the business of just showing people how to modify their Docker system files without real links to docs or at least some trustworthy resource. Any of the docs watchers on this PR know if this might be okay for outside linking? I really don't know how that works.

Here are the guidelines set by the Docs Team but not sure if Gutenberg follows similar or different guidelines.
https://make.wordpress.org/docs/style-guide/linking/external-links/

I found this site to give a nice overview.
https://scriptcrunch.com/enable-docker-remote-api/

However, this is not for all operating systems. It seems this is purely a Linux bug.

Some part of me actually wonders if this bug still exists. Kind of odd to see nothing mentioned about it in official docs.

2023-06-04 08:44 UTC, SavPhill commented
@alexstine Giving this PR a bump as it's 1 year without movement. What action should we take or should we discard this?

2023-06-04 18:03 UTC, alexstine commented
CC: @noahtallen @ObliviousHarmony

2023-06-13 01:11 UTC, noahtallen requested changes
I think I found the right link: https://docs.docker.com/config/daemon/remote-access/

2023-06-13 01:11 UTC, noahtallen commented on docs/getting-started/devenv/docker-ubuntu.md
> +If docker is running, then it is not listening how the WordPress environment is trying to communicate. Try adding the following service override file to include listening on tcp.
```suggestion
If docker is running, then it is not listening how the WordPress environment is trying to communicate. Try adding the following service override file to include listening on tcp. See [this Docker documentation](https://docs.docker.com/config/daemon/remote-access/) on how to configure remote access for Docker daemon.```

2023-06-13 02:07 UTC, SavPhill commented
> I think I found the right link: https://docs.docker.com/config/daemon/remote-access/

Thanks Noah

2023-06-13 17:23 UTC, noahtallen approved these changes

2023-06-13 17:24 UTC, merged