Fix link to "Good First Review" issues in README
WordPress/gutenberg pull request #41754
Opened 2022-06-15 19:32 UTC by mcliwanow

## What?

This PR fixes URL of the "Good First Review" link. Previously, it pointed to open issues with label "Good First Issue". After changes it's pointing to open issues with label "Good First Review".

## Why?

I was going through docs for contributors and when I clicked the "Good First Review" link I noticed it took me to the wrong page so I decided to fix it. It's not a biggie and I hope to contribute in more meaningful way in the future :)

## How?

Nothing fancy, just updated URL of the link in README file.

## Testing Instructions

1. Check if the link to "Good First Review" filter works correctly from Github:
  - Go to https://github.com/mcliwanow/gutenberg/blob/fix/link-to-good-first-review/docs/contributors/code/README.md (updated README file)
  -  Click the "Good First Review" link
  - Verify that you are taken to open issues for the Gutenberg repository and that label "Good First Review" is selected
2.  If your IDE support Previewing `.md` files then:
  - Checkout branch from this PR on your machine
  - Open file `docs/contributors/code/README.md` in Preview mode <img width="1210" alt="image" src="https://user-images.githubusercontent.com/4765119/173907687-0e266fc5-51d2-4dff-913e-45929d480be7.png">
  - Click the "Good First Review" link 
  - Verify that you are taken to open issues for the Gutenberg repository and that label "Good First Review" is selected

2022-06-15 22:42 UTC, skorasaurus requested changes
Thanks for your effort; the good first review link should be for pull requests and go to https://github.com/WordPress/gutenberg/pulls?q=is%3Aopen+is%3Apr+label%3A%22Good+First+Review%22

2022-06-16 05:09 UTC, glendaviesnz commented on docs/contributors/code/README.md
> +Browse [the issues list](https://github.com/wordpress/gutenberg/issues) to find issues to work on. The [good first issue](https://github.com/wordpress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A
Thanks for this, I think the link needs to be `https://github.com/wordpress/gutenberg/pulls?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Review%22`  - I just get an empty list when I go to `https://github.com/wordpress/gutenberg/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Review%2`

2022-06-16 06:19 UTC, mcliwanow commented
>  the good first review link should be for pull requests and go to https://github.com/WordPress/gutenberg/pulls?q=is%3Aopen+is%3Apr+label%3A%22Good+First+Review%22

I feel a little bit embarrassed now 😬 😉  Thanks for pointing that out @skorasaurus ! I have updated code and PR description accordingly.

2022-06-16 06:50 UTC, fabiankaegy approved these changes
Tested the new link and it works as expected :) Thanks for your contribution! :)

2022-06-16 07:17 UTC, merged