Remove top margin on the first paragraph in a modal
WordPress/gutenberg pull request #42369
Opened 2022-07-12 13:05 UTC by jameskoster

## What?
This PR removes the top margin when a paragraph immediately follows `.components-modal__header`.

## Why?
Because the top margin is creating a too-large space between the modal header and the modal content:

<img width="533" alt="Screenshot 2022-07-12 at 13 58 06" src="https://user-images.githubusercontent.com/846565/178496241-ff3832bb-459b-4a87-a206-1ccff3a45c0d.png">

## How?
Just a small CSS tweak:

```
.components-modal__header + p { 
margin-top: 0; 
}

```
## Testing Instructions
1. Open a modal where a paragraph immediately follows the modal header, one example is the selection step when creating a template for a specific post.
2. Ensure the first paragraph has no top margin.

## Screenshots or screencast 
<img width="530" alt="Screenshot 2022-07-12 at 14 05 04" src="https://user-images.githubusercontent.com/846565/178496740-6484efea-0ff2-4545-b375-04bb8862dc23.png">

2022-07-12 13:42 UTC, critterverse requested changes
Looks better! Quick note that I'm still seeing the top margin on the locking modal.

2022-07-12 14:00 UTC, jameskoster commented
Good spot, it's because that paragraph is inside a `form`. We'll either have to move it, or add more styling.

2022-07-12 16:22 UTC, jameskoster commented
I opted to move the paragraph.

<img width="561" alt="Screenshot 2022-07-12 at 17 20 51" src="https://user-images.githubusercontent.com/846565/178543367-96d575c2-97f7-4362-89ad-0c3126d35f00.png">

2022-07-13 12:29 UTC, andreszs commented
Nice PR. It's good to see I'm not the only one annoyed by that constant abuse of **nonsense margins and paddings** by designers. Specially Microsoft's designers, which should be detained and charged with margin and padding extremism.

2022-07-14 13:59 UTC, javierarce approved these changes
LGTM!

2022-07-14 14:03 UTC, paaljoachim commented
A quick look. It seems fine to me.

2022-07-14 15:58 UTC, critterverse approved these changes

2022-07-15 02:19 UTC, merged