Block Editor: Pressing enter at start of the text block prepends a block
WordPress/gutenberg pull request #42462
Opened 2022-07-15 10:27 UTC by gziolo

## What?

## Why?

## How?

## Testing Instructions

## Screenshots or screencast

2022-07-19 13:44 UTC, ntsekouras commented on packages/block-library/src/verse/edit.js
> +					insertBeforeBlock( clientId );
Do you think we should create a similar function to [onInsertBlocksAfter](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-list/block.js#L287) ?

2022-07-19 13:49 UTC, gziolo commented on packages/block-library/src/verse/edit.js
> +					insertBeforeBlock( clientId );
What benefits do you see with introducing another prop passed down a few levels down?

2022-07-19 14:05 UTC, ntsekouras commented on packages/block-library/src/verse/edit.js
> +					insertBeforeBlock( clientId );
Not much to be honest, but the minor things could be:
1. consistency with the `after`
2. more flexibility to what block/blocks to insert - although I don't have a use case on top of my mind that we would want something different. Maybe that might be useful to blocks with innerBlocks that allow specific blocks similar to new List? I haven't checked in depth though.. 

No strong opinions here 😄

2022-07-19 14:28 UTC, gziolo commented on packages/block-library/src/verse/edit.js
> +					insertBeforeBlock( clientId );
`onInsertBlocksAfter` / `insertBlocksAfter` was added before React hooks were used. That's why it was exposed through `withDispatch` HOC. I would personally go in the opposite direction and refactor code in other places to use `useDispatch` and pick the right action for the job: `insertBlocks` is a general one that gives maximum flexibility, `insertBeforeBlock` is great when you want to prepend the default block. There is also `insertAfterBlock` available. If necessary, we can also extend those more specific actions to accept a different block(s) optionally.

2022-07-19 14:29 UTC, gziolo commented on packages/block-library/src/verse/edit.js
> +					insertBeforeBlock( clientId );
See also my note in the description:

> Optionally, we might also consider making both `onEnterAtStart` and `onEnterAtEnd` more abstracted in RichText from `@wordpress/block-editor` and allow passing `true`, example:
>
> `<RichText onEnterAtStart onEnterAtEnd />`
>
> that would default to the callback that automatically finds the current client id of the block and inserts a new default block before/after the block.

2022-07-19 14:35 UTC, ntsekouras commented on packages/block-library/src/verse/edit.js
> +					insertBeforeBlock( clientId );
Sounds good!

2022-07-19 15:34 UTC, ellatrix requested changes
Looking at the video, focus moves to the newly inserted block before the current block. That seems wrong. If you press Enter at the start of a heading for example, you'll notice that focus stays in the heading.

Secondly, I'm not sure if this behaviour makes sense to me. Splitting from the start makes sense for blocks that don't insert a newline on Enter. But code and verse etc. do insert newlines on Enter. So why should it split when at the start of the block? It's now impossible to create a new line before the existing content and add something there.

It could however make sense to add split on **double** Enter for these blocks.

2022-07-20 10:49 UTC, gziolo commented
@ellatrix, thank you for feedback.

> It could however make sense to add split on double Enter for these blocks.

This is how pressing `enter` key at the start of the Verse block behaves in `trunk`:

https://user-images.githubusercontent.com/699132/179963675-5f3e3a3d-be32-4190-abe3-09bc0fbc8315.mov

It's hard to tell whether double `enter` would be an optimal choice.

I see that in the Classic block you can use arrow up/down to insert a paragraph after/before. Maybe that could be a way to improve the current writing flow?

https://user-images.githubusercontent.com/699132/179964249-e4372bb6-9bfa-4105-876d-71809c343c15.mov

2022-07-21 11:40 UTC, ellatrix commented
> It's hard to tell whether double enter would be an optimal choice.

Yes, it only really makes sense for inserting it after the block, not before.

> I see that in the Classic block you can use arrow up/down to insert a paragraph after/before. Maybe that could be a way to improve the current writing flow?

That sounds interesting, although it's hard with FSE and even in the post editor where you could want to navigate to the title.
This actually reminds me of something I wanted to do a while back: it would be cool if arrow key navigation to other blocks had an intermediary step that focusses the in-between inserter. So that could solve your issue here. On arrow up, focus moves to the inserter before the block before moving to the next block so you can insert something. I have a branch somewhere locally that attempts this.

2022-07-21 12:08 UTC, gziolo commented
> it would be cool if arrow key navigation to other blocks had an intermediary step that focusses the in-between inserter. 

In the case where you interact with the first block, then there is no in-between inserter, but maybe there should be something like that.

> On arrow up, focus moves to the inserter before the block before moving to the next block so you can insert something. I have a branch somewhere locally that attempts this.

It would be great to try that instead then 👍🏻

2022-07-27 16:22 UTC, mtias commented
I feel focusing on in between state would make the experience of moving through text worse or less intuitive

2022-09-14 13:32 UTC, gziolo commented
I didn't make any further progress on this PR, and I won't have time in the near future. I'm closing this PR but everyone is invited to take it over.

2022-09-14 13:32 UTC, closed without merging