Fix typo in Readme
WordPress/gutenberg pull request #4350
Opened 2018-01-08 07:17 UTC by burhandodhy

## Description
Typo fix in README.md.

1) metaboxes=> meta-boxes
2) Removed trailing spaces
3) Add space after sentence complete

## How Has This Been Tested?

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

2018-01-09 13:46 UTC, aduth requested changes
The core documentation uses "meta box" (two words) when referring to this feature. I think we ought to do the same here?

Example: https://developer.wordpress.org/plugins/metadata/custom-meta-boxes/

2018-01-09 16:54 UTC, burhandodhy commented
Yes, you are right. I change it to two words.

2018-01-10 00:30 UTC, ntwb approved these changes

2018-01-10 00:46 UTC, aduth approved these changes

2018-01-10 00:46 UTC, merged

2018-01-10 00:46 UTC, aduth commented
Nice!