Lodash: Remove completely from `@wordpress/format-library` package
WordPress/gutenberg pull request #43738
Opened 2022-08-31 11:21 UTC by tyxla

## What?
This PR removes all of the Lodash from the `@wordpress/format-library` package, including the `lodash` dependency altogether. There are just a few usages and conversion is pretty straightforward. 

## Why?

Lodash is known to unnecessarily inflate the bundle size of packages, and in most cases, it can be replaced with native language functionality. See these for more information and rationale:

* https://github.com/WordPress/gutenberg/issues/16938#issuecomment-602837246
* https://github.com/WordPress/gutenberg/issues/17025
* https://github.com/WordPress/gutenberg/issues/39495 

## How?

We're replacing a few usages with their native counterparts. 

## Testing Instructions

* On both web and mobile, make sure to test: 
  * Setting text color in a paragraph block (see #36028 for testing details on mobile)
  * Setting a text to be a link in a paragraph block (see #12249 for testing details on mobile)
* Verify all checks are green.

2022-08-31 11:31 UTC, aristath approved these changes
I didn't test on mobile, but tested on desktop and reviewed the code. LGTM! 👍

2022-08-31 11:36 UTC, tyxla commented
> I didn't test on mobile, but tested on desktop and reviewed the code. LGTM! 👍

Thanks, @aristath! 

I'll hold off merging until the React Native folks to confirm this isn't breaking anything on mobile.

2022-09-01 17:07 UTC, dcalhoun requested changes
Thank you for notifying the mobile team. 🙇🏻 

I tested these changes on an iPhone simulator and Android emulator. I encountered one crash that we should resolve before merging this work please.

2022-09-01 17:07 UTC, dcalhoun commented on packages/format-library/src/link/index.native.js
> +						value.formats[ startIndex ].find(
This change causes a crash. It appears `value.formats[ startIndex ]` sometimes returns `undefined`, which `find` must've gracefully handled previously. 

```suggestion
						value.formats[ startIndex ]?.find(
```

2022-09-01 17:07 UTC, dcalhoun commented on packages/format-library/src/link/index.native.js
> +						value.formats[ endIndex ].find(
Similar to the `startIndex`, this can be `undefined`. 
```suggestion
						value.formats[ endIndex ]?.find(
```

2022-09-02 08:00 UTC, tyxla commented on packages/format-library/src/link/index.native.js
> +						value.formats[ startIndex ].find(
Thanks for this! Addressed in 6e7ec5fe30b2db3aa06859ae115fda878a6f8cea.

2022-09-02 08:00 UTC, tyxla commented on packages/format-library/src/link/index.native.js
> +						value.formats[ endIndex ].find(
Addressed as part of 6e7ec5fe30b2db3aa06859ae115fda878a6f8cea.

2022-09-02 08:00 UTC, tyxla commented
Feedback has been addressed - could I get one last look, @dcalhoun?

2022-09-02 13:42 UTC, dcalhoun approved these changes
🚀 Great work!

2022-09-02 14:31 UTC, tyxla commented
Thank you, @dcalhoun 🙌

2022-09-02 14:31 UTC, merged