Update: Show parent block as selected when there is content locking
WordPress/gutenberg pull request #43918
Opened 2022-09-06 16:10 UTC by jorgefilipecosta

Fix: https://github.com/WordPress/gutenberg/issues/43780
 This PR makes sure that when any block within a container is selected, the parent is also selected in List view.

2022-09-07 09:03 UTC, jameskoster requested changes
The correct block is highlighted in list view as expected. However, when you navigate away from that block, it remains selected:

<img width="1060" alt="Screenshot 2022-09-07 at 10 03 33" src="https://user-images.githubusercontent.com/846565/188837985-75d654f4-a7d3-49a1-8bc9-f70a5d731475.png">

2022-09-07 14:42 UTC, jorgefilipecosta commented
Nice catch @jameskoster the issue should be fixed.

2022-09-07 17:12 UTC, jameskoster commented
Thanks Jorge. 

One tiny nit-pick – selected items in list view should have a 2px border radius. I can see that when I select the group by clicking it in list view:

<img width="344" alt="Screenshot 2022-09-07 at 18 11 21" src="https://user-images.githubusercontent.com/846565/188938873-0dd8adbb-ecbc-411e-92c8-de34853ae006.png">

But when I select a block on the canvas, the radius is missing:

<img width="349" alt="Screenshot 2022-09-07 at 18 11 54" src="https://user-images.githubusercontent.com/846565/188938947-f3906368-6c4a-40a4-8d67-c784b6d1acab.png">

2022-09-08 16:41 UTC, jorgefilipecosta commented
> Thanks Jorge.
> 
> One tiny nit-pick – selected items in list view should have a 2px border radius. I can see that when I select the group by clicking it in list view:
> 
> <img alt="Screenshot 2022-09-07 at 18 11 21" width="344" src="https://user-images.githubusercontent.com/846565/188938873-0dd8adbb-ecbc-411e-92c8-de34853ae006.png">
> 
> But when I select a block on the canvas, the radius is missing:
> 
> <img alt="Screenshot 2022-09-07 at 18 11 54" width="349" src="https://user-images.githubusercontent.com/846565/188938947-f3906368-6c4a-40a4-8d67-c784b6d1acab.png">

Nice catch @jameskoster, the issue is fixed.

2022-09-09 11:34 UTC, jameskoster approved these changes

2022-09-09 14:20 UTC, merged