Scripts: Use start without watcher using --no-watch
WordPress/gutenberg pull request #44237
Opened 2022-09-17 12:29 UTC by kkmuffme

## What?
Sometimes there's a use case, where we don't want to use "npm start" with the watcher.

## Why?
"npm start" directly followed by Ctrl+C, or certain CI environments that want to create unminified JS for analysis without changing the config,...

## How?
- change package.json "start" to "wp-scripts start --no-watch"
- run "npm start -- --no-watch"

## Testing Instructions
any gutenberg, isntead of "npm start" run "npm start -- --no-watch", which will create the unminified/dev JS without starting the watcher.

2022-09-17 15:18 UTC, gziolo reviewed
Thank you for opening this PR. The change proposed makes sense 👍🏻 

There are some formatting issues and running `npm run format` will fix them.

2022-09-17 15:18 UTC, gziolo commented on packages/scripts/scripts/start.js
> +} else if ( hasArgInCLI( '--no-watch' ) === false ) {
It probably could be simplified to:
```suggestion
} else if ( ! hasArgInCLI( '--no-watch' ) ) {
```

2022-09-17 19:54 UTC, kkmuffme commented on packages/scripts/scripts/start.js
> +} else if ( hasArgInCLI( '--no-watch' ) === false ) {
Thanks, done.

2022-09-21 07:09 UTC, gziolo approved these changes
I added an entry in the Changelog file. I need to test it locally before merging to `trunk`.

2022-09-21 07:23 UTC, gziolo requested changes
It works correctly with `--no-watch` but breaks when the option is not passed:

<img width="678" alt="Screen Shot 2022-09-21 at 09 22 30" src="https://user-images.githubusercontent.com/699132/191440628-2b5aae44-d263-4860-ba4b-8bbbdea1069a.png">
<img width="694" alt="Screen Shot 2022-09-21 at 09 22 39" src="https://user-images.githubusercontent.com/699132/191440634-a2245010-f100-4b02-a12d-887f54d03e7a.png">

I created a test block with:

```bash
npx wp-create-block test-block --no-wp-scripts
cd test-block
```

All inside the Gutenberg repository.

2022-10-17 08:45 UTC, kkmuffme commented
Sorry for the delay, fixed now. It's ready to be merged now

2022-10-19 21:10 UTC, gziolo commented
Thank you for addressing my feedback. I will land it as soon as I have a chance to test it again.

2022-12-28 14:41 UTC, kkmuffme commented
@gziolo could you please check and merge this now?

2023-02-02 10:58 UTC, gziolo approved these changes
This tests well with the changes applied. Thank you so much.

2023-02-02 10:58 UTC, merged