Use default value for process.env.WP_SRC_DIRECTORY. Fixes #44309.
WordPress/gutenberg pull request #44367
Opened 2022-09-22 10:59 UTC by loxK

## What?
Fixes WordPress/gutenberg#44309

## Why?
See discussion here: https://github.com/WordPress/gutenberg/pull/43917#pullrequestreview-1113911446

## How?
Using wp-scripts command, if is not specified, `process.env.WP_SRC_DIRECTORY` defaults to string 'src'. When extending the webpack.config.js directly, it should behave the same.

2022-09-23 09:56 UTC, luisherranz reviewed
This looks about right to me. Thanks for the PR, Laurent 🙂

@gziolo, what do you think? Should we also centralize the default value defined on `build.js` and `start.js` so there's only a single place where the `'src'` string is defined?

2022-09-23 10:03 UTC, luisherranz requested changes
Oh, would you please rename the function from `getWebpackSrcDirectory` to `getWordPressSrcDirectory`? Thanks!

2022-09-23 10:03 UTC, luisherranz commented on packages/scripts/utils/config.js
> + * @return {string} the webpack src directory.
```suggestion
 * Returns the WordPress source directory. It defaults to 'src' if the `process.env.WP_SRC_DIRECTORY` variable is not set.
 *
 * @return {string} The WordPress source directory.
```

```suggestion
 * Returns the WordPress source directory. It defaults to 'src' if the `process.env.WP_SRC_DIRECTORY` variable is not set.
```

2022-09-24 00:00 UTC, loxK commented
> @gziolo, what do you think? Should we also centralize the default value defined on `build.js` and `start.js` so there's only a single place where the `'src'` string is defined?

I thought about it too, but decided it was up to you.

2022-09-24 00:17 UTC, loxK commented on packages/scripts/utils/config.js
> + * @return {string} the webpack src directory.
Done.

2022-09-26 11:10 UTC, gziolo reviewed
This looks good to go, @luisherranz is there anything I missed?

2022-09-26 12:38 UTC, luisherranz commented
> @luisherranz is there anything I missed?

If you think it's good, let's merge it 🙂

2022-09-26 12:38 UTC, luisherranz approved these changes

2022-09-26 12:38 UTC, merged

2022-09-26 12:40 UTC, luisherranz commented
Thanks for your contribution, @loxK!

2022-09-27 01:27 UTC, loxK commented
> Thanks for your contribution, @loxK!

I appreciate but it is nothing compared to how useful is WordPress to me. Thank YOU guys.

2022-10-24 18:35 UTC, annezazu commented
@loxK wanted to follow up - did you make a WordPress.org profile? If so, can you share the link here? For example, here's mine: https://profiles.wordpress.org/annezazu/ We'd love to gives you props in the next WordPress release but need your WordPress.org username to do so. 

You can follow the steps above to set it up correctly: https://github.com/WordPress/gutenberg/pull/44367#issuecomment-1257979289

Thank you!

2022-10-25 03:19 UTC, loxK commented
Here you go, thanks

https://profiles.wordpress.org/dreadlox/