QA: no control structures with empty body
WordPress/gutenberg pull request #44548
Opened 2022-09-28 21:22 UTC by jrfnl

## Why?
A control structure with an empty body is often indicative of "missing code", i.e. code which should have been added, but was forgotten.

For this reason, empty bodies for a control structure are flagged when using `WordPress-Extra`.

## How?
For the control structures in this PR, the "body" part is not needed and PHP allows for that without issue (for select control structures). See: https://3v4l.org/ADFk5

2022-09-28 21:58 UTC, dmsnell commented
Hi @jrfnl - thanks for the suggestion. I'd much rather see us add linter-exclude comments here.

hopefully it's obvious from the existing comments that the loop body is meant to be empty and not accidentally empty.

if we remove them altogether we _will_ appease the linter, but I am guessing that having a loop without any body (including the brackets will be even more confusing to people and look wrong at face value (meaning somebody might think they ought to fix it - which could break things).

2022-09-28 22:04 UTC, jrfnl commented
> Hi @jrfnl - thanks for the suggestion. I'd much rather see us add linter-exclude comments here.

Exclude comments should only be used for things which can't/shouldn't be fixed. This is not one of those cases.

> hopefully it's obvious from the existing comments that the loop body is meant to be empty and not accidentally empty.

It is, which is why I am proposing the fixes.

> if we remove them altogether we _will_ appease the linter, but I am guessing that having a loop without any body (including the brackets will be even more confusing to people and look wrong at face value (meaning somebody might think they ought to fix it - which could break things).

While I appreciate what you are saying, that is something which should be fixed by dev-education.

2022-09-28 22:10 UTC, dmsnell requested changes
> shouldn't be fixed

this is what I'm suggesting here. we can let other people chime in, but I would prefer to see this not merge based on consistency with existing code, the risks involved with `while (…);`, and the fact that we're taking something that's explicitly called out in the code to point to the oddity and replacing it with the absence of any indicator, and I suspect the reason for doing so is that a linter, which lacks basic understanding, suggested we should 😉

2022-09-28 22:56 UTC, jrfnl commented
> > shouldn't be fixed
> 
> this is what I'm suggesting here. we can let other people chime in, but I would prefer to see this not merge based on consistency with existing code, the risks involved with `while (…);`, and the fact that we're taking something that's explicitly called out in the code to point to the oddity and replacing it with the absence of any indicator, and I suspect the reason for doing so is that a linter, which lacks basic understanding, suggested we should 😉

Except that this is not a case of "shouldn't be fixed".

An example of "shouldn't be fixed" is code like this:
```php
if ( function_exist( 'fdiv' ) ) {
    return fdiv( ... );
}

// Polyfill the PHP 8.0 fdiv() function and return the result.
```

The above code would be flagged for the use of the PHP 8.0 `fdiv()` function, while there are sufficient safeguards for using it. This is what I mean by "shouldn't be fixed".

The code being flagged up in this PR is perfectly fixable though, either the way it is done in this PR or by rewriting the code to use a pattern like so:
```php
		while ( $this->parse_next_attribute() ) {
			continue;
		}
```

But hey, at the end of the day, decide what you want here, I'm only the maintainer of the WP Coding Standard, so what do I know ?

2022-09-29 20:29 UTC, dmsnell commented
> rewriting the code to use a pattern like so:

adding `continue` seems much better of a change to me, particularly because it leaves an explicit place mark that the loop is intentionally empty. the implicit empty loop seems to look like someone made a mistake and forgot it. at worst, in the case of a missing semicolon which wouldn't be obvious, it almost invites logical defects in the same way that happened with Apple's infamous SSL flaw.

```php
<?php

function keep_going() { static $i = 0; return $i++ < 5; }


while ( keep_going() )

/*
 * Now that we're done scanning the stuff
 * we can continue to do the real work,
 * or pretend we did and simply exclaim
 * that we're finished with our jobs.
 */
echo "Done";
```

> Done

```php

```

2022-09-29 22:27 UTC, jrfnl commented
> in the case of a missing semicolon

That shouldn't ever be able to happen as PHPCS will flag that up as an inline control structure, which is not allowed according to WPCS.

> adding continue seems much better of a change to me, particularly because it leaves an explicit place mark that the loop is intentionally empty.

Fair enough, I will update the PR to that effect.

---

> My purpose in the review was to state the reasons I believe the proposed change increases the risk in the code, why I disagree that the proposed linting fix makes the code better. If it came across as a personal attack I apologize as I meant nothing of the sort. 

Understood. It came across as very dismissive without even considering technical alternatives, let alone good understanding of the tooling, so yeah, it did not start us of on the right footing.

2022-09-29 23:01 UTC, dmsnell approved these changes
How would you feel about leaving the comments in? Either way is fine, but it's nice having some personality in there, and the extra callout that the loop's work is done inside the condition.

2022-09-29 23:02 UTC, dmsnell commented
> let alone good understanding of the tooling

you are correct! my understanding of the tooling is horridly insufficient :)

2022-09-30 00:06 UTC, jrfnl commented
> How would you feel about leaving the comments in? Either way is fine, but it's nice having some personality in there, and the extra callout that the loop's work is done inside the condition.

I can bring them back, but I don't see any value in them. They don't explain or point out _why_ the loop is empty, nor that the work is done inside the condition, so they don't really add anything.

2022-10-04 10:40 UTC, anton-vlasenko approved these changes

2022-10-04 10:41 UTC, merged

2022-10-04 20:13 UTC, dmsnell commented
> they don't really add anything.

just a little bit of humanity 😄