Embed Block: Add support for Tumblr Dashboard URLs.
WordPress/gutenberg pull request #44854
Opened 2022-10-11 05:18 UTC by pento

## What?

Following up on [WP56733](https://core.trac.wordpress.org/ticket/56733), this adds the corresponding regex for Tumblr Dashboard URLs to the Embed block.

## Testing Instructions

- Create a new post.
- Check that pasting this URL shows the correct Tumblr embed: https://photomatt.tumblr.com/post/696629352701493248/why-go-nuts-show-nuts-doesnt-work-in-2022
- Check that pasting this URL shows the correct Tumblr embed: https://www.tumblr.com/photomatt/696629352701493248/why-go-nuts-show-nuts-doesnt-work-in-2022

2022-10-13 08:42 UTC, c4rl0sbr4v0 commented
The second link is not working in my environment :-S

WordPress 6.1-alpha-54133
Gutenberg  14.3.0-rc.1 
![Screenshot 2022-10-13 at 10 41 17](https://user-images.githubusercontent.com/37012961/195547517-7d73c3ba-5463-4d27-9a86-577d515fff40.jpg)
![Screenshot 2022-10-13 at 10 42 32](https://user-images.githubusercontent.com/37012961/195547820-901d1525-19a8-448f-9147-1425589832ff.jpg)

2022-10-13 09:55 UTC, c4rl0sbr4v0 requested changes
The second URL provided is not working 😢

2022-10-14 00:05 UTC, pento commented
Thank you for testing, @c4rl0sbr4v0. Upon re-reading the code, I realised that the original regex was incorrect, but broad enough that the easier method was to modify it to allow all subdomains, rather than just `www`. (I suspect it was never properly triggered, it only worked because WordPress core provided support for subdomains.)

Additionally, the regex I added to core in [WP56733](https://core.trac.wordpress.org/ticket/56733) turned out to be incorrect. I'll re-open that ticket and get it fixed up. In order to test this PR, you may need to manually apply that fix to your WordPress install.

2022-10-18 16:54 UTC, ockham commented
I see that @pento added an alternative [patch](https://core.trac.wordpress.org/attachment/ticket/56733/56733.2.diff) to the Core ticket.

@c4rl0sbr4v0 Could you maybe give this another test, using that patch and @pento's [instructions](https://github.com/WordPress/gutenberg/pull/44854#issuecomment-1278302021)? 🙏 😊

2022-10-19 10:44 UTC, c4rl0sbr4v0 commented
Using this patch https://core.trac.wordpress.org/attachment/ticket/56733/56733.2.diff it works fine on both links.

2022-10-19 11:01 UTC, pento commented
Thanks for testing, @c4rl0sbr4v0! Would you mind commenting on the Core ticket to confirm that you tested it, so that can be committed, too?

2022-10-19 11:16 UTC, c4rl0sbr4v0 approved these changes
Works as expected applying this patch on Core: https://core.trac.wordpress.org/attachment/ticket/56733/56733.2.diff

2022-10-19 12:09 UTC, merged

2022-10-25 09:55 UTC, ockham commented
I just cherry-picked this PR to the wp/6.1 branch to get it included in the next release: d2dee79087