Navigation: Move manage menus button to the navigation selector
WordPress/gutenberg pull request #45785
Opened 2022-11-15 21:43 UTC by scruffian

## What?
This moves the "Manage menus" button inside the Navigation Menu Selector component

## Why?
This feels like a more natural home for this link since it relates directly to the contents of the selector.

## How?
This is a small refactoring since the previous code tidyup made things cleaner.

## Testing Instructions
1. Add a navigation block
2. Check that the manage menus link is available inside the navigation menu selector
 
## Screenshots or screencast 
<img width="280" alt="Screenshot 2022-11-15 at 21 23 17" src="https://user-images.githubusercontent.com/275961/202031281-d0c8da90-48d3-4a04-87d1-6372776e9c61.png">

2022-11-15 23:27 UTC, ajlende commented on packages/block-library/src/navigation/edit/index.js
> -						) }
I don't know how to test this branch of code, but from the code it looks like this instance of the button is removed entirely. Is that intentional?

2022-11-15 23:30 UTC, scruffian commented on packages/block-library/src/navigation/edit/index.js
> -						) }
Yes, because the button now always lives in the menu selector, so we don't need it down here as well.

2022-11-16 05:14 UTC, SaxonF commented
Looks good to me @scruffian !

2022-11-16 07:41 UTC, jasmussen commented
I'm not able to test this PR at the moment, but thank you for it, IMO this strikes a better balance of prominence for the feature.

2022-11-16 09:22 UTC, draganescu requested changes
This PR moves the manage menus for the offcanvas editing experiment too. For that, the manage menus should remain in the advanced area as design suggested.

Also, I think, even outside the experiment, moving manage menus to the menu selector needs design feedback, so this is not just a refactoring.

2022-11-16 10:01 UTC, getdave reviewed
My thoughts on this area that moving the Manage Menus into

2022-11-16 10:01 UTC, getdave commented on packages/block-library/src/navigation/edit/navigation-menu-selector.js
> +							</MenuItem>
This UI is effectively representing a standard `<select>` component. I don't know for certain but my instinct is that it's not going to be accessible for what is effectively a standard link to be inside the select.

That said, when it's inside the experiment that's a different matter. In that case the link will be inside a dropdown from the panel's 3 dots menu which I think will be fine.

2022-11-17 09:17 UTC, jasmussen commented
As far as design feedback goes, I personally think the dropdown is a good place for this. It's contextual to the other menus and tools, and it manages prominence. Besides, you can both delete and rename menus on the Manage page (although I could see the Manage page getting a much needed upgrade separately). This is also where the "Manage" link started, if I recall correctly. 

However the above is not a strong opinion. I'm also am aware of the recent conversation around moving it to "Advanced" instead, and what either of those placements (menu or advanced) boil down to, is so that we don't show it here:

<img width="337" alt="Screenshot 2022-11-17 at 10 15 44" src="https://user-images.githubusercontent.com/1204802/202405502-50dc7729-ba79-4d3a-8ebb-c8c1f0ba5225.png">

So long as that's the case, I don't personally think it's urgent to move the link in either direction.

2022-11-17 09:20 UTC, scruffian commented
Thanks for the feedback, lets table this until we have an outcome from the experiment.

2022-11-17 09:20 UTC, closed without merging