Allow post updates on an edited post with no content
WordPress/gutenberg pull request #45917
Opened 2022-11-19 02:35 UTC by KevinBatdorf

## What?
This allows a user to delete the final block and still save the post. Currently you cannot save it and a refresh attempt prompts the user ("Are you sure you want to reload?") and reloading restores content (since it wasn't saved)

## Why?
Personally, I open a new page for testing blocks as I develop. Remove the block, reload, add it again, rinse and repeat. I also think it's intuitive that you should be able to save here regardless of the use case.

More mentioned in this issue:

closes: https://github.com/WordPress/gutenberg/issues/17346

## How?
```js
// Post is not saveable if empty, unless it's "dirty" (has edits).
! ( isEditedPostEmpty( state ) && ! isEditedPostDirty( state ) ) ||
```

## Testing Instructions
Add a new post, add a few blocks (or one), save, remove blocks, press save.

Outside of this PR, you cannot save. In this PR, you can.

## Screenshots or screencast 

https://user-images.githubusercontent.com/1478421/202830276-a83a8416-4fcd-4e21-aa7a-700674c28350.mov

This PR:

https://user-images.githubusercontent.com/1478421/202830318-13a2dc09-0b3a-490e-bbac-ef579c224177.mov

2022-11-19 04:28 UTC, KevinBatdorf commented
I don't think the e2e test fails are related but I could be wrong. I touched a significant part of the code

2025-07-29 15:15 UTC, SirLouen commented
## Test Report
### Description
❌ This report can't validate that the indicated patch works as expected.

Patch tested: REPLACE_WITH_PATCH_URL

### Environment
- WordPress: 6.9-alpha-60093-src
- PHP: 8.2.29
- Server: Apache/2.4.62 (Debian)
- Database: mysqli (Server: 11.8.2-MariaDB-ubu2404 / Client: mysqlnd 8.2.29)
- Browser: Chrome 138.0.0.0
- OS: Windows 10/11
- Theme: Twenty Twenty-Four 1.3
- MU Plugins: None activated
- Plugins:
  * Gutenberg 21.3.0-rc.1
  * Test Reports 1.2.0

### Testing Instructions 
1. Following instructions [here](https://github.com/WordPress/gutenberg/issues/17346#issue-489720625)
2. Add some metadata to the post ID
3. ❌ After removing all the elements for the content and leaving title and excerpt empty an error appers on Save

### Actual Results
- ❌ Issue is not resolved with the patch

### Additional Notes
- The idea of this patch is to permit saving a post with empty title, content, and excerpt because the original premise was being able to save empty posts with metadata. 
- I would also expect checking if there is actually metadata when there is no title, no content, no excerpt and no metadata, what is the point of saving the post instead of deleting it?
- But in this case, the patch is not working because, on save, an error appears. Needs some changes or review my process to see if i'm missing something in my steps.

### Supplemental Artifacts
After deleting all content, an error appears:
![](https://i.imgur.com/p43oAFT.png)

2025-08-01 15:24 UTC, SirLouen requested changes
## Testing Report and Code Review Update

[After the suggestion](https://github.com/WordPress/gutenberg/issues/17346#issuecomment-3144063124)

This patch is working as expected because the `Updating Failed. Content, Title, and Excerpt are empty` is not hindering this process anymore.

It's kind of odd because after this patch with the filter, the result is an empty post without title, excerpt and acontent as expected, and only the `_edit_lock` field meta.

But still, I'm not sure if I like this code proposal. The whole `isEditedPostSaveable` is not serving its purpose. And if the `wp_insert_post_empty_content` is not set, it should not be "Saveable".

2025-08-04 06:49 UTC, KevinBatdorf commented
The PR is pretty stale at this point. Maybe better to just close it. The editor has changed a lot since this was opened. Thanks for reviewing it though

2025-08-04 06:49 UTC, closed without merging