Fix error when pasting image in caption
WordPress/gutenberg pull request #4603
Opened 2018-01-19 14:43 UTC by iseulde

## Description

Caused by #4298. An error occurs if you paste a single image (right click, copy image) inside an editable field that does not support the splitting of content, e.g. an image caption.

## How Has This Been Tested?
See above.

2018-01-28 11:40 UTC, aduth requested changes

2018-01-28 11:40 UTC, aduth commented on blocks/editable/index.js
> +			} else if ( this.props.onSplit ) {
Should this check be consolidated in `splitContent` instead, so in case we add another call to the function we don't need to similarly guard?

2018-01-28 11:40 UTC, aduth commented on blocks/editable/index.js
>  				setTimeout( () => this.splitContent( content ) );
We're not clearing this timeout if the component unmounts.

2018-01-28 11:40 UTC, aduth commented on blocks/editable/index.js
>  				setTimeout( () => this.props.onReplace( content ) );
We're not clearing this timeout if the component unmounts.

2018-01-30 21:08 UTC, iseulde commented
@aduth Fixed the timeouts... What do you think of this solution?

2018-02-01 17:02 UTC, iseulde commented
Rebased after `Editable` rename.

2018-02-07 12:41 UTC, iseulde commented
Blocked by #4839 if we really want to fix the timeouts here too.

2018-02-08 15:46 UTC, iseulde commented
I removed the `setTimout` changes here. It's being worked on by @mcsf in #4839. Since this PR does not touch that further and fixes a small straightforward error, I'm going to merge.

2018-02-08 15:47 UTC, iseulde commented
With the `setTimout` changes I mean 7f76335de09565f0ba2bc7276486dc77eeffd477.

2018-02-08 15:47 UTC, merged