docgen: Add function to handle list of types for theme.json schema
WordPress/gutenberg pull request #46375
Opened 2022-12-07 18:02 UTC by mikachan

## What?

This PR enables docgen to list multiple types for the theme.json style properties listed in theme-json-living.md.

## Why?

Currently, the generated theme.json docs will not list multiple types and instead will print `undefined`. See the [current generated entry](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/theme-json-reference/theme-json-living.md#border-1) for the `radius` style property.

## How?

Adds a new function called `formatType`, which takes the style property object and checks if the `type` key exists. If it does, it will default to that (the same as the current behavior). If it doesn't exist, it checks for the `anyOf` or `oneOf` properties and makes a comma-separated list of those types.

## Testing Instructions

Run `node ./bin/api-docs/gen-theme-reference.js`, and the generated type for the `radius` property should be "string, object" instead of "undefined".

### Testing Instructions for Keyboard

## Screenshots or screencast

2022-12-19 18:30 UTC, vcanales requested changes

2022-12-19 18:30 UTC, vcanales commented on bin/api-docs/gen-theme-reference.js
> +	}
`formatType` is currently adding a trailing comma when extracting types from reference properties as they don't include a `type` property.

```js
[ { type: 'string' }, { '$ref': '#/definitions/refComplete' } ]
/*
  ### filter

CSS and SVG filter styles.

| Property | Type    | Props |
| -------- | ------- | ----- |
| duotone  | string, |       |
*/
```

Filtering out entries that don't include `type` fixes this.

```suggestion
	if ( prop.hasOwnProperty( 'anyOf' ) || prop.hasOwnProperty( 'oneOf' ) ) {
		const types = prop.anyOf || prop.oneOf;
		type = types
			.filter( ( item ) => !! item.type )
			.map( ( item ) => item.type )
			.join( ', ' );
	}
```

We might want to add a way to describe the `$ref` property, but that's probably better left for later.

2022-12-20 00:46 UTC, mikachan commented on bin/api-docs/gen-theme-reference.js
> +	}
Ah yeah good spot, I guess I was thinking of tackling this when the $ref type had been added. 

$ref will always be an object, so maybe if $ref exists, we could just list 'object'? I've pushed a change that does this to see what you think 🙏

2022-12-20 03:47 UTC, vcanales commented on bin/api-docs/gen-theme-reference.js
> +	}
If there's no specific type for `$ref`, it should be fine to use `object`

2022-12-20 03:50 UTC, vcanales approved these changes
LGTM

2022-12-20 12:02 UTC, merged