[Block Editor]: Lock __experimentalBlockInspectorAnimation setting
WordPress/gutenberg pull request #47740
Opened 2023-02-03 14:25 UTC by ntsekouras

## What?
Part of: https://github.com/WordPress/gutenberg/issues/47196

Locks `__experimentalBlockInspectorAnimation`(introduced [here](https://github.com/WordPress/gutenberg/pull/46342)) and renames it to `blockInspectorAnimation`.

## Testing Instructions
1. The navigation blocks that were using this setting should work as before. No regressions should be introduced.
2. The setting is locked and cannot be updated by third party

2023-02-03 15:02 UTC, artemiomorales commented
Thanks for putting this together.

I’ll defer to @scruffian and @getdave on whether removing the setting for the navigation, navigation link, and navigation submenu is the right move, but this looks good to me.

2023-02-03 15:09 UTC, ntsekouras commented
>I’ll defer to @scruffian and @getdave on whether removing the setting for the navigation, navigation link, and navigation submenu is the right move, but this looks good to me.

I'm not removing them. This PR lock's the editor setting with the previous blocks as [default values for the setting](https://github.com/WordPress/gutenberg/pull/47740/files#diff-99aa3952a26a79284b09ca895d619677db76c3dccf82983891db7902756f8ca5R174).

2023-02-03 15:52 UTC, scruffian approved these changes
LGTM

2023-02-03 16:55 UTC, draganescu requested changes, later dismissed
This is cool but it should work for all navigation allowed inner blocks (page list, social icons, site logo etc)

2023-02-03 17:00 UTC, ntsekouras commented
>This is cool but it should work for all navigation allowed inner blocks (page list, social icons, site logo etc)

Does this work in trunk right now?

2023-02-06 09:38 UTC, adamziel approved these changes
@ntsekouras privacy-wise it looks good to me. I'll defer to @draganescu on the nav block functionality.

2023-02-06 10:04 UTC, merged

2023-02-07 12:32 UTC, ntsekouras commented
Cherry-picked this PR to the wp/6.2 branch.