Navigation: Don't save the level of the link in an attribute
WordPress/gutenberg pull request #48219
Opened 2023-02-17 22:18 UTC by scruffian

## What?
WIP

The useEffect that saves the `isTopLevelLink` and `isTopLevelItem` to an attribute causes ripples through the other useEffects in the navigation block, which means that we get unexpected bugs like this one:
https://github.com/WordPress/gutenberg/issues/47829

I don't think we need this useEffect at all - we don't even need to know if this is a top level link - we can just output the colors on the navigation submenu wrapper. 

## Why?
I think this is a simpler approach and avoids the needs for a useEffect and extra attributes. 

## Testing Instructions
- Set a submenu color on the navigation block
- Check that the color setting is applied only to the submenu, and not the top level links.

### Testing Instructions for Keyboard

## Screenshots or screencast

2023-03-02 12:30 UTC, scruffian commented on packages/block-library/src/navigation-link/index.php
> -function block_core_navigation_link_build_css_colors( $context, $attributes ) {
I'm not sure why this was duplicated. I'd rather use the same function in both places. If we need to keep two copies of it, I'm not sure what we should do with this one - it never uses the $is_sub_menu branch, so we could just remove all that, but then it diverges from `block_core_navigation_submenu_build_css_colors`.

2023-03-02 12:32 UTC, scruffian commented on packages/block-library/src/navigation-link/index.php
> +	$colors          = block_core_navigation_submenu_build_css_colors( $block->context, $attributes );
Is it possible that this function won't be defined? I suppose it is possible for someone to deregister the navigation submenu block, but not the navigation-link block, though I can't think why you would do that. We could move the function to the parent block...

2023-03-02 12:47 UTC, getdave commented on packages/block-library/src/navigation-submenu/index.php
> +				'style' => $style_attribute,
Let's make sure we're escaping this output if it's coming direct from uses

2023-03-02 16:16 UTC, scruffian commented on packages/block-library/src/navigation-submenu/index.php
> +				'style' => $style_attribute,
It is escaped here: https://github.com/WordPress/wordpress-develop/blob/0cb8475c0d07d23893b1d73d755eda5f12024585/src/wp-includes/class-wp-block-supports.php#L216

2023-03-02 16:29 UTC, scruffian commented on packages/block-library/src/navigation-submenu/index.php
> +				'style' => $style_attribute,
I added an extra esc_attr just to be sure!

2023-03-02 17:15 UTC, getdave commented on packages/block-library/src/navigation-submenu/index.php
> +				'style' => $style_attribute,
Oh sorry. I missed `get_block_wrapper_attributes`. It doesn't need escaping again. My bad !

2023-03-03 09:29 UTC, getdave reviewed
I tested this and it worked in the editor but not on the front of the site. I was using TT3.

#### Editor
<img width="954" alt="Screen Shot 2023-03-03 at 09 28 27" src="https://user-images.githubusercontent.com/444434/222683818-05acf8c7-7f16-4e05-8518-67eb9c1c54a5.png">

#### Front of Site
<img width="1115" alt="Screen Shot 2023-03-03 at 09 28 40" src="https://user-images.githubusercontent.com/444434/222683810-21f6a8a7-346b-4795-b96d-dc1d822c35e7.png">

2023-03-03 09:46 UTC, getdave reviewed
I tested this and the colors were applied as expected.

#### Front of Site

<img width="1194" alt="Screenshot 2023-03-03 at 09 45 47" src="https://user-images.githubusercontent.com/444434/222687644-69c2b22a-6fd2-4d94-83b9-3a6fba7275cb.png">


#### Editor
<img width="877" alt="Screenshot 2023-03-03 at 09 46 10" src="https://user-images.githubusercontent.com/444434/222687646-01c9515d-152c-4c84-a437-de207ae3beb5.png">

2023-03-03 09:51 UTC, scruffian commented on packages/block-library/src/navigation-submenu/index.php
> +		$colors      = block_core_navigation_submenu_build_css_colors( $block->context, $attributes, $has_submenu );
👍

2023-03-03 09:59 UTC, getdave approved these changes
I tested this and couldn't find any regressions. I would prefer if we had a few more manual tests confirming the same. 

I'm going to cautiously approve though as I think this fix is critical for fixing numerous bugs.

2023-03-03 10:01 UTC, getdave commented
@ntsekouras @Mamaduka I've added the backport label to this PR as I believe we need it to fix several bugs. I would prefer if more people could test it before it gets merged.

2023-03-03 10:11 UTC, MaggieCabrera approved these changes
This is working as expected!

2023-03-03 10:51 UTC, draganescu requested changes
There is a bug when moving a submenu item to top level, it gets rendered with submenu item colors - not happening on `trunk` for me:


https://user-images.githubusercontent.com/107534/222701971-20375385-0ce9-4535-b1d9-2205af9b8291.mp4

2023-03-03 11:16 UTC, scruffian commented
I have fixed that bug in [623d6f5](https://github.com/WordPress/gutenberg/pull/48219/commits/623d6f5cf61730ab043fc419bfe42b0d32347f4f)

2023-03-03 12:22 UTC, draganescu approved these changes
I think this is a good change and in my testing it works as described.

2023-03-03 13:16 UTC, merged

2023-03-03 15:41 UTC, getdave commented
🍾 🍾 🍾 🍾 🍾 🍾

2023-03-07 07:10 UTC, ntsekouras commented
I just cherry-picked this PR to the wp/6.2 branch to get it included in the next release: e749760c01