Allow private pages to display in Nav block on front of site
WordPress/gutenberg pull request #49223
Opened 2023-03-21 10:32 UTC by getdave

## What?

Allows private Posts to display in the Nav block _if_ they are part of a menu.

Closes https://github.com/WordPress/gutenberg/issues/33215

## Why?

In the Classic Menus system it was not possible to add Private posts to a menu from the Menus screen. However, if the Post was added to a Menu and _then_ subsequently made `Private` it would render on the front of the site and remain in the Menu on the Menus screen.

The Nav Link/Submenu blocks were not mirroring this behaviour. This PR fixes things to display the same behaviour as for Classic Menus.

## How?

There were two tasks that needed to be addressed.

> 1. Check that private posts cannot be found in the Link creation UI.

I checked by:

- ✅ making a Private Post and then trying to find that post using the Link UI search. I could not find it. 
- ✅ verified that [the Post Search endpoint is set to `publish` status only](https://github.com/WordPress/wordpress-develop/blob/7cef755d2761deb7bc7b53d047a27c42d16cd43b/src/wp-includes/rest-api/search/class-wp-rest-post-search-handler.php#L62).

> 2. Add private to the list of allowed post types on the front of the site.

This PR implements this part by adding `private` to the list of post statuses that are allowed.

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast

2023-03-21 10:36 UTC, getdave commented
cc @Chrico who raised [the original Issue](https://github.com/WordPress/gutenberg/issues/33215).

2023-03-21 12:49 UTC, scruffian approved these changes
The code looks good and does what it says.

My concern is that this could potentially change the front end of sites which already have a link to a private post/page in them. Do you think that's something to be careful about?

2023-03-21 13:05 UTC, getdave commented
> Do you think that's something to be careful about?

100%. If this lands then we need to communicate the change. Do you have any ideas about _how_ we could do that?

2023-03-21 15:09 UTC, jeryj commented
> My concern is that this could potentially change the front end of sites which already have a link to a private post/page in them. Do you think that's something to be careful about?

To make sure I follow, is this the scenario that would be changed?
- Someone adds a public page to the navigation block menu (private ones are not allowed)
- They save the page/nav
- They set one of the pages from the nav to private
- Before this PR, the private page would not show on the frontend of their site, but now it will?

2023-03-21 15:15 UTC, getdave commented on phpunit/blocks/render-block-navigation-link-test.php
>  	}
This can be removed as the test class is inherting from the base WP test class which does this clean up.

See: 

- https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/#shared-fixtures
- https://core.trac.wordpress.org/browser/trunk/tests/phpunit/includes/abstract-testcase.php#L91
- https://github.com/WordPress/wordpress-develop/blob/95826a28f17bda68092926bb6c33a05cc9459964/tests/phpunit/includes/functions.php#L110

2023-03-21 15:16 UTC, getdave commented
> * Before this PR, the private page would not show on the frontend of their site, but now it will?

Correct. It's consistent with Classic Menus system but it's not how Block menus have behaved until this PR.

2023-03-22 09:06 UTC, aristath commented
I'm not sure if the old behavior (classic themes) was a feature, or a bug. It sounds to me like what classic themes were doing, was just wrong, and the block fixed the issue.
I'm a bit skeptical about allowing private posts to show in navigation - regardless of whether their status was changed after the menu item was added.

2023-03-22 09:12 UTC, scruffian requested changes
> I'm not sure if the old behavior (classic themes) was a feature, or a bug. It sounds to me like what classic themes were doing, was just wrong, and the block fixed the issue.

I was thinking more about this and I agree with this. In the same way that we'd like page slugs to update when the page updates, I think this is actually a feature not a bug. IMO we should close this.

2023-03-22 09:31 UTC, getdave commented
I'm happy to close it. It did seem strange even though that's how @talldan said Classic Menus behave.

I'll close this out and at least we have a paper trail to follow if it's ever raised in future.

2023-03-22 10:00 UTC, talldan commented
> It did seem strange even though that's how @talldan said Classic Menus behave.

I double checked and it is how they work. 🤷 

I didn't and still don't think it's how the nav block should work.

2023-03-22 10:48 UTC, draganescu commented
There still is the need to provide to the use case where you have content which is accessible only to logged in users but logged out users should still see the link. This thing of "private pages should not appear in nav" is similar to Google not linking to Gmail just because you're logged out. Which of course is not true. Links are there pointing to things so users know things exist.

2023-03-22 11:02 UTC, Chrico commented
Why not just adding a filter and let the developer decide which "post_status" should be allowed to see in "Navigation"-Block?

2023-03-22 11:08 UTC, aristath commented
Does it not work if the user adds the menu items as custom links instead of selecting the post from a dropdown? 🤔 I think that method _should_ work and cover the scenario described above...

2023-03-22 12:42 UTC, draganescu commented
@Chrico I think the filter is "yet another filter", seems like too powerful a solution for such a corner case. From the issue the problem is a disconnect between the editor and the front end of the site. 

I don't think the logic to not render a link that appears in the navigation block in the editor because it is private makes sense. Particularly when, as the issue describes, the page is made private after it was added to the editor. I have doubts about draft pages as well, but private pages/posts are even worse.

In https://github.com/WordPress/gutenberg/pull/27207 I did mention that draft page/post links should show some kind of "indicator that the link will not be visible on the front end". If that indicator were to exist I think things would become clearer, but I would still have doubts, but at least we could explain what is going on.

For now though, as a user, having a link in my navigation not render because I made the page or post private is unexpected and impossible to figure out. I don't agree much with the idea to use "custom links", because, as a user, not finding things is super frustrating. For instance, I have a page which I linked to in my footer. In the mean time I made the page private and want to link to it in the header. I _do the exact same actions_ and the page is not found - because I made it private, but how can I know that? I can't. Also a user that wants to link to their private page will never ever discover that they need to open the inserter and choose custom link.

It's one thing to be smart like having dynamic links which update when the slugs change, and it's another to not render things based on strict heuristics, which we may not be even right about. On another note, I also don't think it's good to encourage "leftover content" in the editor, whicih is there, is visible but does not render. Users should assume that what they see in the editor renders. Hidden content, should exist via special blocks (like annotations or editorial todos etc).

2023-03-22 12:57 UTC, Chrico commented
> I think the filter is "yet another filter", seems like too powerful a solution for such a corner case. From the issue the problem is a disconnect between the editor and the front end of the site.

I just proposed a filter to find a middle ground between "we don't want to change", but still allow developers to change it on their own. Overall the restriction to "only post_status === `publish`" is incorrect here. Why? Because when inserting a new Navigation Item and adding a new Navigation Item you can search via LinkControl on `/wp-json/wp/v2/search?search={YOUR TERM}&per_page=20&type=post&_locale=user` which uses internally the `WP_REST_Post_Search_Handler`. This Handler has a filter called `rest_post_search_query` [1] which allows to add aside from the default `"post_type" => "publish"`[2]  every post_type you want.

So stripping off [3], what before can be allowed is quiet frustating for the User who manages the navigaton menue.


[1] https://github.com/WordPress/WordPress/blob/93a4991c018a562e9cb8298d997be21ffa85e9d1/wp-includes/rest-api/search/class-wp-rest-post-search-handler.php#L90

[2] https://github.com/WordPress/WordPress/blob/93a4991c018a562e9cb8298d997be21ffa85e9d1/wp-includes/rest-api/search/class-wp-rest-post-search-handler.php#L62

[3] https://github.com/WordPress/gutenberg/blob/v15.3.1/packages/block-library/src/navigation-link/index.php#L167

2023-03-27 03:40 UTC, talldan commented
> In https://github.com/WordPress/gutenberg/pull/27207 I did mention that draft page/post links should show some kind of "indicator that the link will not be visible on the front end". If that indicator were to exist I think things would become clearer, but I would still have doubts, but at least we could explain what is going on.

That's a good point. There is an indicator for draft posts:
![Screen Shot 2023-03-27 at 9 50 03 am](https://user-images.githubusercontent.com/677833/227822012-87a49fe4-32b0-41d4-8a37-cd9e00b22904.png)

Something similar should at least exist for private pages when they're hidden.

2025-10-21 13:35 UTC, getdave commented
## Filter Now Available

This PR is no longer needed as a filter has been added to handle this exact use case.

**Filter Added:**   
**Added in:** [PR #63181](https://github.com/WordPress/gutenberg/pull/63181) (merged July 5, 2024)  
**Available since:** WordPress 6.8.0

## How to Use the Filter

To allow private posts to display in Navigation blocks, developers can now use:

```php
add_filter(
    'render_block_core_navigation_link_allowed_post_status',
    function( array $post_status ): array {
        $post_status[] = 'private';
        return $post_status;
    }
);
```

This filter provides the same functionality that this PR was trying to implement, but in a more flexible way that allows developers to control which post statuses are allowed on a per-site basis.

The original issue (#33215) is now resolved through this filter approach rather than hardcoding the behavior.

2025-10-21 13:36 UTC, closed without merging