Duotone: Update to use selectors API
WordPress/gutenberg pull request #49325
Opened 2023-03-24 05:56 UTC by aaronrobertshaw

## What?

- Updates Duotone support to leverage the selectors API introduced in https://github.com/WordPress/gutenberg/pull/46496.
- Fixes display of duotone global styles on the frontend

## Why?

- Fixes regression

## How?
- Updates `WP_Duotone_Gutenberg` to leverage the new global function for retrieving feature selectors
- Updates Duotone block support JS hook to prefer selectors API if available
- Moves the Image block's duotone selector to the selectors API as that block now uses the API.

## Testing Instructions
1. Apply a global duotone filter for the Image block
2. Create a post with an Imag block and save it
3. View the frontend and see that the image is missing the global duotone filter
4. Checkout this PR and reload the frontend
5. The duotone filter should now be applied.

Note: The lack of the global duotone filter in the post editor is a known issue that is being worked on, see https://github.com/WordPress/gutenberg/pull/49239.

## Screenshots or screencast 

| Before | After |
|---|---|
| <img width="1302" alt="Screenshot 2023-03-24 at 3 54 13 pm" src="https://user-images.githubusercontent.com/60436221/227436422-9b23fc5d-1df5-4a71-a529-cd58c39053f9.png"> | <img width="1266" alt="Screenshot 2023-03-24 at 3 52 45 pm" src="https://user-images.githubusercontent.com/60436221/227436454-13df03ed-8ada-4a3c-b7da-a0d7a8f62c32.png"> |

2023-03-24 14:48 UTC, scruffian approved these changes
LGTM

2023-03-24 14:58 UTC, scruffian requested changes
Actually this breaks the Site Editor:

<img width="1191" alt="Screenshot 2023-03-24 at 14 58 10" src="https://user-images.githubusercontent.com/275961/227561417-835fa129-a440-4e8c-8a42-546de80b8ad3.png">

2023-03-24 15:25 UTC, jeryj commented
The site editor breaks from [`duotoneSelector` getting set to `true` in `use-global-styles-output.js`](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/global-styles/use-global-styles-output.js#L917-L918):

```
const duotoneSelector = blockType?.supports?.color?.__experimentalDuotone ?? null;
```

 rather than a selector string, like `.wp-block-post-author__avatar img` as it does on `trunk`. Not sure on the fix.

2023-03-27 04:26 UTC, aaronrobertshaw commented
Thanks for digging into the issue @jeryj 👍 

> Not sure on the fix.

I have a fix working locally for this. The issue though highlights that I need to update the `useGlobalStylesOutput` hook in general to support the selectors API. I'm currently working on this today and hope to have something up for review late today or early tomorrow.

2023-03-28 07:25 UTC, aaronrobertshaw commented
Closing as these changes were absorbed into a single PR cleaning up the Selectors API (https://github.com/WordPress/gutenberg/pull/49393).

2023-03-28 07:25 UTC, closed without merging