Adjusted heading ratio to Perfect Fifth (1.5) (Issue #4965)
WordPress/gutenberg pull request #5011
Opened 2018-02-12 20:37 UTC by twsp

## Description
Changed ratio of em for h1 through h6 to follow a Perfect Fifth (1.5) ratio.  This was recommended as a design change in issue #4965.

## How Has This Been Tested?
This has been tested by using a local WordPress environment to create and view all header sizes.

## Screenshots (jpeg or gifs if applicable):
![2018-02-12 15_31_20-sample title _ add new post testsite wordpress](https://user-images.githubusercontent.com/12479754/36118266-68f06164-100a-11e8-8c8e-9a19beb1ae2e.png)

## Types of changes
This is a non-breaking design change that only affects the size of headers in the Gutenberg editor.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style.
- [X] My code has proper inline documentation.

2018-02-13 07:27 UTC, ntwb reviewed
...

2018-02-13 07:28 UTC, ntwb requested changes
@twsp It looks like some formatting issues have crept in, could you update the PR please to use tabs for indentation and not spaces and keep the existing blanks lines please 😄

2018-02-13 23:21 UTC, ntwb requested changes
See above comment

2018-02-21 05:22 UTC, ntwb approved these changes

2018-02-21 05:22 UTC, ntwb requested changes

2018-02-21 05:22 UTC, ntwb commented on blocks/library/heading/editor.scss
> +	}
The extra spaces above also need to be removed please

2018-03-14 08:43 UTC, jasmussen commented
Thank you for creating a pull request! However the typographic scale hasn't yet been decided upon in https://github.com/WordPress/gutenberg/issues/4965, and "Perfect Fifth" feels way too big for Gutenberg. Additionally when we are ready to implement, we need to also consider a separate set of sizes for mobile, as well as include the page title as a H1. Apologize for being so late to review this, and I'd love to help you with this.

2018-05-10 19:46 UTC, karmatosed commented
For now, lets close this as we're still undecided on direction. I do in saying this want to be clear we can always reopen any pull request or issue. Once we decide we can then have a PR for #4965

2018-05-10 19:46 UTC, closed without merging