wp-env: Fix redirect loop for instances on port 80 (and 443)
WordPress/gutenberg pull request #50282
Opened 2023-05-03 09:39 UTC by Luehrsen

## What?

This Pull Request introduces an exception within the `addOrReplacePort` function, ensuring that if the specified port is either 80 or 443, the input remains unaltered.

## Why?

The modifications introduced in #49883 mandate the inclusion of port numbers in the constants `WP_TESTS_DOMAIN`, `WP_SITEURL`, and `WP_HOME`. Unfortunately, there doesn't appear to be a configuration option to bypass the addition of these ports.

As a result, this negatively impacts all `wp-env` instances operating on ports 80 or 443. Modern browsers automatically remove these default ports, which leads to a redirection loop in the frontend, rendering the site inaccessible to users

2023-05-03 16:53 UTC, ObliviousHarmony requested changes
Thanks for catching this and working on it!

I don't think the function signature has the correct type for port anymore. We are assuming that it's a string, but as per the validation done when parsing configuration files, it should always be number.

Could we:

- Update the `addOrReplacePort` JSDoc for `port` to be `{number}`.
- Update tests to pass a number instead of a string.

2023-05-03 22:10 UTC, ObliviousHarmony commented
When I reviewed this @Luehrsen I noticed a small thing about port validation. I fixed that in another PR, but while I was there, couldn't help but bundle in this change 😅 You can take a look at https://github.com/WordPress/gutenberg/pull/50300, but, I took this and made the small change I suggested!

2023-05-04 08:20 UTC, Luehrsen commented
@ObliviousHarmony Yeah, I think we can close this and work on #50300. 

Just make sure to credit appropriately and mention #49883 for better visibility! :)

2023-05-04 15:31 UTC, ObliviousHarmony commented
Alright @Luehrsen,

I've gone ahead and updated that PR's description to better reflect the primary fix it contains.

Thanks!

2023-05-04 16:37 UTC, noahtallen commented
Closing now that #50300 has landed!

2023-05-04 16:37 UTC, closed without merging