Block card: Add `min-height` to prevent layout shift.
WordPress/gutenberg pull request #50585
Opened 2023-05-12 12:49 UTC by juanfra

## What?

Adding `min-height` to the block card. Setting the value to `102px`, as the two-line descriptions computed height is slightly more than 100 (and probably my OCD is aligned with even numbers).

Fixes: https://github.com/WordPress/gutenberg/issues/49734

## Why?

To prevent a layout shift when selecting different blocks, in favor of a more consistent user experience.

## Testing Instructions
1. Create a page.
2. Add two blocks having different length for their descriptions (i.e.: Tag cloud and Archives).
3. Confirm that the block card for both has the same height.

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/252415/be7e87e3-39cb-467f-a1c4-4eb436fd108f

2023-05-12 15:56 UTC, priethor approved these changes
Works well for me, but I'd like a second opinion from @jasmussen or @richtabor

2023-05-12 19:00 UTC, richtabor commented on packages/block-editor/src/components/block-card/style.scss
> +	min-height: 102px;
Let's just use `100` here.

2023-05-12 19:05 UTC, richtabor commented
For blocks with multi-line descriptions (no change): 

| Before  | After |
| ------------- | ------------- |
|<img width="280" alt="CleanShot 2023-05-12 at 15 03 04" src="https://github.com/WordPress/gutenberg/assets/1813435/3f2736f5-fe98-46d7-af22-d35b02bea7b2">|<img width="280" alt="CleanShot 2023-05-12 at 15 02 44" src="https://github.com/WordPress/gutenberg/assets/1813435/5546f1a9-e5f8-4583-bedb-6508fa8751ba">|

For blocks with one-line descriptions: 

| Before  | After |
| ------------- | ------------- |
|<img width="280" alt="CleanShot 2023-05-12 at 15 01 49" src="https://github.com/WordPress/gutenberg/assets/1813435/acd49a31-0714-453d-8861-798630f6f936">|<img width="279" alt="CleanShot 2023-05-12 at 15 01 14" src="https://github.com/WordPress/gutenberg/assets/1813435/e9243cec-f261-4906-8885-2f1cb59fcb6f">|


It does make the Settings and Styles icons stay in the same position when a block does have a short description: 

https://github.com/WordPress/gutenberg/assets/1813435/129e4682-f5d6-4ad1-8133-5c894ce83ae6

2023-05-12 19:06 UTC, richtabor requested changes
Let's change it to `100px` as the min-height. I'd appreciate another look from @WordPress/gutenberg-design as well.

2023-05-15 08:38 UTC, jasmussen commented
I appreciate the layout shift prevention, especially for when the inspector is tabbed. Still, looking at just this one alone, it does feel like an uneven bit of space:

<img width="290" alt="Screenshot 2023-05-15 at 10 31 39" src="https://github.com/WordPress/gutenberg/assets/1204802/89729be3-bc3f-4d9b-80c7-242e12a8e13e">

It's okay though. A somewhat bigger issue is the space that group blocks now have:

<img width="354" alt="Screenshot 2023-05-15 at 10 31 05" src="https://github.com/WordPress/gutenberg/assets/1204802/af4b6028-bca1-4361-b062-c274093768eb">

<img width="324" alt="Screenshot 2023-05-15 at 10 31 16" src="https://github.com/WordPress/gutenberg/assets/1204802/d333afff-603a-42df-b30f-58f7fd4db7e9">

Since those 3 transform buttons in the inspector cause a layout shift regardless, I wonder if this might need a different approach after all. Considering also that the layout shift is only ever going to be a problem when you have the tabbed inspector, we could take an editorial approach to this. Notably the Featured Image block's description feels almost tautological, and could probably be expanded a bit. If we did a review of blocks, with a goal to have most of them feature 2 line descriptions, it might get us to the following place:

* Only review blocks with the split inspector
* Keep the group blocks as they are, as they feature the inspector transform shortcuts
* Get most other blocks to a place where they have 2 lines of descriptions
* Anything more than 2 lines deserves verbose text anyway, like Site Logo

What do you think?

2023-05-15 13:16 UTC, juanfra commented
My main concern with the editorial approach is that it'll be impossible to maintain it with i18n. The two-line sentences will likely be one or three (or more) in different languages.

Targeting only blocks with the split inspector could be a good solution. If we want to avoid the randomness of the descriptions ultimately, I think there are other options to consider (probably deserves a new issue, but just sharing):

- Hide the block description by default and add a preference with the possibility of showing the description. The description is already shown in the block inserter.
- Make the description part "toggable", or have an info icon that shows the content via a tooltip.
- Move the description, into a "Help" or "Information" section within the sidebar. That can also be a place to store tips, links, etc. Eventually, the most probable case is that if someone doesn't understand the purpose of the block they will go to a "Help" or "Information" section. Something like this:

<img width="465" alt="Screenshot 2023-05-15 at 15 08 56" src="https://github.com/WordPress/gutenberg/assets/252415/3b4d2a9e-fdc7-47d2-b9c3-3b43555e7e1f">

2025-06-05 13:04 UTC, juanfra commented
Closing this as it’s been inactive for a while.

2025-06-05 13:04 UTC, closed without merging