Add fall-through conditional for editor syncing of Navigation post types
WordPress/gutenberg pull request #50867
Opened 2023-05-23 09:17 UTC by getdave

## What?

Avoids unwanted network request to ?find_template triggered by syncing editor with state.

## Why?

We want to avoid unnecessary network calls.

## How?

Add a conditional to the code that inits an entity in the editor from the URL. As we're not _yet_ ready to handle Navigation entities but we're showing them in browse mode we need to catch this condition and allow it to do nothing.

In the future we will utilise this to implement focus mode for Navigation.

## Testing Instructions

- Have at least one menu.
- Open Site Editor
- Open Browse Mode
- Click Navigation
- Browse to a single Navigation
- See no network request

### Testing Instructions for Keyboard

## Screenshots or screencast

2023-05-23 16:13 UTC, scruffian commented
This breaks some parts of the experience for me - if I load a navigation directly (via `wp-admin/site-editor.php?postId=2874&postType=wp_navigation`) then the preview is blank.

2023-05-26 08:18 UTC, getdave commented
Ah we'll need to wait until https://github.com/WordPress/gutenberg/pull/39286 is merged. That's cos in lieu of that it's trying to find a specific template for the route. @scruffian can you add a blocking review pls 🙏

2023-05-26 08:26 UTC, MaggieCabrera requested changes
Let's wait for this until https://github.com/WordPress/gutenberg/pull/39286 merges

2023-06-21 11:51 UTC, scruffian commented
I think we can close this.

2023-06-21 11:51 UTC, closed without merging

2023-06-21 12:07 UTC, getdave commented
Yes this not needed.