Add Block-editor-keyboard-shortcut test case
WordPress/gutenberg pull request #50930
Opened 2023-05-24 18:54 UTC by alvitazwar

## What?
Based on https://github.com/WordPress/gutenberg/pull/38570, part of https://github.com/WordPress/gutenberg/issues/38851. Migrate [block-editor-keyboard-shortcuts.test.js](https://github.com/WordPress/gutenberg/blob/trunk/packages/e2e-tests/specs/editor/various/block-editor-keyboard-shortcuts.test.js)

## Why?
See https://github.com/WordPress/gutenberg/pull/38570 for its background and rationale.

This is split into a new PR for easier review.

## How?
See https://github.com/WordPress/gutenberg/pull/38570 for the proposed migration steps.

## Testing Instructions
npm run test:e2e:playwright /test/e2e/specs/editor/various/block-editor-keyboard-shortcuts.spec.js
## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/55917380/381ed206-721a-4be7-b8b1-9015b9bda964

2023-05-25 04:45 UTC, kevin940726 commented
Hey there! I wanted to express my gratitude for the PR you submitted. By the way, have you had a chance to check out the latest best practices guide? It's packed with some really helpful tips and tricks that can make a big difference in how we write reliable and readable e2e tests. One key suggestion is to make good use of the `getByRole` method when selecting elements, and consider using `editor.getBlocks` instead of snapshot testing. It can really streamline our workflow. Thanks again for your contribution!

2023-05-25 20:06 UTC, alvitazwar commented
@kevin940726  Can you please recheck that for me?

2023-06-08 08:41 UTC, kevin940726 commented
Hi @alvitazwar! I've been busy with something else recently, but this is still on my backlog! I'll get back to it as soon as possible 🙇 .

2023-06-13 08:42 UTC, Mamaduka requested changes
The PR removes the `specs/editor/various/autosave.test.js` file instead of the `block-editor-keyboard-shortcuts.test.js`.

**Additional notes:**
* I'm not sure if `await expect.poll( editor.getEditedPostContent ).toBe( MatchObject );` assertions check anything related to keyboard navigation.
* Let's combine two `test.describe` into one. The grouping usually makes it harder to know where the new tests go. I think it's better to split tests into multiple files if there's a need for a separate test group.

2023-06-13 08:42 UTC, Mamaduka commented on test/e2e/specs/editor/various/block-editor-keyboard-shortcuts.spec.js
> +		page.locator( '[aria-label="Multiple selected blocks"]' );
Call the just the locator doesn't do anything. This should be converted into a proper assertion.

2024-01-03 08:28 UTC, closed without merging