Hide "View" when previewing a theme
WordPress/gutenberg pull request #50986
Opened 2023-05-26 05:17 UTC by okmttdhr

## What?

https://github.com/WordPress/gutenberg/issues/50919
## Why?

## How?

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast

2023-05-30 19:17 UTC, jeryj requested changes

2023-05-30 19:17 UTC, jeryj commented on packages/edit-site/src/components/header-edit-mode/index.js
> +								>
These preview options work on within the editor, so I think we should leave them as they are useful here.

2023-05-30 19:17 UTC, jeryj commented on packages/edit-site/src/components/header-edit-mode/index.js
> +											href={ homeUrl }
I think adding the `isPreviewingTheme()` check here and appending the `?theme_preview` URL query would work well to resolve https://github.com/WordPress/gutenberg/issues/50712. I think https://github.com/WordPress/gutenberg/issues/50713 can be addressed later as a separate PR. The View and Previewing the site links are legitimately useful as is, even if the preview link isn't (yet) appended to all links on the site when previewing.

2023-05-31 16:41 UTC, draganescu commented
I think the first comment by @jeryj is accurate, the mobile and tablet options work well no reason to hide those as well. I think though that hiding the menu group that opens a new tab is good untill we figure out a way to persist theme_preview while browsing the live website.

2023-06-06 11:46 UTC, scruffian commented
> untill we figure out a way to persist theme_preview while browsing the live website

I don't see how this could ever be possible

2023-06-06 15:11 UTC, jeryj commented
Can we check:
- If we're in a theme preview (`GET='theme_preview'`) and if we're on the frontend of the site? Then append the GET param to all links that match the site url with JS after everything has loaded?

Another way would be to add a filter for all content and block content if the theme preview param is there. Then append the GET param to all links that match the site url?

2023-06-12 14:03 UTC, scruffian commented
> I don't see how this could ever be possible

I found a way here: https://github.com/WordPress/gutenberg/pull/51412

2023-06-13 01:18 UTC, okmttdhr commented
I'm closing this PR since https://github.com/WordPress/gutenberg/pull/51412 would come as a solution soon. Thank you for all your reviews.

2023-06-13 01:18 UTC, closed without merging