Add duotone class to nested figure elements
WordPress/gutenberg pull request #51064
Opened 2023-05-29 18:09 UTC by artemiomorales

## What?

Addresses #50973 

Fixes a bug wherein duotone filters were not being applied to images with the lightbox behavior enabled

## Why?

Basic functionality should work for image when the lightbox is activated

## How?

Rather than putting the duotone class on the parent tag of the block in question, it loops through the elements and adds the class to the `<figure>` elements.

Note: This uses @SantosGuillamot's suggested code from the [following comment](https://github.com/WordPress/gutenberg/issues/50973#issuecomment-1567280396) on the related issue.

## Testing Instructions

1. Enable Gutenberg > Experiments > Core Blocks in the admin
2. Add an image to a post
3. Enable the lightbox by enabling Advanced > Behaviors > Lightbox in the block settings
4. Add a duotone via Styles > Filters > Duotone in the block settings
5. Publish and view the post to see the duotone has been applied to the image
6. Click on the image to open the lightbox and ensure the duotone has been applied there as well

### Testing Instructions for Keyboard

N/A

## Screenshots or screencast

2023-05-30 06:26 UTC, artemiomorales commented
I'm not sure if this change would break duotone in any way.
It looks good to me, but would only add duotone when a `<figure>` element with the `.wp-block-image` class is present in the block.

2023-05-30 07:02 UTC, SantosGuillamot commented
> I'm not sure if this change would break duotone in any way.

It'd be great to ask someone involved in the duotone to check if it could cause issues somehow. Maybe @ajlende could help here (sorry for the ping if that's not the case)?

2023-05-30 08:08 UTC, gziolo commented
> > I'm not sure if this change would break duotone in any way.
> 
> It'd be great to ask someone involved in the duotone to check if it could cause issues somehow. Maybe @ajlende could help here (sorry for the ping if that's not the case)?

It's definitely Alex who can give the best answer. I personally don't think you can narrow down the lookup to the Image block because block supports for duotone is not not only used with several other core blocks, but it also can be enabled by third-party blocks.

<img width="466" alt="Screenshot 2023-05-30 at 10 06 09" src="https://github.com/WordPress/gutenberg/assets/699132/e36f1eaf-e135-4a7b-b144-6d3bf9cac51e">

Maybe all you need is to change this selector instead:

https://github.com/WordPress/gutenberg/blob/a3a63c111aad8cc7be2cf77c6cb525fe6e0d7baa/packages/block-library/src/image/block.json#L111-L113

2023-05-30 16:46 UTC, artemiomorales commented
I rebased on #51089, which removes the extra `<div>` around the `<figure>` element and fixes the duotoned image in the content. However, the image in the lightbox is unaffected.

>Maybe all you need is to change this selector instead:
>
> [gutenberg/packages/block-library/src/image/block.json](https://github.com/WordPress/gutenberg/blob/a3a63c111aad8cc7be2cf77c6cb525fe6e0d7baa/packages/block-library/src/image/block.json#L111-L113)
> 
> Lines 111 to 113 in [a3a63c1](https://github.com/WordPress/gutenberg/commit/a3a63c111aad8cc7be2cf77c6cb525fe6e0d7baa)
> 
>  "filter": { 
>  	"duotone": ".wp-block-image img, .wp-block-image .components-placeholder" 
>  }

I've tried targeting the overlay markup using this and it hasn't worked. Will continue digging around.

2023-05-30 17:56 UTC, ajlende requested changes
<img width="709" alt="image" src="https://github.com/WordPress/gutenberg/assets/5129775/f99cfc5a-9c5b-4c6a-8635-e20c51aba8e8">

It seems the global styles filter is overriding filters applied via the block attributes which shouldn't happen. You can kind of see in the screenshot the different filter applied in the background.

2023-05-30 18:19 UTC, ajlende commented
> > Maybe all you need is to change this selector instead
> > …
>
> I've tried targeting the overlay markup using this approach and it hasn't worked.

The duotone hook adds the generated filter id as a class to the first element in the block content.

https://github.com/WordPress/gutenberg/blob/82f6d03850a011b5ff66eb5f2162f7df34678e53/lib/class-wp-duotone-gutenberg.php#L882-L886

Then for the generated duotone CSS, it combines that filter id class with the duotone selector in block.json to apply the filter.

https://github.com/WordPress/gutenberg/blob/82f6d03850a011b5ff66eb5f2162f7df34678e53/lib/class-wp-duotone-gutenberg.php#L673-L684

If you can get the filter id class on the lightbox wrapper and add the new lightbox selector to block.json, you should be able to get it to work.

Let me know if you need any help :)

2023-06-01 12:06 UTC, SantosGuillamot commented
### Issue explanation

I was reviewing this, and I believe we cannot get the filter id class in the lightbox container with the current implementation. The way I understood it:
* The duotone class is added via a `render_block` filter to the parent wrapper using [this code](https://github.com/WordPress/gutenberg/blob/82f6d03850a011b5ff66eb5f2162f7df34678e53/lib/class-wp-duotone-gutenberg.php#L882-L886).
* In the `render_callback` of the image, to add the lightbox, we are getting the `<figure>` from the `block_content` and adding it to the overlay `<div>`. Which results in the following format:

```html
<figure>
   <img>
   <div class="overlay">
       <figure>
           <img>
       </figure>
   </div>
</figure>
```

The problem comes because the `render_block` filter runs after the `render_callback`. This means that:
* When the lightbox copies the `<figure>` to the overlay `<div>`, the duotone class doesn't exist yet.
* When the duotone filter adds the class, it only adds it to the parent `<figure>` and not to the one overlay `<div>`.

For this reason, I believe we cannot follow this approach unless we modify the duotone filter, which may result in other issues.

### Potential solution

I was thinking about how to solve it, and maybe we can **add the lightbox through a `render_block_core/image` filter** as well, that runs after the default `render_block`. This way, it will support not only the changes made by the duotone but also other changes made through the `render_block` filter.

Apart from that, it would be a good first step to abstract the lightbox behavior of the image block, which is something worth exploring in the future.

Any opinions on this approach? Would it make sense?

If so, which is the best place to add this filter?

2023-06-01 12:15 UTC, c4rl0sbr4v0 commented
Well, according to @mtias description [in an issue](https://github.com/WordPress/gutenberg/issues/50029). "Behaviors are meant to be reusable and composable interactive hooks that can be attached to blocks. "

In my opinion, for this and future behaviors, a filter per behavior should be the way to go, as it would be the "easiest" hay to apply it to different blocks, rather than upgrading each block. Ideally, behaviors should not be hard coded in the block folder.

Would be a good idea to have a proper package that could include all future behaviors?

2023-06-02 08:55 UTC, gziolo commented
I wanted to echo what @c4rl0sbr4v0 said. It is a reasonable approach and aligns with how most of the block support features work today, including the duotone filter. You can use `render_block` with a different priority if you want to control the order of when processing for the lightbox and the duotone get applied.  This way, you can have it ready for a more general usage that isn’t tied to the Image block only. It's also worth checking the existing implementations for block supports in https://github.com/WordPress/gutenberg/tree/trunk/lib/block-supports. Maybe some aspects can be abstracted using `WP_Block_Supports::get_instance()->register()`.

2023-06-05 11:37 UTC, SantosGuillamot commented
I opened [this pull request](https://github.com/WordPress/gutenberg/pull/51232) to move the behaviors to block supports, which should solve the problem with the duotone filter. Should we close this pull request @artemiomorales ?

2023-06-05 12:21 UTC, artemiomorales commented
@SantosGuillamot Sounds good! Let's continue discussion in the [new pull request](https://github.com/WordPress/gutenberg/pull/51232).

2023-06-05 12:21 UTC, closed without merging