Env: Migrate to Compose V2
WordPress/gutenberg pull request #51339
Opened 2023-06-08 12:56 UTC by lithrel

Fixes https://github.com/WordPress/gutenberg/issues/51249

## What?

This PR updates `docker-compose` command to v2 `docker compose`.

## Why?
As explained in https://github.com/WordPress/gutenberg/issues/51249 , `docker-compose` v1 is now [deprecated in favor of v2](https://docs.docker.com/compose/migrate/).

## How?
- Update of [docker-compose](https://www.npmjs.com/package/docker-compose) package, the new version [includes support for v2](https://github.com/PDMLab/docker-compose/blob/master/CHANGELOG.md#0240-2023-04-28)
- Update of a command using hardcoded `docker-compose`
- Update of some comments

## Testing Instructions
Run all modified commands:
- `wp-env start`
- `wp-env logs`
- `wp-env run cli wp user list`
- `wp-env stop`
- `wp-env clean`
- `wp-env destroy`

2023-06-13 01:24 UTC, noahtallen commented
The unit test error is unfortunate:

`SyntaxError: Cannot use import statement outside a module`

I think this is because wp-env is still using CJS and not ESM, but this 3rd party dependency (`yaml`) might not provide a CJS option.

I don't know if there's a decent workaround -- we might have to explore migrating wp-env to ESM.

2023-07-10 16:51 UTC, swissspidy commented
```
/home/runner/work/gutenberg/gutenberg/packages/env/node_modules/yaml/browser/index.js:3
    import * as YAML from './dist/index.js'
```

> I think this is because wp-env is still using CJS and not ESM, but this 3rd party dependency (`yaml`) might not provide a CJS option.

It's weird. It does have a CJS build under `dist/index.js`, see https://unpkg.com/browse/yaml@2.3.1/package.json. Shouldn't Node pick that export?

2023-07-10 20:14 UTC, noahtallen commented
> Shouldn't Node pick that export?

Hm, I'd think so! 🤔 Maybe an issue since we're still using node 14? (#52363 )

2023-08-11 11:44 UTC, lithrel commented
> Maybe an issue since we're still using node 14? (#52363 )

I just rebased to get Node 16, and same error apparently :thinking: 
I can get those tests to pass by adding in [Jest config](https://github.com/WordPress/gutenberg/blob/trunk/test/unit/jest.config.js) 
```js
"transformIgnorePatterns": [
    	"/node_modules/(?!(docker-compose|yaml)/)",
	"\\.pnp\\.[^\\/]+$"
],
```
but I feel like I'm missing something more obvious

2023-08-11 20:17 UTC, noahtallen commented
I'd recommend discarding all package-lock changes and then run npm install again! I wonder if we could actually write wp-env with ESM now because nothing imports its code

2023-08-11 20:20 UTC, noahtallen commented
I think `transformIgnorePatterns` is a fine workaround -- in this case, it does look like they need to be transpiled for Jest to use them. If those packages don't provide CJS output, and we don't use ESM, we won't be compatible. Normally, packages provide both types for compatibility, but I guess not in this case

2023-09-22 07:06 UTC, lithrel commented
@noahtallen I tested removing package-lock and reinstalling, but still the same issue. So I implementend the `transformIgnorePatterns` workaround (and also changed a line in documentation), it's passing now :+1: 

If you have a ticket for converting package to ESM I can take a look in the following weeks :eyes:

2023-11-09 23:38 UTC, ObliviousHarmony commented
It looks like the resolution problem is because of the conditional exports in `yaml` being incompatible with Jest. As far as I can tell, the standard is for "import" and "require" to be the conditional exports but `yaml` uses "node" and "default" instead. This ends up being resolved incorrectly and it tries to load the browser code as default. I'm going to submit an upstream fix to `"yaml "` and then once that gets released an upstream fix to `"docker-compose"`.

While we wait for that though, I think it would be worthwhile to get this PR across the finish line. `docker-compose` has been unsupported for quite some time and this change is likely fine as long as we mark it as major. Before we merge though, we should update `docker-compose` again since it has been a long time :smile:

2023-11-17 10:15 UTC, lithrel commented
> Before we merge though, we should update `docker-compose` again since it has been a long time 😄

@ObliviousHarmony  Rebased and updated  `docker-compose` to 0.24.3 :+1:

2023-11-21 18:52 UTC, ObliviousHarmony requested changes
Looks great, thanks for the rebase @lithrel! This looks good, I'm happy with it. Could you add a changelog entry and then we can merge it?

2023-11-22 06:40 UTC, lithrel commented
Done @ObliviousHarmony :)

2023-11-22 13:04 UTC, t-hamano commented
> Run all modified commands:
> - `wp-env start`
> - `wp-env logs`
> - `wp-env run cli wp user list`
> - `wp-env stop`
> - `wp-env clean`
> - `wp-env destroy`

I would like to inform you that all of these commands worked correctly on Windows 11 🎉

2023-11-27 20:20 UTC, ObliviousHarmony commented on packages/env/CHANGELOG.md
> +### Bug fix
```suggestion
### Breaking Change
```

This is really a breaking change and should be noted as such. I _believe_ release automation will also take care of bumping the major version with this header.

2023-11-27 21:21 UTC, ObliviousHarmony approved these changes
Thanks, everything worked for me locally just fine too :smile:

2023-12-04 23:15 UTC, noahtallen commented
Looks like we just need to fix the changelog conflict, and then I'm happy to merge!

2023-12-04 23:17 UTC, noahtallen approved these changes

2023-12-05 09:37 UTC, lithrel commented
@noahtallen rebased/resolved :+1:

2023-12-05 17:29 UTC, merged

2023-12-16 15:57 UTC, ockham commented
👋 FWIW, `npm run wp-env start` has recently started failing for me; I believe it was correlated with this change. The error message is as follows:

```
> gutenberg@17.3.0-rc.1 wp-env
> wp-env start

✖ Error while running docker compose command.
unknown shorthand flag: 'f' in -f
See 'docker --help'.

Usage:  docker [OPTIONS] COMMAND
```

The reason seems to be that `docker-compose` is now a Docker plugin (rather than a separate script or executable) that wasn't installed on my system (and hence `docker compose -f ...` was failing).

I’m using [colima](https://github.com/abiosoft/colima) on my system, and have installed it — and Docker — via `brew`. I found the solution to my issue [here](https://formulae.brew.sh/formula/docker-compose):

```
Compose is now a Docker plugin. For Docker to find this plugin, symlink it:
    mkdir -p ~/.docker/cli-plugins
    ln -sfn $HOMEBREW_PREFIX/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
```

After running those commands, `npm run wp-env start` is working again 🎉 

Just sharing in case anyone is experiencing the same issue.

2023-12-18 22:13 UTC, noahtallen commented
Very nice! I have Docker installed with Docker Desktop, and it seemed to work out of the box with that setup.

2024-02-20 09:05 UTC, swissspidy commented
FYI this did not properly update the version of `docker-compose` in the lock file, which caused some issues later on as a new version of `docker-compose` was released with a breaking change.

See #59183, #6133