Site Editor: Make string to add Template parts & Patterns consistent and translatable
WordPress/gutenberg pull request #51743
Opened 2023-06-21 14:11 UTC by t-hamano

Related to #51078

## What?
This PR makes Template Parts & Patterns Management dropdown string translatable in the site editor.

![capture](https://github.com/WordPress/gutenberg/assets/54422211/af3463dc-c18b-47e3-a9d0-b4eab6a5aa05)

_Update:_ At the same time, through code review, the following were additionally addressed.

- String changes for consistency: `Create a pattern` > `Create pattern`, `Create a template part` > `Create template part`
- Apply this consistency to the title of the template part/pattern modal

## Testing Instructions

No impact on code.

2023-06-21 21:58 UTC, alexstine approved these changes
👍

2023-06-21 22:07 UTC, richtabor requested changes, later dismissed
Left a few minor string changes.

2023-06-21 22:07 UTC, richtabor commented on packages/edit-site/src/components/add-new-pattern/index.js
> +						title: __( 'Create a template part' ),
This should probably read "Create template part"

2023-06-21 22:07 UTC, richtabor commented on packages/edit-site/src/components/add-new-pattern/index.js
> +				label={ __( 'Create a pattern.' ) }
Same with this one here: "Create pattern"

2023-06-21 22:07 UTC, richtabor commented on packages/edit-site/src/components/add-new-pattern/index.js
>  						label={ __( 'Create a pattern' ) }
"Create pattern"

2023-06-22 00:16 UTC, aaronrobertshaw reviewed
Thanks for fixing this @t-hamano 👍 

> Left a few minor string changes.

@richtabor These strings matched the [original template part modal's title](https://github.com/WordPress/gutenberg/pull/51078/files#diff-41b1e08c478663c461064e48175b08f04bde0523000f52cdc0028c0b0a0c4781L44). Do we wish to also change the modal titles for template parts & patterns to remain consistent?

2023-06-22 15:19 UTC, richtabor commented
> Do we wish to also change the modal titles for template parts & patterns to remain consistent?

Yes, that's fine.

2023-06-22 15:59 UTC, t-hamano commented
Thanks for the review, @aaronrobertshaw, @richtabor!

I have made the string consistent, including the `Modal` title.

![dropdownmenu](https://github.com/WordPress/gutenberg/assets/54422211/9eb157f4-0274-4254-bca7-da9110dd0fad)

![template-part](https://github.com/WordPress/gutenberg/assets/54422211/7d4334e0-683d-4248-873a-95437748835b)

![pattern](https://github.com/WordPress/gutenberg/assets/54422211/8e20dee6-ef28-46b3-acb6-069961c74c51)

2023-06-23 04:12 UTC, aaronrobertshaw approved these changes
LGTM 👍 

This might need a rebase though to pick up the recent e2e fixes. Maybe we could update the PR description as well to cover the extra changes also.

2023-06-23 05:26 UTC, t-hamano commented
Thank you all for your reviews!

I have rebased with the latest trunk and updated the PR description. Will merge as soon as it passes testing.

2023-06-23 06:01 UTC, t-hamano commented
@richtabor
Your reapproval might be needed to merge this PR 🙏

2023-06-23 06:11 UTC, merged

2023-06-27 01:23 UTC, tellthemachines commented
I just cherry-picked this PR to the release/16.1 branch to get it included in the next release: 0a924052a1