Make useBlockEditingMode() public
WordPress/gutenberg pull request #52094
Opened 2023-06-29 01:37 UTC by noisysocks

## What?
Makes `useBlockEditingMode()` (see https://github.com/WordPress/gutenberg/pull/50643) public so that extenders can use it. The accompanying selector (`getBlockEditingMode`) and actions (`setBlockEditingMode`, `unsetBlockEditingMode`) are also made public.

## Why?
A few folks have reached out to me asking for this as they'd like to use it in their plugins.

The only reason it's private is because I want the API to have time in the Gutenberg plugin where it can encounter real world usage before we merge it to Core and have to maintain backwards compatibility forever. WP 6.3 was too near when the API was added. By making this public now it will be merged as part of WP 6.4.

## Testing Instructions
Nothing specific. Check for regressions to the Page Content Focus functionality.

2023-07-11 09:07 UTC, Mamaduka requested changes
The changes look good, and I couldn't spot any regression page content focus.

We'll need to audit the `getBlockEditingMode` and remove the `unlock` wrapper where unnecessary.

Here are a few examples:

* https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-editing-mode/index.js#L52
* https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-inspector/index.js#L38-L42
* https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/block-list/block.js#L101-L105

There's more when you search the codebase.

2023-08-07 23:29 UTC, noisysocks commented
👍 all done @Mamaduka.

2023-08-09 03:19 UTC, Mamaduka approved these changes
Thanks for the follow-up, @noisysocks!

The changes look good to me. I smoke-tested the page/template editing in the Site Editor.

2023-08-09 04:11 UTC, merged

2023-10-13 00:00 UTC, ramonjd commented
### ✍🏻 Dev note

####  New public hook in the Block Editor API: useBlockEditingMode()

Blocks can set an editing "mode" using the [useBlockEditingMode](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/#useblockeditingmode) hook.

`useBlockEditingMode()` allows a block to restrict the user interface that is displayed for editing that block and its inner blocks.

The  block editing mode can be one of three options:

-   `'disabled'`: Prevents editing the block entirely, that is, it cannot be selected.
-   `'contentOnly'`: Hides all non-content UI, for example, auxiliary controls in the toolbar, the block movers, block settings.
-   `'default'`: Allows editing the block as normal.

The block editing mode is inherited by all of the block's inner blocks, unless inner blocks have their own modes set.

Usage: 

```jsx
function MyBlock( { attributes, setAttributes } ) {
    useBlockEditingMode( 'disabled' );
    // MyBlock will be marked as 'disabled' editing mode.  
    return <ChildComponent { ...useBlockProps() }></ChildComponent>;
}
```

`useBlockEditingMode()` also returns a block's current editing mode, which can be utilized to further configure block properties. For example, a component inheriting its parent's block editing mode:

```js

function ChildComponent( props ) {
	const blockEditingMode = useBlockEditingMode();
	let text = 'Child component';
	if ( blockEditingMode === 'disabled' ) {  
		// Block is disabled, add custom block properties to indicate disabled mode.
	        text+= ' is disabled!';
	}
	
	if ( blockEditingMode === 'default' ) {
	    // Block can be edited, show controls or other editing-related settings.
	    <MyBlockCustomControls />
	}

        return <div { ...props }>{ text }</div>;
}

```

2024-04-26 12:40 UTC, ellatrix commented
Why do extenders need this?

2024-04-26 12:43 UTC, Mamaduka commented
> Why do extenders need this?

I think to check the block editing mode and hide controls based on it. Some of the [core blocks ](https://github.com/search?q=repo%3AWordPress%2Fgutenberg+useBlockEditingMode+path%3A%2F%5Epackages%5C%2Fblock-library%5C%2Fsrc%5C%2F%2F&type=code) do the same.

2024-04-26 12:57 UTC, ellatrix commented
I can't help but feel these API weren't ready to be public. And now we'll have to support them forever. `getBlockEditingMode` is a recursive selector and used in many other selectors. But now it seems very difficult to change. We're also still discussing alternative for hiding controls (such as #60779), which will be needed for blocking bindings among other things, maybe `contentOnly` and disabling blocks too.

Why should a block be able to disable itself through `useBlockEditingMode( 'disabled' )`? It seems there's only a single use case in GB, so I don't think this should've been made public either?

2024-04-26 13:02 UTC, Mamaduka commented
Yeah. We probably rushed making this public :/

Here's one example in the core that uses `useBlockEditingMode( 'disabled' )` - #60326.

2024-04-26 13:38 UTC, fabiankaegy commented
@ellatrix I cannot speak to if this was rushed or not. But I can speak to why we need it. 

Id you are building a custom block that should work and expose a subset of controls inside a `contentOnly` locked container this is needed. That is why core blocks use it. 

Yeah there is the never official way of adding `__experimentalRole: "content"` in the attribute definition which achieved something similar. But it definitely is something that is needed if custom block should support the various mode that WordPress core has been shipping since 6.1 (2022)