Edit Site: Fix the missing templateType when calling useSiteEditorSettings hook
WordPress/gutenberg pull request #52503
Opened 2023-07-11 10:49 UTC by arthur791004

## What?

The pattern with the post types will be filtered out since the site editor only allows patterns with the specific post type. However, the allowed post type is always `undefined` because we never pass the value when calling the hook.

## Why?

This resolves https://github.com/Automattic/wp-calypso/issues/79145 that the pattern with `wp_template_part` post type becomes the placeholder pattern when you're editing the template part and you cannot do anything on the placeholder pattern.

## How?

The `useSiteEditorSettings` hook supports `templateType` as an argument, just pass the value to it so it can filter the patterns out with the specific post type correctly.

## Testing Instructions

TBD

### Testing Instructions for Keyboard

## Screenshots or screencast 

| Before | After |
| - | - |
| ![image](https://github.com/WordPress/gutenberg/assets/13596067/2f94a6b8-9189-45c1-a5d7-1b4ac9e2307e) | ![image](https://github.com/WordPress/gutenberg/assets/13596067/613eab99-0116-4289-be5f-0ef6b06a0ea9) |

2023-07-12 07:17 UTC, okmttdhr approved these changes
I did not have time to test, but the code looks good 👍 
Thank you for your quick fix.

2023-07-12 07:18 UTC, okmttdhr commented
It might be better to have one more person to review, but let me know if you need to merge.

2023-07-12 13:45 UTC, getdave requested changes
Rather than dd a dependency to the hook why not select the template type within the hook itself?

```
const { templateType } = useSelect( ( select ) => {
		const { getEditedPostType } = unlock( select( editSiteStore ) );

		return {
			templateType: getEditedPostType(),
		};
	}, [] );
```

2023-07-12 14:03 UTC, arthur791004 commented
@getdave I just want to follow the original design to let callers decide the template type. But I agree with you that we can select the template type inside the hook itself. I've made the change as you suggested, thanks 👍

2023-07-12 16:02 UTC, getdave approved these changes
This looks better now - thanks for amending. Not sure about those test failures though... 😟

2023-07-13 02:55 UTC, arthur791004 commented
Seems like the failed tests are flaky as the results are different after re-triggering 😓

2023-07-13 08:14 UTC, getdave commented
@arthur791004 You'll want to `rebase` as opposed to `merge`. We look to avoid merge commits.

- Pull trunk from your upstream (as it looks like you are working on a fork)
- Merge upsteam into your fork's `trunk`.
- Switch to this branch
- `git rebase trunk`

2023-07-13 08:25 UTC, arthur791004 commented
Okay!

2023-07-13 09:00 UTC, arthur791004 commented
@getdave The tests are passed now!

2023-07-13 09:34 UTC, getdave approved these changes
LGTM - this will need backporting so pinging @tellthemachines and @ramonjd

2023-07-14 00:32 UTC, ramonjd commented
Tested and works as described 👍🏻

2023-07-14 00:33 UTC, merged

2023-07-14 01:38 UTC, tellthemachines commented
I just cherry-picked this PR to the update/first-batch-pre-RC1 branch to get it included in the next release: 298f5b1298

2023-07-14 02:04 UTC, arthur791004 commented
Thank you 😊