Create block interactive template
WordPress/gutenberg pull request #52549
Opened 2023-07-12 07:15 UTC by juanmaguitar

## What?
Creation of the "create-block-interactive-template" and addition of "view.js" to the default "create-block"

## Why?
For the reasons explained [here](https://github.com/WordPress/gutenberg/pull/52508#issuecomment-1631105733)

2023-07-12 15:16 UTC, ryanwelcher approved these changes
The template code looks great and I love the addition of viewScript. Before we merge, not sure if we need another review in regards to this adding a new package.

2023-07-12 15:16 UTC, ryanwelcher commented
cc @gziolo

2023-07-12 15:17 UTC, ryanwelcher commented
@juanmaguitar it looks like we need to update the Create Block test to account for the new `view.js` file being added.

2023-07-12 16:44 UTC, luisherranz requested changes
Hey, Juanma. The template code looks good to me but I don't understand why this PR is built on top of [a branch](https://github.com/WordPress/gutenberg/compare/trunk...create-block-interactive-template) that contains part of [the variant PR](https://github.com/WordPress/gutenberg/pull/52508#issuecomment-1631105733) instead of `trunk`. It's not clear to me what's going to be merged and why it will end up in a new branch. From the variant PR, we only need the `viewScript` property propagation.

Would it be worth switching the base of this PR to `trunk` so we can clearly see what's included? Thanks!!

2023-07-12 16:44 UTC, luisherranz commented on packages/create-block-interactive-template/block-templates/view.js.mustache
> +{{#isBasicVariant}}
I see double-line breaks in this file. Is it on purpose?

2023-07-12 16:44 UTC, luisherranz commented on packages/create-block-interactive-template/block-templates/view.js.mustache
> +				context[ '{{namespace}}' ].isOpen = !context[ '{{namespace}}' ].isOpen;
```suggestion
				context[ '{{namespace}}' ].isOpen = ! context[ '{{namespace}}' ].isOpen;
```

There's a missing space after the `!` (my fault).

2023-07-13 18:21 UTC, juanmaguitar commented
I'm closing this PR in favor of this other PR https://github.com/WordPress/gutenberg/pull/52612

2023-07-13 18:21 UTC, closed without merging

2023-07-13 18:23 UTC, juanmaguitar commented
> Hey, Juanma. The template code looks good to me but I don't understand why this PR is built on top of [a branch](https://github.com/WordPress/gutenberg/compare/trunk...create-block-interactive-template) that contains part of [the variant PR](https://github.com/WordPress/gutenberg/pull/52508#issuecomment-1631105733) instead of `trunk`. It's not clear to me what's going to be merged and why it will end up in a new branch. From the variant PR, we only need the `viewScript` property propagation.
> 
> Would it be worth switching the base of this PR to `trunk` so we can clearly see what's included? Thanks!!

@luisherranz You're right. That PR was an attempt of using the same branch and the same PR fo these changes. 
But it's definitely more clear and easy to create a new branch and a new PR on top of `trunk`

2023-07-13 20:01 UTC, luisherranz commented
Thank you, Juanma. I've reviewed the other PR 🙂