Allow setting defaultBlock in navigation block
WordPress/gutenberg pull request #52610
Opened 2023-07-13 16:27 UTC by sethrubenstein

## What?
Create a defaultBlock attribute and sets innerblocks to reference that if attributes are present in it.

## Why?
Solves for #50982

## How?
This adds a new defaultBlock attribute and a check for it along with a quick sanity check if it fails it falls back to the DEFAULT_BLOCK constant.

## Testing Instructions

- Open a post or page
- Copy and paste this block markup into the editor:

- Click + inside the navigation block.
- Now category links should be the default when clicking + inside this navigation block.

2023-07-13 18:07 UTC, scruffian commented
It seems like this only works with variations of the navigation link block. Could we also make it work for all blocks that are allowed inside the navigation block?

2023-07-13 18:11 UTC, sethrubenstein commented
@scruffian It defaults to core/navigation-link, it's current default behavior but if you could do any block thats supported inside the navigation block, like:

`<!-- wp:navigation {"defaultBlock":{"name":"my-custom/nav-block","attributes":{"myValue":"xyz"}}} /-->`

2023-07-13 20:04 UTC, scruffian commented
That didn't work in my testing but maybe I was doing it wrong!

2023-07-14 16:58 UTC, sethrubenstein commented
You are correct @scruffian, because the allowedBlocks are set as a constant at https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/navigation/constants.js#L5 this will only work for the blocks listed therein. I agree it would be nice to extend that as well, and I believe there is other work underway to standardize around an `allowedBlocks` attribute https://github.com/WordPress/gutenberg/pull/52467, when that work is complete along with this work your use-case will be possible. 

https://github.com/WordPress/gutenberg/assets/180264/603d4259-175c-449d-ad66-69ac5f5d3875

2023-07-20 12:32 UTC, scruffian commented
I was trying it with the search block, which is an allowed block, so I would expect it to work...

2023-07-26 02:16 UTC, sethrubenstein commented
Hi @scruffian Just checking back on this, I'm able to get the search block to work, are you passing in something for attributes? In this implementation I'm only passing in the defaultBlock attribute if you give more than just a name, so that the DEFAULT_BLOCK behavior is respected for the time being except for very explicit use cases. 

https://github.com/WordPress/gutenberg/assets/180264/bce02c48-9cfe-4c64-97e5-d75c2e814beb

2023-08-25 09:57 UTC, draganescu commented
One thing to test is that when the navigation block includes other blocks than navigation link the auto insert behavior is turned off. Maybe we should just customize the variation of the navigation link? Like defaultLinkType instead of defautlBlock?

2023-08-25 10:08 UTC, scruffian commented
Ah yes, it wasn't working because I hadn't specified attributes. It does work now.

> One thing to test is that when the navigation block includes other blocks than navigation link the auto insert behavior is turned off

This is still the case.

2023-08-25 10:09 UTC, scruffian approved these changes
I think this is good to go.

2023-08-25 13:29 UTC, draganescu requested changes
I am not sure about this. @sethrubenstein could you consider my idea of the attribute being only for the variation of the navigation link, not for specifying any block? It's just a too finicky for a public API for any block considering we have an allowedBlocks list and that specifying anything other than the navigation link disables the behavior which this PR aims to improve.

What do you think?

2023-08-25 13:35 UTC, sethrubenstein commented
@draganescu yeah that works by me. I need to catch up on the auto insertion apis. All I'm really trying to solve for is when you click plus on the nav block to insert a specific variation (in our case the category link variation) of the navigation link block. Let me investigate best way to do that now that there's this insertion api and I'll modify this PR accordingly.

2023-11-30 15:37 UTC, colorful-tones commented
I'm trying to catch up on all things `defaultBlock`, but very well missed a bunch. However, I'm currently trying to get it to work in [`useInnerBlocksProps`](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor#useinnerblocksprops) and it will not work at all. Does it only work with the Navigation block? That seems odd and the [README](https://github.com/WordPress/gutenberg/blob/HEAD/packages/block-editor/src/components/inner-blocks/README.md#defaultblock) should likely be updated with a pertinent example (if so). 😕

2023-12-01 15:09 UTC, sethrubenstein commented
@colorful-tones Yeah unfortunately this isn't going to work with Nav block currently. We stabilized the defaultBlock api point in 6.4 so it should be available but I realize now I had the syntax wrong on the docs and need to update that asap. The correct syntax for defaultBlock is `{name: 'my/block-name', attributes: { content: 'This block has some predefined content when clicking to insert it into the editor'}}` and of course have `directInsert` set to true as well.

2024-10-21 03:36 UTC, closed without merging