Fix: #52886 Make all the 'Loading' strings consistent
WordPress/gutenberg pull request #52901
Opened 2023-07-24 18:23 UTC by ducksblock

## What?
Making all the 'Loading' strings consistent

## Why?
Making the Loading strings consistent adds to the UI. Here I am fixing #52886 issue which will improve the overall user experience.

## How?
I have changed the strings that were not consistent. I have added an ellipsis at the end of every 'Loading' string.

## Testing Instructions
1. Open any page where  loading pops up
2. Observe the 'Loading' strings

### Testing Instructions for Keyboard
N/A.

## Screenshots or screencast
N/A

2023-07-26 07:36 UTC, afercia requested changes
Thank you @ducksblock !
Apologies, maybe I was not clear.
I'm not sure changing all the strings to just `Loading…` would be ideal. I'd keep the additional text because it adds some useful context. I'd suggest to just add the ellipsis and fix the typos.

2023-07-26 08:23 UTC, ducksblock commented
@afercia I have updated the files as per the request.

2023-07-26 13:14 UTC, afercia approved these changes
Thanks!
LGTM to me, tests pass, all green.

2023-08-01 16:11 UTC, ducksblock commented
@geriux @tellthemachines It'd be great if you guys could review this :)

2023-08-04 07:11 UTC, geriux commented
> @geriux @tellthemachines It'd be great if you guys could review this :)

Hey there! These changes don't affect the mobile editor but in any case, it looks good to me 👍

2023-08-04 09:00 UTC, ducksblock commented
> > @geriux @tellthemachines It'd be great if you guys could review this :)
> 
> Hey there! These changes don't affect the mobile editor but in any case, it looks good to me 👍

Thanks! Can you please approve it so that it can get merged?

2023-08-13 16:25 UTC, t-hamano approved these changes
@ducksblock Thank you for your contribution!

The code looks good to me, no conflicts, and all tests pass, so I would like to merge it.

2023-08-13 16:25 UTC, merged