Updated coding-guideline documentation to include experimental APIs
WordPress/gutenberg pull request #5313
Opened 2018-02-28 16:38 UTC by Xyfi

## Description

Adds documentation to coding-guideline.md, regarding experimental exposed APIs.

### Experimental APIs

Exposed APIs that are still being tested, discussed and are subject to change should be prefixed with `__experimental`, until they are finalized. This is meant to discourage developers from relying on the API, because it might be removed or changed in the (near) future.

Example:

```js
export {
	internalApi as __experimentalExposedApi
} from './internalApi.js';
```

## How Has This Been Tested?

## Screenshots (jpeg or gifs if applicable):

## Types of changes

Documentation

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style.
- [ ] My code has proper inline documentation.

2018-02-28 16:55 UTC, atimmer commented
For clarification, I would change the imported API to `internalApi`. So the code example becomes:

```js
export {
	internalApi as experimental__exposedApi
} from './internalApi.js';
```

2018-02-28 16:55 UTC, atimmer approved these changes

2018-02-28 19:59 UTC, aduth requested changes
Pending feedback from https://github.com/WordPress/gutenberg/pull/4484#discussion_r171354847 per how the demonstrated example is an ESLint error on [`camelcase`](https://eslint.org/docs/rules/camelcase)

2018-03-01 20:24 UTC, aduth approved these changes
Nice 👍

2018-03-02 14:41 UTC, merged