Ignore IDE and Editor specific files
WordPress/gutenberg pull request #53152
Opened 2023-07-30 09:19 UTC by widoz

Someone might use Phpstorm or customize the VSCode installation, those files shouldn't be committed.

## What?
Exclude IDE & Editor specific files and directories

## Why?
For local development it would require less maintainance

## How?
Adding some lines to `.gitignore`

## Testing Instructions
Not relevant

### Testing Instructions for Keyboard
Not relevant

## Screenshots or screencast 
Not relevant

2023-07-30 13:01 UTC, Mamaduka requested changes
Thanks for contributing, @widoz!

The editor-specific files should be ignored locally via global `.gitignore` rather than maintain the list in the project.

Past examples: https://github.com/WordPress/gutenberg/pull/2254#issuecomment-320525495 and https://github.com/WordPress/gutenberg/pull/27360#issuecomment-735773544

2023-07-31 15:44 UTC, widoz commented
> The editor-specific files should be ignored locally via global .gitignore rather than maintain the list in the project.

@Mamaduka thanks for the reply. The problem is that, you might have multiple projects for which you want to have those files under versions. Does not the global force that for all local projects?

2023-07-31 16:38 UTC, Mamaduka commented
I believe you can use the `!` prefix and negate patterns from global `.gitignore`.

## Example

```
!.idea
!.vscode/settings.json
```

2023-08-01 07:22 UTC, widoz commented
> I believe you can use the ! prefix and negate patterns from global .gitignore.

@Mamaduka but at that point for only one single project I'm forced to change the `.gitignore` of a bunch of other projects. What's the main point to not have those files ignored in this project if them are not necessary?

2023-08-01 07:56 UTC, Mamaduka commented
The project has 100+ contributors; if everyone starts adding their environment-specific files to `.gitignore`, we would have an extensive list to maintain. It's recommended to handle those via personal global git ignore files.

General solutions like these might not work for some, but they make maintaining the project easier.

I'll have to close this PR as `wontfix`.

2023-08-01 07:56 UTC, closed without merging