Allow passing optional `afterLoad` callbacks to `store` calls
WordPress/gutenberg pull request #53363
Opened 2023-08-04 19:17 UTC by DAreRodz

## What?

Allow developers to pass callbacks to the Interactivity API `store` function, e.g.,

```js
import { store } from '@wordpress/interactivity';

store(
  {
    // Your global store needs...
  },
  {
    afterLoad: ({ state }) => {
      if (state.myBlock.syncStore) {
        // Sync the store...
      },
    },
  },
);
```

## Why?

Some block types would need to initialize stuff in the global state, which might require the store to be ready.

## How?

A `Set` instance stores all the passed `afterLoad` callbacks to avoid duplicates. All registered callbacks run right after the `init()` function, receiving the global store.

## Testing Instructions
It includes e2e tests that should pass.

2023-08-07 16:49 UTC, DAreRodz commented
@luisherranz ready for review ☝️

2023-08-07 21:40 UTC, artemiomorales approved these changes
Looks good to me!

2023-08-08 10:11 UTC, DAreRodz commented
Thanks, @artemiomorales. I'll wait for @luisherranz to take a look as well before merging. 😊

2023-08-09 09:00 UTC, luisherranz requested changes
Codewise everything looks good. Great tests by the way 🙂

Would you mind adding a new section to the [API reference](https://github.com/WordPress/gutenberg/blob/trunk/packages/interactivity/docs/2-api-reference.md#the-store) to document the options argument and in there, the `afterLoad` option? It doesn't have to be extensive, we can improve it later, but at least we should mention it. Thanks!!

2023-08-09 09:00 UTC, luisherranz commented on packages/interactivity/CHANGELOG.md
> +### New Features
This needs to be singular to be correctly picked up: https://github.com/WordPress/gutenberg/tree/HEAD/packages#maintaining-changelogs

```suggestion
### New Feature
```

2023-08-09 09:22 UTC, gziolo commented on packages/interactivity/CHANGELOG.md
> +### New Features
Both work, singular and plural forms.

2023-08-09 10:37 UTC, luisherranz commented on packages/interactivity/CHANGELOG.md
> +### New Features
`startsWith`? 🙃

2023-08-09 11:18 UTC, gziolo commented on packages/interactivity/CHANGELOG.md
> +### New Features
English grammar is very convenient in this particular case 😄

2023-08-10 16:31 UTC, luisherranz approved these changes
Cool. Thanks, David 🙂

2023-08-11 08:16 UTC, merged