Adds a README.md file to the project scaffolded by create-block
WordPress/gutenberg pull request #53896
Opened 2023-08-23 16:59 UTC by mburridge

## What?

Adds a `README.md` template file to the `create-block` package. This file contains an overview of the project scaffolded by `create-block` and descriptions of the files and directories contained within the project. There are also links to external information sources.

## Why?

Useful as a learning aid and as a reference when creating a new project with the `create-block` package.

## Testing Instructions
To test locally run each of the following commands from within `packages/create-block/lib`:

```
node index.js test-create-block
node index.js --variant dynamic test-create-block-dyn
```

Check that the `README.md` files generated each contain different content for static and dynamic blocks and that they accurately reflect the respective projects.

_Remember to delete the `test-create-block` and `test-create-block-dyn` directories when done!_

## Discussion point

This file will not be generated if the `--no-plugin` flag is defined. Should lines 59 to 84 instead be put in a separate `README.md` file in [the `block` directory](https://github.com/WordPress/gutenberg/tree/trunk/packages/create-block/lib/templates/block)?

2023-08-23 18:31 UTC, ryanwelcher requested changes
This is great work and will be a big help! I made a couple suggestions and my only overall note is to try to add external reference links to all the sections if possible to create a better learning path.

2023-08-23 18:31 UTC, ryanwelcher commented on packages/create-block/lib/templates/plugin/README.md.mustache
> +The `build` directory is where the final deployable build of the block will go. The build process will put compiled versions of files from the `src` directory in here. You should never need to touch
```suggestion
The build process will put compiled versions of files from the `src` directory in here. You should never need to touch this directory directly. 
```

2023-08-23 18:31 UTC, ryanwelcher commented on packages/create-block/lib/templates/plugin/README.md.mustache
> +The `node_modules` directory is where all the modules that the build process depends on live. Again you should never need to directly modify the contents of this directory. To install packages here u
Should we add a link here similar to `package.json`?

2023-08-23 18:31 UTC, ryanwelcher commented on packages/create-block/lib/templates/plugin/README.md.mustache
> +`editor.scss` is a file containing SCSS that styles the appearance of the block in the block editor. It requires a compile step which will result in `build/index.css`.
SCSS is an extension. We should be clear that this file is CSS that will be compiled using Sass
```suggestion
`editor.scss` is a file containing CSS that will be compiled using [Sass](https://sass-lang.com/) that styles the appearance of the block in the block editor. It requires a compile step which will result in `build/index.css`. 
```

2023-08-23 18:31 UTC, ryanwelcher commented on packages/create-block/lib/templates/plugin/README.md.mustache
> +This file performs the server-side rendering in a **dynamic** block.
Is there a link we can add here?

2023-08-23 18:31 UTC, ryanwelcher commented on packages/create-block/lib/templates/plugin/README.md.mustache
> +[This file]
Probably don't need this section at all. It's a bit self-evident :) Just my opinion, not strongly held though.

2023-08-23 18:31 UTC, ryanwelcher commented on packages/create-block/lib/templates/plugin/README.md.mustache
> +## The structure of the project
Love this.

2023-08-23 18:31 UTC, ryanwelcher commented on packages/create-block/lib/templates/plugin/README.md.mustache
> +│── README.md (this file)
```suggestion
│── README.md
```

2023-08-23 18:31 UTC, ryanwelcher commented on packages/create-block/lib/templates/plugin/README.md.mustache
> +`style.scss` contains SCSS that styles the appearance of the block in the front end. It will also be used in the editor unless a style defined here is over-ridden by one in `editor.scss`. This file r
Same note about SCSS being an extension.
```suggestion
`style.scss` contains CSS that will be compiled using [Sass](https://sass-lang.com/] and styles the appearance of the block in the front end. It will also be used in the editor unless a style defined here is over-ridden by one in `editor.scss`. This file requires a compile step which will result in `build/style-index.css`. 
```

2023-08-23 18:33 UTC, ryanwelcher commented
That [failing test](https://github.com/WordPress/gutenberg/actions/runs/5954647830/job/16152587237?pr=53896) is due to this PR adding a new file and it will need to be [updated here I believe](https://github.com/WordPress/gutenberg/blob/trunk/bin/test-create-block.sh#L52)

2023-08-24 15:29 UTC, gziolo commented
It's a great idea to add documentation around the scaffolded project structure. Thank you so much for opening the PR.

I only wanted to highlight two important aspect to consider:
- The new `README.md` file will get created in the root of the project next to `readme.txt`, so that might be unclear what purpose they play. In addition to that, `reamde.txt` is used by the Plugin Directory to pull additional metadata and the intro page. If there is no `readme.txt` then the Plugin Directory tries to read `README.md` instead. More details in https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/.
- The `plugins` folder is used not only with the default template, but also with all external templates that don't define `pluginsTemplatePath`. In effect, the explanation for the project structure might be misleading for some other templates scafolded. The best example would be to run:
  ```bash
  npx wp-create-block test-create-block --template es5
  ```

2024-12-11 10:52 UTC, gziolo commented
@ryanwelcher, is there any follow-up work planned here?

2024-12-11 19:04 UTC, ryanwelcher commented
I'm not sure if @mburridge is still contributing. I can pick this up and move off of his fork to move it forward.

2025-04-30 14:45 UTC, karmatosed commented
For now, I am going to close this as looks like both the contributor originally might have stopped working and the person who picked it up isn't going to carry it on. That is ok - we can always reopen and continue. It seems like it is a good idea to come back to, for now though let's move on.

2025-04-30 14:45 UTC, closed without merging