Changed the message when there are no pages from an error message to …
WordPress/gutenberg pull request #53930
Opened 2023-08-24 20:14 UTC by mklute101

…a more intuitive message

## What?
When a page list block is empty, rather than returning an error message, simply state that there are no pages.

## Why?
The current error message is unintuitive.
 
## How?
It changes the error message to text

## Testing Instructions

 1. Set all pages in the test env to draft
 2. Edit the header or footer template part
 3. Insert a page list block. 
 4. Review the message

### Testing Instructions for Keyboard

## Screenshots or screencast 
<img width="588" alt="Screenshot 2023-08-24 at 4 14 33 PM" src="https://github.com/WordPress/gutenberg/assets/13650277/f6e59a1e-1be0-40d0-ac1d-869265987d8b">

2023-08-25 08:06 UTC, jasmussen approved these changes
I'd call it "You have no pages."

As a small step forward, let's ship this. That said, I still don't know that we want to show anything at all here. But I'll share my arguments on #44486 and we can look at that as a followup. Thanks for the PR!

2023-08-25 08:54 UTC, getdave reviewed
Thank you for your PR 🙇 

I'd like to confirm if this changed markup is _perceivable_ by users of assistive technology. The `Notice` component comes with a set of built in affordances that are very important.

I sense the root of this PR is about the wording - I'm happy with that. However, I would like to understand _why_ we decided to change the components used. What is the justification?

Many thanks

2023-08-25 08:57 UTC, jasmussen commented
There's a bit more conversation in #44486 that touches specifically on this, notably that I'm questioning the usability of showing notice content in the canvas at all. I will defer to experts in the field, but my intuition would be that _the content canvas_ would not be where I'd look for error notices, were I a screen-reader user. To that end, and to ensure actual WYSIWYG, I really think we should move towards having the canvas for content, and the UI for notices and error messages.

2023-08-25 09:06 UTC, draganescu requested changes, later dismissed
I don't see the new message :(


<img width="750" alt="Screenshot 2023-08-25 at 12 06 23" src="https://github.com/WordPress/gutenberg/assets/107534/1cb3be25-42c3-4e90-a38c-c706b1e8ffee">

2023-08-25 09:52 UTC, draganescu commented on packages/block-library/src/page-list/edit.js
> +			></span>
I tested and just using a simple span is better, no className and no `data-rich-text-placeholder`. Just a span with the text passed through `__`.

2023-08-25 16:11 UTC, jameskoster commented
"You" infers site ownership upon the current user which may not be appropriate in enterprise environments with may users with different roles. Perhaps something like "No pages found" would work better?

2023-08-26 14:43 UTC, mklute101 commented
Would it make sense for the language to be the same as an empty post list/query loop? "No results found"
<img width="244" alt="Screenshot 2023-08-26 at 10 42 16 AM" src="https://github.com/WordPress/gutenberg/assets/13650277/865bc234-a09f-47fb-a8ab-fc299b42a42f">

2023-08-28 09:57 UTC, draganescu commented
@mklute101 it should be more specifc than "results" because this is a more specific block trying to fall back to a default and it can't - because there are no pages. So we need to talk about pages.

2023-08-29 13:18 UTC, getdave commented on packages/block-library/src/page-list/edit.js
> +			></span>
```suggestion
			<span>{ __( 'You have no pages yet.' ) }</span>
```

2025-08-04 09:28 UTC, Mamaduka commented
What's the status on this PR? Is it good to merge, or should we close it as stale?

2025-08-21 05:00 UTC, Mamaduka commented
Closing this as "stale".

2025-08-21 05:00 UTC, closed without merging