php.net/date links made functional
WordPress/gutenberg pull request #54205
Opened 2023-09-06 07:31 UTC by karstengresch

Either the link given is intended to work (it does by forwarding) - then it should be functional. Or not - then it should be replaced. Right?

## What?

## Why?

## How?

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast

2023-09-06 13:33 UTC, skorasaurus approved these changes
looks good to me; thanks.

2023-09-06 18:50 UTC, alexstine reviewed
@karstengresch Thanks for the PR.

Could you please run the following command locally to build docs changes? This should allow our static checks to pass.

```bash
npm run docs:build
```

Committing the changes should make all checks green.

2024-03-20 03:38 UTC, t-hamano requested changes
Thanks for the PR!

The document content you update will be automatically built from JSDoc. Therefore, the original JSDoc needs to be updated. In other words, it is a `packages/date/src/index.js` file.
After updating `See php.net/date.` in this file to `See https://php.net/date.`, you need to run `npm run docs:build`.

2025-08-04 09:45 UTC, Mamaduka commented
Thanks for contributing, @karstengresch!

It looks like the issue has been resolved via #69280. I'm going to close the PR.

2025-08-04 09:45 UTC, closed without merging