Query Loop: Allow "enhanced pagination" only with core blocks
WordPress/gutenberg pull request #54347
Opened 2023-09-11 11:23 UTC by DAreRodz

## What?

Prevents enabling enhanced pagination in a Query Loop block if a third-party block is inside the Post Template to ensure compatibility.

1. If the setting is disabled, you can add third-party blocks to the Post Template.
2. If the setting is disabled and third-party blocks are in the Post Template, the setting can't be enabled.
3. If the setting is enabled and you add third-party blocks, a Modal is shown requiring further action:
   a. preserve the third-party blocks: the setting is disabled.
   b. undo changes: the third-party blocks are not added, and the setting is kept enabled.

Tracking issue: https://github.com/WordPress/gutenberg/issues/54291

## Why?

Third-party blocks can be interactive and use a different library than the Interactivity API. This could lead to problems as the
Interactivity API can add, modify, or remove DOM nodes handled by third-party libraries, thus making the blocks that depend on those libraries stop working.

## How?

I haven't found an easy way to prevent certain blocks from being inserted inside another **at any level**, so I wrote a hook to detect what kind of blocks are contained. If a third-party block is found, and the setting is enabled, a modal appears, requiring action to keep a valid state.

## Testing Instructions
TBD

### Testing Instructions for Keyboard
TBD

## Screenshots or screencast
TBD

2023-09-11 12:56 UTC, luisherranz requested changes
I haven't reviewed the code yet, but the UX feels great so far, congratulations 🙂

However, we need to check that there are no third-party blocks inside the Query block, not inside the Post Template block because the regions covers all the Query block nodes. 

Can you change that?


https://github.com/WordPress/gutenberg/assets/3305402/515238b7-049b-4fb9-818f-da16be8a8c74

2023-09-11 12:58 UTC, luisherranz commented
> I haven't found an easy way to prevent certain blocks from being inserted inside another at any level, so I wrote a hook to detect what kind of blocks are contained. If a third-party block is found, and the setting is enabled, a modal appears, requiring action to keep a valid state.

By the way, it's not up to me to decide, but I think showing a modal is the correct UX. Preventing blocks from being inserted could be confusing.

2023-09-11 13:23 UTC, luisherranz commented
For context, we're still thinking about the mechanism to identify compatible blocks. More information here:

- https://github.com/WordPress/gutenberg/discussions/54194

But until we make a decision, we decided to limit the feature to only the Core blocks because they are the most common ones and we know that they are all compatible.

2023-09-11 14:38 UTC, DAreRodz commented
> However, we need to check that there are no third-party blocks inside the Query block, not inside the Post Template block because the regions covers all the Query block nodes.
> 
> Can you change that?

Sure, it makes total sense! I think I read the [task description](https://github.com/WordPress/gutenberg/issues/54291#:~:text=Only%20allow%20enabling%20if%20all%20blocks%20inside%20Post%20Template%20are%20Core%20blocks%20to%20make%20sure%20they%20are%20compatible) too literally. 😅

> - Only allow enabling if all blocks inside Post Template are Core blocks to make sure they are compatible

2023-09-11 15:06 UTC, luisherranz commented
That was my bad, sorry 🙂

2023-09-12 10:25 UTC, luisherranz requested changes
We need to improve the accessibility of the modal. I made a video to explain, but basically I think that when the modal appears, the focus should be on the `Ok, understood` button, and the title & message of the modal should be announced.

<div>
    <a href="https://www.loom.com/share/4398656726654e8db6cac53b5709d209">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/4398656726654e8db6cac53b5709d209-with-play.gif">
    </a>
  </div>

https://www.loom.com/share/4398656726654e8db6cac53b5709d209

EDIT: Can you search for all the modals in the codebase to see if there's another one that appears suddenly like this one, to see how they deal with the accessibility?

2023-09-12 11:11 UTC, DAreRodz commented
Thanks for the review, @luisherranz. 🙏 Yup, I also noticed the accessibility issues with the Modal component. I'm working on fixing them.

2023-09-12 12:44 UTC, luisherranz commented
Apart from that, do you consider this ready for review?

2023-09-13 10:08 UTC, DAreRodz commented
> Apart from that, do you consider this ready for review?

Not yet; I'm planning to include the additional enhancements listed in https://github.com/WordPress/gutenberg/issues/54414 in this PR.

2023-09-13 10:25 UTC, luisherranz approved these changes
Thanks, David!! 🎉

2023-09-13 11:01 UTC, merged