Interactivity API: Add `timeout` option to `navigate()`
WordPress/gutenberg pull request #54474
Opened 2023-09-14 19:16 UTC by DAreRodz

## What?

This PR adds an option to the `navigate()` function exposed by the Interactivity API.

When the timeout expires, the browser reloads the page you are visiting instead of waiting.

Part of https://github.com/WordPress/gutenberg/issues/54291

## Why?

To add a default behavior when a navigation takes too long.

## How?

Inside `navigation()`, where the function awaits the request to be resolved, I added another promise that fulfills when the timeout passes. Then, I used `Promise.race()` to return the resolved value of the fastest promise.

## Testing Instructions

You can use the Enhanced pagination feature of the Query Loop block to test this.

1. Inside the Site Editor, go to the Blog Home template.
2. Enable "Enhanced pagination" in the Query Loop settings.
3. Visit the homepage.
4. In the browser dev tools, go to the Network tab, and create a very slow throttling profile (slower than "Slow 3G").
5. Select that throttling profile
6. On the site, click "Older posts"
7. Wait 10 seconds
8. Deactivate network throttling
9. The browser should reload the requested page.

## Screenshots or screencast

https://github.com/WordPress/gutenberg/assets/6917969/3dc7c540-276c-4ab5-8e74-d72d76c77e77

2023-09-15 09:01 UTC, SantosGuillamot requested changes
I have a couple of comments:

* We are focusing the first element even if the timeout is reached.
* The loading bar disappears after the timeout, even if it hasn't navigated yet to the new page.

These aspects combined give me the impression that it has navigated even if we are still in the same page. Could we not focus the first element and keep the loading bar until it actually loads the next page?

I made a quick video explaining what I mean:

https://github.com/WordPress/gutenberg/assets/34552881/967a45e3-c107-4082-b5e7-1f7f6063fa03

2023-09-15 10:16 UTC, DAreRodz commented
> These aspects combined give me the impression that it has navigated even if we are still in the same page. Could we not focus the first element and keep the loading bar until it actually loads the next page?

Thanks, @SantosGuillamot; that's good feedback. 👌

The `navigate` function doesn't currently return any information about whether the navigation has timed out. In practice, that shouldn't be a problem, because the page reloads directly by changing `window.location`. However, in this case, as we're adding a network throttling, that location change takes much longer than expected and you can notice the `navigate` function has finished, and the scroll and focus have also changed.

We could maybe return a boolean from the `navigate` function and take that value into account before updating focus or finishing the loading bar animation. 🤔

2023-09-18 07:58 UTC, luisherranz commented
Maybe navigate should never resolve if there was a timeout.

2023-09-18 19:14 UTC, DAreRodz commented
I made `navigate()` to throw an error if the current timeout finishes. That should fix the issue, @SantosGuillamot.

2023-09-19 07:46 UTC, luisherranz commented
Why is throwing an error better than not resolving the function?

2023-09-19 08:09 UTC, DAreRodz commented
> Why is throwing an error better than not resolving the function?

I don't think it's _better_―for me, it was just a matter of convenience. 😅

Actually, the `navigate()` function is not resolving, but _rejecting_, and throwing an error effectively stops the execution of the current async function if you're not capturing it so the code waiting for `navigate()` doesn't run.

In addition, it simplifies the code as we don't have to write something to handle when the timeout finishes and then await a never-resolving `Promise`.

If you prefer, here you have a code that makes `navigate()` neither resolve nor reject. 😄 

```patch
diff --git a/packages/interactivity/src/router.js b/packages/interactivity/src/router.js
index e4f53970fb..58d0ec3e10 100644
--- a/packages/interactivity/src/router.js
+++ b/packages/interactivity/src/router.js
@@ -92,15 +92,20 @@ export const navigate = async ( href, options = {} ) => {
 	prefetch( url, options );
 
 	const pagePromise = pages.get( url );
+
+	let hasTimedOut = false;
 	const timeoutPromise = new Promise( ( r ) => {
 		timeoutId = setTimeout( r, options.timeout ?? 10000 );
 	} ).then( () => {
 		window.location.assign( href );
-		throw new Error( 'timeout' );
+		hasTimedOut = true;
 	} );
 
 	const page = await Promise.race( [ pagePromise, timeoutPromise ] );
 
+	// Never ever resolve.
+	if ( hasTimedOut ) await new Promise( () => {} );
+
 	// Once the page is fetched, the destination URL could have changed (e.g.,
 	// by clicking another link in the meantime). If so, bail out, and let the
 	// newer execution to update the HTML.

```

2023-09-19 10:07 UTC, luisherranz commented
Let's go with the unresolved then to avoid throwing errors on people's websites 🙂

2023-09-19 11:47 UTC, luisherranz approved these changes
Looks good to me. Thanks, David 🙂

2023-09-19 13:22 UTC, SantosGuillamot approved these changes
It seems to be working fine now 🙂

2023-09-19 15:15 UTC, merged