Template Part block: Fall back to current theme if no theme attribute is given.
WordPress/gutenberg pull request #55217
Opened 2023-10-10 18:37 UTC by ockham

Part of the task in WordPress Core seeking performance improvements:
- https://github.com/WordPress/wordpress-develop/pull/5455.
- https://core.trac.wordpress.org/ticket/59583

An alternative approach to #53423.

Result of a [discussion](https://wordpress.slack.com/archives/C02RQBWTW/p1696959836535969?thread_ts=1696880738.627909&cid=C02RQBWTW) with @felixarntz, aiming to fix the performance regression re-introduced by https://core.trac.wordpress.org/changeset/56818.

## What?
If a Template Part block is encountered that doesn't have a `theme` attribute, fall back to the current them (`get_stylesheet()`) instead.

## Why?
This should allow removing injection of the `theme` attribute during rendering of the Template Part block.

## How?
By falling back to the current theme (`get_stylesheet()`) if `$attributes['theme']` isn't set.

## Testing Instructions
Verify that Template Parts blocks that are part of patterns still work, both on the frontend and in the editor. Specifically, verify that there are no `Template part has been deleted or is unavailable` errors.

_Will be followed up by a Core PR to remove `theme` attribute injection on the frontend._

cc/ @gziolo

2023-10-10 18:43 UTC, felixarntz reviewed
I know this is a WIP, just sharing very early feedback here :)

2023-10-10 18:43 UTC, felixarntz commented on packages/block-library/src/template-part/index.php
> +	if ( isset( $attribues['theme'] ) ) {
```suggestion
	if ( isset( $attributes['theme'] ) ) {
```
😁

2023-10-10 18:43 UTC, felixarntz commented on packages/block-library/src/template-part/index.php
> +	if ( isset( $attributes['slug'] ) ) {
We probably want to keep this condition to not change the behavior:
```suggestion
	if ( isset( $attributes['slug'] ) && get_stylesheet() === $theme ) {
```

2023-10-11 06:41 UTC, gziolo commented on packages/block-library/src/template-part/index.php
> +	if ( isset( $attribues['theme'] ) ) {
Fixed with https://github.com/WordPress/gutenberg/pull/55217/commits/06af1954236e2a8e918dde411b69fe7c7281e47a.

2023-10-11 07:31 UTC, gziolo commented
After looking at how https://github.com/WordPress/gutenberg/pull/55217 is implemented, I think we should also remove the following line that get executed only in the Gutenberg plugin:

https://github.com/WordPress/gutenberg/blob/8a9cb70272edcfdfd34f3557848949eb0fd29921/packages/block-library/src/pattern/index.php#L47

The same logic should be handled now on the front end with the fallback logic for the `theme` attribute in the Template Part block.

2023-10-11 10:39 UTC, mikachan reviewed
Thank you for working on this! I can confirm this fixes the original issue in https://github.com/WordPress/gutenberg/issues/53194.

I tested using the same themes (Overlaid and Lativ) as when I tested https://github.com/WordPress/gutenberg/pull/53423, and this PR works well 👍

2023-10-11 14:45 UTC, pbking commented
Tested in all scenarios I can dream up and works as I would expect.  My only suggestion is that, as @gziolo suggested, the call to `_inject_theme_attribute_in_block_template_content()` be removed in this change.  It's unnecessary with this change.  

Once that change has been made this is ready to ship.

2023-10-11 15:17 UTC, felixarntz approved these changes
Pending the additional feedback in https://github.com/WordPress/gutenberg/pull/55217#issuecomment-1757019650, the change so far looks good to me.

2023-10-11 15:37 UTC, felixarntz commented
Given @ockham is out today, I took the liberty of pushing the additionally requested change in https://github.com/WordPress/gutenberg/pull/55217/commits/47608ff7a68aa60d3ed878314a0d57e8d93e8a27. @gziolo @pbking @mikachan Could you please take another look?

2023-10-11 16:01 UTC, mikachan approved these changes
LGTM and works well in my testing, thanks @felixarntz!

2023-10-11 16:41 UTC, felixarntz requested changes
I am currently benchmarking and profiling this change further, and it seems the approach here is not right in terms of performance at least. Marking as request for changes for now, let's hold off merging at this point.

2023-10-11 18:38 UTC, felixarntz approved these changes
I have concluded my performance investigation here and left a summary in https://core.trac.wordpress.org/ticket/59583#comment:20.

TL;DR This fix makes sense and is good to merge. However, it doesn't fully address the performance issues (partly because the initial "performance win" was mostly due to the bug introduced.

I have identified another very promising performance opportunity related to this https://core.trac.wordpress.org/ticket/59600 and https://github.com/WordPress/wordpress-develop/pull/5463

2023-10-11 20:26 UTC, felixarntz commented
@ockham @gziolo @mikachan I think this is good to merge. I'll leave that to you since I'm not sure on the workflow in relation to backporting to the 6.4 release, but LGTM from my end. Once backported to core, we can update https://github.com/WordPress/wordpress-develop/pull/5455 accordingly.

2023-10-12 09:18 UTC, ockham commented
Thanks all! I'll go ahead and merge this then; also going to mark for inclusion in WP RC.

@mikachan We need this in Core to unblock https://github.com/WordPress/wordpress-develop/pull/5455. In principle, it's probably fine to land on Monday, but it might be nice to do it even earlier to give us some more time to discover any potential issues with this. Are y'all planning a package sync this week still by any chance? 😊

2023-10-12 09:19 UTC, merged

2023-10-12 09:19 UTC, ockham commented on packages/block-library/src/template-part/index.php
> -	if ( isset( $attribues['theme'] ) ) {
🙈

2023-10-12 09:58 UTC, mikachan commented
I just cherry-picked this PR to the 6.4-rc1 branch to get it included in the next release: fd15da3b83