Add Get started with create-block doc.
WordPress/gutenberg pull request #55373
Opened 2023-10-15 21:24 UTC by ndiego

Fixes https://github.com/WordPress/gutenberg/issues/54960

## What?
This PR adds a getting started guide for `create-block`. This package is one of the best tools for getting started with block development. Having a primer on the subject in the [Getting Started](https://developer.wordpress.org/block-editor/getting-started/devenv/) section will help new developers get oriented.

2023-10-16 09:55 UTC, gziolo commented
Between this PR and #55372, I'm wondering how much we could remove from README files in `@wordpress/create-block` and `@wordpress/scripts` to point folks to these newly created documents instead. Otherwise, we might end up maintaining similar content in two places, which is usually suboptimal in the long term as they tend to diverge.

It surely can be tackled (if not planned already) as a follow-up, I mostly wanted to flag it as a great way to send folks from these packages to higher-level onboarding docs.

2023-10-16 09:56 UTC, gziolo commented on docs/getting-started/devenv/get-started-with-create-block.md
> +The [`@wordpress/create-block`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/) package is an officially supported tool for scaffolding a WordPress plug
Aside: there is also an integration with `wp-env` included in Create Block, but it isn't enabled by default. Folks can enable it with the `--wp-env` CLI param, or through external templates.

2023-10-16 09:59 UTC, gziolo commented on docs/getting-started/devenv/get-started-with-create-block.md
> +When working on your block, use the `npm run start` command. This will start a development server and automatically rebuild the block whenever any code change is detected.
While it works to use `npm run start`, it's also possible to call [`npm start`](https://docs.npmjs.com/cli/v10/commands/npm-start) for convenience. I don't remember if the included form is being used to align with other npm commands so just sharing as a sidenote.

2023-10-16 10:01 UTC, gziolo commented
Love this effort!

2023-10-16 10:43 UTC, fabiankaegy commented
@gziolo i would hate to see the actual readme files of the packages get removed. These are what shows on NPM and what should in my opinion always be the source of truth for a package.

2023-10-16 11:08 UTC, gziolo commented
> @gziolo i would hate to see the actual readme files of the packages get removed. These are what shows on NPM and what should in my opinion always be the source of truth for a package.

I didn't say that:

>  how much we could remove from README files

My comment was about removing similar content not the file from the package and linking to the Block Editor Handbook instead.

2023-10-16 12:10 UTC, fabiankaegy commented
> > @gziolo i would hate to see the actual readme files of the packages get removed. These are what shows on NPM and what should in my opinion always be the source of truth for a package.
> 
> I didn't say that:
> 
> > how much we could remove from README files
> 
> My comment was about removing similar content not the file from the package and linking to the Block Editor Handbook instead.

🤦 

Sorry for the confusion :)

2023-10-16 15:00 UTC, ndiego commented
> Between this PR and https://github.com/WordPress/gutenberg/pull/55372, I'm wondering how much we could remove from README files in @wordpress/create-block and @wordpress/scripts to point folks to these newly created documents instead. Otherwise, we might end up maintaining similar content in two places, which is usually suboptimal in the long term as they tend to diverge.

Yeah, I agree. We can look at those next. I think the readme's for the packages could be slimmed down and really just focus on the technical documentation and link to the "Get started..." guides as needed.

2023-10-17 11:49 UTC, juanmaguitar requested changes

2023-10-17 11:49 UTC, juanmaguitar commented on docs/getting-started/devenv/get-started-with-create-block.md
> +The [`@wordpress/create-block`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/) package is an officially supported tool for scaffolding a WordPress plug
We could add some more context here to introduce the tool:

> Custom blocks for the Block Editor in WordPress are usually registered via plugins and they are defined through a specific set of files. The [`@wordpress/create-block`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/) package is the officially supported tool to scaffold the structure of files needed to create and register a block.

2023-10-17 11:49 UTC, juanmaguitar commented on docs/getting-started/devenv/get-started-with-create-block.md
> +Using the terminal, navigate to the `plugins/` folder of your [local WordPress development environment](https://developer.wordpress.org/block-editor/getting-started/devenv/#local-wordpress-environmen
Because with `wp-env` (and `wp-now`) we don't really need a previous local WordPress installation we could smooth this "blocker" 

> You can use `create-block` to create the boilerplate of a custom block registered by a plugin from just anywhere and then [use  `wp-env` from the inside of your generated plugin folder,](https://developer.wordpress.org/block-editor/getting-started/devenv/get-started-with-wp-env/) to launch a local WordPress with your new plugin installed and activated.

> If you have your own [local WordPress development environment] navigate to your `plugins/` folder and run `create-block'  from there.

> Run the following command to scaffold an example block plugin:

2023-10-17 13:22 UTC, ndiego commented on docs/getting-started/devenv/get-started-with-create-block.md
> +The [`@wordpress/create-block`](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/) package is an officially supported tool for scaffolding a WordPress plug
Good call, fixed.

2023-10-17 13:22 UTC, ndiego commented on docs/getting-started/devenv/get-started-with-create-block.md
> +Using the terminal, navigate to the `plugins/` folder of your [local WordPress development environment](https://developer.wordpress.org/block-editor/getting-started/devenv/#local-wordpress-environmen
Just updated the doc with that info.

2023-10-17 19:12 UTC, juanmaguitar approved these changes

2023-10-17 19:18 UTC, merged