Update Labels in Block Inserter (block patterns tab)
WordPress/gutenberg pull request #55986
Opened 2023-11-09 07:32 UTC by SavPhill

In the Patterns tab of the Block Inserter I have amended the labels for 'My patterns' and 'All patterns' to 'My Patterns' and 'All Patterns' (title case). I believe this is a more consistent approach, also I see further down we have 'Call to Action' pattern category which is title case.

<img width="1436" alt="Screenshot 2566-11-09 at 14 23 30" src="https://github.com/WordPress/gutenberg/assets/38789408/a8933508-7886-4128-99fd-49a2190036c4">

## What?

Adding title case for two labels

## Why?

A more professional, consistent edit
## How?

## Testing Instructions

1. Open the block inserter and view the 'Patterns' tab.

### Testing Instructions for Keyboard

## Screenshots or screencast

2023-11-09 19:15 UTC, richtabor requested changes
I suppose "Call to Action" should be "Call to action", rather than changing the title case of the menu items for patterns. I suppose "All patterns" could be just "All" though. 

Sentence case is used prominently throughout the UI:

![CleanShot 2023-11-09 at 14 12 55](https://github.com/WordPress/gutenberg/assets/1813435/2952415a-1de5-401f-9171-e49b3affffe4)
![CleanShot 2023-11-09 at 14 14 36](https://github.com/WordPress/gutenberg/assets/1813435/55d36072-5de4-4fe9-9e3c-86651bbd2645)
![CleanShot 2023-11-09 at 14 14 57](https://github.com/WordPress/gutenberg/assets/1813435/d85a0234-e80e-436b-b0b2-037c6fa54f98)

2023-11-10 22:01 UTC, richtabor commented
Thoughts @WordPress/gutenberg-design?

2023-11-13 09:38 UTC, jasmussen commented
Since sentence case (with capitals for proper nouns) is the standard, so good catch on the inconsistencies.

Per the latest change, it appears we have "All" and "My patterns". Agreed also that "Call to Action" should be sentence case, but that can be separate if need be? Otherwise, 👍 👍

2023-11-13 15:32 UTC, richtabor approved these changes

2023-11-23 12:58 UTC, SavPhill commented
I'm not sure why the End-to-End Test has failed for this adjustment. What's required to resolve this?

2023-11-23 20:04 UTC, merged

2023-11-23 20:55 UTC, glendaviesnz commented
>I'm not sure why the End-to-End Test has failed for this adjustment. What's required to resolve this?

Was a failure unrelated to this PR - I reran the test and it passed.