Site Editor: Update the order of the sidebar items
WordPress/gutenberg pull request #56430
Opened 2023-11-22 11:10 UTC by scruffian

## What?
Reorders the items in the sidebar of the Site Editor, in Site View.

## Why?
Users are much more likely to want to edit pages and templates than Navigation or Styles, so we should raise these up. We would also prefer that they begin by working on their pages than their navigation, as its an easier place to start.

## How?
Simply reorder the code

## Testing Instructions
Go to the Site Editor and check the order of the items in the sidebar.

## Screenshots or screencast 
Before
<img width="181" alt="Screenshot 2023-11-22 at 11 09 44" src="https://github.com/WordPress/gutenberg/assets/275961/a28371fe-71ff-4ce1-9020-c5d6c93fdc08">

After
<img width="183" alt="Screenshot 2023-11-22 at 11 07 39" src="https://github.com/WordPress/gutenberg/assets/275961/883c623e-a4d9-4518-8865-7432cd364b50">

2023-11-22 11:15 UTC, MaggieCabrera commented
I'd argue that on theme activation, Styles would probably be the first thing you'd want to change or at least check, to see if the options the theme includes are what you like. The problem with this is once you are done with that, it's no longer relevant for you and get's stuck at the top never to be used again. Complicated.

2023-11-22 11:48 UTC, draganescu commented
I think putting pages 1st is the thing that has to go through. Ideally the sidebar item order should be a reflection of what we think users do most. I doubt template updates, managing patterns and style switching and often used after setup. But incoming updates will make this more complicated (with new content management features available) so not sure we can land on the best ordering now. Maybe even Navigation can go under patterns who knows.

But putting Pages 1st makes a lot of sense.

2023-11-22 14:40 UTC, richtabor commented
I like this; the only change I'd make is moving Patterns above Templates. 

After pages, patterns are the next most composable units at this level in the site editor. You're more likely to create and manage patterns than you are templates.

2023-11-22 14:42 UTC, richtabor commented
It's a bit odd having Navigation all the way at the bottom too; maybe it's fine to have Styles at the end - as it's the most different.

2023-11-23 14:39 UTC, scruffian commented
I updated this so that the new order is:

- Pages
- Patterns
- Templates
- Navigation
- Styles

2023-11-24 06:57 UTC, okmttdhr commented
Thank you for your quick action, @scruffian!

In the context of block theme previews, it seems that users often prefer to adjust Styles. This tendency is because many users are inclined to explore variations in the look and feel of their site rather than delving into detailed setups while initially trying out a theme preview.

Maybe we can add a condition to address this situation?

2023-11-26 04:05 UTC, richtabor commented
> Maybe we can add a condition to address this situation?

Or perhaps styles is the active view when previewing a theme.

2023-11-26 19:54 UTC, richtabor commented
> Pages
Patterns
Templates
Navigation
Styles

I like it.

2023-11-26 22:11 UTC, autumnfjeld commented
> I'd argue that on theme activation, Styles would probably be the first thing you'd want to change or at least check.

100%
Also for normal SE usage, I'd think Styles should come first.  It's the easiest thing for a user to grasp.  And likely one of the first things the "average"  user will play with.

Can we move Styles to the top? Or second following Pages?

2023-11-26 22:16 UTC, autumnfjeld commented
> Users are much more likely to want to edit pages and templates than Navigation or Styles,

@scruffian Why do you think users won't be frequently using Styles?  Do you have data on that?

IMO, particularly for new sites or anyone looking to do a refresh of fonts or colors, Styles is a very important feature.

2023-11-27 14:32 UTC, ianstewart commented
Based on watching users in usability testing, paired with my own conception of themes I'd suggest the following order.

- Styles
- Templates
- Pages
- Patterns
- Navigation


The list starts at the top with the broadest global means of previewing things: global fonts, colours, and other design details. Then moves on to the "big pages" of templates, most notably with the "big" template for your home page. Then down to more granular and smaller as you go.

2023-11-27 15:17 UTC, scruffian commented
I don't have any data, and I don't feel strongly about the order except that I think Navigation should not be the top.

I updated it to:

- Styles
- Templates
- Pages
- Patterns
- Navigation

2023-11-28 00:52 UTC, okmttdhr approved these changes
Looks good to me 🙌

2023-11-28 11:58 UTC, jameskoster commented
Just noting that as part of the admin redesign work there are plans to allow customisation of menus. See the first video here: https://github.com/WordPress/gutenberg/issues/53322 (around 7:20). This can happen automatically in different flows too, for instance when previewing a theme Styles might be given increased prominence.

2023-11-28 14:10 UTC, draganescu requested changes
This PR evolved approximatively like this:

0. navigation, styles, pages, templates, patterns
1. pages, templates, patterns, styles, navigation
2. pages, patterns, templates, navigation, styles
3. styles, templates, pages, patterns, navigation

This shows a relative lack of consensus on what we're doing here. The goal of the PR was to move Navigation from being 1st item. Now we're reordering all the items :) and with conflicting views:

- are styles somethig that should be 1st all the time?
- is navigation something that should be last all the time?
- is the site editor a place where you'll eventually go to edit content, if so, then pages are likely lost in the middle

I just want to make sure we note these differences in approach and views before this just lands.

@jameskoster thanks for mentioning the incoming customisation features - nevertheless the default is probably gona be at least 7 out of 10 sidebars.

2023-11-29 15:00 UTC, getdave commented
I'm not convinced that reorder these items makes a huge amount of difference. People scan lists. We're adept at doing so. Once we find the right item we can easily recall it's location within the list for next time.

Moreover, this list of menu items has changed several times over the past few releases. I would tend to agree with Andrei that it's difficult to agree on a consensus when there is this amount of flux.

2023-11-30 12:15 UTC, jameskoster commented
> nevertheless the default is probably gona be at least 7 out of 10 sidebars

That could be correct, but it's quite a bold assumption, would you say only 3 out of 10 users customise their home screens/desktops? The point was more that we don't really know how much of a problem this is currently, or how much impact customisability will have. So while I don't totally oppose it, changing the order feels a little arbitrary to me, especially as it has already changed a few times already as noted above.

2023-12-01 11:23 UTC, draganescu commented
>  So while I don't totally oppose it, changing the order feels a little arbitrary to me, especially as it has already changed a few times already as noted above.

I am saying this exact thing, with the metaphoric 7 out of 10, that _many_ people rely on the default so "changing the order feels a little arbitrary to me" and it's not made easier to commit just because people will be able to customise :)

2023-12-05 10:26 UTC, closed without merging