Add centering style also to the theme style output
WordPress/gutenberg pull request #5706
Opened 2018-03-20 07:46 UTC by jasmussen

Fixes comment in https://github.com/WordPress/gutenberg/pull/5209#issuecomment-374328167.

Previous implementation assumed the theme would handle centering, just like it's traditionally handled alignleft and alignright classes, but since the aligncenter is now applied to the `figure` element, any theme that uses code like `img.aligncenter` won't work. Hence this PR.

2018-03-20 17:47 UTC, aduth requested changes
For images which are resized, the explicit width is assigned to the `figcaption`, so it won't be properly centered by `text-align: center;` (since the width of the container itself is restricted). In the theme I'm using (Astra), `.aligncenter` is styled with `display: block; margin-left: auto; margin-right: auto;`

It's a bit of a slippery slope to start making these fixes on behalf of themes. How far do we take this? What about themes which have their own `.aligncenter` (not `img`-filtered) styles which conflict with the ones we define as the compatibility styles?

2018-03-21 07:28 UTC, jasmussen commented
In general I'd be okay with closing this PR as a "wontfix" and let themes do the work. 

However the change to add a figure around an img is somewhat big, and given how basic an element images are, it _would_ be nice if images, floats and centering did not require theme updates. So far we've noted that you don't have to change your theme at all, to make it Gutenberg compatible, though you _can_ opt in to wide alignments. 

As such, I'd prefer to update this PR with the suggested code you noted, for _images_ specifically. But regardless, I'm pinging @karmatosed for a decision & thoughts.

2018-03-21 20:46 UTC, karmatosed commented
> However the change to add a figure around an img is somewhat big, and given how basic an element images are, it would be nice if images, floats and centering did not require theme updates. So far we've noted that you don't have to change your theme at all, to make it Gutenberg compatible, though you can opt in to wide alignments.

I agree with this and whatever we can do to ease we should. I also agree we don't want to bring too much burden into Gutenberg, it's a balance. However, in this case I feel it's important to add this.

2018-03-21 20:46 UTC, karmatosed approved these changes

2018-03-22 11:02 UTC, jasmussen commented
@aduth I don't disagree with you — it feels slightly like overstepping, to add these styles. However in stock Twenty Sixteen using Gutenberg, it feels like centering this image, unresized, in Gutenberg should _just work_:

![raised-fist_270a](https://user-images.githubusercontent.com/1204802/37766699-05efe536-2dc8-11e8-99dc-828df84b4277.png)

If I apply your suggested styles, (`display: block; margin-left: auto; margin-right: auto;`), I get this in the editor:

<img width="853" alt="screen shot 2018-03-22 at 11 55 10" src="https://user-images.githubusercontent.com/1204802/37766752-2b5538b2-2dc8-11e8-9040-56c5a5e014eb.png">

and thijs on the frontend:

<img width="1140" alt="screen shot 2018-03-22 at 11 54 34" src="https://user-images.githubusercontent.com/1204802/37766761-30c4f9d6-2dc8-11e8-9783-0c4bfdfc6d4e.png">

If I add the "text-align center", it works:

<img width="1146" alt="screen shot 2018-03-22 at 11 57 51" src="https://user-images.githubusercontent.com/1204802/37766786-435cc65a-2dc8-11e8-8d57-4deb6dd12604.png">

It even works if I resize the image:

<img width="1125" alt="screen shot 2018-03-22 at 11 58 25" src="https://user-images.githubusercontent.com/1204802/37766831-6ce71cfa-2dc8-11e8-9eb4-4158a229915a.png">

It also works with resized and unresized floats:

<img width="342" alt="screen shot 2018-03-22 at 11 59 19" src="https://user-images.githubusercontent.com/1204802/37766886-9df69c44-2dc8-11e8-90e6-34e3fd737c51.png">

<img width="725" alt="screen shot 2018-03-22 at 12 00 03" src="https://user-images.githubusercontent.com/1204802/37766888-9f90af5e-2dc8-11e8-8243-89342546664f.png">

I understand your concern, and pushed your suggested code from Astra as well. I share some of those concerns myself in https://github.com/WordPress/gutenberg/pull/5209#issuecomment-367957818, I even created this PR to address the float+caption issue in a different way: https://github.com/WordPress/gutenberg/pull/5460

What are your thoughts on how best to proceed?

2018-04-03 14:26 UTC, aduth approved these changes
Let's merge this as-is. I agree `figcaption` wrapper changes warrant some transitional defaults, also at least scoped to the block.

2018-04-04 06:49 UTC, merged

2018-04-04 06:49 UTC, jasmussen commented
👍 👍 thanks Andrew.