Save Button: Fix the translation of the Activate button
WordPress/gutenberg pull request #57147
Opened 2023-12-18 06:51 UTC by arthur791004

## What?

Add the comment of the translator to the interpolation string to make the string able to be translated

## Why?

Referring to https://github.com/WordPress/gutenberg/pull/55752#discussion_r1428062410, we have to fix the translation for the interpolation string.

## How?

Simply add the comment of the translator.

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast

2023-12-18 07:49 UTC, okmttdhr approved these changes
Thanks for fixing it ✅

2023-12-18 09:26 UTC, mcsf requested changes
Maybe I wasn't the clear in [my comment](https://github.com/WordPress/gutenberg/pull/55752#discussion_r1428062410): the strings aren't being translated, and that's the first thing to fix:

```diff
-return sprintf( 'Activating %s', previewingThemeName );
+return sprintf( __( 'Activating %s' ), previewingThemeName );
```


 My observation about `translators:` comments was a corollary of that:

```diff
-return sprintf( __( 'Activating %s' ), previewingThemeName );
+return sprintf(
+    // translators: ...
+    __( 'Activating %s' ),
+    previewingThemeName
+);
```

2023-12-19 09:52 UTC, arthur791004 commented
> Maybe I wasn't the clear in https://github.com/WordPress/gutenberg/pull/55752#discussion_r1428062410: the strings aren't being translated, and that's the first thing to fix:

I'm sorry I didn't notice the `__()` is missing 🙈

2023-12-19 15:33 UTC, mcsf approved these changes

2023-12-19 15:35 UTC, mcsf commented
There was a linting error, but I pushed a fix.

2023-12-19 15:53 UTC, merged