Add static block previews experiment
WordPress/gutenberg pull request #57977
Opened 2024-01-18 17:45 UTC by scruffian

## What?
This is a followup to https://github.com/WordPress/gutenberg/pull/55850.

## Why?
The idea is to get the basic version of this into the repo as an experiment, so that more people can use it.

The idea works well, but there are some problems with placeholder content. To solve this we need to make use of things like the block bindings API, which aren't fully fleshed out. By making this available as an experiment we hope that the shortcomings will be clearer to more people and also it will be possible to iterate on these ideas without needing to keep a long running branch in sync with trunk.

## How?
- Add a new experiment to Gutenberg
- Create a new REST API endpoint to fetch a preview of a block / group of blocks
- Implements a new component to fetch the preview from the API and insert the HTML, instead of rendering a block editor

## Testing Instructions
- Enable the `Static Block Previews` experiment in `wp-admin/admin.php?page=gutenberg-experiments`.
- Switch to TT4
- Open the site editor
- Go to the "Replace Template" option:
<img width="269" alt="Screenshot 2024-01-18 at 17 44 56" src="https://github.com/WordPress/gutenberg/assets/275961/fdaf2864-8d77-4f6f-aa16-b8e9fcf7892a">
- Confirm that the previews load without placeholders!

2024-01-18 17:46 UTC, scruffian commented on packages/block-editor/src/components/block-preview/auto.js
> +				{ children ? (
I don't like doing this, is there another way?

2024-01-23 13:33 UTC, getdave commented
Why a new PR? How come we didn't just change https://github.com/WordPress/gutenberg/pull/55850 to be experimental? 

Seems like fewer files were changed in this PR so perhaps it's a subset?

2024-02-01 17:21 UTC, draganescu commented
@getdave we made a new PR b/c the previous one was more exploratory and had lots of duplication in place. Here it's parts of the previous learning applied. Plus the experiment.

I think this is in a good state now to land as an experiment. If the experiment is enabled:

- a new REST controller is available exposing one new endpoint
- a server preview component is inserted via block editor settings
- this server preview component takes over the default component that is just a block list block rendered

We still need to iterate to:

- see about placeholder preview on the server
- try to integrate previewing with block bindings, binding to example data
- see about the required context and how that can use standard ways (replace the "fake post" logic)
- see about reusing the block render endpoint

... but iteration will be simpler with the experimental code merged.

2024-02-05 10:31 UTC, draganescu approved these changes
Let's get this in and iterate on it 🚀

2024-02-05 10:59 UTC, ellatrix requested changes
Can we wait for a bit here? I'm investigating the pages that you are testing and there's a lot of room for improvement on the editor side.

2024-02-05 16:07 UTC, fabiankaegy commented
I also want to make sure everyone is in alignement whether this shuld go into WordPress 6.5 without having gone through a few testing cycles in the Gutenberg plugin. Just want to make sure we are not rushing something into core unless it is ready

2024-02-05 16:32 UTC, scruffian commented
> I also want to make sure everyone is in alignement whether this shuld go into WordPress 6.5 without having gone through a few testing cycles in the Gutenberg plugin. Just want to make sure we are not rushing something into core unless it is ready

I agree, the intention is to merge this as an experiment in the plugin only so that we can find ways to get it working with block bindings.

2024-02-05 18:45 UTC, draganescu commented
I don't understand blocking an experiment from landing. @ellatrix @fabiankaegy did you find any leak in the guards we put in place for the experiment? If not why block this?

This makes iterating on the server side rendering API easy and _possible_. With the incoming block bindings and the advancements in the HTML API one should be able to entirely render patterns and templates on the server, not needing to instance a whole editor clientside.

So this work is independent of the attempts to make the editor faster. It just happens that _today_ it is faster, hence the experimental nature.

2024-02-05 18:55 UTC, fabiankaegy commented
@draganescu sorry I didn't look at the code when I left the comment. So I for one didn't recognize this was an experimental API. 

Knowing that there is no concern from me.

2024-02-05 19:24 UTC, getdave commented on lib/compat/wordpress-6.5/rest-api.php
> +add_action( 'rest_api_init', 'gutenberg_register_block_rederer_routes' );
```suggestion
function gutenberg_register_block_render_routes() {
	$gutenberg_experiments = get_option( 'gutenberg-experiments' );
	if ( empty( $gutenberg_experiments ) || ! array_key_exists( 'gutenberg-server-block-previews', $gutenberg_experiments ) ) {
		return;
	}
	$block_renderer_controller = new Gutenberg_Render_Blocks_Controller();
	$block_renderer_controller->register_routes();
}

add_action( 'rest_api_init', 'gutenberg_register_block_render_routes' );
```

2024-02-05 19:25 UTC, getdave commented on lib/compat/wordpress-6.5/rest-api.php
> +function gutenberg_register_block_rederer_routes() {
If this is experimental and not targetted for 6.5 then this code should be in the `experiments` directory.

2024-02-05 19:25 UTC, getdave commented
As this is not targetted for 6.5 and it an experiment I:

- updated the label on the PR
- recommended moving the PHP code to the correct matching directory

2024-02-06 07:58 UTC, ellatrix commented
I have many thoughts on this.

* Yes, you added it as an experiment, but to me that doesn’t change much, experiments are meant to be shipped at some point, and as far as I can see, the PR would replace all block/patterns previews when the flag is removed. With it being an official experiment, it adds much more intention to do that.
    * I’m also not sure if it should be an experiment? Who are you planning to tell to enable and test this experiment? What is the difference between this and a Playground link?
* I’m investigating performance issues with this particular flow and modal this week. I have tried other pattern previews and they weren’t as slow as this modal, and I’ve only been aware of this one since yesterday. I would like to have the chance to improve the performance of the editor and blocks used so we can compare between this and improved previews without the performance bugs, and with a test to verify.
* If the primary goal is performance, I would love to see a performance test. I’m actually making one now to compare the performance with trunk and my future PRs for improving this.
* If the primary goal is to make previewing easier outside the editor rather than making previewing inside the editor faster, can we remove it from the block preview component? As much as this enables testing for the static block previews, it also disables testing for the dynamic block preview if this gets enabled (which is what I mean when I say that we’re sweeping issues under the rug).
* All in all, I feel like this is a pretty big shift and I would appreciate more opinions before merging.

2024-02-06 11:17 UTC, draganescu commented
@ellatrix where do we have these guidelines about what merging an experiment means?

What is it that holds anyone back from improving the client side rendering by working on any branch with this experiment turned off?

How would we test the server rendering experiment without a use case to see how it behaves?

2024-02-06 13:33 UTC, ellatrix commented
I don't know if there are any guidelines for experiments. But I think it would be good to know what the plan is for the experiment. Is it just for GB contributors to try, or GB plugin users?

> How would we test the server rendering experiment without a use case to see how it behaves?

But what are the use cases where it's valuable outside the editor? If that's the primary purpose, could we test with those use cases instead?

All I'm asking here is some more time to investigate, think about it, discuss etc. If it's not for 6.5, there's no need to rush it?

2024-02-09 11:12 UTC, scruffian commented
>  If it's not for 6.5, there's no need to rush it?

Absolutely no need to rush :)

2024-03-01 19:16 UTC, scruffian commented
Closing this as we're not convinced it is useful.

2024-03-01 19:16 UTC, closed without merging

2024-03-01 19:23 UTC, fabiankaegy commented
@scruffian Are you able to point me to where the usefullness of this was discussed? I know @ellatrix had shared concerns but I'd love to figure out what the final rational / resolution of this is :)

2024-03-01 19:59 UTC, scruffian commented
I discussed it in person with @draganescu and @ellatrix, but I'm happy to give an overview of our thinking...

Static block previews could improve rendering speeds in both
1. The BlockPreview component in the editor
2. Pattern previews in the frontend.

For the first of these, we aren't convinced that this approach will ever be more efficient than the current approach because it relies on an API request. Instead we would rather put more effort into speeding up the BlockPreview component by removing more unnecessary processes from it.

For the second, we aren't convinced that Gutenberg is the right place to work on this. The code in this PR could still be valuable to provide static block previews in a plugin, but we couldn't see a use case for this in core.

I hope that is clear. Happy to answer more questions.

2024-03-01 20:07 UTC, fabiankaegy commented
Thanks for adding this :) 

I think there is a ton of value in having the reasons of why something was abandoned / decided documented for our future selves so we can remember / evaluate against that. So I really appreciate you adding those details :)

2024-03-01 20:38 UTC, scruffian commented
Thanks for pushing me to elaborate :)