Font Library: Replace manage fonts icon with button with visible text
WordPress/gutenberg pull request #58158
Opened 2024-01-24 05:04 UTC by t-hamano

Fixes #58082

## What?

## Why?

## How?

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast

2024-01-24 08:26 UTC, jasmussen requested changes
Thank you for the PR. I don't agree with the original issue. We use icon buttons to manage prominence across the UI, and in this case, clicking any single font in the list below opens the manage dialog, so the prominence is intentional.

There's a text-labels only toggle in preferences, this can potentially be a space for text-label changes.

2024-01-25 07:03 UTC, t-hamano commented
@jasmussen Thank you for your feedback. If we want to improve this font panel, what do you think is the best approach? If we want to keep the icon, I think one way is to change it to a cog icon, as mentioned in [this comment](https://github.com/WordPress/gutenberg/issues/58082#issuecomment-1905278157).

2024-01-25 07:51 UTC, jasmussen commented
I think there's potential to refine the Aa icon itself to better represent typography, but the cog icon is already widely used. We could potentially replace it with a plus, or an ellipsis. The thing is, once you have fonts, the management stuff is secondary (or even tertiary) in importance.

What we can do is add this button when there are no fonts installed, like so:

<img width="1200" alt="Add fonts from scratch" src="https://github.com/WordPress/gutenberg/assets/1204802/7fc62089-d7ef-4262-8b1c-c3ad1de5db91">

2024-01-27 05:47 UTC, t-hamano commented
My concern is that this icon itself does not represent an actual function, and people might not even notice that it is a button and is clickable. For example, what about `edit` icon instead of `cog`?

![image](https://github.com/WordPress/gutenberg/assets/54422211/38e7b7dd-81b8-4f83-b9e2-72a50d36c95d)

2024-01-29 08:39 UTC, afercia commented
> I think there's potential to refine the Aa icon itself to better represent typography,

I don't agree with this design feedback. It's not just the icon meaning. It's the proliferation of icon buttons all overl in the user interface that doesn;t add great value and instead makes things more confusing.

From an accessibility perspective, the accessibility team reported several times that icons do have ienherent problems and their usage should be limited, or accompanied with text. Keeping dismissing the feedback provided by the accessibility team and insistning on using only icons isn't hte best 

Lastly, users from the FSE Outreach Program are already reporting they can't find a way to open the 'Manage all fonts' modal, see https://github.com/WordPress/gutenberg/issues/55179
I'm not sure ignoring users' feedback is the best way to make the user interface more usable.

To me, the changes in this PR make perfectly sense and I'm all for it.

I'd also like to see ane stablished pattern for all the buttons that open a modal sialog.

2024-01-29 08:47 UTC, afercia commented
> We use icon buttons to manage prominence across the UI, and in this case, clicking any single font in the list below opens 
the manage dialog, so the prominence is intentional.

I would like to add my thoughts on this part.

> clicking any single font in the list below opens the manage dialog

Yes, but it opens the modal dialog sub-view with the fonts details. This is very confusing as the only way for users to understand they are in a 'sub view' is the small chevron left icon to go back. I'm not sure this is an ideal design in the first place.

> so the prominence is intentional

Is the intent to make the 'manage all fonts' Aa icon _less_ prominent and make the single font buttons _more_ prominent so to induce users to click on the font details? Then I'd argue the 'Manage all fonts' should be _last_ in the list. 
How is this different from other logical hierarchy already in use in the editor? We do have list of templates, ad list of patterns thtat are followed by a 'manage all' byutton. The mental model established in those cases should be adopted here as well, for consistency and to reduce cognitive load.

2024-01-29 09:20 UTC, afercia commented
> What we can do is add this button when there are no fonts installed

I agree when there's no font installed, the current UI provides very little clarity on how to add fonts. Screenshot:

![Screenshot 2024-01-29 at 10 05 10](https://github.com/WordPress/gutenberg/assets/1682452/0a697988-f174-450e-ab0f-a8c295fcd90f)

Also, when opening the modal dialog the 'Library' tabpanel is of course empty. No content at all. As a user I would be confused and feel like it's a dead end. I'd have to explore the content of the other tabs to understand what I can do in this odal dialog. I'd think that either the 'Library' panel should not be rendered at all when there's no fonts installed or, better, some introductory / eplanatory short text should be added. Screenshot of the empty Library. Screenshot:

![Screenshot 2024-01-29 at 10 05 32](https://github.com/WordPress/gutenberg/assets/1682452/307608ce-a72a-4a5a-b094-6127cfdd5c06)

Re: The mokup proposed above for the 'no fonts' case:

<img width="332" alt="no fonts mockup" src="https://github.com/WordPress/gutenberg/assets/1682452/14b01544-0185-44bf-b52f-d5dee2773221">

- The 'Add fonts' button with visible text makes things very clear for all users. I'd be all for it.
- However, both the `Aa` icon button and the text 'No fonts installed' would be redundant in this scenario:
  - The `Aa` icon button just replicates the 'Add fonts' button functionality.
  - The text 'No fonts installed' is of little use because it is already clear there's no font, otherwise there wouldn't be an 'Add fonts' button.
  - I'm not sure adding the 'Add fonts' button and then making it disappear after some fonts are installed would cprovide good affordance. Controls that disappeaer contribute to make the UI confusing and don't help with predictability. Rather, I'd keep the button and change the text to 'Manage all fonts'.

2024-01-29 19:59 UTC, earnjam commented
> Thank you for the PR. I don't agree with the original issue. We use icon buttons to manage prominence across the UI, and in this case, clicking any single font in the list below opens the manage dialog, so the prominence is intentional.

@jasmussen I hope that you mean that your disagreement is with the specific approach of that solution, not with the underlying problem. 

#55179 identifies that there is a very real, valid discovery problem with the `Aa` icon serving as the sole mechanism for managing fonts. @afercia opened #58082 as a specific issue that would help alleviate the problem. 

One could argue that would be better as a PR and not a distinct issue, but his two follow-up comments ([1](https://github.com/WordPress/gutenberg/issues/58082#issuecomment-1905648219), [2](https://github.com/WordPress/gutenberg/issues/58082#issuecomment-1904264654)) on that issue actually surfaced a more core underlying problem—the inconsistency of what these icons mean and do. Your position that the "prominence is intentional" is irrelevant. Just because something is intentional does not mean it is intuitive. 

I'd suggest it might make more sense to move discussion away from this PR (and also out from #58082), over to the originally reported problem in #55179 to talk about possible solutions. This might help prevent conflating a single solution with the more broad/overarching problem.

2024-01-30 00:33 UTC, richtabor commented
How about the settings icon that we use in other controls? This aligns with other controls. 

https://github.com/WordPress/gutenberg/assets/1813435/e2366c07-5e16-48cb-8c1c-d2f696de221f

We could potentially use the + for when there are no fonts, though that's likely closer to an edge case.

2024-01-30 00:34 UTC, richtabor commented
> I'd think that either the 'Library' panel should not be rendered at all when there's no fonts installed or, better, some introductory / eplanatory short text should be added.

Dialog about what this is and how to use it would be helpful.

2024-01-30 00:35 UTC, richtabor commented
> It's the proliferation of icon buttons all overl in the user interface that doesn;t add great value and instead makes things more confusing.

Icons are fine—if they're consistently applied. Why I'm suggesting the settings icon that we use in the same placement for other controls.

2024-01-30 02:28 UTC, t-hamano commented
Thank you everyone for your opinions. This issue is also discussed in #58082 and #55179. It might be a good idea to freeze this PR and continue the discussion on the first issue, #55179.

2024-02-02 02:10 UTC, t-hamano commented
It looks like #58580 has been merged, so I'm closing this PR.

2024-02-02 02:10 UTC, closed without merging