Move zoom out into PreviewDropdown
WordPress/gutenberg pull request #58202
Opened 2024-01-24 15:35 UTC by richtabor

## What?

Related to https://github.com/WordPress/gutenberg/pull/56806, moving the standalone zoom control into the PreviewDropdown. This aligns the display and zoom tools into one area, as they are directly related. 

Previously, invoking zoom would hide the preview device controls (as the zoom UI was separate from the preview UI). With this change we don't need to get smart on that front; just include the like actions in the same area. 

I am curious if we need to have this behind an experimental flag, not that it's much more integrated into the existing UI — rather than appended at the top of the toolbar. Sure, there are further refinements that the zoomed out view may hold, but it's nice to be able to see more of a page all at once. 

## How?

## Testing Instructions

1.  Turn on the zoom experiment.
2. Open a post or page.
3. Open the PreviewDropdown.
4. Try activating the various preview options. 
5. Do the same in the site editor. 
6. Ensure the changes are not reflected when the experiment is off. 

## Screenshots or screencast 

https://github.com/WordPress/gutenberg/assets/1813435/459f09c7-b4bd-48f3-b8df-70cb356401d4

## Follow-up
1. I set this zoom percentage to 50%, but it would be nice to have a "Zoom to fit" control, which would zoom out enough so you can see the entire page. 

2. With that fit control in mind alongside 50%, we may need to be more clear about zooming back to 100%, like below. Although "Zoom to 100%" and "Desktop" have the same behavior. cc @WordPress/gutenberg-design.

![CleanShot 2024-01-24 at 10 33 31](https://github.com/WordPress/gutenberg/assets/1813435/e597e483-cd8d-4db9-8679-605ed596f425)

2024-01-25 10:21 UTC, jasmussen commented
Oh, nice one, that's interesting! Here's a GIF of what I observe:

![zoom](https://github.com/WordPress/gutenberg/assets/1204802/3bb66d8f-c867-4052-ba4a-851d7e984fe6)

Specifically I click in that GIF the preview dropdown, where a 50% zoom exists, which I then toggle on to zoom out, and off, to zoom back in. This is a little different from what you note in the post, maybe I had some errors in compiling the branch, let me know, but if we do move the controls in here, I'd have both 100% and 50% zoom, so one is always checked. 

One curiosity is that the zoom out in this branch is mutually exclusive with the Desktop/Tablet/Mobile previews. That's actually what gives me a little pause here, if the zoom control is meant to be explicit, something user invokeable, and live there, then either it should be _one_ dropdown group so it's clear that they are mutually exclusive, or they should stack, i.e. I can see Tablet at 50%. The latter isn't that useful, but the former is a bit confusing.

If we do want user control of zoom levels, another option is to add a control in the breadcrumb footer bar, a tiny stepped slider, or just a dropdown that shows `Zoom: 100% ▾`, that's also a common place for such controls. I don't love that idea because it buries the feature. 

Another option is to tie it to an edit mode. It isn't clear how useful this is when you're just writing a post or page building, but when you're building with sections, inserting top-level patterns, it's very useful. I think I've seen separate mockups (from you?) where this mode gets automatically invoked when you press the pattern tab in the inserter, changig the editing mode of the canvas to reveal top-level sibling inserters for pattern placement. That feels like a fluid way to invoke the zoom contextually; does the user need more zoom level control here?

2024-01-29 18:13 UTC, richtabor commented
@jasmussen I pushed up changes to make zoom stack with device previews, like this: 

https://github.com/WordPress/gutenberg/assets/1813435/9b68879f-478d-4e7e-a7d0-9519ff4ddfeb

What do you think?

2024-01-29 18:16 UTC, richtabor commented
> Another option is to tie it to an edit mode. It isn't clear how useful this is when you're just writing a post or page building, but when you're building with sections, inserting top-level patterns, it's very useful. I think I've seen separate mockups (from you?) where this mode gets automatically invoked when you press the pattern tab in the inserter, changig the editing mode of the canvas to reveal top-level sibling inserters for pattern placement. That feels like a fluid way to invoke the zoom contextually; does the user need more zoom level control here?

Yes, I think we'll invoke the zoom-out mode in areas where it makes sense to do, like how it's done in when previewing styles. But I do think it's a nice-to-have to zoom out and see a whole page's design. We do it in Figma all the time, to take a birds-eye view and make sure elements are cohesive, aligned properly, etc. 

I do like having it in the existing device preview control—even stacked with preview. It's a relative control and feels expected.

2024-01-30 09:11 UTC, jasmussen commented
I think it might work, when stacked. Not entirely sure how useful it is, but if it can directly tie into any how the style variation zooming and any future assembler or site-view related zooming might work (same componentry etc), then it might be okay?

I think my main concern is putting it in that dropdown. I still have this idea that the preview dropdown can potentially hold extensibility for plugins there, such as "view with paywall" or "view with premium" or other things. Those might still all stack, but it could also become a long list. Maybe that shouldn't block this, but pertinent for the thought process perhaps.

2024-02-08 18:57 UTC, richtabor commented
Made some changes based on feedback: 

- Removed "stacking" of zoom + device previews. 
- 50% (zoom-out mode) is only available when in desktop view. 

Thoughts @WordPress/gutenberg-design @mtias?


https://github.com/WordPress/gutenberg/assets/1813435/d274d99a-c5d7-4e9a-91fb-7b290a0bfaf4

2024-02-08 19:01 UTC, richtabor commented
We do need to omit this from the post editor, or add zooming there (which I presume is a bigger lift).

2024-02-21 11:39 UTC, paaljoachim commented
This looks good @richtabor Rich!

What about just clicking twice on the 50% zoom? 
First click to activate.
Second click to deactivate.
Removing the 100% option.

EDIT: The reason why I say this is that we have for instance List View. Click once to open and click again to close. The same goes for other things that can be pressed. Once to activate/open and once to deactivate/close.

2024-02-21 11:51 UTC, scruffian submitted a review, later dismissed
This is looking good. I think we should bring it in and see how users respond.

2024-02-21 11:56 UTC, jasmussen commented
Let's not merge this quite yet, there are some aspects around the zoom out experiment that I think we need to figure out in a more holistic way. This PR can be part of that, but let's hold off on merging until the view is clearer.

2024-02-21 13:48 UTC, youknowriad commented
@jasmussen I'm not really sure why we should hold this PR. It feels like an improvement to me over the weird button we have in trunk. It's still an experiment though but it makes the current experiment a bit better.

2024-02-21 13:49 UTC, getdave commented
> Let's not merge this quite yet, there are some aspects around the zoom out experiment that I think we need to figure out in a more holistic way. This PR can be part of that, but let's hold off on merging until the view is clearer.

I'm curious - why we can't merge this as it's under an experiment? We don't know the full scope of the project but that would seem ok in this context. Can you help me to understand? Thanks.

2024-02-21 14:00 UTC, jasmussen commented
Oh I thought it took it out of the experiment. If it remains as an experiment, that's seems okay.

My personal concern is that we are adding both granularity and promincence to a tool that I'm not personally sure will be that useful in practice. The existing experiment let us test a generally zoomed out view, but in practice it hasn't felt that useful. I always saw the evolution to be _less promince and less granularity_ by being invoked by doing another action, such as opening the Patterns section, or invoking a "receded view" through another action. I.e. it could be tied to select mode. But never anything explicit like it is in Google Docs or otherwise. Just zooming out, as a separate affordance, just feels like another tool that doesn't have a clear utility.

2024-02-21 14:34 UTC, anton-vlasenko commented
## Test Report
### This report validates that the PR addresses the issue.

Patch tested: https://github.com/WordPress/gutenberg/pull/58202,

### Environment
- WordPress: 6.5-beta2-57671-src
- PHP: 7.4.33
- Server: Apache/2.4.58 (Unix) PHP/7.4.33
- Database: mysqli (Server: 5.7.42 / Client: mysqlnd 7.4.33)
- Browser: Safari 17.3.1 (macOS)
- Theme: Twenty Twenty-One 2.1
- MU-Plugins: None activated
- Plugins:
  * Gutenberg 17.7.0

### Actual results
- ✅ Changes are reverted when the zoom experiment option is disabled for posts.
- ✅ Changes are reverted when the zoom experiment option is disabled for pages.
- ✅ Preview options function correctly in various preview modes for both pages and posts.

2024-02-21 14:57 UTC, getdave commented
@jasmussen ah yes it's still an experiment. Perhaps @richtabor is best placed to advise on the utility of the PR but I'm still inclined to merge it and iterate within the context of the experiment.

2024-02-21 15:14 UTC, youknowriad commented
we actually discussed some of this with @mtias and it seems that we might want both:

 - Invoking zoom-out automatically in some situations like pattern inserter, styles...
 - Manually trigger it on demand.

2024-02-21 15:49 UTC, getdave approved these changes
🚀 Merge and iterate

2024-02-27 20:27 UTC, annezazu commented
Just quick feedback that I think conflating both zooming in/out on your content with a preview of what the content looks like on different devices is quite confusing. I don't think they are the same mental models at all. For zoomed out mode, I'm trying to see more of my content and interact at a higher level with patterns (in the future). For previewing, I'm simply trying to get a sense of how my site will look on different devices. Having these exist alongside each other doesn't seem to provide value but feels like it's more surfacing complexity. 

To be clear, I'm all for both controls -- just not intermingled with each other.

2024-04-22 17:01 UTC, scruffian requested changes, later dismissed
When I am in zoomed out view and i open the device preview, zoom out mode closes.

2024-06-17 22:57 UTC, stokesman commented
It’s neat to see this. It’s a very good vein to explore. Along these lines, my wish is that device previews engage zoom-to-fit behavior when their dimensions are greater than what’s available in the interface. Currently, it causes overflow in the content area and I think it'd be nicer to just scale to fit (just like browser dev tools does when selecting a device with greater dimensions then the window).

2024-07-29 08:03 UTC, scruffian commented
Closing in favour of https://github.com/WordPress/gutenberg/pull/63870

2024-07-29 08:03 UTC, closed without merging