Add visible text to the Gallery add item button
WordPress/gutenberg pull request #5824
Opened 2018-03-27 16:59 UTC by afercia

This PR adds a visible `Upload Image` text to the Gallery add item button that was previously completely unlabeled. For more details please refer to the related issue #5823 

Screenshots:

![screen shot 2018-03-27 at 18 30 07](https://user-images.githubusercontent.com/1682452/37982410-c7916a94-31f0-11e8-9ac6-85dd0ba830f2.jpg)

![screen shot 2018-03-27 at 18 30 49](https://user-images.githubusercontent.com/1682452/37982411-c7aeeda8-31f0-11e8-8aad-f1cf1b499c6f.jpg)

Fixes #5823

2018-03-27 17:25 UTC, aduth requested changes
The styling doesn't look vertically aligned quite right.

![No Flex](https://user-images.githubusercontent.com/1779930/37983724-3b4755f4-31c2-11e8-9685-6184562f3b8e.png)

Instead of setting hard-coded values, I think we can leverage Flex to center the items, also without the intermediary `.blocks-gallery-add-item-label` element.

This styling on the `.blocks-gallery-add-item-button` button wrapper seems to work well for me:

```css
display: flex;
flex-direction: column;
justify-content: center;
```

![Yes Flex](https://user-images.githubusercontent.com/1779930/37983808-7fb39414-31c2-11e8-8c5b-97708013310f.png)

2018-03-27 17:38 UTC, karmatosed commented
This seems like a good improvement a few points:
- Let's sort out the spacing top/bottom
- Let's use the same font as we use in buttons and actions over the body

![2018-03-27 at 18 38](https://user-images.githubusercontent.com/253067/37984393-1213d78a-31ee-11e8-95d2-67bf7941b374.png)

2018-03-27 22:11 UTC, afercia commented
Thanks @aduth @karmatosed. My initial try was to keep the "plus" in the same exact position as before. To clarify, see below: before and after

<img width="665" alt="screen shot 2018-03-27 at 23 44 45" src="https://user-images.githubusercontent.com/1682452/37997151-6484699a-321a-11e8-9a13-33af0c2388c3.png">

But that's more a design decision so definitely up to you. Updated to use flexbox, so now the plus and text are centered vertically.

Worth noting flexbox on buttons _was_ broken in Edge and still partially buggy in Firefox. I seemed to recall two bugs we've faced (and fighted against) about buttons at the company I work for, see:
https://github.com/philipwalton/flexbugs#flexbug-3
https://github.com/philipwalton/flexbugs#flexbug-9

I've tested the flexbox approach in IE11 and Edge and seems to work. Bug # 3 was fixed in Edge. Bug # 9 is not relevant in Firefox just because the vertical centering is the default for buttons. However, if you alter the `justify-content`, say to `flex-start`, it still doesn't have any effect on Firefox.

Worth reminding the gallery layout is broken in IE11, see https://github.com/WordPress/gutenberg/issues/5504, and I wouldn't be surprised if the root cause is a bit too much enthusiasm in using flexbox.

> Let's use the same font as we use in buttons and actions over the body

The button already uses the default font for buttons, which is the stack of system fonts. I'm sorry I have no idea what `actions over the body` are 🙂

2018-03-28 10:05 UTC, afercia commented
To recap: current rendering (also to compare the font used for buttons):

![screen shot 2018-03-28 at 12 03 23](https://user-images.githubusercontent.com/1682452/38022578-2f394826-3280-11e8-9031-67fe743335b9.png)

2018-03-28 11:35 UTC, karmatosed approved these changes

2018-03-28 11:36 UTC, karmatosed commented
Approving based on design but the 'Image' should be lowercase to fit in a sentence. Once that's done @afercia, we can ship this thanks.

2018-03-28 12:33 UTC, aduth approved these changes
Code-wise looks good 👍 

Though we should probably come to a common solution if we want buttons to have a consistent font family, even those within the editor content. Maybe applied as a button style in [`.edit-post-visual-editor`](https://github.com/WordPress/gutenberg/blob/464b8c6a54f5af978f443a52749a1f8d8399ebe3/edit-post/components/visual-editor/style.scss#L1-L25)?

Aside: For good measure with regard to the Flex bugs, I tested in Chrome, Firefox, Safari (OSX) and Edge, IE11 (Windows). All appears well, aside from some unrelated vertical stretching of gallery images in IE11.

2018-03-28 18:21 UTC, afercia commented
> Maybe applied as a button style in `.edit-post-visual-editor`?

Makes sense to me since `Noto Serif` is set there. Let's try it.

2018-03-28 18:42 UTC, merged