Font Library: Fix focus loss when update/install button is pressed
WordPress/gutenberg pull request #58364
Opened 2024-01-29 04:05 UTC by t-hamano

## What?

## Why?

## How?

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast

2024-01-29 08:07 UTC, afercia approved these changes
Looks good to me.

2024-01-29 08:12 UTC, afercia commented
> the footer itself is not displayed when no font is selected to be installed. This PR displays the footer even when no font is selected and renders an inactive button.

@t-hamano nice addition, thank you. 

- updating fonts does not notify the screen reader
- focus is also lost when the font is removed

Are these two bugs already tracked in other GitHub issues?

2024-01-29 08:21 UTC, t-hamano commented
@afercia Thanks for the review!

> - updating fonts does not notify the screen reader
> - focus is also lost when the font is removed
> 
> Are these two bugs already tracked in other GitHub issues?

As far as I know, it hasn't been reported anywhere yet. I plan to submit both problems as issues later.

2024-01-29 08:23 UTC, afercia requested changes
Sorry I spoke too soon.
We also need to noop the buttons when they are aria-disabled. The pattern to use is similar to the one used for many other buttons e.g. the Save button. something like 
`onClick={ (condition to disable the button) ? undefined : callback }`

2024-01-29 08:24 UTC, afercia commented on packages/edit-site/src/components/global-styles/font-library-modal/font-collection.js
>  				onClick={ handleInstall }
The button should be noop'ed when `isDisabled || isInstalling`

2024-01-29 08:24 UTC, afercia commented on packages/edit-site/src/components/global-styles/font-library-modal/installed-fonts.js
>  				onClick={ saveFontFamilies }
The button should be noop'ed when `! fontFamiliesHasChanges`

2024-01-29 08:26 UTC, t-hamano commented
> We also need to noop the buttons when they are aria-disabled. The pattern to use is similar to the one used for many other buttons e.g. the Save button. something like

Yes, I just noticed that too, so I updated it 😅

2024-01-29 08:32 UTC, t-hamano commented
Oops, I noticed that the following issue has already been reported.

> - updating fonts does not notify the screen reader

- #54601

> - focus is also lost when the font is removed

- #58314

2024-01-30 11:13 UTC, afercia approved these changes
Changes look good to me 🎉 
Unrelated test is failing, will restart the job to see it everything is green,

2024-01-30 11:17 UTC, t-hamano commented
@afercia Thanks for the review!

As seen in [this comment](https://wordpress.slack.com/archives/C02RQC4LY/p1706517911581429) on slack, it seems that the test failure also occurred on trunk. This problem is now resolved, so I merged the trunk again. All tests should now pass.

2024-01-30 11:19 UTC, afercia commented
Thanks @t-hamano. Yes Inoticed other PRs failing today and I rebased them. I think the preferred flow in this project is to _rebase_ on top of trunk and not merge?

2024-01-30 11:29 UTC, t-hamano commented
I don't think there is a strict rule as to whether we should use merge or rebase. It seems that different people prefer different things.

Personally, when I want to import trunk changes, I follow the following rules:

- Use "rebase" if no one has reviewed it yet
- Use "merge" if there are already comments or reviews.

If I already have a comment tree hanging in a PR, I feel like a force push will interrupt that timeline.

However, Gutenberg uses [squash merge](https://learn.microsoft.com/en-us/azure/devops/repos/git/merging-with-squash?view=azure-devops#squash-merge) by default, so no matter how many commits are made to one PR, they will be aggregated into one commit in the trunk.

So in the end, I think either one is fine 👍

2024-01-30 11:31 UTC, afercia commented
> However, Gutenberg uses squash merge

Right, thanks.

2024-01-30 12:23 UTC, merged

2024-01-31 15:17 UTC, ciampo commented
Thank you @t-hamano for working on this!

As a small follow-up, would you mind using the `Button`'s APIs instead?

Instead of using `aria-disabled`, you should be able to get the same behavior by using the `disabled` prop (like before), and adding the `__experimentalIsFocusable` prop too. Thank you 🙏

2024-01-31 15:24 UTC, t-hamano commented
> As a small follow-up, would you mind using the `Button`'s APIs instead?

All right 👍