Update/multi block mover
WordPress/gutenberg pull request #5864
Opened 2018-03-28 23:25 UTC by dom-o

## Description
Fixes #5752 

## How Has This Been Tested?
Manually tested;  didn't find any regressions.
Ran npm test and all still pass.

![move_top_up](https://user-images.githubusercontent.com/5658814/38061461-448877aa-32bd-11e8-9f1e-e3d36cd010d6.JPG)

![move_bottom_down](https://user-images.githubusercontent.com/5658814/38061470-59719ebc-32bd-11e8-817e-b874037da191.JPG)

## Types of changes
Multi-selected block mover buttons are disabled when blocks are at the top/bottom; aria-labels are set accordingly.

2018-03-28 23:47 UTC, aduth requested changes
`BlockListBlock`, the parent component which renders this one, already has `isFirst` and `isLast` props. It also renders a `<BlockMover />` of its own for singular selection, and `<BlockListMultiControls />` for a multi-selection. Seems we could just pass those from there instead of calculating it again here?

https://github.com/WordPress/gutenberg/blob/3e56452edb142e5bb72cf5bf025b7afe9d441e78/editor/components/block-list/block.js#L408-L409

https://github.com/WordPress/gutenberg/blob/3e56452edb142e5bb72cf5bf025b7afe9d441e78/editor/components/block-list/block.js#L518

**Edit:** Actually, this will work for `isFirst`, but since the movers are only rendered for the first block in a multi-selection, it won't know if the extent of its multi-selection is the end of the block list. So we may still need `connect` to provide this information. It could be provided as `isLast` direct from `connect` (where `lastIndex + 1 === blockCount` occurs in the `connect` function).

...or, maybe the fact that the source of these props would become disjointed this way could be good justification for the approach as you have proposed, since it's all relatively well-contained, even if we are repeating some information already available from the direct parent of the multi-controls.

Thoughts? 😄

2018-03-29 00:16 UTC, dom-o commented
I originally looked into passing from `BlockListBlock`, but the separate sources did feel a little weird. I'm not married to it either way; both would work. Providing them straight from `connect `is good though.

2018-03-30 15:14 UTC, aduth approved these changes
Looks great, thanks 👍 

Aside: It's more of an issue with nested blocks and their layouts (one which is not easy to solve), but down/up arrow will still be shown for multi-selection of a complete first/last column.

![image](https://user-images.githubusercontent.com/1779930/38142727-7df61552-340b-11e8-9435-fefe60db4468.png)

2018-03-30 15:14 UTC, aduth commented on editor/components/block-list/multi-controls.js
> +	const firstIndex = getBlockIndex( state, first( uids ), rootUID );
Alternatively, we could use `getFirstMultiSelectedBlockUid` and `getLastMultiSelectedBlockUid`, but this isn't very complex logic, so seems reasonable enough.

2018-03-30 15:14 UTC, merged