getDirectInsertBlock: Remove 'directInsert' as a callback handler
WordPress/gutenberg pull request #59172
Opened 2024-02-19 11:50 UTC by Mamaduka

## What?
PR removes support for the `directInsert` callback value in `getDirectInsertBlock`.

## Why?
The logic was introduced as part of initial experiment #34899 but hasn't been used in the core for a while. The setting became a boolean after the stabilization. See #52083.

The block edit components are better suited to derive similar setting values based on the state and context.

## Testing Instructions
1. Open a post or page.
2. Insert a Buttons block.
3. Add a few buttons.
4. Confirm you can directly insert new button blocks using an in-between inserter.

### Testing Instructions for Keyboard
Same.

2024-02-19 12:12 UTC, Mamaduka commented
cc @sethrubenstein

2024-02-21 23:48 UTC, noisysocks requested changes, later dismissed
Tests well, thanks for the nice cleanup.

There's a JSDoc here that needs updating:

https://github.com/WordPress/gutenberg/blob/cab4b280913b0fe6d15e24ee052cd5a94526687d/packages/block-editor/src/components/inner-blocks/use-nested-settings-update.js#L40

Since `InnerBlocks` is a public API this is technically a breaking change.

I can't find any usage of the API in wpdirectory.net and it was only ever documented via the `useNestedSettingsUpdate` JSDoc which is pretty obscure so I think it's acceptable to output a `deprecated()` warning in `useNestedSettingsUpdate` and no longer support the behaviour.

2024-02-22 11:54 UTC, Mamaduka commented
@noisysocks, I added the deprecation notice.

## Screenshot
![CleanShot 2024-02-22 at 15 51 12](https://github.com/WordPress/gutenberg/assets/240569/2707f175-de82-4aae-863f-48df7f1878af)

2024-02-26 11:48 UTC, jsnajdr approved these changes
:+1:

2024-02-26 14:36 UTC, merged