Remove scrolling of empty image blocks.
WordPress/gutenberg pull request #59305
Opened 2024-02-23 08:00 UTC by torounit

## What?

Remove scrolling of empty image blocks.

## Why?

Fix #59226.

## How?

Show `.components-placeholder__fieldset` only `is-selected`.

## Testing Instructions

It seems easiest to produce with the 'Team members' pattern that's included with WordPress 6.4/6.5 by default.

1. Insert that pattern
2. Resize the viewport until the scrollbars appear

### Testing Instructions for Keyboard

## Screenshots or screencast 

![スクリーンショット 2024-02-23 16 59 52](https://github.com/WordPress/gutenberg/assets/1908815/baeea448-b85f-44e3-9b2b-708b348817fd)

2024-02-23 08:08 UTC, fabiankaegy requested changes
Thank you for working on this! 

Whilst the solution you added here works, it is too broadly applied. Currently this style update here applies to all instances of the Placeholder component. Which is used by many blocks in many instances. 

Instead of making this change here in the placeholder component CSS this should be done in the `editor.css` file of the imabe block scoped to only apply to the placeholder nested inside an image block

2024-02-23 08:30 UTC, torounit commented
@fabiankaegy Thank you for reviewing! 

Fixed to be controlled by editor.css in the image block.

2024-02-23 09:34 UTC, fabiankaegy approved these changes
This now works as expected :) thanks!

2024-02-23 12:42 UTC, merged

2024-03-14 08:05 UTC, jasmussen commented
I believe this PR caused a regression, so that the image block now features a layout shift when selected. Before this PR:

![before](https://github.com/WordPress/gutenberg/assets/1204802/2f49ff3f-5aff-4c38-83d4-2a1c3a731e0b)

After:

![after](https://github.com/WordPress/gutenberg/assets/1204802/98be9640-3abc-44c0-aa34-8ee136cc7afe)

I'll see if I can spin up a PR.

2024-03-14 08:18 UTC, jasmussen commented
Alternative fix here: https://github.com/WordPress/gutenberg/pull/59857