Adds import statement to code usage example
WordPress/gutenberg pull request #59327
Opened 2024-02-23 19:01 UTC by bacoords

## What?

This is a minor documentation change to add the `import` statement to the code example. This seems to be a consistent pattern. Examples from other packages:

- https://developer.wordpress.org/block-editor/reference-guides/packages/packages-i18n/
- https://developer.wordpress.org/block-editor/reference-guides/packages/packages-autop/

## Why?

Added for consistency and because import statements in the example code can be  helpful for newer developers.

2024-02-24 01:48 UTC, t-hamano requested changes
Nice catch 👍

2024-02-24 01:50 UTC, t-hamano commented
This documentation is auto-generated from JSDoc. Therefore, you need to update the following locations:

https://github.com/WordPress/gutenberg/blob/593fd6455a16c2e6adeeb07db8ff4d06f76ddb6a/packages/html-entities/src/index.js#L9-L14

Then run `docs:build` to regenerate the documentation. It's also a good idea to use single quotes instead of double quotes.

2024-02-27 00:18 UTC, bacoords commented
Makes sense about the auto-generation. Thanks @t-hamano for explaining how to commit here- I've pushed an update.

2024-02-27 01:38 UTC, t-hamano approved these changes
LGTM! I'm a little concerned that the GitHub action related to backporting PHP is failing, but this PR does not make any changes to PHP files, and this GitHub action is optional. Therefore, I will merge this PR 👍

2024-02-27 01:40 UTC, merged