Rich text: fix typing into empty flex element
WordPress/gutenberg pull request #59473
Opened 2024-02-29 16:34 UTC by ellatrix

## What?

Fixes #59192.

## Why?

Fixes #59192.

## How?

Input goes inside the placeholder when the wrapper element has display flex. We can fix that by considering any text inside the placeholder element to be content.

Create an empty paragraph and set display to flex. Typing inside it should work.

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast

2024-02-29 16:59 UTC, fabiankaegy commented
@getdave @youknowriad @annezazu @colorful-tones How do you all feel about including this in 6.5? It is a bug fix of something that has been broken for a while but I think is worth including in the bugfix phase.

2024-02-29 17:01 UTC, ellatrix commented
I'm ok with that, it's a very isolated fix.

2024-02-29 20:14 UTC, annezazu commented
I'm in agreement, especially if it's an isolated fix as Ella says!

2024-02-29 21:01 UTC, colorful-tones commented
Do it. 🚀

2024-02-29 21:38 UTC, youknowriad commented
I think it's fine the change seems low impact.

2024-03-01 07:27 UTC, fabiankaegy requested changes
Hey @ellatrix 👋 

I just tested this locally and sadly can still replicate the issue. I added a video here to show what I'm seeing. 

https://github.com/WordPress/gutenberg/assets/20684594/df243242-d1c6-42ad-8751-bcdb96641fd2

2024-03-01 07:46 UTC, fabiankaegy approved these changes
Ignore my earlier message. I had a local setup issue and the build wasn't working. I can confirm this fixes the issue

2024-03-01 11:01 UTC, merged

2024-03-04 09:09 UTC, youknowriad commented
I just cherry-picked this PR to the update/packages-6.5-rc1 branch to get it included in the next release: 43b12eea88