Standardise capitalisation of the term 'navigation menu'
WordPress/gutenberg pull request #59479
Opened 2024-02-29 21:24 UTC by xhemals

## What?
Standardising the capitalisation of the term 'navigation menu'

## Why?
#59442 Mentions this is an issue with the code base. So this is to fix those inconsistencies

## How?
I have ran a replace all command within vscode to replace the outliers in.js .md and .scss and .phpfiles

2024-03-26 10:46 UTC, Mamaduka requested changes
Thanks for contributing, @xhemals!

I believe the original issue intends to standardize user-facing labels. I recommend making more targeted changes instead of searching/replacing the whole codebase.

cc @afercia

2024-03-26 10:46 UTC, Mamaduka commented on .vscode/settings.json
PRs shouldn't include user configurations. Use global git ignore to ignore files specific to your environment.

2024-03-27 07:58 UTC, afercia commented
> I believe the original issue intends to standardize user-facing labels. I recommend making more targeted changes instead of searching/replacing the whole codebase.
> 
> cc @afercia

Yes in https://github.com/WordPress/gutenberg/issues/59442 I suggested to search only within translatable strings that is thte ones that use the i18n functions.
Translatable functions in Gutenberg are `__()`, `_x()`, `_n()`, and `_nx()` so I suggested a regex to search the codebase `\( '.*navigation menu`. The syntax may vary depending on the code editor in use. See [the internationalization docs](https://github.com/WordPress/gutenberg/blob/ffc02bf54720ec95f3380d422e1cb44458e5a621/docs/how-to-guides/internationalization.md).

2024-03-27 21:14 UTC, closed without merging

2024-03-27 21:15 UTC, xhemals commented
I will re-create a new pull request with the intended changes, rather than how I did things. Apologies for the confusion