Test: Dynamically detect and set max-workers
WordPress/gutenberg pull request #59904
Opened 2024-03-15 11:58 UTC by sirreal

See:
https://jestjs.io/docs/troubleshooting#tests-are-extremely-slow-on-docker-andor-continuous-integration-ci-server

## What?

## Why?

## How?

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast

2024-03-15 13:22 UTC, sirreal commented
I'm not sure how many workers we have access to, we use a lot, but we could consider sharding the tests as well.

2024-03-18 21:01 UTC, desrosj requested changes
A few small changes, and I think this is worth merging to try out.

As for the sharding recommendation and splitting into additional jobs, I do recommend we do that as well.

As an organization, we have an allotment of 500 concurrent runners. At peak times, it's not uncommon to have jobs waiting for runner machines. I haven't done the math in at least 6 months, but my findings previously were that the majority of our workflow jobs complete in 1-2 minutes or less. So while there is an initial spike in runner allocation when a commit is made or a PR is updated, it's usually fairly brief.

Personally, the first thing I would do is split off the date tests into it's own job. While it's only 5 seconds, it makes sense to split it off since it's a separate group entirely. When they fail, it makes it more obvious which group has issues.

Looking at your observations for baseline and the results of this PR, I wouldn't be surprised if we could get this down under 2 minutes (or even 1) per runner if we shard into 2, 3, or 4 different runners. This does require more runner machines, but if they take less than 1 minute, it won't result in a meaningful delay.

2024-03-18 21:01 UTC, desrosj commented on .github/workflows/unit-test.yml
> +              uses: SimenB/github-actions-cpu-cores@v2
```suggestion
              uses: SimenB/github-actions-cpu-cores@97ba232459a8e02ff6121db9362b09661c875ab8 # v2.0.0
```
For third party actions, we should hardcode the SHA value for the version we wish to use. This is recommended in the [security hardening guidelines](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions). We use Dependabot to manage these updates automatically, so the burden of maintenance is not that great.

2024-03-18 21:01 UTC, desrosj commented on .github/workflows/unit-test.yml
> +              uses: SimenB/github-actions-cpu-cores@v2
```suggestion
              uses: SimenB/github-actions-cpu-cores@97ba232459a8e02ff6121db9362b09661c875ab8 # v2.0.0
```

2024-03-19 09:31 UTC, sirreal commented
Thanks for the review and thoughts, @desrosj! I've applied your suggestion to pin the action to the specific sha.

If you agree, I'd like to merge this PR as-is and iteratively work on other improvements.

2024-03-19 12:32 UTC, desrosj approved these changes

2024-03-19 12:33 UTC, desrosj commented
> If you agree, I'd like to merge this PR as-is and iteratively work on other improvements.

Totally! Wanted to leave that feedback here in context. But I agree. Splitting it out into a follow up PR makes the most sense.

2024-03-19 12:34 UTC, merged

2024-03-20 20:28 UTC, sirreal commented
I'll continue with some improvements discussed in #60045.