Fix the block variations transforms labeling and improve UI clarity
WordPress/gutenberg pull request #59916
Opened 2024-03-15 15:23 UTC by afercia

Fixes https://github.com/WordPress/gutenberg/issues/59898

## What?

The block varaitions in the block inspector may use 3 different components based on some conditions. All three components use less than ideal labeling. Also, the UI doesn't really make clear what the icon buttons are about.
Minor: when rendered as a dropdown button, the gap between the toggle button and the dropdwon menu is too large.

## Why?

- All settings sections in the inspector should be cleaerly identified by some visible text that clearly explains what that UI is about. Depending on the cases, these visible text can be a visual label, or a fieldseet legend, or a toggle button text (for the menu).
- The variation labels must not change dynamically. The also need to match the tooltips text.
- A dropdown menu must be 'visually connected' to its toggle button, the current gap is too large.
- I'm not sure why the variations are visually placed within the block 'carrd'. The block card is meant to contain the block name and descriptions. The variations are a separate concept. As such, they should be visually separated.

## How?

- Makes the radiogroup 'visual label' visible. The group itself is labeled via an `aria-label` that uses the same text of the visual label. This hasn't changed, it's how the component works.
- Avoids to dynamically change the button labels. The accessible bane of a control should rarely change.
- Makes the tooltips text match the accessible name.
- Reduces the gap between the menu toggle and the menu by making sure all three components the variations can be rendered with use the same wrapper, with the same padding.
- Visually separates the variations UI from the block card.
- There's now more horizontal room so the default radiogroup now shows up to _six_ variations instead of five. WHen more than 6, the component switches to a group of buttons that can wrap to multiple lines, as it is on trunk.

## Testing Instructions

- Go to the site editor and select a Group block.
- Observe the variations in the block inspector.
- Obseerve the variations are not left aligned and have a visible title 'Transform to variation'.
- Hover or focus each button and activate them. Observe the tooltiip text is always the same and doesn't change dynamically.
- Alter the [Group block variations](https://github.com/WordPress/gutenberg/blob/b6c37f383070d35af77d1aab9b9ef01df33c6d9d/packages/block-library/src/group/variations.js) and add a few more variations so that they are more than 6. Build and refresh the editor.
- Observe the variations are now normal icon buttons.
- Obseerve the variations have a visible title 'Transform to variation'.
- Hover or focus each button and observe their tooltip text matches the aria-label value.
- Alter again the variations and make at least two of them use the same icon. Build and refresh the editor.
- Observe the variations are now a dropdown menu.
- Observe hte menu toggle text is still 'Transform to variation', this hasn't changed.
- Hover of cous the menu toggle and observe there's no tooltip any longer (the tooltip was redundant as it just repeated the visible text).
- Open the menu and observe the gap between the menu toggle and the menu is now the expected one and consistend with all the other dropdown menus.

### Testing Instructions for Keyboard

## Screenshots or screencast 

Before:

![before](https://github.com/WordPress/gutenberg/assets/1682452/0307e2b1-3eeb-47ab-97d7-5581f8d5fe4c)

After:

![after](https://github.com/WordPress/gutenberg/assets/1682452/aa5ecfa4-f625-4b3a-ad64-324dd7caef97)

2024-07-12 12:18 UTC, afercia commented
Rebased on top of latest trunk and fixed a few typos in the PR description.

2024-07-12 13:00 UTC, Mamaduka commented
Thank you, @afercia! I added this to my list and will try to review it early next week.

2024-07-15 09:59 UTC, Mamaduka approved these changes
This looks good from the code perspective ✅

Pinging @WordPress/gutenberg-design for the design feedback.

P.S. Rebasing should resolve failing performance tests.

2024-07-15 10:11 UTC, jasmussen requested changes
The addition of a separator and the added spacing makes the inspector unreasonably longer, pushing downwards the primary block controls. Let's hear from others if there's a better way to solve this, that makes better use of the available space. If a better option presents itself, feel free to dismiss my review.

2024-07-16 04:09 UTC, richtabor commented
I agree with @jasmussen. Adding _more_ doesn't always equate to a more understandable interface.

2024-07-16 07:08 UTC, jarekmorawski commented
For what it's worth, here's how we solved a similar problem in the Product Collection block in WooCommerce. The dropdown uses a tertiary button style and sits in the same column as the block's description.

![Transform](https://github.com/user-attachments/assets/a735eca2-1d6f-4350-801c-758a91db1262)

2024-07-16 13:41 UTC, afercia commented
@jasmussen @richtabor thanks for your feedback.

To me, this is a valid accessibility issue. It's not clear what those buttons are because there's nothing that explains it. Any group of controls should be clearly identified, either by a visible legend of a fieldset, or a visible label, or a heading, depending on the nature of the controls.

In this case I opted for a heading. I'm glad to remove the separator or make visual adjustments based on your design feedback. It's totally okay if you don't agree on the visual design change but in that case I'm kindly asking you to provide an alternative solution to a valid issue. Just saying 'no' without providing an alternative solution isn't acceptable. Thanks.

@jarekmorawski thanks but unfortunately the tertiary buttons aren't accessible. In absence of color, they just look like text. They should be refactored but that's another issue.

2024-07-17 19:19 UTC, richtabor commented
> To me, this is a valid accessibility issue. It's not clear what those buttons are because there's nothing that explains it.

How does this differ from icons say in the top toolbar, or block toolbar?

2024-07-26 08:44 UTC, afercia commented
> The addition of a separator and the added spacing makes the inspector unreasonably longer, pushing downwards the primary block controls.

I measured the 'unreasonably'. It's about 40 pixels. See screenshot below.

I don't think 40 pixels are unreasonable. I'd appreciate some more objective feedback because stating that 40 pixels make the inspector 'unreasonably longer' doesn't sound fair to me.

Before and after:

![before and after](https://github.com/user-attachments/assets/b3dda797-e9ae-4e8b-94a9-e977e01187ea)

> How does this differ from icons say in the top toolbar, or block toolbar?

I'd be happy to add visible headings in the top toolbar and block toolbar, even though I'd think those are slightly different cases because the context helps understand what those controls are.

2024-07-27 02:04 UTC, richtabor requested changes
While I appreciate the effort, the design changes add additional complexity to the Inspector/Block Card; complexity that is not worth the perceived benefit. 

For one, the Inspector controls are further down the sidebar. 

Second, the additional label detracts from the primary intention of the Block Card: to clearly inform you of the selected block. As proposed, there is no primary intention, only two secondary: the selected block and its transforms. 

And third, with this proposal, the Styles and Settings tabs conflict visually with the transform icon buttons, as the border above makes the transform icon buttons seem like one interaction unit with the Tabs. 

The previous design, without these changes, was much more simplistic and purposeful. Once you interact with the transforms, you know what they do.

2025-07-25 06:53 UTC, Mamaduka commented
Closing this as "Stale". Let's continue the discussion in the issue.

2025-07-25 06:53 UTC, closed without merging