Update the query block to permit non-core interactive blocks
WordPress/gutenberg pull request #60006
Opened 2024-03-19 22:55 UTC by colinduwe

## What?
Allow non-core interactive blocks to be placed inside the core/query block

## Why?
With the introduction of the interactivity API, extenders are eager to use the API with the core/query block to enhance WordPress sites. This adjustment allows them to be used. This PR addresses https://github.com/WordPress/gutenberg/issues/59752

## How?
Adds a check to ensure that any non-core blocks inside the core/query block have their block.supports.interactivity property set to true.

## Testing Instructions
1. Create a new page/post with query with a post template and pagination within it. 
2. Set the query's "Force page reload" to false
3. Add a non-core block inside the query.
4. Verify that you get the modal alerting you that non-interactive plugin blocks are not allowed. "Force page reload" is enabled.
5. Add a non-core block that has block.supports.interactivity inside the query
6. Verify you can enable/disable the "Force page reload"
7. On the front end verify that the advanced pagination works as expected.

Here's a non-core block with block.supports.interactivity you can use to test this: [test static block](https://github.com/colinduwe/test-block-static/blob/main/test-block-static.zip)

https://github.com/WordPress/gutenberg/assets/2152870/180c1e79-5071-4f15-b16d-d013b5309db8

2024-03-21 13:32 UTC, c4rl0sbr4v0 commented on packages/block-library/src/query/utils.js
> +					);
We can include as well non interactive blocks that supports client navigation (disabling force page reload). Those ones should have this block supports structure. You can check the paragraph block for example.

```
	"interactivity": {
			"clientNavigation": true
		}
```

2024-03-21 13:34 UTC, c4rl0sbr4v0 requested changes
Thanks for working on this PR!
I think we can adapt it to be compatible with every block that indicates the interactivity support.

2024-03-21 13:34 UTC, c4rl0sbr4v0 commented on packages/block-library/src/query/utils.js
> +						! blockInteractivity
We may need to revisit this conditional and allow all blocks with supports interactivity true and/or interactivity.clientNavigation.

2024-03-26 00:25 UTC, colinduwe commented
The PR does works with both ways blocks currently indicate interactivity support

I did just test and if you were to make a block with this:
"interactivity": {
    "clientNavigation": false
}
evaluates as true and allows you to add it to a query block. I will fix up the check.

2024-03-28 06:27 UTC, gziolo commented on packages/block-library/src/query/utils.js
> +						! blockName.startsWith( 'core/' ) &&
I don’t think you need to check against core blocks anymore now that block support allows opting into client-side navigation.

2024-04-03 16:39 UTC, c4rl0sbr4v0 requested changes
Thanks for the PR.
Just those small nitpicks and is ready to go.

2024-04-03 16:39 UTC, cbravobernal commented on packages/block-library/src/query/utils.js
> +					const blockInteractivityBool = Object.is(
Can we rename this to a more descriptive name? Something like `blockSupportsInteractivity`

2024-04-03 16:39 UTC, c4rl0sbr4v0 commented on packages/block-library/src/query/utils.js
> +					const blockClientNavigation = getBlockSupport(
Can we rename this to a more descriptive name? Something like `blockSupportsInteractivityClientNavigation`

2024-04-03 16:39 UTC, cbravobernal commented on packages/block-library/src/query/edit/enhanced-pagination-modal.js
> +				'Currently, avoiding full page reloads is not possible when non-interactive blocks from plugins are present inside the Query block.'
non-interactive or non-clientNavigation compatible.
You can add non interactive blocks that are still client navigation compatible ones.

2024-04-03 16:40 UTC, c4rl0sbr4v0 commented
I've set the label as a bug instead of an enhancement. As in PHP, it's already checking the block supports. In the editor part, it should have done the same thing in WP 6.5

I hope we can land this in 6.5.1

2024-04-03 18:09 UTC, colinduwe commented
I'd love to understand how to write a test for this but can't make heads or tails of the sprawling documentation. It seems like it should just be a unit test of useUnsupportedBlocks() in the utils file. Can anyone suggest a tutorial or another block to look to as template?

2024-04-04 10:05 UTC, c4rl0sbr4v0 commented
> I'd love to understand how to write a test for this but can't make heads or tails of the sprawling documentation. It seems like it should just be a unit test of useUnsupportedBlocks() in the utils file. Can anyone suggest a tutorial or another block to look to as template?

An option could be to make an e2e like the one in `test/e2e/specs/editor/blocks/query.spec.js` or something similar than https://github.com/WordPress/gutenberg/blob/6ba2c4e8d938ddf6905ec5f0ee911f5b7726a397/test/e2e/specs/editor/various

I'll leave the PR approved, so you can add the test in a follow-up PR.

2024-04-04 10:07 UTC, c4rl0sbr4v0 approved these changes

2024-04-04 10:07 UTC, c4rl0sbr4v0 commented on packages/block-library/src/query/utils.js
> +					const blockSupportsInteractivityBool = Object.is(
```suggestion
					const blockSupportsInteractivity = Object.is(
```

2024-04-05 20:20 UTC, merged

2024-04-09 02:48 UTC, tellthemachines commented
I just cherry-picked this PR to the add/fixes-for-651 branch to get it included in the next release: 79babeda48