Shadow: revert shadow default presets opt-in to opt-out
WordPress/gutenberg pull request #60204
Opened 2024-03-26 14:11 UTC by madhusudhand

## What?

This change reverts part of changes from #58766 and #59499.
It is to sync changes from https://github.com/WordPress/wordpress-develop/pull/6309 back to Gutenberg.

## Why?

Previous fix causing regression as mentioned [here](https://github.com/WordPress/gutenberg/issues/59989)

## How?

Restores defaultPresets to `true` and removes it from appearanceTools.

## Testing Instructions

## Screenshots or screencast 

Fixes: #59989 and #60192 (work in progress)

2024-03-26 15:31 UTC, ajlende approved these changes
Thanks for getting the backport to GB opened up.

LGTM 👍

2024-03-26 15:34 UTC, ajlende commented
This is a backport to Gutenberg for [Trac #60815](https://core.trac.wordpress.org/ticket/60815) and the https://github.com/WordPress/wordpress-develop/pull/6309 fix.

2024-03-26 17:14 UTC, mikachan approved these changes
These changes are in line with the changes in https://github.com/WordPress/wordpress-develop/pull/6309, so I think this is good to land.

2024-03-27 18:17 UTC, ajlende requested changes
@oandregal added some tests to the [core changeset](https://core.trac.wordpress.org/changeset/57885). @madhusudhand can you copy those over here as well?

2024-03-28 14:06 UTC, ajlende approved these changes
Thanks for getting the tests copied over!

2024-04-02 07:24 UTC, merged