Edit Post: Expose PluginSidebar as final API
WordPress/gutenberg pull request #6031
Opened 2018-04-06 09:03 UTC by gziolo

## Description
TBD ...

## How Has This Been Tested?

## Types of changes
Refactoring applied. There shouldn't be any noticeable changes in the UI.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code has proper inline documentation.

2018-04-06 13:41 UTC, gziolo commented on edit-post/components/sidebar/index.js
> +	ifCondition( ( { activeSidebarName, name } ) => activeSidebarName === name ),
Actually, it'd trigger less re-renders when `isActive` is returned from `withSelect`.

2018-04-06 14:06 UTC, gziolo commented
> Can you elaborate on how to test? I tried pasting the example plugin into the console, but got a "Uncaught SyntaxError: Unexpected token <" error.

I provided also ES5 version of the plugin which you can paste in the JS console.

2018-04-06 14:32 UTC, jasmussen commented
Here's a GIF:

![sidebars](https://user-images.githubusercontent.com/1204802/38426890-19448b36-39b8-11e8-9ce5-fc4d92318528.gif)

Everything about this is solid. Love it. Looks and works and feels right. Ship it!

Can't wait to see the icon pinning feature 🌟

2018-04-09 08:24 UTC, Xyfi commented
There is something wrong with the mobile view:
<img width="742" alt="another_brave_new_world____ _local_wordpress_dev_ _wordpress" src="https://user-images.githubusercontent.com/5389513/38487122-7438529c-3bdf-11e8-9757-6178add82891.png">
Both the 'x' buttons close the sidebar.

Also @aduth had the idea to reuse the sidebar API for the document and block sidebars as well, instead this PR introduces two new sidebars (`BlockSidebar` and `DocumentSidebar`).

All in all a good PR.

2018-04-09 08:25 UTC, abotteram requested changes
The mobile view needs to be fixed. See comment above.

2018-04-09 09:18 UTC, atimmer approved these changes
Having given this a quick look, that general ideas look great. I'll leave it to @Xyfi to review and test the code in more detail.

2018-04-09 09:30 UTC, gziolo commented
> Also @aduth had the idea to reuse the sidebar API for the document and block sidebars as well, instead this PR introduces two new sidebars (`BlockSidebar` and `DocumentSidebar`). Is this something we still want?

We could do it, although it works exactly the same at the moment, but without explicitly using `registerPlugin` method. `BlockSidebar` and `DocumentSidebar` work almost exactly the same as `PluginSidebar`, but provide their own customized implementation.

2018-04-09 11:28 UTC, gziolo commented
@Xyfi this issue with movers exists also in the `master` branch. I think it is a regression introduced in one of the recent PRs.

2018-04-09 12:05 UTC, gziolo commented
Opened #6081 to address issues with the overlapping block controls.

2018-04-09 20:07 UTC, gziolo commented
@Xyfi, I think I fixed all visual issues on mobile:

![screen shot 2018-04-09 at 22 05 41](https://user-images.githubusercontent.com/699132/38520156-3ff584ec-3c42-11e8-8c69-a598010608d1.png)

it aligns with `Document` settings:

![screen shot 2018-04-09 at 22 06 53](https://user-images.githubusercontent.com/699132/38520183-554cd976-3c42-11e8-98e9-6f47ce87514f.png)

2018-04-10 08:01 UTC, Xyfi commented
> We could do it, although it works exactly the same at the moment, but without explicitly using registerPlugin method. BlockSidebar and DocumentSidebar work almost exactly the same as PluginSidebar, but provide their own customized implementation.

If it works exactly the same, doesn't that mean there is quite some duplicate code there? Also I think that [these lines](https://github.com/WordPress/gutenberg/blob/5a64d58ad270855c16d4f85186895e20f8803da7/edit-post/components/layout/index.js#L89-L91) clutter the layout file a bit.

2018-04-10 08:13 UTC, abotteram approved these changes

2018-04-10 08:13 UTC, merged

2018-04-18 08:56 UTC, mtias commented
Great to see all the work and refinement behind these APIs!