Fix expander padding and outline
WordPress/gutenberg pull request #6065
Opened 2018-04-08 15:30 UTC by abhijitrakas

## Description
The expander select box has extra `top` and `bottom` padding and small yellow outline below expander button which does not look good.   

## How Has This Been Tested?
Click on `All Posts` and check the expander select box. You will find that there is extra `top` and `bottom` padding and check small yellow outline below expander button.
 
## Screenshots (jpeg or gifs if applicable):
![expander-padding](https://user-images.githubusercontent.com/26354653/38469245-0a974962-3b6f-11e8-8ee5-cf80af934901.png)

## Types of changes
It's just little `enhancement` in CSS.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style.
- [ ] My code has proper inline documentation.

2018-04-08 18:40 UTC, paulwilde commented
This is probably browser specific, as it looks fine in Safari and Chrome.

2018-04-09 02:03 UTC, abhijitrakas commented
@paulwilde On my `ubuntu 16.04` I have check with `chrome` and `firefox` both showing me this padding issue.

2018-04-09 03:25 UTC, abhijitrakas commented
@paulwilde You are right, I have tested on `Mac` for safari, firefox, and chrome browsers and it looks perfect. Also, checked on `Windows`  and `padding` look perfect here as well. The `padding` issue only found with `Ubuntu`.  

But, I found `outline` issue on all `OS` with all browsers.   

So, I am reverting `padding` changes but keeping `outline` fix. Is it ok?

2018-04-24 01:39 UTC, abhijitrakas commented
@aduth when we click on the `select box` it shows the `outline` around the select box. So the change will fix it. Please check attachment for more detail.

![outline-css-gutenberg](https://user-images.githubusercontent.com/26354653/39161444-5026824c-478e-11e8-8896-13176159a88d.png)

2018-04-24 02:02 UTC, aduth commented
What is fixed? That it is not shown? Shouldn't we want a visible outline, or at least an obvious focus/active state effect?

2018-04-24 02:46 UTC, abhijitrakas commented
@aduth in the previous attachment you can see a black dotted line. I think don't require that. The fix removing that black dotted line.

2018-04-25 20:51 UTC, aduth requested changes
Okay, I understand better now. Ultimately this is caused by the fact that the expander substitutes its own `:focus` styles with a `box-shadow` without resetting the browser default `outline` value. Can I ask that you place the `outline: none;` in the same style selector where `box-shadow` is assigned, to keep them aligned?

https://github.com/WordPress/gutenberg/blob/5a6693589285363341bebad15bd56d9371cf8ecc/gutenberg.php#L437-L441

2018-04-26 02:45 UTC, abhijitrakas commented
I have tried to add `outline`  in this selector  https://github.com/WordPress/gutenberg/blob/5a6693589285363341bebad15bd56d9371cf8ecc/gutenberg.php#L437-L441

but it's not working. Means outline still present there. @aduth

2018-04-30 18:29 UTC, aduth commented
Ok, I see those styles are applying to the `.expander`'s `:after` pseudo-element, not the `.expander` itself which is focused.

Can we add a scoping to `.split-page-title-action` style for consistency with others? `.expander` is a bit broad and could conflict with other plugins.

```css
.split-page-title-action .expander {
	outline: none;
}
```

Just to note: From what I understand, this is just a temporary UI element during the plugin stage.

2018-05-17 07:04 UTC, abhijitrakas commented
@aduth updated code as you suggested. Please check.

2018-05-23 19:50 UTC, aduth approved these changes
Looks good. Thanks 👍

2018-05-23 19:50 UTC, merged