Theme.json reference: Add fluid typography properties.
WordPress/gutenberg pull request #60980
Opened 2024-04-23 07:34 UTC by carolinan

## What?

Add minFontSize, maxViewportWidth, minViewportWidth to settings > typography > fluid in the theme.json reference.

Closes https://github.com/WordPress/gutenberg/issues/59747

2024-04-23 07:50 UTC, ramonjd approved these changes
Oh wow, thanks for updating that. Totally missed it.

🎉

2024-04-23 08:15 UTC, t-hamano requested changes
This document is automatically generated from the theme.json schema, so it cannot be updated directly 😅 These properties are [defined](https://github.com/WordPress/gutenberg/blob/73a17b0d3dc9e08aaeb84bf03c9398d61a327a8c/schemas/json/theme.json#L523-L534) in JSON Schema, so you may need to adjust [the generation logic](https://github.com/WordPress/gutenberg/blob/73a17b0d3dc9e08aaeb84bf03c9398d61a327a8c/bin/api-docs/gen-theme-reference.js#L119-L143).

2024-04-23 08:18 UTC, carolinan commented
Running `npm run docs:build ` removes the changes, so they must be automatically generated. I have not worked with these docs in a long time, so I forgot.

2024-04-23 08:18 UTC, carolinan commented
hehe Aki was faster.

2024-04-23 08:20 UTC, carolinan commented
@ramonjd are we sure  settings.typograhy.fluid props are an `object` and not an `array` 😄 ?

2024-04-23 08:25 UTC, ramonjd commented
>  are we sure settings.typograhy.fluid props are an object and not an array 😄 ?

Yes, it's referring to the JSON props, and it can be either an object or a bool.

> This document is automatically generated from the theme.json schema, so it cannot be updated directly

Oh I assumed @carolinan had just run `npm run docs:build` and it had somehow passed the build before 🤣

2024-04-23 09:13 UTC, t-hamano commented
From what I've looked into, it looks like the entire document isn't being generated correctly, especially `Type` and `Props`.

For example, `styles.color.background` is of type `string`, but it is written as `string, object` in the doc. Also, the `settings.typography.fluid` is shown as `undefined`. This is probably because the `oneOf` property is not parsed correctly.

We may need to update the code around [this](https://github.com/WordPress/gutenberg/blob/73a17b0d3dc9e08aaeb84bf03c9398d61a327a8c/bin/api-docs/gen-theme-reference.js#L134-L138). I don't have time to look into it right away, but I would like to look into this ligic when I have tine.

2024-04-23 12:26 UTC, closed without merging

2024-04-24 05:19 UTC, ramonjd commented
> We may need to update the code around [this](https://github.com/WordPress/gutenberg/blob/73a17b0d3dc9e08aaeb84bf03c9398d61a327a8c/bin/api-docs/gen-theme-reference.js#L134-L138). I don't have time to look into it right away, but I would like to look into this ligic when I have tine.

I had some time today. Thanks for the tip off @t-hamano 

https://github.com/WordPress/gutenberg/pull/61024