Select last section if parent section doesn't exist
WordPress/gutenberg pull request #61002
Opened 2024-04-23 13:55 UTC by draganescu

## What?

Fixes #60972

## Why?

Selecting a category from the inserter patterns tab puts the editor in zoom out mode. Since in zoom out mode block selection is disabled and we default to "section" selection, we need to manage what is selected.

There is some logic to decide what to select in `__unstableSetEditorMode` which is an action in the block editor store, so when zoom out is activated:

- if there is a section root
  - **if there is a block selected, select the parent section**
  - if there is no block selection, select the last section
- if there is no section root
  - if there is a selected block, select the root parent
- finally,
  - select the "last root block" (*)

The bug in #60972 happens because we didn't consider that a selected block may have an undefined parent section (the root block doesn't).

## How?

Fixes `__unstableSetEditorMode` to also select the last section, if the currently selected block does not have a valid parent section.

## Testing Instructions

0. Create a template with several patterns grouped in a group block whose tag is set to `main`
1. Open main Block Inserter
2. Click Pattern Tab
3. Click a Pattern Category
4. Click Block Tab
5. Click Pattern Tab
6. Click Pattern Category
7. **It should work as expected**

### Testing Instructions for Keyboard

n/a

## Screenshots or screencast 

n/a

(*) "last root block", we expect that in a template we'd have a list of patterns or other grouped blocks, so if they're not in a `main` group they're considered sections themselves.

2024-04-23 14:26 UTC, scruffian approved these changes
LGTM. Pushed a small refactor.

2024-04-23 14:50 UTC, Mamaduka approved these changes
Thank you, @draganescu! The fix works as expected.

Note: The logic inside the `mode === 'zoom-out'` block is becoming a little bit hard to follow. It might be a time for minor refactoring + adding comments.

2024-04-23 14:57 UTC, Mamaduka requested changes, later dismissed
I think I found another issue that seems to be related.

## Screenshot

Uploading CleanShot 2024-04-23 at 18.55.47.mp4…

2024-04-24 09:18 UTC, scruffian commented
@Mamaduka good catch, but I think this is a slightly different scenario, so I think we should deal with it in a different PR. I created a new issue to keep track of it: https://github.com/WordPress/gutenberg/issues/61038

2024-04-24 09:18 UTC, merged

2024-04-24 09:21 UTC, Mamaduka commented
@scruffian, that sounds good. Could you add details on how it's different from the issue @draganescu resolved?