Add `WP_ENV_TESTS_MYSQL_PORT` / `.wp-env.json` `testsMysqlPort` option
WordPress/gutenberg pull request #61057
Opened 2024-04-24 22:03 UTC by BrianHenryIE

Fix: https://github.com/WordPress/gutenberg/issues/50677

## What?

Currently, the tests container's database port is assigned randomly each time wp-env is started. This PR adds the ability to set the MySQL port number in the `.wp-env.json` file or via a `WP_ENV_TESTS_MYSQL_PORT` environmental variable.

## Why?

I'd like to be able to use the database in unit tests.

## How?

By adding a config option to keep the port number static.

## Testing Instructions

Set `testsMysqlPort` in `.wp-env.json`
```
{
	"testsMysqlPort": 52666
}
```

```
$ cat .wp-env.json | jq '.testsMySqlPort = 52666' | sponge .wp-env.json`
$ npx wp-env start
...
MySQL for automated testing is listening on port 52666
```

```
$ WP_ENV_TESTS_MYSQL_PORT=56678 npx wp-env start
...
MySQL for automated testing is listening on port 56678
```

## Screenshots or screencast 

<img width="636" alt="Screenshot 2024-04-24 at 2 59 05 PM" src="https://github.com/WordPress/gutenberg/assets/4720401/62cb1bb9-fc31-4c27-95f9-44d917bfeb89">

<img width="878" alt="Screenshot 2024-04-24 at 2 59 19 PM" src="https://github.com/WordPress/gutenberg/assets/4720401/0f44a500-c2e0-47e8-849e-bfe691e9db66">

2024-05-01 23:03 UTC, ObliviousHarmony requested changes
This seems like a reasonable addition to `wp-env`, thanks!

I've left some comments :smile:

2024-05-01 23:03 UTC, ObliviousHarmony commented on packages/env/lib/config/parse-config.js
> +	testsMysqlPort: null,
I view the top-level `port` and `testsPort` properties are more of a legacy thing. It's more intuitive to set configuration like this _only_ at the environment level. How would you feel about dropping the root `testsMysqlPort` in favor of just having `development.mysqlPort` and `tests.mysqlPort`?

2024-05-01 23:03 UTC, ObliviousHarmony commented on packages/env/lib/build-docker-compose-config.js
> +	const testsMysqlPorts = `\${WP_ENV_TESTS_MYSQL_PORT:-${ config.env.tests.mysqlPort ?? '' }}:3306`;
If we're going to support customizing the port like this let's go ahead and also support the development environment's MySQL port too.

2024-05-14 05:19 UTC, BrianHenryIE commented
To test, checkout this PR and create a project with its `package.json` referencing it:

```json
{
  "name": "gutenberg-61057-test",
  "devDependencies": {
    "@wordpress/env": "file:/Users/brianhenry/Sites/gutenberg/packages/env"
  }
}
```

```bash
npm install;
npx wp-env start;
```

Observe default behaviour with randomly assigned MySQL ports:

```
MySQL is listening on port 54916
MySQL for automated testing is listening on port 54922
```

Add `.wp-env.json`:
```json
{
  "env": {
    "development": {
      "mysqlPort": 13306
    },
    "tests": {
      "mysqlPort": 13307
    }
  }
}
```

```bash
npx wp-env start;
```

Observe specified ports used:

```
MySQL is listening on port 13306
MySQL for automated testing is listening on port 13307
```

Test Bash env variables:

```bash
WP_ENV_MYSQL_PORT=13304 npx wp-env start
```

```
MySQL is listening on port 13304
MySQL for automated testing is listening on port 13307
```

```bash
WP_ENV_TESTS_MYSQL_PORT=13305 npx wp-env start
```

```
MySQL is listening on port 13306
MySQL for automated testing is listening on port 13305
```

I'll take another look at the automated tests soon.

2024-05-15 18:54 UTC, desrosj approved these changes
This seems sensible to me. Thanks for adding tests! @ObliviousHarmony has this been updated to your liking?

2024-05-15 19:18 UTC, desrosj commented
Actually on second look I [mistook these changes as new tests](https://github.com/WordPress/gutenberg/pull/61057/files#diff-90b1c99fd7324cd750e05b3166ed8f0dc47fd4cec7925976a703e1065b9d364c). It would be great to add a few if you could.

2024-06-05 14:16 UTC, desrosj commented
It seems like all of the feedback has been reasonably addressed. Since this is only being blocked by the review points to be confirmed as addressed, I'm going to merge this to give it a try.

2024-06-05 14:17 UTC, merged