Force Link UI to appear below a link if one is selected
WordPress/gutenberg pull request #6113
Opened 2018-04-11 01:50 UTC by noisysocks

Fixes https://github.com/WordPress/gutenberg/pull/6028#issuecomment-380175237.

Before:

![before](https://user-images.githubusercontent.com/253067/38571795-67e66758-3ce9-11e8-8e63-106ec64fa6e2.gif)

Now:

![link](https://user-images.githubusercontent.com/612155/38592260-768cd41e-3d7e-11e8-8678-b0dbc963ff80.gif)

2018-04-11 15:16 UTC, karmatosed approved these changes
Design wise this seems to have solved the dancing link issue. I'll let a code review happen also though.

2018-04-11 16:07 UTC, iseulde commented
Hm, I'm not entirely sure how to test. I still see the link toolbar moving around.

![link](https://user-images.githubusercontent.com/4710635/38629006-1d855078-3db3-11e8-8744-34780742d180.gif)

2018-04-11 16:09 UTC, iseulde commented
Nevermind, I didn't check the branch out properly.

2018-04-11 16:14 UTC, iseulde commented
Still has some issues. Not sure why we are keeping the `getRectangleFromRange` at all. Isn't this only used for the link?

![link](https://user-images.githubusercontent.com/4710635/38629376-2a2dde70-3db4-11e8-80af-dfaaab86ad0c.gif)

2018-04-11 16:24 UTC, ellatrix requested changes
See https://github.com/WordPress/gutenberg/pull/6113#issuecomment-380509977. I think we can drop the calculation if none of the `parents` is a link (it's only used for links and there is no way this could be generalised). We can't just look at the `element` because there might be nested tags.

2018-04-12 00:28 UTC, noisysocks commented
Thanks @iseulde. I've fixed the issue with nested tags—great catch.

We can't drop the `getRectangleFromRange` calculation entirely, however, since the Link UI needs to be positioned underneath the selection when you are creating a new link, e.g:

![link](https://user-images.githubusercontent.com/612155/38649864-2bdcd9dc-3e3c-11e8-8944-a49fea6577d5.gif)

2018-04-13 09:48 UTC, ellatrix approved these changes
Looks good to go, but please fix the lining error first. :)

2018-04-16 00:42 UTC, merged

2018-04-16 00:43 UTC, noisysocks commented
Thanks @iseulde!