add generic button instead of inserter between sections
WordPress/gutenberg pull request #61434
Opened 2024-05-07 07:34 UTC by MaggieCabrera

## What?

## Why?

## How?

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast

2024-05-08 02:00 UTC, ellatrix commented on packages/block-editor/src/components/block-tools/zoom-out-mode-inserters.js
> +								category: 'all',
We should probably make these private symbols

2024-05-08 02:08 UTC, MaggieCabrera commented
For what it's worth, I give a ✅ to Ella's changes, let's get someone else's approval too

2024-05-08 02:15 UTC, richtabor commented
Let's remove the horizontal lines here:  

![CleanShot 2024-05-08 at 11 14 05](https://github.com/WordPress/gutenberg/assets/1813435/b1fdaa33-a5b5-4d2e-9a50-1b99d39d18ee)

2024-05-08 02:17 UTC, richtabor commented
@jeryj Where do you think focus should go once you click the quick inserter?

2024-05-08 02:55 UTC, richtabor commented
Also, it currently does not open the "All" category, when the inserter is already open. We should have it behave consistently, i.e. always open the "All" category. 

As an aside, it _may_ need to only open the patterns tab, not the a category—but let's get it consistent with "all" first, then we can decide which works better.

2024-05-08 03:20 UTC, scruffian requested changes, later dismissed
When I click on an inserter in the canvas we should update the insertion point so that blocks and patterns get inserted below it.

2024-05-08 04:02 UTC, jeryj commented
> Where do you think focus should go once you click the quick inserter?

I would say the first focusable within the patterns tab panel. Right now that would be the Pattern Search input.

2024-05-09 01:07 UTC, ellatrix commented on packages/block-editor/src/components/block-tools/zoom-out-mode-inserters.js
> +				className="block-editor-button-pattern-inserter"
Do we still need this class name?

2024-05-09 01:11 UTC, MaggieCabrera commented on packages/block-editor/src/components/block-tools/zoom-out-mode-inserters.js
> +				className="block-editor-button-pattern-inserter"
I don't think so, it can go

2024-05-09 03:01 UTC, richtabor commented
It's a step forward; not the end-goal. A few notes: 

1. When selecting an insertion point, I should be able to insert patterns with the latest pattern added to the bottom of newly inserted patterns. Currently they're always inserted at the specified insertion point. 
2. Let's follow-up with trying the inserter not opening the "All" category, focusing on the search input.

2024-05-09 03:18 UTC, richtabor commented
While https://github.com/WordPress/gutenberg/pull/61434/commits/ac1bbadb47308ffd0e1ffea7f0a7a91f254b9a0e enforces patterns to insert after the previous one inserted, it negates the opening of the inserter with the "All" category selected.

2024-05-09 03:32 UTC, richtabor commented
> While https://github.com/WordPress/gutenberg/commit/ac1bbadb47308ffd0e1ffea7f0a7a91f254b9a0e enforces patterns to insert after the previous one inserted, it negates the opening of the inserter with the "All" category selected.

Works well. Thanks!

2024-05-09 03:34 UTC, ellatrix approved these changes

2024-05-09 04:01 UTC, richtabor approved these changes
Looks good. Let's try an iteration that does not open "All" and focuses on search unseated.

2024-05-09 05:01 UTC, merged

2024-05-21 08:48 UTC, Mamaduka commented
Hey, @MaggieCabrera

The new e2e test introduced here looks to be flaky - #61806.

2024-05-21 09:33 UTC, MaggieCabrera commented
> Hey, @MaggieCabrera
> 
> The new e2e test introduced here looks to be flaky - #61806.

I'll look into it as soon as I can

2024-05-22 09:44 UTC, Mamaduka commented
I think I know the cause of the issue:

Opening the Pattern tab in the inserter closes the "Styles" sidebar and exits the "zoom-out" mode, and the "Add pattern" buttons are no longer visible.

I thought that the Patterns tab in the inserter enabled "zoom-out" mode as well, so I'm not sure if this is a regression in core or just a broken test.

cc @draganescu, @jeryj

2024-05-23 14:07 UTC, tyxla commented
Got a minor follow-up to this one in #61908, related to #61788.