Interactivity API: Added comments for directive parsing
WordPress/gutenberg pull request #61456
Opened 2024-05-07 19:26 UTC by amitraj2203

## What?
Fixes: #61455 

## Why?
It adds comments for directive parsing

## How?

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast

2024-05-07 19:45 UTC, cbravobernal requested changes
Hi there!

I was thinking about doing a refactor (setting the variables names with what they should be, instead of 'prefix' or 'suffix' rather than adding code comments 😅 

Thanks for contributing on this issue!

2024-05-07 20:10 UTC, amitraj2203 commented
@cbravobernal I've made the changes you suggested! Now, instead of using 'prefix' and 'suffix', I've renamed the variables more clearly.

Thanks!

2024-05-13 10:34 UTC, cbravobernal requested changes
I'm leaving this on `Request changes` to wait for https://github.com/WordPress/gutenberg/pull/61409 to be merged and also to get some more feedback about the naming of those vars.

2024-05-13 10:34 UTC, cbravobernal commented on packages/interactivity/src/vdom.ts
> +					// Check if the directive name matches the expected format.
```suggestion
```
Same here.

2024-05-13 10:34 UTC, cbravobernal commented on packages/interactivity/src/vdom.ts
> +				// The reducer function accumulates the __directives object.
```suggestion
```
Same here.

2024-05-13 10:34 UTC, cbravobernal commented on packages/interactivity/src/vdom.ts
> +							console.warn(
Let's wait for https://github.com/WordPress/gutenberg/pull/61409 to be merged and update with its function.

2024-05-13 10:34 UTC, cbravobernal commented on packages/interactivity/src/vdom.ts
> +					// Creating or updating the array for the specific directive type in the directives object.
```suggestion
```
Same here

2024-05-13 10:34 UTC, cbravobernal commented on packages/interactivity/src/vdom.ts
> +					// Splitting the directive name into directive type and input.
```suggestion
```
Same here

2024-05-13 10:34 UTC, cbravobernal commented on packages/interactivity/src/vdom.ts
> +					const directiveType = directiveMatch[ 1 ] || '';
```suggestion
					const directive = directiveMatch[ 1 ] || '';
```
I think directive is a better name.

2024-05-13 10:34 UTC, cbravobernal commented on packages/interactivity/src/vdom.ts
> +					const directiveInput = directiveMatch[ 2 ] || 'default';
Could be "event" or "directiveEvent" a better name for this?

Not sure, cause they are events in `data-wp-on-document` or `data-wp-on-window` or `data-wp-on`. But can also be styles or classes in `data-wp-class--` or `data-wp--style`.

What do you think about it? Let's ping some folks with experience developing with the Interactivity API to get some feedback.

Ping: @ryanwelcher , @luisherranz , @DAreRodz or @sethrubenstein

2024-05-14 18:17 UTC, amitraj2203 commented
Hi @cbravobernal I have made changes as per your suggestion. Now waiting for replies from other folks.

2024-05-24 10:04 UTC, cbravobernal commented
Sorry @amitraj2203 but we are not going to merge this PR. The prefix word is being used through all the Interactivity codebase, and is a bigger refactor than expected.

2024-05-24 10:04 UTC, closed without merging