Zoom Out: Show a preview when dragging and dropping patterns from the inserter.
WordPress/gutenberg pull request #61511
Opened 2024-05-09 03:54 UTC by scruffian

## What?
When dragging and dropping patterns from the inserter we now show a preview of the pattern instead of the draggable chip.

## Why?
This will be more user friendly and easier for users to understand what they are doing.

## How?
Just let the browser handle the preview.

## Testing Instructions
1. Open the patterns inserter
2. Drag a pattern into the canvas
3. Check that you see a preview of the pattern you are moving

## Screenshots or screencast 
<img width="1512" alt="Screenshot 2024-05-09 at 12 54 13" src="https://github.com/WordPress/gutenberg/assets/275961/5c78b9eb-76c7-46ec-8ebe-6763af781f51">

2024-05-09 04:08 UTC, ellatrix approved these changes

2024-05-10 04:52 UTC, MaggieCabrera approved these changes
Working as intended, I updated the changelog and pinged some component maintainers

2024-05-10 05:12 UTC, ntsekouras commented
We need to find a different handling for this because right now the browser takes a screenshot and can include the pattern's title and hover styles, which is not what we want.

2024-05-10 05:48 UTC, draganescu requested changes
> We need to find a different handling for this because right now the browser takes a screenshot and can include the pattern's title and hover styles, which is not what we want.

2024-09-30 07:04 UTC, draganescu commented
I will close this because no progress and also because we use the chip in all the other places.

2024-09-30 07:04 UTC, closed without merging