Only output one BlockTypesTabPanel
WordPress/gutenberg pull request #62300
Opened 2024-06-04 20:03 UTC by jeryj

Instead of having two blockTypesTabPanels, just use one by adding our current category as the top level item and put all blocks (without groupings) within it. I'm not sure if this change will be desired though.

## What?

## Why?

## How?

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast

2024-06-04 20:42 UTC, jeryj commented
@ellatrix Curious on your feedback for if this code is an improvement performance wise or if I'm over-thinking it.
@richtabor Do you think grouping all allowed blocks for a block within one category (block name title) is OK, or will some blocks show too many ungrouped blocks beneath them (such as the navigation block).

2024-06-05 04:51 UTC, ellatrix requested changes
I feel like I talked about this a few times before: if you create a single "insertable at selection" category, all the other categories disappear. So if you open the inserter in a quote or group, they'll all be squashed into a single one.

<img width="1029" alt="image" src="https://github.com/WordPress/gutenberg/assets/4710635/4f8abb9b-153c-4edc-be71-a6daeadb6122">

2024-06-05 04:52 UTC, ellatrix commented
To me this is not a "code quality" PR, there's a change in behaviour.

2024-06-05 04:53 UTC, ellatrix commented
> Curious on your feedback for if this code is an improvement performance wise or if I'm over-thinking it.

Curious why you think `BlockTypesTabPanel` is a performance issue? It doesn't do anything unperformant?

2024-06-05 15:29 UTC, jeryj commented
> I feel like I talked about this a few times before: if you create a single "insertable at selection" category, all the other categories disappear. So if you open the inserter in a quote or group, they'll all be squashed into a single one.

Yes, I noticed that too and mentioned it above. I was thinking about redefining the heuristics so if it has a lot of blocks within it, such as the group block, then it outputs things within the normal categories. Trying to get a feel for different options.

> To me this is not a "code quality" PR, there's a change in behaviour.

I wasn't sure what to categorize it as since it's not a bug and it may not be an enhancement in its current state :) 

> Curious why you think BlockTypesTabPanel is a performance issue? It doesn't do anything unperformant?

It's doing a lot of things for the initial category that aren't necessary, like grouping into collections, outputting most used blocks. I think it could be simpler to pass one list of items and categories, so I'm trying it out. I'll probably drop close this PR, but I was curious to see how it was in practice.

2024-06-07 15:56 UTC, jeryj commented
@WordPress/gutenberg-design - Can I get feedback on the UX of the inserter category heuristics here? I think this is an improvement to the output and organization of the block inserter categories when we have block filtering relative to the selected block.

2024-06-08 13:49 UTC, paaljoachim commented
If I understand this correctly.
That Most used in the Block inserter will change depending on selected block in Canvas view. I have mixed feelings about this as for many users it can be fairly random which block is selected in Canvas view. Other times it can be helpful to select a specific block in Canvas view and have a more focused/tailored block inserter experience.

An example would be having a specific WooCommerce block selected in Canvas view and then seeing other WooCommerce blocks on the top of the Block inserter to give a signal to the user a relation of the selected block to other similar blocks in the Block inserter.

It can be very helpful to create a relation between a selected block in Canvas view <-> seeing more focused blocks in the Block inserter. Gradually over time an user can notice the relation. Then might on purpose select specific blocks in Canvas view to get related blocks in the Block inserter.

2024-06-10 06:41 UTC, jasmussen commented
Thanks for the PR. While the behavior in trunk isn't necessarily the most intuitively understandable, there's something obvious about the sorting in categories of _inserts in selected block_ and _inserts after_, but the behavior for the Group block, feels like it bridges those two gaps in an intuitive way. 

Reducing duplication, and showing towards the top the most useful and common blocks you'd likely insert contextually, that feels valid enough. But it's not clear this brings benefits to the actual user experience, especially for the group block. I could very well be missing nuance, however, the trunk behavior I haven't had a chance to absorb fully yet.

2024-06-25 19:41 UTC, jeryj commented
Closing for now, but we can open this exploration up later if needed.

2024-06-25 19:41 UTC, closed without merging