Fixed : Disambiguate "Cover" translatable string in the context of background-panel.js
WordPress/gutenberg pull request #62440
Opened 2024-06-10 09:55 UTC by narenin

## What?
[In image block's background-panel.js context](https://github.com/WordPress/gutenberg/blob/bbdf1a7f39dd75f672fe863c9d8ac7bf8faa874b/packages/block-editor/src/components/global-styles/background-panel.js#L547), there is a "Cover" string sharing its translation with other occurrences of "Cover", like the Cover block. It results in wrong translation of the setting in some locales, like in French where the Cover Block is translated into "Bloc Bannière" while "Cover Size" cannot be translated into "Taille Bannière".

This PR will fix the issue raised in https://github.com/WordPress/gutenberg/issues/62426

## Why?
It fixed the disambiguate we have in "Cover" translatable string in the context of `background-panel.js`

## How?
This PR will add some context using _x(), just like we did in [this other occurrence of "Cover", in a very similar context](https://github.com/WordPress/gutenberg/blob/bbdf1a7f39dd75f672fe863c9d8ac7bf8faa874b/packages/block-library/src/image/image.js#L61) to fix this issue.

## Testing Instructions

1. Install `fr_FR` language pack
2. Open `Background panel component`
3. See that the "Cover" string is translated into "Bannière". "Couvrir" should be used instead.

## Screenshots or screencast 

**Before:**

![image](https://github.com/WordPress/gutenberg/assets/32844880/1d9087f5-6266-4ece-b178-f1d651e30710)

**After:**

![image](https://github.com/WordPress/gutenberg/assets/32844880/a312883b-7a93-4486-b798-bfa3710b5080)

2024-06-10 10:07 UTC, audrasjb commented
Thanks for the PR! It looks good to me.
By the way I think we could also add context for the "Contains" string.

2024-06-10 10:14 UTC, narenin commented
@audrasjb Thanks for the feedback, I have added the same for **"Contains"** and **"Tile"** string.

2024-06-11 02:58 UTC, ramonjd requested changes
Thanks for the PR @narenin 

I'd update the copy to describe the translation context more accurately, and so it's differentiated from the [Cover block context](https://github.com/WordPress/gutenberg/blob/bbdf1a7f39dd75f672fe863c9d8ac7bf8faa874b/packages/block-library/src/image/image.js#L61)

2024-06-11 02:58 UTC, ramonjd commented on packages/block-editor/src/components/global-styles/background-panel.js
> +					label={ _x( 'Cover', 'Scale option for dimensions control' ) }
```suggestion
					label={ _x( 'Cover', 'Size option for background image control' ) }
```

2024-06-11 02:58 UTC, ramonjd commented on packages/block-editor/src/components/global-styles/background-panel.js
> +					label={ _x( 'Contain', 'Scale option for dimensions control' ) }
```suggestion
					label={ _x( 'Contain', 'Size option for background image control' ) }
```

2024-06-11 02:58 UTC, ramonjd commented on packages/block-editor/src/components/global-styles/background-panel.js
> +					label={ _x( 'Tile', 'Scale option for dimensions control' ) }
```suggestion
					label={ _x( 'Tile', 'Size option for background image control' ) }
```

2024-06-11 02:59 UTC, ramonjd commented on packages/block-editor/src/components/global-styles/background-panel.js
> +					label={ _x( 'Tile', 'Scale option for dimensions control' ) }
There are also some JS linting errors around this line too:

https://github.com/WordPress/gutenberg/actions/runs/9446520609/job/26016390453?pr=62440#step:5:104

2024-06-11 05:51 UTC, ramonjd approved these changes
Great stuff! Thanks for the quick changes 🙇🏻

2024-06-11 06:28 UTC, merged

2024-06-18 06:15 UTC, ellatrix commented
This was cherry-picked to the wp/6.6 branch.