Accessibility: Fix custom color palette
WordPress/gutenberg pull request #62753
Opened 2024-06-21 14:59 UTC by ellatrix

## What?

Makes the custom color palette options accessible. Fixes #62728.

## Why?

Because it's inaccessible atm.

## How?

1. Always should the input and remove button.
2. Make the color indicator a button, which opens the popover.
3. Define an `onClose` function for the popover.

## Testing Instructions

See the three steps in #62728.

### Testing Instructions for Keyboard

## Screenshots or screencast

2024-06-21 16:49 UTC, joedolson commented
Can I ask that we provide testing information that uses the names of things as they're exposed in the editing environment? There's nothing literally called "Global Styles" in the editor, so it's difficult for outside users to make use of those instructions to locate the item to be tested.

I believe this is referring to the color options in the Stylebook, but please confirm.

2024-06-21 18:38 UTC, ellatrix commented
It's called "Styles". I think it used to be called Global Styles and people still refer to it by that name

<img width="317" alt="image" src="https://github.com/WordPress/gutenberg/assets/4710635/8225794b-a36c-4a9e-a8a4-cda8e2a9c962">

2024-06-21 22:48 UTC, joedolson commented
This is definitely a significant improvement.

I'd still very much like to see two changes:

1) Have a 'cancel' option in the color popover, so that it's possible to change a color, then return to the previous color without needing to have the hex value memorized. Right now, if you change a color, but don't have the previous value recorded, there's no way to return to the previous color. 

2) Have the `esc` key trigger the cancel behavior, and have a button available to save the changes. I think that a click outside of the popover should be treated as a completion action; but escape should be treated as a cancellation.

2024-06-24 07:48 UTC, afercia commented
Thanks for looking into this @ellatrix 
It does solve some of the issues discovered on https://github.com/WordPress/gutenberg/pull/62698 and then reported on https://github.com/WordPress/gutenberg/issues/62728

I'd agree with @joedolson that the color picker would need Cancel and Save buttons. Not sure if that can be addressed in this PR or separately, as it appears to be a broader issue with the color picker.

I'd suggest two further improvements to be made, if possible, in this PR:

For consistnecy, the focus style of the new button to edit custom colors should be, ideally, a circular outline. Screenshot of the two different focus styles of the color buttons:

![Screenshot 2024-06-24 at 09 44 35](https://github.com/WordPress/gutenberg/assets/1682452/b6398fba-bac0-4944-ba4a-1584b2f30b1d)

When removing a custom color by pressing the minus icon button 'Remove color', focus should be managed to avoid a focus loss. I'd think the only reasonable place to move focus to would be the plus icon button 'Add color'.

2024-06-24 07:53 UTC, afercia requested changes
Please see last comment.

2024-06-24 08:57 UTC, ellatrix commented
I can check again later today. I'd like this PR to be included in RC1, so it should be ready today, but I have a few other things to work through first.

2024-06-24 08:59 UTC, ellatrix commented
To me even the focus outline might be need a larger change (needing to pull in and extracting other components), so I'm not sure if it should block this improvement tbh... I went for the quick fix of wrapping the color in a Button.

2024-06-24 08:59 UTC, ellatrix commented
I could try to prevent the focus loss on remove though 👍

2024-06-24 09:59 UTC, afercia commented
I'd agree it would be good to have these improvements in the RC. Further fixes can be done as follow-up in https://github.com/WordPress/gutenberg/issues/62728

2024-06-24 13:06 UTC, ellatrix commented
@afercia I fixed the focus loss.

2024-06-24 13:07 UTC, ellatrix commented
Let's do this PR instead of #62698.

2024-06-25 07:09 UTC, afercia commented
> I fixed the focus loss.

@ellatrix thanks. I'm not sure the 'Done' button is the right choice though. When there's only one custom color, removing it will also make the 'Done' button disappear so in this case focus is lost anyways.

2024-06-25 07:24 UTC, ellatrix commented
@afercia Where to you suggest it to move?

2024-06-25 08:05 UTC, afercia commented
> I'd think the only reasonable place to move focus to would be the plus icon button 'Add color'.

Although not ideal, I think the 'Add color' button is the only one that is guaranteed to be always rendered?

2024-06-25 08:43 UTC, ellatrix commented
I'm not sure I have time left to fix this, I need to release the editor packages asap. If not, this will slip to 6.7

2024-06-25 09:25 UTC, afercia commented
I can try to have a look at it.

2024-06-25 09:53 UTC, afercia commented
After https://github.com/WordPress/gutenberg/pull/62753/commits/262a4867232d70e690e5162b42b8d8565e2a5cd6 I focus is now moved back to the 'Add color' button when removing a color. When users `canOnlyChangeValues`, the focus loss doesn't occur in the first place because there's no 'Remove' button.

Thi UI would need more work as there are other focus losses and room for accessibility improvements but I'd think this PR is an improvement that would be nice to have in the 6.6 release.

2024-06-25 10:22 UTC, ellatrix commented
Great, thanks @afercia! Could you approve the PR? I'll merge it and cherry pick it onto the release branch

2024-06-25 10:40 UTC, afercia approved these changes

2024-06-25 10:41 UTC, afercia commented
Done, thanks 👍🏽

2024-06-25 10:42 UTC, merged

2024-06-25 11:56 UTC, ellatrix commented
Manually backported this in https://github.com/WordPress/gutenberg/pull/62824