Add changelog entry for splitTask export from @wordpress/interactivity
WordPress/gutenberg pull request #62805
Opened 2024-06-24 19:41 UTC by westonruter

See https://github.com/WordPress/gutenberg/pull/62665#issuecomment-2186797243

2024-06-24 20:31 UTC, cbravobernal requested changes, later dismissed
Thanks for updating the changelog!

Changes should be under ## Unreleased heading. Once packages are released it will auto-update to its correspondant version.

2024-06-24 20:31 UTC, cbravobernal commented on packages/interactivity/CHANGELOG.md
> +
```suggestion
```

2024-06-24 20:31 UTC, cbravobernal commented on packages/interactivity/CHANGELOG.md
```suggestion
### Enhancements

-   Export `splitTask` function from `@wordpress/interactivity` package to facilitate yielding to the main thread. See example in [async actions](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/interactivity-api/api-reference.md#async-actions) documentation. ([#62665](https://github.com/WordPress/gutenberg/pull/62665))
```

2024-06-25 07:04 UTC, luisherranz approved these changes
Perfect, thank you!

2024-06-25 07:05 UTC, merged