URL input polish
WordPress/gutenberg pull request #6306
Opened 2018-04-20 08:21 UTC by jasmussen

This PR fixes two issues with the URL input dialog.

The first issue is that the URL bar, in very tight circumstances, would create a horizontal scrollbar — because it was abs positioned at the center of where it needed to be and then pulled leftwards 50% — but the invisible div was still poking out at the right. First commit fixes this.

The second was a scoping issue with the URL input when used for the Image block, when toolbar is fixed to top. This fixes that:

<img width="458" alt="screen shot 2018-04-20 at 10 17 36" src="https://user-images.githubusercontent.com/1204802/39038804-9fda72ec-4484-11e8-8b0a-41f67dc7f6b5.png">

2018-04-22 23:55 UTC, noisysocks requested changes
Thanks for fixing this! ❤️ 

The UI shown when adding a link to an image looks and behaves 💯.

I do see one regression, though. When inserting a link into a paragraph block, the UI moves around from side to side a lot while you are typing:

![links](https://user-images.githubusercontent.com/612155/39101392-61549552-46dc-11e8-8c4c-f8f342984933.gif)

2018-04-22 23:55 UTC, noisysocks commented on blocks/rich-text/format-toolbar/index.js
> +						<div style={ { position: 'absolute', transform: 'translateX( -50% )', ...focusPosition } }>
One sneaky `position` was OK, but now that there are a few properties I think we ought to give this div a `className` and add a new rule to `format-toolbar/style.scss`:

```scss
.blocks-format-toolbar__link-container {
    position: absolute;
    transform: translateX( -50% );
}
```

2018-04-22 23:55 UTC, noisysocks commented on blocks/rich-text/format-toolbar/style.scss
> +    	left: 0;
There's some weird indentation going on here.

2018-04-23 10:04 UTC, jasmussen commented
Thank you for the feedback! I believe I addressed it:

<img width="397" alt="screen shot 2018-04-23 at 11 59 58" src="https://user-images.githubusercontent.com/1204802/39120363-8497623a-46ee-11e8-9f5a-746b4ed8fa2e.png">

2018-04-23 10:33 UTC, jasmussen commented on blocks/rich-text/format-toolbar/style.scss
> +    position: absolute;
Hmm interesting — I was sure I installed eslint in VS Code — wondering why it didn't catch this...

2018-04-23 23:57 UTC, noisysocks approved these changes

2018-04-24 07:00 UTC, merged

2018-04-24 07:01 UTC, jasmussen commented
Hooray! Thanks!