Image: Adopt margin block support
WordPress/gutenberg pull request #63546
Opened 2024-07-15 03:18 UTC by aaronrobertshaw

Part of: https://github.com/WordPress/gutenberg/issues/43241

## What?

Adopts margin support for the Image block.

## Why?

- Offers greater design flexibility
- Improves consistency in design tooling with other blocks

## How?

- Adopts margin block support

## Testing Instructions

- In the site editor, add an Image block to a page
- Style via Global Styles and confirm the editor and frontend display correctly
- Override the global styles on the block instance and confirm they display appropriately in the editor and frontend

Note: Global margins will be overridden by layout whereas block instance margins will not be.

## Screenshots or screencast 

https://github.com/user-attachments/assets/472e6ac4-99de-4120-ab13-077b5c1039c0

2024-07-15 05:33 UTC, fabiankaegy approved these changes
Very happy to see this 🚀

2024-07-15 12:40 UTC, artemiomorales requested changes
I tested adding a margin to an image aligned to the right with the lightbox enabled, and the margin causes the lightbox to not animate smoothly:

https://github.com/user-attachments/assets/6dd5e7c3-e799-4079-9942-9ce39f706e7e

The added margin is likely throwing off the lightbox calculations; likely we should aim to take those into account.

2024-07-15 13:41 UTC, artemiomorales commented
The animation is also affected with center-aligned images that have a margin enabled:

https://github.com/user-attachments/assets/20fcef46-a1de-4ccc-9f45-b1760376cac9

We should also take into account using different aspect ratios, custom sizing, different resolutions, both scale options `cover` and `contain`, and border.

<img width="1276" alt="Screenshot 2024-07-15 at 9 04 07 AM" src="https://github.com/user-attachments/assets/8f35ee26-eec5-4f4b-b943-cebd1d65909e">

Regarding border, I see the lightbox animation is actually broken on `trunk` when a border is defined. I mention it here because it's related, but I've [opened a separate issue](https://github.com/WordPress/gutenberg/issues/63567) for that.

https://github.com/user-attachments/assets/a43987e0-6caa-4c46-8f9c-ddff0a57d1bc

My guess is the [setOverlayStyles callback](https://github.com/WordPress/gutenberg/blob/c54c0020a7a8ebf22738aa96cb398ea4cf17a30a/packages/block-library/src/image/view.js#L168) would need to modified to make the margin support compatible with the lightbox.

2024-07-16 00:43 UTC, aaronrobertshaw commented
Thanks for reviewing @artemiomorales 👍 

I honestly missed testing image lightbox functionality when adding the margin support here 😅 

From what you've outlined though it sounds like there is a more general problem with lightbox not taking into account image styles that affect spacing such as margin and border, than a problem with the application of margins on an image.

It is worth noting that you can already define margins for images via theme.json. Does this not also cause a problem or is the issue that block support styles are applied as inline styles and override lightbox resets etc?

Do you think this issue needs to block the adoption of margin support for all images? Can it be addressed separately via 
https://github.com/WordPress/gutenberg/issues/63567?

2024-07-16 19:41 UTC, artemiomorales commented
> It is worth noting that you can already define margins for images via theme.json. Does this not also cause a problem or is the issue that block support styles are applied as inline styles and override lightbox resets etc?

@aaronrobertshaw It appears that the lightbox works as expected when defining the margin via theme.json — the issue, as you've pointed out, is that the styles are applied inline, notably to the parent `figure` element.

> Do you think this issue needs to block the adoption of margin support for all images? Can it be addressed separately via
https://github.com/WordPress/gutenberg/issues/63567?

I think so, otherwise anyone who adds a margin to an image with `Expand on Click` will see a broken experience, which could reduce confidence in the feature. I'm open to hearing other opinions on that, though. In any case, I've started looking at the lightbox code to see how we could resolve it.

Would it be alright if I worked on that this week as part of this PR? I'm happy to hear other ideas too, let me know what you think 🙏

2024-07-16 22:18 UTC, artemiomorales approved these changes
@aaronrobertshaw It turns out that the lightbox copies the figure's inline styles in the overlay, and the new margins were throwing off the calculations. I pushed a commit to remove the margins from the overlay, and it seems to work properly now.

I can do another smoke test tomorrow but will go ahead and approve so you can merge if you're feeling confident with all of the use cases 🙏

2024-07-17 04:04 UTC, aaronrobertshaw commented
@artemiomorales are there unit tests for the lightbox behaviour that can be updated to protect against regressions?

2024-07-17 04:50 UTC, artemiomorales commented
> are there unit tests for the lightbox behaviour that can be updated to protect against regressions?

@aaronrobertshaw There were but they need to be redone. I can take a look at that tomorrow, as part of this PR or a separate one, whichever you prefer.

2024-07-18 03:12 UTC, artemiomorales commented
@aaronrobertshaw Ok I added a test to ensure the margin inline styles don't get applied to the overlay image 👍

2024-07-18 05:23 UTC, aaronrobertshaw commented
Really appreciate the help getting the lightbox behaviour sorted @artemiomorales, thanks 👍 

I've given this PR a run both before and after the latest updates. The animation looks nice and smooth again.

https://github.com/user-attachments/assets/6089fe5e-00ce-4f6e-8acc-dccbc357a1e5

2024-07-18 05:49 UTC, andrewserong approved these changes
I'm not very familiar with the lightbox code and it took me a little while to find the control for it (is the only place it's exposed in global styles > blocks > image?). But it's working nicely!

✅ Image margin set in global styles is output correctly in post and site editors and on the site frontend
✅ Block level instance overrides work correctly
✅ In manual testing the lightbox feature still appears to be working as expected AFAIK

LGTM! 🚀

2024-07-18 06:00 UTC, aaronrobertshaw commented
Thanks for the review @andrewserong 👍 

> is the only place it's exposed in global styles > blocks > image?

There is also the link block toolbar button. Under that you'll have the option to choose "Expand on click".

I agree though, the discoverability of it isn't fantastic. It took me a while and I knew it was there and was actively looking for it.

2024-07-18 06:03 UTC, merged

2024-07-18 06:05 UTC, andrewserong commented
> There is also the link block toolbar button. Under that you'll have the option to choose "Expand on click".

Thank you! That was a TIL for me, I didn't realise it was under there, I was looking at the inspector sidebar. Cheers!