Improve the various Alignment controls props handling
WordPress/gutenberg pull request #63696
Opened 2024-07-18 10:00 UTC by dhananjaykuber

Fixes [#63649](https://github.com/WordPress/gutenberg/issues/63649)

## What?
This PR standardizes and improves the labels and descriptions for alignment controls across various blocks (Paragraph, Table, Group, and Media & Text) to enhance clarity and accessibility.

## Why?
The current implementation has inconsistent and sometimes misleading labels and descriptions for alignment controls. This leads to confusion for users, especially those using screen readers. Standardizing these elements will improve the overall user experience and accessibility of the Gutenberg editor.

## How?
- Updated the AlignmentControl, BlockAlignmentUI, and BlockVerticalAlignmentUI components to accept and properly use label and description props.
- Modified the usage of these components in Paragraph, Table, Group, and Media & Text blocks to provide more accurate and consistent labels and descriptions.
- Ensured that all alignment controls have appropriate `aria-describedby` attributes.

## Screenshots or screencast 
**Paragraph**
<img width="688" alt="Screenshot 2024-07-18 at 3 20 34 PM" src="https://github.com/user-attachments/assets/be34dc6f-ff01-441c-aa4a-4d6d21515411">
<img width="529" alt="Screenshot 2024-07-18 at 3 21 01 PM" src="https://github.com/user-attachments/assets/a1023810-81eb-4712-80f7-a1d214fc9a47">

**Table**
<img width="649" alt="Screenshot 2024-07-18 at 3 21 17 PM" src="https://github.com/user-attachments/assets/7d6f9564-bbbe-43b8-b981-07ac244a4604">
<img width="531" alt="Screenshot 2024-07-18 at 3 21 31 PM" src="https://github.com/user-attachments/assets/3bc36bf2-f28f-46da-af30-4aabf7b1c771">

**Group**
<img width="654" alt="Screenshot 2024-07-18 at 3 22 06 PM" src="https://github.com/user-attachments/assets/65651bf2-4c99-412b-8a01-5f7d328ae65b">
<img width="529" alt="Screenshot 2024-07-18 at 3 22 17 PM" src="https://github.com/user-attachments/assets/364b42de-03a3-4209-bd25-1ad51d83c008">

**Media & Text**
<img width="689" alt="Screenshot 2024-07-18 at 3 22 31 PM" src="https://github.com/user-attachments/assets/e11ddc15-43c8-44b4-ab26-8264dcf14c6b">
<img width="530" alt="Screenshot 2024-07-18 at 3 22 40 PM" src="https://github.com/user-attachments/assets/22f29dc4-e414-4ae3-b04c-854cff96910c">

2024-07-18 10:11 UTC, dhananjaykuber commented
Writing test cases.

2024-09-23 12:56 UTC, afercia commented on packages/block-library/src/table/edit.js
>  							label={ __( 'Change column alignment' ) }
I'd change this label to use a more consistent wording with the other labels. Something along the lines of 'Align columns content' would be clear enough to amke the description not necessary.

2024-09-23 13:02 UTC, afercia requested changes
Thanks for this PR!
From an accessibility perspective I like the idea of making all these controls consistent to:
- Have a clear label that uses the same pattern.
- Have the ability to provide an optional description.

To me, all the labels should start with the verb `Align` so that I would suggest to change the label of the table block.

I;d think that all the labels are clear enough, there's no need to provide a description which would be a littl eredundantl For example:

label: "Align block"
description: "Change block alignment"

The label is already clear enough. I'm not sure it needs a description.

The one for the table columns could be:

label: "Change column alignment"

and not need the description "Adjust the alignment of content within table columns".

I'd appreciate a review from @wordpress/gutenberg-core

2024-10-07 14:36 UTC, colorful-tones commented
@ndiego @kevin940726 

WP 6.7 Beta 2 is tomorrow - it seems there has been little movement on this and I'm thinking we should punt it to 6.8. Thoughts?

2024-10-08 02:21 UTC, kevin940726 commented
That makes sense to me 👍.

2025-01-06 13:19 UTC, dhananjaykuber commented
[screen-capture.webm](https://github.com/user-attachments/assets/77d7ca0e-98f7-49d8-8626-cba2d7936591)

2025-01-06 13:20 UTC, dhananjaykuber commented
Please check I have removed unnecessary description and just added clear labels for controls 

Thank you

2025-08-22 06:18 UTC, t-hamano commented
This issue has been punted to 6.7. Let's move this issue to the 6.9 Editor Tasks board and see what's possible in 6.9.

@dhananjaykuber Could you rebase this PR on top of the trunk branch so that we can review this PR again?

2025-08-22 06:28 UTC, dhananjaykuber commented
> This issue has been punted to 6.7. Let's move this issue to the 6.9 Editor Tasks board and see what's possible in 6.9.
> 
> @dhananjaykuber Could you rebase this PR on top of the trunk branch so that we can review this PR again?

Hi @t-hamano I’ve rebased the branch on top of the latest trunk.

2025-08-23 04:30 UTC, t-hamano commented on packages/block-editor/src/components/alignment-control/ui.js
> +	label = __( 'Align block' ),
```suggestion
	label = __( 'Align text' ),
```

As the component's icon indicates, this component essentially controls "text" alignment:

<img width="249" height="196" alt="Image" src="https://github.com/user-attachments/assets/da02eeee-7044-42a9-8234-dc3506486a9e" />

I think the label "Add block" is misleading. Launch Storybook and a screen reader to test the default behavior of this component.

2025-08-23 04:30 UTC, t-hamano commented on packages/block-editor/src/components/block-alignment-control/ui.js
> +					: {},
Isn't this the `description`, not the `aria-description`?

2025-08-23 04:30 UTC, t-hamano commented on packages/block-editor/src/components/block-vertical-alignment-control/ui.js
> +	),
```suggestion
	label = __( 'Align content vertically' ),
```

I think the context is redundant.

2025-08-23 04:30 UTC, t-hamano commented on packages/block-editor/src/components/block-vertical-alignment-control/ui.js
> +	description,
This means that the `BlockVerticalAlignmentUI` newly supports the `description` prop. However, I don't think there's any use of this component with the description prop yet, so I'll recommend reverting this change and consider adding the description prop in a follow-up if needed.

2025-08-23 04:30 UTC, t-hamano commented on packages/block-library/src/paragraph/edit.js
> +						label={ __( 'Align text' ) }
We can delete this prop if the default `label` prop value of the `AlignmentUI` becomes `Align text`. See https://github.com/WordPress/gutenberg/pull/63696#discussion_r2295091674

2025-09-22 15:14 UTC, t-hamano commented
@dhananjaykuber Do you have the bandwidth to move this PR forward? Thank you!

2025-09-22 15:16 UTC, dhananjaykuber commented
Hi @t-hamano , so for the delay. I'll work on this feedback today. 

Thank you 

> @dhananjaykuber Do you have the bandwidth to move this PR forward? Thank you!

2025-10-20 14:24 UTC, t-hamano commented
With WordPress 6.9 Beta 1 just around the corner, so I'd like to punt this to 7.0.

2025-10-20 14:41 UTC, mcsf commented
> With WordPress 6.9 Beta 1 just around the corner, so I'd like to punt this to 7.0.

Agreed. This is worth spending time on to catch all the nuances.

2025-10-21 15:16 UTC, priethor commented
+1 to punting to 7.0

2026-03-06 01:34 UTC, t-hamano commented
As the 7.0 Beta release is underway, let's punt this PR to 7.1.

2026-05-31 12:08 UTC, t-hamano commented on packages/block-editor/src/components/alignment-control/ui.js
> +	label = __( 'Align block' ),
Fixed in c7989c87cb1618c737e295f6aa3cc47aa40461be

2026-05-31 12:09 UTC, t-hamano commented on packages/block-editor/src/components/block-vertical-alignment-control/ui.js
> +	description,
Fixed in https://github.com/WordPress/gutenberg/pull/63696/changes/a7b3a94d87d3eea65bb0978f7856b16f45cde87e

2026-05-31 12:09 UTC, t-hamano commented on packages/block-editor/src/components/block-vertical-alignment-control/ui.js
> +	),
Fixed in e087b707deb94b2296674b4ce5ab875996edbc4f

2026-05-31 12:10 UTC, t-hamano commented on packages/block-editor/src/components/block-alignment-control/ui.js
> +					: {},
Fixed in a7b3a94d87d3eea65bb0978f7856b16f45cde87e

2026-05-31 12:11 UTC, t-hamano commented
I have resolved the conflicts and applied the changes I proposed. I welcome any additional feedback.

2026-07-22 13:45 UTC, getdave approved these changes
This is looking good to me

Nit: I noticed the label `Align columns content` Since this action applies to the selected column only, should this be `Align column content`?

2026-07-22 14:31 UTC, t-hamano commented
> Nit: I noticed the label `Align columns content` Since this action applies to the selected column only, should this be `Align column content`?

Nice catch, I will merge this after fixing it.

2026-07-22 15:27 UTC, merged