Update "Edit site" admin bar link to open Site Editor at top level
WordPress/gutenberg pull request #63835
Opened 2024-07-23 06:38 UTC by dhananjaykuber

Fixes [#63785](https://github.com/WordPress/gutenberg/issues/63785)

## What?
This PR updates the "Edit site" admin bar control to consistently open the Site Editor at the top level, rather than opening the specific template editing view of the current page.

## Why?
This change is necessary to improve user experience and consistency within the WordPress editor. Currently, the "Edit site" control behaves unpredictably, dropping users into various levels of the Site Editor depending on the page they're viewing. This can be disorienting and makes the control less effective as an entry point to the Site Editor.

By making this change, we align the behavior with the "Editor" control in the WP Admin > Appearance menu, providing a more predictable and consistent experience for users.

## How?
The implementation involves modifying the link destination of the "Edit site" admin bar control. Instead of linking to the specific template editing view, it will now link to the top-level Site Editor page.
```php
$wp_admin_bar->add_node(
	array(
	        'id'    => 'site-editor',
		'title' => __( 'Edit site' ),
		'href'  => admin_url( 'site-editor.php' ),
	)
);
```

## Testing Instructions
1. Ensure you're using a block-based theme.
2. Visit different pages on your site's front-end (homepage, a blog post, a static page, etc.).
3. Click the "Edit site" link in the admin bar for each of these pages.
4. Verify that regardless of which page you're on, clicking "Edit site" always takes you to the top-level Site Editor view.
5. Confirm that you're not dropped into a specific template editing view.

## Screenshots or screencast 
https://github.com/user-attachments/assets/6da0c123-8761-43bd-b67f-6644f7be99cb

2024-07-23 06:55 UTC, carolinan requested changes
This needs to be changed in the 6.7 folder, not 6.6.

2024-11-08 20:44 UTC, richtabor commented
@dhananjaykuber do you mind addressing the feedback? Thanks!

2025-01-07 05:04 UTC, carolinan commented
Hi
Since 6.7 has already been released, this folder can't be used. It needs to be in a folder for the next major release.

2025-01-07 05:42 UTC, dhananjaykuber commented
Hi @carolinan,
Thank you for pointing that out. I’ll ensure that this is added to the folder for the next major release.

2025-01-11 19:07 UTC, richtabor commented
Intrigued to get this in a good state. What can I do to help? 

I'm seeing more and more WordPress users getting unintentionally placed in the Site Editor by selecting this; resulting in getting lost/confused.

2025-03-05 05:16 UTC, carolinan commented
I am closing this in favor of https://github.com/WordPress/gutenberg/pull/69271 because there are some changes in this PR that are unrelated to the issue.

2025-03-05 05:16 UTC, closed without merging