Made media library update on open
WordPress/gutenberg pull request #6390
Opened 2018-04-24 15:14 UTC by jorgefilipecosta

This PR updates media library when it is opened, this makes sure that if a new item was inserted since the last time the library was opened it will appear in the media library.

Fixes: https://github.com/WordPress/gutenberg/issues/4612

## How has this been tested?
Add 3 empty image blocks.
One the first select an image from the media library.
On the second drag&drop an image that is not on the media library from your computer to the image block.
On the third open the media library and verify the image that was added in step 2 is shown in the media library (in master it was not).

2018-05-03 14:09 UTC, youknowriad requested changes
It does fix the bug you mention but it creates another one. Try uploading image inside the media library, you won't be able to select it. In master it works.

2018-05-09 22:08 UTC, jorgefilipecosta commented
Hi @youknowriad, thank you a lot for catching this issue!
I have been trying and "battling" to find a clean way to refresh the media library and I was not able to find a good approach. I was able to find a big hack that seems to work fine, but unfortunately, I don't think is something mergeable but may be a tip for a correct approach.
I will think continue to think about other way. Unfortunately, I'm not familiar with the media library and Backbone.js so If anyone as a tip to handle this problem it is totally welcome. I tried using reset, fetch and other common methods but all of them were impossible to use or did not refresh the gallery.

2018-09-13 18:50 UTC, aduth commented
Is it likely this will be resumed, or can it be closed?

2018-09-13 19:06 UTC, jorgefilipecosta commented
I am Not sure, I mean in order to fix the bug we need to request all images each time we open the media library (to know if new media was added in parallel) but that makes the open of the media library slower, it is a tradeoff that we should make.

2018-09-13 20:07 UTC, aduth commented
Since we have an issue tracking it (#4612), I'll err on the side of closing until a decision can be made.

2018-09-13 20:07 UTC, closed without merging