Docs: Add documentation for `render_block` and `register_block_type_args` to Block Filters
WordPress/gutenberg pull request #64118
Opened 2024-07-30 19:46 UTC by ndiego

Fixes https://github.com/WordPress/gutenberg/issues/64037

## What?
The documentation for [Block Filters](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/) currently does not mention the `register_block_type_args` or `ender_block`/`render_block_{block/name}` filters, which are some of the most used filters for extending and modifying blocks.

This PR adds brief descriptions and an example for each as well as a few other edits. Further edits will be needed for this page as some of the other filters are missing examples. I will tackle that in a follow-up PR.

2024-07-31 08:03 UTC, juanmaguitar commented
I'm missing some guidance in this page about the mixture of PHP and JS functions.
We could add some brief intro of the type of APIs available for each section (Registration, Frontent, Editor...) and some context for that.

For example, registration happens on both the server and the client, so there are APIs to modify block metadata before registration on both sides, but the editor part only happens on the client, so there are only JS functions to alter this side of the block's management.

This could be helpful for developers to understand (and remember) the possibilities and limitations of these filters.

2024-07-31 08:04 UTC, juanmaguitar requested changes

2024-07-31 08:04 UTC, juanmaguitar commented on docs/reference-guides/filters/block-filters.md
> +## `render_block_{namespace/block}`
Shouldn't this be a h3 heading `###`?

2024-07-31 08:04 UTC, juanmaguitar commented on docs/reference-guides/filters/block-filters.md
> +## `render_block`
Shouldn't this be a h3 heading `###`?

2024-07-31 17:28 UTC, ndiego commented on docs/reference-guides/filters/block-filters.md
> +## `render_block_{namespace/block}`
Fixed

2024-07-31 17:28 UTC, ndiego commented on docs/reference-guides/filters/block-filters.md
> +## `render_block`
Fixed!

2024-07-31 17:30 UTC, ndiego commented
> For example, registration happens on both the server and the client, so there are APIs to modify block metadata before registration on both sides, but the editor part only happens on the client, so there are only JS functions to alter this side of the block's management.

I added a section about this and also linked to the [block registration](https://developer.wordpress.org/block-editor/getting-started/fundamentals/registration-of-a-block/) guide for more info.

2024-08-01 16:05 UTC, juanmaguitar approved these changes

2024-08-01 16:05 UTC, merged

2024-08-03 13:12 UTC, gziolo commented
Cool, thank you for improving this document 👍