Improve the G in Gutenberg
WordPress/gutenberg pull request #6418
Opened 2018-04-25 13:49 UTC by pento

## Description

While the "Welcome to Gutenberg" message at the end of `bin/setup-local-env.sh` is cute, it was missing something. Something important. Something magical. Something... wavy.

This PR improves the G, to more closely match Gutenberg's actual logo.

## Screenshots

*Before*

<img width="467" alt="The Gutenberg ASCII art at the end of the setup script" src="https://user-images.githubusercontent.com/352291/39249795-ca7d3928-48e2-11e8-888e-d702a8e3a524.png">

*After*

<img width="457" alt="The Gutenberg ASCII art at the end of the setup script" src="https://user-images.githubusercontent.com/352291/39249755-b82bdb26-48e2-11e8-99d5-0b0a071362c6.png">

2018-04-25 13:54 UTC, jdevalk commented
https://www.youtube.com/watch?v=Xi3aEGo8y-E

2018-04-25 13:58 UTC, pento commented
![You have distracted from my creative process](https://user-images.githubusercontent.com/352291/39250592-7df03324-48e4-11e8-83f4-a4ac6035e3a1.png)

2018-04-25 14:02 UTC, Soean approved these changes

2018-04-25 14:13 UTC, youknowriad requested changes
I should have made the PR 😆

2018-04-25 14:26 UTC, pento commented
@youknowriad:

<img width="575" alt="https://twitter.com/kanyewest/status/987727961477472257" src="https://user-images.githubusercontent.com/352291/39252094-3b2e1da4-48e8-11e8-89c5-ac90d4824589.png">

@jasmussen:

<img width="578" alt="https://twitter.com/kanyewest/status/988571191651713024" src="https://user-images.githubusercontent.com/352291/39252179-6c2879fe-48e8-11e8-9cea-b1c1d8d693d1.png">

2018-04-25 14:44 UTC, aduth commented on bin/setup-local-env.sh
> +|  ،~’.   . |---  ,---. ,---. |---. ,---. ,---. ,---.
The standard tilde is perhaps a bit too harsh. What do you think of "Swung Dash" `⁓` (U+2053)?

2018-04-25 14:56 UTC, jasmussen commented
"Build Tooling"

2018-04-25 14:59 UTC, mzorz commented
I love it.  It brings memories of my good old BBS times.

2018-04-25 15:30 UTC, notnownikki commented
Retina displays will need this alternate version

```
`shhhhhdh-.yhhhhhhhhhhhho  .od+          .-//:-`    `.://:-`         .yh/` `+hhhhhhhhhhhhy-+hhhhhhh+
.mm/:::/:-::////+ss+////- /mm/-+s+.   `+dmdhyhmmh++sdmdhydmmy-    -+s+:sNh. .::/+ss/:::::/--:::::oNh
.dh`    `oy`   .hMNmmy:` .dN.-mNsmm.`/mmo.    `oNMMMd-`   `:hNy. :mmsNd.sM+ `:ymmNMh.    so.     :my
 ..  `:sy:`/ds. .sNdohmds+mN-.ymdmy.sNd//+syhddNmssyNmddhyo+:oNd-.ymdms.hMoodNhohNy. .sd+``+yo:` `-.
.dy`-dmdMs``oNNs:`-ohdNMNmdmm+:://+dMMmdhso/:-hN+  .dN/:/+oyhdNMNs///:/dNdmNMNdhs-`-smNs. .dMhmh`:my
-Nh`oMmmd:   -dMNdo:-.--..`.omNmmmdy+:.``    -Nd.   oNs     `.-/ohdmmNNs-`..-..-:odNMd-    +mdmM-:Nh
-Nh`.oo:.     .hMMMmddysoosydmho:.`    `-:/oshNs    -NNyo+/-.`   ``:ohmdhsoosyhdmMMMd.      ./o+`:Nh
-Nh` `+hhdh+.  -dMNms//+oo+/-.`  `.:+yhddhysosNy.  `/Ndooyyhddhs/-`  `.-/+oo+//smNMm-  .+hdhh+`  :Nh
-Nh` `/+::+mm:  oNyomd/`      `-ohddyo:-```  `omdyshmh-   ``.-/ohddy/.      `:hmosNs  :mm+::+/`  :Nh
-Nh`       /My  /Nh`-yNh:::-:sddy+-`      ``..-/omNh+:-.``      `.:ohmh+:///ymy- yN+  yM/        :Nh
-Nh`     `-hN+  oNs  `+NNhhmNd/.`    `.:+shhddhdNMMNmhhdhhyo/-.     `-sNmhymMs`  +Ns` +Nh-`      :Nh
-Nd+syyhhhdy:` /mm.   +My``oNy`  `./shdhyo/-.-ommo/hNy/..:+oyddho:`   /Nh.`/Mh`  `dN/ `:ydhhhyys/+Nh
-NNds++/:-.` `omd:   .sNmysdNs`./ydds/-`   .+dmo.  `:hmy-   `.-+yddo  :NNhydNd:   -hmo` `.-:/++sdNMh
yNs./hddy:  -hNo.  `:dmo/o+/yNhmdo:`     `/dmo.      `/hms-      .//-smh/://:yNs.  `oNh-  .sddho.sMd
Nm-`mm+oMy`:dm/   `oNh-/hy--yNmNo.     `+dmo.          `:dms-     `+md+-:`:dy:+md:   /md:`oMy/dN--mN
hNo.+hddh::md:   .hNo-sNh:omd/.omd/`   +ds-              `/ys   `/hNo. +mh/+dm+:hN+`  :dN:.sdddo.oNh
.smho////omd:   -dN+-hmo:dmo`   -ymh-   `                  `   .ymy-    :hNo-yNs-yNo`  -dmo///+ohms.
 `-+syhhdNN:   .hN/-dm//mm:      `:hy.                        `sh/`      `oNy-sNy.hN+`  -NMdhhys+-` 
-hs/-..`sMo   `yN+.dN//mm.     `-. ``                          `` `-.      +Nh.sNs.hN/   /Nh.`..-oho
:Mmddds:Nd`   +My`yM+-Nm-    `:ymo`              ```              -dmo.    `oNy.yM/:mm`  `sM+-ddddMh
:My````hN/   `mm:-Mh.dN/   `:hmy-            ./syhhhyo/.           `+dmo.   `yN+:md`oNo   -mN.`` :Nh
:My`  .Nd-   +Ns sN++Ny`  -yNy:            `omms/---/omm+            `+mmo.  .md-hN/-md.   sM+   :Nh
:My`  /My` `.hN/ .:-dN- -hNh:              yMy`       -dM:             `omm+. sMo./``hN+`` :Nd`  :Nh
:My`  oNyoydmmNmh+ :md-yNh:`              -Mm-         :+`  `-`          .+mm+:My``+hmNmmdyomm-  :Nh
:My`  yMNy+-.` -yNsoNNNh:                 +Mh.           `-omh.            `omNMd:hNs. `.:odMm:  :Nh
:My`  hMy.      :NNmMMy.                  +Mh.     .+yhdmmds:               `:NMNmMm-     `-mN/  :Nh
:My`  sMNmds+::omN:/Nmmmo`                +Mh.   `smy/:dM/                 -yNdNd.+Ndo:/+sdNMm:  :Nh
:My`  oNs./oyNNh+. :md.omm+.              :Md-   -y:  .hM/               -yNh::My` .+mMdyo:-mm-  :Nh
`:-   :Mh`   yN+   `hN: .omm+`            `dMs        .dM:             -yNd:` yN+   `dN/   :Nd`  `:-
-d+   `mm:   :Nh`   /Ny`  .omm+`           .yNh/-.`.-/dNs`           -yNh:`  :Nd.   :Nh`   sMo   -ys
.os+`  oMs`   dN/   `hN+    .smm+`          `-ohdhhhhyo-`          .ymd/`   .hN/   `yN/   -dN.  :ss+
.sys.  .dN-   -Nd.   .mN/     .omd+`            `````            -smh/`    `sMs    +Nh   `sMo  `/yy+
-yhhs.  /Nh`   +Nh`   :dN:      -smd/`                         .smd/`     `yNs`   :md-   :Nd.  /hhhs
-yyyyo` `sNs`  `sNs`   -dN+`      -smd/`                     -smd/`      -yNo`   -mm:   .mm:  /yyhyo
.ossso:` `yNo`  `oNy.   .yNy-       -smh/`                 .omd+`      `+mm/`   /mm:   .hN/  -+ssss+
-yyyyhy:  `hNo`   oNd-   `/dmo.       -ymh/`             .omd+.      `:hNy-   `oNd-   -hN/  `syyyyyo
-hhhhhhho` .sNs.  `/dm+.```.odms-`     `:ymh/`         .omd+.      `/hmy:````-hNy-   :mm/  :yhhhhhhs
`:oy/:+so+- `+NhosyhdNNdhhhhyymMNh+.`    `-ymh:`     .odm+.     `:odMNdyhhhhhmNmhhyosmd: `/+so/:os+-
`oNh.`+hhh+`` :dMm+:---.---:/+oyhdmmho/-`  `:ymh:` .+ddo.  `.-+ydmmdhso+:----.---:yNNs` `-yhhs-`/md-
-Nm..shhhhhho` .omh/.-://+++//:---:/oyddhyo/::+dNyodNs::/+syddhs/:---:://+++//:--smh:  :yhhhhhh/`+Ny
-Nh`.o+-:ossoo+. .smNNdyysssyyhhddhyo/:-:+oyhhhdmNMNmhhhhso/:-:+syhdhhhyysssyymNNd/` /oosss+--o/ :Nd
`hN+-o: .+sssss:..`-smh+........--:+shdhs/.```...hN+..````-+yddho/:-........:smd+....osssoo: `+/.hN/
 .ymy/-````so.yddh/  .odmmNmhdddhys+:--/sdmh+-`  yN/  `-odmh+:--/oshhddhdmNmmh/`  yddh/:y:```.:odm+`
  `/mNNdhyys+-...`     `:ymmy+:-:/oyddhs:.-odmy:`hN/.+hmh/-./yddhs+/:::odmdo-`    ```..:osyhhmNMy-  
 `omho/oy+/ohmy-          `:sddho:.``./ymms-`:yNmmNdmmo-./ymdo:.``-+ydmh+-          `+mmy+/sy:+yNh: 
`sNs``.mm:  `:md-           `./smNNdyo/-:+hmh/oNh/-omd-+dms/-:+shmNNh+-`            oNy.  `yN+``:mm-
-NNoshmh:     sMo.`       .+ydmdhhdmNMMNddhmMMMd.   +NMMMdddmMMMNdhhhdmds:`      `.:dN-    .smdyohMs
:Nmy+/-.    `:mMmdmh:   .ymd+-..://::+yNd+::/oNm:  `sNy/:::smdo:-:/:-../ymd/`  .sddmNMy.    `.:/shNy
 .`   /dy+/+yNMm:.:mN. :mm/` :hmdhhmms--hNo   :mm/-yNy`  -dNo.+dmdhdmd+` .yNs``oMs..sMMds//ohy.  `.`
 -/////omMMNdoNNy+sNm+omM/` +Mh:   :hMNosmM/   .sNNd/`  `mMhodMmooo-.sNh` .dMy/yMm+omMysmMMNh+/////-
`+yyyyyyyyyyyyyyyhyyyyyyhs` :+.    :oosoooo:     oh-     +ooooooooo- `/+` /yyyyyyyyyyyyyyyyyyyyyyyy+
```

2018-04-25 15:36 UTC, aaronjorbin commented
This PR seems like it was 
![jw9hbla](https://user-images.githubusercontent.com/622599/39256391-c77ab57c-487c-11e8-84ed-80a1eb4ba7a8.png)

2018-04-25 17:13 UTC, notnownikki commented
I'm pretty sure this impacts embeds in some way.

2018-04-25 21:39 UTC, mcsf commented
Can we get some regression tests for this before merging?

2018-04-26 02:57 UTC, pento commented
@notnownikki: I love the work on the retina image! Let's do a followup PR that detects the screen DPI in the terminal, as it feels like it might be a bit out of scope for this PR.

@aaronjorbin: You have no idea, this is like my 10th revision.

@jasmussen: Thank you for the accessibility aspect, it's important to consider. The good news is, the poor contrast is entirely down to my choice of Terminal themes: most default themes will display it as #FF00FF (or something similar) against #000000 (again, or something similar), which has [pretty good contrast](https://webaim.org/resources/contrastchecker/?fcolor=FF00FF&bcolor=000000).

There are also a many high contrast Terminal themes available for every terminal app and platform that you choose to use.

Though, this does bring up the point of screen readers. Obviously, no screen reader would be able to make sense of this output, but I'm not aware of a way to provide a plain text alternative for it. Interestingly, [MUDs](https://en.wikipedia.org/wiki/MUD) have done a lot of work on providing accessible terminal interfaces, but that hasn't filtered back to the various terminal apps.

@mcsf: As this is a highly visual issue, perhaps an appropriate regression test would be a bot that takes a screenshot of the G and posts it to every PR, for manual confirmation?

2018-04-26 04:47 UTC, merged

2018-04-26 04:56 UTC, noisysocks commented
<img width="576" alt="screen shot 2018-04-26 at 14 54 43" src="https://user-images.githubusercontent.com/612155/39286573-f6b0f3e8-4961-11e8-85a4-2128e433daf4.png">

2018-04-26 06:37 UTC, jasmussen commented
Did you address Riads' concerns? https://github.com/WordPress/gutenberg/pull/6418#pullrequestreview-115195151

2018-04-26 06:51 UTC, pento commented
@jasmussen: I feel that Kanye sufficiently addressed @youknowriad's concerns. 

That said, I do understand how it may not have been entirely satisfactory. Thankfully, Kanye has chosen to re-address those concerns.

<img width="581" alt="https://twitter.com/kanyewest/status/989268464392011776" src="https://user-images.githubusercontent.com/352291/39290142-f5ea7e56-4971-11e8-9dbb-3bfcc6628525.png">

2018-04-26 07:02 UTC, jasmussen commented
Okay. I also see that you properly milestoned it too. We'll let it slide. This time. 

I'm watching you: 👈✌️👀