Update: Move item size control to the new view config UI.
WordPress/gutenberg pull request #64380
Opened 2024-08-08 16:55 UTC by jorgefilipecosta

This PR moves the item size picker to the new view configuration UI.
Follow up to https://github.com/WordPress/gutenberg/pull/64175.

cc: @WordPress/gutenberg-design 

## Screenshots
<img width="405" alt="Screenshot 2024-08-08 at 17 55 12" src="https://github.com/user-attachments/assets/2841ace4-6abb-4335-9e87-c11d6bd4db21">

## Testing Instructions
I verified the item size picker is only available on the grid layout and still works as expected.

2024-08-12 06:58 UTC, jasmussen commented
I wonder if instead of the eye icon we should try a check-box based interface. The eye doesn't feel super clear here. The closed eye also isn't super clear, I wonder if we shouldn't refresh it to be the eye but with a diagonal line across.

2024-08-12 12:54 UTC, jameskoster commented
> be the eye but with a diagonal line across

Happy to try that separately, I don't think that icon exists in the set yet.

@jorgefilipecosta thanks for the work so far, a couple of small suggestions:

* Would it be possible to add marks to the range, like the example [here](https://wordpress.github.io/gutenberg/?path=/story/components-rangecontrol--with-integer-step-and-marks)?
* In this context I think we can remove the `-` / `+` buttons.
* "Item size" → "Preview size".
* Apply `__next40pxDefaultSize` to the range.

2024-08-12 22:13 UTC, jorgefilipecosta commented
> I wonder if instead of the eye icon we should try a check-box based interface. The eye doesn't feel super clear here. The closed eye also isn't super clear, I wonder if we shouldn't refresh it to be the eye but with a diagonal line across.

Hi @jasmussen, seems like something we can try, I can have a look in a different PR.

@jameskoster all your feedback was applied.

2024-08-13 11:08 UTC, jameskoster commented
Thanks @jorgefilipecosta, I'm seeing two small issues...

Sometimes I'm unable select the last value in the range, here's a video to demonstrate:


https://github.com/user-attachments/assets/dd8cd1ef-fca8-4b64-a3a1-54108d12925c



Probably separate but the appearance of the marks is a bit buggy. I think they should rest on top of the track rather than above it, something like this:

<img width="319" alt="Screenshot 2024-08-13 at 12 06 13" src="https://github.com/user-attachments/assets/91f17edc-b1ae-4bcc-9284-b75c33d6723d">

Maybe @WordPress/gutenberg-components has some insights there.

2024-08-13 12:15 UTC, jorgefilipecosta commented
Hi @jameskoster, the bug was fixed 👍

Regarding the marks I agree that your proposal seems like a preferred behavior, but I think we can fix it outside of this PR. The fix is on the component is even on the stories https://wordpress.github.io/gutenberg/?path=/story/components-rangecontrol--with-integer-step-and-marks it shows the UI as in this PR.

2024-08-13 13:53 UTC, jameskoster commented
Thanks for the fix, it's working now :)

For the marks I suppose the question is whether or not this PR should be blocked by the visual bug. I suppose the other option would be to remove them for now and open a follow-up later once the display issue has been fixed. What do you think?

2024-08-13 14:23 UTC, tyxla commented
> For the marks I suppose the question is whether or not this PR should be blocked by the visual bug. I suppose the other option would be to remove them for now and open a follow-up later once the display issue has been fixed. What do you think?

Looks unrelated to this PR.

I can repro in Storybook:

![Screenshot 2024-08-13 at 17 21 44](https://github.com/user-attachments/assets/9a876288-3d7e-4d29-80e0-f84eb63a3adc)

@mirka could this be a recent regression caused by any of our work on #38730?

2024-08-13 14:54 UTC, mirka commented
> @mirka could this be a recent regression caused by any of our work on #38730?

No, I think the positioning of the marks was weird like this, for as long as I can remember 😅 I don't even know what the intended design was, but it does look like it was vertically centered on the line, originally (#19916). We should definitely fix it — I assumed it was an outdated feature or something because we never really heard about the visual issue.

2024-08-13 15:10 UTC, jameskoster commented
It's complicated further by `SpacingSizesControl` which has different mark styling 😓

I think the way to proceed here is;

* Remove the marks in this PR.
* Fix mark positioning in the component.
* Follow-up to add marks to this control once the positioning is fixed in the component.
* Potentially consolidate mark styling with `SpacingSizesControl`.

2024-08-13 16:10 UTC, jorgefilipecosta commented
> It's complicated further by `SpacingSizesControl` which has different mark styling 😓
> 
> I think the way to proceed here is;
> 
> * Remove the marks in this PR.
> * Fix mark positioning in the component.
> * Follow-up to add marks to this control once the positioning is fixed in the component.
> * Potentially consolidate mark styling with `SpacingSizesControl`.

@jameskoster, Sounds like a good plan, following it, I removed the marks.

2024-08-13 17:07 UTC, jameskoster approved these changes
Nice. This is working well for me an tidies things up compared to trunk so I'm happy to approve the design. We can always follow up to finesse.

I'll open an issue about the marks bug.

2024-08-13 17:18 UTC, jameskoster requested changes, later dismissed
Actually, I noticed the range control is backwards haha. As you slide to the right the preview should get larger, it's currently the other way around :)

2024-08-13 22:16 UTC, jorgefilipecosta commented
> Actually, I noticed the range control is backwards haha. As you slide to the right the preview should get larger, it's currently the other way around :)

Hi @jameskoster, I missed a commit push, it should be fixed.

2024-08-14 05:58 UTC, jasmussen commented
Forgive me for jumping in randomly with a possibly context-lacking question: can this use the same design as the existing stepped slider we have?

2024-08-14 13:54 UTC, t-hamano reviewed
Unrelated to this PR, but I noticed that the Order button doesn't work.

The strange thing is that once I change the Sort By field to something other than Title, the Order button works:

https://github.com/user-attachments/assets/21f9a602-3c5c-4728-a6ff-c20e0bc0aece

2024-08-14 13:54 UTC, t-hamano commented on packages/dataviews/src/dataviews-layouts/grid/density-picker.tsx
> +			className="dataviews-density-picker__range-control"
This selector is no longer used anywhere so I think it can be removed.

2024-08-14 14:07 UTC, jorgefilipecosta commented
Good find @t-hamano, that the sorting issue is not related to this PR. It only affects patterns (not templates and pages). I will look for a fix and propose a PR to it.

2024-08-14 14:21 UTC, tyxla commented
> > @mirka could this be a recent regression caused by any of our work on #38730?
> 
> No, I think the positioning of the marks was weird like this, for as long as I can remember 😅 I don't even know what the intended design was, but it does look like it was vertically centered on the line, originally (#19916). We should definitely fix it — I assumed it was an outdated feature or something because we never really heard about the visual issue.

Cool, well it seems like @jameskoster opened an issue already (#64481) and @ramonjd already opened a PR to fix it (#64487) 👏  - let's make sure to review that.

2024-08-15 12:01 UTC, jameskoster commented
> Forgive me for jumping in randomly with a possibly context-lacking question: can this use the same design as the existing stepped slider we have?

@jasmussen I think you're referring to `SpacingSizesControl`. That component is specifically for handling spacing like margin/padding, and all of the linking/unlinking is built-in. I agree the visuals should be aligned, but that's a separate task. 

@jorgefilipecosta it seems the marks issue on `RangeControl` was fixed already, so we can rebase and add it back here if you like. Or handle it in a separate PR, no strong feeling here :) 

Otherwise this seems good to me.

2024-08-15 14:11 UTC, merged

2024-08-15 14:11 UTC, jorgefilipecosta commented
Merging this one as all the blockers were addressed will follow up with the addition of the marks.