Update get-started-with-wp-scripts.md
WordPress/gutenberg pull request #64436
Opened 2024-08-12 09:57 UTC by StudioSpindle

## What?
Added a minor change to the documentation.

## Why?
Found myself enqueuing the assets manually. While the preferred approach is to use the register_block type. 

## How?
Made that a bit more prominent that you can register the block via the `init` hook.

Hopefully this is useful.

2024-08-12 11:16 UTC, ndiego requested changes
Thanks for this PR @StudioSpindle! I added a few suggested updates.

2024-08-12 11:16 UTC, ndiego commented on docs/getting-started/devenv/get-started-with-wp-scripts.md
> +	register_block_type( __DIR__ . '/build' );
```suggestion
	// The build folder contains the block.json file.
	register_block_type( __DIR__ . '/build' );
```

2024-08-12 11:16 UTC, ndiego commented on docs/getting-started/devenv/get-started-with-wp-scripts.md
> +See full [example](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/minimal-block-ca6eda)
```suggestion
View the complete [example](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/minimal-block-ca6eda) in context.
```

2024-08-12 11:16 UTC, ndiego commented on docs/getting-started/devenv/get-started-with-wp-scripts.md
> +#### Manual enqueuing
```suggestion
```

I don't think we need another heading here.

2024-08-12 11:16 UTC, ndiego commented on docs/getting-started/devenv/get-started-with-wp-scripts.md
> +This will both register the block on server-side and client-side. More information regarding the registering of a block can be found in [Registration of a block](https://developer.wordpress.org/block
```suggestion
Using this approach will register the block on the server. More information regarding the registering of a block can be found in [Registration of a block](https://developer.wordpress.org/block-editor/getting-started/fundamentals/registration-of-a-block/).
```

Using `register_block_type` doesn't register the block in the client, only the server.

2024-08-13 07:58 UTC, StudioSpindle commented
Perfect, thank you. Let me know if anything else is necessary from me.

2024-08-16 13:43 UTC, shail-mehta commented
@StudioSpindle Could you please incorporate the suggested changes from the comments above?

2024-11-01 09:31 UTC, closed without merging

2024-11-19 14:45 UTC, RVledder commented
Yes! Sorry, I'm not sure why the head repository was deleted. I will update based on your suggestions and then file in a new PR.