fix typo in block-wrapper.md
WordPress/gutenberg pull request #64447
Opened 2024-08-12 15:37 UTC by janpfeil

## What?

## Why?

## How?

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast

2024-08-12 15:57 UTC, fabiankaegy reviewed
Good catch :) Thanks for the fix!

2024-08-12 15:57 UTC, fabiankaegy approved these changes

2024-08-12 16:30 UTC, shail-mehta requested changes
@janpfeil There are two additional instances in docs/reference-guides/filters/block-filters.md file, on lines 142 and 175. Could you please update those as well?

2024-08-12 17:35 UTC, ndiego commented
> @janpfeil There are two additional instances in docs/reference-guides/filters/block-filters.md file, on lines 142 and 175. Could you please update those as well?

@shail-mehta this has been fixed in https://github.com/WordPress/gutenberg/pull/64452. Can you clear your change request on this PR, and then we can merge it. Thanks!

2024-08-13 02:34 UTC, shail-mehta approved these changes

2024-08-13 07:40 UTC, juanmaguitar approved these changes

2024-08-13 16:40 UTC, merged