feat: Experimental editor assets REST API endpoint
WordPress/gutenberg pull request #64517
Opened 2024-08-14 15:30 UTC by dcalhoun

## What?

Enable requesting all assets — styles and scripts — loaded for the block editor via the REST API. 

## Why?

The [WordPress mobile](https://github.com/wordpress-mobile) team is exploring a web view-based editor where a given site's editor assets power the editing experience. If deemed successful, the experimental approach might bring a few benefits to the iOS and Android mobile apps editing experience: 

* Expanded core block support. 
* Expanded third-party block support. 
* Improved offline editing support. 
* Closer overall alignment with the web editing experience. 

## How?

Add an experimental block editor assets REST API endpoint. The endpoint returns a collection of relevant assets utilizing an approach similar to WordPress core's [iframe editor assets utility](https://github.com/WordPress/wordpress-develop/blob/2061a52da3d9d6d3994b0a60b2df07037d95e3d8/src/wp-includes/block-editor.php#L284-L388). 

## Testing Instructions

**Without Permission**
1. Make an unauthenticated request to the new endpoint: `curl -L <site_url>/?rest_route=/__experimental/wp-block-editor/v1/editor-assets`
2. Verify a 401 error response is returned. 

**With Permission**
1. Visit you site's WP Admin and navigate to **Users** → **Edit** (the `admin` user).
2. Create and copy an [application password](https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/#basic-authentication-with-application-passwords).
3. Create and copy a Base64 version of the combined username and application password: `echo -n 'admin:<application_password>' | base64 | pbcopy`
4. Make an authenticated request to the new endpoint: `curl --header "Authorization: Basic <base64_string>" -L <site_url>/?rest_route=/__experimental/wp-block-editor/v1/editor-assets`
5. Verify the response includes the expected editor style and script tags. 

### Testing Instructions for Keyboard

N/A, no user-facing changes. 

## Screenshots or screencast 
N/A, no user-facing changes.

2024-08-14 17:32 UTC, spacedmonkey requested changes
Instead of this new PR, please can you review my PR - https://github.com/WordPress/gutenberg/pull/21244.

2024-08-17 11:43 UTC, dcalhoun commented
> Instead of this new PR, please can you review my PR - #21244.

Thank you for sharing this helpful context, @spacedmonkey. 🙇🏻 

I reviewed the earlier PR — it is very cool and appears quite robust! I am concerned that its original goals may differ too much from the WordPress mobile team’s current goals. That divergence may complicate using the prior implementation for our particular needs. 

More specifically, the following are a few challenges I encountered in my research. I’m unsure if/how your prior implementation might address them. I welcome your thoughts on these. 

First, third-party plugins often fail to _globally_ register conditionally utilized assets, instead the assets are _only_ conditionally enqueued. This results in assets un-queryable at the global level. As quoted below, the WPGraphQL project referenced this same challenge in its own [asset query feature](https://github.com/wp-graphql/wp-graphql/pull/1313) as a “known issue.” In my proposed changes, I mitigate this issue by simulating an editor environment through [applying relevant hooks](https://github.com/WordPress/gutenberg/pull/64517/files#diff-30922137e06a174aff32be2caae94ab31d62a62f7f9b5a0cb6e2574bf1642885R86-R89), a very unique action for the particular use case of retrieving all editor assets. 

> Many plugins and themes, for example, don't register styles and scripts to the global registry, they *just* enqueue them. This can be problematic as the resource nodes for the assets won't be accessible via a node query using the asset ID, nor would they be accessible via a root `{ registeredScripts { nodes { ...fields } }` query (because they're not *actually* registered).
>
> The Storefront theme is an [example](https://github.com/woocommerce/storefront/blob/29cc2844504a96aaba999099e5cd4b3e16c6761c/inc/woocommerce/class-storefront-woocommerce.php#L150-L152) of conditionally *registering* assets, which is also problematic. This means that a resource is *only* queryable via a connection and *not* available in a Root Query for all registered assets or via the `node( id: $id )` query.
> 
> This will take some education around the ecosystem. . .**Registering scripts and styles should be global, and enqueueing them should be conditional / contextual.**

Second, the lower level nature of the prior implementation provides a robust foundation, but comes at the expense of requiring the client to reimplement dependency features WordPress already performs — e.g., sorting dependencies for correct loading order, deduplicating dependencies shared across assets, and building script/link tags. Rather than building this functionality in the mobile app, my proposed changes rely upon WordPress for these necessary actions. 

Lastly, the prior implementation’s current form appears to only support querying a single asset [by handle](https://github.com/WordPress/gutenberg/pull/21244/files#diff-986bd669c2de637765390a94bf5f9d9d1f524d2f525df4ee99dff1046b657967R270-R272), rather than querying all assets for the editor; I presume we could adapt it to support querying all assets, though. My proposed changes focus on the specific need of loading all editor assets, rather than a single asset. 

Again, thank you for sharing the past context. I’m interested to hear your thoughts on the challenges I share and the WordPress mobile team’s specific goal; it could be that both implementations provide unique value/capability for achieving the mobile team's goal. And, of course, please let me know if I misinterpreted anything in my review of your prior PR. 

I look forward to exploring this together!

2024-08-19 19:44 UTC, spacedmonkey commented
@dcalhoun 

To give you a little more context, I am a maintainer of the REST API in core and a core committer. I am the committer most likely to get this into core.

I agree that there are many issues with scripts being dynamically registered. It is likely that we will only be able to support scripts and styles that are registered by the register_block_type_from_metadata function. We may also need to manually trigger the register_core_block_style_handles function and possibly the enqueue_block_assets action as well.

I understand that my endpoint may not exactly match what you need, but it is a start. I strongly believe we can get it to a point where it could serve your purposes. However, I must emphasize that any endpoint that ends up in core needs to be generic and function as an interface that will remain in core indefinitely. Long after the mobile application codebase has changed, this endpoint will need to work the same way, as we promise backward compatibility. My endpoint is written to serve anyone requesting scripts and styles, not just a specific use case. For example, this endpoint could be used in a headless application.

For these reasons, I do not support the current format of this PR, as I don’t feel the endpoint is generic enough for other uses. In its current state, I would block it from being committed to core. However, I believe that my PR is a good base to build on. Could you take my PR and build on top of it, @dcalhoun? I am willing to pair on this, but I have limited time as I am about to become a father.

2024-08-23 12:44 UTC, dcalhoun commented
@spacedmonkey thank you for providing additional details for your perspective on these proposed changes. I understand and recognize the value in a more generic approach that might better serve additional use cases. 

Currently, I am exploring an alternative approach inspired by the web editor's [`loadAssets`](https://github.com/WordPress/gutenberg/blob/d5d2667fe430562f5a3f1686b45da1b69a79aead/packages/block-directory/src/store/load-assets.js) utility used for on-demand loading of plugin assets when installing a block from the inserter. 

I'll close this PR for the time being, as it seems a different approach  — either the aforementioned `loadAssets` or building upon https://github.com/WordPress/gutenberg/pull/21244 — is the most likely path forward. 

Congratulations on fatherhood, that is wonderful!

2025-02-19 14:02 UTC, closed without merging