Update block-filters.md
WordPress/gutenberg pull request #64959
Opened 2024-08-31 17:53 UTC by davy440

## What?
Describing the `blocks.getBlockAttributes` filter

## Why?
The documentation needed updation regarding the filter. It could be helpful exploring further applications of the filter hook.

## How?
Currently, there is no documentation for the filter hook.

## Testing Instructions
1. Set up the block development environment using @wordpress/scripts package.
2. Setup an entry-point for webpack in the package.
3. Add the code to the entry pint.
4. Save and compile.

2024-09-03 17:27 UTC, akasunil commented
Thank you for your contribution! 

Is it possible for us to utilize the same simple example function something like other filters example in the same readme? I think this one is a little too technical; since the purpose of this is just to show how to apply the filter, a simple function would do the job.

2024-09-11 04:01 UTC, davy440 reviewed
Modified the example and provided additional info

2024-09-11 04:18 UTC, davy440 commented
@akasunil Thanks for the feedback. I have modified the example and provided additional info regarding the filter.
Please review.

Thanks,
Divjot

2024-09-11 05:28 UTC, akasunil commented
Thanks @davy440 for the ping. I have left couple of suggestions. Hope to get it addressed.

2024-09-11 12:31 UTC, davy440 commented
@akasunil Yes, I have provided a simpler example in my most recent commit. Is there something else I'm missing?

2024-09-12 05:46 UTC, akasunil requested changes

2024-09-12 05:46 UTC, akasunil commented on docs/reference-guides/filters/block-filters.md
> +    'it-residence/lock-paragraphs',
```suggestion
    'my-plugin/lock-paragraphs',
```

2024-09-12 05:46 UTC, akasunil commented on docs/reference-guides/filters/block-filters.md
> +// Call the filter
```suggestion
// Add the filter
```

2024-09-12 05:46 UTC, akasunil commented on docs/reference-guides/filters/block-filters.md
> +function lockParagraphs( blockAttributes, blockType, innterHTML, attributes  ) {
```suggestion
function lockParagraphs( blockAttributes, blockType, innerHTML, attributes  ) {
```

2024-09-12 05:46 UTC, akasunil commented on docs/reference-guides/filters/block-filters.md
> +- `attributea` (`object`): Known attributes of the block.
```suggestion
- `attributes` (`object`): Known attributes of the block.
```

2024-09-12 05:46 UTC, akasunil commented on docs/reference-guides/filters/block-filters.md
> +    if(blockType['name'] === 'core/paragraph') {
```suggestion
    if('core/paragraph' === blockType.name) {
```

2024-09-12 20:40 UTC, davy440 commented
@akasunil thanks for the above fixes. Didn't pay attention to the above mentioned errors earlier.

2024-09-13 14:24 UTC, akasunil requested changes
Thank you @davy440, These looks really good. just one final thing to address and then we are ready to go.

2024-09-13 14:24 UTC, akasunil commented on docs/reference-guides/filters/block-filters.md
> +- `attributes` (`object`): Known attributes of the block.
```suggestion
- `blockAttributes` (`Object`): All block attributes.
- `blockType` (`Object`): The block type.
- `innerHTML` (`string`): Raw block content.
- `attributes` (`object`): Known block attributes (from delimiters).
```

2024-09-20 06:09 UTC, akasunil approved these changes
LGTM!

2024-09-26 20:08 UTC, davy440 commented
@akasunil Is there any update regarding the PR? Please let me know if anything is required from my end.

Thank you,
Divjot

2024-09-27 06:11 UTC, akasunil commented
Hi @davy440  Can you sync the PR with trunk?

2024-09-28 02:56 UTC, davy440 commented
@akasunil Just synced the fork with main branch. Showing 11 commits ahead of main branch. Let me know if anyhting else is required.

Thanks

2024-10-01 05:02 UTC, merged