Add all color palettes to select from editor panel
WordPress/gutenberg pull request #65148
Opened 2024-09-09 11:38 UTC by AKSHAT2802

Part of: https://github.com/WordPress/gutenberg/issues/64857

## What?
This PR Adds all the available colors in the list of editor color panel ( default, theme, custom )  so that the user can any predefined color in the editor.

## Why?
When selecting a color we should have a list of all the predefined options for a user instead of only custom-defined options.

## How?
Modified with-color-context.js file to list all the color instead of only custom colors.

## Screenshots or screencast
### Before
<img width="705" alt="Screenshot 2024-09-09 at 5 07 46 PM" src="https://github.com/user-attachments/assets/b2d7d9a1-de81-4671-9cda-8c44ca26bc6f">

### After

https://github.com/user-attachments/assets/895492b8-0601-461d-affb-cd6361c5ae5e

2024-10-25 12:43 UTC, ndiego commented
Thanks for working on this @AKSHAT2802. However, I don't think we should display the default color palette as well, only the theme color palette in addition to any custom options set by the user. Using the Twenty Twenty-Four theme as an example, this is what it should look like. 

|  There are no custom colors | The user has added custom colors |
|-|-|
|<img width="668" alt="image" src="https://github.com/user-attachments/assets/a65660eb-43d0-4e56-84e3-6338494837d7">|<img width="698" alt="image" src="https://github.com/user-attachments/assets/1959b083-d58a-4e4a-a245-db80643461ac">|

2024-11-07 14:21 UTC, richtabor requested changes
Two notes: 

1. I should only see the palettes which I have enabled. If I don't have the default palette enabled via theme.json, then I should not see that palette here.

2. I'd expect the colors in the same order as the color palette elsewhere, with theme colors first, then custom colors:

![CleanShot 2024-11-07 at 09 19 10](https://github.com/user-attachments/assets/63a81b21-ed74-427c-bbbc-35c38d193451)

2024-11-12 20:29 UTC, AKSHAT2802 commented
Hii @richtabor & @ndiego 
Thanks for the review 
Updated the PR

Sample Images 

1] Theme palette with custom colors
![image](https://github.com/user-attachments/assets/13db0ef8-b162-4878-b3b3-7c6be2f5093a)

2] Changed theme palette with no custom colors
![image](https://github.com/user-attachments/assets/191bfc4c-2e02-4371-ac4e-f76e30493a38)

3] Changed theme palette and added custom colors
![image](https://github.com/user-attachments/assets/f8268e7c-8c4b-4e22-a7da-5172876b515f)

2024-11-13 11:53 UTC, t-hamano reviewed
I think the default palette should not be disabled all the time, but only when `settings.color.defaultPalette` is `false`, otherwise it won't match other color palettes. Moreover, the order is "Theme" > "Default" > "Custom":

## Current

![image](https://github.com/user-attachments/assets/a48097cb-897d-4e6f-b7dc-f5e447949761)

## Expected

![image](https://github.com/user-attachments/assets/20cc76d9-8147-44af-b293-11a63a98988f)

Additionally, don't forget to test the inline text highlighting palette in this PR:

![image](https://github.com/user-attachments/assets/9c97b3fe-845a-4e75-a4ac-e1e46913e9c1)

2024-11-13 11:53 UTC, t-hamano commented on packages/block-editor/src/components/color-palette/with-color-context.js
> +		const colors = [ ...( themeColors || [] ), ...( customColors || [] ) ];
```suggestion
		const colors = [ ...themeColors, ...defaultColors, ...customColors ];
```

This simplification should be fine.

2024-11-13 13:49 UTC, richtabor commented
> I think the default palette should not be disabled all the time, but only when settings.color.defaultPalette is false, otherwise it won't match other color palettes. Moreover, the order is "Theme" > "Default" > "Custom":

+1

2024-11-14 10:04 UTC, AKSHAT2802 commented
Thanks, @t-hamano for the update. 
I have changed the code according to the requirements.

2024-11-15 09:34 UTC, t-hamano commented on packages/block-editor/src/components/color-palette/with-color-context.js
> +		const { disableCustomColors = ! enableCustomColors } = props;
```suggestion
		const _colors = enableDefaultColors
			? [
					...( themeColors || [] ),
					...( defaultColors || [] ),
					...( customColors || [] ),
			  ]
			: [ ...( themeColors || [] ), ...( customColors || [] ) ];

		const { colors = _colors, disableCustomColors = ! enableCustomColors } =
			props;
```

This change contains two fixes:

- Fixes a critical error that occurs when theme colors or custom colors are missing.
- Respects the `colors` prop of the `ColorPalette` component.

2024-11-19 13:22 UTC, t-hamano commented
Thanks for the update.

To ship this PR, we need to resolve the unit test failure. The failing tests are for the Cover block, and I think it's because the PR changed the behavior of the placeholder.

In trunk, the placeholder shows the default palette even if there are no colors available:

![image](https://github.com/user-attachments/assets/859ae31f-c2c4-4ec2-b924-f1c73f33938f)

In this PR, no palette is shown:

![image](https://github.com/user-attachments/assets/b9a5a2f4-ad0a-43a1-ae49-80baa20fc16a)

The behavior in this PR should be correct, so we need to fix the unit tests.

The following changes should solve the problem, could you try them?

```diff
diff --git a/packages/block-library/src/cover/test/edit.js b/packages/block-library/src/cover/test/edit.js
index 5c1a5b5e13..f5d6a5301e 100644
--- a/packages/block-library/src/cover/test/edit.js
+++ b/packages/block-library/src/cover/test/edit.js
@@ -337,7 +337,7 @@ describe( 'Cover block', () => {
                        describe( 'when colors are disabled', () => {
-                                       await createAndSelectBlock();
+                                       await selectBlock( 'Block: Cover' );
                                        await userEvent.click(
                                                screen.getByRole( 'tab', { name: 'Styles' } )
                                        );
@@ -350,7 +350,7 @@ describe( 'Cover block', () => {
                                } );
                                test( 'does not render opacity control', async () => {
                                        await setup( undefined, true, disabledColorSettings );
-                                       await createAndSelectBlock();
+                                       await selectBlock( 'Block: Cover' );
                                        await userEvent.click(
                                                screen.getByRole( 'tab', { name: 'Styles' } )
                                        );
```

2024-11-21 22:48 UTC, richtabor approved these changes
LGTM 
![CleanShot 2024-11-21 at 17 48 04](https://github.com/user-attachments/assets/8305c42d-68b0-4482-979e-b5394db78dde)

2024-11-22 11:39 UTC, t-hamano commented
It has passed all CI checks so let's merge this PR.

@AKSHAT2802 Thank you for your efforts!

2024-11-22 11:39 UTC, merged