Remove clip & -webkit-clip-path for screen-reader-text CSS
WordPress/gutenberg pull request #66147
Opened 2024-10-15 20:44 UTC by mediaformat

## What?

Addresses part of https://github.com/WordPress/gutenberg/issues/65954

## Why?

The utility .screen-reader-text CSS is used in several places throughout the Gutenberg code base. In https://github.com/WordPress/gutenberg/pull/65409 it came up that we should update all the areas to match the changing CSS rules proposed in https://github.com/WordPress/gutenberg/pull/65409.

## How?

Remove the unnecessary clip: rect(1px, 1px, 1px, 1px); and -webkit-clip-path: inset(50%); rules  from the packages/block-library/src/components/downloadable-block-list-item/style.scss

2024-10-16 07:47 UTC, afercia commented
Thanks @mediaformat 
I think this rulest can be entirely replaced with a `display: none`. Currently, this rule is only set when a block from the blocks directory in the main inserter is in the process of being installed.
It is meant to temporarily hide the block author name when `isInstalling` is true. After the block is installed, the author name is visible again. Anyways, the whole content of the button in the inserter is overridde by the `aria-label` set on the button so there's really no need to use the screen-reader-text rule on the author name.

- Open the main inserter.
- Search for some term e.g. `image`
- Scroll down the inserter and observe the `Available to install` section. Note: this is the blocks directory. It takes a while to load.
- Choose one of the blocks from the blocks directory and click to install it.
- Observe the content of the block item in the list changes and shows an `Installing...` text.
- Observe the original content of the block item is visible again when the block is installed.

2024-10-16 07:52 UTC, afercia requested changes
I'd suggest to replace the entire rule with a `display: none`.

2024-10-16 15:28 UTC, mediaformat commented
@afercia I see what you mean. I'll replace the entire rule with `display: none;` as suggested.

2024-10-16 17:15 UTC, colorful-tones commented
> I'd suggest to replace the entire rule with a display: none.

Great catch and thanks @afercia !
Thanks for addressing with an update @mediaformat 👏 

I tested with `display: none` and works as intended.

2024-10-18 10:30 UTC, afercia approved these changes
LGTM to me!

2024-10-18 10:31 UTC, merged