Add check for empty list item
WordPress/gutenberg pull request #66344
Opened 2024-10-22 17:52 UTC by nani-samireddy

## What?

- [x] https://github.com/wordpress/gutenberg/issues/65876

As mentioned in the above issue. When we create a list and if we leave the last item empty. It renders a empty list item on the front-end.

## Why?

It is missing a check while saving the list-item.

## How?

- Added a check to only save the list-item only if it content

## Testing Instructions
- Open the Gutenberg Editor.
- Add the list block
- Add two or three items and for the last item keep it empty
- On the front-end it should not display the last list-item ( empty one)

### Testing Instructions for Keyboard

## Screenshots or screencast 
### before 
<img width="1196" alt="Screenshot 2024-10-22 at 11 21 09 PM" src="https://github.com/user-attachments/assets/6470c75e-19c0-4e98-9984-d4436abfa143">
<img width="1452" alt="Screenshot 2024-10-22 at 11 20 59 PM" src="https://github.com/user-attachments/assets/b39dacc8-cb3a-417a-bc1d-02f594c03407">

### After

<img width="1194" alt="Screenshot 2024-10-22 at 11 17 20 PM" src="https://github.com/user-attachments/assets/4d5b5a3b-1b4f-434d-868f-bd4016159bb9">

<img width="1450" alt="Screenshot 2024-10-22 at 11 17 39 PM" src="https://github.com/user-attachments/assets/29badc83-1b23-44c1-8377-76a5bfa81799">

2024-10-23 03:36 UTC, Mamaduka commented on packages/block-library/src/list-item/save.js
> +	if ( attributes.content?.length === 0 ) {
The rich text has the `RichText.isEmpty` utility to check if the value is empty.

2024-10-23 05:26 UTC, nani-samireddy commented on packages/block-library/src/list-item/save.js
> +	if ( attributes.content?.length === 0 ) {
Thank you @Mamaduka 
I have updated the logic to use RichText.isEmpty utility

2024-12-13 12:25 UTC, up1512001 approved these changes
LGTM

2024-12-13 12:53 UTC, Mamaduka requested changes
I'm still not sure about and looking for the feedback from @ellatrix!

@up1512001, you can also see that tests are failing, with usually means that PR isn't ready to be merged.

2024-12-13 14:31 UTC, up1512001 commented
I checked the test failure issue and noticed that its due to this file `test/integration/fixtures/documents/mixed-content-out.html`.
seems like we need to change this
```html
<ul class="wp-block-list"><!-- wp:list-item -->
<li></li>
<!-- /wp:list-item -->
```
with this 
```html
<ul class="wp-block-list"><!-- wp:list-item /-->
```

@Mamaduka let me know if I am right 🙇

2024-12-13 15:34 UTC, Mamaduka commented
@up1512001, @nani-samireddy, I also see failures in e2e tests.

2024-12-13 19:06 UTC, up1512001 commented
@Mamaduka one thing I notice during debugging `e2e` that to run it in watch mode we need to change package.json script from this `"test:e2e:watch": "npm run test:e2e -- --watch",` to this `"test:e2e:watch": "npm run test:e2e --watch",` isn't it strange 🤔 
```

npm run test:e2e:watch    

> gutenberg@19.9.0-rc.1 test:e2e:watch
> npm run test:e2e -- --watch


> gutenberg@19.9.0-rc.1 test:e2e
> wp-scripts test-playwright --config test/e2e/playwright.config.ts --watch

error: unknown option '--watch'
```

2024-12-18 06:42 UTC, up1512001 approved these changes
Looks good to me, @Mamaduka any suggestions. 🙇

2024-12-18 06:47 UTC, ellatrix commented on test/e2e/specs/editor/blocks/list.spec.js
> +<!-- wp:list-item /-->
This does not make any sense to me.

2024-12-18 06:49 UTC, ellatrix requested changes
Why?

> It is missing a check while saving the list-item.

I don't understand this answer to "Why?"

This does not make sense to be at all. If the user adds a list item, it should be displayed.

2024-12-18 07:19 UTC, closed without merging

2024-12-18 07:19 UTC, nani-samireddy commented
Closing this PR based on this [comment](https://github.com/WordPress/gutenberg/issues/65876#issuecomment-2550507207)

Thank you @ellatrix for confirming the expected behaviour of the list-item.

Thank you @up1512001 and @Mamaduka for taking time and reviewing this

2024-12-18 07:27 UTC, Mamaduka commented
Thanks for contributing, @nani-samireddy!