fix: Restore placeholders for all RichText
WordPress/gutenberg pull request #6647
Opened 2018-05-08 20:12 UTC by tofumatt

Fix #6470.

Restores placeholders for all RichText blocks.

## Description
Restored placeholders for all RichText blocks. These were removed in #2624. Both this issue and the removal of the placeholder on focus were okayed by @karmatosed so I'm not sure what the preferred UX is here... but I'll say I find the disappearing placeholder on focus to be inconsistent with the rest of Gutenberg and also the web in general.

## How has this been tested?
Tested in Chrome/Firefox/Edge/Safari and it worked.

## Screenshots

### Before
![2018-05-08 21 07 13](https://user-images.githubusercontent.com/90871/39780477-4a00a8bc-5304-11e8-95a8-d96dd7c91293.gif)

### After
![2018-05-08 20 56 14](https://user-images.githubusercontent.com/90871/39780478-4d1ee068-5304-11e8-9026-dd45c7810985.gif)

## Types of changes
New feature/restoration of feature (placeholders always displayed).
Removed the `keepPlaceholderOnFocus` prop from `RichText` because nothing else in Gutenberg was using it. Not sure if that counts as breaking and we need to deprecate.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

2018-05-09 11:41 UTC, youknowriad commented
Added a design feedback label since it was an intentional behavior.

2018-05-11 11:44 UTC, gziolo commented on editor/components/rich-text/index.js
> -			keepPlaceholderOnFocus = false,
It should be also removed from Readme file: https://github.com/WordPress/gutenberg/blob/4af0d34480a22623d4c03a436c2bd7628bc710ba/editor/components/rich-text/README.md#keepplaceholderonfocus-boolean

2018-05-11 11:46 UTC, gziolo commented
Code wise it looks good, but I would defer final 👍 to @karmatosed and @jasmussen.

2018-05-11 17:24 UTC, karmatosed requested changes
The PR linked was primarily about removing from links. I think #2161 is where the original removal for paragraphs happened. I tend to agree with it also but only because of the flow. We have it appear on first adding a block, I would argue it's not needed for each after. When we did have it, the experience was a little weird if you imagine writing a few paragraphs in a row and seeing it each time.

That all said, there could be a middle ground. Perhaps we only show the first paragraph block and then do not if someone adds more after? This would mean paragraphs in-between other blocks would always have it. I'm kind of seeing that behaviour right now but it seems not consistent.

2018-05-11 18:11 UTC, tofumatt commented
If one thinks of each `Paragraph` block as part of a larger input field then yes actually, the current implementation works as a regular ol' `<textarea>` would.

The middle-ground state seems complicated (some users could easily interpret it as a bug as well) and actually upon reflection I think the behaviour as-is is quite in-line with how a (prose) editor should work.

Sounds like things are working as intended and we should close #6470 as a "won't fix".

2018-05-11 18:11 UTC, closed without merging