Update/inquirer dependency
WordPress/gutenberg pull request #67877
Opened 2024-12-12 11:31 UTC by gziolo

## What?

> [Inquirer.js](https://github.com/SBoudrias/Inquirer.js/tree/main) recently underwent a rewrite from the ground up to reduce the package size and improve performance. The previous version of the package is still maintained (though not actively developed), and offered hundreds of community contributed prompts that might not have been migrated to the latest API.

## Why?

## How?

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast 

|Before|After|
|-|-|
|||

2024-12-17 14:26 UTC, ryanwelcher approved these changes
Code changes LGTM. I've testing in both interactive and quick mode and everything seems to work as expected.

2024-12-18 10:01 UTC, t-hamano reviewed
I have confirmed that it works correctly on a Windows host OS.

One concern is that an error occurs when I cancel the prompt. In my environment, this occurs on both a Windows host OS and an Ubuntu OS:

```
$ npx wp-create-block

Let's customize your WordPress plugin with blocks:
? The template variant to use for this block: (Use arrow keys)
❯ static
  dynamic
/home/t-hamano/projects/gutenberg/node_modules/@inquirer/core/dist/commonjs/lib/create-prompt.js:84
            reject(new errors_js_1.ExitPromptError(`User force closed the prompt with ${code} ${signal}`));
                   ^

ExitPromptError: User force closed the prompt with 0 null
    at /home/t-hamano/projects/gutenberg/node_modules/@inquirer/core/dist/commonjs/lib/create-prompt.js:84:20
    at Emitter.emit (/home/t-hamano/projects/gutenberg/node_modules/@inquirer/core/node_modules/signal-exit/dist/cjs/index.js:71:19)
    at #processEmit (/home/t-hamano/projects/gutenberg/node_modules/@inquirer/core/node_modules/signal-exit/dist/cjs/index.js:240:27)
    at #process.emit (/home/t-hamano/projects/gutenberg/node_modules/@inquirer/core/node_modules/signal-exit/dist/cjs/index.js:191:37)
    at process.callbackTrampoline (node:internal/async_hooks:130:17)
```

This error doesn't seem to occur on trunk.

2024-12-18 12:23 UTC, gziolo commented
@t-hamano, thank you for your feedback. I fixed the issue you reported in https://github.com/WordPress/gutenberg/pull/67877/commits/2e91186cfcd7799630897e21e2f547b748fb6302 by following this documentation:

https://github.com/SBoudrias/Inquirer.js/blob/e228166601c5acebc4750f4474a31b38a555a93d/packages/prompts/README.md#handling-ctrlc-gracefully

2024-12-18 12:30 UTC, gziolo commented on packages/create-block/lib/index.js
> +						projectTemplate,
I changed the name from `pluginTemplate` to `projectTemplate` as I realized that the name became confusing after we introduced the concept of scaffolding a block without a plugin. This part is used to scaffold only the block.  Consequently, the name `getPluginTemplate` became `getProjectTemplate`. It's also a step towards the potential introduction of the template for a theme that needs dev tools for JavaScript and CSS.

2024-12-18 12:31 UTC, gziolo commented on packages/create-block/lib/index.js
> +							! plugin && 'textdomain',
In my testing, the `textdomain` prompt only makes sense when `--no-plugin` option is selected. Otherwise, it should be equal to the plugin slug name.

2024-12-19 07:10 UTC, t-hamano approved these changes
LGTM! I have confirmed that `ctrl+c` works on both Windows OS and Linux.

2024-12-19 07:13 UTC, t-hamano requested changes
Wait, we may also need to update the env command.

```
$ npm run wp-env destroy

> gutenberg@19.9.0 wp-env
> wp-env destroy

ℹ WARNING! This will remove Docker containers, volumes, networks, and images associated with the WordPress instance.
✖ inquirer.prompt is not a function
TypeError: inquirer.prompt is not a function
    at destroy (/home/t-hamano/projects/gutenberg/packages/env/lib/commands/destroy.js:43:39)
```

2024-12-19 09:11 UTC, gziolo commented
@t-hamano, for consistency, I updated all occurrences so it's handled the same way. That also covers:

<img width="1277" alt="Screenshot 2024-12-19 at 10 10 59" src="https://github.com/user-attachments/assets/2fd2174e-757f-42ad-89f1-8a81c6a43902" />

Consequently, the Gutenberg repository uses only `@inquirer/prompts` in all places.

2024-12-19 09:54 UTC, t-hamano approved these changes
Thanks for the update. I have tested again and everything seems to be working as expected.

2024-12-19 09:54 UTC, t-hamano commented on packages/create-block/lib/index.js
> +					log.info( 'Please try again later!' );
```suggestion
					log.info( 'Cancelled.' );
```

Does this message also need to be unified?

2024-12-19 10:39 UTC, merged