Archive Title Block: Refactor settings panel to use ToolsPanel
WordPress/gutenberg pull request #67915
Opened 2024-12-13 07:26 UTC by karthick-murugan

## What?
Part of: https://github.com/WordPress/gutenberg/issues/67813

## Why?
Archive Title Block code to include ToolsPanel instead of PanelBody.

## How?
Refactored Archive Title Block code to include ToolsPanel instead of PanelBody.

## Testing Instructions

- Login to Dashboard
- Edit any post/ page
- Add Archive Title block.
- Check settings panel of the Archive title block and verify the change.

## Screenshots or screencast 

**Before**
![before_archive](https://github.com/user-attachments/assets/02eb8c28-5cc7-40d1-a20a-a9fd3c60090a)

**After**
![after_archive](https://github.com/user-attachments/assets/b278889c-3a3b-44af-b035-195968fe43de)

2024-12-13 14:36 UTC, fabiankaegy requested changes, later dismissed
In this initial refactor we should ensure that any controls that were visible before are alway visible after. So we should add the `isShownByDefault` prop to the TabsPanelItem

https://github.com/user-attachments/assets/186eda6e-6939-4041-8485-cccd8e2dfa82

2024-12-16 05:14 UTC, karthick-murugan commented
> In this initial refactor we should ensure that any controls that were visible before are alway visible after. So we should add the `isShownByDefault` prop to the TabsPanelItem
> 
>  CleanShot.2024-12-13.at.15.34.10.mp4

The changes has been updated @fabiankaegy

2025-01-12 08:34 UTC, t-hamano reviewed
I think the following are expected specifications for the ToolsPanel:

- Reset action should update the setting value to the default value.
- hasValue prop should be true when it is not the default value.

Based on this, I have added a few more suggestions.

Additionally, it would be a good idea to add the `dropdownMenuProps` to ensure that the drop-down menu is positioned on the left ([Example](https://github.com/WordPress/gutenberg/blob/2397525dfbe29814ace66dd1dbca152208aad9a8/packages/block-library/src/button/edit.js#L127)).

2025-01-12 08:34 UTC, t-hamano commented on packages/block-library/src/query-title/edit.js
> +								showPrefix: false,
```suggestion
								showPrefix: true,
```

The default value of the `showPrefix` attribute is `true`.

2025-01-12 08:34 UTC, t-hamano commented on packages/block-library/src/query-title/edit.js
> +							hasValue={ () => showPrefix !== undefined }
```suggestion
							hasValue={ () => showPrefix !== undefined }
```

It should be considered the opposite of a default value, i.e. it "has a value" when it is `false`.

2025-01-12 08:34 UTC, t-hamano commented on packages/block-library/src/query-title/edit.js
> +								setAttributes( { showPrefix: false } )
```suggestion
								setAttributes( { showPrefix: true } )
```

2025-01-12 08:34 UTC, t-hamano commented on packages/block-library/src/query-title/edit.js
> +								showSearchTerm: false,
```suggestion
								showSearchTerm: true,
```

The default value of the `showSearchTerm` attribute is `true`.

2025-01-12 08:34 UTC, t-hamano commented on packages/block-library/src/query-title/edit.js
> +							hasValue={ () => showSearchTerm !== undefined }
```suggestion
							hasValue={ () => showSearchTerm !== undefined }
```

It should be considered the opposite of a default value, i.e. it "has a value" when it is `false`.

2025-01-12 08:34 UTC, t-hamano commented on packages/block-library/src/query-title/edit.js
> +								setAttributes( { showSearchTerm: false } )
```suggestion
								setAttributes( { showSearchTerm: true } )
```

2025-01-12 08:34 UTC, t-hamano commented on packages/block-library/src/query-title/edit.js
> +							isShownByDefault
```suggestion
							isShownByDefault
```

I don't think resetAllFilter is necessary.

2025-01-12 08:34 UTC, t-hamano commented on packages/block-library/src/query-title/edit.js
>  							}
```suggestion
							}
							isShownByDefault
```

2025-01-13 10:26 UTC, karthick-murugan commented
> I think the following are expected specifications for the ToolsPanel:
> 
> * Reset action should update the setting value to the default value.
> * hasValue prop should be true when it is not the default value.
> 
> Based on this, I have added a few more suggestions.
> 
> Additionally, it would be a good idea to add the `dropdownMenuProps` to ensure that the drop-down menu is positioned on the left ([Example](https://github.com/WordPress/gutenberg/blob/2397525dfbe29814ace66dd1dbca152208aad9a8/packages/block-library/src/button/edit.js#L127)).

Thanks for the detailed feedback @t-hamano. Updated all the changes.

2025-01-14 07:13 UTC, t-hamano approved these changes
I made a small suggestion at the end, but it works fine 👍

2025-01-14 07:13 UTC, t-hamano commented on packages/block-library/src/query-title/edit.js
> +							hasValue={ () => showPrefix === false }
```suggestion
							hasValue={ () => ! showPrefix }
```

2025-01-14 07:13 UTC, t-hamano commented on packages/block-library/src/query-title/edit.js
> +							hasValue={ () => showSearchTerm === false }
```suggestion
							hasValue={ () => ! showSearchTerm }
```

2025-01-14 07:41 UTC, karthick-murugan commented on packages/block-library/src/query-title/edit.js
> +							hasValue={ () => showPrefix === false }
Updated

2025-01-14 07:41 UTC, karthick-murugan commented on packages/block-library/src/query-title/edit.js
> +							hasValue={ () => showSearchTerm === false }
Updated

2025-01-14 09:24 UTC, merged