Refactor "Settings" panel of Next Post block to use ToolsPanel instead of PanelBody
WordPress/gutenberg pull request #67976
Opened 2024-12-13 11:48 UTC by rinkalpagdar

Part of #67813 
Fixes #67943 

## Testing Instructions

- Add Next post block
- Open the settings panel

## Screenshots or screencast 

|Before|After|
|<img width="280" alt="before-next-post" src="https://github.com/user-attachments/assets/6e7d44fa-4eb6-4b3b-8e6a-22322a2af810" />|<img width="280" alt="after-next-post" src="https://github.com/user-attachments/assets/6d7b7f2c-f2c6-455e-891d-6664fffc8445" />|

2024-12-13 15:07 UTC, fabiankaegy requested changes

2024-12-13 15:07 UTC, fabiankaegy commented on packages/block-library/src/post-navigation-link/edit.js
> +						onDeselect={() => setAttributes({ showTitle: false })}
```suggestion
						onDeselect={() => setAttributes({ showTitle: false })}
						isShownByDefault
```

2024-12-13 15:07 UTC, fabiankaegy commented on packages/block-library/src/post-navigation-link/edit.js
> +						onDeselect={() => setAttributes({ arrow: 'none' })}
```suggestion
						onDeselect={() => setAttributes({ arrow: 'none' })}
						isShownByDefault
```

2024-12-16 05:30 UTC, rinkalpagdar commented
Hello @fabiankaegy I have implemented your suggestion. Thanks for the feedback.

2025-01-13 04:13 UTC, t-hamano reviewed
Thanks for the PR!

I've left some feedback so I'd be happy if you could check it out.

2025-01-13 04:13 UTC, t-hamano commented on packages/block-library/src/post-navigation-link/edit.js
> +				<ToolsPanel label={ __( 'Settings' ) }>
Let's add dropdownMenuProps to place the dropdown on the left side of the block sidebar ([Example](https://github.com/WordPress/gutenberg/blob/ad8bdfe512cfef2e54d30459bff945f4231f27de/packages/block-library/src/archives/edit.js#L38)).

2025-01-13 04:13 UTC, t-hamano commented on packages/block-library/src/post-navigation-link/edit.js
> +					<ToolsPanelItem
All controls are expected to be visible by default for now. Let's add `isShownByDefault` prop to all `ToolsPanelItem` components.

2025-01-13 04:13 UTC, t-hamano commented on packages/block-library/src/post-navigation-link/edit.js
>  						<ToggleControl
This control also needs to be wrapped in `ToolsPanelItem`

2025-01-13 12:16 UTC, rinkalpagdar commented on packages/block-library/src/post-navigation-link/edit.js
>  						<ToggleControl
This is conditional control based on the first toggle so we can't add it in `ToolsPanelItem`.

2025-01-14 08:46 UTC, t-hamano commented on packages/block-library/src/post-navigation-link/edit.js
>  						<ToggleControl
You can also use the `ToolsPanelItem` component for conditional control ([Example](https://github.com/WordPress/gutenberg/blob/669662c740bf0e69f58ad1d7e570607c066f31ef/packages/block-library/src/archives/edit.js#L60-L61)).

2025-01-17 07:38 UTC, t-hamano reviewed
Thanks for the update! I just left a few more suggestions at the end, but overall it looks good.

However, we're running into an issue where the order of the controls doesn't match the order of the dropdown items:

![display-order](https://github.com/user-attachments/assets/b211605c-10ea-4f41-a40a-e598c71271d0)

This was reported in [the comment](https://github.com/WordPress/gutenberg/issues/67813#issuecomment-2586335910), and will need to be resolved before I can ship this PR.

Sorry, but please be patient until that issue is resolved.

2025-01-17 07:38 UTC, t-hamano commented on packages/block-library/src/post-navigation-link/edit.js
> +									isShownByDefault
The `isShownByDefault` prop needs to be added to the `ToolsPanelItem` component, not the `ToggleGroupControl` component.

2025-01-17 07:38 UTC, t-hamano commented on packages/block-library/src/post-navigation-link/edit.js
> +						hasValue={ () => !! arrow }
```suggestion
						hasValue={ () => arrow !== 'none' }
```

If the value is the default value `none`,  we must return `false`.

2025-01-17 10:45 UTC, rinkalpagdar commented
> Thanks for the update! I just left a few more suggestions at the end, but overall it looks good.
> 
> However, we're running into an issue where the order of the controls doesn't match the order of the dropdown items:
> 
> ![display-order](https://private-user-images.githubusercontent.com/54422211/404198978-b211605c-10ea-4f41-a40a-e598c71271d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcxMDYyNzgsIm5iZiI6MTczNzEwNTk3OCwicGF0aCI6Ii81NDQyMjIxMS80MDQxOTg5NzgtYjIxMTYwNWMtMTBlYS00ZjQxLWE0MGEtZTU5OGM3MTI3MWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE3VDA5MjYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0N2M3YzliN2VkOTdhYjQyY2VhMWUyMTVjYWVkNjhhYTVmMWJkYWNhOTdlM2ViYTgwYTNkNWFlMGExZGIwN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Yt_TXZSLh5k0mBE8VWq4n5-Cc6xWZvK_xQ-y_fOZaqc)
> 
> This was reported in [the comment](https://github.com/WordPress/gutenberg/issues/67813#issuecomment-2586335910), and will need to be resolved before I can ship this PR.
> 
> Sorry, but please be patient until that issue is resolved.

Hello @t-hamano 
I have checked all properties of `toolsPanelItem`, Can you please guide me on how to maintain order of it?

2025-01-17 11:57 UTC, t-hamano commented
> I have checked all properties of toolsPanelItem, Can you please guide me on how to maintain order of it?

As far as I know, there are currently no options to solve this.

I think we need to analyze the behavior of the `ToolsPanel` and `ToolsPanelItem` components itself and address it. See [this discussion](https://github.com/WordPress/gutenberg/issues/67813#issuecomment-2586335910).

2025-06-14 02:04 UTC, t-hamano commented
Hi @rinkalpagdar, I noticed that this block was refactored by #70276 and has already been merged.

I'm sorry, I should have realized that multiple PRs had been submitted for the same block.

I would like to close this PR, but I appreciate your efforts 🙏

2025-06-14 02:04 UTC, closed without merging