Update text description of the "Contain text cursor inside block" preference
WordPress/gutenberg pull request #68132
Opened 2024-12-19 10:13 UTC by karthick-murugan

## What?
Fixes https://github.com/WordPress/gutenberg/issues/57351

This PR updates the description of the "Contain text cursor inside block" preference in the Accessibility options.

## Why?
The previous description implied the feature was primarily beneficial for screen reader users, which was misleading. The feature impacts all keyboard users, providing better control while navigating between blocks. The new description is clearer, more user-focused, and emphasizes its broader applicability.

## How?
The description was rewritten to explain the functionality in simpler terms that resonate with casual users, outlining how it affects keyboard navigation and enhances usability.

## Testing Instructions

1. Open the WordPress admin dashboard.
2. Navigate to Options > Preferences > Accessibility.
3. Locate the "Contain text cursor inside block" option.
4. Verify the updated description is displayed correctly.
5. Confirm the description accurately explains the behaviour by testing the preference in a post or page.

### Testing Instructions for Keyboard

## Screenshots or screencast 

## Before
![before_preference](https://github.com/user-attachments/assets/6619f86b-74af-49db-9a6a-05301ea71426)

## After
 ![after_preference](https://github.com/user-attachments/assets/4ad59e4e-5f35-4b55-94b4-f3daa5acf9c3)

2025-01-06 12:18 UTC, karthick-murugan commented
@joedolson - Please have a look at this PR when you get some time.

2025-01-14 19:51 UTC, joedolson commented
It's definitely an improvement. I think swapping the word 'Restricts' for 'Keeps' is not an improvement; 'Keeps' is simpler. 

I still think that "while navigating" isn't enough information. Can we specify what type of navigation, e.g.:

"Keeps the text cursor within blocks while navigating with arrow keys, preventing it from moving to other blocks, enhancing accessibility for keyboard users."

We could omit the phrase 'enhancing accessibility for keyboard users'. I don't think keeping that phrase is specifically necessary, though I don't think it hurts, either - it helps give context for all users about what the value of this option is. But this is an option within the accessibility settings section, so I don't see it as necessary to explain that it's an accessibility enhancement.

2025-01-17 00:59 UTC, joedolson requested changes
Suggest changes in https://github.com/WordPress/gutenberg/pull/68132#issuecomment-2590978434

2025-01-17 05:18 UTC, karthick-murugan commented
> Suggested changes in [#68132 (comment)](https://github.com/WordPress/gutenberg/pull/68132#issuecomment-2590978434)

@joedolson - Updated the description as suggested.

2025-01-17 18:54 UTC, joedolson approved these changes
I made a very minor text tweak; but otherwise this seems good to go!

2025-01-23 15:09 UTC, afercia commented
This looks good and makes sense, thanks all!

2025-01-23 15:09 UTC, merged