Fix Inconsistent Labels for Lightbox Feature
WordPress/gutenberg pull request #68261
Opened 2024-12-24 07:15 UTC by karthick-murugan

## What?
Fixes https://github.com/WordPress/gutenberg/issues/55617 

This PR ensures consistent terminology between the editor (backend) and frontend for the lightbox feature. The label "Expand on click" in the editor has been updated to "Enlarge image" for alignment with the frontend aria-labels.

## Why?
Consistency in terminology is vital for accessibility and usability. Users of assistive technology will now encounter the same terms ("Enlarge image") in both the editor and frontend, reducing potential confusion. 

## How?

- Updated the editor UI setting label from "Expand on click" to "Enlarge image."
- Verified that the aria-label for the trigger button and modal dialog in the frontend is "Enlarge image," ensuring consistency across the interface.

## Testing Instructions

1. Open a post or page.
2. Insert an image block with the lightbox feature enabled.
3. Observe that the lightbox setting in the editor now reads "Enlarge image."

## Screenshots or screencast 

![backend_enlarge](https://github.com/user-attachments/assets/b0106bce-2738-4053-b6f0-f7345ec10b06)

2025-01-06 11:43 UTC, karthick-murugan commented
@afercia - Please have a look at this PR and let me know if you have any suggestions.

2025-01-07 09:27 UTC, afercia commented on packages/block-library/src/image/index.php
> +			aria-describedby="' . esc_attr( $alt ) . '"
The `aria-describedby` attribute should point to the ID of a hidden element that contains the description. If it turns to be too complicated, we could consider to not use a description at all.

2025-01-07 09:30 UTC, afercia requested changes
I left a comment about aria-describedby that should be addressed.
Also, some tests are failing because they still expect a button with name 'Expand on click'', they should be updated/
A quick note; I think the preferred way to sync with trunk is to rebase insteaf of merging trunk.

2025-01-07 14:47 UTC, karthick-murugan commented on packages/block-library/src/image/index.php
> +			aria-describedby="' . esc_attr( $alt ) . '"
@afercia - Considering the complexity of this implementation, I have removed the aria-describedby attribute as per your suggestion. We can address it in a separate PR to ensure it is handled comprehensively.

2025-01-08 12:18 UTC, afercia commented
@karthick-murugan thanks for working on this. 
The aria-label of the modal dialog should be adjusted to be more meaningful. Currently, it uses the same text used for hte button: `Enlarge`. However, the modal dialog should be labeled to communicate this is the _enlarged_ image. Something simple like `Enlarged image` would work, I think.

I think that the button label should stay `__( 'Enlarge' )` and a new `$dialog_aria_label` variable should be added with value `__( 'Enlarged image' )`  and then be used [here](https://github.com/WordPress/gutenberg/blob/54f59fece2d9abd28fea97f3c2273dd9fc6e0eb8/packages/block-library/src/image/index.php#L193).

2025-01-08 12:20 UTC, afercia requested changes
Looks good to me but a new variable should be adder to be used for the modal dialog label.

2025-01-08 13:32 UTC, karthick-murugan commented
> Looks good to me but a new variable should be adder to be used for the modal dialog label.

@afercia - Thanks for your time on reviewing this PR. Updated the changes that you have requested.

2025-01-08 13:38 UTC, afercia approved these changes
Looks good to me.
This improves naming consistency, simplifies labeling and makes the UI more predictable.

2025-01-08 13:44 UTC, merged