Components: Standardize reduced motion handling using media queries
WordPress/gutenberg pull request #68421
Opened 2024-12-31 04:22 UTC by SainathPoojary

Part of: https://github.com/WordPress/gutenberg/issues/68282

## What?

## Why?

## How?

## Testing Instructions

### Testing Instructions for Keyboard

## Screenshots or screencast 

|Before|After|
|-|-|
|||

2024-12-31 11:19 UTC, SainathPoojary commented
Hey @t-hamano, 

This package includes several components. Would it be better to raise a new PR for the remaining components, or should I add them to this PR?

Components currently in PR:
```
button
checbox-control
circular-option-picker
form-toggle
form-token-field
panel
placeholder
```

Remaining components:
```
resizable-box
tab-panel
animate
modal
toolbar
drop-zone
```

2025-01-02 04:21 UTC, t-hamano commented
@SainathPoojary Thanks for working on this issue.

> This package includes several components. Would it be better to raise a new PR for the remaining components, or should I add them to this PR?

It will be easy to test this PR because almost all components are published in Storybook, so I personally think it's okay to include all components in this PR.

2025-01-02 08:08 UTC, SainathPoojary commented
Got it, I agree! I’ll include the remaining components in this PR.

2025-01-03 15:13 UTC, SainathPoojary commented
Hey @t-hamano,

I have standardized the transition and animation for the Component package and attached a video demonstrating the tests for each component. Please take a look when you have a moment.

Thank you!

2025-01-05 07:48 UTC, t-hamano reviewed
Thanks for the PR! I've tested all components on Storybook and everything appears to work as before.

In order for this PR to be shippable, could you confirm the following?

- Rebase the PR. This should pass all E2E tests (See https://github.com/WordPress/gutenberg/pull/68484).
- Update the [CHANGELOG](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md). Add a `Internal` section under the `Unreleased` section and add this PR as an item in it.

@WordPress/gutenberg-components If you have any feedback on this PR, please let us know 🙏

---

Note: The CI error reported in [the comment](https://github.com/WordPress/gutenberg/pull/68419#issuecomment-2567550864) (Storybook build error) does not occur in this PR.

Presumably the error only occurs when surrounded by a breakpoint mixin like below, but there are no media queries surrounded by a breakpoint mixin in this PR:

```scss
.selector {
	@include break-medium {
		@media not (prefers-reduced-motion) {
		}
	}
}
```

2025-01-05 07:48 UTC, t-hamano commented on packages/components/src/circular-option-picker/style.scss
>  	will-change: transform;
I think we could move the `will-change` inside the media query.

2025-01-05 07:48 UTC, t-hamano commented on packages/components/src/resizable-box/style.scss
>  	will-change: transform;
```suggestion
	@media not (prefers-reduced-motion) {
		transition: transform 0.1s ease-in;
		will-change: transform;
	}
```

2025-01-05 07:48 UTC, t-hamano commented on packages/components/src/toolbar/toolbar/style.scss
> +			}
Do you know what this animation is intended to do? As far as I've tested, the outline animation when I focus on a button doesn't work.

Maybe we can improve or fix this in a follow-up.

2025-01-06 07:24 UTC, SainathPoojary commented on packages/components/src/toolbar/toolbar/style.scss
> +			}
Hey @t-hamano, to better understand what this animation is doing, I increased the animation duration to 0.5s. Here’s the result.

https://github.com/user-attachments/assets/638db6c7-0f90-49fc-af39-d21e01e7183d

2025-01-06 08:57 UTC, SainathPoojary commented
Hey @t-hamano,

I have implemented all the requested changes and also updated the code with the trunk, Please have a look at your convenience.

Thank you!

2025-01-07 08:36 UTC, t-hamano commented on packages/components/src/toolbar/toolbar/style.scss
> +			}
Thank you! I didn't know there was an animation applied to it.

2025-01-07 08:39 UTC, t-hamano approved these changes
LGTM! All components appear to be correctly standardized.

Before shipping this PR, can you check the following points?

- Move the changelog entry to the correct place. It needs to be in the `Unreleased` section:
  ```markdown
  ## Unreleased

  ### Internal

  -   `Components`: Standardize reduced motion handling using media queries ([#68421](https://github.com/WordPress/gutenberg/pull/68421)).

  ## 29.1.0 (2025-01-02)
  ```
- Rebase this PR so that All CIs pass

2025-01-07 09:46 UTC, SainathPoojary commented
Hey @t-hamano,

I have moved the changelog entry to the correct place now. Previously, I merged trunk into my PR, and I believe all the CI checks are now passing. Would you like me do it again?

Thank you!

2025-01-07 10:01 UTC, t-hamano requested changes
Unfortunately, after testing this PR again, it appears that Storybook is no longer able to build. This is the same issue reported [here](https://github.com/WordPress/gutenberg/pull/68419#issuecomment-2567550864).

I don't know the exact reason yet, but it might be a good idea to merge the Storybook build's CI (#68466) first while we investigate the cause.

2025-01-07 10:21 UTC, t-hamano commented
I was wrong. After running `npm install` on another old branch, I didn't run `npm install` after switching to this branch 😅

In this PR, The StoryBook build is indeed successful. Just to be sure, I tried rebasing this PR on the trunk branch, and it worked just as well.

2025-01-07 10:22 UTC, t-hamano approved these changes

2025-01-07 10:23 UTC, merged