Adding block description settings in preference
WordPress/gutenberg pull request #68435
Opened 2024-12-31 11:51 UTC by benazeer-ben

## What?
Fixes: https://github.com/WordPress/gutenberg/issues/42197

## How?
Added a toggle to the Appearance section in  Preferences modal, which allows you to turn off block descriptions.

## Testing Instructions

- Go to WP admin dashboard.
- Open any page/post in edit mode.
- Add any block, check its description in the editor sidebar.
- Open Preference modal from the Options.
- Turn off/on the `Show block descriptions` option from Appearance section.
- Check the block description based on the settings and verify.

## Screenshots or screencast 

https://github.com/user-attachments/assets/225ea727-5132-4c2c-be9f-77f34059e00a

2025-02-27 06:43 UTC, benazeer-ben commented
Hi Team,

Whenever you have some time, could you please review this PR? I’d really appreciate your feedback.

Thanks in advance!

cc: @t-hamano @carolinan

2025-02-27 07:02 UTC, carolinan approved these changes
Thank you for the ping.
I have tested the functionality and it is working as described.
The text strings; the label and description, also feel suitable to me.

I am personally not sure about this use case.  It also hides the description of the variations, like the explanation for the grid and stack group block variations.
But since it was requested by @richtabor I will assume he still wants this change to go in.

2025-02-28 10:16 UTC, t-hamano commented
Thanks for the PR, @benazeer-ben!

> I am personally not sure about this use case. 

To be honest, I'm not sure how useful this feature would be 😅 Either way, we'll need some design feedback. 

@WordPress/gutenberg-design 

Furthermore, if we do move forward with this feature, we might want to consider whether we need a similar setup for the widget editor, which would need to implement the same functionality separately.

2025-03-11 07:11 UTC, Mamaduka requested changes
I think we should be careful when introducing similar preferences and keep WP's ["Decisions, not options"](https://wordpress.org/about/philosophy/#:~:text=Decisions%2C%20not%20options) philosophy in mind.

* If most block descriptions aren't helpful in the sidebar, maybe we should remove them.
* Alternatively, we could hide them when simplifying editing is enabled.

Thanks again for contributing, @benazeer-ben! For similar enhancement requests, I recommend requesting initial feedback on the issue before moving to implementation.

2025-03-11 08:06 UTC, benazeer-ben commented
> I think we should be careful when introducing similar preferences and keep WP's ["Decisions, not options"](https://wordpress.org/about/philosophy/#:~:text=Decisions%2C%20not%20options) philosophy in mind.

Thanks for the info, @Mamaduka. I will ensure to request initial feedback on any enhancement issue before proceeding with implementation.

Should I close this PR? Please guide me on the next steps.

2025-03-11 08:07 UTC, Mamaduka commented
Yes, let's close this for now. Thanks again, @benazeer-ben!

2025-03-11 08:07 UTC, closed without merging