Update doc to add PHP strategy to register block variations
WordPress/gutenberg pull request #68434
Opened 2024-12-31 10:25 UTC by Sukhendu2002

Issue: https://github.com/WordPress/gutenberg/issues/63182

## What?
This PR updates the Block Editor Handbook under the "Block API Reference > Variations" section to include detailed instructions on how to add block variations via PHP using the get_block_type_variations hook.

### Changes Made:

- Added a new subsection titled "Adding Block Variations from PHP."
- Explained the get_block_type_variations hook and its parameters.
- Included a practical PHP code example demonstrating how to add a custom variation to the core/navigation-link block.

2025-02-17 15:11 UTC, juanmaguitar requested changes

2025-02-17 15:11 UTC, juanmaguitar commented on docs/reference-guides/block-api/block-variations.md
> +function my_custom_navigation_link_variations( $variations, $block_type ) {
I think a better example would be the following one:

```
function my_custom_image_variation( $variations, $block_type ) {
    // Only modify variations for the navigation-link block
    if ( 'core/image' !== $block_type->name ) {
        return $variations;
    }

    // Add a custom variation
    $variations[] = array(
		'name'        => 'wide-image',
		'title'       => __( 'Wide image', 'textdomain' ),
		'description' => __( 'A wide image', 'textdomain' ),
		'scope'       => array( 'inserter' ),
		'isDefault'   => false,
		'attributes'  => array(
			'align' => 'wide', // Identifies the link type as custom
		),
    );

    return $variations;
}
add_filter( 'get_block_type_variations', 'my_custom_image_variation', 10, 2 );
```

As a 'core/image' variation doesn't need to be the children of another to be inserted (as it happens with `core/navigation-link` that can only be inserted inside of a  ´core/navigation´)
Also in the example above there's a visual change that clarifies the use this variation.

2025-02-18 05:54 UTC, Sukhendu2002 commented on docs/reference-guides/block-api/block-variations.md
> +function my_custom_navigation_link_variations( $variations, $block_type ) {
Hey @juanmaguitar, Thanks for the review! I appreciate the clarification. I've updated the example code accordingly to better reflect the correct usage of block variations for core/image.

2025-02-18 09:38 UTC, juanmaguitar approved these changes

2025-02-18 09:41 UTC, juanmaguitar commented
Thank you very much @Sukhendu2002 for working on this.
I have added a tip callout to recommend a very relevant blog post in the WP Developer Blog.
Other than that, it's good to go! 🛳️

2025-02-18 18:33 UTC, merged