Change `Convert to blocks` label
WordPress/gutenberg pull request #6903
Opened 2018-05-22 21:40 UTC by Soean

## Description
Changes `Convert to Blocks` to `Convert to blocks` in the invalid Block warning to match the block settings menu label. This PR fixes 1/3 of #6210 

### InvalidBlockWarning
Before:
<img width="356" alt="bildschirmfoto 2018-05-22 um 22 46 03" src="https://user-images.githubusercontent.com/695201/40391427-7a87daa4-5e18-11e8-85aa-56028a3f5407.png">
After:
<img width="344" alt="bildschirmfoto 2018-05-22 um 23 38 14" src="https://user-images.githubusercontent.com/695201/40391623-3d47ed90-5e19-11e8-897c-def43f2d937f.png">

### Block settings menu:
<img width="268" alt="bildschirmfoto 2018-05-22 um 22 44 07" src="https://user-images.githubusercontent.com/695201/40391429-7df9010e-5e18-11e8-9d71-00dd980cf202.png">

2018-07-05 23:31 UTC, tofumatt requested changes
I'd argue that the lowercase version is the one that should be changed; Blocks can be thought of as a kind of proper noun and there are other spots in your screenshot that capitalise "Block" ("Shared Block" and "Block Settings", for instance).

I think it makes sense to capitalise them, so I would change the one lowercase string and then this should be 🚢

2018-07-11 23:02 UTC, Soean commented
@tofumatt Tanks for the feedback, that seems right. I changed the entry in the Block settings menu to uppercase.

2018-07-18 09:12 UTC, tofumatt approved these changes
Right on, looks good then! Sorry for the delay in looking at this one again 😓

2018-07-18 21:52 UTC, Soean commented
Already fixed in #7882

2018-07-18 21:52 UTC, closed without merging