Grammatical fix
WordPress/gutenberg pull request #6990
Opened 2018-05-28 17:32 UTC by leahkoerper

Remove errant apostrophe in block description

## Description
Removed a grammatically incorrect apostrophe from the Classic Block block description.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

2018-05-29 15:27 UTC, karmatosed commented
@noisysocks as you rightly point out it's meant to say this. For now closing as this is valid a statement.

2018-05-30 19:56 UTC, leahkoerper commented
Done!

2018-06-01 03:46 UTC, noisysocks requested changes

2018-06-01 03:46 UTC, noisysocks commented on core-blocks/freeform/index.js
> +	description: __( 'It\'s the classic WordPress editor and it's a block! Drop the editor right in.' ),
We need to escape the `'` here by inserting a `\` before it:

```js
description: __( 'It\'s the classic WordPress editor and it\'s a block! Drop the editor right in.' ),
```

2018-06-02 15:34 UTC, karmatosed approved these changes

2018-06-04 05:56 UTC, noisysocks approved these changes

2018-06-04 05:56 UTC, merged

2018-06-04 05:56 UTC, noisysocks commented
Thanks @leahkoerper!