Try another approach to fixing the sibling inserter in Firefox
WordPress/gutenberg pull request #7530
Opened 2018-06-25 12:18 UTC by jasmussen

This PR partially fixes #7508. It is an alternate version of #7525, though much the same.

In #7220 we introduced a new behavior for the sibling inserter, which requires a click on the plus in the center as opposed to just clicking between two blocks.

Turns out it was sort of a race condition between onClick and onMouseDown, the latter which fires first. So in a way, the Firefox and Safari behavior of selecting the block (which is selected onMouseDown) as opposed to clicking the sibling inserter was the correct one.

This PR "fixes" it by also making the sibling inserter use onMouseDown. But in addition to this, it uses onClick as well, so it's still keyboardable.

The net effect is that both work, with the added benefit that in Firefox and Safari, the block that you're hovering isn't briefly "selected" when you're clicking.

GIF:

![sibling](https://user-images.githubusercontent.com/1204802/41849815-a14cafbe-7882-11e8-87ef-e3f85e66b1d0.gif)

2018-06-25 12:24 UTC, tofumatt submitted a review, later dismissed
This could be DRY'd up, but since I'll take a shot at getting the focus to work I'll just do that ^_^

2018-06-26 08:01 UTC, youknowriad approved these changes
LGTM 👍 

Maybe we can add a comment clarifying why we need this duplication. Also, do you have any idea if we can replace the parent `onMouseDown` event with `onClick`? This could be more impactful but I wonder why we're using `onMouseDown` in the first place.

2018-06-26 08:02 UTC, youknowriad requested changes
Just noticed the breakage in the e2e tests, we might want to take a look at those ;)

2018-06-26 08:07 UTC, jasmussen commented
Thanks for the fast review, and will look at tests in a second. Just wanted to clarify that I just pushed a change in https://github.com/WordPress/gutenberg/pull/7530/commits/743c21995c96d482f41f65ce837183e4d85fd755 which changes it so the onFocusInserter is attached to onMouseDown as well, and this fixes the issue for Firefox and Safari, without us losing focus. Behold:

![safari](https://user-images.githubusercontent.com/1204802/41897805-a0e0f6ec-7928-11e8-9ae0-f635bdb21a0e.gif)

The issue where the block toolbar briefly appears is still there, but this is an improvement in that it now works as intended.

2018-06-26 08:15 UTC, jasmussen commented
Okay I think the latest two commits might have fixed the e2e tests. Final review?

2018-06-26 08:22 UTC, youknowriad approved these changes

2018-06-26 08:26 UTC, merged

2018-06-29 18:14 UTC, aduth commented
I don't think the changes to `package-lock.json` were intended here? I see local changes anytime I run `npm install`.

2018-06-29 18:17 UTC, aduth commented
See #7641

2018-06-29 18:29 UTC, aduth commented
This is purely a styling issue: #7642