Update/block remove button
WordPress/gutenberg pull request #7543
Opened 2018-06-26 03:29 UTC by talldan

## Description
Addresses #7216, moves the remove icon button to the ellipsis menu as a menu button.

## How has this been tested?
- Added unit tests for 'Remove Block' menu button
- Performed manual tests including removing single and multiple blocks

## Screenshots
![screen shot 2018-06-26 at 11 24 08 am](https://user-images.githubusercontent.com/677833/41887506-8854fd5c-7933-11e8-9928-5a7d31425715.png)

## Types of changes
- Removed old icon button version of remove button
- Altered existing Remove menu button (which still seemed to be present from previous version) to display like other menu buttons
- Added tests for menu button

## Checklist:
- [ x ] My code is tested.
- [ x ] My code follows the WordPress code style.
- [ x ] My code follows the accessibility standards
- [ x ] My code has proper inline documentation.

2018-06-26 16:39 UTC, karmatosed commented
Thanks for working on this @noisysocks. Could you add a seperator using the style used in other drop downs?

![artboard](https://user-images.githubusercontent.com/253067/41926612-c65812e0-7967-11e8-8388-183126b7b894.png)

This visually creates a good divide in actions.

2018-06-27 09:46 UTC, talldan commented
Well, I thought adding a separator would be nice and easy, but there were a few intricacies:

- In the other menu, a `MenuGroup` component is used to separate the menu items. The styling was applied only to that menu's `MenuGroup`s though. I've changed it now so that it applied to all `MenuGroup`s. I had a search in the codebase, and the only thing that it might affect that I'm unsure how to view is something called `PluginSidebarMoreMenuItem` - I guess I'll need some plugins to view that?
- I had to refactor a bit, since the menu items for 'Convert to Regular Block' and 'Delete Shared Block' were actually rendered in one parent component and because of that it was impossible to get a `MenuGroup` around the menu items we wanted. I've extracted the Delete Shared Block into its own component.
- Using `MenuGroup`s in the block settings menu introduces a bit of extra padding. It could be removed using a modifier. Let me know.

Here's a couple of screenshots showing how it looks now:
![screen shot 2018-06-27 at 5 26 49 pm](https://user-images.githubusercontent.com/677833/41966389-93b4cbd8-7a31-11e8-9c13-55afc4e2fe97.png)
![screen shot 2018-06-27 at 5 27 13 pm](https://user-images.githubusercontent.com/677833/41966407-9a95ab7a-7a31-11e8-82c0-5c69b1f05a06.png)

2018-06-27 10:05 UTC, talldan commented
Another very little thing I thought. It feels like when the menu is open, the ellipsis icon button should really not become invisible. In my screenshots above, the popover menu feels like its calling out from nowhere.

2018-06-27 19:40 UTC, karmatosed commented
This looks great and thanks for the hardwork wrangling this @talldan. I agree let's have the ellipsis show.

2018-06-28 00:41 UTC, noisysocks commented
> I've changed it now so that it applied to all MenuGroups. I had a search in the codebase, and the only thing that it might affect that I'm unsure how to view is something called PluginSidebarMoreMenuItem - I guess I'll need some plugins to view that?

You can test the plugins menu by pasting [this snippet](https://gist.github.com/gziolo/e2954aa83aa1f823b2b05ca1660c2223#file-my-plugin-es5-js) (the ES5 version) into your DevTools console. This will add a button into the More menu. See https://github.com/WordPress/gutenberg/pull/6031 for some context on that feature.

2018-06-28 01:12 UTC, noisysocks requested changes
Great work on this! It's looking really really close.

I'm not sure about re-using `MenuGroup` in this way. I support the general idea but there's a few implications:

1. We now have two `<div role="menu">`s nested within a `<div role="menu">` which feels a little weird to me.

<img width="663" alt="screen shot 2018-06-28 at 10 54 08" src="https://user-images.githubusercontent.com/612155/42007262-5b95e386-7ac2-11e8-9806-3d9b99dfc1c4.png">

2. The child `<div role="menu">`s have an `aria-labelledby` attribute which refers to an identifier that doesn't exist. Admittedly, this is probably a bug in `MenuGroup`.

3. Moving the `border-bottom` rule to `MenuGroup` has caused some regressions with `PluginSidebarMoreMenuItem`, like you suspected it would:

<img width="276" alt="screen shot 2018-06-28 at 10 56 16" src="https://user-images.githubusercontent.com/612155/42007323-b3567428-7ac2-11e8-8a71-f201e3762ed0.png">

4. The extra padding—like you said 🙂

---

I notice that we have a `.editor-block-settings-menu__separator` class defined already, so an alternative to `MenuGroup` might be to simply use a div with that class to add the separator line. You can see an example of us doing exactly that in `editor/components/block-settings-menu/block-transformations.js`.

2018-06-28 01:12 UTC, noisysocks commented on editor/components/block-settings-menu/shared-block-delete-button.js
> +export function SharedBlockDeleteButton( { sharedBlock, onDelete, itemsRole } ) {
I like that these components only have one responsibility now 🙂🌈

2018-06-28 02:22 UTC, noisysocks approved these changes

2018-06-28 02:30 UTC, merged

2018-07-03 11:55 UTC, hedgefield commented
LOVE THIS.