Documentation: Expand upon register_block_type usage with dynamic blocks
WordPress/gutenberg pull request #7550
Opened 2018-06-26 16:06 UTC by ckanitz

## Description
We found the doc lacking of some notes regarding `register_block_type` function and `render_callback` feature. To save block-developers some time I added just some lines to avoid 404 and/or 400 errors.

## How has this been tested?
It's a readme file ¯\_(ツ)_/¯

2018-09-13 19:18 UTC, aduth requested changes

2018-09-13 19:18 UTC, aduth commented on docs/blocks/creating-dynamic-blocks.md
> +Because it is a dynamic block it also needs a server component. The rendering can be added using the `render_callback` property when using the `register_block_type` function. Please note, that the `r
- Grammar: The comma after "Please note" can be removed.
- `render_callback` is not the responsibility of the block implementer to be called. Was it intended to be `register_block_type` ?

2018-11-22 09:49 UTC, gziolo commented
@chrisvanpatten - can you double check if it is still relevant?

2019-01-04 11:55 UTC, gziolo commented
I'm closing this PR because of the lack of activity. Thank you for your contribution, feel free to reopen when you resolve all merge conflicts and address feedback shared in the comments.

2019-01-04 11:55 UTC, closed without merging