Update JSDOM to 10.1.x
WordPress/gutenberg pull request #796
Opened 2017-05-16 09:06 UTC by iseulde

2017-05-16 15:27 UTC, aduth requested changes

2017-05-16 15:27 UTC, aduth commented on bootstrap-test.js
> +/* eslint-disable no-var */
We can and should use `const` here.

http://node.green/#ES2015-bindings-const

2017-05-16 15:27 UTC, aduth commented on bootstrap-test.js
> +var JSDOM = require( 'jsdom' ).JSDOM;
Minor: Could assign by destructure:

```js
const { JSDOM } = require( 'jsdom' );
```

2017-05-16 17:23 UTC, iseulde commented on bootstrap-test.js
> +/* eslint-disable no-var */
Huh, strange, I tried this before and it errored.

2017-05-16 17:56 UTC, aduth commented on bootstrap-test.js
> +const { JSDOM } = require(	 'jsdom' );
Tab snuck in instead of space after `require(`

2017-05-17 15:58 UTC, iseulde commented on bootstrap-test.js
> +const { JSDOM } = require(	 'jsdom' );
Whoops.

2017-05-17 15:59 UTC, iseulde commented on bootstrap-test.js
> +const { JSDOM } = require(	 'jsdom' );
I'm surprised eslint didn't catch this.

2017-05-17 17:03 UTC, aduth approved these changes

2017-05-17 17:05 UTC, merged