[Enhancement] Change color of links in gallery block caption
WordPress/gutenberg pull request #8004
Opened 2018-07-17 15:24 UTC by nfmohit-wpmudev

## Description
This PR addresses #7952 which reports the low readability links in image captions in the gallery block against the dark gradient background. This changes the default blue link color to white so that it is readable.

## How has this been tested?
This has been tested by making sure the link color is white so that it is well readable against the dark gradient background, which turns to blue when the link background is changed to white when it is focused.

This was tested in WP 4.9.7, Gutenberg 3.2.0, Apache server with PHP 7.2.0 and MySQL 5.6.34. According to initial tests, the code doesn’t seem to affect any other areas.

## Screenshots 
![pull-7952-min](https://user-images.githubusercontent.com/20284937/42827200-bb9562da-8a07-11e8-9d33-4bce1a929165.gif)

## Types of changes
This PR just adds CSS specific to the gallery block editor which changes the link color to white, and blue when it is focused, i.e. when the background turns white.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

2018-08-08 11:29 UTC, mtias commented on core-blocks/gallery/editor.scss
> +			color: #007FAC;
This could probably be transparent `rgba(0,0,0,0.2)` or something like that.

2018-08-08 18:55 UTC, tofumatt requested changes
Good idea, thanks!

I think the code just needs tweaking. Let me know if you can make the changes @mtias and I suggested, but if not I can make them and merge this 👍

2018-08-08 18:55 UTC, tofumatt commented on core-blocks/gallery/editor.scss
> +			color: #fff;
This should be `$white`, I'd think, just for consistency. 😄

2018-08-08 23:57 UTC, tofumatt commented
You're the best, I was literally just about to open this PR but it's great you got to it. Sorry for the delay! 😄

2018-08-08 23:58 UTC, tofumatt approved these changes

2018-08-08 23:59 UTC, nfmohit-wpmudev commented on core-blocks/gallery/editor.scss
> +			color: rgba(0, 0, 0, 0.2);
@tofumatt I was just about to edit the commit and improve the formatting 😅 Thank you so much ❤️

2018-08-09 00:01 UTC, nfmohit-wpmudev commented
Thank you @tofumatt ❤️ I'm sorry about the delay guys, thank you so much for the review and merge ❤️

2018-08-09 00:07 UTC, tofumatt commented
No worries, thanks so much! 👍

2018-08-09 00:47 UTC, tofumatt commented
I'm getting test failures locally too 😢

I wanted to get this merged but I'm not sure what's up with the failures. I'll have another look tomorrow, sorry.

2018-08-09 04:09 UTC, nfmohit-wpmudev commented
I tried taking a look but am not sure what went wrong. Thanks for looking @tofumatt ❤️

2018-08-09 06:44 UTC, jasmussen commented
There were some tests failing yesterday due what seems like a race condition. See https://wordpress.slack.com/archives/C02QB2JS7/p1533732745000038

2018-08-14 12:13 UTC, merged