Packages: Extract `@wordpress/nux` package
WordPress/gutenberg pull request #8016
Opened 2018-07-18 11:14 UTC by gziolo

## Description
Part of #3955.

This PR extracts new `@wordpress/nux` package.

## How has this been tested?

`npm test` and make sure there are no regressions.

Make sure you can see the tips when you load new post (make sure you have `localstorage` cleared before).

2018-07-18 11:43 UTC, tofumatt commented on packages/nux/README.md
> +The NUX (New User eXperience) module exposes components, and `wp.data` methods useful for onboarding a new user to the WordPress admin interface. Specifically, it exposes _tips_ and _guides_.
❤️

2018-07-18 11:44 UTC, tofumatt requested changes
You should add an eslint rule to the `.eslintrc` that forbids imports from `'nux'` and `'nux/*'`, similar to the other package import rules.

2018-07-19 07:47 UTC, gziolo commented
@tofumatt,  an eslint rule added with f6829aa.

2018-07-19 10:31 UTC, tofumatt commented
> Edit: There was a similar rule already, I updated to use the more common pattern.

Oops, I didn't realise!

2018-07-19 10:32 UTC, gziolo commented
Thre is still some issue with loading CSS file with this config. I'm looking into it.

2018-07-19 14:08 UTC, gziolo commented
663f9d1 fixes the issue with missing CSS files. It's not great but should help us move forward with this one. It's exactly the same approach we took when moving `components` folder in #7640:
https://github.com/WordPress/gutenberg/blob/330a4cf23b3fba073038e4bab041ff612bef09c4/components/index.js

Let's open a follow up PR where we tackle copying CSS files generated by packages build step and add RTL support there, too.

2018-07-19 14:10 UTC, youknowriad approved these changes
LGTM 👍

2018-07-19 14:10 UTC, tofumatt approved these changes

2018-07-20 04:45 UTC, merged

2018-07-20 04:54 UTC, gziolo commented
Opened #8067 to keep track of CSS workaround.