Add an edit button to embed blocks
WordPress/gutenberg pull request #8084
Opened 2018-07-20 14:06 UTC by notnownikki

## Description

Adds an edit button to the embed blocks, so you can change the URL.

## How has this been tested?

Embed some content, click the edit button, change the URL, embed again.

## Types of changes
New feature

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

2018-07-24 11:34 UTC, notnownikki commented
Rebased to pick up the alignment toolbar changes

2018-07-26 10:51 UTC, gziolo commented
Code wise it looks good. However, there is some visual issue which needs to be fixed before we proceed:

![screen shot 2018-07-26 at 12 50 05](https://user-images.githubusercontent.com/699132/43258285-971ae5ca-90d2-11e8-81b6-5d7c0ef35ca0.png)

Browser: Chrome, macOS.

2018-07-26 10:53 UTC, gziolo requested changes
Code wise it looks good. However, there are some visual issues which need to be fixed before we proceed:

![screen shot 2018-07-26 at 12 50 05](https://user-images.githubusercontent.com/699132/43258285-971ae5ca-90d2-11e8-81b6-5d7c0ef35ca0.png)

![screen shot 2018-07-26 at 12 53 05](https://user-images.githubusercontent.com/699132/43258377-df4293fc-90d2-11e8-9bfd-833a9aa8b6bd.png)


Browser: Chrome, macOS.

2018-07-26 10:55 UTC, notnownikki commented
I wonder if this is an issue with mixing `supports` and `BlockControls` in the same block. I'll take a look!

2018-07-26 11:19 UTC, notnownikki commented
Wrapped the edit control in `Toolbar`, seems to fix it. Perhaps I missed something in a past change, I'm sure this used to happen automatically...

2018-07-26 11:34 UTC, gziolo approved these changes
Thanks for fixing, all good after your change. 🚢

2018-07-26 11:58 UTC, merged

2018-08-02 12:28 UTC, mtias commented
Nice small improvement, thanks!