Ensure post_id is sent to the REST API in ServerSideRender component
WordPress/gutenberg pull request #8270
Opened 2018-07-29 01:24 UTC by alexsanford

## Description

Fixes https://github.com/WordPress/gutenberg/issues/8178

This PR adds a `post_id` parameter to the REST API call of the `ServerSideRender` component. This ensures the global `$post` object is set properly. Previously, it was only set when rendering to the frontend, but not when rendering for the API call.

While working on this, we decided that this component, being tied closely to the WordPress REST API, really belongs in the `@wordpress/editor` package. It was moved in this PR, and a deprecated version was added in the original package (`@wordpress/components`) for backwards compatibility.

## How has this been tested?

This was tested locally using a dynamic block that displayed information from the `$post` object, ensuring the post information was rendered properly on the frontend and in the editor using `ServerSideRender`.

An automated test was added to ensure that the parameter is added properly to the URL path.

Also I verified that the current two blocks using `ServerSideRender` (Archives and Latest Comments) still work as expected.

## Types of changes

This change should be a non-breaking enhancement.

That said, I did change the name of the `rendererPathWithAttributes` function to `rendererPath`, and it's technically possible that some 3rd-party code is importing and using that. But I assume that's ok since it's not part of Gutenberg's documented API.

This change also deprecates `wp.components.ServerSideRender` in favor of `wp.editor.ServerSideRender`.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

2018-07-31 10:31 UTC, jorgefilipecosta reviewed
Hi @alexsanford, thank you for working on this issue 👍 I feel we should not use @wordpress/data in @wordpress/components (until now we never did it).
I think a solution could be moving the component to @worpress/editor (with a straightforward deprecation logic on the existing component) or creating a wrapper in @wordpress/editor that injects the post id using withSelect similarly to what happened with editor/utils/media-upload.

2018-08-01 13:13 UTC, alexsanford commented
@jorgefilipecosta Thanks for your comments!

I think that moving this component into `@wordpress/editor` makes a lot of sense given that it's _not_ a generic UI component and it requires the WP API. I'll get that moved over 🙂

2018-08-08 01:16 UTC, alexsanford commented on packages/components/src/server-side-render/index.js
> +import { select } from '@wordpress/data';
@jorgefilipecosta Done! I moved the component to `@wordpress/editor` and created a deprecated version in `@wordpress/components`.

I also updated the PR description to reflect this.

2018-08-08 01:16 UTC, alexsanford commented on packages/components/src/server-side-render/index.js
> + * A wrapper to inject the Post Id.
Done

2018-08-08 01:16 UTC, alexsanford commented
@jorgefilipecosta I addressed the comments above. Note that I also rebased the branch.

2018-08-09 15:22 UTC, danielbachhuber commented
@alexsanford Thanks for taking this on :)

Per my note in the original issue, I think we want to go in a different direction:

> Similar to `editor/utils/media-upload`, we'll want to create a `editor/utils/server-side-render/` wrapper that enriches `ServerSideRender` with `getCurrentPostId()`.

Doing so lets us keep `ServerSideRender` as a generic component, but then also lets us have an enriched component in the editor context.

2018-08-10 01:44 UTC, alexsanford commented
@danielbachhuber but would you say that `ServerSideRender` really is a generic component? I suppose it is in the sense that it could be used outside of the editor. But it seems pretty closely tied to the WordPress API, which is unlike all of the other truly generic components.

In any case, I can put together another PR and we can decide which one we like better 🙂

2018-08-10 11:36 UTC, danielbachhuber commented
> would you say that `ServerSideRender` really is a generic component? I suppose it is in the sense that it could be used outside of the editor. But it seems pretty closely tied to the WordPress API, which is unlike all of the other truly generic components.

Yes, generic in the sense that it can be used outside of the editor. For instance, it will need to be used to preview blocks within the Customize experience (whenever that comes). Your wording is more correct, however.

> In any case, I can put together another PR and we can decide which one we like better 

Sounds good, thanks.

2018-08-13 14:36 UTC, aduth requested changes
I was going to leave a comment about this not being generic component with its consideration of the post ID from editor state, but @danielbachhuber summarized much better than I already.

2018-08-24 14:57 UTC, alexsanford commented
@danielbachhuber Sorry for the delay on this one! I've submitted a new PR (https://github.com/WordPress/gutenberg/pull/9323) so let's continue the conversation over there 🙂 

Closing this one.

2018-08-24 14:57 UTC, closed without merging