Show I
WordPress/gutenberg pull request #8395
Opened 2018-08-02 15:04 UTC by earnjam

## Description

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

2018-08-03 15:29 UTC, earnjam commented
I'm having second thoughts about this method, as modifying the response here might break back compatibility. 

An alternative proposed to core is a `date_floating` flag.

The other possibility is to check if the `date` and `modified` values are identical on a `draft` or `auto-draft`. They should likely only be identical when a true post date hasn't been set yet, but that feels like a potentially invalid assumption (though with very low risk if wrong)

2018-08-06 18:06 UTC, earnjam commented
Updated to use a `date_floating` flag on the REST API response based on discussions on https://core.trac.wordpress.org/ticket/39953

2018-08-06 18:22 UTC, desrosj requested changes
I think the addition of flag makes sense over filtering the response here. Few points:

- There is a closure being used that should become a regular function definition.
- Not sure that `get_post()->post_date_gmt` will _always_ return a proper `WP_Post` object.

2018-08-06 19:28 UTC, earnjam commented
Removed the closure, wasn't thinking there. 🙈 

The `get_callback` function can take a parameter that is an array of values of the post in the REST API response. I used that to pass an ID to the `get_post()` call. That seems safer because if there isn't a post with that ID, then it would have erred out before it got to that point. 

## Quick Summary
Posts that have a status of `draft` or `auto-draft` and do not have a date explicitly set by the user, have a date that is considered floating. Essentially this means a true post date hasn't been set, and will either be set automatically when the post is published or can be set manually by the user. When the date is floating, we should be showing "Publish: Immediately" instead of a date that may not be accurate once published. 

WordPress core traditionally uses a saved value of `0000-00-00 00:00:00` for `post_date_gmt` to determine if the post has a floating date. 

About 18 months ago, we added a shim to force the REST API to return a value for the `date_gmt` because its easier to work with than the localized `date`. See https://core.trac.wordpress.org/changeset/40108

This essentially means there is no way to know for certain that a post has a floating date. Based on some discussions in [trac ticket #39953](https://core.trac.wordpress.org/ticket/39953) it seems like adding a `date_floating` flag is the best solution for backwards compatibility. That's what I've done here.

2018-08-07 15:44 UTC, earnjam commented
I'm not sure why Travis won't update here. I manually re-ran the build and all checks passed: https://travis-ci.org/WordPress/gutenberg/builds/412776921

2018-08-07 15:53 UTC, earnjam commented
@danielbachhuber When you have a minute, can I get your thoughts on this approach since it will require a change to the REST API? See [my last comment above](https://github.com/WordPress/gutenberg/pull/8395#issuecomment-410825440) for a quick summary and related links to trac.

2018-08-07 19:34 UTC, danielbachhuber commented
> When you have a minute, can I get your thoughts on this approach

Ugh, what an awful issue. I've read the Trac ticket and will give it some thought. I think @joehoyle might be at WC Pub contributor day on Friday too.

2018-08-07 20:11 UTC, earnjam commented
Thanks. I don't like the solution for sure, but I'm struggling to come up with a better alternative.

2018-08-17 16:11 UTC, danielbachhuber commented on lib/rest-api.php
> +	register_rest_field( $post_types, 'date_floating', array( 'get_callback' => 'gutenberg_get_date_floating_flag' ) );
Should this be flagged as a read-only field?

2018-08-17 16:12 UTC, danielbachhuber requested changes
I don't love the `date_floating` attribute name, but I don't see a way around it at this point.

Could we get PHPUnit tests added for the behavior of `date_floating`, so we have explicit usage described?

2018-09-16 19:52 UTC, kadamwhite commented
Based on the most recent conversation in https://core.trac.wordpress.org/ticket/39953 I would prefer we move forward with the solution of inferring this flag when the modified date is the same as the post date, and update the `PostScheduleLabel` component accordingly. I have proposed a small patch for the Gutenberg side of things in that ticket, which I will prepare as a separate PR.

2018-09-17 13:58 UTC, kadamwhite commented
I propose #9967 as an alternative approach which should supersede this PR.

2018-09-26 10:53 UTC, earnjam commented
Closing this in favor of #9967

2018-09-26 10:53 UTC, closed without merging