Fix unrecognised `forwardedRef` prop
WordPress/gutenberg pull request #8570
Opened 2018-08-06 03:28 UTC by noisysocks

## Description
Fixes a warning I noticed while testing https://github.com/WordPress/gutenberg/pull/8556. 

`withGlobalEvents` was setting `forwardedRef` on the wrapped component, which caused an `Unrecognised forwardedRef prop` React warning in `FocusableIframe`.

Also corrects some incorrect indentation in some embedded JavaScript.

## How has this been tested?
3. Click to add a new block
4. Select `Custom HTML` block
5. Click `Preview` button

No errors or warnings should appear in the console.

2018-08-06 12:24 UTC, nerrad reviewed
I think it *might* be better to remove the `forwardedRef` prop on any leaf components rather than in the HOC.

2018-08-06 16:05 UTC, aduth requested changes

2018-08-06 16:05 UTC, aduth commented on packages/compose/src/with-global-events/index.js
> +						{ ...omit( this.props, [ 'forwardedRef' ] ) }
Performance-wise, we could probably benefit by just passing the original props as a standalone prop value from within `forwardRef`:

```js
 		return forwardRef( ( props, ref ) => {
 			return <Wrapper ownProps={ props } forwardedRef={ ref } />;
 		} );
```

For example, we do this with `withSelect`:

https://github.com/WordPress/gutenberg/blob/4fd5c20af4a8a46c92048574e363b07977aa0f3f/packages/data/src/components/with-select/index.js#L127

2018-08-06 16:06 UTC, aduth commented
>I think it might be better to remove the forwardedRef prop on any leaf components rather than in the HOC.

How would this be implemented?

2018-08-06 16:08 UTC, nerrad commented
> How would this be implemented?

Your suggestion here: https://github.com/WordPress/gutenberg/pull/8570#pullrequestreview-143659784 would make my suggestion moot :).

2018-08-07 00:40 UTC, aduth approved these changes
👍

2018-08-07 01:23 UTC, merged