Show drop zone background when file is dragged
WordPress/gutenberg pull request #8752
Opened 2018-08-09 05:44 UTC by Stoyan0v

## Description
This PR fixes #8115 . The drop zone background when it has `is-dragging-over-element` class name, but is overridden by another another selectors `is-close-to-top, is-close-to-bottom` which remove the background. The issue has been introduced the following PR: #6040, which fix the following issue:
#6035. My initial idea was to just remove the background from `is-close-to-top, is-close-to-bottom` classes, but this will bring back the background when a block is dragged over another block. So I decided to use the `is-dragging-file` class, which is added only when a files is dragged over the block.

## How has this been tested?
* I dragged a file over a block and the background was visible.
* I dragged a block over another block. but this time the background was not visible, which was expected.

## Types of changes
Bug fix.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

2018-08-10 19:58 UTC, earnjam commented
Thanks for the PR @Stoyan0v!

This looks good to me. And thanks for the research on the original reason for the change. That helps prevent us from bringing that problem back while fixing this one!

Screencaps from testing:
![drag-drop](https://user-images.githubusercontent.com/4267290/43978641-f4e78958-9cb5-11e8-9978-621bf8db7ffe.gif)

![block-drag](https://user-images.githubusercontent.com/4267290/43978668-094bc576-9cb6-11e8-99f1-cb8239d7e819.gif)

2018-08-10 19:58 UTC, earnjam approved these changes

2018-08-10 20:15 UTC, earnjam requested changes

2018-08-10 20:15 UTC, earnjam commented on packages/components/src/drop-zone/style.scss
> +			background-color: rgba( $blue-dark-900, 0.8 );
Can you remove the whitespace inside the parenthesis on this line? It's tripping up the tests and causing travis to fail. 
![image](https://user-images.githubusercontent.com/4267290/43979365-807b511e-9cb8-11e8-891c-efe55ea87b14.png)

2018-08-15 17:23 UTC, earnjam approved these changes

2018-08-15 17:33 UTC, earnjam commented on packages/components/src/drop-zone/style.scss
> +			background-color: rgba( $blue-dark-900, 0.8 );
We just had some discussions about the discrepancies between the WPCS whitespace rules in PHP and CSS the other day. I get confused myself 😄

2018-08-15 17:35 UTC, merged

2018-08-16 16:49 UTC, karmatosed commented
@earnjam whilst I understand the speed to get this in, it should have had a design review. Let's make sure in the future we get anything like this through the proper process over just merge. Totally understand the efficiency but visually this should have gone through iterations. We can now need to skip back and do those.

2018-08-16 19:27 UTC, earnjam commented
@karmatosed I'm sorry! I thought this was just a bug/regression in the existing design and I couldn't find any indications that the existing design was problematic. I absolutely would have asked for design review if I thought it was making any changes to existing designs. 

I'll err on the side of anything visual needing design review going forward. 😅