Pad menus
WordPress/gutenberg pull request #8758
Opened 2018-08-09 07:58 UTC by jasmussen

This adds padding to the block more menu. At first glance this will look like much, but in fact it simply makes it the same padding as that of every other popover.

This starts work on an aspect of #7433. 

Screenshots:

<img width="341" alt="screen shot 2018-08-09 at 09 57 08" src="https://user-images.githubusercontent.com/1204802/43886033-cf3afdc6-9bba-11e8-80ee-bd313f87c0e9.png">

<img width="309" alt="screen shot 2018-08-09 at 09 57 12" src="https://user-images.githubusercontent.com/1204802/43886035-d05ab6d8-9bba-11e8-97ef-7e1c2f6965c6.png">

2018-08-09 08:16 UTC, jasmussen commented
The padding was actually 11px, now that's compensated for.

Also sort the Edit as HTML button at the end of the first list. See #7433

<img width="493" alt="screen shot 2018-08-09 at 10 15 17" src="https://user-images.githubusercontent.com/1204802/43886829-440fda34-9bbd-11e8-923d-ffa58b0448b0.png">

2018-08-09 16:55 UTC, SuperGeniusZeb commented
The mockups in #7433 show <kbd><samp>Edit as HTML</samp></kbd> coming _before_ <kbd><samp>Add to Reusable Blocks</kbd>.

2018-08-10 07:05 UTC, talldan requested changes
This looks really nice! Just need to sort out the white-space issues.

2018-08-10 07:05 UTC, talldan commented on packages/editor/src/components/block-settings-menu/style.scss
> +		margin-right: -$item-spacing + $border-width;
Shame we have to use negative margin, but I can't think of a better way.

2018-08-10 07:13 UTC, jasmussen commented
Good catch Zeb, sorted again:

<img width="531" alt="screen shot 2018-08-10 at 09 11 59" src="https://user-images.githubusercontent.com/1204802/43943919-8a64d834-9c7d-11e8-965d-65084fa29333.png">

2018-08-10 07:13 UTC, jasmussen commented on packages/editor/src/components/block-settings-menu/index.js
> +							) }							<div className="editor-block-settings-menu__separator" />
I think I inadvertently fixed this in the rebase. Thanks.

2018-08-10 07:21 UTC, talldan approved these changes

2018-08-10 08:14 UTC, merged