Add a filter for the reusable block id
WordPress/gutenberg pull request #8912
Opened 2018-08-13 09:15 UTC by brucepearson

## Description
Add a filter so that plugins and themes can filter the reusable block id and return a different block.

## Why is this needed.
Plugins may want to display a different reusable block in some situations. Eg. WPML allows you to translate the reusable block. When rendering the page that contains the reusable block WPML can detect the current language and select the appropriate reusable block to display. 

## How has this been tested?
This has been tested with WPML using the follow code example.

```
add_filter( 'gutenberg_reusable_block_id', 'gutenberg_reusable_block_id_filter' );
function gutenberg_reusable_block_id_filter( $block_id ) {
   return icl_object_id( $block_id, 'wp_block', true );
}
```

## Types of changes
Add a new filter

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

2018-08-15 03:59 UTC, gziolo commented
I noticed that this proposal doesn’t contain any documentation - both inline and general guidelines in the handbook how to use this hook.

2018-08-15 05:33 UTC, noisysocks commented
Cool suggestion—I think it makes sense.

I'm wondering though if we should make this more general-purpose by passing the filter the `$ref` and having it return the HTML that should be rendered. 

> I noticed that this proposal doesn’t contain any documentation - both inline and general guidelines in the handbook how to use this hook.

Yes, we'll need to document this.

2018-08-15 09:06 UTC, brucepearson commented
@noisysocks I've added inline documentation for the filter. I couldn't find where Gutenberg hooks are documented in the handbook.

2018-10-20 08:03 UTC, gziolo commented
Sorry, I missed that! Yes, we can include it. Actually it might be very useful. 

Let’s add some docs with ESNext/ES5 examples about the filter in this document:
https://github.com/WordPress/gutenberg/blob/master/docs/extensibility/extending-blocks.md.

I also agree with the suggestion from @noisysocks that it would be neat to include the html as a param in the filter for some more advanced use cases.

2018-10-20 08:11 UTC, gziolo commented
@pento @mcsf what’s the process for PHP changes now when 5.0 beta process starts?

2018-10-21 05:04 UTC, pento commented
PHP in the `block-library` will continue to be maintained in Gutenberg, as changes are usually closely tied to JS changes, too. Updates land in core by updating the version in core's `package.json`, running `npm install`, then `npm webpack:dev`.

2018-11-04 07:20 UTC, pento requested changes
I'm fine with this going in, let's just change the filter name, as it'll be going straight into Core.

2018-11-04 12:10 UTC, pento commented
It'd be useful if this filter also had the post ID that the reusable block is being embedding in.

2018-11-05 08:59 UTC, andreasciamanna commented on packages/block-library/src/block/index.php
> +	$reusable_block_id = apply_filters( 'gutenberg_reusable_block_id', $attributes['ref'] );
Done

2018-11-05 09:01 UTC, andreasciamanna commented
@pento 

> It'd be useful if this filter also had the post ID that the reusable block is being embedding in.

Done.

I wasn't sure if I should have used `global $post` or, as I did here, `get_post()`.  
They should both achieve the same result, but I've used the latter more for readability purposes.

2018-11-16 10:34 UTC, gziolo commented
It looks like a more general solution proposed in #11730 could work here, too. The only change that would need to be applied is that the other proposed filter would have to take `$post_id` as one of the params.

2019-01-23 09:03 UTC, gziolo commented
Closing in favor of https://core.trac.wordpress.org/ticket/45451.

2019-01-23 09:03 UTC, closed without merging

2019-01-23 09:11 UTC, gziolo commented
Patch has landed in `trunk`:
https://core.trac.wordpress.org/changeset/44553

It should be released next month in WordPress 5.1.