Add has_block function and unit tests for it
WordPress/gutenberg pull request #9058
Opened 2018-08-16 19:26 UTC by andreilupu

## Description
A refresh for #8340 

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [x] My code has proper inline documentation.

2018-08-16 21:26 UTC, obenland requested changes

2018-08-16 21:26 UTC, obenland commented on lib/register.php
> +	if ( ! has_blocks( $post ) ) {
This check could probably moved to the top of the function. If there are no blocks, getting the post before hand seems superfluous.

2018-08-16 21:55 UTC, obenland approved these changes

2018-08-16 21:55 UTC, obenland commented
@mtias Looks like this is too late for 3.6?

2018-08-17 02:30 UTC, pento commented
Wonderful, thanks @andreilupu!

I think we can safely put this into 3.6, it's a useful addition.

2018-08-17 02:31 UTC, merged