[WIP] Introduce get_blocks function
WordPress/gutenberg pull request #9208
Opened 2018-08-21 18:31 UTC by obenland

See #8352.

## Description
A convenient wrapper for `gutenberg_parse_blocks()` that can be used as a template tag as well, complimentary to `has_blocks()` and `has_block()`.

## How has this been tested?

## Screenshots 

## Types of changes

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

2018-08-21 21:39 UTC, obenland commented
I was thinking about a complimentary `get_block()` function, but given how block type instances are not necessarily unique within a post, using the singular in the function name didn't seem to make much sense.

Maybe a `get_blocks( $block_type, $post )` to return an array of all blocks of a specific type? Not sure how useful that would be. It could also be argued that devs could filter the return value of `get_blocks()` themselves, which is basically what that would do anyway. Thoughts?

2018-08-22 12:32 UTC, danielbachhuber requested changes

2018-08-22 12:32 UTC, danielbachhuber commented on lib/register.php
> + * @param int|string|WP_Post|null $post Optional. Post content, post ID, or post object. Defaults to global $post.
I think this is a little too magical for me. Accepting four potential variable types that each mean different things is more confusing than it is helpful.

Given `gutenberg_parse_blocks()` already exists for parsing blocks from a string, I'd suggest `get_blocks()` should accept a `WP_Post` object, `$post_id` Post ID, or null (which would default to the global `$post`).

2018-08-22 12:35 UTC, danielbachhuber commented
> Maybe a `get_blocks( $block_type, $post )` to return an array of all blocks of a specific type? Not sure how useful that would be. It could also be argued that devs could filter the return value of `get_blocks()` themselves, which is basically what that would do anyway. Thoughts?

What about a `gutenberg_parse_block_types( $block_type, $content )` ?

2018-08-22 12:47 UTC, aduth commented
>What about a `gutenberg_parse_block_types( $block_type, $content )` ?

I'm a bit hesitant on this since "block type" has a special distinct meaning from the "block"; it's the term we use to describe its abstract definition (`register_block_type`). That sounds not like what we're proposing to return from a `gutenberg_parse_block_types` function, which might be more appropriately named something like `gutenberg_parse_blocks_of_type`

2018-08-22 12:49 UTC, aduth commented
Re: `gutenberg_parse_blocks` vs. `get_blocks`, we should consider what we want the landscape of final available functions to be. We could collapse what we have as `gutenberg_parse_blocks` (eventually `wp_parse_blocks`?) _into_ `get_blocks` if we want it to be an overloaded function returning a parsed result. And if we don't, then I think we should make clearer that `get_blocks` is specific to certain usages (e.g. `get_post_blocks`).

2018-08-22 12:53 UTC, danielbachhuber commented
If we want to have some function that magically references the global `$post`, I think it should be separate from the function that parses a string for blocks.

Other than that, I don't have strong opinions about naming. PHP and WordPress have inconsistent naming patterns as it is, so I imagine we could find prior art in any direction we look. I'd prefer to delegate naming to one or two people over making it a group decision.

2019-01-31 18:09 UTC, gziolo commented
This PR is no longer relevant to Gutenberg plugin now that all the surrounding logic were moved to WordPress core. I'm closing this PR, however, we might still want to open a ticket against WordPress core. What do you think?

2019-01-31 18:09 UTC, closed without merging