Components: Adding a generic token field component
WordPress/gutenberg pull request #924
Opened 2017-05-29 14:23 UTC by youknowriad

In order to do #854 we need a generic Tags Input (with auto-complete...). Building such a component from scratch is not an easy task. So I shamelessly copied the component from Calypso and I adapted it to match our guidelines. It's a lot of code, so I'd appreciate help reviewing this component.

<img width="288" alt="screen shot 2017-05-29 at 15 19 48" src="https://cloud.githubusercontent.com/assets/272444/26553246/b8bcb76e-4482-11e7-9384-3b0ac950f3ca.png">

In order to test it. I'm using it in the sidebar with static values.
In a follow-up PR. I'll try to use it to update the post tags.

2017-05-29 17:43 UTC, nylen commented
I do not think we should merge this without automated tests.  Fortunately [they already exist](https://github.com/Automattic/wp-calypso/tree/master/client/components/token-field/test) and we now have a PR to add component tests in this repository (#926).

Can we / should we remove some of the unneeded functionality here like a token's `status`?

2017-05-30 09:00 UTC, youknowriad commented
> Can we / should we remove some of the unneeded functionality here like a token's status ?

Sure we can, I don't know if we should? Couldn't this be useful somewhere else?

2017-05-30 09:48 UTC, youknowriad commented
Tests are failing on CI but passing locally but the error is weird.

2017-05-31 11:30 UTC, youknowriad commented
Tests are passing again. I'll appreciate some 👀 here. Thanks

2017-05-31 14:06 UTC, aduth requested changes
When opening Post Settings on this branch, the page goes blank. I don't see the same on master.

2017-05-31 14:46 UTC, youknowriad commented
@aduth Yep, it was related, should be fixed now.

2017-05-31 14:48 UTC, aduth approved these changes

2017-05-31 17:00 UTC, merged

2017-05-31 20:47 UTC, aduth commented
I forgot how slow these tests were, but we're now seeing Travis timeouts in unrelated branches because they take too long. We can bump timeouts, but I'd almost rather remove the tests before allowing ourselves to succumb to accepting slow tests.

2017-06-01 17:41 UTC, nylen commented
Even though these tests use `enzyme`, they look more like "integration tests" than "unit tests" and perhaps should not be run on every build.  They might fit better in another category of tests (https://github.com/WordPress/gutenberg/issues/939#issuecomment-305260781).  However, `TokenField` has a long history of weird bugs and these tests are pretty important.