Components: Improve empty elements filters in Slot implementation
WordPress/gutenberg pull request #9371
Opened 2018-08-27 11:40 UTC by gziolo

## Description
Raised by @aduth in https://github.com/WordPress/gutenberg/pull/5952#discussion_r212715645:

> Why do we filter here?

> To get rid of empty elements. Some fills render nothing based on Redux state. If you want to prevent rendering a slot wrapper it it has no fill which render something this is the way to go. In retrospective, I think this could be also done outside. Should we move it out or improve here and add some comments?

> Comments would be good.
> It was also strange to me that we filter only if the children is passed as a function, but not otherwise.
> Also, `filter( Boolean )` doesn't sound like a sufficient way to imitate React's treatment of "empty". For example, a child of 0 would be omitted here, but is a valid / non-empty child to render.

This PR adds `isEmptyElement` helper method and adds proper inline documentation explaining why it is used with `fills`.

## How has this been tested?
`npm test`

## Types of changes
Refactoring.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style. 
- [x] My code follows the accessibility standards. 
- [X] My code has proper inline documentation.

2018-08-27 11:58 UTC, gziolo commented on packages/components/src/slot-fill/utils.js
> +export const isEmptyElement = ( element ) => {
We use it only here, if there is going to be another use case, we could think to move it `@wordpress/element`.

2018-09-05 10:10 UTC, talldan requested changes
Looks like a nice improvement. The only edge-case I can think of is `isEmptyElement( new String( '' ) )`, which I think would return false. It'd be pretty easy to fix that using the same approach used with arrays.

Would also be great to add jsdocs for isEmptyElement

2018-09-05 15:17 UTC, talldan approved these changes

2018-09-05 15:18 UTC, talldan commented
Great - I'm happy with those changes.

> In general, both should never happen

🤞 hopefully!

2018-09-05 16:39 UTC, merged

2018-09-05 16:40 UTC, aduth commented
This pierces the abstraction of `@wordpress/element`. Should not this have been added there instead?

2018-09-05 18:08 UTC, aduth commented
>This pierces the abstraction of `@wordpress/element`. Should not this have been added there instead?

I suppose it's okay to allow this to be disregarded as it relates to a 3.8 RC, only because it's not part of a public API.

2018-09-06 06:50 UTC, gziolo commented
> I suppose it's okay to allow this to be deferred as it relates to a 3.8 RC, only because it's not part of a public API.

I left my own comment about it https://github.com/WordPress/gutenberg/pull/9371#discussion_r212950080 where I assumed we don't want to expose it in `@wordpress/element` until we have another use case for it.

2018-09-06 16:41 UTC, aduth commented
In that case I'd rather just [flag it as experimental](https://github.com/WordPress/gutenberg/blob/master/docs/reference/coding-guidelines.md#experimental-apis).

My main issue is that, as far as anything in `components` is concerned, there should be zero awareness of what value an `element` holds. There is no commitment guaranteed by `@wordpress/element` that this shape is to remain, and will be hard to account for if ever changed.