Change the Gutenberg release process
WordPress/gutenberg pull request #9573
Opened 2018-09-03 12:57 UTC by jdevalk

## Description
As more and more people are testing Gutenberg, we must make sure we improve the stability of the Gutenberg project. In order to do that, we should switch from just releasing `master` every week or two weeks to a system where we have a slightly longer RC period. 

I therefore propose we switch to a system where every time we do a release, we create a new release branch for the next release, and treat that as an RC. To do this we need a `develop` branch as the default, and a `master` branch as the current released version. The following describes the workflow and ground rules I think would work well for this:

## Workflow

On the day of a release:

- Create the release branch for the next release, in the format of `release/1.x.0`.
- Set the release date on the milestone for the next release. 
- Create the milestone for the release _after_ the next release, so if you're creating the release branch for 3.8, you create the milestone for 3.9. 
- The release branch becomes the RC for the next release, allowing developers that build integrations to test with this RC.
- The release branch is committed to Subversion `trunk` on wordpress.org's SVN so translators can already start translating.
- Releases are merged back into the `master` and `develop` branch as soon as they're released, so `master` always reflects the current released state.

## Ground rules

- Only bug fixes for regressions are merged on the release branch, everything else goes into the `develop` branch.
- Releases can, if needed, go out _after_ their planned date, but never before, because developers that build integrations need to be able to do planning on when they can test.
- For reasons of stability, every public API is deprecated with a 4 week notice period.
- Merges should be milestoned to the correct milestone on merge.

## Steps to take

* [ ] Update `release.md` with the new workflow (in this pull).
* [ ] Remove the branch check from `build-plugin-zip.sh` as it no longer works with this workflow (in this pull).
* [ ] Add a checkbox to the `Bug_report.md` issue template to check whether the issue is a regression  (in this pull).
* [ ] Create a new `develop` branch, and make it the default.
* [ ] Protect the `master` branch and only allow commits / merges by the people that do releases.
* [ ] Create a new `release/x.x` branch for every new release.

2018-09-03 14:01 UTC, youknowriad commented
Thanks for the PR, we definitely need something like that going forward. We did a "Call for testing" before releasing during the last release but extending its duration while allowing people to continue working/merging PR in the meantime seems like a good improvement.

Instead of changing how we work with `master` and making a new `develop` default branch, I'd suggest keeping master as is and create a `release` branch. Which means:

 - `master` is the equivalent of the `develop` branch proposed
 - `release` is the equivalent of the `master` branch proposed

This has the advantage of not requiring us to update the 238 open PRs :) and not changing too much the workflow of the current contributors.

2018-09-03 14:03 UTC, tofumatt requested changes
I see the value in creating *release candidate* ("RC") versions of Gutenberg that are shipped to a subset of users willing to test an "RC" or "Beta" version of the plugin for about a week before we ship it to more users. That part makes sense to me 👍

There are issues with the proposed approach, though:

1. idiomatically, `master` is the development branch in many repositories and we should try to preserve `git`/GitHub/JS/node idioms
2. Creating a `3.9-rc` tag should do the trick, and new releases can be made off that tag with `git cherry-pick`. `3.9-rc1`, `3.9-rc2` is easier to manage than the several branch/development changes proposed and is much more idiomatic in the Node space. See: https://addons.readthedocs.io/en/latest/server/push-duty.html for how Mozilla's Add-ons web properties handle this process. It works great and is frictionless. Fixes get merged to `master` and cherry-picked to release tags. It's very easy and cuts down on branch maintenance.

The `rc` tags should be shipped out to users willing to participate in "beta-testing" or "release-testing" Gutenberg. This would likely be in the form of a separate, "beta"/RC plugin that would get updated with new RC tags.

2018-09-03 14:06 UTC, tofumatt commented
> Instead of changing how we work with master and making a new develop default branch, I'd suggest keeping master as is and create a release branch. Which means:

Further to that, as mentioned, I think not maintaining a separate branch but simply cherry-picking any hotfixes and creating new `rc` tags is a simpler workflow that is more idiomatic to other software projects using git. This isn't SVN, we don't need to maintain long-running branches when we can just cherry-pick commits that need to go in a release. Tracking them somewhere is straightforward and I think easier than maintaining a long-running branch. 🤷‍♂️

2018-09-03 14:10 UTC, youknowriad commented
> Further to that, as mentioned, I think not maintaining a separate branch but simply cherry-picking any hotfixes and creating new rc tags is a simpler workflow that is more idiomatic to other software projects using git.

Yes, this is an alternative too, I don't mind it :). The important part like mentioned is to keep the PRs merging to `master`

2018-09-03 14:58 UTC, jdevalk commented
@tofumatt I honestly think cherrypicking in times when there is a lot of development is a waste of time, this solution is far simpler and allows for more automation later on. 

@youknowriad's on the naming of branches is fine with me, I don't really have a strong opinion on any of that and can see the advantage in not having to change those pull requests.

2018-09-03 15:13 UTC, tofumatt commented
As someone who has done a few Gutenberg releases I find cherry-picking easier with fewer moving parts.

It allows us to ship only stability fixes with things found after the release candidate is shipped and avoids a branch we need to target and then merge back into `master`. It means `master` gets our fixes right away and then we just send them to a new RC.

If you mean cherry-picking many fixes is time-consuming: it's not. Cherry-picking every commit and releasing a new RC constantly would be, but doing a cherry-picked release once a day isn't a huge bother.

Additionally: @gziolo mentioned that if we create some e2e tests around popular plugins and target them against our RC, we could probably be quite aware of breakage in advance, which'd be cool.

2018-09-05 13:11 UTC, atimmer commented
Maybe it is good to highlight that the proposed system is not new, but an adapted version of [git-flow](https://nvie.com/posts/a-successful-git-branching-model/).

2018-09-05 13:16 UTC, tofumatt commented
Yes, I recognised it as such 😄

While that system clearly works for some, I find it to be extra admin work and would prefer to avoid long-running branches.

@mtias mentioned soon we'll have multiple layers of testing:

> We’ll probably have to figure out multiple layers of testing, as we’d have:
> - 5.0 betas, stable, and bug fixes.
> - 5.1 additions and cycle.
> - Phase 2 customization and ongoing Gutenberg plugin.

Feature flags and shipping certain features in master but not the release tags would help us and be useful in other contexts too, more than maintaining extra branches and increasing cognitive overhead for non-releasing developers (eg *most* of the contributors on the project).

2018-09-05 14:23 UTC, closed without merging