RichText Native: Adds onEnter callback and function placeholder.
WordPress/gutenberg pull request #9671
Opened 2018-09-06 16:55 UTC by diegoreymendez

## Description

This PR adds an onEnter callback property to the native implementation of RichText.

## How has this been tested?

Tested in `gutenberg-mobile`.  There's no logic yet but I tested the callback is being called properly.

## Types of changes

Adds an `onEnter` callback property to the native implementation of RichText.
Adds a placeholder method and binds it to the callback.
Adds a console log that's printed whenever the callback is executed.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style. 
- [ ] My code follows the accessibility standards. 
- [ ] My code has proper inline documentation.

2018-09-06 20:51 UTC, SergioEstevao commented
@diegoreymendez don't you need a branch/PR on gutenberg-mobile that refers to this and to the updated version of react-aztec repo?

2018-09-06 21:47 UTC, diegoreymendez commented
@SergioEstevao - You're right.  The PR is here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/136

2018-09-10 14:58 UTC, SergioEstevao commented on packages/editor/src/components/rich-text/index.native.js
> +	onEnter( event ) {
You need to remove the parameter here, now that you update the onEnter interface on the RN-Aztec repo.

2018-09-10 14:58 UTC, SergioEstevao requested changes
Just need to update to the latest API for the onEnter event.

2018-09-10 15:09 UTC, diegoreymendez commented
@SergioEstevao - My bad... I had made the changes in the submodule but failed to push them properly.  It's not updated.

2018-09-13 15:11 UTC, diegoreymendez commented
@SergioEstevao - This is ready for another look.

2018-09-13 15:26 UTC, SergioEstevao approved these changes
Good work.

2018-09-13 15:28 UTC, merged